import type { SpotlightStatsFighter } from "../../../src/features/picks/spotlightContent.ts";

export type UfcStatsSnapshotFighter = Omit<SpotlightStatsFighter, "fighterSlug">;

// Canonical checked-in UFCStats snapshot for fighters on the card currently
// eligible for owner-authored Spotlights. Values are copied from UFCStats
// profiles so Spotlight creation does not depend on UFCStats uptime.
const fighters: Record<string, UfcStatsSnapshotFighter> = {
  "anthony hernandez": {
    name: "Anthony Hernandez",
    record: "15-3-0 (1 NC)",
    dob: "1993-10-18",
    height: "6' 0\"",
    reach: "75\"",
    stance: "Orthodox",
    slpm: 4.57,
    strikingAccuracy: 60,
    sapm: 3.1,
    strikingDefense: 51,
    takedownAverage: 5.88,
    takedownAccuracy: 48,
    takedownDefense: 68,
    submissionAverage: 1.6,
  },
  "gregory rodrigues": {
    name: "Gregory Rodrigues",
    record: "19-6-0",
    dob: "1992-02-17",
    height: "6' 3\"",
    reach: "75\"",
    stance: "Orthodox",
    slpm: 5.53,
    strikingAccuracy: 51,
    sapm: 4.78,
    strikingDefense: 50,
    takedownAverage: 1.9,
    takedownAccuracy: 34,
    takedownDefense: 75,
    submissionAverage: 0.4,
  },
  "roman dolidze": {
    name: "Roman Dolidze",
    record: "15-5-0",
    dob: "1988-07-15",
    height: "6' 2\"",
    reach: "76\"",
    stance: "Orthodox",
    slpm: 3.19,
    strikingAccuracy: 41,
    sapm: 3.71,
    strikingDefense: 48,
    takedownAverage: 1.16,
    takedownAccuracy: 28,
    takedownDefense: 32,
    submissionAverage: 0.7,
  },
  "reinier de ridder": {
    name: "Reinier de Ridder",
    record: "21-4-0",
    dob: "1990-09-07",
    height: "6' 4\"",
    reach: "78\"",
    stance: "Southpaw",
    slpm: 2.47,
    strikingAccuracy: 48,
    sapm: 2.36,
    strikingDefense: 47,
    takedownAverage: 2.56,
    takedownAccuracy: 10,
    takedownDefense: 40,
    submissionAverage: 0.6,
  },
  "serghei spivac": {
    name: "Serghei Spivac",
    record: "18-6-0",
    dob: "1995-01-24",
    height: "6' 3\"",
    reach: "78\"",
    stance: "Orthodox",
    slpm: 3.57,
    strikingAccuracy: 47,
    sapm: 4.23,
    strikingDefense: 52,
    takedownAverage: 3.82,
    takedownAccuracy: 59,
    takedownDefense: 63,
    submissionAverage: 0.5,
  },
  "vitor petrino": {
    name: "Vitor Petrino",
    record: "14-2-0",
    dob: "1997-08-28",
    height: "6' 2\"",
    reach: "77\"",
    stance: "Orthodox",
    slpm: 3.24,
    strikingAccuracy: 48,
    sapm: 2.71,
    strikingDefense: 51,
    takedownAverage: 2.6,
    takedownAccuracy: 46,
    takedownDefense: 79,
    submissionAverage: 0.7,
  },
  "kennedy nzechukwu": {
    name: "Kennedy Nzechukwu",
    record: "14-6-1",
    dob: "1992-06-13",
    height: "6' 5\"",
    reach: "83\"",
    stance: "Southpaw",
    slpm: 4.96,
    strikingAccuracy: 46,
    sapm: 4.58,
    strikingDefense: 51,
    takedownAverage: 0.5,
    takedownAccuracy: 45,
    takedownDefense: 80,
    submissionAverage: 0.2,
  },
  "shamil gaziev": {
    name: "Shamil Gaziev",
    record: "14-3-0",
    dob: "1990-02-10",
    height: "6' 4\"",
    reach: "78\"",
    stance: "Orthodox",
    slpm: 2.94,
    strikingAccuracy: 46,
    sapm: 4.92,
    strikingDefense: 45,
    takedownAverage: 1.06,
    takedownAccuracy: 33,
    takedownDefense: 83,
    submissionAverage: 0.3,
  },
  "kody steele": {
    name: "Kody Steele",
    record: "8-1-0",
    dob: "1995-04-21",
    height: "5' 9\"",
    reach: "71\"",
    stance: "Orthodox",
    slpm: 3.85,
    strikingAccuracy: 33,
    sapm: 6.2,
    strikingDefense: 52,
    takedownAverage: 1.07,
    takedownAccuracy: 25,
    takedownDefense: 100,
    submissionAverage: 0.5,
  },
  "gauge young": {
    name: "Gauge Young",
    record: "11-3-0",
    dob: "2000-07-14",
    height: "5' 9\"",
    reach: "70\"",
    stance: "Orthodox",
    slpm: 6.32,
    strikingAccuracy: 52,
    sapm: 5.12,
    strikingDefense: 49,
    takedownAverage: 0.75,
    takedownAccuracy: 30,
    takedownDefense: 76,
    submissionAverage: 0,
  },
  "carli judice": {
    name: "Carli Judice",
    record: "6-2-0",
    dob: "1999-03-02",
    height: "5' 7\"",
    reach: "68\"",
    stance: "Southpaw",
    slpm: 9.32,
    strikingAccuracy: 50,
    sapm: 6.62,
    strikingDefense: 57,
    takedownAverage: 0.52,
    takedownAccuracy: 25,
    takedownDefense: 80,
    submissionAverage: 0,
  },
  "jeisla chaves": {
    name: "Jeisla Chaves",
    record: "8-0-0",
    dob: "1997-02-02",
    height: "5' 6\"",
    reach: "68\"",
    stance: "Orthodox",
    slpm: 4.97,
    strikingAccuracy: 56,
    sapm: 4.2,
    strikingDefense: 54,
    takedownAverage: 1.5,
    takedownAccuracy: 37,
    takedownDefense: 63,
    submissionAverage: 0.5,
  },
  "wes schultz": {
    name: "Wes Schultz",
    record: "9-3-0",
    dob: "1996-08-09",
    height: "6' 1\"",
    reach: "77\"",
    stance: "Orthodox",
    slpm: 2.43,
    strikingAccuracy: 43,
    sapm: 3.11,
    strikingDefense: 43,
    takedownAverage: 2.39,
    takedownAccuracy: 25,
    takedownDefense: 0,
    submissionAverage: 1.2,
  },
  "jackson mcvey": {
    name: "Jackson McVey",
    record: "7-2-0",
    dob: "1999-03-25",
    height: "6' 4\"",
    reach: "77\"",
    stance: "Southpaw",
    slpm: 6.51,
    strikingAccuracy: 69,
    sapm: 3.37,
    strikingDefense: 24,
    takedownAverage: 0,
    takedownAccuracy: 0,
    takedownDefense: 0,
    submissionAverage: 1.2,
  },
  "shanelle dyer": {
    name: "Shanelle Dyer",
    record: "7-1-0",
    dob: "2001-04-23",
    height: "5' 6\"",
    reach: "65\"",
    stance: "Orthodox",
    slpm: 7.71,
    strikingAccuracy: 46,
    sapm: 6.72,
    strikingDefense: 51,
    takedownAverage: 0.7,
    takedownAccuracy: 8,
    takedownDefense: 100,
    submissionAverage: 0,
  },
  "elise reed": {
    name: "Elise Reed",
    record: "8-5-0",
    dob: "1992-12-05",
    height: "5' 3\"",
    reach: "63\"",
    stance: "Orthodox",
    slpm: 3.41,
    strikingAccuracy: 53,
    sapm: 3.26,
    strikingDefense: 51,
    takedownAverage: 0.46,
    takedownAccuracy: 60,
    takedownDefense: 53,
    submissionAverage: 0,
  },
};

function normalizeName(value: string) {
  return value
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[’']/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

export function getUfcStatsSnapshotFighter(name: string) {
  return fighters[normalizeName(name)] ?? null;
}
