import {
  assertAverageFanQuestion,
  type AverageFanQuestion,
  type AverageFanSport,
} from "./averageFanEngine";

export interface AverageFanPreviewRun {
  sport: AverageFanSport;
  board: readonly AverageFanQuestion[];
  final: AverageFanQuestion;
}

const NFL_PREVIEW = [
  {
    id: "average-fan-preview-nfl-1a",
    sport: "nfl",
    grade: 1,
    subject: "Players",
    format: "short-answer",
    prompt: "Which Chiefs quarterback won Super Bowl LVII and LVIII MVP?",
    answer: "Patrick Mahomes",
    aliases: ["Mahomes", "Patrick Mahomes II"],
    explanation: "Patrick Mahomes was named MVP of both Super Bowl LVII and Super Bowl LVIII.",
    contentType: "evergreen",
    difficultyNudge: 0,
    fanMisses: ["Josh Allen", "Joe Burrow"],
    protectedFinal: false,
  },
  {
    id: "average-fan-preview-nfl-1b",
    sport: "nfl",
    grade: 1,
    subject: "Teams",
    format: "three-choice",
    prompt: "Which team plays its home games at Lambeau Field?",
    answer: "Green Bay Packers",
    aliases: ["Packers", "Green Bay"],
    choices: ["Green Bay Packers", "Chicago Bears", "Minnesota Vikings"],
    explanation: "Lambeau Field is the longtime home of the Green Bay Packers.",
    contentType: "evergreen",
    difficultyNudge: -1,
    protectedFinal: false,
  },
  {
    id: "average-fan-preview-nfl-2a",
    sport: "nfl",
    grade: 2,
    subject: "NFL History",
    format: "short-answer",
    prompt: "Who is the Super Bowl trophy named after?",
    answer: "Vince Lombardi",
    aliases: ["Lombardi"],
    explanation: "The NFL renamed its championship trophy the Vince Lombardi Trophy after Lombardi's death in 1970.",
    contentType: "evergreen",
    difficultyNudge: 0,
    fanMisses: ["Pete Rozelle", "George Halas"],
    protectedFinal: false,
  },
  {
    id: "average-fan-preview-nfl-2b",
    sport: "nfl",
    grade: 2,
    subject: "X’s & O’s",
    format: "short-answer",
    prompt: "What offensive position normally snaps the ball to the quarterback?",
    answer: "Center",
    aliases: ["The center"],
    explanation: "The center starts the play by snapping the ball to the quarterback.",
    contentType: "evergreen",
    difficultyNudge: -1,
    fanMisses: ["Guard", "Tackle"],
    protectedFinal: false,
  },
  {
    id: "average-fan-preview-nfl-3a",
    sport: "nfl",
    grade: 3,
    subject: "Players",
    format: "three-choice",
    prompt: "Which receiver won AP Offensive Player of the Year for the 2022 season?",
    answer: "Justin Jefferson",
    aliases: ["Jefferson"],
    choices: ["Justin Jefferson", "Tyreek Hill", "Davante Adams"],
    explanation: "Justin Jefferson won 2022 AP Offensive Player of the Year after leading the NFL in catches and receiving yards.",
    contentType: "evergreen",
    difficultyNudge: 0,
    protectedFinal: false,
  },
  {
    id: "average-fan-preview-nfl-3b",
    sport: "nfl",
    grade: 3,
    subject: "Teams",
    format: "short-answer",
    prompt: "Which team selected Joe Burrow with the first pick of the 2020 NFL Draft?",
    answer: "Cincinnati Bengals",
    aliases: ["Bengals", "Cincinnati"],
    explanation: "The Cincinnati Bengals selected Joe Burrow No. 1 overall in 2020.",
    contentType: "evergreen",
    difficultyNudge: 0,
    fanMisses: ["Miami Dolphins", "Carolina Panthers"],
    protectedFinal: false,
  },
  {
    id: "average-fan-preview-nfl-4a",
    sport: "nfl",
    grade: 4,
    subject: "NFL History",
    format: "short-answer",
    prompt: "The Chiefs-Bills playoff game remembered for '13 seconds' was part of which NFL season?",
    answer: "2021",
    aliases: ["2021 season", "The 2021 season"],
    explanation: "Kansas City beat Buffalo in overtime in the AFC Divisional Round following the 2021 regular season.",
    contentType: "evergreen",
    difficultyNudge: 1,
    fanMisses: ["2020", "2022"],
    protectedFinal: false,
  },
  {
    id: "average-fan-preview-nfl-4b",
    sport: "nfl",
    grade: 4,
    subject: "X’s & O’s",
    format: "true-false",
    prompt: "A nickel defense gets its name from having five defensive backs on the field.",
    answer: "True",
    aliases: [],
    explanation: "Nickel packages typically use five defensive backs, which gives the package its name.",
    contentType: "evergreen",
    difficultyNudge: 0,
    protectedFinal: false,
  },
  {
    id: "average-fan-preview-nfl-5a",
    sport: "nfl",
    grade: 5,
    subject: "Players",
    format: "short-answer",
    prompt: "Which Rams receiver won Super Bowl LVI MVP after completing the receiving Triple Crown that season?",
    answer: "Cooper Kupp",
    aliases: ["Kupp"],
    explanation: "Cooper Kupp led the NFL in receptions, receiving yards, and receiving touchdowns before earning Super Bowl LVI MVP.",
    contentType: "evergreen",
    difficultyNudge: 1,
    fanMisses: ["Odell Beckham Jr.", "Robert Woods"],
    protectedFinal: false,
  },
  {
    id: "average-fan-preview-nfl-5b",
    sport: "nfl",
    grade: 5,
    subject: "NFL History",
    format: "three-choice",
    prompt: "Which former franchise identity relocated from Houston to Tennessee before becoming the Titans?",
    answer: "Houston Oilers",
    aliases: ["Oilers", "The Oilers"],
    choices: ["Houston Oilers", "Houston Texans", "St. Louis Cardinals"],
    explanation: "The Houston Oilers moved to Tennessee, briefly played as the Tennessee Oilers, and became the Titans in 1999.",
    contentType: "evergreen",
    difficultyNudge: 1,
    protectedFinal: false,
  },
  {
    id: "average-fan-preview-nfl-final",
    sport: "nfl",
    grade: 5,
    subject: "X’s & O’s",
    format: "short-answer",
    prompt: "In offensive personnel terminology, what does '11 personnel' mean?",
    answer: "1 running back, 1 tight end, 3 wide receivers",
    aliases: ["1 RB, 1 TE, 3 WR", "one running back, one tight end, three wide receivers"],
    explanation: "The first digit counts running backs and the second counts tight ends; the remaining eligible skill players are wide receivers.",
    contentType: "evergreen",
    difficultyNudge: 2,
    fanMisses: ["2 running backs, 1 tight end, 2 wide receivers", "1 running back, 2 tight ends, 2 wide receivers"],
    protectedFinal: true,
  },
] as const satisfies readonly AverageFanQuestion[];

const CFB_PREVIEW = [
  {
    id: "average-fan-preview-cfb-1a",
    sport: "cfb",
    grade: 1,
    subject: "Players",
    format: "short-answer",
    prompt: "Which LSU quarterback won the Heisman Trophy for the 2019 season?",
    answer: "Joe Burrow",
    aliases: ["Burrow"],
    explanation: "Joe Burrow won the 2019 Heisman Trophy during LSU's undefeated national-title season.",
    contentType: "evergreen",
    difficultyNudge: -1,
    fanMisses: ["Jayden Daniels", "Joe Brady"],
    protectedFinal: false,
  },
  {
    id: "average-fan-preview-cfb-1b",
    sport: "cfb",
    grade: 1,
    subject: "Programs",
    format: "three-choice",
    prompt: "Which program plays its home games at Michigan Stadium, better known as the Big House?",
    answer: "Michigan",
    aliases: ["Michigan Wolverines", "Wolverines"],
    choices: ["Michigan", "Ohio State", "Penn State"],
    explanation: "Michigan Stadium in Ann Arbor is nicknamed the Big House.",
    contentType: "evergreen",
    difficultyNudge: -1,
    protectedFinal: false,
  },
  {
    id: "average-fan-preview-cfb-2a",
    sport: "cfb",
    grade: 2,
    subject: "Traditions",
    format: "true-false",
    prompt: "Ohio State players receive gold pants charms after beating Michigan.",
    answer: "True",
    aliases: [],
    explanation: "Ohio State's Gold Pants tradition rewards wins over rival Michigan.",
    contentType: "evergreen",
    difficultyNudge: 0,
    protectedFinal: false,
  },
  {
    id: "average-fan-preview-cfb-2b",
    sport: "cfb",
    grade: 2,
    subject: "CFB History",
    format: "short-answer",
    prompt: "What four-team postseason system determined the national champion from the 2014 through 2023 seasons?",
    answer: "College Football Playoff",
    aliases: ["CFP", "The College Football Playoff"],
    explanation: "The four-team College Football Playoff debuted after the 2014 regular season and expanded beginning with the 2024 season.",
    contentType: "evergreen",
    difficultyNudge: 0,
    fanMisses: ["Bowl Championship Series", "AP Poll"],
    protectedFinal: false,
  },
  {
    id: "average-fan-preview-cfb-3a",
    sport: "cfb",
    grade: 3,
    subject: "Players",
    format: "three-choice",
    prompt: "Which Alabama wide receiver won the Heisman Trophy for the 2020 season?",
    answer: "DeVonta Smith",
    aliases: ["Devonta Smith", "Smith"],
    choices: ["DeVonta Smith", "Jaylen Waddle", "Jerry Jeudy"],
    explanation: "DeVonta Smith became the first wide receiver to win the Heisman since Desmond Howard.",
    contentType: "evergreen",
    difficultyNudge: 0,
    protectedFinal: false,
  },
  {
    id: "average-fan-preview-cfb-3b",
    sport: "cfb",
    grade: 3,
    subject: "Programs",
    format: "short-answer",
    prompt: "Which school did Caleb Williams represent when he won the 2022 Heisman Trophy?",
    answer: "USC",
    aliases: ["Southern California", "USC Trojans", "Southern Cal"],
    explanation: "Caleb Williams won the 2022 Heisman in his first season at USC.",
    contentType: "evergreen",
    difficultyNudge: 0,
    fanMisses: ["Oklahoma", "UCLA"],
    protectedFinal: false,
  },
  {
    id: "average-fan-preview-cfb-4a",
    sport: "cfb",
    grade: 4,
    subject: "Traditions",
    format: "short-answer",
    prompt: "What nickname identifies Texas A&M's student body and fan tradition as an extra player?",
    answer: "12th Man",
    aliases: ["The 12th Man", "Twelfth Man", "The Twelfth Man"],
    explanation: "Texas A&M's 12th Man tradition traces to E. King Gill being called from the stands to stand ready in 1922.",
    contentType: "evergreen",
    difficultyNudge: 0,
    fanMisses: ["The Corps", "Aggie Spirit"],
    protectedFinal: false,
  },
  {
    id: "average-fan-preview-cfb-4b",
    sport: "cfb",
    grade: 4,
    subject: "CFB History",
    format: "short-answer",
    prompt: "What championship system immediately preceded the College Football Playoff?",
    answer: "Bowl Championship Series",
    aliases: ["BCS", "The BCS"],
    explanation: "The Bowl Championship Series ran from the 1998 season through the 2013 season before the CFP replaced it.",
    contentType: "evergreen",
    difficultyNudge: 0,
    fanMisses: ["Bowl Alliance", "Coaches Poll"],
    protectedFinal: false,
  },
  {
    id: "average-fan-preview-cfb-5a",
    sport: "cfb",
    grade: 5,
    subject: "Players",
    format: "short-answer",
    prompt: "Which defensive back on LSU's 2019 national-title team won the Jim Thorpe Award?",
    answer: "Grant Delpit",
    aliases: ["Delpit"],
    explanation: "LSU safety Grant Delpit won the 2019 Jim Thorpe Award as the nation's top defensive back.",
    contentType: "evergreen",
    difficultyNudge: 2,
    fanMisses: ["Derek Stingley Jr.", "Kristian Fulton"],
    protectedFinal: false,
  },
  {
    id: "average-fan-preview-cfb-5b",
    sport: "cfb",
    grade: 5,
    subject: "Programs",
    format: "three-choice",
    prompt: "Which program won the 2005 national championship behind quarterback Vince Young?",
    answer: "Texas",
    aliases: ["Texas Longhorns", "Longhorns"],
    choices: ["Texas", "USC", "Oklahoma"],
    explanation: "Texas beat USC in the Rose Bowl to finish 13-0 and win the 2005 national championship.",
    contentType: "evergreen",
    difficultyNudge: 1,
    protectedFinal: false,
  },
  {
    id: "average-fan-preview-cfb-final",
    sport: "cfb",
    grade: 5,
    subject: "CFB History",
    format: "short-answer",
    prompt: "Which head coach led Florida to national championships in both the 2006 and 2008 seasons?",
    answer: "Urban Meyer",
    aliases: ["Meyer"],
    explanation: "Urban Meyer coached Florida to BCS national championships following the 2006 and 2008 seasons.",
    contentType: "evergreen",
    difficultyNudge: 2,
    fanMisses: ["Steve Spurrier", "Jim McElwain"],
    protectedFinal: true,
  },
] as const satisfies readonly AverageFanQuestion[];

const UFC_PREVIEW = [
  {
    id: "average-fan-preview-ufc-1a",
    sport: "ufc",
    grade: 1,
    subject: "Fighters",
    format: "short-answer",
    prompt: "Which UFC star is nicknamed 'The Notorious'?",
    answer: "Conor McGregor",
    aliases: ["McGregor", "Conor"],
    explanation: "Conor McGregor has long competed under the nickname 'The Notorious.'",
    contentType: "evergreen",
    difficultyNudge: -1,
    fanMisses: ["Nate Diaz", "Sean O'Malley"],
    protectedFinal: false,
  },
  {
    id: "average-fan-preview-ufc-1b",
    sport: "ufc",
    grade: 1,
    subject: "Fights",
    format: "three-choice",
    prompt: "Which city is the traditional home of UFC International Fight Week?",
    answer: "Las Vegas",
    aliases: ["Las Vegas, Nevada", "Vegas"],
    choices: ["Las Vegas", "New York City", "Miami"],
    explanation: "UFC International Fight Week is traditionally staged in Las Vegas.",
    contentType: "evergreen",
    difficultyNudge: -1,
    protectedFinal: false,
  },
  {
    id: "average-fan-preview-ufc-2a",
    sport: "ufc",
    grade: 2,
    subject: "Championships",
    format: "true-false",
    prompt: "A UFC fighter can hold championships in two weight classes at the same time.",
    answer: "True",
    aliases: [],
    explanation: "The UFC has had simultaneous two-division champions, often called champ-champs.",
    contentType: "evergreen",
    difficultyNudge: -1,
    protectedFinal: false,
  },
  {
    id: "average-fan-preview-ufc-2b",
    sport: "ufc",
    grade: 2,
    subject: "Octagon IQ",
    format: "short-answer",
    prompt: "How many rounds are scheduled in a standard non-title UFC bout?",
    answer: "3",
    aliases: ["Three", "3 rounds", "Three rounds"],
    explanation: "Standard non-title UFC bouts are scheduled for three five-minute rounds.",
    contentType: "evergreen",
    difficultyNudge: -1,
    fanMisses: ["5", "4"],
    protectedFinal: false,
  },
  {
    id: "average-fan-preview-ufc-3a",
    sport: "ufc",
    grade: 3,
    subject: "Fighters",
    format: "three-choice",
    prompt: "Who won the UFC welterweight title from Kamaru Usman with a fifth-round head kick at UFC 278?",
    answer: "Leon Edwards",
    aliases: ["Edwards", "Leon"],
    choices: ["Leon Edwards", "Colby Covington", "Jorge Masvidal"],
    explanation: "Leon Edwards knocked out Kamaru Usman late in round five at UFC 278.",
    contentType: "evergreen",
    difficultyNudge: 0,
    protectedFinal: false,
  },
  {
    id: "average-fan-preview-ufc-3b",
    sport: "ufc",
    grade: 3,
    subject: "Fights",
    format: "short-answer",
    prompt: "At UFC 229, Khabib Nurmagomedov defended the lightweight title against whom?",
    answer: "Conor McGregor",
    aliases: ["McGregor", "Conor"],
    explanation: "Khabib Nurmagomedov submitted Conor McGregor in the fourth round at UFC 229.",
    contentType: "evergreen",
    difficultyNudge: 0,
    fanMisses: ["Dustin Poirier", "Justin Gaethje"],
    protectedFinal: false,
  },
  {
    id: "average-fan-preview-ufc-4a",
    sport: "ufc",
    grade: 4,
    subject: "Championships",
    format: "short-answer",
    prompt: "Who became the UFC's first fighter to hold titles in two divisions simultaneously?",
    answer: "Conor McGregor",
    aliases: ["McGregor", "Conor"],
    explanation: "Conor McGregor added the lightweight title to his featherweight belt at UFC 205.",
    contentType: "evergreen",
    difficultyNudge: 0,
    fanMisses: ["Daniel Cormier", "Amanda Nunes"],
    protectedFinal: false,
  },
  {
    id: "average-fan-preview-ufc-4b",
    sport: "ufc",
    grade: 4,
    subject: "Octagon IQ",
    format: "true-false",
    prompt: "A judge can award a 10-8 round even when no knockdown occurs.",
    answer: "True",
    aliases: [],
    explanation: "A 10-8 is based on the scoring criteria and degree of dominance; a knockdown is not required.",
    contentType: "evergreen",
    difficultyNudge: 1,
    protectedFinal: false,
  },
  {
    id: "average-fan-preview-ufc-5a",
    sport: "ufc",
    grade: 5,
    subject: "Fighters",
    format: "short-answer",
    prompt: "Which fighter did Georges St-Pierre defeat to win the UFC middleweight title at UFC 217?",
    answer: "Michael Bisping",
    aliases: ["Bisping"],
    explanation: "Georges St-Pierre returned from a four-year absence and submitted middleweight champion Michael Bisping at UFC 217.",
    contentType: "evergreen",
    difficultyNudge: 2,
    fanMisses: ["Luke Rockhold", "Anderson Silva"],
    protectedFinal: false,
  },
  {
    id: "average-fan-preview-ufc-5b",
    sport: "ufc",
    grade: 5,
    subject: "Championships",
    format: "short-answer",
    prompt: "Whom did Amanda Nunes knock out to win the UFC featherweight title and become a two-division champion?",
    answer: "Cris Cyborg",
    aliases: ["Cyborg", "Cristiane Justino", "Cris Justino"],
    explanation: "Amanda Nunes knocked out Cris Cyborg at UFC 232 to add the featherweight title to her bantamweight belt.",
    contentType: "evergreen",
    difficultyNudge: 1,
    fanMisses: ["Holly Holm", "Germaine de Randamie"],
    protectedFinal: false,
  },
  {
    id: "average-fan-preview-ufc-final",
    sport: "ufc",
    grade: 5,
    subject: "Octagon IQ",
    format: "three-choice",
    prompt: "Under the Unified Rules, which judging criterion is considered first?",
    answer: "Effective striking and grappling",
    aliases: ["Effective striking/grappling"],
    choices: ["Effective striking and grappling", "Effective aggressiveness", "Fighting area control"],
    explanation: "Judges prioritize effective striking and grappling before effective aggressiveness and then fighting area control.",
    contentType: "evergreen",
    difficultyNudge: 2,
    protectedFinal: true,
  },
] as const satisfies readonly AverageFanQuestion[];

const PREVIEW_BANK = {
  nfl: NFL_PREVIEW,
  cfb: CFB_PREVIEW,
  ufc: UFC_PREVIEW,
} as const satisfies Record<AverageFanSport, readonly AverageFanQuestion[]>;

export function averageFanPreviewRun(sport: AverageFanSport): AverageFanPreviewRun {
  const rows = PREVIEW_BANK[sport].map((question) => assertAverageFanQuestion(question));
  const board = rows.filter((question) => !question.protectedFinal);
  const final = rows.find((question) => question.protectedFinal);
  if (board.length !== 10 || !final) {
    throw new Error(`Average Fan ${sport} preview must contain 10 board questions and one Final.`);
  }
  return { sport, board, final };
}
