/**
 * UFC Who Am I calibration set (full 100-fighter population).
 *
 * The underlying PR10 research remains an archive of sourced person-identity facts.
 * This layer answers a narrower gameplay question: does the fact materially help a
 * knowledgeable sports fan identify the hidden fighter? We retain sports identity,
 * signature public identity, and at most one useful color lane per fighter while
 * removing biography/job/degree/hobby filler from the playable clue pool.
 */
export const UFC_WHO_AM_I_CALIBRATION_SUBJECT_IDS = [
  "ufc:jon-jones",
  "ufc:demetrious-johnson",
  "ufc:khabib-nurmagomedov",
  "ufc:max-holloway",
  "ufc:randy-couture",
  "ufc:alex-pereira",
  "ufc:tj-dillashaw",
  "ufc:francis-ngannou",
  "ufc:aljamain-sterling",
  "ufc:justin-gaethje",
  "ufc:dustin-poirier",
  "ufc:tito-ortiz",
  "ufc:robbie-lawler",
  "ufc:henry-cejudo",
  "ufc:petr-yan",
  "ufc:conor-mcgregor",
  "ufc:lyoto-machida",
  "ufc:dricus-du-plessis",
  "ufc:khamzat-chimaev",
  "ufc:sean-omalley",
  "ufc:forrest-griffin",
  "ufc:chael-sonnen",
  "ufc:valentina-shevchenko",
  "ufc:rose-namajunas",
  "ufc:cris-cyborg",
  "ufc:kayla-harrison",
  "ufc:miesha-tate",
  "ufc:jorge-masvidal",
  "ufc:michael-chandler",
  "ufc:brian-ortega",
  "ufc:ciryl-gane",
  "ufc:marlon-vera",
  "ufc:dominick-reyes",
  "ufc:dan-hooker",
  "ufc:georges-st-pierre",
  "ufc:islam-makhachev",
  "ufc:matt-hughes",
  "ufc:stipe-miocic",
  "ufc:israel-adesanya",
  "ufc:chuck-liddell",
  "ufc:merab-dvalishvili",
  "ufc:cain-velasquez",
  "ufc:junior-dos-santos",
  "ufc:tyron-woodley",
  "ufc:alex-pantoja",
  "ufc:ilia-topuria",
  "ufc:robert-whittaker",
  "ufc:chris-weidman",
  "ufc:sean-strickland",
  "ufc:brandon-moreno",
  "ufc:rashad-evans",
  "ufc:dominick-cruz",
  "ufc:michael-bisping",
  "ufc:quinton-jackson",
  "ufc:brock-lesnar",
  "ufc:paddy-pimblett",
  "ufc:zhang-weili",
  "ufc:ronda-rousey",
  "ufc:carla-esparza",
  "ufc:mackenzie-dern",
  "ufc:holly-holm",
  "ufc:nate-diaz",
  "ufc:colby-covington",
  "ufc:yair-rodriguez",
  "ufc:kevin-holland",
  "ufc:gilbert-burns",
  "ufc:nick-diaz",
  "ufc:anderson-silva",
  "ufc:alexander-volkanovski",
  "ufc:kamaru-usman",
  "ufc:jose-aldo",
  "ufc:daniel-cormier",
  "ufc:charles-oliveira",
  "ufc:frankie-edgar",
  "ufc:benson-henderson",
  "ufc:bj-penn",
  "ufc:glover-teixeira",
  "ufc:leon-edwards",
  "ufc:fabricio-werdum",
  "ufc:tony-ferguson",
  "ufc:frank-shamrock",
  "ufc:deiveson-figueiredo",
  "ufc:vitor-belfort",
  "ufc:tom-aspinall",
  "ufc:royce-gracie",
  "ufc:anthony-pettis",
  "ufc:shogun-rua",
  "ufc:dan-henderson",
  "ufc:amanda-nunes",
  "ufc:joanna-jedrzejczyk",
  "ufc:jessica-andrade",
  "ufc:alexa-grasso",
  "ufc:julianna-pena",
  "ufc:rafael-dos-anjos",
  "ufc:donald-cerrone",
  "ufc:stephen-thompson",
  "ufc:derrick-lewis",
  "ufc:paulo-costa",
  "ufc:tai-tuivasa",
  "ufc:diego-lopes",
] as const;

const retainedConceptsBySubject = new Map<string, ReadonlySet<string>>([
  ["ufc:jon-jones", new Set(["iowa-central-wrestling-and-degree", "nfl-brothers-arthur-and-chandler", "youtube-technique-study", "robbery-intervention-title-day"])],
  ["ufc:demetrious-johnson", new Set(["wrestling-accountability-origin", "matt-hume-longtime-mentor", "mighty-mouse-nickname-origin", "lifelong-gamer-and-streamer"])],
  ["ufc:khabib-nurmagomedov", new Set(["father-school-before-fighting", "combat-sambo-world-champion", "post-retirement-coaching-role", "eagle-fighting-championship-owner"])],
  ["ufc:max-holloway", new Set(["josh-keanu-speedbag-gym-origin", "blessed-nickname-origin", "mini-blessed-son-rush"])],
  ["ufc:randy-couture", new Set(["army-101st-airborne-service", "olympic-alternate-wrestling-background", "the-natural-nickname-origin", "expendables-acting-career"])],
  ["ufc:alex-pereira", new Set(["kickboxing-to-escape-alcohol", "glory-simultaneous-two-division-champion", "poatan-indigenous-name-origin", "fighter-sister-aline-pereira"])],
  ["ufc:tj-dillashaw", new Set(["raiders-family-and-football-background", "mma-after-college-wrestling", "ultimate-fighter-team-bisping", "duane-ludwig-colorado-move"])],
  ["ufc:francis-ngannou", new Set(["fourteen-month-migration-seventh-crossing", "boxing-dream-to-mma-factory-pivot"])],
  ["ufc:aljamain-sterling", new Set(["funk-master-nickname-origin", "division-three-all-american-wrestler", "matt-serra-bjj-black-belt"])],
  ["ufc:justin-gaethje", new Set(["morenci-copper-mining-family", "northern-colorado-all-american-wrestler", "highlight-nickname-wrestling-slams"])],
  ["ufc:dustin-poirier", new Set(["fightville-documentary-subject", "diamond-nickname-tim-credeur", "louisiana-hot-sauce-and-cajun-roots"])],
  ["ufc:tito-ortiz", new Set(["ufc-one-royce-gracie-inspiration", "tank-abbott-training-connection", "golden-west-wrestling-scholarship", "ufc-thirteen-no-prize-money"])],
  ["ufc:robbie-lawler", new Set(["father-started-martial-arts-after-brother", "san-diego-to-iowa-athletic-upbringing", "miletich-gym-at-sixteen", "matt-pena-longtime-corner"])],
  ["ufc:henry-cejudo", new Set(["youngest-us-freestyle-olympic-gold", "arizona-bronze-gloves-boxing", "older-brother-angel-wrestling-influence", "triple-c-nickname-origin"])],
  ["ufc:petr-yan", new Set(["boxing-at-thirteen-to-mma", "youth-boxing-trainer-education", "no-mercy-nickname-mindset"])],
  ["ufc:conor-mcgregor", new Set(["crumlin-boxing-after-football", "john-kavanagh-sbg-commitment-pivot", "notorious-nickname-origin", "proper-no-twelve-cofounder"])],
  ["ufc:lyoto-machida", new Set(["shotokan-with-father-from-age-three", "five-thirty-discipline-training", "karate-core-in-mma", "sumo-and-jiu-jitsu-cross-training"])],
  ["ufc:dricus-du-plessis", new Set(["judo-wrestling-kickboxing-childhood", "teenage-south-african-wako-champion", "stillknocks-nickname-brother-origin"])],
  ["ufc:khamzat-chimaev", new Set(["chechnya-to-sweden-wrestling", "hotel-gift-card-allstars-origin", "borz-means-wolf"])],
  ["ufc:sean-omalley", new Set(["helena-montana-first-coach", "sugar-nickname-sweet-to-watch", "fight-week-colorful-hair-tradition", "snoop-dogg-contender-series-connection"])],
  ["ufc:forrest-griffin", new Set(["university-police-officer", "mma-hobby-dan-severn-first-pro", "tuf-one-bonnar-mainstream-breakthrough"])],
  ["ufc:chael-sonnen", new Set(["realtor-and-political-ambitions", "ncaa-and-greco-roman-wrestling", "fighting-as-hobby-philosophy", "american-gangster-persona-origin"])],
  ["ufc:valentina-shevchenko", new Set(["martial-arts-family-start-age-five", "peru-eight-year-home", "lifelong-dance-training", "fighter-sister-antonina"])],
  ["ufc:rose-namajunas", new Set(["martial-arts-since-age-five", "thug-nickname-origin"])],
  ["ufc:cris-cyborg", new Set(["handball-discovery-at-nineteen", "chute-boxe-first-woman", "early-womens-mma-main-event", "cyborg-name-from-evangelista-santos"])],
  ["ufc:kayla-harrison", new Set(["moved-to-boston-for-jimmy-pedro", "first-us-olympic-judo-gold", "youngest-us-rokudan", "retirement-to-striking-to-mma"])],
  ["ufc:miesha-tate", new Set(["boys-wrestling-team-after-basketball", "washington-girls-wrestling-champion", "mma-start-at-nineteen", "cupcake-nickname-and-baking"])],
  ["ufc:jorge-masvidal", new Set(["miami-cuban-american-upbringing", "backyard-fights-kimbo-circle", "gamebred-nickname-brother-origin", "global-pre-ufc-fight-circuit"])],
  ["ufc:michael-chandler", new Set(["missouri-wrestling-walk-on", "woodley-askren-big-brother-influence", "mizzou-wrestling-coach-job", "high-school-football-background"])],
  ["ufc:brian-ortega", new Set(["rener-gracie-student-from-thirteen", "t-city-triangle-nickname-origin", "law-enforcement-self-defense-instructor", "james-luhrsen-garage-training"])],
  ["ufc:ciryl-gane", new Set(["soccer-basketball-youth-sports", "luxury-furniture-coworker-muay-thai", "two-time-france-muay-thai-champion", "fernand-lopez-mma-factory-pivot"])],
  ["ufc:marlon-vera", new Set(["jiu-jitsu-start-at-sixteen", "first-ecuadorian-ufc-fighter", "daughter-surgery-career-motivation", "chito-childhood-nickname-origin", "downloaded-fight-videos-in-ecuador"])],
  ["ufc:dominick-reyes", new Set(["stony-brook-football-safety", "devastator-nickname-origin", "fighter-brother-alex-reyes"])],
  ["ufc:dan-hooker", new Set(["friend-knockout-mma-origin", "hangman-nickname-chokes", "pre-ufc-kickboxing-titles", "one-minute-scraps-promotion"])],
  ["ufc:georges-st-pierre", new Set(["bullying-karate-self-defense", "gymnastics-olympic-lifting-cross-training"])],
  ["ufc:islam-makhachev", new Set(["training-age-ten-self-defense", "combat-sambo-championship-pedigree", "abdulmanap-khabib-training-lineage"])],
  ["ufc:matt-hughes", new Set(["eastern-illinois-all-american-wrestling", "agricultural-company-parallel-career", "ufc-front-office-athlete-development", "identical-twin-mark-mma-partner"])],
  ["ufc:stipe-miocic", new Set(["cleveland-multi-sport-athlete", "cleveland-golden-gloves-boxing", "firefighter-paramedic-career", "croatian-family-roots", "mma-start-helping-training-partner"])],
  ["ufc:israel-adesanya", new Set(["self-protection-training-origin", "computer-graphic-design-study", "last-stylebender-anime-identity", "dance-background-ufc243-walkout"])],
  ["ufc:chuck-liddell", new Set(["karate-since-twelve-dream-gym", "head-tattoo-peace-prosperity", "post-retirement-ufc-executive"])],
  ["ufc:merab-dvalishvili", new Set(["judo-sambo-seven-year-foundation", "georgian-sambo-youth-medals", "lookin-for-a-fight-discovery"])],
  ["ufc:cain-velasquez", new Set(["brown-pride-tattoo-family-heritage", "elite-amateur-wrestling-path", "olympic-path-chose-mma"])],
  ["ufc:junior-dos-santos", new Set(["capoeira-adolescent-origin", "yuri-carlton-jiujitsu-to-mma", "cigano-soap-opera-nickname"])],
  ["ufc:tyron-woodley", new Set(["missouri-wrestling-credentials", "college-wrestling-coach-job", "acting-straight-outta-compton"])],
  ["ufc:alex-pantoja", new Set(["bjj-muay-thai-to-mma-career", "uber-driving-acl-period"])],
  ["ufc:ilia-topuria", new Set(["father-bjj-age-four", "arnold-fighter-tournament-win", "european-youth-bjj-runner-up", "georgia-spain-dual-identity"])],
  ["ufc:robert-whittaker", new Set(["railcorp-electrician-apprentice", "three-martial-arts-black-belts"])],
  ["ufc:chris-weidman", new Set(["assistant-wrestling-coach-grad-student", "jiujitsu-through-helping-mma-fighters", "grapplers-quest-thirteen-submissions", "basement-apartment-waited-for-ufc"])],
  ["ufc:sean-strickland", new Set(["training-age-fourteen-anger-outlet", "professional-since-sixteen", "motorcycle-accident-career-hiatus", "unfiltered-no-character-persona"])],
  ["ufc:brandon-moreno", new Set(["family-pinata-business", "mma-start-exercise-chubby-kid", "assassin-baby-nickname-debut"])],
  ["ufc:rashad-evans", new Set(["michigan-state-division-one-wrestler", "undersized-heavyweight-tuf2-gamble"])],
  ["ufc:dominick-cruz", new Set(["dominator-high-school-football-joke", "seventh-grade-wrestling-start", "multi-surgery-injury-comeback", "combat-sports-analyst-career"])],
  ["ufc:michael-bisping", new Set(["count-nickname-ancestry", "detached-retina-two-surgeries", "jiujitsu-childhood-no-holds-barred", "analyst-commentator-acting-second-career"])],
  ["ufc:quinton-jackson", new Set(["wrestling-redirected-street-path", "japan-second-home-family-ties", "a-team-ba-baracus-role"])],
  ["ufc:brock-lesnar", new Set(["ncaa-heavyweight-wrestling-champion", "wwe-next-big-thing-stardom", "minnesota-vikings-nfl-attempt", "diverticulitis-colon-surgery"])],
  ["ufc:paddy-pimblett", new Set(["full-time-training-at-sixteen", "liverpool-fc-home-away-passion", "ricky-mental-health-advocacy"])],
  ["ufc:zhang-weili", new Set(["sanda-foundation", "ufc157-womens-main-event-inspiration"])],
  ["ufc:ronda-rousey", new Set(["mother-annmaria-judo-lineage", "historic-2008-olympic-bronze", "pro-wrestling-fandom-wwe-crossover"])],
  ["ufc:carla-esparza", new Set(["menlo-college-wrestling", "bjj-muay-thai-between-wrestling-seasons"])],
  ["ufc:mackenzie-dern", new Set(["father-megaton-bjj-age-three", "elite-bjj-championship-pedigree", "professional-bjj-before-mma", "us-brazil-bilingual-identity"])],
  ["ufc:holly-holm", new Set(["preachers-daughter-nickname", "cardio-kickboxing-accidental-start", "boxing-hall-of-fame-career"])],
  ["ufc:nate-diaz", new Set(["nick-royce-gracie-influence", "cesar-gracie-shark-tank-training", "vegan-diet-body-awareness", "stockton-gym-youth-teaching"])],
  ["ufc:colby-covington", new Set(["chaos-nickname-mother-mythology", "pac10-ncaa-wrestling-pedigree", "iowa-to-oregon-state-wrestling-path", "masvidal-roommates-to-rivals"])],
  ["ufc:yair-rodriguez", new Set(["taekwondo-at-five", "discovered-vale-todo-gym", "parral-to-chicago-training-move"])],
  ["ufc:kevin-holland", new Set(["kung-fu-humbling-start-age-sixteen", "trailblazer-nickname-school-name", "dual-black-belts-kungfu-bjj", "big-mouth-midfight-talking-persona"])],
  ["ufc:gilbert-burns", new Set(["durinho-nickname-brother-diminutive", "bjj-world-title-before-mma", "belfort-cornerman-hooft-connection"])],
  ["ufc:nick-diaz", new Set(["stockton-slap-grandfather-origin", "offroad-triathlon-passion"])],
  ["ufc:anderson-silva", new Set(["spider-man-comic-collector", "royce-gracie-ufc1-inspiration"])],
  ["ufc:alexander-volkanovski", new Set(["alexander-the-great-nickname-heritage", "national-level-wrestling-background", "warilla-gorillas-rugby-league", "rugby-conditioning-led-to-mma-coach"])],
  ["ufc:kamaru-usman", new Set(["marty-wrestling-nickname", "olympic-wrestling-dream", "rashad-evans-mma-bridge"])],
  ["ufc:jose-aldo", new Set(["childhood-cheek-scar", "soccer-first-ambition", "manaus-to-rio-leap", "capoeira-before-jiu-jitsu"])],
  ["ufc:daniel-cormier", new Set(["all-state-football-to-wrestling", "2008-olympic-weight-cut-crisis", "gilroy-high-wrestling-coach"])],
  ["ufc:charles-oliveira", new Set(["do-bronx-neighborhood-identity"])],
  ["ufc:frankie-edgar", new Set(["union-plumber-double-life", "clarion-division-one-wrestler", "wrestling-school-and-gym-owner"])],
  ["ufc:benson-henderson", new Set(["dana-college-wrestling-all-american", "declined-police-career-for-mma", "toothpick-fight-habit"])],
  ["ufc:bj-penn", new Set(["baby-jay-name-origin", "neighbor-tom-callos-bjj-introduction", "prodigy-rapid-black-belt-rise"])],
  ["ufc:glover-teixeira", new Set(["royce-tape-changed-boxing-plan", "hackleman-liddell-mentorship"])],
  ["ufc:leon-edwards", new Set<string>()],
  ["ufc:fabricio-werdum", new Set(["spain-long-term-home", "ufc-spanish-analyst", "cro-cop-croatia-japan-bridge", "vai-cavalo-nickname"])],
  ["ufc:tony-ferguson", new Set(["three-sport-varsity-athlete", "el-cucuy-nickname-meaning", "unconventional-self-designed-training"])],
  ["ufc:frank-shamrock", new Set(["helped-form-american-kickboxing-academy", "early-balanced-cross-training", "fighter-to-fight-executive-identity"])],
  ["ufc:deiveson-figueiredo", new Set(["marajoara-grappling-origin"])],
  ["ufc:vitor-belfort", new Set(["street-sparring-tissue-mouthguards", "carlson-gracie-protege", "teenage-move-to-los-angeles"])],
  ["ufc:tom-aspinall", new Set(["martial-arts-father-andy", "jiu-jitsu-first-background", "tyson-fury-training-influence", "speed-over-heavyweight-stereotype"])],
  ["ufc:royce-gracie", new Set(["chosen-as-unimposing-gracie-representative"])],
  ["ufc:anthony-pettis", new Set(["showtime-nickname-from-roufus", "brother-sergio-fighter-family"])],
  ["ufc:shogun-rua", new Set(["brother-ninja-inspired-start", "chute-boxe-hard-sparring-culture", "japan-second-home"])],
  ["ufc:dan-henderson", new Set(["father-high-school-wrestling-coach", "two-time-greco-roman-olympian", "mma-funded-third-olympic-bid", "randy-couture-mma-bridge", "team-quest-founder"])],
  ["ufc:amanda-nunes", new Set<string>()],
  ["ufc:joanna-jedrzejczyk", new Set(["basketball-before-muay-thai", "self-funded-muay-thai-travel"])],
  ["ufc:jessica-andrade", new Set(["futsal-background", "school-judo-to-bjj", "bate-estaca-piledriver-nickname"])],
  ["ufc:alexa-grasso", new Set(["family-gym-reception-and-cleaning", "national-bjj-win-with-irene-aldana"])],
  ["ufc:julianna-pena", new Set(["career-threatening-knee-rebuild"])],
  ["ufc:rafael-dos-anjos", new Set(["international-training-germany-singapore", "sold-everything-for-california-move"])],
  ["ufc:donald-cerrone", new Set(["bull-riding-rodeo-background", "extreme-adrenaline-lifestyle", "bmf-ranch-training-compound"])],
  ["ufc:stephen-thompson", new Set(["wonderboy-nickname-origin", "head-kids-instructor", "chris-weidman-family-connection"])],
  ["ufc:derrick-lewis", new Set(["george-foreman-boxing-mentorship", "black-beast-gym-mascot-origin", "hurricane-harvey-rescues"])],
  ["ufc:paulo-costa", new Set(["homemade-cement-dumbbells", "borrachinha-to-eraser-nickname"])],
  ["ufc:tai-tuivasa", new Set(["sydney-roosters-rugby-league", "street-fighting-channeled-into-mma", "shoey-celebration-ritual"])],
  ["ufc:diego-lopes", new Set(["moved-to-mexico-to-teach-bjj", "alexa-grasso-coach", "donald-cerrone-idol-and-training"])],
]);

const calibrationSubjectIds = new Set<string>(UFC_WHO_AM_I_CALIBRATION_SUBJECT_IDS);

export function isUfcWhoAmICalibrationSubject(subjectId: string) {
  return calibrationSubjectIds.has(subjectId);
}

export function shouldUseUfcWhoAmIIdentityConcept(subjectId: string, conceptId: string) {
  const retained = retainedConceptsBySubject.get(subjectId);
  return retained ? retained.has(conceptId) : true;
}

export function retainedUfcWhoAmIIdentityConcepts(subjectId: string) {
  return retainedConceptsBySubject.get(subjectId) ?? null;
}
