import type { UfcWhoAmIAuthoredIdentity } from "./ufcWhoAmIAuthoredScripts";

const BANDS = ["broad","broad","helpful","helpful","helpful","strong","strong","strong","giveaway","giveaway"] as const;
type Row = readonly [text: string, sourceIds: readonly string[]];

function identity(
  subjectId: string,
  name: string,
  sources: Readonly<Record<string,string>>,
  a: readonly Row[],
  b: readonly Row[],
): UfcWhoAmIAuthoredIdentity {
  const slug = subjectId.slice(4);
  const script = (id: "A"|"B", rows: readonly Row[]) => ({
    id,
    clues: rows.map(([text, sourceIds], i) => ({
      id: `ufc-${slug}-${id.toLowerCase()}-${i+1}`,
      text,
      band: BANDS[i]!,
      verification: "verified" as const,
      sourceIds,
    })),
  });
  return { subjectId, name, earlyRotation: "normal", sources, scripts: { A: script("A",a), B: script("B",b) } };
}

export const ufcWhoAmIAuthoredExpansion2026B: readonly UfcWhoAmIAuthoredIdentity[] = [
  identity("ufc:shavkat-rakhmonov","Shavkat Rakhmonov",{
    stats:"https://ufcstats.com/statistics/fighters",
    profile:"https://www.ufc.com/athlete/shavkat-rakhmonov",
  },[
    ["I entered the UFC with an unbeaten professional record.",["stats","profile"]],
    ["My game combines patient striking with a strong submission attack.",["profile"]],
    ["I finished each of my first six UFC opponents.",["stats","profile"]],
    ["My first UFC appearance ended with a first-round submission.",["stats"]],
    ["I later submitted a veteran contender late in the second round to move into the rankings.",["stats","profile"]],
    ["I stopped Geoff Neal with a standing rear-naked choke after a striking-heavy fight.",["stats","profile"]],
    ["I became the first fighter to submit Stephen Thompson in the UFC.",["stats","profile"]],
    ["My first UFC decision came only after six straight Octagon finishes.",["stats"]],
    ["That decision win was over Ian Machado Garry in a five-round bout.",["stats","profile"]],
    ["Known as “Nomad,” I built one of welterweight’s most unusual undefeated finishing streaks.",["profile"]],
  ],[
    ["I came to the UFC as a former M-1 welterweight champion.",["profile"]],
    ["Before my first UFC decision, every professional win of my career had come inside the distance.",["profile"]],
    ["I won my Octagon debut by submission in 2020.",["stats"]],
    ["My next UFC fight also ended by submission.",["stats"]],
    ["I then added a knockout before returning to my grappling-heavy finishing path.",["stats"]],
    ["A guillotine finish of Neil Magny pushed me into the division’s upper tier.",["stats","profile"]],
    ["I followed with submissions of Geoff Neal and Stephen Thompson.",["stats","profile"]],
    ["My matchup with Ian Machado Garry went all five rounds and ended my all-finishes streak.",["stats"]],
    ["I won that fight by unanimous decision to remain unbeaten.",["stats","profile"]],
    ["The Kazakhstan welterweight is recognized for pairing an unbeaten rise with a long streak of finishes.",["profile"]],
  ]),
  identity("ufc:urijah-faber","Urijah Faber",{
    stats:"https://ufcstats.com/statistics/fighters",
    profile:"https://www.ufc.com/athlete/urijah-faber",
    hof:"https://www.ufc.com/hof/urijah-faber",
  },[
    ["I was already a major champion before the UFC absorbed my division.",["profile","hof"]],
    ["My career helped make lighter weight classes more visible to mainstream MMA fans.",["hof"]],
    ["I entered the UFC in 2011 and immediately won a three-round decision.",["stats"]],
    ["I spent much of my UFC run in title eliminators and championship fights.",["stats","profile"]],
    ["My first UFC title shot came only four months after my Octagon debut.",["stats"]],
    ["I challenged Dominick Cruz for the bantamweight title in a trilogy rivalry.",["stats","hof"]],
    ["I also fought Renan Barao twice for UFC bantamweight gold.",["stats"]],
    ["After a long absence, I returned in 2019 and scored a first-round knockout.",["stats","profile"]],
    ["I founded Team Alpha Male and became one of Sacramento’s defining MMA figures.",["profile","hof"]],
    ["I entered the UFC Hall of Fame after a career strongly associated with the nickname “The California Kid.”",["hof"]],
  ],[
    ["I built my reputation around speed, wrestling and guillotine attacks at the lighter weights.",["profile"]],
    ["Before the UFC had my weight classes, I became the face of a major U.S. promotion’s featherweight division.",["hof"]],
    ["I held that promotion’s championship for years and defended it repeatedly.",["hof"]],
    ["My UFC career began after the WEC merger.",["profile","hof"]],
    ["I earned multiple UFC title opportunities but never captured a UFC belt.",["stats"]],
    ["One of my strongest UFC stretches in 2013 included four wins in a single calendar year.",["stats"]],
    ["I submitted Michael McDonald in that run to earn another championship shot.",["stats"]],
    ["My final UFC comeback included a quick knockout of Ricky Simón at age 40.",["stats","profile"]],
    ["My gym produced multiple elite bantamweights, including future UFC champions and title challengers.",["profile","hof"]],
    ["The Hall of Famer known as “The California Kid” was a WEC champion and Team Alpha Male founder.",["hof"]],
  ]),
  identity("ufc:frank-mir","Frank Mir",{
    stats:"https://ufcstats.com/statistics/fighters",
    profile:"https://www.ufc.com/athlete/frank-mir",
  },[
    ["I made my UFC debut in 2001 and quickly became known for submissions at heavyweight.",["stats","profile"]],
    ["My early career featured several first-round submission wins over much larger opponents.",["stats"]],
    ["I won UFC gold less than three years after my Octagon debut.",["stats","profile"]],
    ["A serious motorcycle accident interrupted my first championship reign.",["profile"]],
    ["I won the heavyweight title by breaking Tim Sylvia’s arm with an armbar.",["stats","profile"]],
    ["Years later, I submitted Brock Lesnar in Lesnar’s UFC debut.",["stats","profile"]],
    ["I stopped Antônio Rodrigo Nogueira to win an interim heavyweight title.",["stats","profile"]],
    ["In a rematch, I became the first fighter to submit Nogueira.",["stats","profile"]],
    ["My UFC career included four separate championship fights across different eras.",["stats"]],
    ["My jiu-jitsu-heavy heavyweight résumé made me one of the division’s signature submission specialists.",["profile"]],
  ],[
    ["Brazilian jiu-jitsu was the foundation that separated me from many heavyweights of my era.",["profile"]],
    ["I entered the UFC before turning 23 and stayed connected to the promotion for more than a decade.",["stats","profile"]],
    ["My first two UFC wins both came by submission.",["stats"]],
    ["I later captured a vacant championship with one of the fastest title-fight submissions of the era.",["stats"]],
    ["An accident outside the cage forced me away from competition and cost me the belt.",["profile"]],
    ["I rebuilt my career enough to win interim gold several years later.",["stats","profile"]],
    ["My rivalry with Brock Lesnar produced one submission win and one championship loss.",["stats"]],
    ["I later broke Antônio Rodrigo Nogueira’s arm with a kimura in their rematch.",["stats","profile"]],
    ["I also fought Junior dos Santos for the undisputed heavyweight championship.",["stats"]],
    ["The former heavyweight champion is one of the most decorated submission artists in UFC heavyweight history.",["profile"]],
  ]),
  identity("ufc:alistair-overeem","Alistair Overeem",{
    stats:"https://ufcstats.com/statistics/fighters",
    profile:"https://www.ufc.com/athlete/alistair-overeem",
  },[
    ["I arrived in the UFC with an unusually deep résumé from other combat-sports organizations.",["profile"]],
    ["My background included both high-level MMA and elite kickboxing competition.",["profile"]],
    ["I made my UFC debut in 2011 with a first-round stoppage.",["stats"]],
    ["My UFC run mixed spectacular wins with several knockout losses in a dangerous heavyweight era.",["stats","profile"]],
    ["I stopped Brock Lesnar with a body kick and follow-up strikes in my Octagon debut.",["stats","profile"]],
    ["Later wins over Junior dos Santos and Andrei Arlovski earned me a title shot.",["stats"]],
    ["I challenged Stipe Miocic for the UFC heavyweight championship in 2016.",["stats","profile"]],
    ["I dropped the champion early but was later stopped in the first round.",["stats","profile"]],
    ["Outside the UFC, I won the Strikeforce heavyweight title and the K-1 World Grand Prix.",["profile"]],
    ["My career is one of the rare résumés to include elite accomplishments in UFC, PRIDE-era MMA, Strikeforce and K-1.",["profile"]],
  ],[
    ["I competed professionally for many years before ever stepping into the UFC.",["profile"]],
    ["My striking base was strong enough to produce championships in kickboxing as well as MMA.",["profile"]],
    ["I moved through several major promotions across Japan, Europe and the United States.",["profile"]],
    ["By the time I reached the Octagon, I was already a veteran with dozens of professional fights.",["profile"]],
    ["My UFC debut was a high-profile heavyweight bout that ended in under three minutes.",["stats"]],
    ["I later assembled a four-fight winning streak to earn a UFC championship opportunity.",["stats"]],
    ["That run included a knockout of Junior dos Santos.",["stats","profile"]],
    ["I fought Stipe Miocic for the UFC heavyweight title in Cleveland.",["stats"]],
    ["My non-UFC résumé includes Strikeforce heavyweight gold and a K-1 Grand Prix championship.",["profile"]],
    ["Known as “The Reem,” I became one of the most accomplished crossover heavyweight strikers in MMA history.",["profile"]],
  ]),
  identity("ufc:rich-franklin","Rich Franklin",{
    stats:"https://ufcstats.com/statistics/fighters",
    profile:"https://www.ufc.com/athlete/rich-franklin",
    hof:"https://www.ufc.com/news/ufc-rich-franklin-embodied-we-are-all-fighters-mantra-hall-of-fame",
  },[
    ["Before fighting full time, I worked as a high school teacher.",["hof"]],
    ["I became one of the UFC’s most visible ambassadors during the sport’s mid-2000s growth.",["hof"]],
    ["My early UFC run featured wins at both middleweight and light heavyweight.",["stats"]],
    ["I won championship gold in 2005.",["stats","profile"]],
    ["I stopped Evan Tanner to capture the UFC middleweight title.",["stats","profile"]],
    ["I defended the belt against Nate Quarry and David Loiseau.",["stats"]],
    ["Anderson Silva ended my reign and later defeated me again in a rematch.",["stats","profile"]],
    ["I continued competing in major fights well after losing the title.",["stats","profile"]],
    ["Late-career wins included Chuck Liddell and a second victory over Wanderlei Silva.",["stats"]],
    ["The former math teacher and UFC middleweight champion entered the UFC Hall of Fame in 2019.",["hof"]],
  ],[
    ["I earned degrees in mathematics and education before my fighting career became full time.",["hof"]],
    ["My public image contrasted with many early stereotypes about professional fighters.",["hof"]],
    ["I entered the UFC in 2003 and quickly established myself with stoppage wins.",["stats"]],
    ["A move through multiple weight classes helped me remain relevant for years.",["stats","profile"]],
    ["My first title victory came by doctor stoppage in a rematch.",["stats"]],
    ["I then made two successful defenses of the middleweight championship.",["stats"]],
    ["A devastating clinch-striking specialist took the belt from me in 2006.",["stats","profile"]],
    ["I later fought at catchweight and light heavyweight against several former champions.",["stats"]],
    ["My nickname “Ace” became one of the recognizable identities of the UFC’s post-TUF boom period.",["profile"]],
    ["I am the Hall of Fame former middleweight champion who taught high school math before becoming a full-time fighter.",["hof"]],
  ]),
  identity("ufc:carlos-condit","Carlos Condit",{
    stats:"https://ufcstats.com/statistics/fighters",
    profile:"https://www.ufc.com/athlete/carlos-condit",
  },[
    ["I entered the UFC in 2009 after already winning a major welterweight championship elsewhere.",["profile"]],
    ["My style was built around pace, knees, kicks and a willingness to engage in chaotic fights.",["profile"]],
    ["I lost my UFC debut by split decision before winning five straight.",["stats"]],
    ["That streak pushed me into an interim-title opportunity.",["stats","profile"]],
    ["I beat Nick Diaz over five rounds to win the interim UFC welterweight championship.",["stats","profile"]],
    ["I then challenged Georges St-Pierre in a title-unification bout.",["stats"]],
    ["A head kick briefly dropped the champion, but I lost the fight by decision.",["stats","profile"]],
    ["I later challenged Robbie Lawler for the undisputed title in a close five-round fight.",["stats","profile"]],
    ["Before the UFC, I was the final WEC welterweight champion.",["profile"]],
    ["Known as “The Natural Born Killer,” I became associated with one of the most aggressive striking styles of my era.",["profile"]],
  ],[
    ["I built a reputation as a finisher long before reaching the UFC.",["profile"]],
    ["My pre-UFC career included championship success in the WEC.",["profile"]],
    ["Inside the Octagon, I became known for absorbing pressure and answering with combinations, knees and kicks.",["profile"]],
    ["My early UFC run included a dramatic late stoppage in a fight I had been losing.",["stats"]],
    ["I knocked out Dan Hardy and Dong Hyun Kim in consecutive fights.",["stats"]],
    ["I won interim gold by outpointing Nick Diaz in 2012.",["stats","profile"]],
    ["I later fought Georges St-Pierre and Robbie Lawler for undisputed UFC gold.",["stats"]],
    ["My title fight with Lawler became especially remembered for its violent fifth round.",["profile"]],
    ["I finished my UFC career with victories over Court McGee and Matt Brown before one final bout.",["stats"]],
    ["The former WEC and interim UFC welterweight champion carried the nickname “The Natural Born Killer.”",["profile"]],
  ]),
  identity("ufc:matt-serra","Matt Serra",{
    stats:"https://ufcstats.com/statistics/fighters",
    profile:"https://www.ufc.com/athlete/matt-serra",
    hof:"https://www.ufc.com/hof/matt-serra",
  },[
    ["I spent years in the UFC before ever receiving a championship opportunity.",["stats","profile"]],
    ["My background was rooted in Brazilian jiu-jitsu and submission grappling.",["profile"]],
    ["I competed at lightweight before later moving permanently to welterweight.",["stats"]],
    ["A reality-show comeback changed the direction of my career.",["profile","hof"]],
    ["I won The Ultimate Fighter 4 welterweight tournament by decision.",["stats","profile"]],
    ["That victory earned me a title shot against Georges St-Pierre.",["stats","profile"]],
    ["I scored one of UFC history’s biggest upsets by stopping him in the first round.",["stats","hof"]],
    ["I lost the championship in the rematch the following year.",["stats"]],
    ["I later fought Matt Hughes in a long-discussed grudge match.",["stats","profile"]],
    ["The Long Island jiu-jitsu black belt became a UFC Hall of Famer and prominent coach after his fighting career.",["hof"]],
  ],[
    ["I was a decorated submission grappler before I became a UFC champion.",["profile"]],
    ["My early Octagon years were spent mostly around the lightweight division.",["stats"]],
    ["I never built a long winning streak in the UFC before my championship moment.",["stats"]],
    ["Instead, my breakthrough came through a veteran season of The Ultimate Fighter.",["profile"]],
    ["I edged Chris Lytle in the finale to earn a title opportunity.",["stats"]],
    ["I entered that championship fight as a massive underdog.",["hof"]],
    ["I hurt Georges St-Pierre with punches and finished him in Round 1 to win the welterweight belt.",["stats","hof"]],
    ["The rematch took place in Montreal and ended with me losing by second-round stoppage.",["stats"]],
    ["I later became closely associated with coaching fighters such as Chris Weidman and Aljamain Sterling.",["profile","hof"]],
    ["I am the Hall of Fame winner of The Ultimate Fighter 4 who authored the famous 2007 upset of Georges St-Pierre.",["hof"]],
  ]),
  identity("ufc:luke-rockhold","Luke Rockhold",{
    stats:"https://ufcstats.com/statistics/fighters",
    profile:"https://www.ufc.com/athlete/luke-rockhold",
  },[
    ["I entered the UFC in 2013 as a champion from another major promotion.",["profile"]],
    ["My game combined southpaw kicking with strong top control and submission skills.",["profile"]],
    ["My UFC debut ended in a first-round knockout loss.",["stats"]],
    ["I responded by winning four straight fights, all by stoppage.",["stats","profile"]],
    ["That run included submissions of Tim Boetsch and Michael Bisping.",["stats"]],
    ["I then submitted Lyoto Machida to earn a UFC title opportunity.",["stats","profile"]],
    ["I stopped Chris Weidman in the fourth round to win the middleweight championship.",["stats","profile"]],
    ["I lost the belt in my first defense when a late replacement knocked me out.",["stats","profile"]],
    ["Before the UFC, I had been the Strikeforce middleweight champion.",["profile"]],
    ["My career later extended into grappling, boxing and other crossover combat-sports appearances.",["profile"]],
  ],[
    ["A strong kicking game and elite jiu-jitsu made me dangerous both standing and on top.",["profile"]],
    ["I reached the UFC after a long unbeaten run in Strikeforce.",["profile"]],
    ["My first Octagon fight went badly, but I quickly rebuilt.",["stats"]],
    ["I finished each of my next four UFC opponents before receiving a title shot.",["stats"]],
    ["A body kick stoppage began that surge.",["stats"]],
    ["I later beat Michael Bisping and Lyoto Machida by submission.",["stats"]],
    ["My championship win came by ground-and-pound against Chris Weidman.",["stats","profile"]],
    ["Bisping then knocked me out in their rematch to take the belt.",["stats","profile"]],
    ["I later moved to light heavyweight and fought Jan Błachowicz before a final UFC bout with Paulo Costa.",["stats"]],
    ["The former Strikeforce and UFC middleweight champion became known for elite kicks, top pressure and outspoken confidence.",["profile"]],
  ]),
  identity("ufc:yoel-romero","Yoel Romero",{
    stats:"https://ufcstats.com/statistics/fighters",
    profile:"https://www.ufc.com/athlete/yoel-romero",
  },[
    ["Before MMA, I reached the highest levels of international freestyle wrestling.",["profile"]],
    ["I entered the UFC in my mid-30s and still became a title contender.",["profile"]],
    ["My first four UFC wins included three knockouts.",["stats"]],
    ["Explosive athleticism and sudden bursts became hallmarks of my fighting style.",["profile"]],
    ["I stopped Tim Kennedy in a famous comeback fight after a chaotic break between rounds.",["stats","profile"]],
    ["I later knocked out Chris Weidman with a flying knee at Madison Square Garden.",["stats","profile"]],
    ["I fought Robert Whittaker for interim middleweight gold in 2017 and lost by decision.",["stats"]],
    ["I knocked out Luke Rockhold in my next fight but was ineligible to win interim gold after missing weight.",["stats","profile"]],
    ["I later challenged Israel Adesanya for the undisputed middleweight championship.",["stats"]],
    ["My wrestling résumé included an Olympic silver medal and a world championship before my MMA career.",["profile"]],
  ],[
    ["My athletic career was already internationally decorated before I ever fought in the UFC.",["profile"]],
    ["Unlike many elite wrestlers, I became especially dangerous in MMA through explosive counterstriking.",["profile"]],
    ["I began my UFC run with a string of wins after the age when many fighters are already declining.",["stats"]],
    ["Several of my biggest finishes came in the third round after patient starts.",["stats"]],
    ["I stopped Lyoto Machida and Chris Weidman during my rise.",["stats"]],
    ["My first championship opportunity came against Robert Whittaker for an interim belt.",["stats"]],
    ["Our rematch was also scheduled for a title, but I missed the championship weight limit.",["profile"]],
    ["I later fought Paulo Costa in one of the division’s most physical three-round battles.",["stats","profile"]],
    ["My final UFC appearance was a five-round title fight with Israel Adesanya.",["stats"]],
    ["The Cuban Olympic silver medalist wrestler became one of the UFC middleweight division’s most explosive knockout threats.",["profile"]],
  ]),
  identity("ufc:ken-shamrock","Ken Shamrock",{
    stats:"https://ufcstats.com/statistics/fighters",
    profile:"https://www.ufc.com/athlete/ken-shamrock",
    hof:"https://www.ufc.com/hof/ken-shamrock",
  },[
    ["My mixed-martial-arts career began before the UFC’s first event.",["profile","hof"]],
    ["I became a major figure in both American and Japanese early no-holds-barred fighting.",["hof"]],
    ["My first UFC years came in open-weight tournaments and superfights rather than modern divisions.",["stats","hof"]],
    ["Submission grappling was central to my reputation during that era.",["profile"]],
    ["I fought Royce Gracie to a long draw in one of the promotion’s earliest major rematches.",["stats","hof"]],
    ["I beat Dan Severn by submission to win the UFC Superfight Championship.",["stats","hof"]],
    ["My rivalry with Severn continued in a title rematch the next year.",["stats"]],
    ["After years away, I returned to the UFC in 2002 for a title fight with Tito Ortiz.",["stats","profile"]],
    ["Outside MMA, I also became a major professional-wrestling personality in WWE.",["profile","hof"]],
    ["Known as “The World’s Most Dangerous Man,” I entered the UFC Hall of Fame as a Pioneer Wing figure.",["hof"]],
  ],[
    ["I competed in Pancrase during the earliest years of modern mixed martial arts.",["profile","hof"]],
    ["My career blurred the lines between shoot fighting, submission grappling and professional wrestling.",["hof"]],
    ["I appeared in the UFC before weight classes or gloves were standard.",["stats","hof"]],
    ["My early UFC résumé included tournament bouts and Superfight Championship matches.",["stats"]],
    ["I shared a famous 36-minute fight with Royce Gracie at UFC 5.",["stats","hof"]],
    ["I later submitted Dan Severn to claim the Superfight title.",["stats"]],
    ["A second bout with Severn became one of the early era’s most controversial title fights.",["stats","hof"]],
    ["My long layoff from the Octagon ended with a 2002 championship fight.",["stats"]],
    ["A trilogy with Tito Ortiz became a major part of my later UFC career.",["stats","profile"]],
    ["The UFC pioneer and WWE star was famously billed as “The World’s Most Dangerous Man.”",["hof"]],
  ]),
  identity("ufc:joshua-van","Joshua Van",{
    stats:"https://ufcstats.com/statistics/fighters",
    profile:"https://www.ufc.com/athlete/joshua-van",
    title:"https://www.ufc.com/news/flyweight-champion-joshua-van-set-rematch-alexandre-pantoja-cryptocom-ufc-331",
  },[
    ["I entered the UFC in 2023 as a young flyweight prospect.",["stats","profile"]],
    ["My early rise was built on pace, boxing combinations and the ability to win long striking exchanges.",["profile"]],
    ["I won my first three UFC appearances before suffering my first Octagon loss.",["stats"]],
    ["I responded to that setback with a rapid climb through the division.",["stats","profile"]],
    ["In 2025, I won three UFC fights in less than four months.",["stats","profile"]],
    ["The third of those was a high-paced decision over Brandon Royval.",["stats","profile"]],
    ["That victory earned me a flyweight title opportunity before the end of the year.",["profile","title"]],
    ["I won UFC gold when Alexandre Pantoja suffered an arm injury early in our title fight.",["stats","title"]],
    ["I defended the belt in 2026 by stopping Tatsuro Taira in the fifth round.",["stats","title"]],
    ["I later defeated Pantoja again in their rematch at UFC 331.",["title"]],
  ],[
    ["I was born in Myanmar and built my professional career in the United States.",["profile"]],
    ["My fighting style is centered on pressure boxing and unusually high output for the flyweight division.",["profile"]],
    ["I joined the UFC while still in my early 20s.",["profile"]],
    ["After one loss in 2024, I began a long winning run.",["stats"]],
    ["I beat Rei Tsuruya and Bruno Silva during the first half of 2025.",["stats"]],
    ["A short-notice matchup with Brandon Royval became one of the year’s most acclaimed fights.",["stats","profile"]],
    ["I won that decision and jumped directly into the championship picture.",["stats","title"]],
    ["My first title win came after an injury to Alexandre Pantoja only seconds into the bout.",["stats","title"]],
    ["I then earned a fifth-round TKO over Tatsuro Taira for my first successful defense.",["stats","title"]],
    ["The Myanmar-born champion rose from unranked prospect to UFC flyweight titleholder during a breakout 2025.",["profile","title"]],
  ]),
];
