import type { UfcWhoAmIAuthoredIdentity } from "./ufcWhoAmIAuthoredScripts";

const BANDS = ["broad","broad","helpful","helpful","helpful","strong","strong","strong","giveaway","giveaway"] as const;
type Row = readonly [text: string, sourceIds: readonly string[]];

function identity(
  subjectId: string,
  name: string,
  sources: Readonly<Record<string,string>>,
  a: readonly Row[],
  b: readonly Row[],
): UfcWhoAmIAuthoredIdentity {
  const slug = subjectId.slice(4);
  const script = (id: "A"|"B", rows: readonly Row[]) => ({
    id,
    clues: rows.map(([text, sourceIds], i) => ({
      id: `ufc-${slug}-${id.toLowerCase()}-${i+1}`,
      text,
      band: BANDS[i]!,
      verification: "verified" as const,
      sourceIds,
    })),
  });
  return { subjectId, name, earlyRotation: "normal", sources, scripts: { A: script("A",a), B: script("B",b) } };
}

export const ufcWhoAmIAuthoredExpansion2026A: readonly UfcWhoAmIAuthoredIdentity[] = [
  identity("ufc:jiri-prochazka","Jiří Procházka",{
    stats:"https://ufcstats.com/statistics/fighters",
    profile:"https://www.ufc.com/athlete/jiri-prochazka",
    feature:"https://www.ufc.com/news/jiri-prochazka-path-champion",
  },[
    ["Before joining the UFC, I had already built a reputation as an aggressive finisher in a major Japanese promotion.",["profile","feature"]],
    ["My UFC debut came in 2020, and my first two Octagon appearances both ended by knockout.",["stats","profile"]],
    ["I needed only those two UFC wins to earn my first championship opportunity.",["stats","profile"]],
    ["My first UFC title fight became a five-round battle that ended inside the final minute.",["stats","profile"]],
    ["I won that vacant light heavyweight championship with a late fifth-round submission of Glover Teixeira.",["stats","profile"]],
    ["A shoulder injury led me to vacate the championship before I could defend it.",["profile","feature"]],
    ["I later fought Alex Pereira twice for UFC light heavyweight gold and was stopped both times.",["stats","profile"]],
    ["I rebounded from the first of those losses with a stoppage win over Aleksandar Rakić.",["stats","profile"]],
    ["My pre-UFC résumé included winning the RIZIN light heavyweight championship.",["profile","feature"]],
    ["My unorthodox movement, high-volume offense and samurai-inspired public persona became signatures of my UFC identity.",["profile","feature"]],
  ],[
    ["I came to the UFC after competing extensively in Europe and Japan rather than through a long regional U.S. circuit.",["profile","feature"]],
    ["My style is built around pressure, stance switches and attacks from unusual angles.",["profile"]],
    ["I opened my UFC career by knocking out a former title challenger in the second round.",["stats","profile"]],
    ["My second UFC fight ended with a spinning-elbow knockout in the second round.",["stats","profile"]],
    ["Those two wins put me into a vacant-title fight in only my third UFC appearance.",["stats","profile"]],
    ["I survived deep trouble before submitting Glover Teixeira with less than a minute left in Round 5.",["stats","profile"]],
    ["After giving up the belt because of injury, I returned directly into another championship path.",["profile","feature"]],
    ["I later stopped Jamahal Hill and Khalil Rountree Jr. in consecutive fights.",["stats"]],
    ["I fought Carlos Ulberg for the light heavyweight title in 2026 and was stopped in the opening round.",["stats","profile"]],
    ["The former RIZIN champion from the Czech Republic is known for a wild, risk-heavy striking style.",["profile","feature"]],
  ]),
  identity("ufc:magomed-ankalaev","Magomed Ankalaev",{
    stats:"https://ufcstats.com/statistics/fighters",
    profile:"https://www.ufc.com/athlete/magomed-ankalaev",
    title:"https://www.ufc.com/athlete/magomed-ankalaev",
  },[
    ["I entered the UFC in 2018 after beginning my professional MMA career four years earlier.",["profile"]],
    ["My Octagon debut ended in a submission loss with only seconds remaining.",["stats","profile"]],
    ["I answered that debut loss by putting together one of the division’s longest unbeaten stretches.",["stats","profile"]],
    ["My rise mixed knockout wins with increasingly patient decision victories over ranked opposition.",["stats","profile"]],
    ["A 2022 vacant-title fight ended in a draw rather than producing a new champion.",["stats","profile"]],
    ["I later knocked out Johnny Walker in a rematch after our first meeting ended as a no contest.",["stats","profile"]],
    ["I defeated Aleksandar Rakić by decision to strengthen my claim to another title shot.",["stats","profile"]],
    ["In March 2025, I beat Alex Pereira by unanimous decision to win the UFC light heavyweight championship.",["stats","profile"]],
    ["My reign ended seven months later when Pereira stopped me in the first round of their rematch.",["stats","profile"]],
    ["I returned in 2026 with a fifth-round stoppage win over Bogdan Guskov.",["stats","profile"]],
  ],[
    ["My MMA base grew out of combat sambo and a measured southpaw striking game.",["profile"]],
    ["I became known for controlling distance and limiting opponents’ clean offense rather than relying only on highlight finishes.",["profile"]],
    ["After losing my first UFC fight, I went years without another official defeat.",["stats","profile"]],
    ["During that run I beat the same opponent twice by knockout in 2020.",["stats"]],
    ["I also defeated former title challengers at light heavyweight while steadily moving up the rankings.",["stats","profile"]],
    ["My first UFC championship bout was against Jan Błachowicz and finished as a split draw.",["stats","profile"]],
    ["A later title eliminator win over Aleksandar Rakić finally led me back to championship gold.",["stats","profile"]],
    ["I took the belt from Alex Pereira over five rounds at UFC 313.",["stats","profile"]],
    ["Pereira reclaimed it from me with a first-round stoppage at UFC 320.",["stats","profile"]],
    ["I am the former UFC light heavyweight champion whose first career UFC loss came to a last-second Paul Craig triangle choke.",["stats","profile"]],
  ]),
  identity("ufc:jan-blachowicz","Jan Błachowicz",{
    stats:"https://ufcstats.com/statistics/fighters",
    profile:"https://www.ufc.com/athlete/jan-blachowicz",
  },[
    ["I arrived in the UFC in 2014 after winning championships in European MMA.",["profile"]],
    ["My first several UFC years were uneven, and I had to rebuild after losing four of five fights.",["stats","profile"]],
    ["A long turnaround run eventually carried me from fringe contender to championship level.",["stats","profile"]],
    ["Power in my left hand became a defining part of my late-career rise.",["profile"]],
    ["I stopped Luke Rockhold and Corey Anderson during the surge that earned me a vacant-title opportunity.",["stats","profile"]],
    ["I knocked out Dominick Reyes in 2020 to become UFC light heavyweight champion.",["stats","profile"]],
    ["My first defense was a five-round decision win over unbeaten middleweight champion Israel Adesanya.",["stats","profile"]],
    ["Glover Teixeira submitted me in my next title defense.",["stats","profile"]],
    ["I later fought Magomed Ankalaev to a draw for the vacant light heavyweight championship.",["stats","profile"]],
    ["The phrase “Legendary Polish Power” became closely tied to my championship run.",["profile"]],
  ],[
    ["Before my UFC title run, I spent years fighting through setbacks rather than taking a direct path to the top.",["profile"]],
    ["I entered the promotion with a strong kickboxing base and significant experience outside the UFC.",["profile"]],
    ["My breakthrough came after I learned to pair patient counterstriking with heavy power.",["profile"]],
    ["I scored important late-career wins over former champions and top contenders at 205 pounds.",["stats","profile"]],
    ["A knockout of Corey Anderson put me squarely into the title picture.",["stats","profile"]],
    ["I won vacant gold by stopping Dominick Reyes in Abu Dhabi.",["stats","profile"]],
    ["I became the first man to hand Israel Adesanya a professional MMA loss when I defended the belt.",["stats","profile"]],
    ["After losing the title, I remained in the division’s elite and later drew in another vacant-title fight.",["stats","profile"]],
    ["I shared the Octagon with Alex Pereira, Magomed Ankalaev and Carlos Ulberg late in my career.",["stats"]],
    ["I am the Polish former UFC light heavyweight champion known for “Legendary Polish Power.”",["profile"]],
  ]),
  identity("ufc:jamahal-hill","Jamahal Hill",{
    stats:"https://ufcstats.com/statistics/fighters",
    profile:"https://www.ufc.com/athlete/jamahal-hill",
  },[
    ["I reached the UFC through Dana White’s Contender Series.",["profile"]],
    ["I built my rise around a southpaw striking game and knockout power at light heavyweight.",["profile"]],
    ["One early UFC win was later changed to a no contest.",["stats","profile"]],
    ["My first UFC defeat came in a fight where I suffered a serious arm injury.",["stats","profile"]],
    ["I answered that setback with a string of stoppage wins.",["stats","profile"]],
    ["Knockouts of Jimmy Crute and Johnny Walker pushed me toward the top of the division.",["stats","profile"]],
    ["I stopped Thiago Santos in the fourth round of my first UFC main event.",["stats","profile"]],
    ["I won the vacant light heavyweight title by beating Glover Teixeira over five rounds in Brazil.",["stats","profile"]],
    ["An Achilles injury caused me to vacate the championship before making a defense.",["profile"]],
    ["I returned from that layoff directly into a title fight with Alex Pereira at UFC 300.",["stats","profile"]],
  ],[
    ["My professional MMA career began relatively late compared with many elite fighters.",["profile"]],
    ["I was one of the early Contender Series graduates to later become a UFC champion.",["profile"]],
    ["My UFC game became known for long-range boxing and finishing power rather than a wrestling-first approach.",["profile"]],
    ["After a 2021 loss, I produced three straight knockout or TKO victories.",["stats"]],
    ["That run included a one-punch finish of a future title challenger.",["stats","profile"]],
    ["I accepted a vacant-title fight on short notice after the division’s championship picture changed.",["profile"]],
    ["I defeated Glover Teixeira by unanimous decision to become champion in January 2023.",["stats","profile"]],
    ["I voluntarily gave up the belt after rupturing my Achilles tendon.",["profile"]],
    ["My first fight back was the UFC 300 main event against Alex Pereira.",["stats","profile"]],
    ["Known as “Sweet Dreams,” I became UFC light heavyweight champion after entering through the Contender Series.",["profile"]],
  ]),
  identity("ufc:carlos-ulberg","Carlos Ulberg",{
    stats:"https://ufcstats.com/statistics/fighters",
    profile:"https://www.ufc.com/athlete/carlos-ulberg",
    title:"https://www.ufc.com/athlete/carlos-ulberg",
  },[
    ["I came to MMA with a substantial kickboxing background.",["profile"]],
    ["My UFC debut in 2021 ended in a knockout loss after a wild first-round fight.",["stats","profile"]],
    ["I rebuilt from that defeat with a long winning streak at light heavyweight.",["stats","profile"]],
    ["My early UFC surge featured several first-round knockouts.",["stats","profile"]],
    ["I also showed a submission side by finishing Da Woon Jung with a rear-naked choke.",["stats","profile"]],
    ["A 12-second knockout of Alonzo Menifield became one of the fastest finishes in UFC light heavyweight history.",["profile"]],
    ["I later beat former champion Jan Błachowicz by decision.",["stats","profile"]],
    ["A first-round knockout of Dominick Reyes put me in championship position.",["stats","profile"]],
    ["In April 2026, I knocked out Jiří Procházka to win the UFC light heavyweight title.",["stats","profile"]],
    ["I became one of the Contender Series alumni to capture a UFC championship.",["profile"]],
  ],[
    ["Before the UFC, my combat-sports résumé was built heavily in kickboxing rather than wrestling.",["profile"]],
    ["I train out of the same New Zealand camp that produced multiple UFC champions and title challengers.",["profile"]],
    ["After losing my first UFC appearance, I did not lose again on the road to the title.",["stats","profile"]],
    ["My streak mixed quick knockouts with decisions against seasoned ranked opponents.",["stats"]],
    ["I stopped Nicolae Negumereanu and Ihor Potieria in consecutive UFC appearances.",["stats"]],
    ["I later outpointed Volkan Oezdemir before facing a former champion.",["stats"]],
    ["That former champion was Jan Błachowicz, whom I defeated over three rounds.",["stats","profile"]],
    ["I then knocked out Dominick Reyes in the opening round.",["stats","profile"]],
    ["My championship win came by first-round knockout over Jiří Procházka at UFC 327.",["stats","profile"]],
    ["The New Zealand kickboxer became UFC light heavyweight champion in 2026 after entering the promotion through the Contender Series.",["profile"]],
  ]),
  identity("ufc:arman-tsarukyan","Arman Tsarukyan",{
    stats:"https://ufcstats.com/statistics/fighters",
    profile:"https://www.ufc.com/athlete/arman-tsarukyan",
  },[
    ["I made my UFC debut in 2019 against an opponent who would later become champion.",["stats","profile"]],
    ["Although I lost that debut by decision, my wrestling exchanges immediately raised my profile.",["profile"]],
    ["I followed the loss with five straight UFC victories.",["stats"]],
    ["My game blends strong takedowns with increasingly dangerous striking.",["profile"]],
    ["A competitive five-round loss in 2022 slowed my first push toward the top.",["stats","profile"]],
    ["I responded with a three-fight streak capped by a first-round knockout of Beneil Dariush.",["stats","profile"]],
    ["At UFC 300, I defeated Charles Oliveira by split decision.",["stats","profile"]],
    ["That win earned me a championship opportunity, but I withdrew from the scheduled bout during fight week.",["profile"]],
    ["I returned in 2025 and submitted Dan Hooker in the second round.",["stats","profile"]],
    ["My UFC debut opponent was Islam Makhachev, and my path eventually brought me back near the top of the same lightweight division.",["stats","profile"]],
  ],[
    ["I grew into elite MMA through a wrestling-heavy style developed from a young age.",["profile"]],
    ["My early UFC résumé showed that I could compete with top-level grapplers before I had much name recognition.",["profile"]],
    ["For several years I won mostly by decisions while sharpening my striking.",["stats"]],
    ["Later in my rise, stoppages became a bigger part of my offense.",["stats","profile"]],
    ["I knocked out Joaquim Silva and then Beneil Dariush in consecutive fights.",["stats"]],
    ["A matchup with a former lightweight champion at UFC 300 became the biggest win of my career to that point.",["stats","profile"]],
    ["I edged Charles Oliveira by split decision in that fight.",["stats","profile"]],
    ["I was booked to challenge for UFC gold in early 2025 but did not make the walk because of injury.",["profile"]],
    ["My next Octagon appearance ended with a submission of Dan Hooker.",["stats","profile"]],
    ["The Armenian-Russian lightweight first announced himself by giving Islam Makhachev a difficult UFC debut fight in 2019.",["stats","profile"]],
  ]),
  identity("ufc:cory-sandhagen","Cory Sandhagen",{
    stats:"https://ufcstats.com/statistics/fighters",
    profile:"https://www.ufc.com/athlete/cory-sandhagen",
  },[
    ["I entered the UFC in 2018 and won my first five appearances.",["stats","profile"]],
    ["My style became known for constant stance changes, movement and creative striking.",["profile"]],
    ["One early UFC win came by triangle choke, but most of my biggest moments came on the feet.",["stats"]],
    ["My first UFC loss ended in under two minutes by submission.",["stats","profile"]],
    ["I answered that loss with a spinning-kick knockout in my next fight.",["stats","profile"]],
    ["I then produced a 28-second flying-knee knockout of Frankie Edgar.",["stats","profile"]],
    ["A close decision loss to T.J. Dillashaw preceded my first UFC championship fight.",["stats","profile"]],
    ["I lost an interim bantamweight title fight to Petr Yan over five rounds.",["stats","profile"]],
    ["Later title opportunities included championship fights with Merab Dvalishvili.",["stats","profile"]],
    ["My résumé spans elite bantamweights across multiple generations, with highlight finishes among the division’s most recognizable.",["stats","profile"]],
  ],[
    ["Before becoming a UFC contender, I worked as a youth wrestling coach while developing my MMA career.",["profile"]],
    ["I have built my offense around range, feints and attacks from unusual angles.",["profile"]],
    ["I won my UFC debut by second-round TKO and followed it with another stoppage.",["stats"]],
    ["My first major contender run included wins over John Lineker and Raphael Assunção.",["stats"]],
    ["A first-round submission loss forced me to rebuild near the top of the division.",["stats"]],
    ["I did that with consecutive knockouts of Marlon Moraes and Frankie Edgar.",["stats","profile"]],
    ["I later headlined five-round fights against Song Yadong and Rob Font and won both.",["stats"]],
    ["I also defeated Marlon Vera by decision in a high-profile main event.",["stats","profile"]],
    ["My first title fight was for interim gold against Petr Yan.",["stats","profile"]],
    ["The rangy Colorado-based bantamweight is closely associated with a flying-knee knockout of Frankie Edgar.",["profile"]],
  ]),
  identity("ufc:umar-nurmagomedov","Umar Nurmagomedov",{
    stats:"https://ufcstats.com/statistics/fighters",
    profile:"https://www.ufc.com/athlete/umar-nurmagomedov",
  },[
    ["I entered the UFC unbeaten in 2021.",["stats","profile"]],
    ["My first two UFC wins both came by submission.",["stats"]],
    ["I combine a wrestling-heavy base with a kicking game that is more active than many expect from my grappling pedigree.",["profile"]],
    ["My first UFC knockout came in 2023.",["stats","profile"]],
    ["A five-round win in 2024 established me as a championship-level bantamweight.",["stats","profile"]],
    ["I defeated Cory Sandhagen by unanimous decision in that main event.",["stats","profile"]],
    ["That victory led to my first UFC title shot.",["stats","profile"]],
    ["I lost a five-round decision to Merab Dvalishvili for the bantamweight championship in 2025.",["stats","profile"]],
    ["I rebounded with wins over Mario Bautista and Deiveson Figueiredo.",["stats"]],
    ["My surname connects me to one of MMA’s most famous fighting families, but my UFC career has been built at bantamweight.",["profile"]],
  ],[
    ["I grew up around high-level grappling and combat-sambo training.",["profile"]],
    ["My MMA style mixes chain wrestling with long kicks and patient striking.",["profile"]],
    ["I won six straight UFC fights before receiving my first championship opportunity.",["stats"]],
    ["During that run I moved between featherweight and bantamweight before settling at 135 pounds.",["stats","profile"]],
    ["A first-round knockout of Raoni Barcelos showed my striking could finish fights as well as my grappling.",["stats","profile"]],
    ["I later went five rounds for the first time against a top contender.",["stats"]],
    ["That opponent was Cory Sandhagen, and I won a unanimous decision.",["stats","profile"]],
    ["My unbeaten professional record ended in a UFC bantamweight title fight with Merab Dvalishvili.",["stats","profile"]],
    ["I returned with a decision over Mario Bautista and then beat former flyweight champion Deiveson Figueiredo.",["stats"]],
    ["I am the bantamweight contender and cousin of Khabib Nurmagomedov.",["profile"]],
  ]),
  identity("ufc:belal-muhammad","Belal Muhammad",{
    stats:"https://ufcstats.com/statistics/fighters",
    profile:"https://www.ufc.com/athlete/belal-muhammad",
  },[
    ["My UFC career began in 2016, and I had to fight through multiple early setbacks.",["stats","profile"]],
    ["For years, my rise was built more on pace, wrestling and decisions than on highlight-reel finishes.",["profile"]],
    ["A 2019 loss became the last defeat before the long run that carried me to a title.",["stats"]],
    ["One fight during that run ended as a no contest because of an accidental eye poke.",["stats"]],
    ["I later beat several ranked veterans in succession to force my way into championship contention.",["stats","profile"]],
    ["A 2022 rematch win avenged one of my earlier UFC losses.",["stats","profile"]],
    ["I then stopped Sean Brady and defeated Gilbert Burns over five rounds.",["stats","profile"]],
    ["In 2024, I beat Leon Edwards by unanimous decision to win the UFC welterweight championship.",["stats","profile"]],
    ["Jack Della Maddalena ended my reign in my first title defense.",["stats","profile"]],
    ["The phrase “Remember the Name” became both my nickname and a running theme of my climb.",["profile"]],
  ],[
    ["I built my reputation on relentless pressure, conditioning and wrestling rather than one signature finishing technique.",["profile"]],
    ["My UFC path was unusually long for a future champion, stretching across years of contender fights.",["stats","profile"]],
    ["I beat Tim Means, Demian Maia and Stephen Thompson during different stages of that rise.",["stats"]],
    ["An accidental foul stopped a 2021 fight before a winner could be determined.",["stats"]],
    ["I later returned to defeat the same opponent who had knocked me out earlier in my UFC career.",["stats"]],
    ["A late stoppage of Sean Brady was one of the rare finishes in my contender run.",["stats","profile"]],
    ["I followed it by defeating Gilbert Burns in a five-round bout.",["stats","profile"]],
    ["My title win came in Manchester against Leon Edwards, whom I outworked over five rounds.",["stats","profile"]],
    ["I lost the championship to Jack Della Maddalena at UFC 315.",["stats","profile"]],
    ["I am the Chicago-raised Palestinian-American welterweight champion known as “Remember the Name.”",["profile"]],
  ]),
  identity("ufc:jack-della-maddalena","Jack Della Maddalena",{
    stats:"https://ufcstats.com/statistics/fighters",
    profile:"https://www.ufc.com/athlete/jack-della-maddalena",
    title:"https://www.ufc.com/news/dana-white-announces-title-fights-ufc-321-and-ufc-322",
  },[
    ["I began my professional career with two losses before turning it around dramatically.",["profile"]],
    ["I reached the UFC after earning a contract through Dana White’s Contender Series.",["profile"]],
    ["My first three UFC wins all came by first-round stoppage.",["stats","profile"]],
    ["Boxing combinations and body work became central to my welterweight style.",["profile"]],
    ["I later added a first-round submission win to show another layer of my game.",["stats","profile"]],
    ["A comeback knockout of Gilbert Burns in Round 3 became my breakthrough elite win.",["stats","profile"]],
    ["In 2025, I defeated Belal Muhammad over five rounds to win the UFC welterweight championship.",["stats","profile"]],
    ["My first title defense came at Madison Square Garden against a former lightweight champion.",["title","stats"]],
    ["Islam Makhachev beat me by unanimous decision to take the belt at UFC 322.",["stats","profile"]],
    ["I later returned in 2026 and was stopped by Carlos Prates.",["stats","profile"]],
  ],[
    ["I grew up in Australia and built my striking around clean boxing rather than a kick-heavy approach.",["profile"]],
    ["My early professional record started 0-2 before I went on a long winning run.",["profile"]],
    ["I entered the UFC in 2022 and immediately produced a series of fast finishes.",["stats"]],
    ["My first UFC decision wins came after I had already established myself as a knockout threat.",["stats"]],
    ["A split decision over Kevin Holland kept my unbeaten UFC run alive.",["stats","profile"]],
    ["I then rallied late to stop Gilbert Burns with a knee and follow-up strikes.",["stats","profile"]],
    ["That win eventually led to a title fight with Belal Muhammad.",["stats","profile"]],
    ["I outpointed Muhammad to become the UFC welterweight champion.",["stats","profile"]],
    ["My reign ended in my first defense when Islam Makhachev moved up a division and beat me over five rounds.",["stats","title"]],
    ["I am the Australian former welterweight champion whose surname is shared with the Perth gym scene that produced my rise.",["profile"]],
  ]),
  identity("ufc:ian-machado-garry","Ian Machado Garry",{
    stats:"https://ufcstats.com/statistics/fighters",
    profile:"https://www.ufc.com/athlete/ian-machado-garry",
    title:"https://www.ufc.com/news/ian-machado-garry-promise-fulfilled-ufc-330",
  },[
    ["I entered the UFC unbeaten in 2021.",["stats","profile"]],
    ["My debut ended with a first-round knockout at Madison Square Garden.",["stats","profile"]],
    ["I built my early run with a mix of decisions and striking stoppages.",["stats"]],
    ["For several years, my undefeated record was a major part of my identity as a prospect.",["profile"]],
    ["I beat experienced welterweights including Neil Magny and Geoff Neal during my rise.",["stats","profile"]],
    ["My first professional loss came by decision in late 2024.",["stats","profile"]],
    ["I rebounded with consecutive wins over Carlos Prates and Belal Muhammad.",["stats","profile"]],
    ["Those wins earned me a UFC welterweight title fight in 2026.",["title","profile"]],
    ["Islam Makhachev defeated me by unanimous decision at UFC 330.",["stats","title"]],
    ["I became the Irish welterweight contender who openly modeled parts of my career ambition on becoming a national MMA star.",["profile","title"]],
  ],[
    ["I won a major European regional championship before signing with the UFC.",["profile"]],
    ["My style is built around long-range striking, movement and confidence in open space.",["profile"]],
    ["I began my UFC career with seven consecutive victories.",["stats"]],
    ["A decision win over Michael Page extended that unbeaten run.",["stats","profile"]],
    ["My first defeat came in a close five-round fight with Shavkat Rakhmonov.",["stats","profile"]],
    ["I then returned with a five-round win over Carlos Prates.",["stats","profile"]],
    ["A later decision over former champion Belal Muhammad moved me to the front of the title line.",["stats","profile"]],
    ["I challenged for welterweight gold in Philadelphia in August 2026.",["title"]],
    ["That championship fight went all five rounds before Islam Makhachev won on the scorecards.",["stats","title"]],
    ["Known as “The Future,” I became one of Ireland’s highest-profile UFC contenders after starting my career unbeaten.",["profile"]],
  ]),
];
