import type { UfcWhoAmIAuthoredIdentity } from "./ufcWhoAmIAuthoredScripts";

const BANDS = ["broad","broad","helpful","helpful","helpful","strong","strong","strong","giveaway","giveaway"] as const;
type Row = readonly [text: string, sourceIds: readonly string[]];

function identity(
  subjectId: string,
  name: string,
  sources: Readonly<Record<string,string>>,
  a: readonly Row[],
  b: readonly Row[],
): UfcWhoAmIAuthoredIdentity {
  const slug = subjectId.slice(4);
  const script = (id: "A"|"B", rows: readonly Row[]) => ({
    id,
    clues: rows.map(([text, sourceIds], i) => ({
      id: `ufc-${slug}-${id.toLowerCase()}-${i+1}`,
      text,
      band: BANDS[i]!,
      verification: "verified" as const,
      sourceIds,
    })),
  });
  return { subjectId, name, earlyRotation: "normal", sources, scripts: { A: script("A",a), B: script("B",b) } };
}

export const ufcWhoAmIAuthoredExpansion2026C: readonly UfcWhoAmIAuthoredIdentity[] = [
  identity("ufc:brandon-royval","Brandon Royval",{
    stats:"https://ufcstats.com/statistics/fighters",
    profile:"https://www.ufc.com/athlete/brandon-royval",
  },[
    ["I entered the UFC in 2020 and immediately became known for frantic, high-volume fights.",["stats","profile"]],
    ["My style mixes scrambles, submissions and aggressive striking rather than patient point fighting.",["profile"]],
    ["My first two UFC appearances both ended with submission wins.",["stats"]],
    ["I then went through back-to-back losses before rebuilding into title contention.",["stats"]],
    ["I submitted Matt Schnell and then stopped Matheus Nicolau during that rebound.",["stats","profile"]],
    ["Those wins earned me a UFC flyweight title shot in late 2023.",["stats","profile"]],
    ["I lost that championship fight to Alexandre Pantoja by decision.",["stats","profile"]],
    ["I then defeated Brandon Moreno and Tatsuro Taira in consecutive five-round fights.",["stats"]],
    ["A 2025 fight with Joshua Van became one of the year’s most celebrated action bouts.",["stats","profile"]],
    ["Known as “Raw Dawg,” I built my reputation around chaos, pace and constant submission threats.",["profile"]],
  ],[
    ["I came to the UFC after championship-level success on the regional scene.",["profile"]],
    ["My fights frequently become scramble-heavy because I attack submissions from unusual positions.",["profile"]],
    ["I won my UFC debut by second-round submission.",["stats"]],
    ["My next win was another submission against a future title challenger.",["stats"]],
    ["After two straight losses, I put together a three-fight winning streak.",["stats"]],
    ["A first-round knockout of Matheus Nicolau secured my first title opportunity.",["stats","profile"]],
    ["I challenged Alexandre Pantoja for flyweight gold at UFC 296.",["stats"]],
    ["I later avenged an earlier loss by beating Brandon Moreno in Mexico City.",["stats","profile"]],
    ["My five-round win over Tatsuro Taira kept me near the top of the division.",["stats"]],
    ["The Denver-based flyweight contender is widely recognized by the nickname “Raw Dawg.”",["profile"]],
  ]),
  identity("ufc:michael-morales","Michael Morales",{
    stats:"https://ufcstats.com/statistics/fighters",
    profile:"https://www.ufc.com/athlete/michael-morales",
  },[
    ["I reached the UFC through Dana White’s Contender Series while still unbeaten.",["profile"]],
    ["My early UFC identity was built around length, athleticism and finishing power at welterweight.",["profile"]],
    ["I won my first two UFC fights by knockout.",["stats"]],
    ["I then showed I could win decisions against experienced opponents.",["stats"]],
    ["A late first-round stoppage in 2024 moved me into the ranked picture.",["stats","profile"]],
    ["I knocked out Gilbert Burns in the first round in 2025.",["stats","profile"]],
    ["Later that year, I stopped Sean Brady in another major welterweight test.",["stats","profile"]],
    ["That win kept my professional record unbeaten through the end of 2025.",["stats","profile"]],
    ["I became one of Ecuador’s most prominent UFC fighters during the rise.",["profile"]],
    ["My combination of an undefeated record and consecutive elite knockouts made me a major welterweight contender.",["profile"]],
  ],[
    ["I began combat sports young and developed a long, rangy striking style.",["profile"]],
    ["I entered the UFC as a Contender Series graduate rather than through The Ultimate Fighter.",["profile"]],
    ["My Octagon debut ended with a first-round knockout.",["stats"]],
    ["I followed it with another stoppage before winning back-to-back decisions.",["stats"]],
    ["A quick finish of Neil Magny became my first major veteran win.",["stats","profile"]],
    ["I then stopped Gilbert Burns with punches in the opening round.",["stats"]],
    ["At Madison Square Garden, I knocked out Sean Brady in the first round.",["stats"]],
    ["Those results pushed me rapidly from prospect status toward the title picture.",["profile"]],
    ["I carried Ecuadorian representation into the upper tier of the UFC welterweight division.",["profile"]],
    ["The unbeaten Contender Series graduate became known for a long reach and explosive finishing power.",["profile"]],
  ]),
  identity("ufc:carlos-prates","Carlos Prates",{
    stats:"https://ufcstats.com/statistics/fighters",
    profile:"https://www.ufc.com/athlete/carlos-prates",
  },[
    ["I entered the UFC in 2024 after earning a contract through Dana White’s Contender Series.",["profile"]],
    ["My striking background was built heavily around Muay Thai and kickboxing.",["profile"]],
    ["I won my first four UFC fights by knockout.",["stats"]],
    ["Those finishes quickly turned me from newcomer into a ranked welterweight.",["stats","profile"]],
    ["My first UFC loss came by decision in a five-round main event.",["stats"]],
    ["I rebounded by knocking out Geoff Neal.",["stats","profile"]],
    ["I then stopped former champion Leon Edwards in 2025.",["stats","profile"]],
    ["In 2026, I knocked out former welterweight champion Jack Della Maddalena.",["stats","profile"]],
    ["I became one of the most visible members of Brazil’s Fighting Nerds team.",["profile"]],
    ["My UFC rise was defined by unusually consistent knockout power at 170 pounds.",["profile"]],
  ],[
    ["Before the UFC, I spent years competing in striking-heavy combat sports and regional MMA.",["profile"]],
    ["My southpaw offense is built around patient pressure and heavy counters.",["profile"]],
    ["My first UFC victory came by second-round knockout.",["stats"]],
    ["Three more knockouts followed before I ever saw a UFC decision.",["stats"]],
    ["A five-round loss ended that opening knockout streak but not my rise.",["stats"]],
    ["I returned with a first-round knockout of Geoff Neal.",["stats"]],
    ["A later stoppage of Leon Edwards became my first win over a former UFC champion.",["stats","profile"]],
    ["I followed that with a 2026 knockout of Jack Della Maddalena.",["stats","profile"]],
    ["My team affiliation with the Fighting Nerds became part of my public identity.",["profile"]],
    ["The Brazilian welterweight Contender Series graduate became known for a string of knockouts over ranked opponents.",["profile"]],
  ]),
  identity("ufc:tim-kennedy","Tim Kennedy",{
    stats:"https://ufcstats.com/statistics/fighters",
    profile:"https://www.ufc.com/athlete/tim-kennedy",
  },[
    ["I entered the UFC in 2013 after years of high-level competition in other promotions.",["profile"]],
    ["My fighting style was built around wrestling, conditioning and physical pressure.",["profile"]],
    ["I won my first three UFC appearances.",["stats"]],
    ["That streak included a five-round main-event victory.",["stats"]],
    ["I defeated Michael Bisping by decision in 2014.",["stats","profile"]],
    ["My next fight became a controversial third-round stoppage loss to Yoel Romero.",["stats","profile"]],
    ["I returned more than two years later for one final UFC appearance.",["stats"]],
    ["Outside MMA, I served for years in the U.S. Army Special Forces.",["profile"]],
    ["I balanced military service with a professional fight career that included Strikeforce title opportunities.",["profile"]],
    ["The Green Beret and UFC middleweight contender became one of MMA’s best-known military crossover figures.",["profile"]],
  ],[
    ["I had already fought for championship gold outside the UFC before joining the promotion.",["profile"]],
    ["My MMA game emphasized top control and cardio more than flashy technique.",["profile"]],
    ["I debuted in the Octagon with a decision win in 2013.",["stats"]],
    ["My second UFC fight ended with a first-round knockout.",["stats"]],
    ["A dominant five-round win over Michael Bisping became one of my signature UFC performances.",["stats"]],
    ["I then faced Yoel Romero in a fight remembered for controversy surrounding the break before Round 3.",["stats","profile"]],
    ["That bout ended with me being stopped late in the third round.",["stats"]],
    ["My life outside the cage included combat deployments and service as an Army Special Forces soldier.",["profile"]],
    ["I later became publicly associated with veteran advocacy and military training work.",["profile"]],
    ["I am the UFC middleweight contender whose fighting career ran alongside service as a Green Beret.",["profile"]],
  ]),
  identity("ufc:brendan-schaub","Brendan Schaub",{
    stats:"https://ufcstats.com/statistics/fighters",
    profile:"https://www.ufc.com/athlete/brendan-schaub",
  },[
    ["I reached the UFC through a heavyweight season of The Ultimate Fighter.",["profile"]],
    ["My athletic background included football before I committed to mixed martial arts.",["profile"]],
    ["My first official UFC appearance came in a reality-show finale.",["stats"]],
    ["I then put together a four-fight UFC winning streak.",["stats"]],
    ["That run included a knockout of Mirko Cro Cop.",["stats","profile"]],
    ["I later submitted Matt Mitrione with a D’Arce choke.",["stats"]],
    ["My UFC career ended after a 2014 loss to Travis Browne.",["stats"]],
    ["After fighting, I became much more visible through podcasts and comedy than through MMA competition.",["profile"]],
    ["My media career included co-hosting a combat-sports podcast with Bryan Callen.",["profile"]],
    ["I am the former UFC heavyweight and TUF finalist who became a prominent podcast personality after retiring.",["profile"]],
  ],[
    ["Before MMA, I played college football and pursued professional opportunities in that sport.",["profile"]],
    ["I moved into fighting with a strong athletic base rather than a long childhood martial-arts résumé.",["profile"]],
    ["A run on The Ultimate Fighter introduced me to UFC audiences.",["profile"]],
    ["I lost in the tournament final but remained with the promotion.",["stats"]],
    ["I answered that loss with three straight stoppage or decision wins.",["stats"]],
    ["A knockout of Mirko Cro Cop became my biggest early highlight.",["stats"]],
    ["Later results were uneven, including losses to Antônio Rodrigo Nogueira and Ben Rothwell.",["stats"]],
    ["I retired from MMA and shifted toward entertainment and long-form conversation shows.",["profile"]],
    ["The podcast “The Fighter and the Kid” became central to my post-fighting public identity.",["profile"]],
    ["The former TUF 10 heavyweight finalist is now better known to many fans for podcasting and comedy.",["profile"]],
  ]),
  identity("ufc:kimbo-slice","Kimbo Slice",{
    stats:"https://ufcstats.com/statistics/fighters",
    profile:"https://www.ufc.com/athlete/kimbo-slice",
  },[
    ["I entered the UFC through a heavyweight season of The Ultimate Fighter.",["profile"]],
    ["My formal MMA résumé was still short when I became a major television draw.",["profile"]],
    ["I fought twice in the UFC after the reality show.",["stats"]],
    ["My Octagon record included one decision win and one stoppage loss.",["stats"]],
    ["I beat Houston Alexander by unanimous decision in my UFC debut.",["stats","profile"]],
    ["I was stopped by Matt Mitrione in my second UFC fight.",["stats"]],
    ["Before the UFC, I had already fought professionally in EliteXC.",["profile"]],
    ["My fame originally exploded through widely circulated backyard and street-fight videos.",["profile"]],
    ["After the UFC, I returned to high-profile MMA competition with Bellator.",["profile"]],
    ["Born Kevin Ferguson, I became famous worldwide under the fighting name Kimbo Slice.",["profile"]],
  ],[
    ["I arrived in mainstream MMA with celebrity that was unusual for someone with so few professional fights.",["profile"]],
    ["My UFC route came through reality television rather than a traditional contender climb.",["profile"]],
    ["I competed at heavyweight and catchweight during my brief UFC run.",["stats"]],
    ["Both of my UFC fights took place within roughly five months.",["stats"]],
    ["My only Octagon win came over Houston Alexander.",["stats"]],
    ["My UFC tenure ended after a second-round TKO loss to Matt Mitrione.",["stats"]],
    ["I had previously headlined cards for EliteXC because of my drawing power.",["profile"]],
    ["That drawing power came from internet videos of unsanctioned fights that spread widely before my MMA career.",["profile"]],
    ["My legal name was Kevin Ferguson, but almost no fight fan knew me by that name first.",["profile"]],
    ["The bearded heavyweight internet sensation known as Kimbo Slice became one of MMA’s earliest viral crossover stars.",["profile"]],
  ]),
  identity("ufc:cm-punk","CM Punk",{
    stats:"https://ufcstats.com/statistics/fighters",
    profile:"https://www.ufc.com/athlete/cm-punk",
    wwe:"https://www.wwe.com/superstars/cm-punk",
  },[
    ["I signed with the UFC without a prior professional MMA fight.",["profile"]],
    ["I trained for my Octagon debut for an extended period after the signing was announced.",["profile"]],
    ["I competed at welterweight in both of my UFC appearances.",["stats"]],
    ["My UFC debut came in 2016 at age 37.",["profile","stats"]],
    ["I lost that debut by first-round submission to Mickey Gall.",["stats"]],
    ["My second UFC fight went the distance against Mike Jackson.",["stats"]],
    ["The original decision in that bout was later overturned to a no contest.",["stats","profile"]],
    ["Before MMA, I had already become globally famous in professional wrestling.",["wwe","profile"]],
    ["I was a multiple-time WWE world champion long before entering the Octagon.",["wwe"]],
    ["My ring name and straight-edge wrestling persona made me instantly recognizable despite only two UFC fights.",["wwe"]],
  ],[
    ["I was a late starter in mixed martial arts and entered the UFC with almost no competitive combat-sports résumé.",["profile"]],
    ["My training camp was based at Roufusport in Milwaukee.",["profile"]],
    ["I made only two UFC appearances.",["stats"]],
    ["Neither appearance produced an official UFC victory.",["stats"]],
    ["Mickey Gall submitted me in a little over two minutes in my debut.",["stats"]],
    ["I returned nearly two years later and completed three rounds with Mike Jackson.",["stats"]],
    ["That result was ultimately recorded as a no contest rather than a loss.",["stats","profile"]],
    ["My pre-UFC fame came from years as one of WWE’s biggest stars.",["wwe"]],
    ["The phrase “Best in the World” and a long WWE championship reign were part of my identity before MMA.",["wwe"]],
    ["The professional-wrestling superstar CM Punk made one of the UFC’s most unusual celebrity transitions.",["wwe","profile"]],
  ]),
  identity("ufc:mike-perry","Mike Perry",{
    stats:"https://ufcstats.com/statistics/fighters",
    profile:"https://www.ufc.com/athlete/mike-perry",
  },[
    ["I made my UFC debut in 2016 and won my first two Octagon fights by knockout.",["stats","profile"]],
    ["My UFC style was built around pressure, durability and heavy boxing.",["profile"]],
    ["I experienced an uneven win-loss run despite producing several violent finishes.",["stats"]],
    ["One of my signature UFC knockouts came by elbow in 2017.",["stats","profile"]],
    ["I knocked out Jake Ellenberger in the second round with an elbow.",["stats"]],
    ["Later wins included decisions over Paul Felder and Alex Oliveira.",["stats"]],
    ["My final UFC victory came against Mickey Gall in 2020.",["stats"]],
    ["After leaving the UFC, I reinvented myself in bare-knuckle boxing.",["profile"]],
    ["I became one of BKFC’s biggest stars and won its symbolic “King of Violence” championship.",["profile"]],
    ["Known as “Platinum,” I became more famous after the UFC through a run of high-profile bare-knuckle fights.",["profile"]],
  ],[
    ["I entered the UFC as a boxer-first welterweight with a reputation for aggression.",["profile"]],
    ["My willingness to brawl often produced memorable fights even when the results were inconsistent.",["profile"]],
    ["I opened my UFC career with consecutive knockouts.",["stats"]],
    ["My first Octagon loss came by decision after those two finishes.",["stats"]],
    ["I bounced back with another pair of knockouts.",["stats"]],
    ["A decision win over Paul Felder showed I could win a rugged three-round fight without a finish.",["stats"]],
    ["My UFC tenure ended after losses to Tim Means and Daniel Rodriguez.",["stats"]],
    ["I then moved into bare-knuckle competition and found a second career.",["profile"]],
    ["Wins over prominent crossover opponents turned me into a centerpiece of BKFC.",["profile"]],
    ["The tattooed Florida brawler known as “Platinum” became synonymous with bare-knuckle fighting after his UFC run.",["profile"]],
  ]),
  identity("ufc:paige-vanzant","Paige VanZant",{
    stats:"https://ufcstats.com/statistics/fighters",
    profile:"https://www.ufc.com/athlete/paige-vanzant",
  },[
    ["I entered the UFC in 2014 at strawweight and won my first three Octagon appearances.",["stats","profile"]],
    ["My early UFC style leaned on pace, clinch work and athletic scrambles.",["profile"]],
    ["My first UFC loss came in a five-round main event.",["stats"]],
    ["I later moved up to flyweight for the final stretch of my UFC career.",["stats","profile"]],
    ["A jumping-switch-kick knockout became my most famous UFC finish.",["stats","profile"]],
    ["I also earned a submission win over Rachael Ostovich at flyweight.",["stats"]],
    ["My UFC run ended in 2020 after a first-round submission loss.",["stats"]],
    ["Outside fighting, I reached the finals of Dancing with the Stars.",["profile"]],
    ["After the UFC, I competed in bare-knuckle boxing and other crossover combat sports.",["profile"]],
    ["My mix of UFC success, television exposure and crossover fighting made me one of the promotion’s most recognizable personalities.",["profile"]],
  ],[
    ["I was still very young when I became a nationally known UFC fighter.",["profile"]],
    ["My rise was as much about relentless pace and toughness as technical finishing skill.",["profile"]],
    ["I won my UFC debut by third-round stoppage.",["stats"]],
    ["Two more wins followed before I headlined a card for the first time.",["stats"]],
    ["Rose Namajunas submitted me in that first UFC main event.",["stats"]],
    ["I rebounded with a highlight-reel knockout of Bec Rawlings.",["stats","profile"]],
    ["A later move to flyweight produced one win in three UFC appearances.",["stats"]],
    ["My profile expanded far beyond MMA through a successful run on network television.",["profile"]],
    ["I later signed for bare-knuckle boxing after leaving the UFC.",["profile"]],
    ["The former UFC strawweight and flyweight contender became a broader celebrity through Dancing with the Stars and crossover combat sports.",["profile"]],
  ]),
  identity("ufc:greg-hardy","Greg Hardy",{
    stats:"https://ufcstats.com/statistics/fighters",
    profile:"https://www.ufc.com/athlete/greg-hardy",
    football:"https://www.pro-football-reference.com/players/H/HardGr00.htm",
  },[
    ["I entered the UFC as a heavyweight through Dana White’s Contender Series.",["profile"]],
    ["My MMA career began unusually late compared with most UFC fighters.",["profile"]],
    ["My Octagon debut ended in a disqualification loss.",["stats"]],
    ["Another early fight was changed to a no contest after an in-cage rule violation involving an inhaler.",["stats","profile"]],
    ["I won three of my first six UFC appearances officially.",["stats"]],
    ["A short-notice fight with Alexander Volkov gave me my first matchup with an established elite heavyweight.",["stats","profile"]],
    ["My later UFC run ended with three consecutive knockout losses.",["stats"]],
    ["Before MMA, I spent multiple seasons playing defensive end in the NFL.",["football","profile"]],
    ["I earned Pro Bowl and second-team All-Pro honors during my football career.",["football"]],
    ["The former NFL defensive end became a UFC heavyweight after beginning MMA only after his football career.",["football","profile"]],
  ],[
    ["I came to professional fighting from another major American sport rather than from wrestling or kickboxing competition.",["profile"]],
    ["My physicality and punching power helped me advance quickly despite limited MMA experience.",["profile"]],
    ["I reached the UFC after appearances on the Contender Series.",["profile"]],
    ["My debut was lost by disqualification for an illegal knee.",["stats"]],
    ["I then scored back-to-back first-round knockouts.",["stats"]],
    ["A later win was overturned because I used an inhaler between rounds without authorization.",["stats","profile"]],
    ["I went the distance with Alexander Volkov on short notice in Moscow.",["stats"]],
    ["My previous career included six NFL seasons as a defensive end.",["football"]],
    ["I recorded a 15-sack NFL season and made a Pro Bowl before turning to MMA.",["football"]],
    ["The ex-Carolina Panthers and Dallas Cowboys pass rusher later fought ten times in the UFC heavyweight division.",["football","stats"]],
  ]),
  identity("ufc:darren-till","Darren Till",{
    stats:"https://ufcstats.com/statistics/fighters",
    profile:"https://www.ufc.com/athlete/darren-till",
  },[
    ["I made my UFC debut in 2015 and began my Octagon career unbeaten through six appearances.",["stats","profile"]],
    ["My striking style centered on a southpaw stance, distance control and a powerful left hand.",["profile"]],
    ["One of my early UFC fights ended in a draw.",["stats"]],
    ["My rise accelerated after a first-round stoppage in a 2017 main event.",["stats","profile"]],
    ["That knockout came against Donald Cerrone.",["stats"]],
    ["I then defeated Stephen Thompson by decision in a five-round fight in Liverpool.",["stats","profile"]],
    ["Those wins earned me a UFC welterweight title shot against Tyron Woodley.",["stats"]],
    ["I lost that championship fight by second-round submission.",["stats"]],
    ["I later moved to middleweight and beat Kelvin Gastelum in my divisional debut.",["stats"]],
    ["Known as “The Gorilla,” I became one of the UFC’s most prominent British title challengers of the late 2010s.",["profile"]],
  ],[
    ["I left England as a young fighter and spent several formative years training in Brazil.",["profile"]],
    ["That overseas development helped shape my Muay Thai-heavy striking game.",["profile"]],
    ["I entered the UFC unbeaten and remained without a loss for several years.",["stats"]],
    ["A draw interrupted that run without ending it.",["stats"]],
    ["I announced myself as a contender by stopping Donald Cerrone in the first round.",["stats","profile"]],
    ["I followed with a decision over Stephen Thompson in my hometown.",["stats","profile"]],
    ["My first professional defeat came in a UFC title fight with Tyron Woodley.",["stats"]],
    ["Jorge Masvidal then knocked me out in London in my next appearance.",["stats"]],
    ["I moved to middleweight afterward and immediately defeated Kelvin Gastelum.",["stats"]],
    ["The Liverpool southpaw known as “The Gorilla” became a welterweight title challenger before moving up to middleweight.",["profile"]],
  ]),
];
