// Canonical profile Signature Fight destinations restored from V1.
// Source: codyking0602/ufc-goat-rankings assets/data/display-overrides.js
// Blob: fca6068990f30f345c08069b962b5a63ae601066
// These are direct public watch URLs; UFC Fight Pass search URLs are intentionally excluded.

export const profileSignatureFightUrls = {
  "jon-jones": "https://youtu.be/ILOnZDCbmKM?is=YBFWXqGDjc9mpcjR",
  "georges-st-pierre": "https://youtu.be/4BCLM2kLh9I?is=F6TfTvsJpzKshLPK",
  "anderson-silva": "https://youtu.be/mWjv5lfe4eY?is=DwGlau_bq7PzxqVe",
  "demetrious-johnson": "https://youtu.be/9LfHvnxk170?is=tYaKigfsNWM3-rEk",
  "islam-makhachev": "https://youtu.be/h9oj6HEdZSI?is=1Fp-NwJ3VRAXCl56",
  "alexander-volkanovski": "https://youtu.be/vE-Vu1EA94A?is=53qFtddjjQOFrkBF",
  "khabib-nurmagomedov": "https://youtu.be/JuBBIJ7adjM?is=0QlHyjPjkzpsQGXL",
  "matt-hughes": "https://youtu.be/W7StRPCtF-E?is=W9q0sloxVcyJN5XW",
  "kamaru-usman": "https://youtu.be/IRUrK8BhjNE?is=1RKIKERb2j7zdgag",
  "max-holloway": "https://youtu.be/5oDsN9s9-yE?is=3pdZSWDbL4y_mzul",
  "stipe-miocic": "https://youtu.be/2yB-hp1OuKo?is=AaykrjmhihljMeKc",
  "jose-aldo": "https://youtu.be/K63PJBKuA4U?is=DDLXv7eVTA8Bjewm",
  "randy-couture": "https://youtu.be/KsLneUSMF9A?is=xbM0ss9sbQg9Dv4I",
  "israel-adesanya": "https://youtu.be/vx3vs0p6TEs?is=jS0EkVTFsuUKhoZn",
  "daniel-cormier": "https://youtu.be/2a0Ul8hRyqk?is=CYsGZkWOUaXUK6lt",
  "alex-pereira": "https://youtu.be/a8orgTRB9zA?is=zvdHIQSdKbY-kgxz",
  "chuck-liddell": "https://youtu.be/4g7YMHiQpf8?is=NYfyiSQTGxpzBQTT",
  "charles-oliveira": "https://youtu.be/Z-B99m_jqJs?is=eHglISzDShhwojtn",
  "tj-dillashaw": "https://youtu.be/xxROoFHRRd8?is=zUZGiVkLSrYCJQEO",
  "merab-dvalishvili": "https://youtu.be/VazxJSDXUs4?is=k9w1Cx8ybdudP3qR",
  "frankie-edgar": "https://youtu.be/9jpBlAiA3BM?is=zHpZeVMxigNffl0x",
  "francis-ngannou": "https://youtu.be/4Go5p7NWaiE?is=8BnCL81aC4u2greg",
  "cain-velasquez": "https://youtu.be/avpNktfdq_4?is=m3ah1k_z7OvWJKWl",
  "benson-henderson": "https://www.youtube.com/watch?v=P65mAfnAFhk",
  "aljamain-sterling": "https://youtu.be/I6WajDmm3yk?is=eGkspFsY7CtEjyHo",
  "junior-dos-santos": "https://youtu.be/zj_IMcTmcNU?is=IrloHxxSgOE9Q_pR",
  "bj-penn": "https://youtu.be/MQGf9p4YsOk?t=1122&is=6pFin0iSE-knCsaR",
  "justin-gaethje": "https://youtu.be/c_ZHlvDn4vM?is=2gEXV0uylOlRGzLU",
  "tyron-woodley": "https://youtu.be/knOFYm1it0k?is=U-dOgX681hEz_cPf",
  "glover-teixeira": "https://www.youtube.com/watch?v=dAsCS4R0cuE",
  "dustin-poirier": "https://youtu.be/m3N1WuErSlg?is=_jDLz8z8YOZmGC9q",
  "alex-pantoja": "https://youtu.be/7sj-snC5qWk?is=_DkasmmAc4OA-IDR",
  "leon-edwards": "https://youtu.be/cBa12HbgdpA?is=394cct3V_dK5UMpz",
  "tito-ortiz": "https://youtu.be/ZBNj8YBmzww?is=TfJb_wVvXgyVBrO6",
  "ilia-topuria": "https://youtu.be/nGcK0ilhu9c?is=VaKy-0-UQAad68t0",
  "fabricio-werdum": "https://youtu.be/EA_u7Uge45Q?is=CP-pl6SIga7UptkJ",
  "robbie-lawler": "https://youtu.be/ocsu8P4-GS4?is=kQFibyNlGENs6-QK",
  "robert-whittaker": "https://youtu.be/7CAkyfHMhhA?is=-CafmSWmneEDF7dK",
  "tony-ferguson": "https://youtu.be/PzrI9PY8gw4?is=DxvbhDuWHC4j1j__",
  "henry-cejudo": "https://youtu.be/Cpujg52kBU0?is=lA6FmsD5nZQYNLKr",
  "chris-weidman": "https://youtu.be/jDPeuWStJy4?is=gI85bNLTdl6U6q05",
  "frank-shamrock": "https://www.youtube.com/watch?v=obS1W3kHGvk",
  "petr-yan": "https://youtu.be/HscShxH_JtI?is=shXOQYq7ZBJ9Ij6z",
  "sean-strickland": "https://youtu.be/VhuOa60BVy0?is=mW_KDjjwj4D179ON",
  "deiveson-figueiredo": "https://youtu.be/OW_uA-X3HOg?is=8ya9VlZVXXDrXSNf",
  "conor-mcgregor": "https://youtu.be/YCE8TDYj7aU?is=I7P8Wc-PVWXMlIzr",
  "brandon-moreno": "https://youtu.be/GPrzwbgg8yU?is=M-G22YQ8u-8QVKtz",
  "vitor-belfort": "https://www.youtube.com/watch?v=St35ub7lmNg",
  "lyoto-machida": "https://youtu.be/P9IrK0Dflb4?is=5Lu2paN2r1OvY6Nk",
  "rashad-evans": "https://youtu.be/YzJjSBV5jsg?is=F9l9dmmcWV30K4Bj",
  "tom-aspinall": "https://youtu.be/sb3K8AuzrMc?is=vpfnb2vD4aPgWFxt",
  "dricus-du-plessis": "https://youtu.be/jLTuhXQRMSg?is=RGX__HY_u-mRzr0F",
  "dominick-cruz": "https://youtu.be/n_KzCRNlcjA?is=n2AH_YPeYsG-SMNq",
  "royce-gracie": "https://youtu.be/-y2SEefVNtE?is=NN1arJDFgj8_a7F9",
  "khamzat-chimaev": "https://youtu.be/P1Yl0iKipxs?is=3xlsp_uGjj6i2W07",
  "michael-bisping": "https://youtu.be/Ne2fSWUWv4U?is=LejcNbriCXqsO38n",
  "anthony-pettis": "https://youtu.be/smbYO1-yqtA?is=lhtpeK1nOCqGUvdc",
  "sean-omalley": "https://youtu.be/EDAt1j_mTCw?is=GFpQRutBy6Ibbvnx",
  "quinton-jackson": "https://youtu.be/W3Ce7KPszhU?is=Pzzqz2wACxC7VY6g",
  "shogun-rua": "https://youtu.be/08YmP1EM2ms?is=gQIDS9i91zPsk3kX",
  "forrest-griffin": "https://youtu.be/dkECRNJCgOc?is=Bh3jqyclBSJ0X-G_",
  "brock-lesnar": "https://youtu.be/WD2-K7dsqYM?is=3Jn9ethtTZSoaFk5",
  "dan-henderson": "https://youtu.be/rLuppO32rUI?is=DdM4tdoZAMapoDRg",
  "chael-sonnen": "https://youtu.be/DpLaqnwFQEY?is=VUYzF8zQsZszQ4aj",
  "paddy-pimblett": "https://youtu.be/-qygvEuJEC8?is=PanrIaWCzzfNqhuf",
  "amanda-nunes": "https://youtu.be/qwPBPiUzgag?is=pTBaihmA06TEDxKo",
  "valentina-shevchenko": "https://youtu.be/bM9I7FEGZZA?is=JiQtLvizH4HgX5yE",
  "zhang-weili": "https://youtu.be/i_AL3LLUnHY?is=n4qx06JN_inLPn64",
  "joanna-jedrzejczyk": "https://youtu.be/cINJim4gWN4?is=Y9AgsjUAgh-5WYoQ",
  "rose-namajunas": "https://youtu.be/G2vSZhl6BFY?is=IYpvomkm6ZdY8fYg",
  "ronda-rousey": "https://youtu.be/tbKIVH8nY60?is=y5-Dat4Qb7IjqLe_",
  "jessica-andrade": "https://youtu.be/nQIBZ2fjrMQ?is=_o9fLH0odv_P1miD",
  "cris-cyborg": "https://youtu.be/iLZwZX39FXU",
  "carla-esparza": "https://youtu.be/jJeZ2wZv0YQ?is=QOK9v0B_kfqvZgqd",
  "alexa-grasso": "https://youtu.be/P0U_W35_cJw?is=mRmw6BHCQGDfTygx",
  "kayla-harrison": "https://youtu.be/UUMlLth-4uQ?is=ZmRXsN5bIzaY1_rq",
  "mackenzie-dern": "https://youtu.be/Gnf14OGq9VY?is=AWeo4KKp08bB0v5k",
  "julianna-pena": "https://youtu.be/tB_Xg1LbMVQ?is=cMc6BXC1LV3u8rJa",
  "miesha-tate": "https://youtu.be/4BWMHK_gnhA?t=661&is=en-jw61zn6lQ-wvD",
  "holly-holm": "https://youtu.be/3j7WaTd8bkQ?is=MPSWMNle4EFHa4Y0",
} as const satisfies Readonly<Record<string, string>>;

export function profileSignatureFightUrlFor(slug: string): string | null {
  return profileSignatureFightUrls[slug as keyof typeof profileSignatureFightUrls] ?? null;
}
