export const COWBOYS_PLAYER_SUMMARIES = {
  "Tony Romo": "QB • 2007 NFC No. 1 seed • Three Pro Bowls from 2007 forward",
  "Dak Prescott": "QB • 2016 Offensive Rookie of the Year • 2023 second-team All-Pro",
  "Jon Kitna": "QB • 2010 relief starter • 16 TD passes",
  "Cooper Rush": "QB • Won four straight starts in 2022 • Longtime backup",
  "Marion Barber III": "RB • 2007 Pro Bowl • 10 rushing TD",
  "Felix Jones": "RB • 2008 first-round pick • 73-yard playoff TD in 2009",
  "Tashard Choice": "RB • 2008 rookie contributor • 472 rushing yards",
  "DeMarco Murray": "RB • 2014 Offensive Player of the Year • NFL rushing champion",
  "Darren McFadden": "RB • 1,089 rushing yards in 2015 • 10 starts",
  "Ezekiel Elliott": "RB • Two-time NFL rushing champion • 2016 first-team All-Pro",
  "Tony Pollard": "RB • 2022 Pro Bowl • 1,007 rushing yards",
  "Rico Dowdle": "RB • 1,079 rushing yards in 2024 • First 1,000-yard season",
  "Terrell Owens": "WR • 2007 first-team All-Pro • 15 receiving TD",
  "Patrick Crayton": "WR • 697 receiving yards in 2007 • 7 receiving TD",
  "Miles Austin": "WR • 2009 Pro Bowl • 1,320 receiving yards",
  "Dez Bryant": "WR • 2014 first-team All-Pro • NFL-high 16 receiving TD",
  "Cole Beasley": "WR • 75 catches in 2016 • 833 receiving yards",
  "Terrance Williams": "WR • 8 receiving TD in 2014 • Playoff TD vs. Detroit",
  "Amari Cooper": "WR • Two Pro Bowls with Dallas • 1,189 yards in 2019",
  "Michael Gallup": "WR • 1,107 receiving yards in 2019 • 6 receiving TD",
  "CeeDee Lamb": "WR • 2023 first-team All-Pro • Cowboys-record 135 catches",
  "KaVontae Turpin": "RET • 2022 Pro Bowl returner • 2024 All-Pro returner",
  "Jason Witten": "TE • Two first-team All-Pro selections from 2007 forward • 1,145 yards in 2007",
  "Martellus Bennett": "TE • 2008 second-round pick • 85 catches in four Dallas seasons",
  "Dalton Schultz": "TE • 78 catches and 8 TD in 2021 • Two playoff TD in 2022",
  "Jake Ferguson": "TE • 2023 Pro Bowl • 71 catches",
  "Flozell Adams": "OL • Pro Bowls in 2007 and 2008 • Starting left tackle",
  "Andre Gurode": "OL • Four straight Pro Bowls from 2007–10 • Starting center",
  "Leonard Davis": "OL • 2007 first-team All-Pro • Three straight Pro Bowls",
  "Marc Colombo": "OL • Starting right tackle on 2007 and 2009 playoff teams",
  "Doug Free": "OL • Starting tackle on 2014 division champion • Longtime Dallas starter",
  "Tyron Smith": "OL • Two-time first-team All-Pro • Eight Pro Bowls as a Cowboy",
  "Travis Frederick": "OL • 2016 first-team All-Pro • Five Pro Bowls",
  "Zack Martin": "OL • Seven first-team All-Pro selections • Nine Pro Bowls",
  "La'el Collins": "OL • 71 Dallas starts • Guard-to-tackle versatility",
  "Connor Williams": "OL • 51 Dallas starts • 2018 second-round pick",
  "Tyler Smith": "OL • 2023 second-team All-Pro • Pro Bowl guard",
  "DeMarcus Ware": "EDGE • 20 sacks in 2008 • Two NFL sack titles with Dallas",
  "Greg Ellis": "EDGE • 2007 Comeback Player of the Year • 12.5 sacks",
  "Jay Ratliff": "DL • 2009 first-team All-Pro • Four straight Pro Bowls",
  "Marcus Spears": "DL • Multi-year starter on Wade Phillips defenses • 2009 division champion",
  "Anthony Spencer": "EDGE • 2012 Pro Bowl • 11 sacks",
  "DeMarcus Lawrence": "EDGE • 2017 second-team All-Pro • 14.5 sacks",
  "Randy Gregory": "EDGE • 6 sacks in 2021 • 17 QB hits",
  "Robert Quinn": "EDGE • 11.5 sacks in 2019 • One-season Dallas impact",
  "Micah Parsons": "EDGE • 2021 Defensive Rookie of the Year • Two-time first-team All-Pro",
  "Sean Lee": "LB • 2016 first-team All-Pro • 145 tackles",
  "Rolando McClain": "LB • 2014 comeback season • 81 tackles",
  "Anthony Hitchens": "LB • Four Dallas seasons • Starter on 2014 division champion",
  "Jaylon Smith": "LB • 2019 Pro Bowl • 142 tackles",
  "Leighton Vander Esch": "LB • 2018 second-team All-Pro • 140 tackles",
  "Terence Newman": "DB • Pro Bowls in 2007 and 2009 • Five Dallas seasons after cutoff",
  "Roy Williams": "DB • 2007 Pro Bowl • Final two Dallas seasons after cutoff",
  "Ken Hamlin": "DB • 2007 Pro Bowl • 5 INT in debut Dallas season",
  "Mike Jenkins": "DB • 2009 Pro Bowl • 5 INT",
  "Orlando Scandrick": "DB • Ten seasons in Dallas • Longtime slot corner",
  "Brandon Carr": "DB • Started all 80 games in five Dallas seasons • 7 INT",
  "Morris Claiborne": "DB • 2012 No. 6 overall pick • Five Dallas seasons",
  "Barry Church": "DB • Four-year starter • 2014 division-title defense",
  "Byron Jones": "DB • 2018 second-team All-Pro • Pro Bowl",
  "Jourdan Lewis": "DB • 2017 third-round pick • Longtime nickel corner",
  "Trevon Diggs": "DB • 2021 first-team All-Pro • NFL-high 11 INT",
  "DaRon Bland": "DB • 2023 first-team All-Pro • NFL-record 5 pick-sixes",
  "Donovan Wilson": "DB • 101 tackles in 2022 • 5 sacks",
  "Malik Hooker": "DB • Starting safety on three straight 12-win teams • 2021–23",
  "Nick Folk": "K • 2007 Pro Bowl • 26-of-31 field goals as a rookie",
  "Dan Bailey": "K • 2015 Pro Bowl • 186 field goals with Dallas",
  "Bryan Anger": "P • 2021 Pro Bowl • 2021 second-team All-Pro",
  "Brandon Aubrey": "K • 2023 first-team All-Pro • 35 straight makes to start career",
} as const;

export type CowboysPlayerName = keyof typeof COWBOYS_PLAYER_SUMMARIES;

export function cowboysPlayerSummary(displayLabel: string | null | undefined) {
  if (!displayLabel) return "";
  return COWBOYS_PLAYER_SUMMARIES[displayLabel as CowboysPlayerName] ?? "";
}
