// PR9 CFB B-tier research data only. Canonical validation and lookup remain in footballPersonIdentityKnowledge.ts.
export const footballPersonIdentityCfbBResearchSources = [
  ["https://mgoblue.com/sports/football/roster/jake-butt/1408","Michigan Athletics — Jake Butt roster"],
  ["https://mgoblue.com/news/2017/4/20/kornacki_butt_looking_to_change_lives","Michigan Athletics — Kornacki: Butt Looking to Change Lives"],
  ["https://mgoblue.com/news/2017/10/9/football-perry-finds-meaning-in-wearing-butts-no-88","Michigan Athletics — Perry Finds Meaning in Wearing Butt's No. 88"],
  ["https://mgoblue.com/news/2008/4/22/dolphins_sign_long_make_him_top_pick_in_nfl_draft","Michigan Athletics — Dolphins Sign Long, Make Him Top Pick in NFL Draft"],
  ["https://mgoblue.com/news/2003/2/5/2003_signing_day_comments_from_coach_lloyd_carr","Michigan Athletics — 2003 Signing Day Comments from Coach Lloyd Carr"],
  ["https://12thman.com/sports/football/roster/season/2010/player/jake-matthews","Texas A&M Athletics — Jake Matthews roster"],
  ["https://12thman.com/news/2023/09/15/2023-texas-am-athletics-hall-of-fame-class-enshrined-at-45th-burgess-banquet","Texas A&M Athletics — 2023 Hall of Fame class banquet"],
  ["https://12thman.com/news/2013/09/11/family-first-1","Texas A&M Athletics — Family First"],
  ["https://12thman.com/news/2013/08/30/family-tradition","Texas A&M Athletics — Family Tradition"],
  ["https://12thman.com/news/2013/01/10/jake-matthews-to-return-to-aggieland","Texas A&M Athletics — Jake Matthews to Return to Aggieland"],
  ["https://georgiadogs.com/roster.aspx?rp_id=4881","Georgia Athletics — Jalen Carter roster"],
  ["https://seminoles.com/news/2013/3/12/signee-breakdown-jalen-ramsey","Florida State Athletics — Signee Breakdown: Jalen Ramsey"],
  ["https://seminoles.com/sports/football/roster/jalen-ramsey/809","Florida State Athletics — Jalen Ramsey roster"],
  ["https://www.specialolympics.org/about/ambassadors/jamaal-charles","Special Olympics — Jamaal Charles ambassador profile"],
  ["https://alcalde.texasexes.org/2016/05/jamaal","The Alcalde — Jamaal"],
  ["https://texaslonghorns.com/news/2005/2/2/020205aac_656","Texas Athletics — 2005 signing class"],
  ["https://tshof.org/inductee/jamaal-charles/","Texas Sports Hall of Fame — Jamaal Charles"],
  ["https://lsusports.net/sports/fb/roster/season/2014/player/jamal-adams","LSU Athletics — Jamal Adams roster"],
  ["https://www.raiders.com/news/jamal-adams-facts-get-to-know-nfl-transactions-raiders-training-camp","Las Vegas Raiders — Jamal Adams facts"],
  ["https://ohiostatebuckeyes.com/news/2006/11/18/under-the-helmet-37","Ohio State Athletics — Under the Helmet"],
  ["https://ohiostatebuckeyes.com/news/2005/2/2/eighteen-student-athletes-sign-to-play-football-at-ohio-state","Ohio State Athletics — 2005 signing class"],
  ["https://ohiostatebuckeyes.com/news/2008/3/27/spring-football-player-profile-james-laurinaitis","Ohio State Athletics — Spring Football Player Profile"],
  ["https://fightingirish.com/news/2014/09/11/coming-of-age","Notre Dame Athletics — Coming of Age"],
  ["https://fightingirish.com/sports/football/roster/player/jaylon-smith","Notre Dame Athletics — Jaylon Smith roster"],
  ["https://ohiostatebuckeyes.com/sports/football/roster/jeff-okudah/449","Ohio State Athletics — Jeff Okudah roster"],
  ["https://ohiostatebuckeyes.com/news/2020/1/3/jeff-okudah-departs-dbu-as-an-all-time-top-cb","Ohio State Athletics — Jeff Okudah Departs DBU"],
  ["https://miamihurricanes.com/sports/football/roster/season/2001-02/player/jeremy-shockey/","Miami Athletics — Jeremy Shockey roster"],
  ["https://soonersports.com/news/2006/8/21/208392693","Oklahoma Athletics — Freshman Tight End Jermaine Gresham"],
  ["https://fightingirish.com/sports/football/roster/player/joe-alt","Notre Dame Athletics — Joe Alt roster"],
  ["https://uwbadgers.com/sports/2015/8/21/GEN_20140101585","Wisconsin Athletics — Joe Thomas profile"],
  ["https://uwbadgers.com/news/2019/6/25/athletics-general-news-events-lucas-uw-athletic-hall-of-fame-2019-joe-thomas-football","Wisconsin Athletics — Hall of Fame feature"],
  ["https://ohiostatebuckeyes.com/news/2013/2/6/ohio-state-signs-24-to-national-letters-of-intent","Ohio State Athletics — 2013 signing class"],
  ["https://ohiostatebuckeyes.com/sports/football/roster/nick-bosa/7994","Ohio State Athletics — Nick Bosa roster"],
  ["https://ohiostatebuckeyes.com/news/2014/9/29/urban-meyer-press-conference-transcript-09-29-14","Ohio State Athletics — Urban Meyer press conference, Sept. 29, 2014"],
  ["https://utsports.com/sports/football/roster/john-henderson/14190","Tennessee Athletics — John Henderson roster"],
  ["https://utsports.com/news/2012/5/25/Vols_Jersey_Countdown_98","Tennessee Athletics — Vols Jersey Countdown: 98"],
  ["https://www.army.mil/article/258443/nfl_football_star_spends_time_with_kids_at_fort_lee_procamp","U.S. Army — Jonathan Allen youth camp feature"],
  ["https://www.washingtonpost.com/sports/colleges/from-foster-care-to-first-round-alabamas-jonathan-allen-plows-forward/2016/12/22/9f61c5d4-c84f-11e6-bf4b-2c064d32a4bf_story.html","The Washington Post — From foster care to first round"],
  ["https://rolltide.com/sports/football/roster/jonathan-allen/3077","Alabama Athletics — Jonathan Allen roster"],
  ["https://texaslonghorns.com/news/2008/10/11/101108aaa_21","Texas Athletics — Texas vs. Oklahoma feature"],
  ["https://texaslonghorns.com/news/2006/11/16/111606aab_105.aspx","Texas Athletics — Jordan Shipley Q&A"],
  ["https://goheels.com/sports/football/roster/julius-peppers/5459","North Carolina Athletics — Julius Peppers football roster"],
  ["https://goheels.com/news/2000/1/22/205462922","North Carolina Athletics — Peppers joins basketball"],
  ["https://goducks.com/sports/football/roster/kayvon-thibodeaux/10601","Oregon Athletics — Kayvon Thibodeaux roster"],
  ["https://goducks.com/news/2019/2/5/football-nsd19","Oregon Athletics — Oregon Adds To Consensus Top 10 Class"],
  ["https://www.latimes.com/sports/newsletter/2021-08-02/high-school-football-prep-rally","Los Angeles Times — Prep Rally interview"],
  ["https://footballfoundation.org/hof_search.aspx?hof=2065","National Football Foundation — Keith Jackson Hall of Fame profile"],
  ["https://soonersports.com/sports/2025/2/26/black-history-month-spotlight","Oklahoma Athletics — Black History Month Spotlight"],
  ["https://www.cfbhall.com/inductees/keith-jackson-2001/","College Football Hall of Fame — Keith Jackson"],
  ["https://miamihurricanes.com/sports/football/roster/season/2001-02/player/kellen-winslow","Miami Athletics — Kellen Winslow roster"],
  ["https://www.sportingnews.com/us/nfl/news/khalil-mack-college-video-game-rating/1tp13tlo204d115tf2mhhlqkb2","Sporting News — Khalil Mack college backstory"],
  ["https://chicago.suntimes.com/2018/10/31/18480992/the-mack-effect-before-he-was-a-bear-olb-khalil-mack-transformed-buffalo","Chicago Sun-Times — Before he was a Bear, Mack transformed Buffalo"],
  ["https://www.si.com/nfl/2014/04/25/2014-nfl-draft-top-64-khalil-mack","Sports Illustrated — 2014 NFL Draft Top 64: Khalil Mack"],
  ["https://www.si.com/college/2013/11/19/khalil-mack-buffalo-bulls","Sports Illustrated — Khalil Mack and Buffalo"],
  ["https://www.ravenspr.com/player_bios/kyle_hamilton.pdf","Baltimore Ravens — Kyle Hamilton media guide bio"],
  ["https://fightingirish.com/sports/football/roster/season/2020-21/player/kyle-hamilton","Notre Dame Athletics — Kyle Hamilton roster"],
  ["https://nsd.floridagators.com/bio/15","Florida Athletics — Kyle Pitts signing bio"],
  ["https://floridagators.com/news/2020/10/2/football-gators-tight-end-kyle-pitts-feature-story","Florida Athletics — Pitts Well-Equipped for Big Stage"],
  ["https://floridagators.com/news/2020/9/7/football-the-kyle-konnection-trask-and-pitts","Florida Athletics — The Kyle Konnection: Trask and Pitts"],
  ["https://www.profootballhof.com/news/2025/03/gold-jacket-spotlight-ladainian-tomlinson-runs-idol%E2%80%99s-handoff-into-nfl-stardom/","Pro Football Hall of Fame — Gold Jacket Spotlight: LaDainian Tomlinson"],
  ["https://footballfoundation.org/honors/hall-of-fame/ladainian-tomlinson/2370","National Football Foundation — LaDainian Tomlinson Hall of Fame profile"],
  ["https://goducks.com/news/2023/12/5/football-james-hall-of-fame-induction-becomes-official-tuesday","Oregon Athletics — James Hall of Fame induction feature"],
  ["https://goducks.com/honors/hall-of-fame/lamichael-james/1253","Oregon Athletics — LaMichael James Hall of Fame"],
  ["https://georgiadogs.com/sports/football/roster/malaki-starks/8131","Georgia Athletics — Malaki Starks roster"],
  ["https://georgiadogs.com/news/2023/9/19/football-quick-chat-malaki-starks","Georgia Athletics — Quick Chat: Malaki Starks"],
  ["https://ohiostatebuckeyes.com/news/2007/5/3/ohio-state-hosts-jesse-owens-classic","Ohio State Athletics — Jesse Owens Classic"],
  ["https://usctrojans.com/sports/track-and-field/roster/marqise-lee/3998","USC Athletics — Marqise Lee track roster"],
  ["https://usctrojans.com/sports/2017/6/15/blog-2011-08-meet-marqise-lee-html.aspx","USC Athletics — Meet Marqise Lee"],
  ["https://www.espn.com/college-football/story/_/id/38703026/marvin-harrison-jr-ohio-state-draft-penn-state","ESPN — Marvin Harrison Jr. profile"],
  ["https://www.foxsports.com/stories/college-football/kyle-mccord-and-marvin-harrison-jrs-long-intertwined-paths-to-the-game","FOX Sports — McCord and Harrison's intertwined paths"],
  ["https://www.phillyvoice.com/marvin-harrison-jr-wide-receiver-prospect-ohio-state-rose-bowl-st-josephs-prep-philadelphia/","PhillyVoice — Marvin Harrison Jr. at Ohio State"],
  ["https://gopsusports.com/sports/football/roster/season/2018/player/micah-parsons","Penn State Athletics — Micah Parsons roster"],
  ["https://gopsusports.com/news/2017/12/20/franklin-and-fb-inks-top-5-class","Penn State Athletics — 2017 signing class"],
  ["https://gopsusports.com/news/2019/07/22/brown-and-parsons-on-butkus-preseason-watch-list","Penn State Athletics — Brown and Parsons on Butkus Preseason Watch List"],
  ["https://texaslonghorns.com/news/2004/12/30/123004aaa_665","Texas Athletics — Family ties add intrigue to Rose Bowl"],
  ["https://texaslonghorns.com/news/2015/9/24/FB_0924152019","Texas Athletics — Michael Huff Hall of Honor profile"],
  ["https://texaslonghorns.com/news/2005/8/30/083005aab_128","Texas Athletics — Mind over matter"],
  ["https://12thman.com/sports/football/roster/season/2012/player/mike-evans","Texas A&M Athletics — Mike Evans roster"],
  ["https://12thman.com/news/2013/09/04/the-rock-from-the-island","Texas A&M Athletics — The Rock from the Island"],
  ["https://lsusports.net/sports/fb/roster/season/2010/player/morris-claiborne","LSU Athletics — Morris Claiborne roster"],
  ["https://georgiadogs.com/sports/football/roster/nakobe-dean/5425","Georgia Athletics — Nakobe Dean roster"],
  ["https://georgiadogs.com/news/2023/4/28/football-dean-still-pursuing-mechanical-engineering-degree","Georgia Athletics — Dean Still Pursuing Mechanical Engineering Degree"],
  ["https://olemisssports.com/news/2021/4/12/football-ole-miss-nfl-legend-patrick-willis-to-deliver-commencement-address.aspx","Ole Miss Athletics — Patrick Willis commencement announcement"],
  ["https://olemisssports.com/news/2003/2/5/2003_Ole_Miss_Signing_Day_Press_Conference_Transcript","Ole Miss Athletics — 2003 Signing Day transcript"],
  ["https://wpial.org/hof.aspx?hof=61","WPIAL Hall of Fame — Paul Posluszny"],
  ["https://collegesportscommunicators.com/news/2006/11/30/GEN_1354.aspx?path=general","College Sports Communicators — Academic All-America announcement"],
  ["https://footballfoundation.org/honors/hall-of-fame/paul-posluszny/2538","National Football Foundation — Paul Posluszny Hall of Fame profile"],
  ["https://gopsusports.com/news/2006/12/10/posluszny-named-mvp-at-nittany-lion-football-banquet","Penn State Athletics — Football Banquet"],
  ["https://seminoles.com/honors/florida-state-athletics-hall-of-fame/peter-warrick/124","Florida State Athletics — Peter Warrick Hall of Fame"],
  ["https://allstatesugarbowl.org/sports/2023/11/28/peter-warrick.aspx","Sugar Bowl — Peter Warrick Hall of Fame"],
  ["https://seminoles.com/news/2026/8/18/football-hall-of-fame-on-campus-salute-for-peter-warrick-set-for-october-31","Florida State Athletics — Hall of Fame On-Campus Salute"],
  ["https://allstatesugarbowl.org/news/2026/1/22/cfb-hall-of-fame.aspx","Sugar Bowl — Three Sugar Bowl Alums Headed to College Football Hall of Fame"],
  ["https://rolltide.com/news/2008/1/8/Rolando_McClain_Named_Freshman_All_American","Alabama Athletics — Rolando McClain Freshman All-America"],
  ["https://www.maxpreps.com/al/decatur/decatur-red-raiders/athletes/rolando-mcclain/bio/?careerid=a03uvbn8dor33","MaxPreps — Rolando McClain basketball bio"],
  ["https://soonersports.com/news/2007/2/7/208402679","Oklahoma Athletics — 2007 signing class"],
  ["https://soonersports.com/news/2011/1/6/208390240","Oklahoma Athletics — Ryan Broyles to Return"],
  ["https://clemsontigers.com/sports/football/roster/player/sammy-watkins","Clemson Athletics — Sammy Watkins roster"],
  ["https://www.patriots.com/team/players-roster/a-j-brown/logs/2024/pre/","New England Patriots player biography"],
  ["https://olemisssports.com/sports/football/roster/a-j-brown/270","Ole Miss Athletics player biography"],
  ["https://www.si.com/college/2016/02/03/aj-brown-myers-commits-ole-miss","Sports Illustrated commitment report"],
  ["https://ohiostatebuckeyes.com/news/2005/9/10/no-time-to-wait","Ohio State Athletics profile, “No Time To Wait”"],
  ["https://www.nhregister.com/news/article/Connections-run-deep-for-Ohio-St-duo-11654413.php","New Haven Register / Associated Press feature"],
  ["https://www.espn.com/college-football/story/_/id/14458113/a-lot-changed-ohio-state-buckeyes-notre-dame-fighting-irish-last-met-fiesta-bowl","ESPN Fiesta Bowl retrospective"],
  ["https://texaslonghorns.com/news/2002/2/6/020602aaa_208","Texas Athletics 2002 recruiting biography"],
  ["https://texaslonghorns.com/news/2005/10/5/100505aab_420.aspx","Texas Athletics feature, “Take it to the house”"],
  ["https://texaslonghorns.com/news/2012/3/30/033112aab_522","Texas Athletics spring-game feature"],
  ["https://www.inquirer.com/college-sports/penn-state/penn-state-abdul-carter-football-cfp-lasalle-glenside-north-philly-20241219.html","Philadelphia Inquirer profile"],
  ["https://gopsusports.com/sports/football/roster/season/2023/player/abdul-carter","Penn State Athletics player biography"],
  ["https://gopsusports.com/news/2024/12/18/carter-warren-selected-sporting-news-all-americans","Penn State Athletics All-America release"],
  ["https://mgoblue.com/sports/football/roster/aidan-hutchinson/22005","Michigan Athletics player biography"],
  ["https://www.detroitlions.com/team/players-roster/aidan-hutchinson/logs/","Detroit Lions player biography"],
  ["https://calbears.com/sports/football/roster/coaches/alex-mack/194","California Athletics Alex Mack biography"],
  ["https://footballfoundation.org/sports/football/roster/alex-mack/573","National Football Foundation Campbell Trophy biography"],
  ["https://static.clubs.nfl.com/image/upload/bills/m8gerv5jb7nkovxkwmb6","Buffalo Bills player biography"],
  ["https://static.clubs.nfl.com/image/upload/raiders/re0vrphviaskzjcnphx1.pdf","Oakland Raiders feature-clips compilation of Bay Area News Group profile"],
  ["https://www.espn.com/blog/sec/post/_/id/96041/amari-cooper-paved-his-own-way-to-alabama","ESPN SEC profile on Cooper’s path to Alabama"],
  ["https://www.umsportshalloffame.com/andre-johnson.html","University of Miami Sports Hall of Fame biography"],
  ["https://miamihurricanes.com/news/2002/05/05/205547137-2/","Miami Athletics 100-meter title release"],
  ["https://miamihurricanes.com/news/2024/02/08/hester-johnson-named-to-pro-football-hall-of-fame/","Miami Athletics Pro Football Hall of Fame release"],
  ["https://miamihurricanes.com/sports/football/roster/season/2001-02/player/andre-johnson/","Miami Hurricanes player biography"],
  ["https://www.heisman.com/heisman-winners/andre-ware/","Heisman Trust biography"],
  ["https://gostanford.com/news/2013/04/17/andrew-luck-profile","Stanford Athletics Andrew Luck profile"],
  ["https://gostanford.com/staff/andrew-luck","Stanford Athletics staff biography"],
  ["https://gophersports.com/news/2016/8/4/Meet_The_Newcomers_Antoine_Winfield_Jr_","Minnesota Athletics newcomer profile"],
  ["https://gophersports.com/sports/football/roster/antoine-winfield-jr/16427","Minnesota Athletics player biography"],
  ["https://www.espn.com/college-football/story/_/id/41962943/boise-state-ashton-jeanty-dominant-running-back-heisman-2024","ESPN profile on Jeanty’s rise"],
  ["https://www.nfl.com/news/2025-nfl-draft-get-to-know-ashton-jeanty","NFL.com draft profile feature"],
  ["https://www.idahostatesman.com/sports/college/mountain-west/boise-state-university/boise-state-football/article295617584.html","Idaho Statesman profile"],
  ["https://broncosports.com/sports/football/roster/jeantyashton/10215","Boise State Athletics player biography"],
  ["https://www.heisman.com/articles/transfers-and-the-heisman/","Heisman Trust transfer history feature"],
  ["https://www.heisman.com/heisman-winners/baker-mayfield/","Heisman Trust Baker Mayfield biography"],
  ["https://rolltide.com/news/2012/12/6/Barrett_Jones_Named_Capital_One_Academic_All_America_of_the_Year","Alabama Athletics Academic All-America release"],
  ["https://footballfoundation.org/sports/football/roster/barrett-jones/569","National Football Foundation Barrett Jones biography"],
  ["https://www.espn.com/nfl/draft2013/story/_/id/9197435/2013-nfl-draft-alabama-barrett-jones-espn-magazine","ESPN The Magazine profile of Barrett Jones"],
  ["https://www.espn.com/nfl/draft2023/story/_/id/36234668/why-bijan-robinson-break-nfl-draft-running-back-bias","ESPN profile of Bijan Robinson"],
  ["https://texaslonghorns.com/sports/football/roster/bijan-robinson/11507","Texas Athletics player biography"],
  ["https://www.bijanrobinson.com/foundation","Bijan Robinson Foundation"],
  ["https://www.si.com/college/2022/12/15/college-athletes-top-food-related-nil-deals-2022","Sports Illustrated NIL feature"],
  ["https://www.kstatesports.com/sports/football/roster/coaches/bill-snyder/1258","Kansas State Athletics coach biography"],
  ["https://www.kshof.org/team/bill-snyder","Kansas Sports Hall of Fame biography"],
  ["https://www.kstatesports.com/news/2018/12/2/football-bill-snyder-announces-retirement-from-kansas-state","Kansas State Athletics retirement release"],
  ["https://soonersports.com/news/2001/1/3/208366339","Oklahoma Athletics profile"],
  ["https://hawkeyesports.com/news/2019/08/30/football-stoops","Iowa Athletics profile"],
  ["https://hawkeyesports.com/news/2011/12/5/wine-online-a-duel-of-friends-in-the-desert","Iowa Athletics feature"],
  ["https://fightingirish.com/news/2006/06/26/summer-football-fix-brady-quinn-feature","Notre Dame Athletics Brady Quinn feature"],
  ["https://fightingirish.com/irish-enjoying-the-combo-platter/","Notre Dame Athletics feature on young combinations"],
  ["https://fightingirish.com/news/2006/11/17/player-feature","Notre Dame Athletics player feature"],
  ["https://osubeavers.com/sports/football/roster/brandin-cooks/2450","Oregon State Athletics player biography"],
  ["https://www.nfl.com/news/brandin-cooks-robert-woods-lead-rolling-rams-wr-corps-0ap3000001014625","NFL.com feature on Brandin Cooks"],
  ["https://hawkeyesports.com/news/2025/08/6/2025-iowa-athletics-hall-of-fame-spotlight-brandon-scherff","Iowa Athletics Hall of Fame spotlight"],
  ["https://hawkeyesports.com/sports/football/roster/player/brandon-scherff","Iowa Athletics player biography"],
  ["https://mgoblue.com/news/2017/4/27/kornacki_braylon_edwards_has_new_no_1","Michigan Athletics No. 1 jersey feature"],
  ["https://mgoblue.com/news/2006/4/18/edwards_donates_500_000_to_athletic_department","Michigan Athletics scholarship announcement"],
  ["https://mgoblue.com/news/2003/8/9/2003_U_M_Football_Media_Day_Offensive_Player_Quotes","Michigan Athletics 2003 media-day quotes"],
  ["https://gobearcats.com/staff/brian-kelly","University of Cincinnati Athletics coach biography"],
  ["https://www.assumption.edu/news-and-events/news/multi-sport-stadium-named-notre-dame-football-coach-brian-kelly-83-hd-12","Assumption University stadium feature"],
  ["https://gvsulakers.com/honors/hall-of-fame/brian-kelly/26","Grand Valley State Athletics Hall of Fame biography"],
  ["https://www.kellycaresfoundation.org/about/our-story/","Kelly Cares Foundation history"],
  ["https://texaslonghorns.com/sports/football/roster/brian-orakpo/748","Texas Athletics player biography"],
  ["https://texaslonghorns.com/news/2009/4/16/041609aaa_26","Texas Athletics feature on Orakpo"],
  ["https://golobos.com/news/2013/05/22/209066364","New Mexico Athletics retirement feature"],
  ["https://golobos.com/news/2017/01/09/brian-urlacher-named-to-nff-college-football-hall-of-fame","New Mexico Athletics Hall of Fame announcement"],
  ["https://miamihurricanes.com/roster/bryant-mckinnie/","Miami Hurricanes player biography"],
  ["https://miamihurricanes.com/news/2025/04/18/dorsey-johnson-mckinnie-morgan-selected-to-miami-football-ring-of-honor","Miami Athletics Ring of Honor announcement"],
  ["https://www.latimes.com/sports/highschool/story/2021-12-11/bryce-young-heisman-trophy-roots-la-cathedral-mater-dei","Los Angeles Times profile of Bryce Young’s roots"],
  ["https://www.latimes.com/sports/highschool/story/2020-01-11/bryce-young-father-scrutinizes-early-recruiting-process","Los Angeles Times recruiting profile"],
  ["https://www.latimes.com/sports/usc/story/2019-09-22/bryce-young-changes-commitment-from-usc-to-alabama","Los Angeles Times commitment report"],
  ["https://www.heisman.com/heisman-winners/bryce-young/","Heisman Trust Bryce Young biography"],
  ["https://www.azcardinals.com/news/mirror-image-budda-baker-joins-tyrann-mathieu-18849030","Arizona Cardinals feature on Budda Baker"],
  ["https://gohuskies.com/sports/football/roster/budda-baker/2117","Washington Athletics player biography"],
  ["https://www.azcardinals.com/news/budda-baker-heads-home-to-seattle-as-cardinal-20148657","Arizona Cardinals homecoming feature"],
  ["https://rolltide.com/news/2010/2/3/Crimson_Tide_Ink_18_on_National_Signing_Day","Alabama Athletics 2010 signing class release"],
  ["https://www.newyorkjets.com/news/jets-agree-to-terms-with-16-undrafted-free-agents","New York Jets undrafted free-agent release"],
  ["https://amp.nfl.com/news/michael-bennett-says-returning-to-ohio-state-was-right-choice-0ap3000000452701","NFL.com report quoting Reggie Ragland"],
  ["https://www.espn.com/college-football/story/_/id/8749314/cj-mosley-return-alabama-crimson-tide-senior-season","ESPN report on Mosley returning to Alabama"],
  ["https://www.espn.com/nfl/story/_/id/38834279/houston-texans-rookie-qb-cj-stroud-already-nfl-star","ESPN long-form profile of C.J. Stroud"],
  ["https://ohiostatebuckeyes.com/sports/football/roster/c-j-stroud/4470","Ohio State Athletics player biography"],
  ["https://ohiostatebuckeyes.com/sports/football/roster/caleb-downs/12257","Ohio State Athletics player biography"],
  ["https://rolltide.com/sports/football/roster/caleb-downs/8857","Alabama Athletics player biography"],
  ["https://www.heisman.com/heisman-winners/caleb-williams/","Heisman Trust Caleb Williams biography"],
  ["https://soonersports.com/news/2021/10/9/football-sooners-top-longhorns-in-red-river-showdown","Oklahoma Athletics Red River recap"],
  ["https://www.espn.com/college-football/story/_/id/38243587/2024-draft-the-moment-decision","ESPN profile of Caleb Williams"],
  ["https://www.heisman.com/heisman-winners/6721/","Heisman Trust Carson Palmer biography"],
  ["https://usctrojans.com/news/2018/4/18/trojan-athletic-fund-heritage-association-spotlight-carson-palmer","USC Athletics Heritage Association spotlight"],
  ["https://usctrojans.com/news/1999/11/22/Football_Closes_1999_Season_Friday","USC Athletics 1999 season notes"],
  ["https://usctrojans.com/news/2000/8/21/A_Look_At_Carson_Palmer","USC Athletics Carson Palmer feature"],
  ["https://usctrojans.com/news/1999/6/21/palmer_poised_to_lead_trojans","USC Athletics feature"],
  ["https://www.texasfootball.com/hof-cedric-benson","Texas High School Football Hall of Fame biography"],
  ["https://texaslonghorns.com/news/2004/3/5/030504aab_823","Texas Athletics announcement on Benson choosing football"],
  ["https://www.espn.com/nfl/playoffs/2013/story/_/id/10355918/super-bowl-xlviii-champ-bailey-gets-chance","ESPN profile of Champ Bailey"],
  ["https://georgiadogs.com/news/2019/10/2/champ-bailey-the-best-ever.aspx","Georgia Athletics feature on Champ Bailey"],
  ["https://georgiadogs.com/news/2003/4/23/As_athlete_Bailey_is_the_boss","Georgia Athletics Bailey family feature"],
  ["https://georgiadogs.com/news/2019/2/2/champ-bailey-named-to-pro-football-hall-of-fame","Georgia Athletics Pro Football Hall of Fame release"],
  ["https://www.heisman.com/articles/25th-anniversary-heisman-winner-charlie-ward/","Heisman Trust 25th-anniversary profile"],
  ["https://seminoles.com/news/2014/6/17/charlie-ward-bio/","Florida State Athletics Charlie Ward biography"],
  ["https://www.espn.com/college-football/story/_/id/38431102/inside-two-sport-florida-state-star-charlie-ward-heisman-season-30-years-later","ESPN 30-year retrospective on Charlie Ward"],
  ["https://mutigers.com/sports/football/roster/season/2005/player/chase-coffman","Missouri Athletics player biography"],
  ["https://mutigers.com/news/2005/02/02/football-announces-2005-recruiting-class","Missouri Athletics 2005 recruiting class release"],
  ["https://goducks.com/staff-directory/chip-kelly/333","University of Oregon Athletics Chip Kelly biography"],
  ["https://virginiasports.com/news/2006/09/17/chris-long-the-mayor-of-charlottesville","Virginia Athletics profile, “The Mayor of Charlottesville”"],
  ["https://gohuskies.com/sports/football/roster/coaches/chris-petersen/4183","Washington Athletics coach biography"],
  ["https://broncosports.com/sports/football/roster/coaches/chris-petersen/1117","Boise State Athletics coach biography"],
  ["https://gohuskies.com/news/2013/12/9/209336083","Washington Athletics introductory press conference"],
  ["https://www.heisman.com/heisman-winners/chris-weinke/","Heisman Trust Chris Weinke biography"],
  ["https://www.heisman.com/articles/heisman-profile-25th-anniversary-winner-chris-weinke/","Heisman Trust 25th-anniversary Weinke profile"],
  ["https://gostanford.com/sports/football/roster/season/2016/player/christian-mccaffrey","Stanford Athletics player biography"],
  ["https://www.hawaiinewsnow.com/story/23824344/brennan-signs-with-la-kiss-of-afl/","Hawaii News Now profile"],
  ["https://cubuffs.com/sports/football/roster/colt-brennan/3699?path=football","Colorado Athletics player biography"],
  ["https://hawaiiathletics.com/sports/football/roster/colt-brennan/7948","Hawaii Athletics player biography"],
  ["https://www.hawaii.edu/news/2021/05/11/in-memoriam-colt-brennan/","University of Hawaii memorial feature"],
  ["https://texaslonghorns.com/sports/football/roster/colt-mccoy/3394","Texas Athletics player biography"],
  ["https://texaslonghorns.com/sports/general/roster/colt-mccoy/5057","Texas Athletics Colt McCoy biography"],
  ["https://www.espn.com/college-football/story/_/id/39833081/cooper-dejean-latest-nfl-draft-find-iowa","ESPN — “Cooper DeJean is the latest NFL draft find from Iowa”"],
  ["https://www.pff.com/news/college-football-iowa-cb-cooper-dejeans-path-to-becoming-one-of-the-best-all-around-defensive-backs-in-college-football","PFF — “Iowa CB Cooper DeJean’s path to becoming one of the best all-around defensive backs in college football”"],
  ["https://www.inquirer.com/eagles/eagles-cooper-dejean-uncovering-the-birds-20250115.html","The Philadelphia Inquirer — Cooper DeJean Q&A"],
  ["https://www.inquirer.com/eagles/eagles-cooper-dejean-odebolt-iowa-high-school-highlights-20250110.html","The Philadelphia Inquirer — Cooper DeJean’s Iowa high-school legacy"],
  ["https://www.newyorkjets.com/news/jets-provide-thrills-on-nickelodeon-2410482","New York Jets — Nickelodeon feature"],
  ["https://www.newyorkjets.com/news/d-brickashaw-ferguson-s-heartfelt-goodbye-17023146","New York Jets — Ferguson retirement feature"],
  ["https://ca.sports.yahoo.com/blogs/nfl-shutdown-corner/shutdown-corner-interview-dbrickashaw-ferguson--nfl.html","Yahoo Sports — Shutdown Corner interview with D’Brickashaw Ferguson"],
  ["https://virginiasports.com/news/2003/04/21/d-brickashaw-ferguson-is-growing-force-on-offensive-line","Virginia Athletics — “D’Brickashaw Ferguson Is Growing Force on Offensive Line”"],
  ["https://virginiasports.com/news/2006/05/20/ferguson-completes-unique-athletic-academic-triple","Virginia Athletics — “Ferguson Completes Unique Athletic-Academic Triple”"],
  ["https://www.si.com/nfl/2017/10/19/dak-prescott-dallas-cowboys-mom-cancer","Sports Illustrated — profile of Dak Prescott and his mother Peggy"],
  ["https://www.si.com/college/2014/10/07/mississippi-state-inside-access","Sports Illustrated — Mississippi State inside-access feature"],
  ["https://www.dallascowboys.com/news/dak-s-road-to-dallas-why-prescott-s-rise-shouldn-t-be-a-surprise-417431","Dallas Cowboys — “Dak’s Road to Dallas”"],
  ["https://www.espn.com/college-football/recap?gameId=333320344","ESPN — 2013 Egg Bowl recap"],
  ["https://hailstate.com/sports/football/roster/prescott-dak/2911","Mississippi State Athletics — Dak Prescott bio"],
  ["https://magazine.foriowa.org/story.php?ed=true&storyid=2552","University of Iowa Magazine — Dallas Clark profile"],
  ["https://purduesports.com/news/2002/10/5/boilermakers-fall-to-no-24-iowa-31-28","Purdue Athletics — 2002 Iowa-Purdue recap"],
  ["https://www.colts.com/news/where-are-they-now-for-dallas-clark-there-s-no-place-like-home-19547878","Indianapolis Colts — “Where Are They Now? Dallas Clark”"],
  ["https://www.si.com/college/2016/03/10/dalvin-cook-fast-quiet-and-could-be-nations-top-rb","Sports Illustrated — Dalvin Cook profile"],
  ["https://www.si.com/nfl/2017/04/25/nfl-draft-dalvin-cook-red-flags-character-concerns-scouts-florida-state-miami-dade","Sports Illustrated — 2017 Dalvin Cook profile"],
  ["https://www.cbsnews.com/miami/news/miamis-yearby-fsus-cook-ex-teammates-now-rivals/","CBS Miami — Cook and Yearby, former teammates turned rivals"],
  ["https://www.espn.com/college-sports/recruiting/football/story/_/id/10391907/examining-pre-signing-day-flipping-epidemic-college-football-recruiting","ESPN — recruiting flip feature"],
  ["https://www.iheart.com/podcast/1119-unafraid-show-with-george-43072275/episode/dan-lanning-interview-mahomes-v-allen-145653316/","Unafraid Show / iHeart — Dan Lanning interview"],
  ["https://goducks.com/staff-directory/dan-lanning/3041","Oregon Athletics — Dan Lanning staff bio"],
  ["https://www.espn.com/college-football/story/_/id/40781349/dan-lanning-journey-commitment-oregon-big-ten-2024","ESPN — Dan Lanning journey to Oregon"],
  ["https://www.espn.com/college-football/story/_/id/39012854/oregon-flashy-dan-lanning-playing-tough-pac-12-championship","ESPN — Oregon and Dan Lanning culture feature"],
  ["https://sports.yahoo.com/articles/oregon-ducks-coach-dan-lannings-234500671.html","Yahoo Sports — Dan and Sauphia Lanning feature"],
  ["https://miamihurricanes.com/news/2021/12/08/a-dream-fulfilled-morgan-enshrined-in-cfb-hof/","Miami Hurricanes — “A Dream Fulfilled: Morgan Enshrined in CFB Hall”"],
  ["https://miamihurricanes.com/news/2021/01/11/morgan-selected-to-cfb-hall-of-fame-class-of-2021/","Miami Hurricanes — Dan Morgan CFB Hall announcement"],
  // PR9_SOURCE_INSERT
] as const;

export const footballPersonIdentityCfbBResearch = [
  // PR9_RECORD_INSERT
] as const;
