export type FootballSubjectAssetKind = "team-mark" | "program-mark";

export interface FootballSubjectAsset {
  src: string;
  kind: FootballSubjectAssetKind;
  label: string;
}

function nflMark(team: string, label: string): FootballSubjectAsset {
  return {
    src: `https://a.espncdn.com/i/teamlogos/nfl/500/${team}.png`,
    kind: "team-mark",
    label,
  };
}

function cfbMark(teamId: number, label: string): FootballSubjectAsset {
  return {
    src: `https://a.espncdn.com/i/teamlogos/ncaa/500/${teamId}.png`,
    kind: "program-mark",
    label,
  };
}

/**
 * Canonical visual catalog for the current Football Back Room subjects.
 *
 * Player and coach cards use the mark of the team/program most strongly tied to the
 * version of the subject represented by the game data. Program and single-season-team
 * subjects use their program mark directly. If/when approved local headshots are added,
 * this remains the one registry that swaps the source; game pages do not own image URLs.
 */
export const footballSubjectAssets: Readonly<Record<string, FootballSubjectAsset>> = {
  // NFL quarterbacks
  "tom-brady": nflMark("ne", "New England Patriots"),
  "patrick-mahomes": nflMark("kc", "Kansas City Chiefs"),
  "joe-montana": nflMark("sf", "San Francisco 49ers"),
  "peyton-manning": nflMark("ind", "Indianapolis Colts"),
  "aaron-rodgers": nflMark("gb", "Green Bay Packers"),
  "johnny-unitas": nflMark("ind", "Baltimore / Indianapolis Colts franchise"),
  "drew-brees": nflMark("no", "New Orleans Saints"),
  "dan-marino": nflMark("mia", "Miami Dolphins"),
  "john-elway": nflMark("den", "Denver Broncos"),
  "brett-favre": nflMark("gb", "Green Bay Packers"),
  "steve-young": nflMark("sf", "San Francisco 49ers"),
  "roger-staubach": nflMark("dal", "Dallas Cowboys"),
  "lamar-jackson": nflMark("bal", "Baltimore Ravens"),
  "kurt-warner": nflMark("lar", "Rams"),
  "terry-bradshaw": nflMark("pit", "Pittsburgh Steelers"),
  "ben-roethlisberger": nflMark("pit", "Pittsburgh Steelers"),
  "troy-aikman": nflMark("dal", "Dallas Cowboys"),
  "eli-manning": nflMark("nyg", "New York Giants"),
  "russell-wilson": nflMark("sea", "Seattle Seahawks"),
  "matt-ryan": nflMark("atl", "Atlanta Falcons"),
  "philip-rivers": nflMark("lac", "Chargers"),
  "matthew-stafford": nflMark("det", "Detroit Lions"),
  "cam-newton": nflMark("car", "Carolina Panthers"),
  "donovan-mcnabb": nflMark("phi", "Philadelphia Eagles"),
  "tony-romo": nflMark("dal", "Dallas Cowboys"),
  "carson-palmer": nflMark("ari", "Arizona Cardinals"),
  "joe-flacco": nflMark("bal", "Baltimore Ravens"),
  "kirk-cousins": nflMark("min", "Minnesota Vikings"),
  "derek-carr": nflMark("lv", "Raiders"),
  "andy-dalton": nflMark("cin", "Cincinnati Bengals"),
  "jay-cutler": nflMark("chi", "Chicago Bears"),
  "ryan-fitzpatrick": nflMark("buf", "Buffalo Bills"),
  "carson-wentz": nflMark("phi", "Philadelphia Eagles"),
  "jameis-winston": nflMark("tb", "Tampa Bay Buccaneers"),
  "marcus-mariota": nflMark("ten", "Tennessee Titans"),
  "sam-bradford": nflMark("lar", "Rams"),
  "mitchell-trubisky": nflMark("chi", "Chicago Bears"),
  "zach-wilson": nflMark("nyj", "New York Jets"),
  "jamarcus-russell": nflMark("lv", "Raiders"),
  "ryan-leaf": nflMark("lac", "Chargers"),
  "johnny-manziel": nflMark("cle", "Cleveland Browns"),

  // NFL running backs
  "jim-brown": nflMark("cle", "Cleveland Browns"),
  "barry-sanders": nflMark("det", "Detroit Lions"),
  "walter-payton": nflMark("chi", "Chicago Bears"),
  "emmitt-smith": nflMark("dal", "Dallas Cowboys"),
  "adrian-peterson": nflMark("min", "Minnesota Vikings"),
  "ladainian-tomlinson": nflMark("lac", "Chargers"),
  "marshall-faulk": nflMark("lar", "Rams"),
  "derrick-henry": nflMark("ten", "Tennessee Titans"),
  "eric-dickerson": nflMark("lar", "Rams"),
  "oj-simpson": nflMark("buf", "Buffalo Bills"),
  "earl-campbell": nflMark("ten", "Oilers / Titans franchise"),
  "curtis-martin": nflMark("nyj", "New York Jets"),
  "thurman-thomas": nflMark("buf", "Buffalo Bills"),
  "tony-dorsett": nflMark("dal", "Dallas Cowboys"),
  "marcus-allen": nflMark("lv", "Raiders"),
  "edgerrin-james": nflMark("ind", "Indianapolis Colts"),
  "jerome-bettis": nflMark("pit", "Pittsburgh Steelers"),
  "terrell-davis": nflMark("den", "Denver Broncos"),
  "frank-gore": nflMark("sf", "San Francisco 49ers"),
  "lesean-mccoy": nflMark("phi", "Philadelphia Eagles"),
  "marshawn-lynch": nflMark("sea", "Seattle Seahawks"),
  "steven-jackson": nflMark("lar", "Rams"),
  "priest-holmes": nflMark("kc", "Kansas City Chiefs"),
  "jamaal-charles": nflMark("kc", "Kansas City Chiefs"),
  "shaun-alexander": nflMark("sea", "Seattle Seahawks"),
  "clinton-portis": nflMark("wsh", "Washington"),
  "tiki-barber": nflMark("nyg", "New York Giants"),
  "eddie-george": nflMark("ten", "Tennessee Titans"),
  "ricky-williams": nflMark("mia", "Miami Dolphins"),
  "chris-johnson": nflMark("ten", "Tennessee Titans"),
  "maurice-jones-drew": nflMark("jax", "Jacksonville Jaguars"),
  "arian-foster": nflMark("hou", "Houston Texans"),
  "demarco-murray": nflMark("dal", "Dallas Cowboys"),
  "mark-ingram": nflMark("no", "New Orleans Saints"),
  "reggie-bush": nflMark("no", "New Orleans Saints"),
  "david-johnson": nflMark("ari", "Arizona Cardinals"),
  "eddie-lacy": nflMark("gb", "Green Bay Packers"),
  "darren-mcfadden": nflMark("lv", "Raiders"),
  "peyton-hillis": nflMark("cle", "Cleveland Browns"),
  "ron-dayne": nflMark("nyg", "New York Giants"),
  "trent-richardson": nflMark("cle", "Cleveland Browns"),
  "montee-ball": nflMark("den", "Denver Broncos"),

  // NFL wide receivers
  "jerry-rice": nflMark("sf", "San Francisco 49ers"),
  "randy-moss": nflMark("min", "Minnesota Vikings"),
  "terrell-owens": nflMark("sf", "San Francisco 49ers"),
  "calvin-johnson": nflMark("det", "Detroit Lions"),
  "larry-fitzgerald": nflMark("ari", "Arizona Cardinals"),
  "marvin-harrison": nflMark("ind", "Indianapolis Colts"),
  "antonio-brown": nflMark("pit", "Pittsburgh Steelers"),
  "julio-jones": nflMark("atl", "Atlanta Falcons"),
  "andre-johnson": nflMark("hou", "Houston Texans"),
  "tyreek-hill": nflMark("kc", "Kansas City Chiefs"),
  "cris-carter": nflMark("min", "Minnesota Vikings"),
  "steve-smith-sr": nflMark("car", "Carolina Panthers"),
  "isaac-bruce": nflMark("lar", "Rams"),
  "torry-holt": nflMark("lar", "Rams"),
  "tim-brown": nflMark("lv", "Raiders"),
  "reggie-wayne": nflMark("ind", "Indianapolis Colts"),
  "deandre-hopkins": nflMark("hou", "Houston Texans"),
  "mike-evans": nflMark("tb", "Tampa Bay Buccaneers"),
  "hines-ward": nflMark("pit", "Pittsburgh Steelers"),
  "anquan-boldin": nflMark("ari", "Arizona Cardinals"),
  "davante-adams": nflMark("gb", "Green Bay Packers"),
  "chad-johnson": nflMark("cin", "Cincinnati Bengals"),
  "brandon-marshall": nflMark("chi", "Chicago Bears"),
  "aj-green": nflMark("cin", "Cincinnati Bengals"),
  "demaryius-thomas": nflMark("den", "Denver Broncos"),
  "dez-bryant": nflMark("dal", "Dallas Cowboys"),
  "wes-welker": nflMark("ne", "New England Patriots"),
  "keenan-allen": nflMark("lac", "Chargers"),
  "roddy-white": nflMark("atl", "Atlanta Falcons"),
  "odell-beckham-jr": nflMark("nyg", "New York Giants"),
  "jordy-nelson": nflMark("gb", "Green Bay Packers"),
  "amari-cooper": nflMark("lv", "Raiders"),
  "santonio-holmes": nflMark("pit", "Pittsburgh Steelers"),
  "plaxico-burress": nflMark("nyg", "New York Giants"),
  "michael-thomas": nflMark("no", "New Orleans Saints"),
  "percy-harvin": nflMark("min", "Minnesota Vikings"),
  "juju-smith-schuster": nflMark("pit", "Pittsburgh Steelers"),
  "braylon-edwards": nflMark("cle", "Cleveland Browns"),
  "josh-gordon": nflMark("cle", "Cleveland Browns"),
  "sammy-watkins": nflMark("buf", "Buffalo Bills"),
  "kenny-golladay": nflMark("det", "Detroit Lions"),
  "kelvin-benjamin": nflMark("car", "Carolina Panthers"),
  "tavon-austin": nflMark("lar", "Rams"),
  "justin-blackmon": nflMark("jax", "Jacksonville Jaguars"),
  "corey-coleman": nflMark("cle", "Cleveland Browns"),
  "nkeal-harry": nflMark("ne", "New England Patriots"),
  "charles-rogers": nflMark("det", "Detroit Lions"),

  // NFL head coaches
  "bill-belichick": nflMark("ne", "New England Patriots"),
  "vince-lombardi": nflMark("gb", "Green Bay Packers"),
  "don-shula": nflMark("mia", "Miami Dolphins"),
  "andy-reid": nflMark("kc", "Kansas City Chiefs"),
  "bill-walsh": nflMark("sf", "San Francisco 49ers"),
  "chuck-noll": nflMark("pit", "Pittsburgh Steelers"),
  "tom-landry": nflMark("dal", "Dallas Cowboys"),
  "paul-brown": nflMark("cle", "Cleveland Browns"),
  "joe-gibbs": nflMark("wsh", "Washington"),
  "bill-parcells": nflMark("nyg", "New York Giants"),
  "mike-tomlin": nflMark("pit", "Pittsburgh Steelers"),
  "marty-schottenheimer": nflMark("kc", "Kansas City Chiefs"),
  "john-harbaugh": nflMark("bal", "Baltimore Ravens"),
  "pete-carroll": nflMark("sea", "Seattle Seahawks"),
  "sean-mcvay": nflMark("lar", "Los Angeles Rams"),
  "sean-payton": nflMark("no", "New Orleans Saints"),
  "tom-coughlin": nflMark("nyg", "New York Giants"),
  "tony-dungy": nflMark("ind", "Indianapolis Colts"),
  "mike-shanahan": nflMark("den", "Denver Broncos"),
  "bill-cowher": nflMark("pit", "Pittsburgh Steelers"),
  "mike-holmgren": nflMark("gb", "Green Bay Packers"),
  "mike-mccarthy": nflMark("gb", "Green Bay Packers"),
  "bruce-arians": nflMark("tb", "Tampa Bay Buccaneers"),
  "doug-pederson": nflMark("phi", "Philadelphia Eagles"),
  "dan-quinn": nflMark("atl", "Atlanta Falcons"),
  "ron-rivera": nflMark("car", "Carolina Panthers"),
  "marvin-lewis": nflMark("cin", "Cincinnati Bengals"),
  "mike-vrabel": nflMark("ten", "Tennessee Titans"),
  "jeff-fisher": nflMark("ten", "Oilers / Titans franchise"),
  "rex-ryan": nflMark("nyj", "New York Jets"),
  "jason-garrett": nflMark("dal", "Dallas Cowboys"),
  "kliff-kingsbury": nflMark("ari", "Arizona Cardinals"),
  "adam-gase": nflMark("nyj", "New York Jets"),
  "josh-mcdaniels": nflMark("lv", "Las Vegas Raiders"),
  "matt-patricia": nflMark("det", "Detroit Lions"),
  "nathaniel-hackett": nflMark("den", "Denver Broncos"),
  "urban-meyer": nflMark("jax", "Jacksonville Jaguars"),
  "hue-jackson": nflMark("cle", "Cleveland Browns"),

  // College quarterbacks
  "cam-newton-2010": cfbMark(2, "Auburn"),
  "joe-burrow-2019": cfbMark(99, "LSU"),
  "vince-young-2005": cfbMark(251, "Texas"),
  "tim-tebow-2007": cfbMark(57, "Florida"),
  "lamar-jackson-2016": cfbMark(97, "Louisville"),
  "matt-leinart-2004": cfbMark(30, "USC"),
  "baker-mayfield-2017": cfbMark(201, "Oklahoma"),
  "trevor-lawrence-2018": cfbMark(228, "Clemson"),
  "marcus-mariota-2014": cfbMark(2483, "Oregon"),
  "johnny-manziel-2012": cfbMark(245, "Texas A&M"),
  "colt-mccoy-2008": cfbMark(251, "Texas"),
  "sam-bradford-2008": cfbMark(201, "Oklahoma"),
  "caleb-williams-2022": cfbMark(30, "USC"),
  "bryce-young-2021": cfbMark(333, "Alabama"),
  "jameis-winston-2013": cfbMark(52, "Florida State"),

  // College programs
  "alabama-program": cfbMark(333, "Alabama"),
  "ohio-state-program": cfbMark(194, "Ohio State"),
  "georgia-program": cfbMark(61, "Georgia"),
  "lsu-program": cfbMark(99, "LSU"),
  "clemson-program": cfbMark(228, "Clemson"),
  "oklahoma-program": cfbMark(201, "Oklahoma"),
  "usc-program": cfbMark(30, "USC"),
  "florida-program": cfbMark(57, "Florida"),
  "texas-program": cfbMark(251, "Texas"),
  "florida-state-program": cfbMark(52, "Florida State"),
  "michigan-program": cfbMark(130, "Michigan"),
  "oregon-program": cfbMark(2483, "Oregon"),
  "auburn-program": cfbMark(2, "Auburn"),
  "miami-program": cfbMark(2390, "Miami"),
  "notre-dame-program": cfbMark(87, "Notre Dame"),

  // Single-season teams
  "2001-miami": cfbMark(2390, "Miami"),
  "2019-lsu": cfbMark(99, "LSU"),
  "2020-alabama": cfbMark(333, "Alabama"),
  "2005-texas": cfbMark(251, "Texas"),
  "2004-usc": cfbMark(30, "USC"),
  "2018-clemson": cfbMark(228, "Clemson"),
  "2013-florida-state": cfbMark(52, "Florida State"),
  "2022-georgia": cfbMark(61, "Georgia"),
  "2008-florida": cfbMark(57, "Florida"),
  "2010-auburn": cfbMark(2, "Auburn"),
  "2014-ohio-state": cfbMark(194, "Ohio State"),
  "2023-michigan": cfbMark(130, "Michigan"),
  "2009-alabama": cfbMark(333, "Alabama"),
  "2002-ohio-state": cfbMark(194, "Ohio State"),
  "2000-oklahoma": cfbMark(201, "Oklahoma"),
};

export function footballSubjectAsset(itemId: string) {
  return footballSubjectAssets[itemId] ?? null;
}
