import type { FootballCanonicalPosition } from "./footballFactualStatsCatalog";

export interface FootballProHallHistoricalRepairSeed {
  id: string;
  name: string;
  kind: "player-career" | "coach";
  position?: FootballCanonicalPosition;
  startSeason: number;
  endSeason: number;
  tier: "A" | "B";
}

/**
 * Official Pro Football Hall of Fame position/profile metadata for reviewed A/B identities that were genuinely
 * absent from the canonical A-C universe after existing canonical/source identities received their Hall tier floor.
 * These are recognition identity seeds only: no factual-stat values or game eligibility live here.
 */
export const footballProHallHistoricalRepairSeeds: readonly FootballProHallHistoricalRepairSeed[] = [
  { id: "nfl-herb-adderley", name: "Herb Adderley", kind: "player-career", position: "DB", startSeason: 1961, endSeason: 1972, tier: "B" },
  { id: "nfl-eric-allen", name: "Eric Allen", kind: "player-career", position: "DB", startSeason: 1988, endSeason: 2001, tier: "B" },
  { id: "nfl-george-allen", name: "George Allen", kind: "coach", startSeason: 1966, endSeason: 1977, tier: "B" },
  { id: "nfl-larry-allen", name: "Larry Allen", kind: "player-career", position: "OL", startSeason: 1994, endSeason: 2007, tier: "B" },
  { id: "nfl-lance-alworth", name: "Lance Alworth", kind: "player-career", position: "WR", startSeason: 1962, endSeason: 1972, tier: "B" },
  { id: "nfl-morten-andersen", name: "Morten Andersen", kind: "player-career", position: "K", startSeason: 1982, endSeason: 2007, tier: "B" },
  { id: "nfl-steve-atwater", name: "Steve Atwater", kind: "player-career", position: "DB", startSeason: 1989, endSeason: 1999, tier: "B" },
  { id: "nfl-lem-barney", name: "Lem Barney", kind: "player-career", position: "DB", startSeason: 1967, endSeason: 1977, tier: "B" },
  { id: "nfl-sammy-baugh", name: "Sammy Baugh", kind: "player-career", position: "QB", startSeason: 1937, endSeason: 1952, tier: "A" },
  { id: "nfl-chuck-bednarik", name: "Chuck Bednarik", kind: "player-career", position: "OL", startSeason: 1949, endSeason: 1962, tier: "A" },
  { id: "nfl-bobby-bell", name: "Bobby Bell", kind: "player-career", position: "LB", startSeason: 1963, endSeason: 1974, tier: "B" },
  { id: "nfl-raymond-berry", name: "Raymond Berry", kind: "player-career", position: "WR", startSeason: 1955, endSeason: 1967, tier: "A" },
  { id: "nfl-elvin-bethea", name: "Elvin Bethea", kind: "player-career", position: "DL", startSeason: 1968, endSeason: 1983, tier: "B" },
  { id: "nfl-fred-biletnikoff", name: "Fred Biletnikoff", kind: "player-career", position: "WR", startSeason: 1965, endSeason: 1978, tier: "B" },
  { id: "nfl-george-blanda", name: "George Blanda", kind: "player-career", position: "QB", startSeason: 1949, endSeason: 1975, tier: "B" },
  { id: "nfl-mel-blount", name: "Mel Blount", kind: "player-career", position: "DB", startSeason: 1970, endSeason: 1983, tier: "B" },
  { id: "nfl-tony-boselli", name: "Tony Boselli", kind: "player-career", position: "OL", startSeason: 1995, endSeason: 2001, tier: "B" },
  { id: "nfl-cliff-branch", name: "Cliff Branch", kind: "player-career", position: "WR", startSeason: 1972, endSeason: 1985, tier: "B" },
  { id: "nfl-robert-brazile", name: "Robert Brazile", kind: "player-career", position: "LB", startSeason: 1975, endSeason: 1984, tier: "B" },
  { id: "nfl-bob-boomer-brown", name: "Bob 'Boomer' Brown", kind: "player-career", position: "OL", startSeason: 1964, endSeason: 1973, tier: "B" },
  { id: "nfl-willie-brown", name: "Willie Brown", kind: "player-career", position: "DB", startSeason: 1963, endSeason: 1978, tier: "B" },
  { id: "nfl-junious-buck-buchanan", name: "Junious 'Buck' Buchanan", kind: "player-career", position: "DL", startSeason: 1963, endSeason: 1975, tier: "B" },
  { id: "nfl-nick-buoniconti", name: "Nick Buoniconti", kind: "player-career", position: "LB", startSeason: 1962, endSeason: 1976, tier: "B" },
  { id: "nfl-leroy-butler", name: "LeRoy Butler", kind: "player-career", position: "DB", startSeason: 1990, endSeason: 2001, tier: "B" },
  { id: "nfl-harold-carmichael", name: "Harold Carmichael", kind: "player-career", position: "WR", startSeason: 1971, endSeason: 1984, tier: "B" },
  { id: "nfl-harry-carson", name: "Harry Carson", kind: "player-career", position: "LB", startSeason: 1976, endSeason: 1988, tier: "B" },
  { id: "nfl-dave-casper", name: "Dave Casper", kind: "player-career", position: "TE", startSeason: 1974, endSeason: 1984, tier: "B" },
  { id: "nfl-don-coryell", name: "Don Coryell", kind: "coach", startSeason: 1973, endSeason: 1986, tier: "B" },
  { id: "nfl-jimbo-covert", name: "Jimbo Covert", kind: "player-career", position: "OL", startSeason: 1983, endSeason: 1990, tier: "B" },
  { id: "nfl-larry-csonka", name: "Larry Csonka", kind: "player-career", position: "RB", startSeason: 1968, endSeason: 1979, tier: "B" },
  { id: "nfl-curley-culp", name: "Curley Culp", kind: "player-career", position: "DL", startSeason: 1968, endSeason: 1981, tier: "B" },
  { id: "nfl-dermontti-dawson", name: "Dermontti Dawson", kind: "player-career", position: "OL", startSeason: 1988, endSeason: 2000, tier: "B" },
  { id: "nfl-fred-dean", name: "Fred Dean", kind: "player-career", position: "DL", startSeason: 1975, endSeason: 1985, tier: "B" },
  { id: "nfl-joe-delamielleure", name: "Joe DeLamielleure", kind: "player-career", position: "OL", startSeason: 1973, endSeason: 1985, tier: "B" },
  { id: "nfl-richard-dent", name: "Richard Dent", kind: "player-career", position: "DL", startSeason: 1983, endSeason: 1997, tier: "B" },
  { id: "nfl-dan-dierdorf", name: "Dan Dierdorf", kind: "player-career", position: "OL", startSeason: 1971, endSeason: 1983, tier: "B" },
  { id: "nfl-chris-doleman", name: "Chris Doleman", kind: "player-career", position: "DL", startSeason: 1985, endSeason: 1999, tier: "B" },
  { id: "nfl-kenny-easley", name: "Kenny Easley", kind: "player-career", position: "DB", startSeason: 1981, endSeason: 1987, tier: "B" },
  { id: "nfl-carl-eller", name: "Carl Eller", kind: "player-career", position: "DL", startSeason: 1964, endSeason: 1979, tier: "B" },
  { id: "nfl-weeb-ewbank", name: "Weeb Ewbank", kind: "coach", startSeason: 1954, endSeason: 1973, tier: "B" },
  { id: "nfl-ray-flaherty", name: "Ray Flaherty", kind: "coach", startSeason: 1936, endSeason: 1949, tier: "B" },
  { id: "nfl-tom-flores", name: "Tom Flores", kind: "coach", startSeason: 1979, endSeason: 1994, tier: "B" },
  { id: "nfl-frank-gifford", name: "Frank Gifford", kind: "player-career", position: "RB", startSeason: 1952, endSeason: 1964, tier: "A" },
  { id: "nfl-sid-gillman", name: "Sid Gillman", kind: "coach", startSeason: 1955, endSeason: 1974, tier: "B" },
  { id: "nfl-randy-gradishar", name: "Randy Gradishar", kind: "player-career", position: "LB", startSeason: 1974, endSeason: 1983, tier: "B" },
  { id: "nfl-harold-red-grange", name: "Harold 'Red' Grange", kind: "player-career", position: "RB", startSeason: 1925, endSeason: 1934, tier: "A" },
  { id: "nfl-bud-grant", name: "Bud Grant", kind: "coach", startSeason: 1967, endSeason: 1985, tier: "B" },
  { id: "nfl-darrell-green", name: "Darrell Green", kind: "player-career", position: "DB", startSeason: 1983, endSeason: 2002, tier: "B" },
  { id: "nfl-kevin-greene", name: "Kevin Greene", kind: "player-career", position: "DL", startSeason: 1985, endSeason: 1999, tier: "B" },
  { id: "nfl-forrest-gregg", name: "Forrest Gregg", kind: "player-career", position: "OL", startSeason: 1956, endSeason: 1971, tier: "B" },
  { id: "nfl-russ-grimm", name: "Russ Grimm", kind: "player-career", position: "OL", startSeason: 1981, endSeason: 1991, tier: "B" },
  { id: "nfl-george-halas", name: "George Halas", kind: "coach", startSeason: 1920, endSeason: 1967, tier: "A" },
  { id: "nfl-charles-haley", name: "Charles Haley", kind: "player-career", position: "DL", startSeason: 1986, endSeason: 1999, tier: "B" },
  { id: "nfl-jack-ham", name: "Jack Ham", kind: "player-career", position: "LB", startSeason: 1971, endSeason: 1982, tier: "B" },
  { id: "nfl-dan-hampton", name: "Dan Hampton", kind: "player-career", position: "DL", startSeason: 1979, endSeason: 1990, tier: "B" },
  { id: "nfl-chris-hanburger", name: "Chris Hanburger", kind: "player-career", position: "LB", startSeason: 1965, endSeason: 1978, tier: "B" },
  { id: "nfl-john-hannah", name: "John Hannah", kind: "player-career", position: "OL", startSeason: 1973, endSeason: 1985, tier: "B" },
  { id: "nfl-cliff-harris", name: "Cliff Harris", kind: "player-career", position: "DB", startSeason: 1970, endSeason: 1979, tier: "B" },
  { id: "nfl-bob-hayes", name: "Bob Hayes", kind: "player-career", position: "WR", startSeason: 1965, endSeason: 1975, tier: "B" },
  { id: "nfl-mike-haynes", name: "Mike Haynes", kind: "player-career", position: "DB", startSeason: 1976, endSeason: 1989, tier: "B" },
  { id: "nfl-ted-hendricks", name: "Ted Hendricks", kind: "player-career", position: "LB", startSeason: 1969, endSeason: 1983, tier: "B" },
  { id: "nfl-gene-hickerson", name: "Gene Hickerson", kind: "player-career", position: "OL", startSeason: 1958, endSeason: 1973, tier: "B" },
  { id: "nfl-winston-hill", name: "Winston Hill", kind: "player-career", position: "OL", startSeason: 1963, endSeason: 1977, tier: "B" },
  { id: "nfl-ken-houston", name: "Ken Houston", kind: "player-career", position: "DB", startSeason: 1967, endSeason: 1980, tier: "B" },
  { id: "nfl-chuck-howley", name: "Chuck Howley", kind: "player-career", position: "LB", startSeason: 1958, endSeason: 1973, tier: "B" },
  { id: "nfl-sam-huff", name: "Sam Huff", kind: "player-career", position: "LB", startSeason: 1956, endSeason: 1969, tier: "A" },
  { id: "nfl-claude-humphrey", name: "Claude Humphrey", kind: "player-career", position: "DL", startSeason: 1968, endSeason: 1981, tier: "B" },
  { id: "nfl-michael-irvin", name: "Michael Irvin", kind: "player-career", position: "WR", startSeason: 1988, endSeason: 1999, tier: "B" },
  { id: "nfl-rickey-jackson", name: "Rickey Jackson", kind: "player-career", position: "LB", startSeason: 1981, endSeason: 1995, tier: "B" },
  { id: "nfl-jimmy-johnson-coach", name: "Jimmy Johnson", kind: "coach", startSeason: 1989, endSeason: 1999, tier: "A" },
  { id: "nfl-jimmy-johnson-player", name: "Jimmy Johnson", kind: "player-career", position: "DB", startSeason: 1961, endSeason: 1976, tier: "B" },
  { id: "nfl-charlie-joiner", name: "Charlie Joiner", kind: "player-career", position: "WR", startSeason: 1969, endSeason: 1986, tier: "B" },
  { id: "nfl-alex-karras", name: "Alex Karras", kind: "player-career", position: "DL", startSeason: 1958, endSeason: 1970, tier: "B" },
  { id: "nfl-jim-kelly", name: "Jim Kelly", kind: "player-career", position: "QB", startSeason: 1986, endSeason: 1996, tier: "A" },
  { id: "nfl-cortez-kennedy", name: "Cortez Kennedy", kind: "player-career", position: "DL", startSeason: 1990, endSeason: 2000, tier: "B" },
  { id: "nfl-joe-klecko", name: "Joe Klecko", kind: "player-career", position: "DL", startSeason: 1977, endSeason: 1988, tier: "B" },
  { id: "nfl-paul-krause", name: "Paul Krause", kind: "player-career", position: "DB", startSeason: 1964, endSeason: 1979, tier: "B" },
  { id: "nfl-earl-curly-lambeau", name: "Earl 'Curly' Lambeau", kind: "coach", startSeason: 1919, endSeason: 1953, tier: "A" },
  { id: "nfl-jack-lambert", name: "Jack Lambert", kind: "player-career", position: "LB", startSeason: 1974, endSeason: 1984, tier: "B" },
  { id: "nfl-dick-night-train-lane", name: "Dick 'Night Train' Lane", kind: "player-career", position: "DB", startSeason: 1952, endSeason: 1965, tier: "A" },
  { id: "nfl-jim-langer", name: "Jim Langer", kind: "player-career", position: "OL", startSeason: 1970, endSeason: 1981, tier: "B" },
  { id: "nfl-willie-lanier", name: "Willie Lanier", kind: "player-career", position: "LB", startSeason: 1967, endSeason: 1977, tier: "B" },
  { id: "nfl-steve-largent", name: "Steve Largent", kind: "player-career", position: "WR", startSeason: 1976, endSeason: 1989, tier: "B" },
  { id: "nfl-bobby-layne", name: "Bobby Layne", kind: "player-career", position: "QB", startSeason: 1948, endSeason: 1962, tier: "A" },
  { id: "nfl-dick-lebeau", name: "Dick LeBeau", kind: "player-career", position: "DB", startSeason: 1959, endSeason: 1972, tier: "B" },
  { id: "nfl-marv-levy", name: "Marv Levy", kind: "coach", startSeason: 1978, endSeason: 1997, tier: "B" },
  { id: "nfl-bob-lilly", name: "Bob Lilly", kind: "player-career", position: "DL", startSeason: 1961, endSeason: 1974, tier: "B" },
  { id: "nfl-floyd-little", name: "Floyd Little", kind: "player-career", position: "RB", startSeason: 1967, endSeason: 1975, tier: "B" },
  { id: "nfl-larry-little", name: "Larry Little", kind: "player-career", position: "OL", startSeason: 1967, endSeason: 1980, tier: "B" },
  { id: "nfl-james-lofton", name: "James Lofton", kind: "player-career", position: "WR", startSeason: 1978, endSeason: 1993, tier: "B" },
  { id: "nfl-howie-long", name: "Howie Long", kind: "player-career", position: "DL", startSeason: 1981, endSeason: 1993, tier: "B" },
  { id: "nfl-sid-luckman", name: "Sid Luckman", kind: "player-career", position: "QB", startSeason: 1939, endSeason: 1950, tier: "A" },
  { id: "nfl-tom-mack", name: "Tom Mack", kind: "player-career", position: "OL", startSeason: 1966, endSeason: 1978, tier: "B" },
  { id: "nfl-john-madden", name: "John Madden", kind: "coach", startSeason: 1969, endSeason: 1978, tier: "A" },
  { id: "nfl-bruce-matthews", name: "Bruce Matthews", kind: "player-career", position: "OL", startSeason: 1983, endSeason: 2001, tier: "B" },
  { id: "nfl-don-maynard", name: "Don Maynard", kind: "player-career", position: "WR", startSeason: 1958, endSeason: 1973, tier: "B" },
  { id: "nfl-randall-mcdaniel", name: "Randall McDaniel", kind: "player-career", position: "OL", startSeason: 1988, endSeason: 2001, tier: "B" },
  { id: "nfl-steve-mcmichael", name: "Steve McMichael", kind: "player-career", position: "DL", startSeason: 1980, endSeason: 1994, tier: "B" },
  { id: "nfl-sam-mills", name: "Sam Mills", kind: "player-career", position: "LB", startSeason: 1986, endSeason: 1997, tier: "B" },
  { id: "nfl-art-monk", name: "Art Monk", kind: "player-career", position: "WR", startSeason: 1980, endSeason: 1995, tier: "B" },
  { id: "nfl-mike-munchak", name: "Mike Munchak", kind: "player-career", position: "OL", startSeason: 1982, endSeason: 1993, tier: "B" },
  { id: "nfl-bronko-nagurski", name: "Bronko Nagurski", kind: "player-career", position: "RB", startSeason: 1930, endSeason: 1943, tier: "A" },
  { id: "nfl-earle-greasy-neale", name: "Earle 'Greasy' Neale", kind: "coach", startSeason: 1941, endSeason: 1950, tier: "B" },
  { id: "nfl-ray-nitschke", name: "Ray Nitschke", kind: "player-career", position: "LB", startSeason: 1958, endSeason: 1972, tier: "B" },
  { id: "nfl-merlin-olsen", name: "Merlin Olsen", kind: "player-career", position: "DL", startSeason: 1962, endSeason: 1976, tier: "B" },
  { id: "nfl-jim-otto", name: "Jim Otto", kind: "player-career", position: "OL", startSeason: 1960, endSeason: 1974, tier: "B" },
  { id: "nfl-steve-owen", name: "Steve Owen", kind: "coach", startSeason: 1930, endSeason: 1953, tier: "B" },
  { id: "nfl-drew-pearson", name: "Drew Pearson", kind: "player-career", position: "WR", startSeason: 1973, endSeason: 1983, tier: "B" },
  { id: "nfl-john-randle", name: "John Randle", kind: "player-career", position: "DL", startSeason: 1990, endSeason: 2003, tier: "B" },
  { id: "nfl-andre-reed", name: "Andre Reed", kind: "player-career", position: "WR", startSeason: 1985, endSeason: 2000, tier: "B" },
  { id: "nfl-mel-renfro", name: "Mel Renfro", kind: "player-career", position: "DB", startSeason: 1964, endSeason: 1977, tier: "B" },
  { id: "nfl-ken-riley", name: "Ken Riley", kind: "player-career", position: "DB", startSeason: 1969, endSeason: 1983, tier: "B" },
  { id: "nfl-willie-roaf", name: "Willie Roaf", kind: "player-career", position: "OL", startSeason: 1993, endSeason: 2005, tier: "B" },
  { id: "nfl-dave-robinson", name: "Dave Robinson", kind: "player-career", position: "LB", startSeason: 1963, endSeason: 1974, tier: "B" },
  { id: "nfl-johnny-robinson", name: "Johnny Robinson", kind: "player-career", position: "DB", startSeason: 1960, endSeason: 1971, tier: "B" },
  { id: "nfl-charlie-sanders", name: "Charlie Sanders", kind: "player-career", position: "TE", startSeason: 1968, endSeason: 1977, tier: "B" },
  { id: "nfl-lee-roy-selmon", name: "Lee Roy Selmon", kind: "player-career", position: "DL", startSeason: 1976, endSeason: 1984, tier: "B" },
  { id: "nfl-sterling-sharpe", name: "Sterling Sharpe", kind: "player-career", position: "WR", startSeason: 1988, endSeason: 1994, tier: "B" },
  { id: "nfl-art-shell", name: "Art Shell", kind: "player-career", position: "OL", startSeason: 1968, endSeason: 1982, tier: "B" },
  { id: "nfl-donnie-shell", name: "Donnie Shell", kind: "player-career", position: "DB", startSeason: 1974, endSeason: 1987, tier: "B" },
  { id: "nfl-mike-singletary", name: "Mike Singletary", kind: "player-career", position: "LB", startSeason: 1981, endSeason: 1992, tier: "B" },
  { id: "nfl-jackie-slater", name: "Jackie Slater", kind: "player-career", position: "OL", startSeason: 1976, endSeason: 1995, tier: "B" },
  { id: "nfl-jackie-smith", name: "Jackie Smith", kind: "player-career", position: "TE", startSeason: 1963, endSeason: 1978, tier: "B" },
  { id: "nfl-john-stallworth", name: "John Stallworth", kind: "player-career", position: "WR", startSeason: 1974, endSeason: 1987, tier: "B" },
  { id: "nfl-roger-staubach", name: "Roger Staubach", kind: "player-career", position: "QB", startSeason: 1969, endSeason: 1979, tier: "A" },
  { id: "nfl-dwight-stephenson", name: "Dwight Stephenson", kind: "player-career", position: "OL", startSeason: 1980, endSeason: 1987, tier: "B" },
  { id: "nfl-hank-stram", name: "Hank Stram", kind: "coach", startSeason: 1960, endSeason: 1977, tier: "B" },
  { id: "nfl-lynn-swann", name: "Lynn Swann", kind: "player-career", position: "WR", startSeason: 1974, endSeason: 1982, tier: "B" },
  { id: "nfl-charley-taylor", name: "Charley Taylor", kind: "player-career", position: "WR", startSeason: 1964, endSeason: 1977, tier: "B" },
  { id: "nfl-derrick-thomas", name: "Derrick Thomas", kind: "player-career", position: "LB", startSeason: 1989, endSeason: 1999, tier: "B" },
  { id: "nfl-emmitt-thomas", name: "Emmitt Thomas", kind: "player-career", position: "DB", startSeason: 1966, endSeason: 1978, tier: "B" },
  { id: "nfl-jim-thorpe", name: "Jim Thorpe", kind: "player-career", position: "RB", startSeason: 1915, endSeason: 1928, tier: "A" },
  { id: "nfl-mick-tingelhoff", name: "Mick Tingelhoff", kind: "player-career", position: "OL", startSeason: 1962, endSeason: 1978, tier: "B" },
  { id: "nfl-andre-tippett", name: "Andre Tippett", kind: "player-career", position: "LB", startSeason: 1982, endSeason: 1993, tier: "B" },
  { id: "nfl-emlen-tunnell", name: "Emlen Tunnell", kind: "player-career", position: "DB", startSeason: 1948, endSeason: 1961, tier: "A" },
  { id: "nfl-gene-upshaw", name: "Gene Upshaw", kind: "player-career", position: "OL", startSeason: 1967, endSeason: 1981, tier: "B" },
  { id: "nfl-dick-vermeil", name: "Dick Vermeil", kind: "coach", startSeason: 1976, endSeason: 2005, tier: "B" },
  { id: "nfl-doak-walker", name: "Doak Walker", kind: "player-career", position: "RB", startSeason: 1950, endSeason: 1955, tier: "A" },
  { id: "nfl-paul-warfield", name: "Paul Warfield", kind: "player-career", position: "WR", startSeason: 1964, endSeason: 1977, tier: "B" },
  { id: "nfl-mike-webster", name: "Mike Webster", kind: "player-career", position: "OL", startSeason: 1974, endSeason: 1990, tier: "B" },
  { id: "nfl-roger-wehrli", name: "Roger Wehrli", kind: "player-career", position: "DB", startSeason: 1969, endSeason: 1982, tier: "B" },
  { id: "nfl-randy-white", name: "Randy White", kind: "player-career", position: "DL", startSeason: 1975, endSeason: 1988, tier: "B" },
  { id: "nfl-dave-wilcox", name: "Dave Wilcox", kind: "player-career", position: "LB", startSeason: 1964, endSeason: 1974, tier: "B" },
  { id: "nfl-larry-wilson", name: "Larry Wilson", kind: "player-career", position: "DB", startSeason: 1960, endSeason: 1972, tier: "B" },
  { id: "nfl-willie-wood", name: "Willie Wood", kind: "player-career", position: "DB", startSeason: 1960, endSeason: 1971, tier: "B" },
  { id: "nfl-rayfield-wright", name: "Rayfield Wright", kind: "player-career", position: "OL", startSeason: 1967, endSeason: 1979, tier: "B" },
  { id: "nfl-ron-yary", name: "Ron Yary", kind: "player-career", position: "OL", startSeason: 1968, endSeason: 1982, tier: "B" },
  { id: "nfl-jack-youngblood", name: "Jack Youngblood", kind: "player-career", position: "DL", startSeason: 1971, endSeason: 1984, tier: "B" },
  { id: "nfl-gary-zimmerman", name: "Gary Zimmerman", kind: "player-career", position: "OL", startSeason: 1986, endSeason: 1997, tier: "B" },
] as const;
