export type FootballWavelengthExpansionSeed = readonly [id: string, text: string, rating: number];

export interface FootballWavelengthExpansionCategory {
  category: string;
  prefix: string;
  seeds: readonly FootballWavelengthExpansionSeed[];
}

export const footballWavelengthExpansionCategories = [
  {
    category: "NFL LEGACY",
    prefix: "legacy",
    seeds: [
      ["baker-mayfield", "Baker Mayfield", 38],
      ["matt-ryan", "Matt Ryan", 70],
      ["philip-rivers", "Philip Rivers", 78],
      ["ben-roethlisberger", "Ben Roethlisberger", 87],
      ["joe-montana", "Joe Montana", 99],
    ],
  },
  {
    category: "GUNSLINGER",
    prefix: "gunslinger",
    seeds: [
      ["drew-brees", "Drew Brees", 65],
      ["philip-rivers", "Philip Rivers", 75],
      ["justin-herbert", "Justin Herbert", 79],
      ["joe-namath", "Joe Namath", 95],
      ["jameis-winston", "Jameis Winston", 98],
    ],
  },
  {
    category: "QB CARRY JOB",
    prefix: "carry",
    seeds: [
      ["jake-coker-2015", "Jake Coker on 2015 Alabama", 12],
      ["stetson-bennett-2021", "Stetson Bennett on 2021 Georgia", 34],
      ["caleb-williams-2023", "Caleb Williams on 2023 USC", 94],
      ["rg3-2012", "Robert Griffin III on 2012 Washington", 96],
      ["cam-newton-2010-auburn", "Cam Newton on 2010 Auburn", 100],
    ],
  },
  {
    category: "OFFENSIVE CHAOS",
    prefix: "chaos",
    seeds: [
      ["2000-ravens", "2000 Ravens offense", 18],
      ["1984-byu", "1984 BYU offense", 75],
      ["2022-usc", "2022 USC offense", 82],
      ["2023-dolphins", "2023 Dolphins offense", 86],
      ["2012-baylor", "2012 Baylor offense", 94],
    ],
  },
  {
    category: "FANBASE INSANITY",
    prefix: "fans",
    seeds: [
      ["northwestern", "Northwestern", 7],
      ["stanford", "Stanford", 18],
      ["browns", "Cleveland Browns", 73],
      ["raiders", "Las Vegas Raiders", 90],
      ["west-virginia", "West Virginia", 92],
    ],
  },
  {
    category: "PROGRAM TRADITION",
    prefix: "tradition",
    seeds: [
      ["indiana", "Indiana", 18],
      ["iowa", "Iowa", 52],
      ["auburn", "Auburn", 78],
      ["oklahoma", "Oklahoma", 95],
      ["alabama", "Alabama", 99],
    ],
  },
  {
    category: "UNIFORM QUALITY",
    prefix: "uniform",
    seeds: [
      ["titans-current", "Tennessee Titans current set", 31],
      ["penn-state", "Penn State", 89],
      ["notre-dame", "Notre Dame", 91],
      ["florida-state", "Florida State", 92],
      ["chargers-powder-blue", "Chargers powder blue", 96],
    ],
  },
  {
    category: "STADIUM ATMOSPHERE",
    prefix: "atmosphere",
    seeds: [
      ["vanderbilt", "Vanderbilt home game", 14],
      ["northwestern", "Northwestern home game", 20],
      ["nebraska-memorial", "Nebraska Memorial Stadium", 86],
      ["camp-randall", "Camp Randall Stadium", 90],
      ["the-swamp", "The Swamp at Florida", 94],
    ],
  },
  {
    category: "RIVALRY HATRED",
    prefix: "rivalry",
    seeds: [
      ["texans-jaguars", "Texans–Jaguars", 15],
      ["georgia-georgia-tech", "Georgia–Georgia Tech", 75],
      ["nebraska-oklahoma", "Nebraska–Oklahoma", 82],
      ["florida-florida-state", "Florida–Florida State", 93],
      ["ole-miss-miss-state", "Ole Miss–Mississippi State", 95],
    ],
  },
  {
    category: "SYSTEM QB PERCEPTION",
    prefix: "system-qb",
    seeds: [
      ["drew-brees", "Drew Brees", 25],
      ["joe-montana", "Joe Montana", 42],
      ["ryan-tannehill", "Ryan Tannehill", 49],
      ["tim-tebow", "Tim Tebow", 72],
      ["jimmy-garoppolo", "Jimmy Garoppolo", 84],
    ],
  },
  {
    category: "COACHING CHAOS",
    prefix: "coach-chaos",
    seeds: [
      ["kyle-shanahan", "Kyle Shanahan", 26],
      ["mike-mcdaniel", "Mike McDaniel", 55],
      ["dabo-swinney", "Dabo Swinney", 63],
      ["mike-gundy", "Mike Gundy", 88],
      ["ed-orgeron", "Ed Orgeron", 92],
    ],
  },
  {
    category: "OFFENSIVE INNOVATION",
    prefix: "innovation",
    seeds: [
      ["brian-ferentz", "Brian Ferentz offense", 2],
      ["greg-roman", "Greg Roman", 70],
      ["paul-johnson", "Paul Johnson triple option", 84],
      ["june-jones", "June Jones run-and-shoot", 91],
      ["sid-gillman", "Sid Gillman", 99],
    ],
  },
  {
    category: "DEFENSIVE TERROR",
    prefix: "terror",
    seeds: [
      ["2023-panthers", "2023 Panthers defense", 20],
      ["2019-patriots", "2019 Patriots defense", 88],
      ["micah-parsons", "Prime Micah Parsons", 90],
      ["derrick-thomas", "Prime Derrick Thomas", 97],
      ["1992-alabama", "1992 Alabama defense", 99],
    ],
  },
  {
    category: "DRAFT BUST",
    prefix: "bust",
    seeds: [
      ["penei-sewell", "Penei Sewell", 2],
      ["alex-smith", "Alex Smith", 32],
      ["sam-darnold", "Sam Darnold", 68],
      ["robert-griffin-iii", "Robert Griffin III", 72],
      ["charles-rogers", "Charles Rogers", 96],
    ],
  },
  {
    category: "CLUTCH REPUTATION",
    prefix: "clutch",
    seeds: [
      ["matt-ryan", "Matt Ryan", 55],
      ["jj-mccarthy", "J.J. McCarthy at Michigan", 85],
      ["tua-2017-title", "Tua Tagovailoa in the 2017 national title game", 90],
      ["nick-foles", "Nick Foles in the playoffs", 94],
      ["stetson-bennett", "Stetson Bennett in the CFP", 95],
    ],
  },
  {
    category: "CHOKE REPUTATION",
    prefix: "choke",
    seeds: [
      ["nick-saban", "Nick Saban", 2],
      ["oregon-modern", "Modern Oregon postseason narrative", 64],
      ["oklahoma-cfp", "Oklahoma in the CFP era", 83],
      ["chargers-playoffs", "Chargers playoff history", 86],
      ["bills-four-super-bowls", "Bills four straight Super Bowl losses", 88],
    ],
  },
  {
    category: "FRANCHISE TRADITION",
    prefix: "franchise",
    seeds: [
      ["lions", "Detroit Lions", 74],
      ["browns", "Cleveland Browns", 76],
      ["patriots", "New England Patriots", 96],
      ["cowboys", "Dallas Cowboys", 98],
      ["bears", "Chicago Bears", 99],
    ],
  },
  {
    category: "FOOTBALL WEIRDNESS",
    prefix: "weird",
    seeds: [
      ["standard-field-goal", "Standard field goal", 5],
      ["stanford-tree", "Stanford Tree mascot", 88],
      ["lsu-shoe-throw", "LSU–Florida shoe throw", 90],
      ["fair-catch-kick", "Fair-catch kick", 92],
      ["iowa-6-4", "Iowa winning 6–4", 98],
    ],
  },
  {
    category: "MEDIA ENERGY",
    prefix: "media",
    seeds: [
      ["joe-buck", "Joe Buck", 50],
      ["dan-orlovsky", "Dan Orlovsky", 78],
      ["gus-johnson", "Gus Johnson", 85],
      ["colin-cowherd", "Colin Cowherd football debate", 89],
      ["lee-corso", "Lee Corso on College GameDay", 92],
    ],
  },
  {
    category: "TAILGATE CULTURE",
    prefix: "tailgate",
    seeds: [
      ["stanford", "Stanford tailgate scene", 10],
      ["usc", "USC tailgate scene", 60],
      ["penn-state", "Penn State tailgate scene", 90],
      ["green-bay", "Green Bay game-day tailgate", 92],
      ["tennessee-vol-navy", "Tennessee Vol Navy", 96],
    ],
  },
  {
    category: "COACHING GENIUS",
    prefix: "genius",
    seeds: [
      ["jeff-saturday", "Jeff Saturday as Colts interim coach", 4],
      ["urban-meyer-jaguars", "Urban Meyer with the Jaguars", 8],
      ["matt-patricia", "Matt Patricia as Lions head coach", 12],
      ["average-coordinator", "A league-average coordinator", 50],
      ["dan-campbell", "Dan Campbell", 70],
      ["lincoln-riley", "Lincoln Riley", 84],
      ["mike-tomlin", "Mike Tomlin", 86],
      ["sean-mcvay", "Sean McVay", 88],
      ["kyle-shanahan", "Kyle Shanahan", 89],
      ["jim-harbaugh", "Jim Harbaugh", 90],
      ["pete-carroll", "Pete Carroll", 91],
      ["steve-spurrier", "Steve Spurrier", 94],
      ["kirby-smart", "Kirby Smart", 95],
      ["tom-landry", "Tom Landry", 96],
      ["don-shula", "Don Shula", 97],
      ["bill-belichick", "Bill Belichick", 97],
      ["andy-reid", "Andy Reid", 98],
      ["bear-bryant", "Bear Bryant", 99],
      ["bill-walsh", "Bill Walsh", 100],
      ["nick-saban", "Nick Saban", 100],
    ],
  },
  {
    category: "HOME-FIELD ADVANTAGE",
    prefix: "home-field",
    seeds: [
      ["empty-stadium", "A 2020 empty stadium", 1],
      ["chargers-sofi", "Chargers at SoFi Stadium", 12],
      ["vanderbilt", "Vanderbilt", 20],
      ["stanford", "Stanford", 25],
      ["cowboys-att", "Cowboys at AT&T Stadium", 48],
      ["notre-dame", "Notre Dame Stadium", 70],
      ["browns", "Cleveland Browns Stadium", 72],
      ["texas-dkr", "Texas at DKR", 82],
      ["wisconsin", "Wisconsin at Camp Randall", 88],
      ["bills", "Bills in Orchard Park", 89],
      ["alabama", "Alabama at Bryant-Denny", 91],
      ["seahawks", "Seahawks at Lumen Field", 92],
      ["florida", "Florida at The Swamp", 94],
      ["lambeau", "Packers at Lambeau Field", 95],
      ["oregon", "Oregon at Autzen Stadium", 96],
      ["tennessee", "Tennessee at Neyland Stadium", 96],
      ["texas-am", "Texas A&M at Kyle Field", 97],
      ["chiefs", "Chiefs at Arrowhead Stadium", 98],
      ["penn-state-whiteout", "Penn State White Out", 99],
      ["lsu-night", "LSU at Tiger Stadium at night", 100],
    ],
  },
  {
    category: "FOOTBALL VILLAINY",
    prefix: "villainy",
    seeds: [
      ["andrew-luck", "Andrew Luck", 4],
      ["barry-sanders", "Barry Sanders", 5],
      ["larry-fitzgerald", "Larry Fitzgerald", 8],
      ["texas", "Texas football", 60],
      ["nebraska-1990s", "1990s Nebraska", 65],
      ["raiders", "Raiders", 70],
      ["lane-kiffin", "Lane Kiffin", 75],
      ["oklahoma", "Oklahoma football", 76],
      ["steelers-1970s", "1970s Steelers", 78],
      ["deion-sanders", "Deion Sanders", 80],
      ["aaron-rodgers", "Aaron Rodgers", 82],
      ["michigan", "Michigan football", 85],
      ["miami-1980s", "1980s Miami Hurricanes", 86],
      ["nick-saban", "Nick Saban", 88],
      ["cowboys", "Dallas Cowboys", 90],
      ["ohio-state", "Ohio State football", 92],
      ["tom-brady", "Tom Brady", 94],
      ["urban-meyer", "Urban Meyer", 95],
      ["bill-belichick", "Bill Belichick", 96],
      ["patriots-dynasty", "Patriots dynasty", 98],
    ],
  },
  {
    category: "FRANCHISE DYSFUNCTION",
    prefix: "dysfunction",
    seeds: [
      ["steelers", "Pittsburgh Steelers", 5],
      ["packers", "Green Bay Packers", 8],
      ["ravens", "Baltimore Ravens", 12],
      ["chiefs", "Kansas City Chiefs", 15],
      ["patriots", "New England Patriots", 25],
      ["49ers", "San Francisco 49ers", 35],
      ["eagles", "Philadelphia Eagles", 40],
      ["seahawks", "Seattle Seahawks", 45],
      ["bears", "Chicago Bears", 60],
      ["cowboys-modern", "Modern Dallas Cowboys", 68],
      ["dolphins", "Miami Dolphins", 70],
      ["raiders", "Las Vegas Raiders", 72],
      ["chargers", "Los Angeles Chargers", 78],
      ["jaguars", "Jacksonville Jaguars", 85],
      ["cardinals", "Arizona Cardinals", 88],
      ["panthers", "Carolina Panthers", 90],
      ["lions-pre-2023", "Pre-2023 Detroit Lions", 92],
      ["jets", "New York Jets", 95],
      ["commanders-snyder", "Washington under Dan Snyder", 100],
      ["browns-modern", "Modern Cleveland Browns", 100],
    ],
  },
  {
    category: "OFFENSIVE FIREPOWER",
    prefix: "firepower",
    seeds: [
      ["2023-iowa", "2023 Iowa", 2],
      ["2000-ravens", "2000 Ravens", 20],
      ["2023-steelers", "2023 Steelers", 30],
      ["2015-broncos", "2015 Broncos", 35],
      ["2011-alabama", "2011 Alabama", 55],
      ["2021-georgia", "2021 Georgia", 75],
      ["2022-usc", "2022 USC", 88],
      ["2023-dolphins", "2023 Dolphins", 89],
      ["2016-oklahoma", "2016 Oklahoma", 90],
      ["2010-auburn", "2010 Auburn", 92],
      ["2014-oregon", "2014 Oregon", 93],
      ["2004-usc", "2004 USC", 94],
      ["1995-nebraska", "1995 Nebraska", 95],
      ["2005-texas", "2005 Texas", 96],
      ["2018-chiefs", "2018 Chiefs", 98],
      ["2020-alabama", "2020 Alabama", 99],
      ["greatest-show-on-turf", "Greatest Show on Turf Rams", 99],
      ["2007-patriots", "2007 Patriots", 100],
      ["2013-broncos", "2013 Broncos", 100],
      ["2019-lsu", "2019 LSU", 100],
    ],
  },
  {
    category: "BIG ARM TALENT",
    prefix: "arm",
    seeds: [
      ["chad-pennington", "Chad Pennington", 8],
      ["drew-brees", "Drew Brees", 55],
      ["tom-brady", "Tom Brady", 62],
      ["joe-burrow", "Joe Burrow", 72],
      ["caleb-williams", "Caleb Williams", 90],
      ["drake-maye", "Drake Maye", 91],
      ["michael-vick", "Michael Vick", 92],
      ["aaron-rodgers", "Aaron Rodgers", 94],
      ["cam-newton", "Cam Newton", 95],
      ["jay-cutler", "Jay Cutler", 95],
      ["matthew-stafford", "Matthew Stafford", 96],
      ["justin-herbert", "Justin Herbert", 97],
      ["brett-favre", "Brett Favre", 98],
      ["jeff-george", "Jeff George", 98],
      ["anthony-richardson", "Anthony Richardson", 99],
      ["john-elway", "John Elway", 99],
      ["patrick-mahomes", "Patrick Mahomes", 99],
      ["josh-allen", "Josh Allen", 100],
      ["jamarcus-russell", "JaMarcus Russell", 100],
      ["joe-milton", "Joe Milton", 100],
    ],
  },
  {
    category: "ATHLETIC FREAK",
    prefix: "freak",
    seeds: [
      ["tom-brady-combine", "Tom Brady at the combine", 5],
      ["peyton-manning", "Peyton Manning", 10],
      ["philip-rivers", "Philip Rivers", 15],
      ["drew-brees", "Drew Brees", 25],
      ["joe-burrow", "Joe Burrow", 50],
      ["travis-kelce", "Travis Kelce", 65],
      ["christian-mccaffrey", "Christian McCaffrey", 78],
      ["lane-johnson", "Lane Johnson", 90],
      ["kyle-pitts", "Kyle Pitts", 94],
      ["reggie-bush", "Reggie Bush at USC", 94],
      ["randy-moss", "Randy Moss", 96],
      ["saquon-barkley", "Saquon Barkley", 96],
      ["jevon-kearse", "Jevon Kearse", 97],
      ["cam-newton", "Cam Newton", 97],
      ["lamar-jackson", "Lamar Jackson", 97],
      ["dk-metcalf", "DK Metcalf", 98],
      ["jadeveon-clowney", "Jadeveon Clowney", 98],
      ["micah-parsons", "Micah Parsons", 98],
      ["derrick-henry", "Derrick Henry", 99],
      ["bo-jackson", "Bo Jackson", 100],
    ],
  },
] as const satisfies readonly FootballWavelengthExpansionCategory[];

export const FOOTBALL_WAVELENGTH_EXPANSION_CLUE_COUNT = footballWavelengthExpansionCategories.reduce(
  (total, category) => total + category.seeds.length,
  0,
);
