// PR9 CFB B-tier research data only. Canonical validation and lookup remain in footballPersonIdentityKnowledge.ts.
export const footballPersonIdentityCfbBResearchSources = [
  ["https://mgoblue.com/sports/football/roster/jake-butt/1408","Michigan Athletics — Jake Butt roster"],
  ["https://mgoblue.com/news/2017/4/20/kornacki_butt_looking_to_change_lives","Michigan Athletics — Kornacki: Butt Looking to Change Lives"],
  ["https://mgoblue.com/news/2017/10/9/football-perry-finds-meaning-in-wearing-butts-no-88","Michigan Athletics — Perry Finds Meaning in Wearing Butt's No. 88"],
  ["https://mgoblue.com/news/2008/4/22/dolphins_sign_long_make_him_top_pick_in_nfl_draft","Michigan Athletics — Dolphins Sign Long, Make Him Top Pick in NFL Draft"],
  ["https://mgoblue.com/news/2003/2/5/2003_signing_day_comments_from_coach_lloyd_carr","Michigan Athletics — 2003 Signing Day Comments from Coach Lloyd Carr"],
  ["https://12thman.com/sports/football/roster/season/2010/player/jake-matthews","Texas A&M Athletics — Jake Matthews roster"],
  ["https://12thman.com/news/2023/09/15/2023-texas-am-athletics-hall-of-fame-class-enshrined-at-45th-burgess-banquet","Texas A&M Athletics — 2023 Hall of Fame class banquet"],
  ["https://12thman.com/news/2013/09/11/family-first-1","Texas A&M Athletics — Family First"],
  ["https://12thman.com/news/2013/08/30/family-tradition","Texas A&M Athletics — Family Tradition"],
  ["https://12thman.com/news/2013/01/10/jake-matthews-to-return-to-aggieland","Texas A&M Athletics — Jake Matthews to Return to Aggieland"],
  ["https://georgiadogs.com/roster.aspx?rp_id=4881","Georgia Athletics — Jalen Carter roster"],
  ["https://seminoles.com/news/2013/3/12/signee-breakdown-jalen-ramsey","Florida State Athletics — Signee Breakdown: Jalen Ramsey"],
  ["https://seminoles.com/sports/football/roster/jalen-ramsey/809","Florida State Athletics — Jalen Ramsey roster"],
  ["https://www.specialolympics.org/about/ambassadors/jamaal-charles","Special Olympics — Jamaal Charles ambassador profile"],
  ["https://alcalde.texasexes.org/2016/05/jamaal","The Alcalde — Jamaal"],
  ["https://texaslonghorns.com/news/2005/2/2/020205aac_656","Texas Athletics — 2005 signing class"],
  ["https://tshof.org/inductee/jamaal-charles/","Texas Sports Hall of Fame — Jamaal Charles"],
  ["https://lsusports.net/sports/fb/roster/season/2014/player/jamal-adams","LSU Athletics — Jamal Adams roster"],
  ["https://www.raiders.com/news/jamal-adams-facts-get-to-know-nfl-transactions-raiders-training-camp","Las Vegas Raiders — Jamal Adams facts"],
  ["https://ohiostatebuckeyes.com/news/2006/11/18/under-the-helmet-37","Ohio State Athletics — Under the Helmet"],
  ["https://ohiostatebuckeyes.com/news/2005/2/2/eighteen-student-athletes-sign-to-play-football-at-ohio-state","Ohio State Athletics — 2005 signing class"],
  ["https://ohiostatebuckeyes.com/news/2008/3/27/spring-football-player-profile-james-laurinaitis","Ohio State Athletics — Spring Football Player Profile"],
  ["https://fightingirish.com/news/2014/09/11/coming-of-age","Notre Dame Athletics — Coming of Age"],
  ["https://fightingirish.com/sports/football/roster/player/jaylon-smith","Notre Dame Athletics — Jaylon Smith roster"],
  ["https://ohiostatebuckeyes.com/sports/football/roster/jeff-okudah/449","Ohio State Athletics — Jeff Okudah roster"],
  ["https://ohiostatebuckeyes.com/news/2020/1/3/jeff-okudah-departs-dbu-as-an-all-time-top-cb","Ohio State Athletics — Jeff Okudah Departs DBU"],
  ["https://miamihurricanes.com/sports/football/roster/season/2001-02/player/jeremy-shockey/","Miami Athletics — Jeremy Shockey roster"],
  ["https://soonersports.com/news/2006/8/21/208392693","Oklahoma Athletics — Freshman Tight End Jermaine Gresham"],
  ["https://fightingirish.com/sports/football/roster/player/joe-alt","Notre Dame Athletics — Joe Alt roster"],
  ["https://uwbadgers.com/sports/2015/8/21/GEN_20140101585","Wisconsin Athletics — Joe Thomas profile"],
  ["https://uwbadgers.com/news/2019/6/25/athletics-general-news-events-lucas-uw-athletic-hall-of-fame-2019-joe-thomas-football","Wisconsin Athletics — Hall of Fame feature"],
  ["https://ohiostatebuckeyes.com/news/2013/2/6/ohio-state-signs-24-to-national-letters-of-intent","Ohio State Athletics — 2013 signing class"],
  ["https://ohiostatebuckeyes.com/sports/football/roster/nick-bosa/7994","Ohio State Athletics — Nick Bosa roster"],
  ["https://ohiostatebuckeyes.com/news/2014/9/29/urban-meyer-press-conference-transcript-09-29-14","Ohio State Athletics — Urban Meyer press conference, Sept. 29, 2014"],
  ["https://utsports.com/sports/football/roster/john-henderson/14190","Tennessee Athletics — John Henderson roster"],
  ["https://utsports.com/news/2012/5/25/Vols_Jersey_Countdown_98","Tennessee Athletics — Vols Jersey Countdown: 98"],
  ["https://www.army.mil/article/258443/nfl_football_star_spends_time_with_kids_at_fort_lee_procamp","U.S. Army — Jonathan Allen youth camp feature"],
  ["https://www.washingtonpost.com/sports/colleges/from-foster-care-to-first-round-alabamas-jonathan-allen-plows-forward/2016/12/22/9f61c5d4-c84f-11e6-bf4b-2c064d32a4bf_story.html","The Washington Post — From foster care to first round"],
  ["https://rolltide.com/sports/football/roster/jonathan-allen/3077","Alabama Athletics — Jonathan Allen roster"],
  ["https://texaslonghorns.com/news/2008/10/11/101108aaa_21","Texas Athletics — Texas vs. Oklahoma feature"],
  ["https://texaslonghorns.com/news/2006/11/16/111606aab_105.aspx","Texas Athletics — Jordan Shipley Q&A"],
  ["https://goheels.com/sports/football/roster/julius-peppers/5459","North Carolina Athletics — Julius Peppers football roster"],
  ["https://goheels.com/news/2000/1/22/205462922","North Carolina Athletics — Peppers joins basketball"],
  ["https://goducks.com/sports/football/roster/kayvon-thibodeaux/10601","Oregon Athletics — Kayvon Thibodeaux roster"],
  ["https://goducks.com/news/2019/2/5/football-nsd19","Oregon Athletics — Oregon Adds To Consensus Top 10 Class"],
  ["https://www.latimes.com/sports/newsletter/2021-08-02/high-school-football-prep-rally","Los Angeles Times — Prep Rally interview"],
  ["https://footballfoundation.org/hof_search.aspx?hof=2065","National Football Foundation — Keith Jackson Hall of Fame profile"],
  ["https://soonersports.com/sports/2025/2/26/black-history-month-spotlight","Oklahoma Athletics — Black History Month Spotlight"],
  ["https://www.cfbhall.com/inductees/keith-jackson-2001/","College Football Hall of Fame — Keith Jackson"],
  ["https://miamihurricanes.com/sports/football/roster/season/2001-02/player/kellen-winslow","Miami Athletics — Kellen Winslow roster"],
  ["https://www.sportingnews.com/us/nfl/news/khalil-mack-college-video-game-rating/1tp13tlo204d115tf2mhhlqkb2","Sporting News — Khalil Mack college backstory"],
  ["https://chicago.suntimes.com/2018/10/31/18480992/the-mack-effect-before-he-was-a-bear-olb-khalil-mack-transformed-buffalo","Chicago Sun-Times — Before he was a Bear, Mack transformed Buffalo"],
  ["https://www.si.com/nfl/2014/04/25/2014-nfl-draft-top-64-khalil-mack","Sports Illustrated — 2014 NFL Draft Top 64: Khalil Mack"],
  ["https://www.si.com/college/2013/11/19/khalil-mack-buffalo-bulls","Sports Illustrated — Khalil Mack and Buffalo"],
  ["https://www.ravenspr.com/player_bios/kyle_hamilton.pdf","Baltimore Ravens — Kyle Hamilton media guide bio"],
  ["https://fightingirish.com/sports/football/roster/season/2020-21/player/kyle-hamilton","Notre Dame Athletics — Kyle Hamilton roster"],
  ["https://nsd.floridagators.com/bio/15","Florida Athletics — Kyle Pitts signing bio"],
  ["https://floridagators.com/news/2020/10/2/football-gators-tight-end-kyle-pitts-feature-story","Florida Athletics — Pitts Well-Equipped for Big Stage"],
  ["https://floridagators.com/news/2020/9/7/football-the-kyle-konnection-trask-and-pitts","Florida Athletics — The Kyle Konnection: Trask and Pitts"],
  ["https://www.profootballhof.com/news/2025/03/gold-jacket-spotlight-ladainian-tomlinson-runs-idol%E2%80%99s-handoff-into-nfl-stardom/","Pro Football Hall of Fame — Gold Jacket Spotlight: LaDainian Tomlinson"],
  ["https://footballfoundation.org/honors/hall-of-fame/ladainian-tomlinson/2370","National Football Foundation — LaDainian Tomlinson Hall of Fame profile"],
  ["https://goducks.com/news/2023/12/5/football-james-hall-of-fame-induction-becomes-official-tuesday","Oregon Athletics — James Hall of Fame induction feature"],
  ["https://goducks.com/honors/hall-of-fame/lamichael-james/1253","Oregon Athletics — LaMichael James Hall of Fame"],
  ["https://georgiadogs.com/sports/football/roster/malaki-starks/8131","Georgia Athletics — Malaki Starks roster"],
  ["https://georgiadogs.com/news/2023/9/19/football-quick-chat-malaki-starks","Georgia Athletics — Quick Chat: Malaki Starks"],
  ["https://ohiostatebuckeyes.com/news/2007/5/3/ohio-state-hosts-jesse-owens-classic","Ohio State Athletics — Jesse Owens Classic"],
  ["https://usctrojans.com/sports/track-and-field/roster/marqise-lee/3998","USC Athletics — Marqise Lee track roster"],
  ["https://usctrojans.com/sports/2017/6/15/blog-2011-08-meet-marqise-lee-html.aspx","USC Athletics — Meet Marqise Lee"],
  ["https://www.espn.com/college-football/story/_/id/38703026/marvin-harrison-jr-ohio-state-draft-penn-state","ESPN — Marvin Harrison Jr. profile"],
  ["https://www.foxsports.com/stories/college-football/kyle-mccord-and-marvin-harrison-jrs-long-intertwined-paths-to-the-game","FOX Sports — McCord and Harrison's intertwined paths"],
  ["https://www.phillyvoice.com/marvin-harrison-jr-wide-receiver-prospect-ohio-state-rose-bowl-st-josephs-prep-philadelphia/","PhillyVoice — Marvin Harrison Jr. at Ohio State"],
  ["https://gopsusports.com/sports/football/roster/season/2018/player/micah-parsons","Penn State Athletics — Micah Parsons roster"],
  ["https://gopsusports.com/news/2017/12/20/franklin-and-fb-inks-top-5-class","Penn State Athletics — 2017 signing class"],
  ["https://gopsusports.com/news/2019/07/22/brown-and-parsons-on-butkus-preseason-watch-list","Penn State Athletics — Brown and Parsons on Butkus Preseason Watch List"],
  ["https://texaslonghorns.com/news/2004/12/30/123004aaa_665","Texas Athletics — Family ties add intrigue to Rose Bowl"],
  ["https://texaslonghorns.com/news/2015/9/24/FB_0924152019","Texas Athletics — Michael Huff Hall of Honor profile"],
  ["https://texaslonghorns.com/news/2005/8/30/083005aab_128","Texas Athletics — Mind over matter"],
  ["https://12thman.com/sports/football/roster/season/2012/player/mike-evans","Texas A&M Athletics — Mike Evans roster"],
  ["https://12thman.com/news/2013/09/04/the-rock-from-the-island","Texas A&M Athletics — The Rock from the Island"],
  ["https://lsusports.net/sports/fb/roster/season/2010/player/morris-claiborne","LSU Athletics — Morris Claiborne roster"],
  ["https://georgiadogs.com/sports/football/roster/nakobe-dean/5425","Georgia Athletics — Nakobe Dean roster"],
  ["https://georgiadogs.com/news/2023/4/28/football-dean-still-pursuing-mechanical-engineering-degree","Georgia Athletics — Dean Still Pursuing Mechanical Engineering Degree"],
  ["https://olemisssports.com/news/2021/4/12/football-ole-miss-nfl-legend-patrick-willis-to-deliver-commencement-address.aspx","Ole Miss Athletics — Patrick Willis commencement announcement"],
  ["https://olemisssports.com/news/2003/2/5/2003_Ole_Miss_Signing_Day_Press_Conference_Transcript","Ole Miss Athletics — 2003 Signing Day transcript"],
  ["https://wpial.org/hof.aspx?hof=61","WPIAL Hall of Fame — Paul Posluszny"],
  ["https://collegesportscommunicators.com/news/2006/11/30/GEN_1354.aspx?path=general","College Sports Communicators — Academic All-America announcement"],
  ["https://footballfoundation.org/honors/hall-of-fame/paul-posluszny/2538","National Football Foundation — Paul Posluszny Hall of Fame profile"],
  ["https://gopsusports.com/news/2006/12/10/posluszny-named-mvp-at-nittany-lion-football-banquet","Penn State Athletics — Football Banquet"],
  ["https://seminoles.com/honors/florida-state-athletics-hall-of-fame/peter-warrick/124","Florida State Athletics — Peter Warrick Hall of Fame"],
  ["https://allstatesugarbowl.org/sports/2023/11/28/peter-warrick.aspx","Sugar Bowl — Peter Warrick Hall of Fame"],
  ["https://seminoles.com/news/2026/8/18/football-hall-of-fame-on-campus-salute-for-peter-warrick-set-for-october-31","Florida State Athletics — Hall of Fame On-Campus Salute"],
  ["https://allstatesugarbowl.org/news/2026/1/22/cfb-hall-of-fame.aspx","Sugar Bowl — Three Sugar Bowl Alums Headed to College Football Hall of Fame"],
  ["https://rolltide.com/news/2008/1/8/Rolando_McClain_Named_Freshman_All_American","Alabama Athletics — Rolando McClain Freshman All-America"],
  ["https://www.maxpreps.com/al/decatur/decatur-red-raiders/athletes/rolando-mcclain/bio/?careerid=a03uvbn8dor33","MaxPreps — Rolando McClain basketball bio"],
  ["https://soonersports.com/news/2007/2/7/208402679","Oklahoma Athletics — 2007 signing class"],
  ["https://soonersports.com/news/2011/1/6/208390240","Oklahoma Athletics — Ryan Broyles to Return"],
  ["https://clemsontigers.com/sports/football/roster/player/sammy-watkins","Clemson Athletics — Sammy Watkins roster"],
  ["https://www.patriots.com/team/players-roster/a-j-brown/logs/2024/pre/","New England Patriots player biography"],
  ["https://olemisssports.com/sports/football/roster/a-j-brown/270","Ole Miss Athletics player biography"],
  ["https://www.si.com/college/2016/02/03/aj-brown-myers-commits-ole-miss","Sports Illustrated commitment report"],
  ["https://ohiostatebuckeyes.com/news/2005/9/10/no-time-to-wait","Ohio State Athletics profile, “No Time To Wait”"],
  ["https://www.nhregister.com/news/article/Connections-run-deep-for-Ohio-St-duo-11654413.php","New Haven Register / Associated Press feature"],
  ["https://www.espn.com/college-football/story/_/id/14458113/a-lot-changed-ohio-state-buckeyes-notre-dame-fighting-irish-last-met-fiesta-bowl","ESPN Fiesta Bowl retrospective"],
  ["https://texaslonghorns.com/news/2002/2/6/020602aaa_208","Texas Athletics 2002 recruiting biography"],
  ["https://texaslonghorns.com/news/2005/10/5/100505aab_420.aspx","Texas Athletics feature, “Take it to the house”"],
  ["https://texaslonghorns.com/news/2012/3/30/033112aab_522","Texas Athletics spring-game feature"],
  ["https://www.inquirer.com/college-sports/penn-state/penn-state-abdul-carter-football-cfp-lasalle-glenside-north-philly-20241219.html","Philadelphia Inquirer profile"],
  ["https://gopsusports.com/sports/football/roster/season/2023/player/abdul-carter","Penn State Athletics player biography"],
  ["https://gopsusports.com/news/2024/12/18/carter-warren-selected-sporting-news-all-americans","Penn State Athletics All-America release"],
  ["https://mgoblue.com/sports/football/roster/aidan-hutchinson/22005","Michigan Athletics player biography"],
  ["https://www.detroitlions.com/team/players-roster/aidan-hutchinson/logs/","Detroit Lions player biography"],
  ["https://calbears.com/sports/football/roster/coaches/alex-mack/194","California Athletics Alex Mack biography"],
  ["https://footballfoundation.org/sports/football/roster/alex-mack/573","National Football Foundation Campbell Trophy biography"],
  ["https://static.clubs.nfl.com/image/upload/bills/m8gerv5jb7nkovxkwmb6","Buffalo Bills player biography"],
  ["https://static.clubs.nfl.com/image/upload/raiders/re0vrphviaskzjcnphx1.pdf","Oakland Raiders feature-clips compilation of Bay Area News Group profile"],
  ["https://www.espn.com/blog/sec/post/_/id/96041/amari-cooper-paved-his-own-way-to-alabama","ESPN SEC profile on Cooper’s path to Alabama"],
  ["https://www.umsportshalloffame.com/andre-johnson.html","University of Miami Sports Hall of Fame biography"],
  ["https://miamihurricanes.com/news/2002/05/05/205547137-2/","Miami Athletics 100-meter title release"],
  ["https://miamihurricanes.com/news/2024/02/08/hester-johnson-named-to-pro-football-hall-of-fame/","Miami Athletics Pro Football Hall of Fame release"],
  ["https://miamihurricanes.com/sports/football/roster/season/2001-02/player/andre-johnson/","Miami Hurricanes player biography"],
  // PR9_SOURCE_INSERT
] as const;

export const footballPersonIdentityCfbBResearch = [
  // PR9_RECORD_INSERT
] as const;
