export const LONGHORNS_PLAYER_SUMMARIES = {
  "Vince Young": "QB • 2005 National Champion • Maxwell Award",
  "Colt McCoy": "QB • 2009 Big 12 Champion • Maxwell Award",
  "Sam Ehlinger": "QB • 2018 Sugar Bowl Champion • Four-year starter",
  "Quinn Ewers": "QB • 2023 Big 12 Champion • Two CFP appearances",
  "Shane Buechele": "QB • 19 Texas starts • 4,636 passing yards",
  "David Ash": "QB • 15–7 as starter • 4,728 passing yards",
  "Jamaal Charles": "RB • 2005 National Champion • 3,328 rushing yards",
  "Bijan Robinson": "RB • 2022 Doak Walker winner • Unanimous All-American",
  "D'Onta Foreman": "RB • 2016 Doak Walker winner • 2,028 rushing yards",
  "Jonathon Brooks": "RB • 1,139 rushing yards in 2023 • Doak Walker semifinalist",
  "Roschon Johnson": "RB • QB-to-RB convert • 2,190 career rushing yards",
  "Tre Wisner": "RB • 1,000-yard rusher in 2024 • CFP semifinalist",
  "Jordan Shipley": "WR • 2009 Consensus All-American • 3,191 receiving yards",
  "Quan Cosby": "WR • 2008 Biletnikoff semifinalist • 1,123 receiving yards",
  "Limas Sweed": "WR • 2005 National Champion • First-team All-Big 12",
  "Marquise Goodwin": "WR • 2012 U.S. Olympian • Two-time NCAA long jump champion",
  "Mike Davis": "WR • 2,753 career receiving yards • 18 receiving TD",
  "Devin Duvernay": "WR • 2019 first-team All-Big 12 • 106 catches",
  "Lil'Jordan Humphrey": "WR • 1,176 receiving yards in 2018 • Sugar Bowl Champion",
  "Xavier Worthy": "WR • 2,755 career receiving yards • 26 receiving TD",
  "Adonai Mitchell": "WR • 2023 Big 12 Offensive Newcomer • 11 receiving TD",
  "Ja'Tavion Sanders": "TE • Texas career TE receptions leader • Two-time first-team All-Big 12",
  "Gunnar Helm": "TE • 2024 Mackey Award semifinalist • 54 career games",
  "Matthew Golden": "WR • Started all 16 games in 2024 • CFP semifinalist",
  "Justin Blalock": "OL • 2006 unanimous All-American • Big 12 OL of the Year",
  "Kasey Studdard": "OL • 2005 National Champion • All-Big 12",
  "Tony Hills": "OL • 2006 All-America honorable mention • All-Big 12",
  "Connor Williams": "OL • 2016 consensus All-American • Freshman All-American",
  "Sam Cosmi": "OL • 2020 unanimous first-team All-Big 12",
  "Kelvin Banks Jr.": "OL • 2024 Outland + Lombardi winner • Unanimous All-American",
  "Jake Majors": "OL • Texas-record 56 career starts • Campbell Trophy finalist",
  "Brian Orakpo": "EDGE • 2008 Nagurski + Lombardi + Hendricks winner",
  "Sergio Kindle": "EDGE • 2009 first-team All-American • 22 tackles for loss",
  "Lamarr Houston": "DL • 2009 first-team All-Big 12 • 22 tackles for loss",
  "Sam Acho": "EDGE • 2010 Campbell + Wuerffel winner • All-American",
  "Alex Okafor": "EDGE • 2011 All-American • 2012 Alamo Bowl Defensive MVP",
  "Jackson Jeffcoat": "EDGE • 2013 Hendricks winner • Big 12 Defensive Player of the Year",
  "Malcom Brown": "DL • 2014 consensus All-American • Nagurski finalist",
  "Poona Ford": "DL • 2017 Big 12 Defensive Lineman of the Year • Team captain",
  "Charles Omenihu": "EDGE • 2018 Big 12 Defensive Lineman of the Year • 9.5 sacks",
  "Joseph Ossai": "EDGE • 2020 first-team All-Big 12 • 15.5 tackles for loss",
  "T'Vondre Sweat": "DL • 2023 Outland winner • Big 12 Defensive Player of the Year",
  "Byron Murphy II": "DL • 2023 Big 12 Defensive Lineman of the Year • All-American",
  "Alfred Collins": "DL • 63 career games • 26 starts",
  "Roddrick Muckelroy": "LB • Two-time All-Big 12 • 291 career tackles",
  "Emmanuel Acho": "LB • Four-year Longhorn • Academic All-American",
  "Jordan Hicks": "LB • 2014 second-team All-American • 147 tackles",
  "Malik Jefferson": "LB • 2017 Big 12 Co-Defensive Player of the Year • 110 tackles",
  "Gary Johnson": "LB • 2018 second-team All-Big 12 • 74 tackles",
  "Jaylan Ford": "LB • 2022 AP third-team All-American • 119 tackles",
  "Anthony Hill Jr.": "LB • 2023 Freshman All-American • 2025 All-American",
  "Michael Huff": "DB • 2005 Thorpe Award • National Champion",
  "Aaron Ross": "DB • 2006 Thorpe Award • First-team All-American",
  "Michael Griffin": "DB • 2005 National Champion • 2006 All-American",
  "Earl Thomas": "DB • 2009 consensus All-American • Big 12 Champion",
  "Quandre Diggs": "DB • 2011 Big 12 Defensive Freshman of the Year • Freshman All-American",
  "Kenny Vaccaro": "DB • 2012 first-team All-American • Team captain",
  "DeShon Elliott": "DB • 2017 unanimous All-American • Thorpe finalist",
  "Brandon Jones": "DB • 2019 second-team All-Big 12 • Team captain",
  "Caden Sterns": "DB • 2018 Big 12 Defensive Freshman of the Year • First-team All-Big 12",
  "Jahdae Barron": "DB • 2024 Thorpe Award • Consensus All-American",
  "Justin Tucker": "K • 2011 All-Big 12 • Texas A&M game-winning field goal",
  "Michael Dickson": "P • 2017 Ray Guy Award • Unanimous All-American",
  "Cameron Dicker": "K • 2018 Red River game-winning field goal • All-Big 12",
  "Derrick Johnson": "LB • 2004 Butkus + Nagurski winner • Unanimous All-American",
  "Cedric Benson": "RB • 2004 Doak Walker winner • 5,540 career rushing yards",
  "Roy Williams": "WR • Three-time first-team All-Big 12 • 3,866 receiving yards",
  "Nathan Vasher": "DB • 2003 All-American • Texas-record 17 career interceptions",
  "Marcus Tubbs": "DL • 2003 first-team All-Big 12 • 74 tackles",
  "Bo Scaife": "TE • 2004 first-team All-Big 12 • 75 career catches",
} as const;

export type LonghornsPlayerName = keyof typeof LONGHORNS_PLAYER_SUMMARIES;

export function longhornsPlayerSummary(displayLabel: string | null | undefined) {
  if (!displayLabel) return "";
  return LONGHORNS_PLAYER_SUMMARIES[displayLabel as LonghornsPlayerName] ?? "";
}
