export interface NflDivisionTeamSeasonPresentation {
  season: number;
  teamCode: string;
  teamName: string;
  divisionLabel: string;
  summary: string;
}

/**
 * Presentation metadata for the server-owned NFL Divisions Draft population.
 * Records and postseason accomplishments are derived from the repository's
 * pinned nflverse 1999-2025 team-season results corpus. Division labels use
 * each franchise's current NFL alignment because division identity is the
 * game-layer grouping.
 */
export const NFL_DIVISION_TEAM_SEASONS = {
  "nfl-division-buf-2024": { season: 2024, teamCode: "BUF", teamName: "Buffalo Bills", divisionLabel: "AFC East", summary: "13-4 · AFC Championship Game" },
  "nfl-division-buf-2022": { season: 2022, teamCode: "BUF", teamName: "Buffalo Bills", divisionLabel: "AFC East", summary: "13-3 · Playoff Win" },
  "nfl-division-buf-2021": { season: 2021, teamCode: "BUF", teamName: "Buffalo Bills", divisionLabel: "AFC East", summary: "11-6 · Playoff Win" },
  "nfl-division-buf-2020": { season: 2020, teamCode: "BUF", teamName: "Buffalo Bills", divisionLabel: "AFC East", summary: "13-3 · AFC Championship Game" },
  "nfl-division-mia-2023": { season: 2023, teamCode: "MIA", teamName: "Miami Dolphins", divisionLabel: "AFC East", summary: "11-6 · Playoff Team" },
  "nfl-division-mia-2008": { season: 2008, teamCode: "MIA", teamName: "Miami Dolphins", divisionLabel: "AFC East", summary: "11-5 · Playoff Team" },
  "nfl-division-mia-2001": { season: 2001, teamCode: "MIA", teamName: "Miami Dolphins", divisionLabel: "AFC East", summary: "11-5 · Playoff Team" },
  "nfl-division-mia-2000": { season: 2000, teamCode: "MIA", teamName: "Miami Dolphins", divisionLabel: "AFC East", summary: "11-5 · Playoff Win" },
  "nfl-division-ne-2016": { season: 2016, teamCode: "NE", teamName: "New England Patriots", divisionLabel: "AFC East", summary: "14-2 · Super Bowl Champion" },
  "nfl-division-ne-2007": { season: 2007, teamCode: "NE", teamName: "New England Patriots", divisionLabel: "AFC East", summary: "16-0 · AFC Champion" },
  "nfl-division-ne-2004": { season: 2004, teamCode: "NE", teamName: "New England Patriots", divisionLabel: "AFC East", summary: "14-2 · Super Bowl Champion" },
  "nfl-division-ne-2003": { season: 2003, teamCode: "NE", teamName: "New England Patriots", divisionLabel: "AFC East", summary: "14-2 · Super Bowl Champion" },
  "nfl-division-nyj-2015": { season: 2015, teamCode: "NYJ", teamName: "New York Jets", divisionLabel: "AFC East", summary: "10-6 · Winning Season" },
  "nfl-division-nyj-2010": { season: 2010, teamCode: "NYJ", teamName: "New York Jets", divisionLabel: "AFC East", summary: "11-5 · AFC Championship Game" },
  "nfl-division-nyj-2009": { season: 2009, teamCode: "NYJ", teamName: "New York Jets", divisionLabel: "AFC East", summary: "9-7 · AFC Championship Game" },
  "nfl-division-nyj-2004": { season: 2004, teamCode: "NYJ", teamName: "New York Jets", divisionLabel: "AFC East", summary: "10-6 · Playoff Win" },
  "nfl-division-bal-2023": { season: 2023, teamCode: "BAL", teamName: "Baltimore Ravens", divisionLabel: "AFC North", summary: "13-4 · AFC Championship Game" },
  "nfl-division-bal-2019": { season: 2019, teamCode: "BAL", teamName: "Baltimore Ravens", divisionLabel: "AFC North", summary: "14-2 · AFC North Champion" },
  "nfl-division-bal-2012": { season: 2012, teamCode: "BAL", teamName: "Baltimore Ravens", divisionLabel: "AFC North", summary: "10-6 · Super Bowl Champion" },
  "nfl-division-bal-2000": { season: 2000, teamCode: "BAL", teamName: "Baltimore Ravens", divisionLabel: "AFC North", summary: "12-4 · Super Bowl Champion" },
  "nfl-division-cin-2022": { season: 2022, teamCode: "CIN", teamName: "Cincinnati Bengals", divisionLabel: "AFC North", summary: "12-4 · AFC Championship Game" },
  "nfl-division-cin-2021": { season: 2021, teamCode: "CIN", teamName: "Cincinnati Bengals", divisionLabel: "AFC North", summary: "10-7 · AFC Champion" },
  "nfl-division-cin-2015": { season: 2015, teamCode: "CIN", teamName: "Cincinnati Bengals", divisionLabel: "AFC North", summary: "12-4 · AFC North Champion" },
  "nfl-division-cin-2013": { season: 2013, teamCode: "CIN", teamName: "Cincinnati Bengals", divisionLabel: "AFC North", summary: "11-5 · AFC North Champion" },
  "nfl-division-cle-2023": { season: 2023, teamCode: "CLE", teamName: "Cleveland Browns", divisionLabel: "AFC North", summary: "11-6 · Playoff Team" },
  "nfl-division-cle-2020": { season: 2020, teamCode: "CLE", teamName: "Cleveland Browns", divisionLabel: "AFC North", summary: "11-5 · Playoff Win" },
  "nfl-division-cle-2007": { season: 2007, teamCode: "CLE", teamName: "Cleveland Browns", divisionLabel: "AFC North", summary: "10-6 · Winning Season" },
  "nfl-division-cle-2002": { season: 2002, teamCode: "CLE", teamName: "Cleveland Browns", divisionLabel: "AFC North", summary: "9-7 · Playoff Team" },
  "nfl-division-pit-2010": { season: 2010, teamCode: "PIT", teamName: "Pittsburgh Steelers", divisionLabel: "AFC North", summary: "12-4 · AFC Champion" },
  "nfl-division-pit-2008": { season: 2008, teamCode: "PIT", teamName: "Pittsburgh Steelers", divisionLabel: "AFC North", summary: "12-4 · Super Bowl Champion" },
  "nfl-division-pit-2005": { season: 2005, teamCode: "PIT", teamName: "Pittsburgh Steelers", divisionLabel: "AFC North", summary: "11-5 · Super Bowl Champion" },
  "nfl-division-pit-2004": { season: 2004, teamCode: "PIT", teamName: "Pittsburgh Steelers", divisionLabel: "AFC North", summary: "15-1 · AFC Championship Game" },
  "nfl-division-hou-2025": { season: 2025, teamCode: "HOU", teamName: "Houston Texans", divisionLabel: "AFC South", summary: "12-5 · Playoff Win" },
  "nfl-division-hou-2018": { season: 2018, teamCode: "HOU", teamName: "Houston Texans", divisionLabel: "AFC South", summary: "11-5 · AFC South Champion" },
  "nfl-division-hou-2012": { season: 2012, teamCode: "HOU", teamName: "Houston Texans", divisionLabel: "AFC South", summary: "12-4 · Playoff Win" },
  "nfl-division-hou-2011": { season: 2011, teamCode: "HOU", teamName: "Houston Texans", divisionLabel: "AFC South", summary: "10-6 · Playoff Win" },
  "nfl-division-ind-2009": { season: 2009, teamCode: "IND", teamName: "Indianapolis Colts", divisionLabel: "AFC South", summary: "14-2 · AFC Champion" },
  "nfl-division-ind-2006": { season: 2006, teamCode: "IND", teamName: "Indianapolis Colts", divisionLabel: "AFC South", summary: "12-4 · Super Bowl Champion" },
  "nfl-division-ind-2005": { season: 2005, teamCode: "IND", teamName: "Indianapolis Colts", divisionLabel: "AFC South", summary: "14-2 · AFC South Champion" },
  "nfl-division-ind-2003": { season: 2003, teamCode: "IND", teamName: "Indianapolis Colts", divisionLabel: "AFC South", summary: "12-4 · AFC Championship Game" },
  "nfl-division-jax-2025": { season: 2025, teamCode: "JAX", teamName: "Jacksonville Jaguars", divisionLabel: "AFC South", summary: "13-4 · AFC South Champion" },
  "nfl-division-jax-2017": { season: 2017, teamCode: "JAX", teamName: "Jacksonville Jaguars", divisionLabel: "AFC South", summary: "10-6 · AFC Championship Game" },
  "nfl-division-jax-2007": { season: 2007, teamCode: "JAX", teamName: "Jacksonville Jaguars", divisionLabel: "AFC South", summary: "11-5 · Playoff Win" },
  "nfl-division-jax-1999": { season: 1999, teamCode: "JAX", teamName: "Jacksonville Jaguars", divisionLabel: "AFC South", summary: "14-2 · AFC Championship Game" },
  "nfl-division-ten-2008": { season: 2008, teamCode: "TEN", teamName: "Tennessee Titans", divisionLabel: "AFC South", summary: "13-3 · AFC South Champion" },
  "nfl-division-ten-2003": { season: 2003, teamCode: "TEN", teamName: "Tennessee Titans", divisionLabel: "AFC South", summary: "12-4 · Playoff Win" },
  "nfl-division-ten-2000": { season: 2000, teamCode: "TEN", teamName: "Tennessee Titans", divisionLabel: "AFC South", summary: "13-3 · Playoff Team" },
  "nfl-division-ten-1999": { season: 1999, teamCode: "TEN", teamName: "Tennessee Titans", divisionLabel: "AFC South", summary: "13-3 · AFC Champion" },
  "nfl-division-den-2025": { season: 2025, teamCode: "DEN", teamName: "Denver Broncos", divisionLabel: "AFC West", summary: "14-3 · AFC Championship Game" },
  "nfl-division-den-2015": { season: 2015, teamCode: "DEN", teamName: "Denver Broncos", divisionLabel: "AFC West", summary: "12-4 · Super Bowl Champion" },
  "nfl-division-den-2013": { season: 2013, teamCode: "DEN", teamName: "Denver Broncos", divisionLabel: "AFC West", summary: "13-3 · AFC Champion" },
  "nfl-division-den-2005": { season: 2005, teamCode: "DEN", teamName: "Denver Broncos", divisionLabel: "AFC West", summary: "13-3 · AFC Championship Game" },
  "nfl-division-kc-2023": { season: 2023, teamCode: "KC", teamName: "Kansas City Chiefs", divisionLabel: "AFC West", summary: "11-6 · Super Bowl Champion" },
  "nfl-division-kc-2022": { season: 2022, teamCode: "KC", teamName: "Kansas City Chiefs", divisionLabel: "AFC West", summary: "14-3 · Super Bowl Champion" },
  "nfl-division-kc-2020": { season: 2020, teamCode: "KC", teamName: "Kansas City Chiefs", divisionLabel: "AFC West", summary: "14-2 · AFC Champion" },
  "nfl-division-kc-2019": { season: 2019, teamCode: "KC", teamName: "Kansas City Chiefs", divisionLabel: "AFC West", summary: "12-4 · Super Bowl Champion" },
  "nfl-division-lac-2009": { season: 2009, teamCode: "LAC", teamName: "San Diego Chargers", divisionLabel: "AFC West", summary: "13-3 · AFC West Champion" },
  "nfl-division-lac-2007": { season: 2007, teamCode: "LAC", teamName: "San Diego Chargers", divisionLabel: "AFC West", summary: "11-5 · AFC Championship Game" },
  "nfl-division-lac-2006": { season: 2006, teamCode: "LAC", teamName: "San Diego Chargers", divisionLabel: "AFC West", summary: "14-2 · AFC West Champion" },
  "nfl-division-lac-2004": { season: 2004, teamCode: "LAC", teamName: "San Diego Chargers", divisionLabel: "AFC West", summary: "12-4 · AFC West Champion" },
  "nfl-division-lv-2016": { season: 2016, teamCode: "LV", teamName: "Oakland Raiders", divisionLabel: "AFC West", summary: "12-4 · Playoff Team" },
  "nfl-division-lv-2002": { season: 2002, teamCode: "LV", teamName: "Oakland Raiders", divisionLabel: "AFC West", summary: "11-5 · AFC Champion" },
  "nfl-division-lv-2001": { season: 2001, teamCode: "LV", teamName: "Oakland Raiders", divisionLabel: "AFC West", summary: "10-6 · Playoff Win" },
  "nfl-division-lv-2000": { season: 2000, teamCode: "LV", teamName: "Oakland Raiders", divisionLabel: "AFC West", summary: "12-4 · AFC Championship Game" },
  "nfl-division-dal-2023": { season: 2023, teamCode: "DAL", teamName: "Dallas Cowboys", divisionLabel: "NFC East", summary: "12-5 · NFC East Champion" },
  "nfl-division-dal-2016": { season: 2016, teamCode: "DAL", teamName: "Dallas Cowboys", divisionLabel: "NFC East", summary: "13-3 · NFC East Champion" },
  "nfl-division-dal-2014": { season: 2014, teamCode: "DAL", teamName: "Dallas Cowboys", divisionLabel: "NFC East", summary: "12-4 · Playoff Win" },
  "nfl-division-dal-2007": { season: 2007, teamCode: "DAL", teamName: "Dallas Cowboys", divisionLabel: "NFC East", summary: "13-3 · NFC East Champion" },
  "nfl-division-nyg-2011": { season: 2011, teamCode: "NYG", teamName: "New York Giants", divisionLabel: "NFC East", summary: "9-7 · Super Bowl Champion" },
  "nfl-division-nyg-2008": { season: 2008, teamCode: "NYG", teamName: "New York Giants", divisionLabel: "NFC East", summary: "12-4 · NFC East Champion" },
  "nfl-division-nyg-2007": { season: 2007, teamCode: "NYG", teamName: "New York Giants", divisionLabel: "NFC East", summary: "10-6 · Super Bowl Champion" },
  "nfl-division-nyg-2000": { season: 2000, teamCode: "NYG", teamName: "New York Giants", divisionLabel: "NFC East", summary: "12-4 · NFC Champion" },
  "nfl-division-phi-2024": { season: 2024, teamCode: "PHI", teamName: "Philadelphia Eagles", divisionLabel: "NFC East", summary: "14-3 · Super Bowl Champion" },
  "nfl-division-phi-2022": { season: 2022, teamCode: "PHI", teamName: "Philadelphia Eagles", divisionLabel: "NFC East", summary: "14-3 · NFC Champion" },
  "nfl-division-phi-2017": { season: 2017, teamCode: "PHI", teamName: "Philadelphia Eagles", divisionLabel: "NFC East", summary: "13-3 · Super Bowl Champion" },
  "nfl-division-phi-2004": { season: 2004, teamCode: "PHI", teamName: "Philadelphia Eagles", divisionLabel: "NFC East", summary: "13-3 · NFC Champion" },
  "nfl-division-was-2024": { season: 2024, teamCode: "WAS", teamName: "Washington Commanders", divisionLabel: "NFC East", summary: "12-5 · NFC Championship Game" },
  "nfl-division-was-2012": { season: 2012, teamCode: "WAS", teamName: "Washington Redskins", divisionLabel: "NFC East", summary: "10-6 · NFC East Champion" },
  "nfl-division-was-2005": { season: 2005, teamCode: "WAS", teamName: "Washington Redskins", divisionLabel: "NFC East", summary: "10-6 · Playoff Win" },
  "nfl-division-was-1999": { season: 1999, teamCode: "WAS", teamName: "Washington Redskins", divisionLabel: "NFC East", summary: "10-6 · Playoff Win" },
  "nfl-division-chi-2018": { season: 2018, teamCode: "CHI", teamName: "Chicago Bears", divisionLabel: "NFC North", summary: "12-4 · NFC North Champion" },
  "nfl-division-chi-2010": { season: 2010, teamCode: "CHI", teamName: "Chicago Bears", divisionLabel: "NFC North", summary: "11-5 · NFC Championship Game" },
  "nfl-division-chi-2006": { season: 2006, teamCode: "CHI", teamName: "Chicago Bears", divisionLabel: "NFC North", summary: "13-3 · NFC Champion" },
  "nfl-division-chi-2001": { season: 2001, teamCode: "CHI", teamName: "Chicago Bears", divisionLabel: "NFC North", summary: "13-3 · Playoff Team" },
  "nfl-division-det-2024": { season: 2024, teamCode: "DET", teamName: "Detroit Lions", divisionLabel: "NFC North", summary: "15-2 · NFC North Champion" },
  "nfl-division-det-2023": { season: 2023, teamCode: "DET", teamName: "Detroit Lions", divisionLabel: "NFC North", summary: "12-5 · NFC Championship Game" },
  "nfl-division-det-2014": { season: 2014, teamCode: "DET", teamName: "Detroit Lions", divisionLabel: "NFC North", summary: "11-5 · Playoff Team" },
  "nfl-division-det-2011": { season: 2011, teamCode: "DET", teamName: "Detroit Lions", divisionLabel: "NFC North", summary: "10-6 · Playoff Team" },
  "nfl-division-gb-2020": { season: 2020, teamCode: "GB", teamName: "Green Bay Packers", divisionLabel: "NFC North", summary: "13-3 · NFC Championship Game" },
  "nfl-division-gb-2011": { season: 2011, teamCode: "GB", teamName: "Green Bay Packers", divisionLabel: "NFC North", summary: "15-1 · NFC North Champion" },
  "nfl-division-gb-2010": { season: 2010, teamCode: "GB", teamName: "Green Bay Packers", divisionLabel: "NFC North", summary: "10-6 · Super Bowl Champion" },
  "nfl-division-gb-2007": { season: 2007, teamCode: "GB", teamName: "Green Bay Packers", divisionLabel: "NFC North", summary: "13-3 · NFC Championship Game" },
  "nfl-division-min-2024": { season: 2024, teamCode: "MIN", teamName: "Minnesota Vikings", divisionLabel: "NFC North", summary: "14-3 · Playoff Team" },
  "nfl-division-min-2017": { season: 2017, teamCode: "MIN", teamName: "Minnesota Vikings", divisionLabel: "NFC North", summary: "13-3 · NFC Championship Game" },
  "nfl-division-min-2009": { season: 2009, teamCode: "MIN", teamName: "Minnesota Vikings", divisionLabel: "NFC North", summary: "12-4 · NFC Championship Game" },
  "nfl-division-min-2000": { season: 2000, teamCode: "MIN", teamName: "Minnesota Vikings", divisionLabel: "NFC North", summary: "11-5 · NFC Championship Game" },
  "nfl-division-atl-2016": { season: 2016, teamCode: "ATL", teamName: "Atlanta Falcons", divisionLabel: "NFC South", summary: "11-5 · NFC Champion" },
  "nfl-division-atl-2012": { season: 2012, teamCode: "ATL", teamName: "Atlanta Falcons", divisionLabel: "NFC South", summary: "13-3 · NFC Championship Game" },
  "nfl-division-atl-2010": { season: 2010, teamCode: "ATL", teamName: "Atlanta Falcons", divisionLabel: "NFC South", summary: "13-3 · NFC South Champion" },
  "nfl-division-atl-2004": { season: 2004, teamCode: "ATL", teamName: "Atlanta Falcons", divisionLabel: "NFC South", summary: "11-5 · NFC Championship Game" },
  "nfl-division-car-2015": { season: 2015, teamCode: "CAR", teamName: "Carolina Panthers", divisionLabel: "NFC South", summary: "15-1 · NFC Champion" },
  "nfl-division-car-2013": { season: 2013, teamCode: "CAR", teamName: "Carolina Panthers", divisionLabel: "NFC South", summary: "12-4 · NFC South Champion" },
  "nfl-division-car-2005": { season: 2005, teamCode: "CAR", teamName: "Carolina Panthers", divisionLabel: "NFC South", summary: "11-5 · NFC Championship Game" },
  "nfl-division-car-2003": { season: 2003, teamCode: "CAR", teamName: "Carolina Panthers", divisionLabel: "NFC South", summary: "11-5 · NFC Champion" },
  "nfl-division-no-2020": { season: 2020, teamCode: "NO", teamName: "New Orleans Saints", divisionLabel: "NFC South", summary: "12-4 · Playoff Win" },
  "nfl-division-no-2018": { season: 2018, teamCode: "NO", teamName: "New Orleans Saints", divisionLabel: "NFC South", summary: "13-3 · NFC Championship Game" },
  "nfl-division-no-2011": { season: 2011, teamCode: "NO", teamName: "New Orleans Saints", divisionLabel: "NFC South", summary: "13-3 · Playoff Win" },
  "nfl-division-no-2009": { season: 2009, teamCode: "NO", teamName: "New Orleans Saints", divisionLabel: "NFC South", summary: "13-3 · Super Bowl Champion" },
  "nfl-division-tb-2021": { season: 2021, teamCode: "TB", teamName: "Tampa Bay Buccaneers", divisionLabel: "NFC South", summary: "13-4 · Playoff Win" },
  "nfl-division-tb-2020": { season: 2020, teamCode: "TB", teamName: "Tampa Bay Buccaneers", divisionLabel: "NFC South", summary: "11-5 · Super Bowl Champion" },
  "nfl-division-tb-2002": { season: 2002, teamCode: "TB", teamName: "Tampa Bay Buccaneers", divisionLabel: "NFC South", summary: "12-4 · Super Bowl Champion" },
  "nfl-division-tb-1999": { season: 1999, teamCode: "TB", teamName: "Tampa Bay Buccaneers", divisionLabel: "NFC South", summary: "11-5 · NFC Championship Game" },
  "nfl-division-ari-2021": { season: 2021, teamCode: "ARI", teamName: "Arizona Cardinals", divisionLabel: "NFC West", summary: "11-6 · Playoff Team" },
  "nfl-division-ari-2015": { season: 2015, teamCode: "ARI", teamName: "Arizona Cardinals", divisionLabel: "NFC West", summary: "13-3 · NFC Championship Game" },
  "nfl-division-ari-2009": { season: 2009, teamCode: "ARI", teamName: "Arizona Cardinals", divisionLabel: "NFC West", summary: "10-6 · Playoff Win" },
  "nfl-division-ari-2008": { season: 2008, teamCode: "ARI", teamName: "Arizona Cardinals", divisionLabel: "NFC West", summary: "9-7 · NFC Champion" },
  "nfl-division-lar-2021": { season: 2021, teamCode: "LAR", teamName: "Los Angeles Rams", divisionLabel: "NFC West", summary: "12-5 · Super Bowl Champion" },
  "nfl-division-lar-2018": { season: 2018, teamCode: "LAR", teamName: "Los Angeles Rams", divisionLabel: "NFC West", summary: "13-3 · NFC Champion" },
  "nfl-division-lar-2001": { season: 2001, teamCode: "LAR", teamName: "St. Louis Rams", divisionLabel: "NFC West", summary: "14-2 · NFC Champion" },
  "nfl-division-lar-1999": { season: 1999, teamCode: "LAR", teamName: "St. Louis Rams", divisionLabel: "NFC West", summary: "13-3 · Super Bowl Champion" },
  "nfl-division-sea-2025": { season: 2025, teamCode: "SEA", teamName: "Seattle Seahawks", divisionLabel: "NFC West", summary: "14-3 · Super Bowl Champion" },
  "nfl-division-sea-2014": { season: 2014, teamCode: "SEA", teamName: "Seattle Seahawks", divisionLabel: "NFC West", summary: "12-4 · NFC Champion" },
  "nfl-division-sea-2013": { season: 2013, teamCode: "SEA", teamName: "Seattle Seahawks", divisionLabel: "NFC West", summary: "13-3 · Super Bowl Champion" },
  "nfl-division-sea-2005": { season: 2005, teamCode: "SEA", teamName: "Seattle Seahawks", divisionLabel: "NFC West", summary: "13-3 · NFC Champion" },
  "nfl-division-sf-2023": { season: 2023, teamCode: "SF", teamName: "San Francisco 49ers", divisionLabel: "NFC West", summary: "12-5 · NFC Champion" },
  "nfl-division-sf-2019": { season: 2019, teamCode: "SF", teamName: "San Francisco 49ers", divisionLabel: "NFC West", summary: "13-3 · NFC Champion" },
  "nfl-division-sf-2012": { season: 2012, teamCode: "SF", teamName: "San Francisco 49ers", divisionLabel: "NFC West", summary: "11-4-1 · NFC Champion" },
  "nfl-division-sf-2011": { season: 2011, teamCode: "SF", teamName: "San Francisco 49ers", divisionLabel: "NFC West", summary: "13-3 · NFC Championship Game" },
} as const satisfies Readonly<Record<string, NflDivisionTeamSeasonPresentation>>;

export function nflDivisionTeamSeasonPresentation(itemReference: string | null | undefined) {
  if (!itemReference) return null;
  return NFL_DIVISION_TEAM_SEASONS[itemReference as keyof typeof NFL_DIVISION_TEAM_SEASONS] ?? null;
}
