// PR10 UFC person-identity research data batch 4. Canonical validation and lookup remain in ufcPersonIdentityKnowledge.ts.
export const ufcPersonIdentityResearchSources4 = [
  ["https://www.cbssports.com/mma/news/ufc-265-ciryl-gane-takes-unusual-path-to-reach-his-potential-greatness-against-derrick-lewis-in-houston/", "CBS Sports", "UFC 265: Ciryl Gane takes unusual path to reach his potential greatness"],
  ["https://www.ufc.com/athlete/ciryl-gane?language_content_entity=en", "UFC", "Ciryl Gane | UFC"],
  ["https://www.espn.com/mma/story/_/id/33102899/ufc-270-one-gym-paris-launched-careers-francis-ngannou-ciryl-gane-coach-rift-made-rivals", "ESPN", "One gym in Paris launched the careers of Francis Ngannou and Ciryl Gane"],
  ["https://www.ufc.com/node/68808", "UFC", "Team Werdum: Marlon 'Chito' Vera"],
  ["https://www.ufc.com/news/vera-fighting-daughters-chance-smile", "UFC", "Vera fighting for daughter's chance at a smile"],
  ["https://www.expreso.ec/deportes/conoce-marlon-vera-chito-ecuador-192366.html", "Expreso", "¿Por qué se lo conoce a Marlon Vera como 'Chito'?"],
  ["https://www.ufc.com/news/marlon-vera-hungrier-ever", "UFC", "Marlon Vera Is Hungrier Than Ever Before"],
  ["https://stonybrookathletics.com/honors/hall-of-fame/dominick-reyes/108", "Stony Brook Athletics", "Dominick Reyes - Hall of Fame"],
  ["https://kr.ufc.com/athlete/dominick-reyes", "UFC", "Dominick Reyes | UFC"],
  ["https://www.ufcespanol.com/athlete/dominick-reyes", "UFC", "Dominick Reyes | UFC"],
  ["https://www.espn.com/mma/story/_/id/28740668/dan-hooker-home-ufc-fight-night-auckland-headline-act", "ESPN", "Dan Hooker at home for UFC Fight Night Auckland headline act"],
  ["https://www.ufc.com/athlete/dan-hooker?language_content_entity=en", "UFC", "Dan Hooker | UFC"],
  ["https://macleans.ca/society/lord-of-the-ring/", "Maclean's", "Georges St. Pierre: Lord of the ring"],
  ["https://www.coachweb.com/sport/1434/georges-st-pierre-on-dinosaurs-and-why-karate-is-the-answer", "Coach", "Georges St-Pierre on dinosaurs and why karate is the answer"],
  ["https://www.ufc.com/news/georges-st-pierre-named-ufc-hall-fame-class-2020", "UFC", "Georges St-Pierre Named To UFC Hall Of Fame Class Of 2020"],
  ["https://www.ufc.com/athlete/islam-makhachev?page=4", "UFC", "Islam Makhachev | UFC Athlete Profile"],
  ["https://www.espn.com/mma/story/_/id/30958405/ufc-259-next-khabib-why-some-believe-islam-makhachev-ready-greatness", "ESPN", "UFC 259: The next Khabib? Why some believe Islam Makhachev is ready for greatness"],
  ["https://www.washingtonpost.com/sports/2025/11/20/islam-makhachev-ufc-brother-dagestan-fighters/", "The Washington Post", "The brotherly sacrifice behind Islam Makhachev's UFC rise"],
  ["https://www.ufc.com/news/matt-hughes-joins-ufc-front-office", "UFC", "Matt Hughes Joins UFC Front Office"],
  ["https://www.ufc.com/news/brothers-armbars-raw-story", "UFC", "Brothers in Armbars - raw story"],
  ["https://www.ufc.com/news/stipe-miocic-athlete", "UFC", "Stipe Miocic - The Athlete"],
  ["https://www.ufc.com/news/stipe-miocic-discovering-his-croatian-roots", "UFC", "Stipe Miocic: Discovering His Croatian Roots"],
  ["https://kr.ufc.com/athlete/stipe-miocic", "UFC", "Stipe Miocic | UFC Athlete Profile"],
  ["https://www.ufc.com/athlete/israel-adesanya?language_content_entity=en", "UFC", "Israel Adesanya | UFC Athlete Profile"],
  ["https://www.espn.com/espn/feature/story/_/id/28780685/the-ufc-next-big-thing", "ESPN", "The UFC's next big thing"],
  ["https://www.espn.com/mma/story/_/id/38346503/ufc-293-israel-adesanya-vs-sean-strickland-israel-adesanya-big-ufc-243-walkout-entrance-versus-robert-whittaker", "ESPN", "Inside Israel Adesanya's iconic UFC 243 walkout"],
  ["https://www.ufc.com/news/road-ufc-200-fighting-liddells-dna", "UFC", "Road to UFC 200: Fighting in Liddell's DNA"],
  ["https://www.ufc.com/news/chuck-liddell-tribute-fighter", "UFC", "Chuck Liddell - A Tribute to a Fighter"],
  ["https://www.ufc.com/news/chuck-liddell-retires-boardroom", "UFC", "Chuck Liddell Retires to Boardroom"],
] as const;

export const ufcPersonIdentityResearch4 = [
  ["ufc:ciryl-gane", [
    ["soccer-basketball-youth-sports", "Gane grew up playing team sports, especially soccer and basketball, before entering combat sports relatively late.", 0],
    ["management-marketing-degree", "Gane completed a degree in management and marketing before his fighting career.", 1],
    ["luxury-furniture-coworker-muay-thai", "While working as a luxury-furniture salesman, a coworker introduced Gane to Muay Thai, launching his combat-sports path.", 0],
    ["two-time-france-muay-thai-champion", "Gane became a two-time French Muay Thai champion before switching to professional MMA.", 1],
    ["fernand-lopez-mma-factory-pivot", "Coach Fernand Lopez quickly recognized Gane's potential at Paris' MMA Factory and pushed him to stop splitting focus with Muay Thai and commit to MMA.", 2],
  ]],
  ["ufc:marlon-vera", [
    ["jiu-jitsu-start-at-sixteen", "Vera has said he had little interest in organized sports until he began jiu-jitsu at 16, which quickly led him toward MMA.", 3],
    ["first-ecuadorian-ufc-fighter", "Vera became the first Ecuadorian fighter to compete in the UFC.", 4],
    ["daughter-surgery-career-motivation", "A major early-career motivation was earning enough to obtain specialized treatment for his daughter, who was born with Moebius syndrome.", 4],
    ["chito-childhood-nickname-origin", "The nickname 'Chito' traces back to childhood versions of his name, including 'Andrechito,' that family members shortened over time.", 5],
    ["downloaded-fight-videos-in-ecuador", "Growing up in Ecuador with limited access to UFC broadcasts and MMA gyms, Vera fed his interest by downloading fight videos and studying the sport from afar.", 6],
  ]],
  ["ufc:dominick-reyes", [
    ["stony-brook-football-safety", "Reyes was a four-year football player and three-year starting safety at Stony Brook before turning to MMA.", 7],
    ["information-systems-degree", "Reyes earned a bachelor's degree in information systems with a business and economics focus.", 8],
    ["technical-support-job", "Before fighting full time, Reyes worked as a technical support specialist at a high school.", 8],
    ["devastator-nickname-origin", "Reyes has explained that 'The Devastator' nickname came from the power of his kicks and the mentality he wanted to bring into fights.", 9],
    ["fighter-brother-alex-reyes", "His older brother Alex Reyes also became a professional MMA fighter and competed in the UFC.", 9],
  ]],
  ["ufc:dan-hooker", [
    ["friend-knockout-mma-origin", "Hooker says he decided to try MMA after watching a friend score a quick knockout and seeing the crowd's reaction, then followed that friend to the gym.", 10],
    ["auckland-doorman-job", "Before fighting full time, Hooker worked as a doorman in Auckland's central business district.", 11],
    ["hangman-nickname-chokes", "Hooker has said 'The Hangman' nickname came from his love of finishing fights with chokes.", 11],
    ["pre-ufc-kickboxing-titles", "Hooker's pre-UFC combat résumé included a King in the Ring middleweight kickboxing championship and a WKBF X-Rules welterweight title.", 11],
    ["one-minute-scraps-promotion", "Hooker has used his platform to promote '1min Scraps,' a New Zealand one-minute street-fighting concept.", 11],
  ]],
  ["ufc:georges-st-pierre", [
    ["bullying-karate-self-defense", "Frequent childhood bullying in Saint-Isidore pushed Georges St-Pierre toward self-defense; his father Roland, a karate black belt, taught him at home before St-Pierre began formal karate training as a child.", 12],
    ["paleontology-dinosaur-passion", "St-Pierre has a long-running fascination with dinosaurs and paleontology and has spoken about the subject in interviews as a genuine personal passion outside fighting.", 13],
    ["gymnastics-olympic-lifting-cross-training", "His athletic preparation has included gymnastics and Olympic lifting, disciplines he has described as useful for explosiveness and overall athletic development.", 13],
    ["gsp-foundation-anti-bullying", "He created the Georges St-Pierre Foundation in 2009 with a mission that includes combating bullying and encouraging youth physical activity.", 14],
    ["film-acting-captain-america", "Outside MMA, St-Pierre pursued acting and appeared as Georges Batroc in Marvel's Captain America: The Winter Soldier.", 14],
  ]],
  ["ufc:islam-makhachev", [
    ["training-age-ten-self-defense", "Makhachev has said he began training at about age 10 because he wanted to become stronger and be able to defend himself.", 15],
    ["combat-sambo-championship-pedigree", "Before becoming known globally for MMA, he built an elite combat-sambo résumé that included world and European titles as well as multiple Russian championships.", 15],
    ["dagestan-state-athletic-faculty", "Makhachev attended Dagestan State University and studied in its athletic or physical-education faculty while developing as a fighter.", 15],
    ["abdulmanap-khabib-training-lineage", "He grew up training in the same Dagestani system as Khabib Nurmagomedov and was developed under Khabib's father, Abdulmanap Nurmagomedov, who became a central mentor to their team.", 16],
    ["brother-kurban-family-sacrifice", "His older brother Kurban gave up his own fighting ambitions and worked to help support the family, allowing Islam to continue pursuing the training path laid out by Abdulmanap Nurmagomedov.", 17],
  ]],
  ["ufc:matt-hughes", [
    ["eastern-illinois-all-american-wrestling", "Hughes graduated from Eastern Illinois University and was a two-time NCAA Division I All-American wrestler before his MMA career.", 18],
    ["agricultural-company-parallel-career", "Even while fighting professionally, Hughes remained closely tied to his rural Illinois roots and operated an agricultural company.", 18],
    ["hometown-youth-mission-mentoring", "He has worked with young people in his hometown area, including mentoring youth and helping provide opportunities for mission trips.", 18],
    ["ufc-front-office-athlete-development", "After his championship career, Hughes moved into a UFC front-office role focused on athlete development and government relations.", 18],
    ["identical-twin-mark-mma-partner", "His identical twin brother Mark was also a wrestler and fighter; the brothers entered MMA together, trained in the Miletich system, and Mark later remained part of Matt's training and corner.", 19],
  ]],
  ["ufc:stipe-miocic", [
    ["cleveland-multi-sport-athlete", "Miocic was a high-level multi-sport athlete in Ohio, earning varsity letters in baseball, football and wrestling before competing in both NCAA wrestling and college baseball.", 20],
    ["cleveland-golden-gloves-boxing", "He added boxing to that athletic base and won the 2009 Cleveland Golden Gloves tournament, advancing to the national quarterfinals.", 20],
    ["firefighter-paramedic-career", "Miocic continued working as a firefighter and paramedic even after becoming a major UFC star, treating that public-service career as an important part of his identity.", 21],
    ["croatian-family-roots", "He was born in the United States to Croatian parents and later traveled to Croatia as an adult to connect with relatives and his family's roots.", 21],
    ["mma-start-helping-training-partner", "Miocic has said his path into MMA began when he went to a gym to help someone else prepare for a fight; the experience pulled him into the sport himself.", 22],
  ]],
  ["ufc:israel-adesanya", [
    ["self-protection-training-origin", "Adesanya has said he began serious combat-sports training in 2008 because he wanted the skills to protect himself.", 23],
    ["computer-graphic-design-study", "Before committing to fighting, he spent roughly three years studying computer graphic design and then left school to pursue combat sports.", 23],
    ["gas-line-billing-job", "One of his pre-fighting jobs was working as a metering and billing coordinator for a gas-line company.", 23],
    ["last-stylebender-anime-identity", "His 'The Last Stylebender' nickname reflects his long-running attachment to animation and anime culture, including Avatar: The Last Airbender.", 24],
    ["dance-background-ufc243-walkout", "Adesanya danced before he was famous as a fighter and made that background part of his public identity, most memorably with a choreographed UFC 243 walkout alongside longtime friends.", 25],
  ]],
  ["ufc:chuck-liddell", [
    ["karate-since-twelve-dream-gym", "Liddell began karate at about age 12 and has described owning a karate gym as an early childhood ambition.", 26],
    ["accounting-degree-grandmother-fallback", "He earned an accounting degree, explaining that his grandmother pushed him toward a practical academic fallback rather than treating physical education as his main plan.", 26],
    ["head-tattoo-peace-prosperity", "The kanji tattoo on the side of Liddell's head has been described by him as meaning a 'place of peace and prosperity.'", 27],
    ["college-bartender-job", "While in college, Liddell worked behind a bar before fighting became his full-time career.", 27],
    ["post-retirement-ufc-executive", "When he first retired from competition, Liddell transitioned into a UFC executive role involving fighter relations and business or regulatory work.", 28],
  ]],
] as const;
