// PR10 UFC person-identity research data batch 7. Canonical validation and lookup remain in ufcPersonIdentityKnowledge.ts.
export const ufcPersonIdentityResearchSources7 = [
  ["https://www.ufc.com/athlete/holly-holm", "UFC", "Holly Holm | UFC Athlete Profile"],
  ["https://www.ufc.com/news/nate-diaz-fighting-life", "UFC", "Nate Diaz's Fighting Life"],
  ["https://www.ufc.com/news/flashback-nate-diaz-23", "UFC", "Flashback: Nate Diaz At 23"],
  ["https://www.ufc.com/news/another-side-nate-diaz", "UFC", "Another Side Of Nate Diaz"],
  ["https://www.ufc.com/athlete/colby-covington", "UFC", "Colby Covington | UFC Athlete Profile"],
  ["https://www.ufc.com/news/colby-covington-proud-his-wrestling-roots-ufc-fight-pass", "UFC", "Colby Covington Proud Of His Wrestling Roots"],
  ["https://www.espn.com/mma/story/_/id/33407960/ufc-272-poker-sushi-betrayal-how-colby-covington-jorge-masvidal-went-roommates-rivals", "ESPN", "UFC 272: How Colby Covington and Jorge Masvidal went from roommates to rivals"],
  ["https://www.ufc.com/node/68250", "UFC", "TUF Latinoamérica: Yair Rodriguez"],
  ["https://www.ufc.com/node/75863", "UFC", "La Otra Cara de Yair Rodriguez"],
  ["https://www.ufc.com/athlete/kevin-holland", "UFC", "Kevin Holland | UFC Athlete Profile"],
  ["https://www.ufc.com/news/kevin-holland-chasing-history-ufc-311", "UFC", "Kevin Holland | Chasing History In 2025"],
  ["https://www.mmafighting.com/2020/5/29/21274531/bronchitis-ice-cream-gilbert-burns-durinho-tyron-woodley-ufc", "MMA Fighting", "From bronchitis and ice cream to the UFC: The story of Gilbert 'Durinho' Burns"],
  ["https://www.ufc.com/news/gilbert-burns-unparalleled-support-system-ufc-287", "UFC", "Gilbert Burns' Unparalleled Support System"],
  ["https://www.ufc.com/news/nick-diaz-man-apart", "UFC", "Nick Diaz: A Man Apart"],
  ["https://www.ufc.com/news/fighting-has-defined-nick-diaz-ufc-266-volkanovski-vs-ortega-diaz-lawler-2", "UFC", "Fighting Has Defined Nick Diaz's Life"],
  ["https://www.ufc.com/news/nick-diaz-knows-what-you-think-about-him-he-also-knows-you-cannot-turn-away", "UFC", "Nick Diaz Knows What You Think About Him. He Also Knows You Cannot Turn Away"],
  ["https://www.ufc.com/news/comeback-anderson-silva-never-really-left", "UFC", "Comeback? Anderson Silva never really left"],
  ["https://www.ufc.com/news/say-it-again-anderson-silvas-greatest-soundbytes", "UFC", "Say it again: Anderson Silva's greatest soundbytes"],
  ["https://www.ufc.com/news/spider-says-silvas-quotes", "UFC", "The Spider Says – Silva's Quotes"],
  ["https://www.sbs.com.au/language/macedonian/en/podcast-episode/from-rugby-league-to-ufc-champ-meet-alexander-the-great-volkanovski/jmty4b72p", "SBS Macedonian", "From Rugby League to UFC champ: meet Alexander \"The Great\" Volkanovski"],
  ["https://www.espn.com/mma/story/_/id/28234665/ufc-alexander-volkanovksi-humble-local-hero-focus-swayed", "ESPN", "Volkanovski the humble local hero whose focus can't be swayed"],
  ["https://www.ufc.com/news/joe-lopez-says-personality-clash-fuels-featherweight-champion-alexander-volkanovski-ufc-266", "UFC", "Joe Lopez: 'Personality Clash' Fuels Volkanovski In A New Way"],
  ["https://www.ufc.com/news/kamaru-usman-reflects-on-his-return-to-nigeria", "UFC", "Kamaru Usman Reflects On His Return To Nigeria"],
  ["https://www.espn.com/espn/feature/story/_/page/Coverstory-April2021/the-reign-kamaru-usman", "ESPN", "The reign of Kamaru Usman"],
  ["https://www.ufc.com/news/its-still-kamaru-usman-time-main-event-ufc-278", "UFC", "It's Still Kamaru Usman Time"],
  ["https://www.espn.com/mma/story/_/id/29424043/fight-island-story-kamaru-usman-father-texas-prison", "ESPN", "Fight Island -- The inside story of Kamaru Usman, his father and a Texas prison"],
] as const;

export const ufcPersonIdentityResearch7 = [
  ["ufc:holly-holm", [
    ["preachers-daughter-nickname", "Holm's 'The Preacher's Daughter' nickname is literal: her father was a Church of Christ preacher for much of her life.", 0],
    ["cardio-kickboxing-accidental-start", "Her combat-sports career began almost accidentally when she took cardio-kickboxing classes for exercise as a teenager and became fascinated by the fighters sparring at the gym.", 0],
    ["boxing-hall-of-fame-career", "Long before her UFC identity was complete, Holm had an elite professional-boxing career that eventually earned induction into major women's and international boxing halls of fame.", 0],
    ["real-estate-license", "Holm attended real-estate school and has maintained a real-estate license outside of fighting.", 0],
    ["server-chiropractic-assistant-jobs", "Her pre-fighting work history included restaurant serving and working as a chiropractic assistant.", 0],
  ]],
  ["ufc:nate-diaz", [
    ["stockton-martial-arts-solace", "Diaz has described martial arts as a source of structure and refuge while growing up in rough parts of Stockton, California.", 1],
    ["nick-royce-gracie-influence", "His older brother Nick helped steer him toward Brazilian jiu-jitsu by showing him footage of Royce Gracie and bringing him deeper into the martial-arts world.", 1],
    ["cesar-gracie-shark-tank-training", "As a teenager, Nate trained in the Cesar Gracie system alongside experienced fighters such as Nick Diaz, Gil Castillo and Dave Terrell, an environment he recalled as unusually demanding for a young prospect.", 2],
    ["vegan-diet-body-awareness", "Diaz adopted a vegan or heavily plant-based diet as part of the way he manages his body and conditioning, making nutrition a recognizable part of his public identity.", 3],
    ["stockton-gym-youth-teaching", "The Diaz brothers built a Stockton martial-arts academy that serves students of different ages, and Nate has spoken about teaching and passing the sport on locally.", 3],
  ]],
  ["ufc:colby-covington", [
    ["chaos-nickname-mother-mythology", "Covington has said his mother gave him the nickname 'Chaos,' connecting it both to the Greek-mythology term and to his unpredictable behavior as a child.", 4],
    ["oregon-state-sociology-degree", "He graduated from Oregon State University with a bachelor's degree in sociology.", 4],
    ["pac10-ncaa-wrestling-pedigree", "Covington's foundation was elite collegiate wrestling, including a Pac-10 championship and All-American recognition at Oregon State.", 4],
    ["iowa-to-oregon-state-wrestling-path", "His college path was not linear: he spent time in the Iowa wrestling system and at junior college before transferring to Oregon State, closer to his family, and rebuilding his Division I career there.", 5],
    ["masvidal-roommates-to-rivals", "Covington and Jorge Masvidal were once close friends, teammates and roommates before their relationship deteriorated into one of MMA's most personal rivalries.", 6],
  ]],
  ["ufc:yair-rodriguez", [
    ["taekwondo-at-five", "Rodriguez's martial-arts background began very young, when his parents enrolled him in taekwondo at about age five.", 7],
    ["discovered-vale-todo-gym", "His route into MMA accelerated when he came across a vale-tudo gym while looking for a place to keep training and decided to try the more complete fighting style.", 8],
    ["parral-to-chicago-training-move", "Rodriguez later left Parral, Mexico for Chicago to train with coaches including Izzy Martinez and Mike Valle, using the move to immerse himself in higher-level preparation away from distractions.", 8],
    ["study-work-training-balancing", "Before he could focus fully on fighting, Rodriguez described trying to balance school, work and training at the same time.", 8],
    ["ranchera-music-personal-tastes", "In his early UFC profile, Rodriguez identified ranchera music among his personal tastes, along with Italian food and beach vacations.", 7],
  ]],
  ["ufc:kevin-holland", [
    ["kung-fu-humbling-start-age-sixteen", "Holland has said he walked into a kung-fu gym around age 16 with an inflated sense of his fighting ability and was quickly humbled, which convinced him to keep training.", 9],
    ["trailblazer-nickname-school-name", "His 'Trailblazer' nickname traces back to his original kung-fu instructor's plan for a school name built around the phrase 'Trailblazer Achieve More.'", 9],
    ["electrical-apprentice-job", "Before fighting full time, Holland worked as an electrical apprentice.", 9],
    ["dual-black-belts-kungfu-bjj", "Holland's training identity combines a second-degree black belt in kung fu with a Brazilian jiu-jitsu black belt under Travis Lutter.", 9],
    ["big-mouth-midfight-talking-persona", "His habit of talking during fights became a signature trait early in his UFC path; Dana White even labeled him 'Big Mouth' after hearing him jaw throughout a Contender Series bout.", 10],
  ]],
  ["ufc:gilbert-burns", [
    ["childhood-bronchitis-sports-catalyst", "Burns has explained that childhood asthmatic bronchitis helped push him toward sports after a doctor recommended physical activity, with swimming among his earliest organized activities.", 11],
    ["upholstery-barter-bjj-scholarship", "Because his family could not easily afford jiu-jitsu, Burns's upholsterer father bartered work on a customer's car seats in exchange for an initial stretch of BJJ training for his sons.", 11],
    ["durinho-nickname-brother-diminutive", "The nickname 'Durinho' is a diminutive play on his older brother Frederick's nickname 'Todo Duro' and was coined in the jiu-jitsu environment around Vitor 'Shaolin' Ribeiro.", 11],
    ["bjj-world-title-before-mma", "Burns deliberately wanted to win a major black-belt jiu-jitsu world title before turning his attention fully to MMA; after accomplishing that goal in 2011, he made the transition.", 11],
    ["belfort-cornerman-hooft-connection", "Before his own UFC run, Burns cornered Vitor Belfort at UFC 133, where he first crossed paths with striking coach Henri Hooft, who later became a major long-term coach and mentor for Burns.", 12],
  ]],
  ["ufc:nick-diaz", [
    ["unstable-school-upbringing", "Diaz has described an unsettled school-age upbringing in which he moved among many schools and was regularly roughed up by older kids, making martial-arts training an important source of structure.", 13],
    ["jiujitsu-community-social-skills", "He has said the jiu-jitsu gym gave him a community he lacked elsewhere and helped him develop confidence and social skills as a teenager.", 13],
    ["two-pre-fight-jobs", "Diaz has recalled having only two conventional jobs before committing to fighting: work at a collections agency and running wires under buildings.", 13],
    ["stockton-slap-grandfather-origin", "Diaz has connected his signature open-hand slap to a childhood memory of his grandfather striking him with an open hand; fans later came to call Diaz's version the 'Stockton Slap.'", 14],
    ["offroad-triathlon-passion", "Endurance sports are a genuine hobby for Diaz: he has described doing multiple triathlons a year, with a particular interest in off-road events.", 15],
  ]],
  ["ufc:anderson-silva", [
    ["raised-by-aunt-and-uncle", "Silva has described being left by his parents when he was very young and being raised by an aunt and uncle, with his uncle serving in the military.", 16],
    ["childhood-soccer-ambition", "Before fighting became his path, Silva wanted to play soccer, but his family's limited finances made organized sports and training difficult.", 16],
    ["spider-man-comic-collector", "Silva said he collected every Spider-Man comic-book series from 1984 onward and identified with Spider-Man because, unlike richer or otherworldly superheroes, he still had ordinary bills to pay.", 17],
    ["practical-joker-personality", "Silva has described himself as a practical joker who likes making people laugh; one story he told was hiding his cousin's tuxedo on the cousin's wedding day.", 17],
    ["royce-gracie-ufc1-inspiration", "Silva said watching Royce Gracie at UFC 1 made competing in the UFC a dream of his.", 18],
  ]],
  ["ufc:alexander-volkanovski", [
    ["alexander-the-great-nickname-heritage", "Volkanovski changed an earlier 'Hulk' nickname to 'Alexander the Great,' tying the name to his Macedonian and Greek family heritage.", 19],
    ["national-level-wrestling-background", "Before rugby league and MMA, Volkanovski trained in Greco-Roman and freestyle wrestling and told SBS he won two Australian national wrestling titles.", 19],
    ["warilla-gorillas-rugby-league", "Volkanovski played rugby league for the Warilla Gorillas, including a 2011 premiership season, and competed at roughly 97 kg before eventually fighting at featherweight.", 19],
    ["family-concreting-trade", "Volkanovski came from a family of concreters and worked in concreting before fighting became his full-time career.", 20],
    ["rugby-conditioning-led-to-mma-coach", "Volkanovski first entered Joe Lopez's Freestyle Fighting Gym with rugby teammates for preseason conditioning; Lopez became his long-term MMA coach.", 21],
  ]],
  ["ufc:kamaru-usman", [
    ["nigeria-to-dallas-childhood", "Usman was born in Auchi, Nigeria, and moved with his family to the Dallas area when he was about eight years old.", 22],
    ["marty-wrestling-nickname", "A high-school wrestling coach who struggled with 'Kamarudeen' called him 'Marty,' a nickname that followed Usman through much of his wrestling career before he publicly reclaimed Kamaru.", 23],
    ["olympic-wrestling-dream", "Usman trained at the U.S. Olympic Training Center with the goal of making an Olympic wrestling team before committing fully to MMA.", 24],
    ["rashad-evans-mma-bridge", "Rashad Evans became an important bridge from Usman's wrestling world into MMA while Usman was at the Olympic Training Center.", 24],
    ["father-prison-and-tv-fights", "While Usman's father served a federal prison sentence, Usman tried to keep early UFC appearances on television rather than pay-per-view so his father and other inmates could watch them.", 25],
  ]],
] as const;
