// PR10 UFC person-identity research data batch 2. Canonical validation and lookup remain in ufcPersonIdentityKnowledge.ts.
export const ufcPersonIdentityResearchSources2 = [
  ["https://www.ufc.com/news/dustin-poiriers-education-through-fire", "UFC", "Dustin Poirier's Education Through Fire"],
  ["https://www.ufc.com/news/shine-diamond-poirier", "UFC", "Shine On, 'Diamond' Poirier"],
  ["https://www.ufc.com/news/dustin-poirier-the-good-fight-foundation", "UFC", "Dustin Poirier Dedicated To 'The Good Fight'"],
  ["https://www.ufc.com/athlete/dustin-poirier", "UFC", "Dustin Poirier | UFC"],
  ["https://www.ufc.com/news/ufc-and-mma-fan-favorite-dustin-diamond-poirier-announce-marketing-partnership-ufc-281?language_content_entity=en", "UFC", "UFC And MMA Fan Favorite Dustin 'The Diamond' Poirier Announce Marketing Partnership"],
  ["https://www.ufc.com/news/ortiz-chronicles-early-years", "UFC", "Ortiz Chronicles: Early Years"],
  ["https://www.ufc.com/news/origins-champ-tito-ortiz?language_content_entity=en", "UFC", "Origins of a Champ: Tito Ortiz"],
  ["https://www.ufc.com/news/robbie-lawler-his-own-words", "UFC", "Robbie Lawler: In His Own Words"],
  ["https://www.ufc.com/news/robbie-lawler-named-ufc-hall-fame-class-2025", "UFC", "Robbie Lawler Named to UFC Hall of Fame Class of 2025"],
  ["https://www.ufc.com/news/rob-ruthless-coaching-journey", "UFC", "Rob to Ruthless - A Coaching Journey"],
  ["https://www.ufc.com/news/henry-cejudo-enters-national-wrestling-hall-fame-saturday", "UFC", "Henry Cejudo enters the National Wrestling Hall of Fame Saturday"],
  ["https://www.ufc.com/athlete/henry-cejudo", "UFC", "Henry Cejudo | UFC"],
  ["https://www.teamusa.com/profiles/henry-cejudo", "Team USA", "Henry Cejudo | Team USA"],
  ["https://www.ufc.com/news/henry-cejudo-triple-c-last-dance-ufc-323", "UFC", "Henry Cejudo | Triple C's Last Dance"],
  ["https://www.ufc.com/athlete/petr-yan?page=1", "UFC", "Petr Yan | UFC"],
  ["https://www.ufc.com/news/yan-lives-his-nickname", "UFC", "Yan Lives Up To His Nickname"],
  ["https://www.espn.com/mma/story/_/id/30752895/ufc-257-party-j-lo-dinner-bono-stories-conor-mcgregor", "ESPN", "UFC 257: Party with J.Lo, dinner with Bono and other stories of Conor McGregor"],
  ["https://shop.conormcgregor.com/pages/about-conor", "Conor McGregor", "About Conor"],
  ["https://us.ufcespanol.com/news/flashback-making-mcgregor", "UFC", "Flashback: Making McGregor"],
  ["https://www.mmafighting.com/ufc/495077/conor-mcgregor-explains-backstory-behind-notorious-nickname", "MMA Fighting", "Conor McGregor explains backstory behind 'Notorious' nickname"],
  ["https://www.ufc.com/news/complete-machida", "UFC", "The Complete Machida"],
  ["https://www.ufc.com/athlete/dricus-du-plessis?language_content_entity=en", "UFC", "Dricus Du Plessis | UFC"],
  ["https://www.ufc.com/athlete/khamzat-chimaev", "UFC", "Khamzat Chimaev | UFC"],
  ["https://kr.ufc.com/athlete/khamzat-chimaev?page=1", "UFC", "Khamzat Chimaev | UFC"],
  ["https://www.ufc.com/news/sean-omalley-fighting-to-be-the-best-ufc-250", "UFC", "Sean O'Malley Fighting To Be The Best"],
  ["https://www.montanasports.com/more-sports/molded-who-i-was-sean-omalley-credits-growing-up-in-montana-as-huge-role-in-ufc-success", "MTN Sports", "Sean O'Malley credits growing up in Montana as 'huge role' in UFC success"],
  ["https://www.bbc.co.uk/sport/mixed-martial-arts/53763265", "BBC Sport", "UFC 252: Sean O'Malley on his dog, his colourful hair and fighting"],
  ["https://www.espn.com/mma/ufc/story/_/id/28809373/facial-tattoos-smoking-snoop-meet-star-fighter-sean-omalley", "ESPN", "UFC 248: Facial tattoos, smoking with Snoop ... meet star fighter Sean O'Malley"],
] as const;

export const ufcPersonIdentityResearch2 = [
  ["ufc:dustin-poirier", [
    ["ninth-grade-dropout-and-juvenile-detention", "Poirier left school in the ninth grade and has spoken openly about spending time in juvenile detention before finding direction through fighting.", 0],
    ["fightville-documentary-subject", "Poirier's early professional rise in Louisiana was prominently documented in the 2011 documentary Fightville.", 1],
    ["good-fight-foundation-gear-auctions", "Poirier and his wife Jolie built The Good Fight Foundation from the idea of auctioning his fight-worn gear and directing the proceeds to community causes.", 2],
    ["diamond-nickname-tim-credeur", "Poirier has credited longtime Louisiana coach Tim Credeur with giving him 'The Diamond' nickname during his WEC-era development.", 3],
    ["louisiana-hot-sauce-and-cajun-roots", "Poirier built Poirier's Louisiana Style hot sauce around the Cajun flavors he grew up with in Lafayette, and it later became the UFC's first official hot-sauce partner.", 4],
  ]],
  ["ufc:tito-ortiz", [
    ["ufc-one-royce-gracie-inspiration", "Ortiz has described watching the first UFC, especially Royce Gracie, as a major spark that made the new sport feel attainable to him.", 5],
    ["tank-abbott-training-connection", "Before becoming a UFC name himself, Ortiz gained early no-holds-barred experience by training with fellow Huntington Beach fighter Tank Abbott.", 5],
    ["golden-west-wrestling-scholarship", "Ortiz rebuilt his wrestling path at Golden West College, where he earned a scholarship and developed into a standout collegiate wrestler.", 6],
    ["ufc-thirteen-no-prize-money", "For his UFC 13 appearance, Ortiz competed without accepting prize money in order to preserve his college wrestling eligibility.", 6],
    ["adult-novelty-store-job", "Ortiz worked at an adult novelty store while trying to support himself before his fighting career took off.", 5],
  ]],
  ["ufc:robbie-lawler", [
    ["father-started-martial-arts-after-brother", "Lawler has said his father put him into martial arts after seeing how much Robbie wanted to compete with an older brother who regularly got the better of him.", 7],
    ["third-grade-weightlifting", "Lawler says he began lifting weights as early as third grade, an unusual childhood habit he later connected to developing his natural punching power.", 7],
    ["san-diego-to-iowa-athletic-upbringing", "Lawler moved from San Diego to Bettendorf, Iowa as a child and later competed in both wrestling and football there.", 8],
    ["miletich-gym-at-sixteen", "At 16, Lawler began training at Pat Miletich's gym, placing him inside one of the defining early American MMA teams while he was still in high school.", 9],
    ["matt-pena-longtime-corner", "Coach Matt Pena became one of Lawler's longest-running corner relationships, working dozens of his professional fights.", 9],
  ]],
  ["ufc:henry-cejudo", [
    ["phoenix-poverty-upbringing", "Cejudo has described growing up in a low-income, welfare-dependent household in Phoenix where basic necessities could be difficult to secure.", 10],
    ["youngest-us-freestyle-olympic-gold", "At 21, Cejudo became the youngest American wrestler at the time to win an Olympic freestyle wrestling gold medal.", 10],
    ["arizona-bronze-gloves-boxing", "Cejudo also competed in amateur boxing and won an Arizona Bronze Gloves championship before fully committing to MMA.", 11],
    ["older-brother-angel-wrestling-influence", "His older brother Angel Cejudo was a nationally ranked freestyle wrestler and an important influence on Henry's path into elite wrestling.", 12],
    ["triple-c-nickname-origin", "The 'Triple C' persona grew from Cejudo combining his Olympic gold-medal identity with his status as UFC champion in two divisions.", 13],
  ]],
  ["ufc:petr-yan", [
    ["boxing-at-thirteen-to-mma", "Yan began boxing at 13 and did not transition into MMA until roughly seven years later.", 14],
    ["three-sessions-per-day-routine", "Yan has described a three-session daily training structure: strength and conditioning in the morning, sparring in the afternoon, and technical drilling in the evening.", 14],
    ["youth-boxing-trainer-education", "Yan spent five years at an athletic institute and specialized in training to become a youth boxing coach.", 14],
    ["part-time-security-jobs", "Before fighting became his profession, Yan worked part-time security jobs.", 14],
    ["no-mercy-nickname-mindset", "Yan chose 'No Mercy' to describe the mindset and opportunistic finishing style he wants to carry into each fight.", 15],
  ]],
  ["ufc:conor-mcgregor", [
    ["crumlin-boxing-after-football", "McGregor played football as a boy before gravitating toward boxing and entering Crumlin Boxing Club around age 10.", 16],
    ["plumber-apprenticeship", "Before committing fully to fighting, McGregor worked as a plumber's apprentice in Dublin.", 17],
    ["john-kavanagh-sbg-commitment-pivot", "McGregor's relationship with John Kavanagh at SBG Ireland became decisive when Kavanagh pushed him to stop drifting and commit seriously to training.", 18],
    ["notorious-nickname-origin", "McGregor has tied 'The Notorious' nickname to his reputation for getting into trouble when he was younger and to his admiration for rapper The Notorious B.I.G.", 19],
    ["proper-no-twelve-cofounder", "Outside fighting, McGregor co-founded the Proper No. Twelve Irish whiskey brand in 2018.", 17],
  ]],
  ["ufc:lyoto-machida", [
    ["shotokan-with-father-from-age-three", "Machida began Shotokan karate at age three under his father Yoshizo, a karate master, and kept that art as the foundation of his fighting style.", 20],
    ["five-thirty-discipline-training", "His father deliberately scheduled 5:30 a.m. karate sessions as a lesson in discipline, a routine Machida continued for years.", 20],
    ["karate-core-in-mma", "Even after branching into MMA, Machida deliberately preserved Shotokan distance, timing and movement as the core of his style rather than abandoning it for a more conventional MMA stance.", 20],
    ["sumo-and-jiu-jitsu-cross-training", "Machida also competed and trained in sumo and began Brazilian jiu-jitsu at 15, adding those arts around his karate base.", 20],
    ["physical-education-degree", "Machida completed a college degree in physical education while pursuing combat-sports training.", 20],
  ]],
  ["ufc:dricus-du-plessis", [
    ["judo-wrestling-kickboxing-childhood", "Du Plessis' martial-arts path moved from judo as a child to wrestling and then K-1 kickboxing as a teenager before MMA.", 21],
    ["teenage-south-african-wako-champion", "As a teenager, du Plessis became a South African WAKO K-1 world champion before moving into MMA.", 21],
    ["stillknocks-nickname-brother-origin", "Du Plessis has credited his brother with the 'Stillknocks' nickname, a reference to his knockout-heavy amateur kickboxing run.", 21],
    ["agricultural-economics-final-year-dropout", "Du Plessis studied agricultural economics at the University of Pretoria but left in his final year when an EFC title opportunity convinced him to pursue fighting full time.", 21],
    ["professional-fighter-only-career", "Du Plessis has said he never had a separate conventional job after school because professional fighting became his full-time career.", 21],
  ]],
  ["ufc:khamzat-chimaev", [
    ["chechnya-to-sweden-wrestling", "Chimaev wrestled from a young age and continued the sport after moving from Chechnya to Sweden.", 22],
    ["hotel-gift-card-allstars-origin", "After winning a hotel gift card through a wrestling event, Chimaev visited Stockholm, tried training at Allstars Training Center and soon rearranged his life around MMA.", 22],
    ["poultry-factory-and-security-jobs", "Before fighting full time, Chimaev worked at a poultry factory in Kalmar and later in security in Stockholm.", 22],
    ["five-am-jog-training-routine", "Chimaev has described beginning a typical training day with a 5 a.m. jog, sleeping again briefly, then returning for team practice later in the morning.", 23],
    ["borz-means-wolf", "His nickname 'Borz' means 'wolf' in Chechen.", 22],
  ]],
  ["ufc:sean-omalley", [
    ["helena-montana-first-coach", "O'Malley grew up in Helena, Montana and has credited first MMA coach Johnny Aho with giving him unusually strong belief in his potential.", 24],
    ["nfl-dream-before-fighting", "Before discovering fighting at 16, O'Malley says he dreamed of reaching the NFL but realized his slight teenage build made that path unrealistic.", 25],
    ["sugar-nickname-sweet-to-watch", "The nickname 'Sugar' came from an early coach who thought O'Malley's striking was 'sweet' to watch.", 26],
    ["fight-week-colorful-hair-tradition", "O'Malley made bright, fight-specific hair colors part of his visual identity, at times using an opponent's national colors and even matching his dog's dyed fur.", 26],
    ["snoop-dogg-contender-series-connection", "After O'Malley's breakout Contender Series knockout, Snoop Dogg became part of the viral moment and later met O'Malley, an association that helped amplify his early UFC-era celebrity.", 27],
  ]],
] as const;
