// PR10 UFC person-identity research data batch 9. Canonical validation and lookup remain in ufcPersonIdentityKnowledge.ts.
export const ufcPersonIdentityResearchSources9 = [
  ["https://www.espn.com/extra/mma/news/story?id=3638757", "ESPN", "Brothers Ken, Frank Shamrock itching to fight"],
  ["https://www.si.com/more-sports/2010/06/29/shamrock", "Sports Illustrated", "Shamrock's legacy stretches beyond the cage; more MMA notes"],
  ["https://www.espn.com/mma/story/_/id/30348955/ufc-champ-deiveson-figueiredo-put-work-sushi-chef-hairdresser", "ESPN", "UFC champ Deiveson Figueiredo has put in the work -- from sushi chef to hairdresser"],
  ["https://www.ufc.com/news/vitor-belfort-fightography-now-live-ufc-fight-pass", "UFC", "Vitor Belfort Fightography now live on UFC FIGHT PASS"],
  ["https://www.ufc.com/news/vitor-belfort-named-ufc-hall-fame-class-2025", "UFC", "VITOR BELFORT NAMED TO UFC HALL OF FAME CLASS OF 2025"],
  ["https://www.ufc.com/news/vitor-belfort-diet", "UFC", "The Vitor Belfort Diet"],
  ["https://www.ufc.com/news/defining-phenom", "UFC", "Defining \"The Phenom\""],
  ["https://www.espn.com/mma/story/_/id/40642235/ufc-304-making-golden-generation-english-mma-leon-edwards-tom-aspinall-michael-bisping", "ESPN", "Bisping, Edwards and Aspinall: Inside the making of English MMA's golden generation"],
  ["https://www.ufc.com/news/tom-aspinall-thrives-under-pressure-heavyweight-ufc-fight-night-brunson-till", "UFC", "Tom Aspinall Thrives Under Pressure | UFC Fight Night: Brunson vs Till"],
  ["https://www.ufc.com/news/tom-aspinall-london-no-going-anywhere-heavyweight-ufc-main-event", "UFC", "Tom Aspinall Not Going Anywhere"],
  ["https://www.espn.com/mma/story/_/id/46706704/ufc-321-secrets-tom-aspinall-heavyweight-fighting-approach", "ESPN", "UFC 321: Inside Tom Aspinall's unique heavyweight strategy"],
  ["https://www.espn.com/mma/story/_/id/9964541/family-tradition", "ESPN", "The Gracies: A family tradition"],
  ["https://www.ufc.com/news/ufc-turns-30-years-old", "UFC", "UFC At 30: Looking Back At Three Decades Of Changing The Game"],
  ["https://www.ufc.com/news/gracie-way", "UFC", "The Gracie Way"],
  ["https://www.mmafighting.com/2010/08/17/183020/showtime-pettis-plans-to-exploit-shane-rollers-holes-seize-w", "MMA Fighting", "‘Showtime’ Pettis Plans to Exploit Shane Roller’s Holes, Seize WEC Spotlight"],
  ["https://www.ufc.com/news/when-its-showtime-anthony-pettis-turns-chaos-comfort", "UFC", "When It's Showtime, Anthony Pettis Turns Chaos Into Comfort"],
  ["https://www.ufc.com/news/pettis-ready-defend", "UFC", "Pettis Ready to Defend"],
  ["https://www.ufc.com/news/anthony-pettis-finally-its-showtime", "UFC", "Anthony Pettis: Finally, It's Showtime"],
  ["https://www.ufc.com/athlete/mauricio-rua", "UFC", "Mauricio Rua | UFC"],
  ["https://www.ufc.com/news/how-chute-boxe-created-brazil-ufc-legends", "UFC", "How Chute Boxe created Brazil UFC legends"],
  ["https://www.ufc.com/news/shogun-returns-his-second-home", "UFC", "Shogun Returns to His Second Home"],
  ["https://www.ufc.com/news/shogun-back-what-was-center-mma", "UFC", "Shogun back in what was the center of MMA"],
  ["https://www.ufc.com/news/dan-henderson-fue-dos-veces-seleccionado-olimpico", "UFC", "Dan Henderson fue dos veces seleccionado olímpico"],
  ["https://www.ufc.com/news/dan-henderson-ufc-career-three-parts", "UFC", "Dan Henderson: A UFC Career in Three Parts"],
  ["https://www.ufc.com/news/nunes-travels-hard-fought-path-stardom", "UFC", "Nunes travels hard-fought path to stardom"],
  ["https://www.ufc.com/athlete/amanda-nunes", "UFC", "Amanda Nunes | UFC"],
  ["https://www.ufc.com/news/joanna-jedrzejczyk-born", "UFC", "Joanna Jedrzejczyk: Born for This"],
  ["https://www.ufc.com/news/jedrzejczyk-took-tough-road-grand-dreams", "UFC", "Jedrzejczyk took tough road to grand dreams"],
  ["https://www.ufc.com/athlete/joanna-jedrzejczyk", "UFC", "Joanna Jędrzejczyk | UFC"],
] as const;

export const ufcPersonIdentityResearch9 = [
  ["ufc:frank-shamrock", [
    ["foster-and-group-home-childhood", "Born Frank Juarez, Shamrock left home young and spent years moving through foster homes and group homes before reaching Bob Shamrock's Boys Ranch.", 0],
    ["bob-shamrock-adoption", "Bob Shamrock took Frank in at his ranch for troubled youth and eventually adopted him; Frank took the Shamrock surname in honor of the man who became his father figure.", 1],
    ["helped-form-american-kickboxing-academy", "After leaving the Lion's Den orbit, Shamrock moved to San Jose and helped form American Kickboxing Academy.", 1],
    ["early-balanced-cross-training", "Working with Javier Mendez, Maurice Smith and Tsuyoshi Kohsaka, Shamrock deliberately diversified his striking, wrestling and submission skills and became an early model of the well-rounded modern MMA fighter.", 1],
    ["fighter-to-fight-executive-identity", "After his first retirement in 1999, Shamrock said he stopped thinking of himself only as a fighter and became a 'fight executive,' taking deliberate control of his personal brand and business value.", 1],
  ]],
  ["ufc:deiveson-figueiredo", [
    ["marajo-island-farm-upbringing", "Figueiredo grew up around a small farm on Marajó Island in Pará, an upbringing closely tied to fishing, animals and rural life.", 2],
    ["marajoara-grappling-origin", "Before formal MMA success, Figueiredo practiced luta marajoara, the traditional grappling style associated with Marajó Island.", 2],
    ["security-guard-job", "Figueiredo worked as a security guard before his fighting career was financially established.", 2],
    ["sushi-chef-and-delivery-business", "Figueiredo worked as a sushi chef and later used money from his early UFC career to help start a sushi-delivery business with his brother.", 2],
    ["hair-salon-work", "Figueiredo also worked in a hair salon, learning styling and makeup work while building his fighting career.", 2],
  ]],
  ["ufc:vitor-belfort", [
    ["street-sparring-tissue-mouthguards", "Belfort has recalled sparring grown men in Rio as a boy using improvised bathroom-tissue mouthguards before he had proper equipment.", 3],
    ["carlson-gracie-protege", "Belfort began boxing and Brazilian jiu-jitsu young and became a black belt under Carlson Gracie by age 18.", 4],
    ["teenage-move-to-los-angeles", "Belfort moved from Brazil to Los Angeles as a teenager to pursue his fighting development in the United States.", 5],
    ["sister-priscila-disappearance", "The 2004 disappearance of Belfort's sister Priscila became a defining family tragedy that Belfort has discussed publicly throughout his career.", 6],
    ["published-autobiography", "Outside competition, Belfort published an autobiography in 2012.", 4],
  ]],
  ["ufc:tom-aspinall", [
    ["martial-arts-father-andy", "Aspinall grew up in martial arts under his father and coach Andy Aspinall, a British jiu-jitsu pioneer with experience across boxing, kickboxing, judo and wrestling.", 7],
    ["jiu-jitsu-first-background", "Despite becoming known for fast heavyweight boxing, Aspinall says his original combat base was Brazilian jiu-jitsu, and he later earned a black belt under his father.", 8],
    ["blue-collar-wigan-area-upbringing", "Aspinall describes growing up in a very blue-collar area around factory workers and plumbers near Manchester/Wigan rather than in a professional-sports environment.", 7],
    ["tyson-fury-training-influence", "Aspinall trained with heavyweight boxing champion Tyson Fury earlier in his career and has named Fury, alongside his father, as an important influence on how he approaches fighting.", 9],
    ["speed-over-heavyweight-stereotype", "Aspinall has deliberately built his identity around moving and training more like a lighter fighter instead of accepting the slow, power-only stereotype of heavyweight MMA.", 10],
  ]],
  ["ufc:royce-gracie", [
    ["adult-sparring-by-fourteen", "By age 14, Gracie was already accustomed to sparring with fully grown men in the Gracie family's jiu-jitsu environment.", 11],
    ["moved-to-rorion-california-garage", "At 17, Gracie left Brazil to join his brother Rorion in Southern California, where the early American Gracie jiu-jitsu operation was run out of a small Hermosa Beach garage.", 11],
    ["chosen-as-unimposing-gracie-representative", "Royce was selected to represent the Gracie family at UFC 1 in part because his relatively ordinary, non-intimidating build would make a stronger demonstration of technique beating size.", 12],
    ["helio-never-forced-jiu-jitsu", "Gracie said his father Hélio never forced him to use jiu-jitsu competitively, instead telling his sons to learn it and choose for themselves whether to use it.", 13],
    ["ritz-crackers-ufc1-celebration", "After the first UFC tournament, Gracie's celebration was notably understated: Ritz crackers and apple juice before going to bed.", 11],
  ]],
  ["ufc:anthony-pettis", [
    ["mother-started-taekwondo-at-five", "Pettis first entered martial arts at age five because his single mother, then attending college, enrolled him and his brother in a campus taekwondo class; Pettis says he initially hated it.", 14],
    ["father-killed-when-sixteen", "Pettis' father was killed in a home-invasion robbery when Pettis was 16, leading him to step away from martial arts before eventually recommitting.", 15],
    ["showtime-nickname-from-roufus", "Duke Roufus gave Pettis the 'Showtime' nickname after an amateur bout they shared on the same card, where Pettis fought through a dislocated shoulder and won with a high kick.", 16],
    ["playground-daredevil-creativity", "Pettis traces his creative fighting instinct to being the child who always tried to one-up other kids, including jumping from higher monkey bars on the playground.", 17],
    ["brother-sergio-fighter-family", "Pettis' younger brother Sergio also became a high-level professional MMA fighter, and the brothers spent years training and competing in the same sport.", 15],
  ]],
  ["ufc:shogun-rua", [
    ["brother-ninja-inspired-start", "Rua began training at 16 after following his older brother Murilo 'Ninja' Rua to Chute Boxe; he has called Ninja the person who motivated him to become a fighter.", 18],
    ["worked-as-model", "Before fighting fully took over his life, Rua worked as a model in Brazil, including photo shoots and fashion shows for brands.", 18],
    ["chute-boxe-hard-sparring-culture", "Rua developed in Chute Boxe's famously aggressive gym culture, describing daily sparring with elite teammates as brutally hard and central to his development.", 19],
    ["japan-second-home", "Rua has referred to Japan as a second home because so much of his early international career, team history and fan connection were built there.", 20],
    ["curitiba-mma-upbringing", "Rua came up in Curitiba when the city was a major center of Brazilian MMA, with his brother Ninja and teammate Wanderlei Silva serving as examples he wanted to follow.", 21],
  ]],
  ["ufc:dan-henderson", [
    ["father-high-school-wrestling-coach", "Henderson grew up with wrestling close to home because his father was a high-school wrestling coach.", 22],
    ["two-time-greco-roman-olympian", "Henderson represented the United States in Greco-Roman wrestling at the 1992 and 1996 Olympic Games.", 22],
    ["mma-funded-third-olympic-bid", "Henderson originally treated MMA as a way to make money while continuing to chase a third Olympic wrestling team rather than as his primary career goal.", 23],
    ["randy-couture-mma-bridge", "Longtime friend and fellow wrestler Randy Couture helped draw Henderson into early mixed martial arts competition.", 23],
    ["team-quest-founder", "Henderson became one of the foundational figures behind Team Quest, the wrestling-heavy camp that became a major part of early American MMA.", 23],
  ]],
  ["ufc:amanda-nunes", [
    ["wild-child-rural-upbringing", "Nunes has described herself as an energetic, fearless child in rural Bahia, including a childhood story in which she traded for a mare and rode it despite her family's concerns.", 24],
    ["mother-put-her-in-karate", "Nunes' mother put her in karate at age seven because she had so much energy and needed a constructive outlet.", 25],
    ["sister-vanessa-bjj-bridge", "As a teenager, Nunes' older sister Vanessa helped bring her into serious jiu-jitsu training in Salvador, an important step toward her professional path.", 24],
    ["uncle-jose-alvis-fighting-influence", "Nunes has named her uncle Jose Alvis as one of her personal heroes and an early fighting influence in the family.", 25],
    ["physical-education-studies", "Nunes studied Physical Education before leaving that path to move to the United States and train full time.", 25],
  ]],
  ["ufc:joanna-jedrzejczyk", [
    ["basketball-before-muay-thai", "Before becoming a combat-sports athlete, Jedrzejczyk played basketball.", 26],
    ["sisters-boyfriend-muay-thai-invitation", "Jedrzejczyk discovered Muay Thai after her twin sister's boyfriend invited her to join them for a class.", 26],
    ["self-funded-muay-thai-travel", "During her elite Muay Thai years, Jedrzejczyk often lost money competing internationally, paying travel costs herself to represent Poland at world championships.", 27],
    ["physical-education-education", "Jedrzejczyk studied Physical Education.", 28],
    ["small-business-with-mother", "Alongside fighting, Jedrzejczyk has said she had a small business with her mother.", 28],
  ]],
] as const;
