// PR10 UFC person-identity research data batch 1. Canonical validation and lookup remain in ufcPersonIdentityKnowledge.ts.
export const ufcPersonIdentityResearchSources1 = [
  ["https://www.ufc.com/athlete/jon-jones", "UFC", "Jon Jones | UFC"],
  ["https://www.ufc.com/athlete/jon-jones?language_content_entity=en&page=1", "UFC", "Jon Jones | UFC"],
  ["https://www.onefc.com/features/the-untold-origins-of-demetrious-mighty-mouse-johnson/", "ONE Championship", "The Untold Origins Of Demetrious 'Mighty Mouse' Johnson"],
  ["https://www.ufc.com/news/demetrious-johnson-talks-kyoji-horiguchi-americas-pregame", "UFC", "Demetrious Johnson Talks Kyoji Horiguchi, America's Pregame"],
  ["https://www.ufc.com/news/demetrious-johnson-hard-work-pays", "UFC", "Demetrious Johnson: Hard Work Pays"],
  ["https://www.seattlemet.com/news-and-city-life/2013/07/demetrious-johnson-isnt-as-little-as-he-looks-july-2013", "Seattle Met", "Demetrious Johnson Isn't as Little as He Looks"],
  ["https://www.gameinformer.com/b/features/archive/2017/10/08/ufc-flyweight-champ-demetrious-johnson-talks-streaming-and.aspx", "Game Informer", "UFC Flyweight Champ Demetrious Johnson Talks Streaming And Gaming"],
  ["https://www.ufc.com/news/making-khabib-nurmagomedov", "UFC", "The Making Of Khabib Nurmagomedov"],
  ["https://www.espn.co.uk/blog/mma/post/_/id/22318/nurmagomedov-brothers-talk-unique-upbringing-us-debut", "ESPN", "Nurmagomedov 'brothers' talk unique upbringing, US debut"],
  ["https://www.ufc.com/news/khabib-eagle-nurmagomedov-named-ufc-hall-fame-class-2022", "UFC", "Khabib 'The Eagle' Nurmagomedov Named to UFC Hall of Fame Class of 2022"],
  ["https://www.ufc.com/news/coach-khabib-spotlight-ufc-311-islam-makhachev-umar-nurmagomedov-tagir-ulanbekov", "UFC", "Coach Khabib Spotlight | UFC 311"],
  ["https://www.ufc.com/news/max-holloway-diamond-paradise", "UFC", "Max Holloway: A Diamond in 'Paradise'"],
  ["https://www.ufc.com/athlete/max-holloway?page=2", "UFC", "Max Holloway | UFC"],
  ["https://www.ufc.com/news/max-holloway-expects-performance-lifetime-co-main-ufc-276", "UFC", "Max Holloway Expects The 'Performance Of A Lifetime'"],
  ["https://www.war.gov/News/Feature-Stories/Story/Article/3619215/sports-heroes-who-served-champion-wrestler-actor-was-also-a-soldier/", "U.S. Department of Defense", "Sports Heroes Who Served: Champion Wrestler, Actor Was Also a Soldier"],
  ["https://sports.yahoo.com/randy-couture-explains-origin-natural-135052584.html", "MMA Junkie / Yahoo Sports", "Randy Couture explains origin of 'The Natural' and 'Captain America' nicknames"],
  ["https://www.ufc.com/news/history-ufc-fighters-movies-and-television-conor-mcgregor-road-house", "UFC", "The History Of UFC Fighters In Movies And Television"],
  ["https://www.ufc.com/athlete/alex-pereira", "UFC", "Alex Pereira | UFC"],
  ["https://www.mmafighting.com/2023/4/8/23672500/racism-alcohol-rituals-fights-alex-pereira-mentor-poatan-israel-adesanya-ufc-287", "MMA Fighting", "Racism, alcohol, rituals, fights: Alex Pereira's mentor opens up on Poatan's journey"],
  ["https://www.ufc.com/news/aline-pereira-ready-make-alex-pereira-splash-ufc-fight-pass", "UFC", "Aline Pereira Ready To Make An Alex Pereira-Like Splash | UFC Fight Pass"],
  ["https://www.ufc.com/news/dillashaw-visits-raiders-headquarters-road-ufc-177", "UFC", "Dillashaw Visits Raiders Headquarters on Road to UFC 177"],
  ["https://www.ufc.com/athlete/tj-dillashaw", "UFC", "TJ Dillashaw | UFC"],
  ["https://www.ufc.com/news/dillashaw-sets-training-camps-colorado", "UFC", "Dillashaw sets up training camps in Colorado"],
  ["https://espnpressroom.com/feature/three-things-to-know-about-the-making-of-espn-cover-story-francis-ngannou/", "ESPN Press Room", "Three Things to Know About the Making of ESPN Cover Story: Francis Ngannou"],
  ["https://www.espn.com/espn/feature/story/_/id/33100543/francis-ngannou-miraculous-journey-ufc-stardom", "ESPN", "Francis Ngannou's Miraculous Journey"],
  ["https://www.ufc.com/news/ufc-francis-ngannou-laying-foundation-his-people-cameroon", "UFC", "Ngannou Laying A Foundation For His People"],
  ["https://www.ufc.com/athlete/aljamain-sterling", "UFC", "Aljamain Sterling | UFC"],
  ["https://www.espn.com/mma/story/_/id/29133514/ufc-274-justin-gaethje-journey-mining-town-mma-stardom", "ESPN", "Inside Justin Gaethje's journey from a mining town to MMA stardom"],
  ["https://us.ufcespanol.com/athlete/justin-gaethje", "UFC", "Justin Gaethje | UFC"],
  ["https://www.sherdog.com/news/news/Justin-Gaethje-Reveals-Origins-of-The-Highlight-Nickname-199769", "Sherdog", "Justin Gaethje Reveals Origins of 'The Highlight' Nickname"],
  ["https://www.ufc.com/news/dustin-poiriers-education-through-fire", "UFC", "Dustin Poirier's Education Through Fire"],
  ["https://www.ufc.com/news/shine-diamond-poirier", "UFC", "Shine On, 'Diamond' Poirier"],
  ["https://www.ufc.com/news/dustin-poirier-the-good-fight-foundation", "UFC", "Dustin Poirier Dedicated To 'The Good Fight'"],
  ["https://www.ufc.com/athlete/dustin-poirier", "UFC", "Dustin Poirier | UFC"],
  ["https://www.ufc.com/news/ufc-and-mma-fan-favorite-dustin-diamond-poirier-announce-marketing-partnership-ufc-281?language_content_entity=en", "UFC", "UFC And MMA Fan Favorite Dustin 'The Diamond' Poirier Announce Marketing Partnership"],
  ["https://www.ufc.com/news/ortiz-chronicles-early-years", "UFC", "Ortiz Chronicles: Early Years"],
  ["https://www.ufc.com/news/origins-champ-tito-ortiz?language_content_entity=en", "UFC", "Origins of a Champ: Tito Ortiz"],
  ["https://www.ufc.com/news/robbie-lawler-his-own-words", "UFC", "Robbie Lawler: In His Own Words"],
  ["https://www.ufc.com/news/robbie-lawler-named-ufc-hall-fame-class-2025", "UFC", "Robbie Lawler Named to UFC Hall of Fame Class of 2025"],
  ["https://www.ufc.com/news/rob-ruthless-coaching-journey", "UFC", "Rob to Ruthless - A Coaching Journey"],
  ["https://www.ufc.com/news/henry-cejudo-enters-national-wrestling-hall-fame-saturday", "UFC", "Henry Cejudo enters the National Wrestling Hall of Fame Saturday"],
  ["https://www.ufc.com/athlete/henry-cejudo", "UFC", "Henry Cejudo | UFC"],
  ["https://www.teamusa.com/profiles/henry-cejudo", "Team USA", "Henry Cejudo | Team USA"],
  ["https://www.ufc.com/news/henry-cejudo-triple-c-last-dance-ufc-323", "UFC", "Henry Cejudo | Triple C's Last Dance"],
  ["https://www.ufc.com/athlete/petr-yan?page=1", "UFC", "Petr Yan | UFC"],
  ["https://www.ufc.com/news/yan-lives-his-nickname", "UFC", "Yan Lives Up To His Nickname"],
  ["https://www.espn.com/mma/story/_/id/30752895/ufc-257-party-j-lo-dinner-bono-stories-conor-mcgregor", "ESPN", "UFC 257: Party with J.Lo, dinner with Bono and other stories of Conor McGregor"],
  ["https://shop.conormcgregor.com/pages/about-conor", "Conor McGregor", "About Conor"],
  ["https://us.ufcespanol.com/news/flashback-making-mcgregor", "UFC", "Flashback: Making McGregor"],
  ["https://www.mmafighting.com/ufc/495077/conor-mcgregor-explains-backstory-behind-notorious-nickname", "MMA Fighting", "Conor McGregor explains backstory behind 'Notorious' nickname"],
  ["https://www.ufc.com/news/complete-machida", "UFC", "The Complete Machida"],
  ["https://www.ufc.com/athlete/dricus-du-plessis?language_content_entity=en", "UFC", "Dricus Du Plessis | UFC"],
  ["https://www.ufc.com/athlete/khamzat-chimaev", "UFC", "Khamzat Chimaev | UFC"],
  ["https://kr.ufc.com/athlete/khamzat-chimaev?page=1", "UFC", "Khamzat Chimaev | UFC"],
  ["https://www.ufc.com/news/sean-omalley-fighting-to-be-the-best-ufc-250", "UFC", "Sean O'Malley Fighting To Be The Best"],
  ["https://www.montanasports.com/more-sports/molded-who-i-was-sean-omalley-credits-growing-up-in-montana-as-huge-role-in-ufc-success", "MTN Sports", "Sean O'Malley credits growing up in Montana as 'huge role' in UFC success"],
  ["https://www.bbc.co.uk/sport/mixed-martial-arts/53763265", "BBC Sport", "UFC 252: Sean O'Malley on his dog, his colourful hair and fighting"],
  ["https://www.espn.com/mma/ufc/story/_/id/28809373/facial-tattoos-smoking-snoop-meet-star-fighter-sean-omalley", "ESPN", "UFC 248: Facial tattoos, smoking with Snoop ... meet star fighter Sean O'Malley"],
  ["https://www.ufc.com/news/flashback-forrest-griffins-new-reality", "UFC", "Flashback: Forrest Griffin's New Reality"],
  ["https://www.ufc.com/news/griffin-bonnar-night-changed-everything?language_content_entity=en", "UFC", "Griffin, Bonnar and the Night that Changed Everything"],
  ["https://www.ufc.com/news/ufc-25-forrest-griffin", "UFC", "UFC 25: Forrest Griffin"],
  ["https://www.ufc.com/news/forrest-griffin-he-did-it-his-way", "UFC", "Forrest Griffin: He Did It His Way"],
  ["https://www.ufc.com/news/outside-octagon-there-will-only-be-one-chael-sonnen", "UFC", "Outside the Octagon: There Will Only Be One Chael Sonnen"],
  ["https://www.ufc.com/news/chael-says-quotables-mmas-most-interesting-man-0", "UFC", "Chael Says: Quotables from MMA's Most Interesting Man"],
  ["https://www.themat.com/news/2016/february/24/bp32-chael-sonnen", "USA Wrestling", "BP32: Chael Sonnen"],
  ["https://www.ufc.com/news/sonnen-says-words-wisdom", "UFC", "Sonnen Says – Words of Wisdom"],
  ["https://www.mmafighting.com/2014/9/5/6108945/morning-report-ufc-chael-sonnen-wanderlei-silva-dana-white-overeem-jacare-king-mo-mma-news", "MMA Fighting", "Morning Report: Chael Sonnen and the 'American Gangster' moniker"],
  ["https://www.ufc.com/news/shevchenko-hoping-take-fast-lane-title-shot", "UFC", "Shevchenko hoping to take fast lane to title shot"],
  ["https://www.mmafighting.com/2019/6/7/18650518/valentina-shevchenko-a-woman-of-many-nations-ahead-of-first-ufc-title-defense", "MMA Fighting", "Valentina Shevchenko, a woman of many nations ahead of first UFC title defense"],
  ["https://www.ufc.com/athlete/valentina-shevchenko?language_content_entity=en", "UFC", "Valentina Shevchenko | UFC"],
  ["https://www.ufc.com/news/antonina-shevchenko-family-business", "UFC", "Antonina Shevchenko: Family Business"],
  ["https://www.ufc.com/athlete/rose-namajunas", "UFC", "Rose Namajunas | UFC"],
  ["https://www.mmafighting.com/2019/5/6/18534776/ufc-237-embedded-episode-1-dont-put-drinks-on-the-piano", "MMA Fighting", "UFC 237 Embedded, Episode 1: Don't put drinks on the piano"],
  ["https://www.ufc.com/news/rose-namajunas-one-win-away", "UFC", "Rose Namajunas: One Win Away"],
  ["https://www.ufc.com/news/defined-her-courage-cyborg-protects-undefeated-streak", "UFC", "Defined by her courage, Cyborg protects undefeated streak"],
  ["https://www.ufc.com/news/cyborg-ready-place-amongst-ufc-legends", "UFC", "Cyborg ready for place amongst UFC legends"],
  ["https://www.ufc.com/news/cyborg-one-greatest-all-time-looks-add-legacy-vs-holm", "UFC", "Cyborg, one of the greatest of all time, looks to add to legacy vs Holm"],
  ["https://www.ufc.com/athlete/kayla-harrison", "UFC", "Kayla Harrison | UFC"],
  ["https://www.ufc.com/news/tates-journey-bottom-could-reach-top-ufc-196", "UFC", "Tate's journey from bottom could reach top at UFC 196"],
  ["https://www.ufc.com/athlete/miesha-tate", "UFC", "Miesha Tate | UFC"],
  ["https://www.ufc.com/news/miesha-tate-having-champions-heart", "UFC", "Miesha Tate on Having a Champion's Heart"],
  ["https://www.ufc.com/news/miesha-tate-cupcake-nickname-only", "UFC", "Miesha Tate: Cupcake Nickname Only"],
  ["https://www.ufc.com/news/jorge-masvidal-gamebred-journey-his-miami-homecoming-ufc-287", "UFC", "Jorge Masvidal's Journey To His Miami Homecoming"],
  ["https://www.espn.com/mma/story/_/id/27931280/from-miami-brawler-ufc-star-jorge-masvidal-always-bmf", "ESPN", "From Miami brawler to UFC star, Jorge Masvidal was always 'Gamebred'"],
  ["https://www.ufc.com/news/masvidal-de-la-calle-la-jaula", "UFC", "Masvidal: De la calle a la jaula"],
  ["https://www.ufc.com/news/jorge-masvidal-exclamation-point", "UFC", "Jorge Masvidal: The Exclamation Point"],
  ["https://www.ufc.com/news/dana-white-announces-michael-chandler-signing-ufc-254-backup", "UFC", "Dana White Announces Michael Chandler Signing"],
  ["https://www.ufc.com/athlete/michael-chandler?language_content_entity=en", "UFC", "Michael Chandler | UFC"],
  ["https://mutigers.com/sports/wrestling/roster/season/2007-08/player/michael-chandler", "University of Missouri Athletics", "Michael Chandler - Wrestling"],
  ["https://www.espn.com/mma/story/_/id/25456207/the-two-lives-brian-ortega-menacing-streets-ufc-stardom", "ESPN", "The two lives of Brian Ortega: From menacing streets to UFC stardom"],
  ["https://www.ufc.com/news/brian-ortega-big-name-hunter", "UFC", "Brian Ortega: Big Name Hunter"],
  ["https://www.espn.com/general/story?id=22619156&src=desktop", "ESPN", "Brian Ortega's path from San Pedro to UFC title contender"],
  ["https://www.ufc.com/news/ortega-happy-showcase-all-skills-ufc-195", "UFC", "Ortega happy to showcase all skills at UFC 195"],
  ["https://www.cbssports.com/mma/news/ufc-265-ciryl-gane-takes-unusual-path-to-reach-his-potential-greatness-against-derrick-lewis-in-houston/", "CBS Sports", "UFC 265: Ciryl Gane takes unusual path to reach his potential greatness"],
  ["https://www.ufc.com/athlete/ciryl-gane?language_content_entity=en", "UFC", "Ciryl Gane | UFC"],
  ["https://www.espn.com/mma/story/_/id/33102899/ufc-270-one-gym-paris-launched-careers-francis-ngannou-ciryl-gane-coach-rift-made-rivals", "ESPN", "One gym in Paris launched the careers of Francis Ngannou and Ciryl Gane"],
  ["https://www.ufc.com/node/68808", "UFC", "Team Werdum: Marlon 'Chito' Vera"],
  ["https://www.ufc.com/news/vera-fighting-daughters-chance-smile", "UFC", "Vera fighting for daughter's chance at a smile"],
  ["https://www.expreso.ec/deportes/conoce-marlon-vera-chito-ecuador-192366.html", "Expreso", "¿Por qué se lo conoce a Marlon Vera como 'Chito'?"],
  ["https://www.ufc.com/news/marlon-vera-hungrier-ever", "UFC", "Marlon Vera Is Hungrier Than Ever Before"],
  ["https://stonybrookathletics.com/honors/hall-of-fame/dominick-reyes/108", "Stony Brook Athletics", "Dominick Reyes - Hall of Fame"],
  ["https://kr.ufc.com/athlete/dominick-reyes", "UFC", "Dominick Reyes | UFC"],
  ["https://www.ufcespanol.com/athlete/dominick-reyes", "UFC", "Dominick Reyes | UFC"],
  ["https://www.espn.com/mma/story/_/id/28740668/dan-hooker-home-ufc-fight-night-auckland-headline-act", "ESPN", "Dan Hooker at home for UFC Fight Night Auckland headline act"],
  ["https://www.ufc.com/athlete/dan-hooker?language_content_entity=en", "UFC", "Dan Hooker | UFC"],
] as const;

export const ufcPersonIdentityResearch1 = [
  [
    "ufc:jon-jones",
    [
      ["mma-start-unexpected-child", "Jones has said he began training MMA in 2007 after learning he had an unexpected child while in college and needing to earn money.", 0],
      ["iowa-central-wrestling-and-degree", "At Iowa Central Community College, Jones won a JUCO national wrestling championship and earned an associate degree.", 0],
      ["nfl-brothers-arthur-and-chandler", "Jones comes from an unusually athletic family: his brothers Arthur and Chandler Jones both played in the NFL.", 1],
      ["youtube-technique-study", "Jones told UFC that he used YouTube to study and pick up unconventional techniques early in his MMA development.", 1],
      ["robbery-intervention-title-day", "On the day he fought Mauricio Rua for the light heavyweight title in 2011, Jones and his coaches chased down a man they saw breaking into a car and helped detain him until police arrived.", 1],
    ],
  ],
  [
    "ufc:demetrious-johnson",
    [
      ["wrestling-accountability-origin", "Johnson first tried wrestling at 13 and has said he was drawn to the sport's individual accountability.", 2],
      ["tacoma-recycling-warehouse-job", "Before fighting full time, Johnson worked an early shift at a Tacoma-area warehouse recycling paper into shipping boards used for televisions.", 3],
      ["matt-hume-longtime-mentor", "Johnson linked up with coach Matt Hume and AMC Pankration in 2005, forming one of the defining long-term coach-fighter relationships of his career.", 4],
      ["mighty-mouse-nickname-origin", "The 'Mighty Mouse' nickname came from a coach because Johnson was the smallest athlete in the gym but was willing to spar with anyone.", 5],
      ["lifelong-gamer-and-streamer", "Johnson is a lifelong video-game fan who later became a serious Twitch streamer, tracing the hobby back to playing games such as Super Contra with his mother.", 6],
    ],
  ],
  [
    "ufc:khabib-nurmagomedov",
    [
      ["father-school-before-fighting", "Khabib has described how his father Abdulmanap initially emphasized education before recognizing his fighting potential and taking a more direct role in training him.", 7],
      ["sixteen-boy-training-household", "During his youth, Khabib was part of an unusually communal training environment in which a large group of boys lived and trained together year-round in Makhachkala under Abdulmanap Nurmagomedov's system.", 8],
      ["combat-sambo-world-champion", "Before his UFC career, Khabib became a two-time Combat Sambo world champion after developing across wrestling, judo and sambo.", 9],
      ["post-retirement-coaching-role", "After retiring from competition, Khabib moved into a coaching and mentoring role for teammates including Islam Makhachev and Umar Nurmagomedov.", 10],
      ["eagle-fighting-championship-owner", "Khabib also became an MMA promoter after retirement, serving as owner of Eagle Fighting Championship.", 9],
    ],
  ],
  [
    "ufc:max-holloway",
    [
      ["waianae-upbringing-and-representation", "Holloway has made representing Waianae, on Oahu, central to his identity, saying the area's negative stereotypes motivated him to show that successful people could come from his hometown.", 11],
      ["josh-keanu-speedbag-gym-origin", "Friend Josh Keanu helped bring Holloway into formal training after a trainer noticed Holloway's natural ability while he was working a speed bag.", 12],
      ["blessed-nickname-origin", "The nickname 'Blessed' stuck after a coach remarked that Holloway was blessed because of how quickly he had progressed and accomplished things in fighting.", 12],
      ["handyman-before-fighting", "Holloway has listed working as a handyman among his jobs before fighting became his profession.", 12],
      ["mini-blessed-son-rush", "Holloway's son Rush, often called 'Mini Blessed,' has long been a visible part of his fight life and a major source of motivation for him.", 13],
    ],
  ],
  [
    "ufc:randy-couture",
    [
      ["army-101st-airborne-service", "Couture served in the U.S. Army from 1982 to 1988, including service with the 101st Airborne Division, and reached the rank of sergeant.", 14],
      ["olympic-alternate-wrestling-background", "Before MMA, Couture was a high-level Greco-Roman wrestler who became a three-time U.S. Olympic team alternate and also wrestled at Oklahoma State.", 14],
      ["the-natural-nickname-origin", "Couture has explained that 'The Natural' was coined by a Full Contact Fighter editor after his early upset of Vitor Belfort, reflecting how naturally he adapted to MMA.", 15],
      ["expendables-acting-career", "Couture built a substantial acting career after becoming an MMA star, most notably playing Toll Road in the Expendables film series.", 16],
      ["gi-foundation-wounded-veterans", "Couture created the Xtreme Couture GI Foundation to support wounded U.S. service members and their families.", 14],
    ],
  ],
  [
    "ufc:alex-pereira",
    [
      ["kickboxing-to-escape-alcohol", "Pereira has said he began kickboxing in 2009 as part of changing his life and getting away from alcohol.", 17],
      ["tire-repair-shop-job", "Before his fighting career, Pereira worked in a tire repair shop.", 17],
      ["glory-simultaneous-two-division-champion", "In kickboxing, Pereira became the first GLORY athlete to hold the promotion's middleweight and light heavyweight titles simultaneously.", 17],
      ["poatan-indigenous-name-origin", "Pereira's mentor Belocqua Wera gave him the name 'Poatan,' a Tupi-Guarani name that Wera described as meaning hands as hard as rocks and used to reconnect Pereira with Indigenous heritage.", 18],
      ["fighter-sister-aline-pereira", "Pereira's younger sister Aline Pereira also became a professional combat-sports athlete, competing in kickboxing, MMA and Karate Combat.", 19],
    ],
  ],
  [
    "ufc:tj-dillashaw",
    [
      ["raiders-family-and-football-background", "Dillashaw grew up in a devoted Raiders family and played football in Pop Warner and high school, lining up at running back, cornerback and linebacker before focusing on wrestling.", 20],
      ["cal-state-kinesiology-degree", "Dillashaw wrestled at Cal State Fullerton and earned a degree in kinesiology with an emphasis in clinical exercise science.", 21],
      ["mma-after-college-wrestling", "After college wrestling ended without the goals he wanted, Dillashaw turned to MMA because he still wanted a competitive outlet.", 21],
      ["ultimate-fighter-team-bisping", "Dillashaw entered the UFC through season 14 of The Ultimate Fighter as a member of Team Bisping.", 21],
      ["duane-ludwig-colorado-move", "A defining coaching relationship with Duane Ludwig eventually led Dillashaw to leave Team Alpha Male and base major training camps in Colorado with Ludwig.", 22],
    ],
  ],
  [
    "ufc:francis-ngannou",
    [
      ["cameroon-sand-mine-childhood", "Ngannou began working in a sand mine in Cameroon at about nine years old.", 23],
      ["fourteen-month-migration-seventh-crossing", "Ngannou's journey from Cameroon toward Europe lasted roughly 14 months, and he ultimately crossed the Strait of Gibraltar on his seventh attempt.", 24],
      ["american-boy-childhood-dream", "As a child in Cameroon, Ngannou called himself the 'American Boy,' with his image of the United States shaped partly by dubbed American television such as Knight Rider.", 24],
      ["boxing-dream-to-mma-factory-pivot", "Ngannou arrived in Paris determined to become a boxer like Mike Tyson and initially resisted MMA; Didier Carmont eventually persuaded him to try Fernand Lopez's MMA Factory when his boxing gym closed temporarily.", 24],
      ["cameroon-foundation-first-mma-gym", "Through the Francis Ngannou Foundation, he later opened what UFC described as the first MMA gym in Cameroon to give local children training and educational opportunities.", 25],
    ],
  ],
  [
    "ufc:aljamain-sterling",
    [
      ["funk-master-nickname-origin", "Sterling's 'Funk Master' identity grew out of the unconventional, scrambling style he developed as a wrestler.", 26],
      ["division-three-all-american-wrestler", "Sterling became a two-time NCAA Division III All-American wrestler at SUNY Cortland.", 26],
      ["physical-education-degree", "After initially studying accounting at SUNY Morrisville, Sterling transferred to SUNY Cortland and earned a bachelor's degree in physical education.", 26],
      ["saks-shoes-and-haircuts", "Before fighting full time, Sterling sold shoes at Saks Fifth Avenue and later cut hair at school to help make money.", 26],
      ["matt-serra-bjj-black-belt", "Sterling earned his Brazilian jiu-jitsu black belt under former UFC champion Matt Serra.", 26],
    ],
  ],
  [
    "ufc:justin-gaethje",
    [
      ["morenci-copper-mining-family", "Gaethje grew up in the Arizona mining town of Morenci in a family deeply tied to the local copper mine; his father spent decades there, and Gaethje himself worked a summer in the mine at 18.", 27],
      ["northern-colorado-all-american-wrestler", "Before MMA, Gaethje wrestled at the University of Northern Colorado and became an NCAA Division I All-American.", 28],
      ["human-services-college-studies", "Gaethje studied human services in college and has said he came close to completing the degree.", 28],
      ["demolition-painting-bouncer-jobs", "His pre-fighting work included demolition, painting and bouncing.", 28],
      ["highlight-nickname-wrestling-slams", "Gaethje has explained that 'The Highlight' nickname predates his reputation as a striker and was originally tied to the highlight-reel slams he produced as a wrestler.", 29],
    ],
  ],
  [
    "ufc:dustin-poirier",
    [
      ["ninth-grade-dropout-and-juvenile-detention", "Poirier left school in the ninth grade and has spoken openly about spending time in juvenile detention before finding direction through fighting.", 30],
      ["fightville-documentary-subject", "Poirier's early professional rise in Louisiana was prominently documented in the 2011 documentary Fightville.", 31],
      ["good-fight-foundation-gear-auctions", "Poirier and his wife Jolie built The Good Fight Foundation from the idea of auctioning his fight-worn gear and directing the proceeds to community causes.", 32],
      ["diamond-nickname-tim-credeur", "Poirier has credited longtime Louisiana coach Tim Credeur with giving him 'The Diamond' nickname during his WEC-era development.", 33],
      ["louisiana-hot-sauce-and-cajun-roots", "Poirier built Poirier's Louisiana Style hot sauce around the Cajun flavors he grew up with in Lafayette, and it later became the UFC's first official hot-sauce partner.", 34],
    ],
  ],
  [
    "ufc:tito-ortiz",
    [
      ["ufc-one-royce-gracie-inspiration", "Ortiz has described watching the first UFC, especially Royce Gracie, as a major spark that made the new sport feel attainable to him.", 35],
      ["tank-abbott-training-connection", "Before becoming a UFC name himself, Ortiz gained early no-holds-barred experience by training with fellow Huntington Beach fighter Tank Abbott.", 35],
      ["golden-west-wrestling-scholarship", "Ortiz rebuilt his wrestling path at Golden West College, where he earned a scholarship and developed into a standout collegiate wrestler.", 36],
      ["ufc-thirteen-no-prize-money", "For his UFC 13 appearance, Ortiz competed without accepting prize money in order to preserve his college wrestling eligibility.", 36],
      ["adult-novelty-store-job", "Ortiz worked at an adult novelty store while trying to support himself before his fighting career took off.", 35],
    ],
  ],
  [
    "ufc:robbie-lawler",
    [
      ["father-started-martial-arts-after-brother", "Lawler has said his father put him into martial arts after seeing how much Robbie wanted to compete with an older brother who regularly got the better of him.", 37],
      ["third-grade-weightlifting", "Lawler says he began lifting weights as early as third grade, an unusual childhood habit he later connected to developing his natural punching power.", 37],
      ["san-diego-to-iowa-athletic-upbringing", "Lawler moved from San Diego to Bettendorf, Iowa as a child and later competed in both wrestling and football there.", 38],
      ["miletich-gym-at-sixteen", "At 16, Lawler began training at Pat Miletich's gym, placing him inside one of the defining early American MMA teams while he was still in high school.", 39],
      ["matt-pena-longtime-corner", "Coach Matt Pena became one of Lawler's longest-running corner relationships, working dozens of his professional fights.", 39],
    ],
  ],
  [
    "ufc:henry-cejudo",
    [
      ["phoenix-poverty-upbringing", "Cejudo has described growing up in a low-income, welfare-dependent household in Phoenix where basic necessities could be difficult to secure.", 40],
      ["youngest-us-freestyle-olympic-gold", "At 21, Cejudo became the youngest American wrestler at the time to win an Olympic freestyle wrestling gold medal.", 40],
      ["arizona-bronze-gloves-boxing", "Cejudo also competed in amateur boxing and won an Arizona Bronze Gloves championship before fully committing to MMA.", 41],
      ["older-brother-angel-wrestling-influence", "His older brother Angel Cejudo was a nationally ranked freestyle wrestler and an important influence on Henry's path into elite wrestling.", 42],
      ["triple-c-nickname-origin", "The 'Triple C' persona grew from Cejudo combining his Olympic gold-medal identity with his status as UFC champion in two divisions.", 43],
    ],
  ],
  [
    "ufc:petr-yan",
    [
      ["boxing-at-thirteen-to-mma", "Yan began boxing at 13 and did not transition into MMA until roughly seven years later.", 44],
      ["three-sessions-per-day-routine", "Yan has described a three-session daily training structure: strength and conditioning in the morning, sparring in the afternoon, and technical drilling in the evening.", 44],
      ["youth-boxing-trainer-education", "Yan spent five years at an athletic institute and specialized in training to become a youth boxing coach.", 44],
      ["part-time-security-jobs", "Before fighting became his profession, Yan worked part-time security jobs.", 44],
      ["no-mercy-nickname-mindset", "Yan chose 'No Mercy' to describe the mindset and opportunistic finishing style he wants to carry into each fight.", 45],
    ],
  ],
  [
    "ufc:conor-mcgregor",
    [
      ["crumlin-boxing-after-football", "McGregor played football as a boy before gravitating toward boxing and entering Crumlin Boxing Club around age 10.", 46],
      ["plumber-apprenticeship", "Before committing fully to fighting, McGregor worked as a plumber's apprentice in Dublin.", 47],
      ["john-kavanagh-sbg-commitment-pivot", "McGregor's relationship with John Kavanagh at SBG Ireland became decisive when Kavanagh pushed him to stop drifting and commit seriously to training.", 48],
      ["notorious-nickname-origin", "McGregor has tied 'The Notorious' nickname to his reputation for getting into trouble when he was younger and to his admiration for rapper The Notorious B.I.G.", 49],
      ["proper-no-twelve-cofounder", "Outside fighting, McGregor co-founded the Proper No. Twelve Irish whiskey brand in 2018.", 47],
    ],
  ],
  [
    "ufc:lyoto-machida",
    [
      ["shotokan-with-father-from-age-three", "Machida began Shotokan karate at age three under his father Yoshizo, a karate master, and kept that art as the foundation of his fighting style.", 50],
      ["five-thirty-discipline-training", "His father deliberately scheduled 5:30 a.m. karate sessions as a lesson in discipline, a routine Machida continued for years.", 50],
      ["karate-core-in-mma", "Even after branching into MMA, Machida deliberately preserved Shotokan distance, timing and movement as the core of his style rather than abandoning it for a more conventional MMA stance.", 50],
      ["sumo-and-jiu-jitsu-cross-training", "Machida also competed and trained in sumo and began Brazilian jiu-jitsu at 15, adding those arts around his karate base.", 50],
      ["physical-education-degree", "Machida completed a college degree in physical education while pursuing combat-sports training.", 50],
    ],
  ],
  [
    "ufc:dricus-du-plessis",
    [
      ["judo-wrestling-kickboxing-childhood", "Du Plessis' martial-arts path moved from judo as a child to wrestling and then K-1 kickboxing as a teenager before MMA.", 51],
      ["teenage-south-african-wako-champion", "As a teenager, du Plessis became a South African WAKO K-1 world champion before moving into MMA.", 51],
      ["stillknocks-nickname-brother-origin", "Du Plessis has credited his brother with the 'Stillknocks' nickname, a reference to his knockout-heavy amateur kickboxing run.", 51],
      ["agricultural-economics-final-year-dropout", "Du Plessis studied agricultural economics at the University of Pretoria but left in his final year when an EFC title opportunity convinced him to pursue fighting full time.", 51],
      ["professional-fighter-only-career", "Du Plessis has said he never had a separate conventional job after school because professional fighting became his full-time career.", 51],
    ],
  ],
  [
    "ufc:khamzat-chimaev",
    [
      ["chechnya-to-sweden-wrestling", "Chimaev wrestled from a young age and continued the sport after moving from Chechnya to Sweden.", 52],
      ["hotel-gift-card-allstars-origin", "After winning a hotel gift card through a wrestling event, Chimaev visited Stockholm, tried training at Allstars Training Center and soon rearranged his life around MMA.", 52],
      ["poultry-factory-and-security-jobs", "Before fighting full time, Chimaev worked at a poultry factory in Kalmar and later in security in Stockholm.", 52],
      ["five-am-jog-training-routine", "Chimaev has described beginning a typical training day with a 5 a.m. jog, sleeping again briefly, then returning for team practice later in the morning.", 53],
      ["borz-means-wolf", "His nickname 'Borz' means 'wolf' in Chechen.", 52],
    ],
  ],
  [
    "ufc:sean-omalley",
    [
      ["helena-montana-first-coach", "O'Malley grew up in Helena, Montana and has credited first MMA coach Johnny Aho with giving him unusually strong belief in his potential.", 54],
      ["nfl-dream-before-fighting", "Before discovering fighting at 16, O'Malley says he dreamed of reaching the NFL but realized his slight teenage build made that path unrealistic.", 55],
      ["sugar-nickname-sweet-to-watch", "The nickname 'Sugar' came from an early coach who thought O'Malley's striking was 'sweet' to watch.", 56],
      ["fight-week-colorful-hair-tradition", "O'Malley made bright, fight-specific hair colors part of his visual identity, at times using an opponent's national colors and even matching his dog's dyed fur.", 56],
      ["snoop-dogg-contender-series-connection", "After O'Malley's breakout Contender Series knockout, Snoop Dogg became part of the viral moment and later met O'Malley, an association that helped amplify his early UFC-era celebrity.", 57],
    ],
  ],
  [
    "ufc:forrest-griffin",
    [
      ["university-police-officer", "Before becoming a full-time fighter, Griffin worked as a university police officer in Georgia.", 58],
      ["mma-hobby-dan-severn-first-pro", "Griffin treated MMA as a side pursuit while working, and his first professional fight was against veteran Dan Severn for only a small purse.", 58],
      ["tuf-one-bonnar-mainstream-breakthrough", "Griffin's 2005 Ultimate Fighter finale with Stephan Bonnar became one of the defining mainstream breakthrough moments in UFC history and helped secure the show's future on television.", 59],
      ["two-new-york-times-bestsellers", "Griffin later became the author of two New York Times bestselling books.", 60],
      ["xacto-self-stitch-removal", "A famous example of Griffin's self-deprecating, rough-edged personality was his account of removing his own stitches with an X-Acto knife after the Bonnar fight.", 61],
    ],
  ],
  [
    "ufc:chael-sonnen",
    [
      ["realtor-and-political-ambitions", "Outside fighting, Sonnen worked in real estate and also pursued political ambitions in Oregon.", 62],
      ["oregon-sociology-business-education", "Sonnen attended the University of Oregon, majoring in sociology and minoring in business.", 63],
      ["ncaa-and-greco-roman-wrestling", "Before MMA, Sonnen was an NCAA Division I All-American wrestler and also competed at a high level in Greco-Roman wrestling.", 64],
      ["fighting-as-hobby-philosophy", "Sonnen repeatedly described professional fighting as a 'hobby' rather than a job, arguing that he wanted his primary work to provide a conventional good or service to the community.", 65],
      ["american-gangster-persona-origin", "Sonnen leaned into the 'American Gangster' moniker as part of the deliberately provocative persona he developed around his fighting career.", 66],
    ],
  ],
  [
    "ufc:valentina-shevchenko",
    [
      ["martial-arts-family-start-age-five", "Shevchenko began martial arts at five in a family already immersed in combat sports; her mother Elena practiced taekwondo and helped lead the Kyrgyz Muay Thai federation.", 67],
      ["peru-eight-year-home", "Shevchenko lived in Peru for years, learned Spanish and came to represent Peru alongside Kyrgyzstan as a major part of her public identity.", 68],
      ["film-directing-degree", "Shevchenko earned an undergraduate degree in film directing from the University of Arts in Kyrgyzstan.", 69],
      ["lifelong-dance-training", "Shevchenko studied dance from a young age and has described dance as a complementary discipline that sharpened her body control.", 67],
      ["fighter-sister-antonina", "Her older sister Antonina Shevchenko also became a professional fighter, making martial arts a shared family profession.", 70],
    ],
  ],
  [
    "ufc:rose-namajunas",
    [
      ["martial-arts-since-age-five", "Namajunas began martial arts at age five and built an unusually broad early base that included taekwondo and karate.", 71],
      ["frozen-custard-job", "As a teenager, Namajunas worked at Gillies Frozen Custard in Milwaukee.", 71],
      ["gardening-hobby", "Namajunas has repeatedly identified gardening as one of her major interests away from fighting.", 71],
      ["piano-hobby", "Playing piano is another visible part of Namajunas' life outside the cage, including during fight-week coverage.", 72],
      ["thug-nickname-origin", "The nickname 'Thug' came from people around her Milwaukee gym, who associated her tough expression and chip-on-the-shoulder attitude with the rough experiences she had grown up around.", 73],
    ],
  ],
  [
    "ufc:cris-cyborg",
    [
      ["handball-discovery-at-nineteen", "Cyborg was playing competitive handball in Curitiba when she was noticed at about 19 and encouraged to try combat sports.", 74],
      ["chute-boxe-first-woman", "Cyborg became the first woman training inside the famously hard Chute Boxe team environment, learning alongside elite Brazilian fighters.", 75],
      ["early-womens-mma-main-event", "Only months after losing her professional debut, Cyborg rebounded into what UFC described as one of the early women's main events in Brazilian MMA.", 74],
      ["cyborg-name-from-evangelista-santos", "The 'Cyborg' name entered her career through then-husband Evangelista 'Cyborg' Santos before becoming more strongly associated with Cris herself.", 76],
      ["mother-seamstress-fightweek-dresses", "Cyborg's mother, Gorete, worked as a seamstress and made dresses for her daughter to wear during fight week.", 74],
    ],
  ],
  [
    "ufc:kayla-harrison",
    [
      ["landscaper-dog-walker-hardware-jobs", "While developing in judo after moving to the Boston area, Harrison worked assorted jobs including landscaping, dog walking, assisting others and working at a hardware store before becoming a judo instructor.", 77],
      ["moved-to-boston-for-jimmy-pedro", "At 16, Harrison moved to the Boston area to train under Olympic medalist and coach Jimmy Pedro, a pivotal decision in her judo career.", 77],
      ["first-us-olympic-judo-gold", "Harrison became the first American to win an Olympic gold medal in judo and then repeated as Olympic champion four years later.", 77],
      ["youngest-us-rokudan", "Harrison became the youngest American awarded the rank of rokudan, a sixth-degree judo black belt.", 77],
      ["retirement-to-striking-to-mma", "After retiring from competitive judo following the 2016 Olympics, Harrison began learning striking and eventually moved to South Florida to pursue MMA at American Top Team.", 77],
    ],
  ],
  [
    "ufc:miesha-tate",
    [
      ["boys-wrestling-team-after-basketball", "Tate found wrestling after basketball did not suit her and joined her high school's boys wrestling team, becoming hooked on the sport after her first practice.", 78],
      ["washington-girls-wrestling-champion", "Tate later won a Washington state girls high-school wrestling championship.", 79],
      ["mma-start-at-nineteen", "At 19, while in college, Tate took an amateur MMA fight after her wrestling background led her into submission grappling and the emerging sport.", 80],
      ["costco-job", "Tate worked at Costco before fighting became her full-time career.", 79],
      ["cupcake-nickname-and-baking", "Her 'Cupcake' nickname played on the contrast between Tate's appearance and toughness and also fit her genuine enjoyment of baking.", 81],
    ],
  ],
  [
    "ufc:jorge-masvidal",
    [
      ["miami-cuban-american-upbringing", "Masvidal's identity is closely tied to growing up in Miami's Cuban-American community and representing the city throughout his career.", 82],
      ["backyard-fights-kimbo-circle", "Before formal MMA fame, Masvidal became known through filmed Miami backyard fights connected to the same South Florida scene that made Kimbo Slice famous.", 83],
      ["gamebred-nickname-brother-origin", "Masvidal has said his brother suggested 'Gamebred,' a term he associates with a pit bull bred for fighting, as the nickname that fit his mentality.", 84],
      ["father-early-career-support", "Masvidal has credited his father with being one of the first people to take his fighting ambition seriously and support it as a real career.", 83],
      ["global-pre-ufc-fight-circuit", "Long before the UFC, Masvidal's career took him through an unusually varied circuit, including fights in Costa Rica, Japan and Strikeforce-era events in the United States.", 85],
    ],
  ],
  [
    "ufc:michael-chandler",
    [
      ["missouri-wrestling-walk-on", "Chandler entered Missouri's wrestling program as a walk-on and developed into an NCAA Division I All-American and team captain.", 86],
      ["woodley-askren-big-brother-influence", "At Missouri, Chandler became close with Tyron Woodley and Ben Askren, whom he described as big-brother figures; seeing them enter MMA helped inspire him to try it after college.", 87],
      ["personal-finance-real-estate-degree", "Chandler earned a bachelor's degree from the University of Missouri in personal financial management services and real estate.", 87],
      ["mizzou-wrestling-coach-job", "Before fighting full time, Chandler worked as a wrestling coach at Missouri.", 87],
      ["high-school-football-background", "Before college wrestling, Chandler was also a multi-year high-school football player in Missouri.", 88],
    ],
  ],
  [
    "ufc:brian-ortega",
    [
      ["san-pedro-low-income-upbringing", "Ortega grew up in low-income housing in San Pedro, California, in an environment he has described as frequently dangerous.", 89],
      ["rener-gracie-student-from-thirteen", "Ortega began learning Brazilian jiu-jitsu with Rener Gracie as a young teenager and remained closely tied to the Gracie Academy.", 90],
      ["t-city-triangle-nickname-origin", "Rener Gracie coined the nickname 'T-City,' short for 'Triangle City,' because of Ortega's reputation for catching triangle chokes.", 91],
      ["law-enforcement-self-defense-instructor", "From his late teens, Ortega helped teach Gracie-style self-defense to law-enforcement personnel.", 90],
      ["james-luhrsen-garage-training", "Ortega formed a long-running striking relationship with coach James Luhrsen that began with humble garage training sessions when Ortega was young.", 92],
    ],
  ],
  [
    "ufc:ciryl-gane",
    [
      ["soccer-basketball-youth-sports", "Gane grew up playing team sports, especially soccer and basketball, before entering combat sports relatively late.", 93],
      ["management-marketing-degree", "Gane completed a degree in management and marketing before his fighting career.", 94],
      ["luxury-furniture-coworker-muay-thai", "While working as a luxury-furniture salesman, a coworker introduced Gane to Muay Thai, launching his combat-sports path.", 93],
      ["two-time-france-muay-thai-champion", "Gane became a two-time French Muay Thai champion before switching to professional MMA.", 94],
      ["fernand-lopez-mma-factory-pivot", "Coach Fernand Lopez quickly recognized Gane's potential at Paris' MMA Factory and pushed him to stop splitting focus with Muay Thai and commit to MMA.", 95],
    ],
  ],
  [
    "ufc:marlon-vera",
    [
      ["jiu-jitsu-start-at-sixteen", "Vera has said he had little interest in organized sports until he began jiu-jitsu at 16, which quickly led him toward MMA.", 96],
      ["first-ecuadorian-ufc-fighter", "Vera became the first Ecuadorian fighter to compete in the UFC.", 97],
      ["daughter-surgery-career-motivation", "A major early-career motivation was earning enough to obtain specialized treatment for his daughter, who was born with Moebius syndrome.", 97],
      ["chito-childhood-nickname-origin", "The nickname 'Chito' traces back to childhood versions of his name, including 'Andrechito,' that family members shortened over time.", 98],
      ["downloaded-fight-videos-in-ecuador", "Growing up in Ecuador with limited access to UFC broadcasts and MMA gyms, Vera fed his interest by downloading fight videos and studying the sport from afar.", 99],
    ],
  ],
  [
    "ufc:dominick-reyes",
    [
      ["stony-brook-football-safety", "Reyes was a four-year football player and three-year starting safety at Stony Brook before turning to MMA.", 100],
      ["information-systems-degree", "Reyes earned a bachelor's degree in information systems with a business and economics focus.", 101],
      ["technical-support-job", "Before fighting full time, Reyes worked as a technical support specialist at a high school.", 101],
      ["devastator-nickname-origin", "Reyes has explained that 'The Devastator' nickname came from the power of his kicks and the mentality he wanted to bring into fights.", 102],
      ["fighter-brother-alex-reyes", "His older brother Alex Reyes also became a professional MMA fighter and competed in the UFC.", 102],
    ],
  ],
  [
    "ufc:dan-hooker",
    [
      ["friend-knockout-mma-origin", "Hooker says he decided to try MMA after watching a friend score a quick knockout and seeing the crowd's reaction, then followed that friend to the gym.", 103],
      ["auckland-doorman-job", "Before fighting full time, Hooker worked as a doorman in Auckland's central business district.", 104],
      ["hangman-nickname-chokes", "Hooker has said 'The Hangman' nickname came from his love of finishing fights with chokes.", 104],
      ["pre-ufc-kickboxing-titles", "Hooker's pre-UFC combat résumé included a King in the Ring middleweight kickboxing championship and a WKBF X-Rules welterweight title.", 104],
      ["one-minute-scraps-promotion", "Hooker has used his platform to promote '1min Scraps,' a New Zealand one-minute street-fighting concept.", 104],
    ],
  ],
] as const;
