// PR10 UFC person-identity research data batch 5. Canonical validation and lookup remain in ufcPersonIdentityKnowledge.ts.
export const ufcPersonIdentityResearchSources5 = [
  ["https://www.ufc.com/athlete/merab-dvalishvili", "UFC", "Merab Dvalishvili | UFC Athlete Profile"],
  ["https://www.ufc.com/news/si-se-puede-cain-velasquez-embodies-mexican-american-pride", "UFC", "Sí, Se Puede: Cain Velasquez Embodies Mexican-American Pride"],
  ["https://www.ufc.com/news/raising-cain", "UFC", "Raising Cain"],
  ["https://www.ufc.com/news/ufc-155-flashback-velasquez-debuts-ufc", "UFC", "UFC 155 Flashback: Velasquez Debuts in UFC"],
  ["https://www.sherdog.com/news/articles/Junior-dos-Santos-A-New-Chapter-103039", "Sherdog", "Junior dos Santos: A New Chapter"],
  ["https://jp.ufc.com/news/junior-cigano-esta-preparado-para-onde-quer-que-luta-va", "UFC", "Júnior Cigano está preparado para onde quer que a luta vá"],
  ["https://www.ufc.com/news/tyron-woodley-fights-ferguson", "UFC", "Tyron Woodley Fights for Ferguson"],
  ["https://www.ufc.com/athlete/tyron-woodley", "UFC", "Tyron Woodley | UFC Athlete Profile"],
  ["https://www.stlmag.com/news/sports/q-a-with-tyron-woodlye-ufc-welterweight-champion/", "St. Louis Magazine", "Q&A with Tyron Woodley, UFC welterweight champion"],
  ["https://www.ufc.com/news/alexandre-pantoja-homecoming-king-champion-ufc-301", "UFC", "Alexandre Pantoja: Homecoming King"],
  ["https://www.ufc.com/athlete/alexandre-pantoja", "UFC", "Alexandre Pantoja | UFC Athlete Profile"],
  ["https://www.ufc.com/news/story-how-alexandre-pantoja-proved-who-he-was-ufc-296-flyweight", "UFC", "The Story Of How Alexandre Pantoja Proved Who He Was"],
  ["https://www.ufc.com/athlete/ilia-topuria", "UFC", "Ilia Topuria | UFC Athlete Profile"],
  ["https://www.ufc.com/news/ilia-topuria-world-know-his-name-vegas-16", "UFC", "Ilia Topuria: The World Will Know His Name"],
  ["https://www.ufc.com/athlete/robert-whittaker", "UFC", "Robert Whittaker | UFC Athlete Profile"],
  ["https://jp.ufc.com/news/chris-weidman-ufc-career-highlights", "UFC", "Chris Weidman | UFC Career Highlights"],
  ["https://www.ufc.com/news/introducing-chris-weidman", "UFC", "Introducing Chris Weidman"],
  ["https://www.ufc.com/athlete/sean-strickland", "UFC", "Sean Strickland | UFC Athlete Profile"],
  ["https://www.ufc.com/news/sean-strickland-all-about-life-ufc-vegas-25", "UFC", "Sean Strickland Is All About This Life"],
  ["https://www.espn.com/mma/story/_/id/30491475/ufc-270-family-pinata-business-ufc-record-book-brandon-moreno-historic-title-quest", "ESPN", "From family piñata business to the UFC record book: Brandon Moreno's historic title quest"],
  ["https://www.ufc.com/news/moreno-reaching-next-level-second-ufc-stint", "UFC", "Moreno Reaching Next Level In Second UFC Stint"],
  ["https://www.ufc.com/news/brandon-moreno-putting-all-his-heart-fight-ufc-mexico-city-flyweight", "UFC", "Brandon Moreno Putting All His Heart Into The Fight"],
] as const;

export const ufcPersonIdentityResearch5 = [
  ["ufc:merab-dvalishvili", [
    ["judo-sambo-seven-year-foundation", "Before concentrating on MMA, Dvalishvili spent about seven years training in judo and sambo.", 0],
    ["physical-education-college-georgia", "He attended college in Georgia and studied physical education.", 0],
    ["construction-job-before-fighting", "Dvalishvili worked in construction before fighting became his livelihood.", 0],
    ["georgian-sambo-youth-medals", "His pre-UFC résumé included a Georgian sambo championship and a bronze medal at the European Youth Sambo Championships.", 0],
    ["lookin-for-a-fight-discovery", "Dvalishvili was one of the fighters whose route to a UFC opportunity ran through Dana White: Lookin' for a Fight.", 0],
  ]],
  ["ufc:cain-velasquez", [
    ["migrant-farmworker-family", "Velasquez grew up in a Mexican-American family whose early U.S. story included his parents doing migrant farm work and following seasonal agricultural jobs.", 1],
    ["brown-pride-tattoo-family-heritage", "His prominent 'Brown Pride' chest tattoo is tied to pride in his Mexican heritage and to the sacrifices he associates with his parents' immigration and work history.", 2],
    ["elite-amateur-wrestling-path", "Before MMA, Velasquez was a junior-college national champion and later a two-time NCAA All-American wrestler at Arizona State.", 3],
    ["arizona-state-education-degree", "He earned a degree in education from Arizona State University while building his wrestling career.", 1],
    ["olympic-path-chose-mma", "Velasquez considered continuing in wrestling toward the 2008 Olympics but chose to pursue MMA instead, joining American Kickboxing Academy after college.", 3],
  ]],
  ["ufc:junior-dos-santos", [
    ["working-class-family-upbringing", "Dos Santos grew up in a working-class Brazilian family as the son of a mechanic and a maid, with limited money and several siblings.", 4],
    ["salvador-bus-ticket-odd-jobs", "When he moved to Salvador as a young man, he arrived with little money and supported himself through jobs such as washing dishes and selling ice cream.", 4],
    ["capoeira-adolescent-origin", "His first martial art was capoeira, which he began practicing as an adolescent before he ever entered Brazilian jiu-jitsu or MMA.", 5],
    ["yuri-carlton-jiujitsu-to-mma", "Training Brazilian jiu-jitsu under Yuri Carlton became the bridge into MMA for dos Santos; Carlton recognized his potential and encouraged him toward fighting.", 5],
    ["cigano-soap-opera-nickname", "The nickname 'Cigano' grew out of his long-haired look and a comparison to a gypsy character from a Brazilian soap opera; the name stuck even though he initially disliked it.", 4],
  ]],
  ["ufc:tyron-woodley", [
    ["ferguson-crowded-evicted-upbringing", "Woodley has described growing up in Ferguson, Missouri in a crowded household of 13 people and experiencing an eviction while he was young.", 6],
    ["missouri-wrestling-credentials", "His athletic foundation was elite wrestling: an undefeated high-school state-title season, a Big 12 championship, and two NCAA Division I All-American honors at Missouri.", 7],
    ["business-public-administration-education", "Woodley earned a business degree at the University of Missouri and later pursued graduate work in public administration with a nonprofit focus.", 7],
    ["college-wrestling-coach-job", "Before fighting full-time, he worked as a college wrestling coach.", 7],
    ["acting-straight-outta-compton", "Woodley built an acting résumé alongside fighting, including an appearance in Straight Outta Compton and other film and television roles.", 8],
  ]],
  ["ufc:alex-pantoja", [
    ["copacabana-working-class-upbringing", "Pantoja grew up in Copacabana in modest circumstances and has described fighting from a young age as a possible route to a better life.", 9],
    ["diverse-pre-fight-jobs", "Before MMA paid the bills, he worked a range of jobs that included waiter, mason, boat-ride worker and Muay Thai instructor.", 10],
    ["bjj-muay-thai-to-mma-career", "Pantoja competed in Brazilian jiu-jitsu and Muay Thai before deciding MMA offered the clearest professional path for him.", 10],
    ["uber-driving-acl-period", "During a difficult stretch of his UFC career, Pantoja drove for Uber while also dealing with an ACL injury and the financial pressure of supporting his family.", 9],
    ["family-us-relocation-goal", "Around his first Brandon Royval fight, Pantoja spoke about earning enough money to improve his family's situation and bring them to live with him in the United States.", 11],
  ]],
  ["ufc:ilia-topuria", [
    ["father-bjj-age-four", "Topuria has said his father introduced him to Brazilian jiu-jitsu at about four years old.", 12],
    ["stradivarius-cashier-job", "Before fighting became his profession, Topuria worked as a cashier at the clothing retailer Stradivarius.", 12],
    ["arnold-fighter-tournament-win", "His pre-UFC accomplishments included winning the Arnold Fighter tournament associated with the Arnold sports festival circuit.", 12],
    ["european-youth-bjj-runner-up", "As a youth grappler, Topuria finished second in a European jiu-jitsu competition before his professional MMA career.", 12],
    ["georgia-spain-dual-identity", "Topuria's identity bridges Georgia and Spain: he spent formative years in Georgia, developed his MMA career in Spain, and has publicly embraced both countries as part of his story.", 13],
  ]],
  ["ufc:robert-whittaker", [
    ["railcorp-electrician-apprentice", "Before fighting became his full-time profession, Whittaker worked as an apprentice electrician for RailCorp.", 14],
    ["three-martial-arts-black-belts", "His martial-arts background spans multiple systems, including black belts in Brazilian jiu-jitsu, hapkido and karate.", 14],
    ["large-family-primary-motivation", "Whittaker consistently describes himself first as a family man; he and his wife have a large family, and he cites providing for them as his central motivation.", 14],
    ["reading-video-games-hobbies", "Outside training, Whittaker has repeatedly listed reading and video games among his main hobbies.", 14],
    ["competition-thrill-training-motivation", "He has said that the competitive challenge and the thrill of testing himself were major reasons he committed to fighting.", 14],
  ]],
  ["ufc:chris-weidman", [
    ["hofstra-dual-degrees", "Weidman earned a bachelor's degree in psychology and later a master's degree in physical education at Hofstra.", 15],
    ["assistant-wrestling-coach-grad-student", "After his college wrestling career, he stayed at Hofstra as an assistant wrestling coach while also attending graduate school full time.", 16],
    ["jiujitsu-through-helping-mma-fighters", "Weidman's route into jiu-jitsu came while he was helping local MMA fighters with their wrestling; he tried BJJ himself and became absorbed by it.", 16],
    ["grapplers-quest-thirteen-submissions", "Early in his grappling transition, he won both his weight class and the absolute division at Grapplers Quest, submitting all 13 opponents he faced at that event.", 15],
    ["basement-apartment-waited-for-ufc", "As a young husband and father living in a basement apartment, Weidman turned down faster-paying opportunities from other promotions because he wanted to hold out for a UFC opportunity.", 16],
  ]],
  ["ufc:sean-strickland", [
    ["training-age-fourteen-anger-outlet", "Strickland has said he began martial-arts training around age 14 because combat sports gave him an outlet for anger and were one of the few athletic environments that held his attention.", 17],
    ["professional-since-sixteen", "He turned professional as a teenager and has said fighting has essentially been his only adult career rather than something he entered after a conventional job.", 17],
    ["motorcycle-accident-career-hiatus", "A serious motorcycle crash caused major injuries and kept Strickland out of competition for nearly two years before he returned.", 18],
    ["dogs-motorcycles-outdoor-hobbies", "Outside the gym, Strickland has described spending time with his dogs, riding motorcycles and recreational shooting among his interests.", 17],
    ["unfiltered-no-character-persona", "Strickland has explicitly described his public persona as unfiltered rather than a constructed character, saying that what fans see is essentially how he behaves off camera as well.", 17],
  ]],
  ["ufc:brandon-moreno", [
    ["family-pinata-business", "Moreno grew up working in his parents' Tijuana piñata business, Piñatas Moreno, which became an important source of income and stability while he trained.", 19],
    ["mma-start-exercise-chubby-kid", "He began MMA at about 12 primarily as exercise after describing himself as a chubby kid who spent a lot of time on video games and junk food; training then became his passion.", 19],
    ["assassin-baby-nickname-debut", "The 'Assassin Baby' nickname dates to his teenage professional debut, when an announcer introduced him that way because of his youthful appearance before a fight with an older-looking opponent.", 20],
    ["lawyer-plan-before-fighting-career", "Before MMA became a realistic career, Moreno had considered studying law and becoming a lawyer, while his parents required him to keep working in the family business as he trained.", 19],
    ["lego-collector-hobby", "Moreno is an enthusiastic LEGO collector and builder; UFC coverage has highlighted the hobby as one of his most recognizable interests away from fighting.", 21],
  ]],
] as const;
