// PR10 UFC person-identity research data batch 3. Canonical validation and lookup remain in ufcPersonIdentityKnowledge.ts.
export const ufcPersonIdentityResearchSources3 = [
  ["https://www.ufc.com/news/flashback-forrest-griffins-new-reality", "UFC", "Flashback: Forrest Griffin's New Reality"],
  ["https://www.ufc.com/news/griffin-bonnar-night-changed-everything?language_content_entity=en", "UFC", "Griffin, Bonnar and the Night that Changed Everything"],
  ["https://www.ufc.com/news/ufc-25-forrest-griffin", "UFC", "UFC 25: Forrest Griffin"],
  ["https://www.ufc.com/news/forrest-griffin-he-did-it-his-way", "UFC", "Forrest Griffin: He Did It His Way"],
  ["https://www.ufc.com/news/outside-octagon-there-will-only-be-one-chael-sonnen", "UFC", "Outside the Octagon: There Will Only Be One Chael Sonnen"],
  ["https://www.ufc.com/news/chael-says-quotables-mmas-most-interesting-man-0", "UFC", "Chael Says: Quotables from MMA's Most Interesting Man"],
  ["https://www.themat.com/news/2016/february/24/bp32-chael-sonnen", "USA Wrestling", "BP32: Chael Sonnen"],
  ["https://www.ufc.com/news/sonnen-says-words-wisdom", "UFC", "Sonnen Says – Words of Wisdom"],
  ["https://www.mmafighting.com/2014/9/5/6108945/morning-report-ufc-chael-sonnen-wanderlei-silva-dana-white-overeem-jacare-king-mo-mma-news", "MMA Fighting", "Morning Report: Chael Sonnen and the 'American Gangster' moniker"],
  ["https://www.ufc.com/news/shevchenko-hoping-take-fast-lane-title-shot", "UFC", "Shevchenko hoping to take fast lane to title shot"],
  ["https://www.mmafighting.com/2019/6/7/18650518/valentina-shevchenko-a-woman-of-many-nations-ahead-of-first-ufc-title-defense", "MMA Fighting", "Valentina Shevchenko, a woman of many nations ahead of first UFC title defense"],
  ["https://www.ufc.com/athlete/valentina-shevchenko?language_content_entity=en", "UFC", "Valentina Shevchenko | UFC"],
  ["https://www.ufc.com/news/antonina-shevchenko-family-business", "UFC", "Antonina Shevchenko: Family Business"],
  ["https://www.ufc.com/athlete/rose-namajunas", "UFC", "Rose Namajunas | UFC"],
  ["https://www.mmafighting.com/2019/5/6/18534776/ufc-237-embedded-episode-1-dont-put-drinks-on-the-piano", "MMA Fighting", "UFC 237 Embedded, Episode 1: Don't put drinks on the piano"],
  ["https://www.ufc.com/news/rose-namajunas-one-win-away", "UFC", "Rose Namajunas: One Win Away"],
  ["https://www.ufc.com/news/defined-her-courage-cyborg-protects-undefeated-streak", "UFC", "Defined by her courage, Cyborg protects undefeated streak"],
  ["https://www.ufc.com/news/cyborg-ready-place-amongst-ufc-legends", "UFC", "Cyborg ready for place amongst UFC legends"],
  ["https://www.ufc.com/news/cyborg-one-greatest-all-time-looks-add-legacy-vs-holm", "UFC", "Cyborg, one of the greatest of all time, looks to add to legacy vs Holm"],
  ["https://www.ufc.com/athlete/kayla-harrison", "UFC", "Kayla Harrison | UFC"],
  ["https://www.ufc.com/news/tates-journey-bottom-could-reach-top-ufc-196", "UFC", "Tate's journey from bottom could reach top at UFC 196"],
  ["https://www.ufc.com/athlete/miesha-tate", "UFC", "Miesha Tate | UFC"],
  ["https://www.ufc.com/news/miesha-tate-having-champions-heart", "UFC", "Miesha Tate on Having a Champion's Heart"],
  ["https://www.ufc.com/news/miesha-tate-cupcake-nickname-only", "UFC", "Miesha Tate: Cupcake Nickname Only"],
  ["https://www.ufc.com/news/jorge-masvidal-gamebred-journey-his-miami-homecoming-ufc-287", "UFC", "Jorge Masvidal's Journey To His Miami Homecoming"],
  ["https://www.espn.com/mma/story/_/id/27931280/from-miami-brawler-ufc-star-jorge-masvidal-always-bmf", "ESPN", "From Miami brawler to UFC star, Jorge Masvidal was always 'Gamebred'"],
  ["https://www.ufc.com/news/masvidal-de-la-calle-la-jaula", "UFC", "Masvidal: De la calle a la jaula"],
  ["https://www.ufc.com/news/jorge-masvidal-exclamation-point", "UFC", "Jorge Masvidal: The Exclamation Point"],
  ["https://www.ufc.com/news/dana-white-announces-michael-chandler-signing-ufc-254-backup", "UFC", "Dana White Announces Michael Chandler Signing"],
  ["https://www.ufc.com/athlete/michael-chandler?language_content_entity=en", "UFC", "Michael Chandler | UFC"],
  ["https://mutigers.com/sports/wrestling/roster/season/2007-08/player/michael-chandler", "University of Missouri Athletics", "Michael Chandler - Wrestling"],
  ["https://www.espn.com/mma/story/_/id/25456207/the-two-lives-brian-ortega-menacing-streets-ufc-stardom", "ESPN", "The two lives of Brian Ortega: From menacing streets to UFC stardom"],
  ["https://www.ufc.com/news/brian-ortega-big-name-hunter", "UFC", "Brian Ortega: Big Name Hunter"],
  ["https://www.espn.com/general/story?id=22619156&src=desktop", "ESPN", "Brian Ortega's path from San Pedro to UFC title contender"],
  ["https://www.ufc.com/news/ortega-happy-showcase-all-skills-ufc-195", "UFC", "Ortega happy to showcase all skills at UFC 195"],
] as const;

export const ufcPersonIdentityResearch3 = [
  ["ufc:forrest-griffin", [
    ["university-police-officer", "Before becoming a full-time fighter, Griffin worked as a university police officer in Georgia.", 0],
    ["mma-hobby-dan-severn-first-pro", "Griffin treated MMA as a side pursuit while working, and his first professional fight was against veteran Dan Severn for only a small purse.", 0],
    ["tuf-one-bonnar-mainstream-breakthrough", "Griffin's 2005 Ultimate Fighter finale with Stephan Bonnar became one of the defining mainstream breakthrough moments in UFC history and helped secure the show's future on television.", 1],
    ["two-new-york-times-bestsellers", "Griffin later became the author of two New York Times bestselling books.", 2],
    ["xacto-self-stitch-removal", "A famous example of Griffin's self-deprecating, rough-edged personality was his account of removing his own stitches with an X-Acto knife after the Bonnar fight.", 3],
  ]],
  ["ufc:chael-sonnen", [
    ["realtor-and-political-ambitions", "Outside fighting, Sonnen worked in real estate and also pursued political ambitions in Oregon.", 4],
    ["oregon-sociology-business-education", "Sonnen attended the University of Oregon, majoring in sociology and minoring in business.", 5],
    ["ncaa-and-greco-roman-wrestling", "Before MMA, Sonnen was an NCAA Division I All-American wrestler and also competed at a high level in Greco-Roman wrestling.", 6],
    ["fighting-as-hobby-philosophy", "Sonnen repeatedly described professional fighting as a 'hobby' rather than a job, arguing that he wanted his primary work to provide a conventional good or service to the community.", 7],
    ["american-gangster-persona-origin", "Sonnen leaned into the 'American Gangster' moniker as part of the deliberately provocative persona he developed around his fighting career.", 8],
  ]],
  ["ufc:valentina-shevchenko", [
    ["martial-arts-family-start-age-five", "Shevchenko began martial arts at five in a family already immersed in combat sports; her mother Elena practiced taekwondo and helped lead the Kyrgyz Muay Thai federation.", 9],
    ["peru-eight-year-home", "Shevchenko lived in Peru for years, learned Spanish and came to represent Peru alongside Kyrgyzstan as a major part of her public identity.", 10],
    ["film-directing-degree", "Shevchenko earned an undergraduate degree in film directing from the University of Arts in Kyrgyzstan.", 11],
    ["lifelong-dance-training", "Shevchenko studied dance from a young age and has described dance as a complementary discipline that sharpened her body control.", 9],
    ["fighter-sister-antonina", "Her older sister Antonina Shevchenko also became a professional fighter, making martial arts a shared family profession.", 12],
  ]],
  ["ufc:rose-namajunas", [
    ["martial-arts-since-age-five", "Namajunas began martial arts at age five and built an unusually broad early base that included taekwondo and karate.", 13],
    ["frozen-custard-job", "As a teenager, Namajunas worked at Gillies Frozen Custard in Milwaukee.", 13],
    ["gardening-hobby", "Namajunas has repeatedly identified gardening as one of her major interests away from fighting.", 13],
    ["piano-hobby", "Playing piano is another visible part of Namajunas' life outside the cage, including during fight-week coverage.", 14],
    ["thug-nickname-origin", "The nickname 'Thug' came from people around her Milwaukee gym, who associated her tough expression and chip-on-the-shoulder attitude with the rough experiences she had grown up around.", 15],
  ]],
  ["ufc:cris-cyborg", [
    ["handball-discovery-at-nineteen", "Cyborg was playing competitive handball in Curitiba when she was noticed at about 19 and encouraged to try combat sports.", 16],
    ["chute-boxe-first-woman", "Cyborg became the first woman training inside the famously hard Chute Boxe team environment, learning alongside elite Brazilian fighters.", 17],
    ["early-womens-mma-main-event", "Only months after losing her professional debut, Cyborg rebounded into what UFC described as one of the early women's main events in Brazilian MMA.", 16],
    ["cyborg-name-from-evangelista-santos", "The 'Cyborg' name entered her career through then-husband Evangelista 'Cyborg' Santos before becoming more strongly associated with Cris herself.", 18],
    ["mother-seamstress-fightweek-dresses", "Cyborg's mother, Gorete, worked as a seamstress and made dresses for her daughter to wear during fight week.", 16],
  ]],
  ["ufc:kayla-harrison", [
    ["landscaper-dog-walker-hardware-jobs", "While developing in judo after moving to the Boston area, Harrison worked assorted jobs including landscaping, dog walking, assisting others and working at a hardware store before becoming a judo instructor.", 19],
    ["moved-to-boston-for-jimmy-pedro", "At 16, Harrison moved to the Boston area to train under Olympic medalist and coach Jimmy Pedro, a pivotal decision in her judo career.", 19],
    ["first-us-olympic-judo-gold", "Harrison became the first American to win an Olympic gold medal in judo and then repeated as Olympic champion four years later.", 19],
    ["youngest-us-rokudan", "Harrison became the youngest American awarded the rank of rokudan, a sixth-degree judo black belt.", 19],
    ["retirement-to-striking-to-mma", "After retiring from competitive judo following the 2016 Olympics, Harrison began learning striking and eventually moved to South Florida to pursue MMA at American Top Team.", 19],
  ]],
  ["ufc:miesha-tate", [
    ["boys-wrestling-team-after-basketball", "Tate found wrestling after basketball did not suit her and joined her high school's boys wrestling team, becoming hooked on the sport after her first practice.", 20],
    ["washington-girls-wrestling-champion", "Tate later won a Washington state girls high-school wrestling championship.", 21],
    ["mma-start-at-nineteen", "At 19, while in college, Tate took an amateur MMA fight after her wrestling background led her into submission grappling and the emerging sport.", 22],
    ["costco-job", "Tate worked at Costco before fighting became her full-time career.", 21],
    ["cupcake-nickname-and-baking", "Her 'Cupcake' nickname played on the contrast between Tate's appearance and toughness and also fit her genuine enjoyment of baking.", 23],
  ]],
  ["ufc:jorge-masvidal", [
    ["miami-cuban-american-upbringing", "Masvidal's identity is closely tied to growing up in Miami's Cuban-American community and representing the city throughout his career.", 24],
    ["backyard-fights-kimbo-circle", "Before formal MMA fame, Masvidal became known through filmed Miami backyard fights connected to the same South Florida scene that made Kimbo Slice famous.", 25],
    ["gamebred-nickname-brother-origin", "Masvidal has said his brother suggested 'Gamebred,' a term he associates with a pit bull bred for fighting, as the nickname that fit his mentality.", 26],
    ["father-early-career-support", "Masvidal has credited his father with being one of the first people to take his fighting ambition seriously and support it as a real career.", 25],
    ["global-pre-ufc-fight-circuit", "Long before the UFC, Masvidal's career took him through an unusually varied circuit, including fights in Costa Rica, Japan and Strikeforce-era events in the United States.", 27],
  ]],
  ["ufc:michael-chandler", [
    ["missouri-wrestling-walk-on", "Chandler entered Missouri's wrestling program as a walk-on and developed into an NCAA Division I All-American and team captain.", 28],
    ["woodley-askren-big-brother-influence", "At Missouri, Chandler became close with Tyron Woodley and Ben Askren, whom he described as big-brother figures; seeing them enter MMA helped inspire him to try it after college.", 29],
    ["personal-finance-real-estate-degree", "Chandler earned a bachelor's degree from the University of Missouri in personal financial management services and real estate.", 29],
    ["mizzou-wrestling-coach-job", "Before fighting full time, Chandler worked as a wrestling coach at Missouri.", 29],
    ["high-school-football-background", "Before college wrestling, Chandler was also a multi-year high-school football player in Missouri.", 30],
  ]],
  ["ufc:brian-ortega", [
    ["san-pedro-low-income-upbringing", "Ortega grew up in low-income housing in San Pedro, California, in an environment he has described as frequently dangerous.", 31],
    ["rener-gracie-student-from-thirteen", "Ortega began learning Brazilian jiu-jitsu with Rener Gracie as a young teenager and remained closely tied to the Gracie Academy.", 32],
    ["t-city-triangle-nickname-origin", "Rener Gracie coined the nickname 'T-City,' short for 'Triangle City,' because of Ortega's reputation for catching triangle chokes.", 33],
    ["law-enforcement-self-defense-instructor", "From his late teens, Ortega helped teach Gracie-style self-defense to law-enforcement personnel.", 32],
    ["james-luhrsen-garage-training", "Ortega formed a long-running striking relationship with coach James Luhrsen that began with humble garage training sessions when Ortega was young.", 34],
  ]],
] as const;
