// PR10 UFC person-identity research data batch 1. Canonical validation and lookup remain in ufcPersonIdentityKnowledge.ts.
export const ufcPersonIdentityResearchSources1 = [
  ["https://www.ufc.com/athlete/jon-jones", "UFC", "Jon Jones | UFC"],
  ["https://www.ufc.com/athlete/jon-jones?language_content_entity=en&page=1", "UFC", "Jon Jones | UFC"],
  ["https://www.onefc.com/features/the-untold-origins-of-demetrious-mighty-mouse-johnson/", "ONE Championship", "The Untold Origins Of Demetrious 'Mighty Mouse' Johnson"],
  ["https://www.ufc.com/news/demetrious-johnson-talks-kyoji-horiguchi-americas-pregame", "UFC", "Demetrious Johnson Talks Kyoji Horiguchi, America's Pregame"],
  ["https://www.ufc.com/news/demetrious-johnson-hard-work-pays", "UFC", "Demetrious Johnson: Hard Work Pays"],
  ["https://www.seattlemet.com/news-and-city-life/2013/07/demetrious-johnson-isnt-as-little-as-he-looks-july-2013", "Seattle Met", "Demetrious Johnson Isn't as Little as He Looks"],
  ["https://www.gameinformer.com/b/features/archive/2017/10/08/ufc-flyweight-champ-demetrious-johnson-talks-streaming-and.aspx", "Game Informer", "UFC Flyweight Champ Demetrious Johnson Talks Streaming And Gaming"],
  ["https://www.ufc.com/news/making-khabib-nurmagomedov", "UFC", "The Making Of Khabib Nurmagomedov"],
  ["https://www.espn.co.uk/blog/mma/post/_/id/22318/nurmagomedov-brothers-talk-unique-upbringing-us-debut", "ESPN", "Nurmagomedov 'brothers' talk unique upbringing, US debut"],
  ["https://www.ufc.com/news/khabib-eagle-nurmagomedov-named-ufc-hall-fame-class-2022", "UFC", "Khabib 'The Eagle' Nurmagomedov Named to UFC Hall of Fame Class of 2022"],
  ["https://www.ufc.com/news/coach-khabib-spotlight-ufc-311-islam-makhachev-umar-nurmagomedov-tagir-ulanbekov", "UFC", "Coach Khabib Spotlight | UFC 311"],
  ["https://www.ufc.com/news/max-holloway-diamond-paradise", "UFC", "Max Holloway: A Diamond in 'Paradise'"],
  ["https://www.ufc.com/athlete/max-holloway?page=2", "UFC", "Max Holloway | UFC"],
  ["https://www.ufc.com/news/max-holloway-expects-performance-lifetime-co-main-ufc-276", "UFC", "Max Holloway Expects The 'Performance Of A Lifetime'"],
  ["https://www.war.gov/News/Feature-Stories/Story/Article/3619215/sports-heroes-who-served-champion-wrestler-actor-was-also-a-soldier/", "U.S. Department of Defense", "Sports Heroes Who Served: Champion Wrestler, Actor Was Also a Soldier"],
  ["https://sports.yahoo.com/randy-couture-explains-origin-natural-135052584.html", "MMA Junkie / Yahoo Sports", "Randy Couture explains origin of 'The Natural' and 'Captain America' nicknames"],
  ["https://www.ufc.com/news/history-ufc-fighters-movies-and-television-conor-mcgregor-road-house", "UFC", "The History Of UFC Fighters In Movies And Television"],
  ["https://www.ufc.com/athlete/alex-pereira", "UFC", "Alex Pereira | UFC"],
  ["https://www.mmafighting.com/2023/4/8/23672500/racism-alcohol-rituals-fights-alex-pereira-mentor-poatan-israel-adesanya-ufc-287", "MMA Fighting", "Racism, alcohol, rituals, fights: Alex Pereira's mentor opens up on Poatan's journey"],
  ["https://www.ufc.com/news/aline-pereira-ready-make-alex-pereira-splash-ufc-fight-pass", "UFC", "Aline Pereira Ready To Make An Alex Pereira-Like Splash | UFC Fight Pass"],
  ["https://www.ufc.com/news/dillashaw-visits-raiders-headquarters-road-ufc-177", "UFC", "Dillashaw Visits Raiders Headquarters on Road to UFC 177"],
  ["https://www.ufc.com/athlete/tj-dillashaw", "UFC", "TJ Dillashaw | UFC"],
  ["https://www.ufc.com/news/dillashaw-sets-training-camps-colorado", "UFC", "Dillashaw sets up training camps in Colorado"],
  ["https://espnpressroom.com/feature/three-things-to-know-about-the-making-of-espn-cover-story-francis-ngannou/", "ESPN Press Room", "Three Things to Know About the Making of ESPN Cover Story: Francis Ngannou"],
  ["https://www.espn.com/espn/feature/story/_/id/33100543/francis-ngannou-miraculous-journey-ufc-stardom", "ESPN", "Francis Ngannou's Miraculous Journey"],
  ["https://www.ufc.com/news/ufc-francis-ngannou-laying-foundation-his-people-cameroon", "UFC", "Ngannou Laying A Foundation For His People"],
  ["https://www.ufc.com/athlete/aljamain-sterling", "UFC", "Aljamain Sterling | UFC"],
  ["https://www.espn.com/mma/story/_/id/29133514/ufc-274-justin-gaethje-journey-mining-town-mma-stardom", "ESPN", "Inside Justin Gaethje's journey from a mining town to MMA stardom"],
  ["https://us.ufcespanol.com/athlete/justin-gaethje", "UFC", "Justin Gaethje | UFC"],
  ["https://www.sherdog.com/news/news/Justin-Gaethje-Reveals-Origins-of-The-Highlight-Nickname-199769", "Sherdog", "Justin Gaethje Reveals Origins of 'The Highlight' Nickname"],
] as const;

export const ufcPersonIdentityResearch1 = [
  ["ufc:jon-jones", [
    ["mma-start-unexpected-child", "Jones has said he began training MMA in 2007 after learning he had an unexpected child while in college and needing to earn money.", 0],
    ["iowa-central-wrestling-and-degree", "At Iowa Central Community College, Jones won a JUCO national wrestling championship and earned an associate degree.", 0],
    ["nfl-brothers-arthur-and-chandler", "Jones comes from an unusually athletic family: his brothers Arthur and Chandler Jones both played in the NFL.", 1],
    ["youtube-technique-study", "Jones told UFC that he used YouTube to study and pick up unconventional techniques early in his MMA development.", 1],
    ["robbery-intervention-title-day", "On the day he fought Mauricio Rua for the light heavyweight title in 2011, Jones and his coaches chased down a man they saw breaking into a car and helped detain him until police arrived.", 1],
  ]],
  ["ufc:demetrious-johnson", [
    ["wrestling-accountability-origin", "Johnson first tried wrestling at 13 and has said he was drawn to the sport's individual accountability.", 2],
    ["tacoma-recycling-warehouse-job", "Before fighting full time, Johnson worked an early shift at a Tacoma-area warehouse recycling paper into shipping boards used for televisions.", 3],
    ["matt-hume-longtime-mentor", "Johnson linked up with coach Matt Hume and AMC Pankration in 2005, forming one of the defining long-term coach-fighter relationships of his career.", 4],
    ["mighty-mouse-nickname-origin", "The 'Mighty Mouse' nickname came from a coach because Johnson was the smallest athlete in the gym but was willing to spar with anyone.", 5],
    ["lifelong-gamer-and-streamer", "Johnson is a lifelong video-game fan who later became a serious Twitch streamer, tracing the hobby back to playing games such as Super Contra with his mother.", 6],
  ]],
  ["ufc:khabib-nurmagomedov", [
    ["father-school-before-fighting", "Khabib has described how his father Abdulmanap initially emphasized education before recognizing his fighting potential and taking a more direct role in training him.", 7],
    ["sixteen-boy-training-household", "During his youth, Khabib was part of an unusually communal training environment in which a large group of boys lived and trained together year-round in Makhachkala under Abdulmanap Nurmagomedov's system.", 8],
    ["combat-sambo-world-champion", "Before his UFC career, Khabib became a two-time Combat Sambo world champion after developing across wrestling, judo and sambo.", 9],
    ["post-retirement-coaching-role", "After retiring from competition, Khabib moved into a coaching and mentoring role for teammates including Islam Makhachev and Umar Nurmagomedov.", 10],
    ["eagle-fighting-championship-owner", "Khabib also became an MMA promoter after retirement, serving as owner of Eagle Fighting Championship.", 9],
  ]],
  ["ufc:max-holloway", [
    ["waianae-upbringing-and-representation", "Holloway has made representing Waianae, on Oahu, central to his identity, saying the area's negative stereotypes motivated him to show that successful people could come from his hometown.", 11],
    ["josh-keanu-speedbag-gym-origin", "Friend Josh Keanu helped bring Holloway into formal training after a trainer noticed Holloway's natural ability while he was working a speed bag.", 12],
    ["blessed-nickname-origin", "The nickname 'Blessed' stuck after a coach remarked that Holloway was blessed because of how quickly he had progressed and accomplished things in fighting.", 12],
    ["handyman-before-fighting", "Holloway has listed working as a handyman among his jobs before fighting became his profession.", 12],
    ["mini-blessed-son-rush", "Holloway's son Rush, often called 'Mini Blessed,' has long been a visible part of his fight life and a major source of motivation for him.", 13],
  ]],
  ["ufc:randy-couture", [
    ["army-101st-airborne-service", "Couture served in the U.S. Army from 1982 to 1988, including service with the 101st Airborne Division, and reached the rank of sergeant.", 14],
    ["olympic-alternate-wrestling-background", "Before MMA, Couture was a high-level Greco-Roman wrestler who became a three-time U.S. Olympic team alternate and also wrestled at Oklahoma State.", 14],
    ["the-natural-nickname-origin", "Couture has explained that 'The Natural' was coined by a Full Contact Fighter editor after his early upset of Vitor Belfort, reflecting how naturally he adapted to MMA.", 15],
    ["expendables-acting-career", "Couture built a substantial acting career after becoming an MMA star, most notably playing Toll Road in the Expendables film series.", 16],
    ["gi-foundation-wounded-veterans", "Couture created the Xtreme Couture GI Foundation to support wounded U.S. service members and their families.", 14],
  ]],
  ["ufc:alex-pereira", [
    ["kickboxing-to-escape-alcohol", "Pereira has said he began kickboxing in 2009 as part of changing his life and getting away from alcohol.", 17],
    ["tire-repair-shop-job", "Before his fighting career, Pereira worked in a tire repair shop.", 17],
    ["glory-simultaneous-two-division-champion", "In kickboxing, Pereira became the first GLORY athlete to hold the promotion's middleweight and light heavyweight titles simultaneously.", 17],
    ["poatan-indigenous-name-origin", "Pereira's mentor Belocqua Wera gave him the name 'Poatan,' a Tupi-Guarani name that Wera described as meaning hands as hard as rocks and used to reconnect Pereira with Indigenous heritage.", 18],
    ["fighter-sister-aline-pereira", "Pereira's younger sister Aline Pereira also became a professional combat-sports athlete, competing in kickboxing, MMA and Karate Combat.", 19],
  ]],
  ["ufc:tj-dillashaw", [
    ["raiders-family-and-football-background", "Dillashaw grew up in a devoted Raiders family and played football in Pop Warner and high school, lining up at running back, cornerback and linebacker before focusing on wrestling.", 20],
    ["cal-state-kinesiology-degree", "Dillashaw wrestled at Cal State Fullerton and earned a degree in kinesiology with an emphasis in clinical exercise science.", 21],
    ["mma-after-college-wrestling", "After college wrestling ended without the goals he wanted, Dillashaw turned to MMA because he still wanted a competitive outlet.", 21],
    ["ultimate-fighter-team-bisping", "Dillashaw entered the UFC through season 14 of The Ultimate Fighter as a member of Team Bisping.", 21],
    ["duane-ludwig-colorado-move", "A defining coaching relationship with Duane Ludwig eventually led Dillashaw to leave Team Alpha Male and base major training camps in Colorado with Ludwig.", 22],
  ]],
  ["ufc:francis-ngannou", [
    ["cameroon-sand-mine-childhood", "Ngannou began working in a sand mine in Cameroon at about nine years old.", 23],
    ["fourteen-month-migration-seventh-crossing", "Ngannou's journey from Cameroon toward Europe lasted roughly 14 months, and he ultimately crossed the Strait of Gibraltar on his seventh attempt.", 24],
    ["american-boy-childhood-dream", "As a child in Cameroon, Ngannou called himself the 'American Boy,' with his image of the United States shaped partly by dubbed American television such as Knight Rider.", 24],
    ["boxing-dream-to-mma-factory-pivot", "Ngannou arrived in Paris determined to become a boxer like Mike Tyson and initially resisted MMA; Didier Carmont eventually persuaded him to try Fernand Lopez's MMA Factory when his boxing gym closed temporarily.", 24],
    ["cameroon-foundation-first-mma-gym", "Through the Francis Ngannou Foundation, he later opened what UFC described as the first MMA gym in Cameroon to give local children training and educational opportunities.", 25],
  ]],
  ["ufc:aljamain-sterling", [
    ["funk-master-nickname-origin", "Sterling's 'Funk Master' identity grew out of the unconventional, scrambling style he developed as a wrestler.", 26],
    ["division-three-all-american-wrestler", "Sterling became a two-time NCAA Division III All-American wrestler at SUNY Cortland.", 26],
    ["physical-education-degree", "After initially studying accounting at SUNY Morrisville, Sterling transferred to SUNY Cortland and earned a bachelor's degree in physical education.", 26],
    ["saks-shoes-and-haircuts", "Before fighting full time, Sterling sold shoes at Saks Fifth Avenue and later cut hair at school to help make money.", 26],
    ["matt-serra-bjj-black-belt", "Sterling earned his Brazilian jiu-jitsu black belt under former UFC champion Matt Serra.", 26],
  ]],
  ["ufc:justin-gaethje", [
    ["morenci-copper-mining-family", "Gaethje grew up in the Arizona mining town of Morenci in a family deeply tied to the local copper mine; his father spent decades there, and Gaethje himself worked a summer in the mine at 18.", 27],
    ["northern-colorado-all-american-wrestler", "Before MMA, Gaethje wrestled at the University of Northern Colorado and became an NCAA Division I All-American.", 28],
    ["human-services-college-studies", "Gaethje studied human services in college and has said he came close to completing the degree.", 28],
    ["demolition-painting-bouncer-jobs", "His pre-fighting work included demolition, painting and bouncing.", 28],
    ["highlight-nickname-wrestling-slams", "Gaethje has explained that 'The Highlight' nickname predates his reputation as a striker and was originally tied to the highlight-reel slams he produced as a wrestler.", 29],
  ]],
] as const;
