// PR10 UFC person-identity research data batch 2. Canonical validation and lookup remain in ufcPersonIdentityKnowledge.ts.
export const ufcPersonIdentityResearchSources2 = [
  ["https://macleans.ca/society/lord-of-the-ring/", "Maclean's", "Georges St. Pierre: Lord of the ring"],
  ["https://www.coachweb.com/sport/1434/georges-st-pierre-on-dinosaurs-and-why-karate-is-the-answer", "Coach", "Georges St-Pierre on dinosaurs and why karate is the answer"],
  ["https://www.ufc.com/news/georges-st-pierre-named-ufc-hall-fame-class-2020", "UFC", "Georges St-Pierre Named To UFC Hall Of Fame Class Of 2020"],
  ["https://www.ufc.com/athlete/islam-makhachev?page=4", "UFC", "Islam Makhachev | UFC Athlete Profile"],
  ["https://www.espn.com/mma/story/_/id/30958405/ufc-259-next-khabib-why-some-believe-islam-makhachev-ready-greatness", "ESPN", "UFC 259: The next Khabib? Why some believe Islam Makhachev is ready for greatness"],
  ["https://www.washingtonpost.com/sports/2025/11/20/islam-makhachev-ufc-brother-dagestan-fighters/", "The Washington Post", "The brotherly sacrifice behind Islam Makhachev's UFC rise"],
  ["https://www.ufc.com/news/matt-hughes-joins-ufc-front-office", "UFC", "Matt Hughes Joins UFC Front Office"],
  ["https://www.ufc.com/news/brothers-armbars-raw-story", "UFC", "Brothers in Armbars - raw story"],
  ["https://www.ufc.com/news/stipe-miocic-athlete", "UFC", "Stipe Miocic - The Athlete"],
  ["https://www.ufc.com/news/stipe-miocic-discovering-his-croatian-roots", "UFC", "Stipe Miocic: Discovering His Croatian Roots"],
  ["https://kr.ufc.com/athlete/stipe-miocic", "UFC", "Stipe Miocic | UFC Athlete Profile"],
  ["https://www.ufc.com/athlete/israel-adesanya?language_content_entity=en", "UFC", "Israel Adesanya | UFC Athlete Profile"],
  ["https://www.espn.com/espn/feature/story/_/id/28780685/the-ufc-next-big-thing", "ESPN", "The UFC's next big thing"],
  ["https://www.espn.com/mma/story/_/id/38346503/ufc-293-israel-adesanya-vs-sean-strickland-israel-adesanya-big-ufc-243-walkout-entrance-versus-robert-whittaker", "ESPN", "Inside Israel Adesanya's iconic UFC 243 walkout"],
  ["https://www.ufc.com/news/road-ufc-200-fighting-liddells-dna", "UFC", "Road to UFC 200: Fighting in Liddell's DNA"],
  ["https://www.ufc.com/news/chuck-liddell-tribute-fighter", "UFC", "Chuck Liddell - A Tribute to a Fighter"],
  ["https://www.ufc.com/news/chuck-liddell-retires-boardroom", "UFC", "Chuck Liddell Retires to Boardroom"],
  ["https://www.ufc.com/athlete/merab-dvalishvili", "UFC", "Merab Dvalishvili | UFC Athlete Profile"],
  ["https://www.ufc.com/news/si-se-puede-cain-velasquez-embodies-mexican-american-pride", "UFC", "Sí, Se Puede: Cain Velasquez Embodies Mexican-American Pride"],
  ["https://www.ufc.com/news/raising-cain", "UFC", "Raising Cain"],
  ["https://www.ufc.com/news/ufc-155-flashback-velasquez-debuts-ufc", "UFC", "UFC 155 Flashback: Velasquez Debuts in UFC"],
  ["https://www.sherdog.com/news/articles/Junior-dos-Santos-A-New-Chapter-103039", "Sherdog", "Junior dos Santos: A New Chapter"],
  ["https://jp.ufc.com/news/junior-cigano-esta-preparado-para-onde-quer-que-luta-va", "UFC", "Júnior Cigano está preparado para onde quer que a luta vá"],
  ["https://www.ufc.com/news/tyron-woodley-fights-ferguson", "UFC", "Tyron Woodley Fights for Ferguson"],
  ["https://www.ufc.com/athlete/tyron-woodley", "UFC", "Tyron Woodley | UFC Athlete Profile"],
  ["https://www.stlmag.com/news/sports/q-a-with-tyron-woodlye-ufc-welterweight-champion/", "St. Louis Magazine", "Q&A with Tyron Woodley, UFC welterweight champion"],
  ["https://www.ufc.com/news/alexandre-pantoja-homecoming-king-champion-ufc-301", "UFC", "Alexandre Pantoja: Homecoming King"],
  ["https://www.ufc.com/athlete/alexandre-pantoja", "UFC", "Alexandre Pantoja | UFC Athlete Profile"],
  ["https://www.ufc.com/news/story-how-alexandre-pantoja-proved-who-he-was-ufc-296-flyweight", "UFC", "The Story Of How Alexandre Pantoja Proved Who He Was"],
  ["https://www.ufc.com/athlete/ilia-topuria", "UFC", "Ilia Topuria | UFC Athlete Profile"],
  ["https://www.ufc.com/news/ilia-topuria-world-know-his-name-vegas-16", "UFC", "Ilia Topuria: The World Will Know His Name"],
  ["https://www.ufc.com/athlete/robert-whittaker", "UFC", "Robert Whittaker | UFC Athlete Profile"],
  ["https://jp.ufc.com/news/chris-weidman-ufc-career-highlights", "UFC", "Chris Weidman | UFC Career Highlights"],
  ["https://www.ufc.com/news/introducing-chris-weidman", "UFC", "Introducing Chris Weidman"],
  ["https://www.ufc.com/athlete/sean-strickland", "UFC", "Sean Strickland | UFC Athlete Profile"],
  ["https://www.ufc.com/news/sean-strickland-all-about-life-ufc-vegas-25", "UFC", "Sean Strickland Is All About This Life"],
  ["https://www.espn.com/mma/story/_/id/30491475/ufc-270-family-pinata-business-ufc-record-book-brandon-moreno-historic-title-quest", "ESPN", "From family piñata business to the UFC record book: Brandon Moreno's historic title quest"],
  ["https://www.ufc.com/news/moreno-reaching-next-level-second-ufc-stint", "UFC", "Moreno Reaching Next Level In Second UFC Stint"],
  ["https://www.ufc.com/news/brandon-moreno-putting-all-his-heart-fight-ufc-mexico-city-flyweight", "UFC", "Brandon Moreno Putting All His Heart Into The Fight"],
  ["https://www.ufc.com/news/ufc-legend-rashad-evans-retires?language_content_entity=en", "UFC", "UFC Legend Rashad Evans Retires"],
  ["https://www.ufc.com/news/rashad-evans-risked-it-all-tuf", "UFC", "Rashad Evans Risked It All On TUF"],
  ["https://www.ufc.com/athlete/dominick-cruz", "UFC", "Dominick Cruz | UFC Athlete Profile"],
  ["https://www.ufc.com/news/dominick-cruz-named-ufc-hall-fame-class-2026", "UFC", "Dominick Cruz Named To UFC Hall Of Fame Class Of 2026"],
  ["https://www.ufc.com/news/dominick-cruz-comeback-begins-again", "UFC", "Dominick Cruz: The Comeback Begins Again"],
  ["https://www.ufc.com/news/few-have-done-it-better-bisping", "UFC", "Few Have Done It Better Than Bisping"],
  ["https://www.ufc.com/news/michael-bisping-giving-fans-what-they-came-see", "UFC", "Michael Bisping Giving Fans What They Came To See"],
  ["https://www.ufc.com/news/grounded-kennedy-outpoints-bisping", "UFC", "Grounded: Kennedy Outpoints Bisping"],
  ["https://www.ufc.com/news/bisping-headlines-2019-ufc-hall-fame-class", "UFC", "Bisping Headlines 2019 UFC Hall Of Fame Class"],
  ["https://jp.ufc.com/news/quintons-quotables", "UFC", "Quinton's Quotables"],
  ["https://www.ufc.com/news/rampage-jackson-theres-no-place-his-second-home", "UFC", "Rampage Jackson: There's No Place Like His Second Home"],
  ["https://www.ufc.com/news/rampage-rashad-carwin-and-more-new-ufc-mag", "UFC", "Rampage, Rashad, Carwin and More in New UFC Magazine"],
  ["https://www.ufc.com/news/brock-lesnar-be-featured-espns-e60", "UFC", "Brock Lesnar To Be Featured On ESPN's E:60"],
  ["https://kr.ufc.com/news/brock-lesnar-modern-day-gladiator", "UFC", "Brock Lesnar - Modern Day Gladiator"],
  ["https://www.ufc.com/athlete/paddy-pimblett", "UFC", "Paddy Pimblett | UFC Athlete Profile"],
  ["https://www.bbc.co.uk/sport/mixed-martial-arts/62396350", "BBC Sport", "Paddy Pimblett: UFC star's emotional mental health message after friend's death"],
  ["https://www.ufc.com/athlete/zhang-weili", "UFC", "Zhang Weili | UFC Athlete Profile"],
  ["https://www.xinhuanet.com/english/2020-03/12/c_138870504.htm", "Xinhua", "Feature: Zhang Weili fights her way to the top"],
  ["https://www.ufc.com/news/zhang-weili-found-her-voice-in-mixed-martial-arts-ufc-248", "UFC", "Zhang Weili Found Her Voice In Mixed Martial Arts"],
  ["https://www.espn.com/espnw/athletes-life/the-buzz/article/13533062/ronda-rousey-reveals-special-connection-young-fan", "ESPN", "Ronda Rousey reveals special connection to young fan"],
  ["https://www.ufc.com/news/ronda-rousey-judo-pressure-and-tate", "UFC", "Ronda Rousey: Judo, Pressure and Tate"],
  ["https://www.ufc.com/news/ronda-rousey-makes-history-first-woman-selected-induction-ufc-hall-fame", "UFC", "Ronda Rousey Makes History As First Woman Selected For Induction Into UFC Hall Of Fame"],
  ["https://www.espn.com/wwe/story/_/id/22244988/ronda-rousey-signs-wwe", "ESPN", "Ronda Rousey signs with WWE"],
  ["https://www.ufc.com/athlete/carla-esparza", "UFC", "Carla Esparza | UFC Athlete Profile"],
  ["https://www.ufc.com/news/ufc-magazine-carla-esparza-profile", "UFC", "UFC Magazine: Carla Esparza Profile"],
  ["https://www.ufc.com/athlete/mackenzie-dern", "UFC", "Mackenzie Dern | UFC Athlete Profile"],
  ["https://www.ufc.com/news/mackenzie-dern-full-circle-abu-dhabi-ufc-321", "UFC", "Mackenzie Dern | Full Circle"],
  ["https://www.ufc.com/news/mackenzie-dern-focused-motherhood-and-learning-ufc-women", "UFC", "Mackenzie Dern Focused On Motherhood And Learning"],
  ["https://www.ufc.com/athlete/holly-holm", "UFC", "Holly Holm | UFC Athlete Profile"],
  ["https://www.ufc.com/news/nate-diaz-fighting-life", "UFC", "Nate Diaz's Fighting Life"],
  ["https://www.ufc.com/news/flashback-nate-diaz-23", "UFC", "Flashback: Nate Diaz At 23"],
  ["https://www.ufc.com/news/another-side-nate-diaz", "UFC", "Another Side Of Nate Diaz"],
  ["https://www.ufc.com/athlete/colby-covington", "UFC", "Colby Covington | UFC Athlete Profile"],
  ["https://www.ufc.com/news/colby-covington-proud-his-wrestling-roots-ufc-fight-pass", "UFC", "Colby Covington Proud Of His Wrestling Roots"],
  ["https://www.espn.com/mma/story/_/id/33407960/ufc-272-poker-sushi-betrayal-how-colby-covington-jorge-masvidal-went-roommates-rivals", "ESPN", "UFC 272: How Colby Covington and Jorge Masvidal went from roommates to rivals"],
  ["https://www.ufc.com/node/68250", "UFC", "TUF Latinoamérica: Yair Rodriguez"],
  ["https://www.ufc.com/node/75863", "UFC", "La Otra Cara de Yair Rodriguez"],
  ["https://www.ufc.com/athlete/kevin-holland", "UFC", "Kevin Holland | UFC Athlete Profile"],
  ["https://www.ufc.com/news/kevin-holland-chasing-history-ufc-311", "UFC", "Kevin Holland | Chasing History In 2025"],
  ["https://www.mmafighting.com/2020/5/29/21274531/bronchitis-ice-cream-gilbert-burns-durinho-tyron-woodley-ufc", "MMA Fighting", "From bronchitis and ice cream to the UFC: The story of Gilbert 'Durinho' Burns"],
  ["https://www.ufc.com/news/gilbert-burns-unparalleled-support-system-ufc-287", "UFC", "Gilbert Burns' Unparalleled Support System"],
  ["https://www.ufc.com/news/nick-diaz-man-apart", "UFC", "Nick Diaz: A Man Apart"],
  ["https://www.ufc.com/news/fighting-has-defined-nick-diaz-ufc-266-volkanovski-vs-ortega-diaz-lawler-2", "UFC", "Fighting Has Defined Nick Diaz's Life"],
  ["https://www.ufc.com/news/nick-diaz-knows-what-you-think-about-him-he-also-knows-you-cannot-turn-away", "UFC", "Nick Diaz Knows What You Think About Him. He Also Knows You Cannot Turn Away"],
] as const;

export const ufcPersonIdentityResearch2 = [
  [
    "ufc:georges-st-pierre",
    [
      ["bullying-karate-self-defense", "Frequent childhood bullying in Saint-Isidore pushed Georges St-Pierre toward self-defense; his father Roland, a karate black belt, taught him at home before St-Pierre began formal karate training as a child.", 0],
      ["paleontology-dinosaur-passion", "St-Pierre has a long-running fascination with dinosaurs and paleontology and has spoken about the subject in interviews as a genuine personal passion outside fighting.", 1],
      ["gymnastics-olympic-lifting-cross-training", "His athletic preparation has included gymnastics and Olympic lifting, disciplines he has described as useful for explosiveness and overall athletic development.", 1],
      ["gsp-foundation-anti-bullying", "He created the Georges St-Pierre Foundation in 2009 with a mission that includes combating bullying and encouraging youth physical activity.", 2],
      ["film-acting-captain-america", "Outside MMA, St-Pierre pursued acting and appeared as Georges Batroc in Marvel's Captain America: The Winter Soldier.", 2],
    ],
  ],
  [
    "ufc:islam-makhachev",
    [
      ["training-age-ten-self-defense", "Makhachev has said he began training at about age 10 because he wanted to become stronger and be able to defend himself.", 3],
      ["combat-sambo-championship-pedigree", "Before becoming known globally for MMA, he built an elite combat-sambo résumé that included world and European titles as well as multiple Russian championships.", 3],
      ["dagestan-state-athletic-faculty", "Makhachev attended Dagestan State University and studied in its athletic or physical-education faculty while developing as a fighter.", 3],
      ["abdulmanap-khabib-training-lineage", "He grew up training in the same Dagestani system as Khabib Nurmagomedov and was developed under Khabib's father, Abdulmanap Nurmagomedov, who became a central mentor to their team.", 4],
      ["brother-kurban-family-sacrifice", "His older brother Kurban gave up his own fighting ambitions and worked to help support the family, allowing Islam to continue pursuing the training path laid out by Abdulmanap Nurmagomedov.", 5],
    ],
  ],
  [
    "ufc:matt-hughes",
    [
      ["eastern-illinois-all-american-wrestling", "Hughes graduated from Eastern Illinois University and was a two-time NCAA Division I All-American wrestler before his MMA career.", 6],
      ["agricultural-company-parallel-career", "Even while fighting professionally, Hughes remained closely tied to his rural Illinois roots and operated an agricultural company.", 6],
      ["hometown-youth-mission-mentoring", "He has worked with young people in his hometown area, including mentoring youth and helping provide opportunities for mission trips.", 6],
      ["ufc-front-office-athlete-development", "After his championship career, Hughes moved into a UFC front-office role focused on athlete development and government relations.", 6],
      ["identical-twin-mark-mma-partner", "His identical twin brother Mark was also a wrestler and fighter; the brothers entered MMA together, trained in the Miletich system, and Mark later remained part of Matt's training and corner.", 7],
    ],
  ],
  [
    "ufc:stipe-miocic",
    [
      ["cleveland-multi-sport-athlete", "Miocic was a high-level multi-sport athlete in Ohio, earning varsity letters in baseball, football and wrestling before competing in both NCAA wrestling and college baseball.", 8],
      ["cleveland-golden-gloves-boxing", "He added boxing to that athletic base and won the 2009 Cleveland Golden Gloves tournament, advancing to the national quarterfinals.", 8],
      ["firefighter-paramedic-career", "Miocic continued working as a firefighter and paramedic even after becoming a major UFC star, treating that public-service career as an important part of his identity.", 9],
      ["croatian-family-roots", "He was born in the United States to Croatian parents and later traveled to Croatia as an adult to connect with relatives and his family's roots.", 9],
      ["mma-start-helping-training-partner", "Miocic has said his path into MMA began when he went to a gym to help someone else prepare for a fight; the experience pulled him into the sport himself.", 10],
    ],
  ],
  [
    "ufc:israel-adesanya",
    [
      ["self-protection-training-origin", "Adesanya has said he began serious combat-sports training in 2008 because he wanted the skills to protect himself.", 11],
      ["computer-graphic-design-study", "Before committing to fighting, he spent roughly three years studying computer graphic design and then left school to pursue combat sports.", 11],
      ["gas-line-billing-job", "One of his pre-fighting jobs was working as a metering and billing coordinator for a gas-line company.", 11],
      ["last-stylebender-anime-identity", "His 'The Last Stylebender' nickname reflects his long-running attachment to animation and anime culture, including Avatar: The Last Airbender.", 12],
      ["dance-background-ufc243-walkout", "Adesanya danced before he was famous as a fighter and made that background part of his public identity, most memorably with a choreographed UFC 243 walkout alongside longtime friends.", 13],
    ],
  ],
  [
    "ufc:chuck-liddell",
    [
      ["karate-since-twelve-dream-gym", "Liddell began karate at about age 12 and has described owning a karate gym as an early childhood ambition.", 14],
      ["accounting-degree-grandmother-fallback", "He earned an accounting degree, explaining that his grandmother pushed him toward a practical academic fallback rather than treating physical education as his main plan.", 14],
      ["head-tattoo-peace-prosperity", "The kanji tattoo on the side of Liddell's head has been described by him as meaning a 'place of peace and prosperity.'", 15],
      ["college-bartender-job", "While in college, Liddell worked behind a bar before fighting became his full-time career.", 15],
      ["post-retirement-ufc-executive", "When he first retired from competition, Liddell transitioned into a UFC executive role involving fighter relations and business or regulatory work.", 16],
    ],
  ],
  [
    "ufc:merab-dvalishvili",
    [
      ["judo-sambo-seven-year-foundation", "Before concentrating on MMA, Dvalishvili spent about seven years training in judo and sambo.", 17],
      ["physical-education-college-georgia", "He attended college in Georgia and studied physical education.", 17],
      ["construction-job-before-fighting", "Dvalishvili worked in construction before fighting became his livelihood.", 17],
      ["georgian-sambo-youth-medals", "His pre-UFC résumé included a Georgian sambo championship and a bronze medal at the European Youth Sambo Championships.", 17],
      ["lookin-for-a-fight-discovery", "Dvalishvili was one of the fighters whose route to a UFC opportunity ran through Dana White: Lookin' for a Fight.", 17],
    ],
  ],
  [
    "ufc:cain-velasquez",
    [
      ["migrant-farmworker-family", "Velasquez grew up in a Mexican-American family whose early U.S. story included his parents doing migrant farm work and following seasonal agricultural jobs.", 18],
      ["brown-pride-tattoo-family-heritage", "His prominent 'Brown Pride' chest tattoo is tied to pride in his Mexican heritage and to the sacrifices he associates with his parents' immigration and work history.", 19],
      ["elite-amateur-wrestling-path", "Before MMA, Velasquez was a junior-college national champion and later a two-time NCAA All-American wrestler at Arizona State.", 20],
      ["arizona-state-education-degree", "He earned a degree in education from Arizona State University while building his wrestling career.", 18],
      ["olympic-path-chose-mma", "Velasquez considered continuing in wrestling toward the 2008 Olympics but chose to pursue MMA instead, joining American Kickboxing Academy after college.", 20],
    ],
  ],
  [
    "ufc:junior-dos-santos",
    [
      ["working-class-family-upbringing", "Dos Santos grew up in a working-class Brazilian family as the son of a mechanic and a maid, with limited money and several siblings.", 21],
      ["salvador-bus-ticket-odd-jobs", "When he moved to Salvador as a young man, he arrived with little money and supported himself through jobs such as washing dishes and selling ice cream.", 21],
      ["capoeira-adolescent-origin", "His first martial art was capoeira, which he began practicing as an adolescent before he ever entered Brazilian jiu-jitsu or MMA.", 22],
      ["yuri-carlton-jiujitsu-to-mma", "Training Brazilian jiu-jitsu under Yuri Carlton became the bridge into MMA for dos Santos; Carlton recognized his potential and encouraged him toward fighting.", 22],
      ["cigano-soap-opera-nickname", "The nickname 'Cigano' grew out of his long-haired look and a comparison to a gypsy character from a Brazilian soap opera; the name stuck even though he initially disliked it.", 21],
    ],
  ],
  [
    "ufc:tyron-woodley",
    [
      ["ferguson-crowded-evicted-upbringing", "Woodley has described growing up in Ferguson, Missouri in a crowded household of 13 people and experiencing an eviction while he was young.", 23],
      ["missouri-wrestling-credentials", "His athletic foundation was elite wrestling: an undefeated high-school state-title season, a Big 12 championship, and two NCAA Division I All-American honors at Missouri.", 24],
      ["business-public-administration-education", "Woodley earned a business degree at the University of Missouri and later pursued graduate work in public administration with a nonprofit focus.", 24],
      ["college-wrestling-coach-job", "Before fighting full-time, he worked as a college wrestling coach.", 24],
      ["acting-straight-outta-compton", "Woodley built an acting résumé alongside fighting, including an appearance in Straight Outta Compton and other film and television roles.", 25],
    ],
  ],
  [
    "ufc:alex-pantoja",
    [
      ["copacabana-working-class-upbringing", "Pantoja grew up in Copacabana in modest circumstances and has described fighting from a young age as a possible route to a better life.", 26],
      ["diverse-pre-fight-jobs", "Before MMA paid the bills, he worked a range of jobs that included waiter, mason, boat-ride worker and Muay Thai instructor.", 27],
      ["bjj-muay-thai-to-mma-career", "Pantoja competed in Brazilian jiu-jitsu and Muay Thai before deciding MMA offered the clearest professional path for him.", 27],
      ["uber-driving-acl-period", "During a difficult stretch of his UFC career, Pantoja drove for Uber while also dealing with an ACL injury and the financial pressure of supporting his family.", 26],
      ["family-us-relocation-goal", "Around his first Brandon Royval fight, Pantoja spoke about earning enough money to improve his family's situation and bring them to live with him in the United States.", 28],
    ],
  ],
  [
    "ufc:ilia-topuria",
    [
      ["father-bjj-age-four", "Topuria has said his father introduced him to Brazilian jiu-jitsu at about four years old.", 29],
      ["stradivarius-cashier-job", "Before fighting became his profession, Topuria worked as a cashier at the clothing retailer Stradivarius.", 29],
      ["arnold-fighter-tournament-win", "His pre-UFC accomplishments included winning the Arnold Fighter tournament associated with the Arnold sports festival circuit.", 29],
      ["european-youth-bjj-runner-up", "As a youth grappler, Topuria finished second in a European jiu-jitsu competition before his professional MMA career.", 29],
      ["georgia-spain-dual-identity", "Topuria's identity bridges Georgia and Spain: he spent formative years in Georgia, developed his MMA career in Spain, and has publicly embraced both countries as part of his story.", 30],
    ],
  ],
  [
    "ufc:robert-whittaker",
    [
      ["railcorp-electrician-apprentice", "Before fighting became his full-time profession, Whittaker worked as an apprentice electrician for RailCorp.", 31],
      ["three-martial-arts-black-belts", "His martial-arts background spans multiple systems, including black belts in Brazilian jiu-jitsu, hapkido and karate.", 31],
      ["large-family-primary-motivation", "Whittaker consistently describes himself first as a family man; he and his wife have a large family, and he cites providing for them as his central motivation.", 31],
      ["reading-video-games-hobbies", "Outside training, Whittaker has repeatedly listed reading and video games among his main hobbies.", 31],
      ["competition-thrill-training-motivation", "He has said that the competitive challenge and the thrill of testing himself were major reasons he committed to fighting.", 31],
    ],
  ],
  [
    "ufc:chris-weidman",
    [
      ["hofstra-dual-degrees", "Weidman earned a bachelor's degree in psychology and later a master's degree in physical education at Hofstra.", 32],
      ["assistant-wrestling-coach-grad-student", "After his college wrestling career, he stayed at Hofstra as an assistant wrestling coach while also attending graduate school full time.", 33],
      ["jiujitsu-through-helping-mma-fighters", "Weidman's route into jiu-jitsu came while he was helping local MMA fighters with their wrestling; he tried BJJ himself and became absorbed by it.", 33],
      ["grapplers-quest-thirteen-submissions", "Early in his grappling transition, he won both his weight class and the absolute division at Grapplers Quest, submitting all 13 opponents he faced at that event.", 32],
      ["basement-apartment-waited-for-ufc", "As a young husband and father living in a basement apartment, Weidman turned down faster-paying opportunities from other promotions because he wanted to hold out for a UFC opportunity.", 33],
    ],
  ],
  [
    "ufc:sean-strickland",
    [
      ["training-age-fourteen-anger-outlet", "Strickland has said he began martial-arts training around age 14 because combat sports gave him an outlet for anger and were one of the few athletic environments that held his attention.", 34],
      ["professional-since-sixteen", "He turned professional as a teenager and has said fighting has essentially been his only adult career rather than something he entered after a conventional job.", 34],
      ["motorcycle-accident-career-hiatus", "A serious motorcycle crash caused major injuries and kept Strickland out of competition for nearly two years before he returned.", 35],
      ["dogs-motorcycles-outdoor-hobbies", "Outside the gym, Strickland has described spending time with his dogs, riding motorcycles and recreational shooting among his interests.", 34],
      ["unfiltered-no-character-persona", "Strickland has explicitly described his public persona as unfiltered rather than a constructed character, saying that what fans see is essentially how he behaves off camera as well.", 34],
    ],
  ],
  [
    "ufc:brandon-moreno",
    [
      ["family-pinata-business", "Moreno grew up working in his parents' Tijuana piñata business, Piñatas Moreno, which became an important source of income and stability while he trained.", 36],
      ["mma-start-exercise-chubby-kid", "He began MMA at about 12 primarily as exercise after describing himself as a chubby kid who spent a lot of time on video games and junk food; training then became his passion.", 36],
      ["assassin-baby-nickname-debut", "The 'Assassin Baby' nickname dates to his teenage professional debut, when an announcer introduced him that way because of his youthful appearance before a fight with an older-looking opponent.", 37],
      ["lawyer-plan-before-fighting-career", "Before MMA became a realistic career, Moreno had considered studying law and becoming a lawyer, while his parents required him to keep working in the family business as he trained.", 36],
      ["lego-collector-hobby", "Moreno is an enthusiastic LEGO collector and builder; UFC coverage has highlighted the hobby as one of his most recognizable interests away from fighting.", 38],
    ],
  ],
  [
    "ufc:rashad-evans",
    [
      ["police-career-original-goal", "Before MMA became his profession, Evans's original career plan was to become a police officer.", 39],
      ["michigan-state-division-one-wrestler", "Evans wrestled at the NCAA Division I level for Michigan State, giving him the amateur-wrestling base that later shaped his MMA style.", 39],
      ["michigan-state-psychology-degree", "He graduated from Michigan State with a degree in psychology.", 39],
      ["mma-after-graduation-career-pivot", "Evans did not initially treat fighting as his life plan; he moved seriously toward MMA after finishing college and setting aside the law-enforcement path he had expected to follow.", 39],
      ["undersized-heavyweight-tuf2-gamble", "Although naturally closer to light heavyweight, Evans entered The Ultimate Fighter 2 as a heavyweight because it was his chance to reach the UFC, competing against substantially larger castmates.", 40],
    ],
  ],
  [
    "ufc:dominick-cruz",
    [
      ["dominator-high-school-football-joke", "Cruz has explained that 'The Dominator' began as a tongue-in-cheek high-school football nickname while he was an undersized linebacker rather than as a self-created MMA persona.", 41],
      ["customer-service-job-before-fighting", "Before fighting became his career, Cruz worked as a customer-service representative.", 41],
      ["seventh-grade-wrestling-start", "His combat-sports foundation began with wrestling in seventh grade at Flowing Wells in Tucson.", 42],
      ["multi-surgery-injury-comeback", "Cruz's career was dramatically shaped by a long injury cycle that included two surgeries on his left ACL, a groin tear and later a torn right ACL.", 43],
      ["combat-sports-analyst-career", "Alongside and after fighting, Cruz developed a major second career as a combat-sports analyst and broadcaster, earning industry recognition for his analysis.", 42],
    ],
  ],
  [
    "ufc:michael-bisping",
    [
      ["manual-odd-jobs-before-ufc", "Before MMA paid his bills, Bisping worked physically demanding jobs including slaughterhouse work, construction or laboring, and upholstery.", 44],
      ["count-nickname-ancestry", "His 'The Count' nickname originated as a reference to his family ancestry rather than to his fight record or a self-declared royal persona.", 45],
      ["detached-retina-two-surgeries", "A detached retina became one of the defining obstacles of Bisping's career, eventually requiring two surgeries and a long layoff while leaving lasting damage to his vision.", 46],
      ["jiujitsu-childhood-no-holds-barred", "Bisping began jiu-jitsu as a child and, as a teenager, competed in an early British 'no holds barred' event that predated his modern MMA career.", 47],
      ["analyst-commentator-acting-second-career", "He built a substantial post-fighting media career as a UFC commentator and analyst while also taking acting roles in films such as Den of Thieves and xXx: Return of Xander Cage.", 47],
    ],
  ],
  [
    "ufc:quinton-jackson",
    [
      ["poor-memphis-upbringing", "Jackson has described growing up poor in Memphis, being picked on over his clothes, and becoming strongly motivated to create a better life for his mother and siblings.", 48],
      ["wrestling-redirected-street-path", "School wrestling became an important redirection for Jackson after a rough adolescence centered on street fighting, giving his aggression a structured competitive outlet.", 48],
      ["rv-homeless-early-pride", "Early in his professional career after moving from Memphis to California, Jackson went through a period of extreme financial instability and lived in an RV while trying to establish himself as a fighter.", 48],
      ["japan-second-home-family-ties", "His years fighting in Japan made the country a second home to him and created lasting personal and family connections beyond the bouts themselves.", 49],
      ["a-team-ba-baracus-role", "Jackson crossed into mainstream acting by playing B.A. Baracus in the 2010 film The A-Team.", 50],
    ],
  ],
  [
    "ufc:brock-lesnar",
    [
      ["webster-dairy-farm-upbringing", "Lesnar grew up on a dairy farm outside Webster, South Dakota, a rural background that long predated his combat-sports fame.", 51],
      ["ncaa-heavyweight-wrestling-champion", "Before professional wrestling or MMA, Lesnar became an NCAA heavyweight wrestling champion after progressing through junior college and the University of Minnesota.", 51],
      ["wwe-next-big-thing-stardom", "Lesnar became a major WWE star under 'The Next Big Thing' billing before he entered elite MMA.", 51],
      ["minnesota-vikings-nfl-attempt", "At the height of his pro-wrestling fame, Lesnar left WWE to chase a childhood NFL ambition and went through Minnesota Vikings training camp despite not having played college football.", 51],
      ["diverticulitis-colon-surgery", "A severe bout of diverticulitis interrupted his MMA career and ultimately led to surgery in which a section of his colon was removed.", 52],
    ],
  ],
  [
    "ufc:paddy-pimblett",
    [
      ["full-time-training-at-sixteen", "Pimblett began MMA training at about 15 and committed to it full time by 16, later saying he never followed a conventional job path because fighting became his occupation so young.", 53],
      ["liverpool-fc-home-away-passion", "He is a devoted Liverpool FC supporter and has described following the club home and away as his main passion outside MMA.", 53],
      ["big-nog-role-model", "Pimblett has named Antônio Rodrigo Nogueira as a favorite fighter and role model, particularly admiring Nogueira's ability to survive adversity and come back in fights.", 53],
      ["father-of-twin-daughters", "Fatherhood became a major part of Pimblett's public life after he and his wife became parents to twin daughters, Betsy and Margot.", 53],
      ["ricky-mental-health-advocacy", "After the death of his friend Ricky by suicide, Pimblett used a high-profile post-fight interview to urge men to speak openly and seek help rather than silently carry mental-health struggles.", 54],
    ],
  ],
  [
    "ufc:zhang-weili",
    [
      ["sanda-foundation", "Zhang's martial-arts foundation included sanda before she became a professional mixed martial artist.", 55],
      ["civilian-jobs-beijing", "Before fighting could support her, Zhang worked a variety of jobs in Beijing, including supermarket cashier, kindergarten teacher and hotel desk clerk.", 56],
      ["gym-staff-free-training-equipment", "In 2010 she took a staff job at a Beijing gym in part because it gave her free access to training equipment she otherwise could not afford to use regularly.", 56],
      ["injury-hiatus-persistence", "A serious injury interrupted Zhang's early martial-arts development for years, but she eventually returned to training rather than abandoning the goal of competing.", 57],
      ["ufc157-womens-main-event-inspiration", "Watching Ronda Rousey and Liz Carmouche headline UFC 157 helped convince Zhang that women could build a future at the highest level of MMA and made the UFC feel like a realistic dream.", 55],
    ],
  ],
  [
    "ufc:ronda-rousey",
    [
      ["childhood-speech-apraxia", "Rousey had a serious speech difficulty as a young child that was later identified as apraxia, and she spent years in speech therapy before becoming a public athlete and entertainer.", 58],
      ["competitive-swimming-with-father", "Before judo, Rousey spent part of her childhood as a competitive swimmer, a sport she shared closely with her father.", 59],
      ["mother-annmaria-judo-lineage", "She began judo under the influence of her mother, AnnMaria De Mars, who had herself become the first American to win a world judo championship.", 60],
      ["historic-2008-olympic-bronze", "Rousey won bronze in judo at the 2008 Beijing Olympics, becoming the first American woman to win an Olympic judo medal after women's judo became an official Olympic sport.", 60],
      ["pro-wrestling-fandom-wwe-crossover", "She was a longtime professional-wrestling fan before eventually joining WWE herself, turning an existing personal interest into a major second combat-entertainment career.", 61],
    ],
  ],
  [
    "ufc:carla-esparza",
    [
      ["menlo-college-wrestling", "Esparza wrestled for four years at Menlo College and became a two-time collegiate All-American under coach and two-time Olympian Lee Allen.", 62],
      ["business-sports-management-degree", "She earned a business degree with a concentration in sports management.", 62],
      ["bjj-muay-thai-between-wrestling-seasons", "During breaks from collegiate wrestling, Esparza added Brazilian jiu-jitsu and Muay Thai, and the combination helped make MMA feel like a natural next sport.", 62],
      ["personal-training-job", "Alongside her early fight career, Esparza worked as a personal trainer.", 62],
      ["early-career-financial-sacrifice", "Her earliest professional fights were financially precarious enough that medical costs could consume most or all of a purse, and she continued living with her parents while trying to make fighting sustainable.", 63],
    ],
  ],
  [
    "ufc:mackenzie-dern",
    [
      ["father-megaton-bjj-age-three", "Dern grew up inside Brazilian jiu-jitsu: her father is Wellington 'Megaton' Dias, and she began training in his academy at about age three.", 64],
      ["elite-bjj-championship-pedigree", "Before becoming a UFC fighter, she built one of the sport's most recognizable modern women's grappling résumés, including world-level Brazilian jiu-jitsu and ADCC titles.", 64],
      ["professional-bjj-before-mma", "Her occupation before MMA was already professional competition in Brazilian jiu-jitsu rather than a conventional civilian job.", 64],
      ["us-brazil-bilingual-identity", "Born in the United States and raised between the U.S. and Brazil, Dern grew up fluent in English and Portuguese and has described both countries as central to her identity.", 65],
      ["motherhood-jiujitsu-family-continuity", "After becoming a mother, Dern quickly folded daughter Moa into the family's jiu-jitsu culture; UFC coverage noted that Moa had her first gi while still an infant.", 66],
    ],
  ],
  [
    "ufc:holly-holm",
    [
      ["preachers-daughter-nickname", "Holm's 'The Preacher's Daughter' nickname is literal: her father was a Church of Christ preacher for much of her life.", 67],
      ["cardio-kickboxing-accidental-start", "Her combat-sports career began almost accidentally when she took cardio-kickboxing classes for exercise as a teenager and became fascinated by the fighters sparring at the gym.", 67],
      ["boxing-hall-of-fame-career", "Long before her UFC identity was complete, Holm had an elite professional-boxing career that eventually earned induction into major women's and international boxing halls of fame.", 67],
      ["real-estate-license", "Holm attended real-estate school and has maintained a real-estate license outside of fighting.", 67],
      ["server-chiropractic-assistant-jobs", "Her pre-fighting work history included restaurant serving and working as a chiropractic assistant.", 67],
    ],
  ],
  [
    "ufc:nate-diaz",
    [
      ["stockton-martial-arts-solace", "Diaz has described martial arts as a source of structure and refuge while growing up in rough parts of Stockton, California.", 68],
      ["nick-royce-gracie-influence", "His older brother Nick helped steer him toward Brazilian jiu-jitsu by showing him footage of Royce Gracie and bringing him deeper into the martial-arts world.", 68],
      ["cesar-gracie-shark-tank-training", "As a teenager, Nate trained in the Cesar Gracie system alongside experienced fighters such as Nick Diaz, Gil Castillo and Dave Terrell, an environment he recalled as unusually demanding for a young prospect.", 69],
      ["vegan-diet-body-awareness", "Diaz adopted a vegan or heavily plant-based diet as part of the way he manages his body and conditioning, making nutrition a recognizable part of his public identity.", 70],
      ["stockton-gym-youth-teaching", "The Diaz brothers built a Stockton martial-arts academy that serves students of different ages, and Nate has spoken about teaching and passing the sport on locally.", 70],
    ],
  ],
  [
    "ufc:colby-covington",
    [
      ["chaos-nickname-mother-mythology", "Covington has said his mother gave him the nickname 'Chaos,' connecting it both to the Greek-mythology term and to his unpredictable behavior as a child.", 71],
      ["oregon-state-sociology-degree", "He graduated from Oregon State University with a bachelor's degree in sociology.", 71],
      ["pac10-ncaa-wrestling-pedigree", "Covington's foundation was elite collegiate wrestling, including a Pac-10 championship and All-American recognition at Oregon State.", 71],
      ["iowa-to-oregon-state-wrestling-path", "His college path was not linear: he spent time in the Iowa wrestling system and at junior college before transferring to Oregon State, closer to his family, and rebuilding his Division I career there.", 72],
      ["masvidal-roommates-to-rivals", "Covington and Jorge Masvidal were once close friends, teammates and roommates before their relationship deteriorated into one of MMA's most personal rivalries.", 73],
    ],
  ],
  [
    "ufc:yair-rodriguez",
    [
      ["taekwondo-at-five", "Rodriguez's martial-arts background began very young, when his parents enrolled him in taekwondo at about age five.", 74],
      ["discovered-vale-todo-gym", "His route into MMA accelerated when he came across a vale-tudo gym while looking for a place to keep training and decided to try the more complete fighting style.", 75],
      ["parral-to-chicago-training-move", "Rodriguez later left Parral, Mexico for Chicago to train with coaches including Izzy Martinez and Mike Valle, using the move to immerse himself in higher-level preparation away from distractions.", 75],
      ["study-work-training-balancing", "Before he could focus fully on fighting, Rodriguez described trying to balance school, work and training at the same time.", 75],
      ["ranchera-music-personal-tastes", "In his early UFC profile, Rodriguez identified ranchera music among his personal tastes, along with Italian food and beach vacations.", 74],
    ],
  ],
  [
    "ufc:kevin-holland",
    [
      ["kung-fu-humbling-start-age-sixteen", "Holland has said he walked into a kung-fu gym around age 16 with an inflated sense of his fighting ability and was quickly humbled, which convinced him to keep training.", 76],
      ["trailblazer-nickname-school-name", "His 'Trailblazer' nickname traces back to his original kung-fu instructor's plan for a school name built around the phrase 'Trailblazer Achieve More.'", 76],
      ["electrical-apprentice-job", "Before fighting full time, Holland worked as an electrical apprentice.", 76],
      ["dual-black-belts-kungfu-bjj", "Holland's training identity combines a second-degree black belt in kung fu with a Brazilian jiu-jitsu black belt under Travis Lutter.", 76],
      ["big-mouth-midfight-talking-persona", "His habit of talking during fights became a signature trait early in his UFC path; Dana White even labeled him 'Big Mouth' after hearing him jaw throughout a Contender Series bout.", 77],
    ],
  ],
  [
    "ufc:gilbert-burns",
    [
      ["childhood-bronchitis-sports-catalyst", "Burns has explained that childhood asthmatic bronchitis helped push him toward sports after a doctor recommended physical activity, with swimming among his earliest organized activities.", 78],
      ["upholstery-barter-bjj-scholarship", "Because his family could not easily afford jiu-jitsu, Burns's upholsterer father bartered work on a customer's car seats in exchange for an initial stretch of BJJ training for his sons.", 78],
      ["durinho-nickname-brother-diminutive", "The nickname 'Durinho' is a diminutive play on his older brother Frederick's nickname 'Todo Duro' and was coined in the jiu-jitsu environment around Vitor 'Shaolin' Ribeiro.", 78],
      ["bjj-world-title-before-mma", "Burns deliberately wanted to win a major black-belt jiu-jitsu world title before turning his attention fully to MMA; after accomplishing that goal in 2011, he made the transition.", 78],
      ["belfort-cornerman-hooft-connection", "Before his own UFC run, Burns cornered Vitor Belfort at UFC 133, where he first crossed paths with striking coach Henri Hooft, who later became a major long-term coach and mentor for Burns.", 79],
    ],
  ],
  [
    "ufc:nick-diaz",
    [
      ["unstable-school-upbringing", "Diaz has described an unsettled school-age upbringing in which he moved among many schools and was regularly roughed up by older kids, making martial-arts training an important source of structure.", 80],
      ["jiujitsu-community-social-skills", "He has said the jiu-jitsu gym gave him a community he lacked elsewhere and helped him develop confidence and social skills as a teenager.", 80],
      ["two-pre-fight-jobs", "Diaz has recalled having only two conventional jobs before committing to fighting: work at a collections agency and running wires under buildings.", 80],
      ["stockton-slap-grandfather-origin", "Diaz has connected his signature open-hand slap to a childhood memory of his grandfather striking him with an open hand; fans later came to call Diaz's version the 'Stockton Slap.'", 81],
      ["offroad-triathlon-passion", "Endurance sports are a genuine hobby for Diaz: he has described doing multiple triathlons a year, with a particular interest in off-road events.", 82],
    ],
  ],
] as const;
