// PR10 UFC person-identity research data batch 8. Canonical validation and lookup remain in ufcPersonIdentityKnowledge.ts.
export const ufcPersonIdentityResearchSources8 = [
  ["https://www.ufc.com/news/brazil-aldo-king-honed-humble-roots", "UFC", "In Brazil Aldo is King, honed by humble roots"],
  ["https://www.ufc.com/news/legendary-moura-discusses-aldos-evolution", "UFC", "Legendary Moura Discusses Aldo's Evolution"],
  ["https://www.ufc.com/news/jose-aldo-el-maradona-de-las-amm", "UFC", "José Aldo: El \"Maradona\" de las AMM"],
  ["https://www.ufc.com/news/lifetime-challenges-daniel-cormier-confronts-fight-his-life", "UFC", "In A Lifetime of Challenges, Daniel Cormier Confronts the Fight of His Life"],
  ["https://www.ufc.com/news/daniel-cormier-named-to-the-ufc-hall-of-fame-modern-wing-class-of-2022", "UFC", "Daniel Cormier Named To UFC Hall of Fame | Class of 2022"],
  ["https://www.espn.com/mma/story/_/id/39914950/ufc-300-there-always-plan-charles-oliveira", "ESPN", "UFC 300: There has always been a plan for Charles Oliveira"],
  ["https://www.ufc.com/news/no-more-pipe-dreams-edgar", "UFC", "No More Pipe Dreams For Edgar"],
  ["https://www.ufc.com/athlete/frankie-edgar", "UFC", "Frankie Edgar | UFC"],
  ["https://www.ufc.com/news/frankie-edgar-dreams-reality", "UFC", "Frankie Edgar: From dreams to reality"],
  ["https://www.ufc.com/news/frankie-edgar-begins-new-adventure-ufc-gym-owner", "UFC", "Frankie Edgar begins new adventure as UFC GYM owner"],
  ["https://www.mmafighting.com/2009/10/06/189429/humble-ben-henderson-makes-big-statement-i-will-be-the-best", "MMA Fighting", "Humble Ben Henderson Makes Big Statement: 'I Will Be the Best'"],
  ["https://www.mmafighting.com/2023/4/2/23640361/benson-henderson-admits-hidden-toothpick-in-mouth-for-a-lot-of-ufc-fights-accidentally-swallowed", "MMA Fighting", "Benson Henderson admits he had hidden toothpick in mouth for 'a lot of fights,' recalls time he accidentally swallowed it"],
  ["https://www.ufc.com/news/bj-penn-el-hombre-el-prodigio-la-leyenda", "UFC", "BJ Penn, el hombre, el prodigio, la leyenda"],
  ["https://www.ufc.com/news/jay-dee-penn-father-bj-dana-white-fertitta-1945-2021", "UFC", "Jay Dee Penn 1945-2021"],
  ["https://www.ufc.com/news/bj-penn-joins-ufc-hall-fame-july", "UFC", "BJ Penn Joins the UFC Hall of Fame in July"],
  ["https://www.ufc.com/news/brothers-armbars-raw-story", "UFC", "Brothers in Armbars - raw story"],
  ["https://www.espn.com/mma/story/_/id/21759989/glover-teixeira-my-life-fighter", "ESPN", "My life as a fighter: Glover Teixeira"],
  ["https://www.ufc.com/news/making-glover-teixeira-urban-legend-ufc-star", "UFC", "Making Glover Teixeira: Urban legend to UFC star"],
  ["https://www.espn.com/mma/story/_/id/27208469/ufc-278-kamaru-usman-vs-leon-edwards-mma-saved-being-dead-prison-dead-broke", "ESPN", "Leon Edwards: MMA saved me from being 'dead, in prison or dead broke'"],
  ["https://www.espn.com/mma/story/_/id/40642235/ufc-304-making-golden-generation-english-mma-leon-edwards-tom-aspinall-michael-bisping", "ESPN", "Bisping, Edwards and Aspinall: Inside the making of English MMA's golden generation"],
  ["https://www.mmafighting.com/2015/6/9/8735917/losing-to-girlfriends-ex-boyfriend-changed-fabricio-werdum-s-life", "MMA Fighting", "Losing to girlfriend's ex-boyfriend changed Fabricio Werdum's life forever"],
  ["https://www.ufc.com/news/werdum-el-brasileno-mas-espanol-del-ufc", "UFC", "Werdum: El brasileño más español del UFC"],
  ["https://www.ufc.com/news/fabricio-werdum-se-une-como-analista-en-espanol-en-ufc", "UFC", "Fabricio Werdum se une como analista en español en UFC"],
  ["https://www.ufc.com/news/another-new-start-tony-ferguson", "UFC", "Another New Start for Tony Ferguson"],
  ["https://www.ufc.com/athlete/tony-ferguson", "UFC", "Tony Ferguson | UFC"],
  ["https://www.ufc.com/news/tony-fergusons-perfect-storm", "UFC", "Tony Ferguson's Perfect Storm"],
  ["https://www.ufc.com/news/after-recovering-injury-tony-ferguson-feels-better-ever", "UFC", "After Recovering From Injury, Tony Ferguson Feels Better Than Ever"],
] as const;

export const ufcPersonIdentityResearch8 = [
  ["ufc:jose-aldo", [
    ["childhood-cheek-scar", "Aldo's recognizable cheek scar came from a childhood accident involving a hot grill.", 0],
    ["soccer-first-ambition", "Aldo originally tried to become a professional soccer player before fighting became his career.", 1],
    ["manaus-to-rio-leap", "As a young fighter, Aldo left Manaus for Rio de Janeiro to pursue training at Nova União despite having very little money or support in the city.", 0],
    ["nova-uniao-mats-and-hunger", "Early in Rio, Aldo slept on mats at the academy and sometimes lacked money for food, with teammates and people around the gym helping him with meals and clothing.", 1],
    ["capoeira-before-jiu-jitsu", "Aldo began in capoeira before later adding Brazilian jiu-jitsu, an origin that helped shape the unusually athletic kicking and movement associated with his style.", 2],
  ]],
  ["ufc:daniel-cormier", [
    ["father-killed-when-seven", "Cormier's father was killed in a shooting on Thanksgiving Day when Cormier was seven years old.", 3],
    ["all-state-football-to-wrestling", "Cormier was an all-state high-school linebacker with a football opportunity at LSU, but academics helped steer him toward junior-college wrestling instead.", 3],
    ["daughter-kaedyn-loss", "Cormier's infant daughter Kaedyn died in a 2003 automobile crash, a loss he has discussed as one of the defining tragedies of his life.", 3],
    ["2008-olympic-weight-cut-crisis", "As captain of the 2008 U.S. Olympic wrestling team, Cormier was hospitalized after his body shut down during a severe weight cut and he was unable to compete.", 3],
    ["gilroy-high-wrestling-coach", "Outside fighting and broadcasting, Cormier became a high-school wrestling coach at Gilroy High School and later built a youth wrestling academy.", 4],
  ]],
  ["ufc:charles-oliveira", [
    ["childhood-arthritis-heart-murmur", "At about eight years old, Oliveira was diagnosed with rheumatoid arthritis and a heart murmur and was initially told to avoid vigorous activity.", 5],
    ["jiu-jitsu-despite-medical-restrictions", "A family friend introduced Oliveira to Brazilian jiu-jitsu around age 12; he became obsessed with it and continued training while still receiving medical treatment.", 5],
    ["do-bronx-neighborhood-identity", "Oliveira's 'Do Bronx' name is a reference to being from the favela or neighborhood where he grew up.", 5],
    ["community-raffle-funded-us-trip", "When Oliveira needed money for his first trip to the United States for an MMA opportunity, people in his community organized a raffle at a local market to help fund it.", 5],
    ["family-fight-week-fasting-ritual", "During fight weeks, Oliveira's parents have fasted with him in solidarity with his weight cut, while his grandmother sends a voice message that he repeatedly listens to.", 5],
  ]],
  ["ufc:frankie-edgar", [
    ["union-plumber-double-life", "Edgar worked full shifts as a union plumber while already competing in the UFC, then coached wrestling before training at night.", 6],
    ["clarion-division-one-wrestler", "At Clarion University, Edgar qualified for the NCAA Division I wrestling championships in each of his four years.", 7],
    ["political-science-degree", "Edgar earned a bachelor's degree in Political Science from Clarion University.", 7],
    ["sixty-dollar-first-fight", "Edgar has recalled earning only $60 for his first MMA fight, breaking his orbital bone in the bout, with his future wife Renee in attendance.", 8],
    ["wrestling-school-and-gym-owner", "Edgar later became an entrepreneur in his hometown area, owning a wrestling school and opening a UFC GYM location.", 9],
  ]],
  ["ufc:benson-henderson", [
    ["korean-mother-taekwondo-tradition", "Henderson's Korean mother insisted that he and his brother learn taekwondo when they were young as a way to connect with Korean culture and tradition.", 10],
    ["dana-college-wrestling-all-american", "Henderson fell in love with wrestling after wandering into a wrestling room and later became a two-time NAIA All-American at Dana College.", 10],
    ["criminal-justice-sociology-double-major", "Henderson double-majored in criminal justice and sociology in college.", 10],
    ["declined-police-career-for-mma", "After college, Henderson passed police testing and received job offers from departments in Omaha and Denver, but chose to pursue MMA instead.", 10],
    ["toothpick-fight-habit", "Henderson admitted that for many fights he secretly kept a toothpick in his mouth while competing and even once accidentally swallowed one.", 11],
  ]],
  ["ufc:bj-penn", [
    ["baby-jay-name-origin", "Penn was born Jay Dee Penn; with his father and older brothers also sharing the Jay Dee name, the youngest became known as 'Baby Jay,' which was shortened to B.J.", 12],
    ["neighbor-tom-callos-bjj-introduction", "Penn was introduced to Brazilian jiu-jitsu as a teenager through Tom Callos, a neighbor and tenant connected to the Penn family.", 13],
    ["prodigy-rapid-black-belt-rise", "Penn earned a Brazilian jiu-jitsu black belt in less than three years and became the first American to win a black-belt world championship, helping establish 'The Prodigy' identity.", 14],
    ["penn-brothers-training-family", "B.J. and his brothers trained together for years and helped build a family-centered martial-arts culture in Hilo.", 15],
    ["father-career-supporter", "Penn's father, Jay Dee Penn Sr., was a master carpenter and businessman who strongly supported his sons' martial-arts pursuits and helped B.J. navigate his early career.", 13],
  ]],
  ["ufc:glover-teixeira", [
    ["brazilian-farm-upbringing", "Teixeira grew up in the rural Brazilian town of Sobrália on a farm before emigrating to the United States as a teenager.", 16],
    ["connecticut-landscaping-job", "After moving to Connecticut around age 19, Teixeira worked in landscaping and sent money home to help his family.", 16],
    ["royce-tape-changed-boxing-plan", "Teixeira initially wanted to box, but watching a tape of Royce Gracie at UFC 1 redirected him toward mixed martial arts and jiu-jitsu.", 17],
    ["hackleman-liddell-mentorship", "John Hackleman invited Teixeira to train in California, where Chuck Liddell became an important training partner and influence on his striking and wrestling development.", 17],
    ["visa-exile-delayed-us-return", "Immigration and visa problems forced Teixeira to leave the United States for Brazil for years, delaying the American chapter of his career until the issue was resolved.", 17],
  ]],
  ["ufc:leon-edwards", [
    ["kingston-to-birmingham-childhood", "Edwards was born in Kingston, Jamaica, where his family lived in a modest wooden home with a zinc roof, before moving to Birmingham, England.", 18],
    ["father-killed-in-london", "Edwards' father was shot and killed in London when Edwards was a teenager, a turning point he has openly linked to a turbulent period in his life.", 18],
    ["street-gang-path-before-mma", "As a teenager in Birmingham, Edwards became involved in street violence and gang activity before martial arts gave him a different path.", 18],
    ["mother-pushed-him-into-mma-gym", "Edwards credits his mother with pushing him into an MMA gym as a teenager after she saw a local gym opening and wanted him away from the streets.", 19],
    ["brother-fabian-pro-fighter", "Leon Edwards' younger brother Fabian also became a professional mixed martial artist, making fighting a family profession.", 19],
  ]],
  ["ufc:fabricio-werdum", [
    ["girlfriends-ex-started-bjj-path", "Werdum has said a beach confrontation in which his girlfriend's ex-boyfriend, a jiu-jitsu practitioner, easily controlled him pushed him to begin Brazilian jiu-jitsu training.", 20],
    ["spain-long-term-home", "Werdum moved to Spain after establishing himself in jiu-jitsu and lived there for years, becoming fluent enough in Spanish to be closely identified with Spanish-speaking MMA audiences.", 21],
    ["ufc-spanish-analyst", "While still an active fighter, Werdum joined UFC's Spanish-language pay-per-view broadcasts as an analyst.", 22],
    ["cro-cop-croatia-japan-bridge", "Werdum went from Spain to Croatia to train Mirko Cro Cop, and that relationship helped open the door to Werdum's fighting career in Japan.", 21],
    ["vai-cavalo-nickname", "Werdum is known by the Portuguese nickname 'Vai Cavalo,' a horse-related phrase often rendered approximately as 'go horse.'", 21],
  ]],
  ["ufc:tony-ferguson", [
    ["three-sport-varsity-athlete", "Ferguson lettered repeatedly in football, baseball and wrestling in high school, with organized sports becoming a major part of his Michigan upbringing.", 23],
    ["el-cucuy-nickname-meaning", "Ferguson's 'El Cucuy' nickname refers to the Spanish boogeyman.", 23],
    ["bartender-before-fighting", "Ferguson has said the longest-running job he held before fighting full time was bartending, a job he enjoyed because of the constant interaction with people.", 24],
    ["hunting-taught-patience", "Ferguson has credited lessons from hunting with his father for teaching him patience and the value of staying quiet and focused.", 25],
    ["unconventional-self-designed-training", "Ferguson became known for self-designed, unconventional training methods, including tire work and a routine he called 'Cucuy's Cold Cool Down,' which he said always had a purpose even when it looked unusual.", 26],
  ]],
] as const;
