// PR10 UFC person-identity research data batch 3. Canonical validation and lookup remain in ufcPersonIdentityKnowledge.ts.
export const ufcPersonIdentityResearchSources3 = [
  ["https://www.ufc.com/news/comeback-anderson-silva-never-really-left", "UFC", "Comeback? Anderson Silva never really left"],
  ["https://www.ufc.com/news/say-it-again-anderson-silvas-greatest-soundbytes", "UFC", "Say it again: Anderson Silva's greatest soundbytes"],
  ["https://www.ufc.com/news/spider-says-silvas-quotes", "UFC", "The Spider Says – Silva's Quotes"],
  ["https://www.sbs.com.au/language/macedonian/en/podcast-episode/from-rugby-league-to-ufc-champ-meet-alexander-the-great-volkanovski/jmty4b72p", "SBS Macedonian", "From Rugby League to UFC champ: meet Alexander \"The Great\" Volkanovski"],
  ["https://www.espn.com/mma/story/_/id/28234665/ufc-alexander-volkanovksi-humble-local-hero-focus-swayed", "ESPN", "Volkanovski the humble local hero whose focus can't be swayed"],
  ["https://www.ufc.com/news/joe-lopez-says-personality-clash-fuels-featherweight-champion-alexander-volkanovski-ufc-266", "UFC", "Joe Lopez: 'Personality Clash' Fuels Volkanovski In A New Way"],
  ["https://www.ufc.com/news/kamaru-usman-reflects-on-his-return-to-nigeria", "UFC", "Kamaru Usman Reflects On His Return To Nigeria"],
  ["https://www.espn.com/espn/feature/story/_/page/Coverstory-April2021/the-reign-kamaru-usman", "ESPN", "The reign of Kamaru Usman"],
  ["https://www.ufc.com/news/its-still-kamaru-usman-time-main-event-ufc-278", "UFC", "It's Still Kamaru Usman Time"],
  ["https://www.espn.com/mma/story/_/id/29424043/fight-island-story-kamaru-usman-father-texas-prison", "ESPN", "Fight Island -- The inside story of Kamaru Usman, his father and a Texas prison"],
  ["https://www.ufc.com/news/brazil-aldo-king-honed-humble-roots", "UFC", "In Brazil Aldo is King, honed by humble roots"],
  ["https://www.ufc.com/news/legendary-moura-discusses-aldos-evolution", "UFC", "Legendary Moura Discusses Aldo's Evolution"],
  ["https://www.ufc.com/news/jose-aldo-el-maradona-de-las-amm", "UFC", "José Aldo: El \"Maradona\" de las AMM"],
  ["https://www.ufc.com/news/lifetime-challenges-daniel-cormier-confronts-fight-his-life", "UFC", "In A Lifetime of Challenges, Daniel Cormier Confronts the Fight of His Life"],
  ["https://www.ufc.com/news/daniel-cormier-named-to-the-ufc-hall-of-fame-modern-wing-class-of-2022", "UFC", "Daniel Cormier Named To UFC Hall of Fame | Class of 2022"],
  ["https://www.espn.com/mma/story/_/id/39914950/ufc-300-there-always-plan-charles-oliveira", "ESPN", "UFC 300: There has always been a plan for Charles Oliveira"],
  ["https://www.ufc.com/news/no-more-pipe-dreams-edgar", "UFC", "No More Pipe Dreams For Edgar"],
  ["https://www.ufc.com/athlete/frankie-edgar", "UFC", "Frankie Edgar | UFC"],
  ["https://www.ufc.com/news/frankie-edgar-dreams-reality", "UFC", "Frankie Edgar: From dreams to reality"],
  ["https://www.ufc.com/news/frankie-edgar-begins-new-adventure-ufc-gym-owner", "UFC", "Frankie Edgar begins new adventure as UFC GYM owner"],
  ["https://www.mmafighting.com/2009/10/06/189429/humble-ben-henderson-makes-big-statement-i-will-be-the-best", "MMA Fighting", "Humble Ben Henderson Makes Big Statement: 'I Will Be the Best'"],
  ["https://www.mmafighting.com/2023/4/2/23640361/benson-henderson-admits-hidden-toothpick-in-mouth-for-a-lot-of-ufc-fights-accidentally-swallowed", "MMA Fighting", "Benson Henderson admits he had hidden toothpick in mouth for 'a lot of fights,' recalls time he accidentally swallowed it"],
  ["https://www.ufc.com/news/bj-penn-el-hombre-el-prodigio-la-leyenda", "UFC", "BJ Penn, el hombre, el prodigio, la leyenda"],
  ["https://www.ufc.com/news/jay-dee-penn-father-bj-dana-white-fertitta-1945-2021", "UFC", "Jay Dee Penn 1945-2021"],
  ["https://www.ufc.com/news/bj-penn-joins-ufc-hall-fame-july", "UFC", "BJ Penn Joins the UFC Hall of Fame in July"],
  ["https://www.ufc.com/news/brothers-armbars-raw-story", "UFC", "Brothers in Armbars - raw story"],
  ["https://www.espn.com/mma/story/_/id/21759989/glover-teixeira-my-life-fighter", "ESPN", "My life as a fighter: Glover Teixeira"],
  ["https://www.ufc.com/news/making-glover-teixeira-urban-legend-ufc-star", "UFC", "Making Glover Teixeira: Urban legend to UFC star"],
  ["https://www.espn.com/mma/story/_/id/27208469/ufc-278-kamaru-usman-vs-leon-edwards-mma-saved-being-dead-prison-dead-broke", "ESPN", "Leon Edwards: MMA saved me from being 'dead, in prison or dead broke'"],
  ["https://www.espn.com/mma/story/_/id/40642235/ufc-304-making-golden-generation-english-mma-leon-edwards-tom-aspinall-michael-bisping", "ESPN", "Bisping, Edwards and Aspinall: Inside the making of English MMA's golden generation"],
  ["https://www.mmafighting.com/2015/6/9/8735917/losing-to-girlfriends-ex-boyfriend-changed-fabricio-werdum-s-life", "MMA Fighting", "Losing to girlfriend's ex-boyfriend changed Fabricio Werdum's life forever"],
  ["https://www.ufc.com/news/werdum-el-brasileno-mas-espanol-del-ufc", "UFC", "Werdum: El brasileño más español del UFC"],
  ["https://www.ufc.com/news/fabricio-werdum-se-une-como-analista-en-espanol-en-ufc", "UFC", "Fabricio Werdum se une como analista en español en UFC"],
  ["https://www.ufc.com/news/another-new-start-tony-ferguson", "UFC", "Another New Start for Tony Ferguson"],
  ["https://www.ufc.com/athlete/tony-ferguson", "UFC", "Tony Ferguson | UFC"],
  ["https://www.ufc.com/news/tony-fergusons-perfect-storm", "UFC", "Tony Ferguson's Perfect Storm"],
  ["https://www.ufc.com/news/after-recovering-injury-tony-ferguson-feels-better-ever", "UFC", "After Recovering From Injury, Tony Ferguson Feels Better Than Ever"],
  ["https://www.espn.com/extra/mma/news/story?id=3638757", "ESPN", "Brothers Ken, Frank Shamrock itching to fight"],
  ["https://www.si.com/more-sports/2010/06/29/shamrock", "Sports Illustrated", "Shamrock's legacy stretches beyond the cage; more MMA notes"],
  ["https://www.espn.com/mma/story/_/id/30348955/ufc-champ-deiveson-figueiredo-put-work-sushi-chef-hairdresser", "ESPN", "UFC champ Deiveson Figueiredo has put in the work -- from sushi chef to hairdresser"],
  ["https://www.ufc.com/news/vitor-belfort-fightography-now-live-ufc-fight-pass", "UFC", "Vitor Belfort Fightography now live on UFC FIGHT PASS"],
  ["https://www.ufc.com/news/vitor-belfort-named-ufc-hall-fame-class-2025", "UFC", "VITOR BELFORT NAMED TO UFC HALL OF FAME CLASS OF 2025"],
  ["https://www.ufc.com/news/vitor-belfort-diet", "UFC", "The Vitor Belfort Diet"],
  ["https://www.ufc.com/news/defining-phenom", "UFC", "Defining \"The Phenom\""],
  ["https://www.ufc.com/news/tom-aspinall-thrives-under-pressure-heavyweight-ufc-fight-night-brunson-till", "UFC", "Tom Aspinall Thrives Under Pressure | UFC Fight Night: Brunson vs Till"],
  ["https://www.ufc.com/news/tom-aspinall-london-no-going-anywhere-heavyweight-ufc-main-event", "UFC", "Tom Aspinall Not Going Anywhere"],
  ["https://www.espn.com/mma/story/_/id/46706704/ufc-321-secrets-tom-aspinall-heavyweight-fighting-approach", "ESPN", "UFC 321: Inside Tom Aspinall's unique heavyweight strategy"],
  ["https://www.espn.com/mma/story/_/id/9964541/family-tradition", "ESPN", "The Gracies: A family tradition"],
  ["https://www.ufc.com/news/ufc-turns-30-years-old", "UFC", "UFC At 30: Looking Back At Three Decades Of Changing The Game"],
  ["https://www.ufc.com/news/gracie-way", "UFC", "The Gracie Way"],
  ["https://www.mmafighting.com/2010/08/17/183020/showtime-pettis-plans-to-exploit-shane-rollers-holes-seize-w", "MMA Fighting", "‘Showtime’ Pettis Plans to Exploit Shane Roller’s Holes, Seize WEC Spotlight"],
  ["https://www.ufc.com/news/when-its-showtime-anthony-pettis-turns-chaos-comfort", "UFC", "When It's Showtime, Anthony Pettis Turns Chaos Into Comfort"],
  ["https://www.ufc.com/news/pettis-ready-defend", "UFC", "Pettis Ready to Defend"],
  ["https://www.ufc.com/news/anthony-pettis-finally-its-showtime", "UFC", "Anthony Pettis: Finally, It's Showtime"],
  ["https://www.ufc.com/athlete/mauricio-rua", "UFC", "Mauricio Rua | UFC"],
  ["https://www.ufc.com/news/how-chute-boxe-created-brazil-ufc-legends", "UFC", "How Chute Boxe created Brazil UFC legends"],
  ["https://www.ufc.com/news/shogun-returns-his-second-home", "UFC", "Shogun Returns to His Second Home"],
  ["https://www.ufc.com/news/shogun-back-what-was-center-mma", "UFC", "Shogun back in what was the center of MMA"],
  ["https://www.ufc.com/news/dan-henderson-fue-dos-veces-seleccionado-olimpico", "UFC", "Dan Henderson fue dos veces seleccionado olímpico"],
  ["https://www.ufc.com/news/dan-henderson-ufc-career-three-parts", "UFC", "Dan Henderson: A UFC Career in Three Parts"],
  ["https://www.ufc.com/news/nunes-travels-hard-fought-path-stardom", "UFC", "Nunes travels hard-fought path to stardom"],
  ["https://www.ufc.com/athlete/amanda-nunes", "UFC", "Amanda Nunes | UFC"],
  ["https://www.ufc.com/news/joanna-jedrzejczyk-born", "UFC", "Joanna Jedrzejczyk: Born for This"],
  ["https://www.ufc.com/news/jedrzejczyk-took-tough-road-grand-dreams", "UFC", "Jedrzejczyk took tough road to grand dreams"],
  ["https://www.ufc.com/athlete/joanna-jedrzejczyk", "UFC", "Joanna Jędrzejczyk | UFC"],
  ["https://www.ufc.com/athlete/jessica-andrade", "UFC", "Jessica Andrade | UFC"],
  ["https://www.ufc.com/news/jessica-andrade-full-speed-ahead", "UFC", "Jessica Andrade: Full Speed Ahead"],
  ["https://www.espn.com/mma/ufc/story/_/id/27647180/mexico-strawweight-alexa-grasso-ready-live-ufc-expectations", "ESPN", "Alexa Grasso ready to live up to expectations"],
  ["https://www.ufc.com/athlete/alexa-grasso", "UFC", "Alexa Grasso | UFC"],
  ["https://www.ufc.com/news/pena-once-directionless-found-her-way-through-fighting", "UFC", "Pena, once directionless, found her way through fighting"],
  ["https://www.espn.com/blog/onenacion/post/_/id/5584/julianna-pena-mmas-venezuelan-vixen-wants-to-fight-the-good-fight", "ESPN", "Julianna Pena: MMA's Venezuelan Vixen wants to fight the good fight"],
  ["https://www.ufc.com/athlete/julianna-pena", "UFC", "Julianna Peña | UFC"],
  ["https://www.mmafighting.com/2014/1/31/5365176/michael-chiesa-on-julianna-pena-injury-situation-this-whole-thing-is", "MMA Fighting", "Michael Chiesa on Julianna Pena injury situation: 'This whole thing is pretty devastating'"],
  ["https://www.mmafighting.com/2016/7/4/12066124/from-little-donkey-to-ufc-champion-how-rafael-dos-anjos-beat-the-odds", "MMA Fighting", "From 'little donkey' to UFC champion: How Rafael dos Anjos beat the odds"],
  ["https://www.ufc.com.br/news/espantosa-evolucao-de-rafael-dos-anjos", "UFC", "A espantosa evolução de Rafael dos Anjos"],
  ["https://www.ufc.com.br/athlete/rafael-dos-anjos", "UFC", "Rafael dos Anjos | UFC"],
  ["https://www.espn.com/mma/story/_/id/28029101/what-need-know-donald-cowboy-cerrone", "ESPN", "What you need to know about Donald 'Cowboy' Cerrone"],
  ["https://www.espn.com/espn/feature/story/_/id/26642572/cowboy-cerrone-wild-ride-bmf-ranch-filled-danger-danger", "ESPN", "Cowboy's wild ride"],
  ["https://www.ufc.com/news/stephen-thompson-karates-back-20", "UFC", "Stephen Thompson - Karate's Back 2.0"],
  ["https://www.ufc.com/athlete/stephen-thompson", "UFC", "Stephen Thompson | UFC"],
  ["https://www.ufc.com/news/stephen-thompson-mma-evangelist", "UFC", "Stephen Thompson - The MMA Evangelist"],
  ["https://www.espn.com/mma/story/_/id/18015888/stephen-thompson-champion-karate-hopes-become-ufc-welterweight-champion-ufc-209", "ESPN", "Stephen Thompson: Champion in karate, hopes to become UFC welterweight champion"],
  ["https://www.ufc.com/news/derrick-lewis-reflects-his-journey-top-ufc-247-heavyweight", "UFC", "Derrick Lewis Reflects On His Journey To The Top"],
  ["https://www.mmafighting.com/2014/6/22/5829788/no-small-wonder-derrick-lewis-journey-from-sugar-land-to-the-promised", "MMA Fighting", "No small wonder: Derrick Lewis' journey from Sugar Land to the Promised Land"],
  ["https://www.ufc.com/news/derrick-lewis-goes-hands-help-houston-flood-victims", "UFC", "Derrick Lewis Goes Hands-On To Help Houston Flood Victims"],
  ["https://www.mmafighting.com/2019/8/17/20809028/troublemaker-paulo-costa-endless-quest-greatness-ufc", "MMA Fighting", "'Troublemaker': Paulo Costa's endless quest for greatness"],
  ["https://www.espn.com/mma/story/_/id/29931659/the-ufc-best-nicknames-stories-them", "ESPN", "The UFC's best nicknames and the stories behind them"],
  ["https://www.ufc.com/news/fighting-has-always-been-part-tai-tuivasa", "UFC", "Fighting has always been a part of Tai Tuivasa"],
  ["https://www.espn.com/mma/story/_/id/33202812/ufc-271-tai-tuivasa-talks-shoeys-fta-life-unlikely-role-model", "ESPN", "'From The Area': Tai Tuivasa's shoey has become more than just a celebration"],
  ["https://www.ufc.com/athlete/diego-lopes", "UFC", "Diego Lopes | UFC"],
  ["https://www.mmafighting.com/2025/4/9/24398105/8-cent-meals-bucket-shower-mexican-dream-improbable-rise-diego-lopes", "MMA Fighting", "8-cent meals, bucket shower and Mexican dream: The improbable rise of Diego Lopes"],
  ["https://www.ufc.com/news/diego-lopes-enjoys-responsibility-opening-ufc-freedom-250", "UFC", "Diego Lopes Enjoys Responsibility of Opening UFC Freedom 250"],
] as const;

export const ufcPersonIdentityResearch3 = [
  [
    "ufc:anderson-silva",
    [
      ["raised-by-aunt-and-uncle", "Silva has described being left by his parents when he was very young and being raised by an aunt and uncle, with his uncle serving in the military.", 0],
      ["childhood-soccer-ambition", "Before fighting became his path, Silva wanted to play soccer, but his family's limited finances made organized sports and training difficult.", 0],
      ["spider-man-comic-collector", "Silva said he collected every Spider-Man comic-book series from 1984 onward and identified with Spider-Man because, unlike richer or otherworldly superheroes, he still had ordinary bills to pay.", 1],
      ["practical-joker-personality", "Silva has described himself as a practical joker who likes making people laugh; one story he told was hiding his cousin's tuxedo on the cousin's wedding day.", 1],
      ["royce-gracie-ufc1-inspiration", "Silva said watching Royce Gracie at UFC 1 made competing in the UFC a dream of his.", 2],
    ],
  ],
  [
    "ufc:alexander-volkanovski",
    [
      ["alexander-the-great-nickname-heritage", "Volkanovski changed an earlier 'Hulk' nickname to 'Alexander the Great,' tying the name to his Macedonian and Greek family heritage.", 3],
      ["national-level-wrestling-background", "Before rugby league and MMA, Volkanovski trained in Greco-Roman and freestyle wrestling and told SBS he won two Australian national wrestling titles.", 3],
      ["warilla-gorillas-rugby-league", "Volkanovski played rugby league for the Warilla Gorillas, including a 2011 premiership season, and competed at roughly 97 kg before eventually fighting at featherweight.", 3],
      ["family-concreting-trade", "Volkanovski came from a family of concreters and worked in concreting before fighting became his full-time career.", 4],
      ["rugby-conditioning-led-to-mma-coach", "Volkanovski first entered Joe Lopez's Freestyle Fighting Gym with rugby teammates for preseason conditioning; Lopez became his long-term MMA coach.", 5],
    ],
  ],
  [
    "ufc:kamaru-usman",
    [
      ["nigeria-to-dallas-childhood", "Usman was born in Auchi, Nigeria, and moved with his family to the Dallas area when he was about eight years old.", 6],
      ["marty-wrestling-nickname", "A high-school wrestling coach who struggled with 'Kamarudeen' called him 'Marty,' a nickname that followed Usman through much of his wrestling career before he publicly reclaimed Kamaru.", 7],
      ["olympic-wrestling-dream", "Usman trained at the U.S. Olympic Training Center with the goal of making an Olympic wrestling team before committing fully to MMA.", 8],
      ["rashad-evans-mma-bridge", "Rashad Evans became an important bridge from Usman's wrestling world into MMA while Usman was at the Olympic Training Center.", 8],
      ["father-prison-and-tv-fights", "While Usman's father served a federal prison sentence, Usman tried to keep early UFC appearances on television rather than pay-per-view so his father and other inmates could watch them.", 9],
    ],
  ],
  [
    "ufc:jose-aldo",
    [
      ["childhood-cheek-scar", "Aldo's recognizable cheek scar came from a childhood accident involving a hot grill.", 10],
      ["soccer-first-ambition", "Aldo originally tried to become a professional soccer player before fighting became his career.", 11],
      ["manaus-to-rio-leap", "As a young fighter, Aldo left Manaus for Rio de Janeiro to pursue training at Nova União despite having very little money or support in the city.", 10],
      ["nova-uniao-mats-and-hunger", "Early in Rio, Aldo slept on mats at the academy and sometimes lacked money for food, with teammates and people around the gym helping him with meals and clothing.", 11],
      ["capoeira-before-jiu-jitsu", "Aldo began in capoeira before later adding Brazilian jiu-jitsu, an origin that helped shape the unusually athletic kicking and movement associated with his style.", 12],
    ],
  ],
  [
    "ufc:daniel-cormier",
    [
      ["father-killed-when-seven", "Cormier's father was killed in a shooting on Thanksgiving Day when Cormier was seven years old.", 13],
      ["all-state-football-to-wrestling", "Cormier was an all-state high-school linebacker with a football opportunity at LSU, but academics helped steer him toward junior-college wrestling instead.", 13],
      ["daughter-kaedyn-loss", "Cormier's infant daughter Kaedyn died in a 2003 automobile crash, a loss he has discussed as one of the defining tragedies of his life.", 13],
      ["2008-olympic-weight-cut-crisis", "As captain of the 2008 U.S. Olympic wrestling team, Cormier was hospitalized after his body shut down during a severe weight cut and he was unable to compete.", 13],
      ["gilroy-high-wrestling-coach", "Outside fighting and broadcasting, Cormier became a high-school wrestling coach at Gilroy High School and later built a youth wrestling academy.", 14],
    ],
  ],
  [
    "ufc:charles-oliveira",
    [
      ["childhood-arthritis-heart-murmur", "At about eight years old, Oliveira was diagnosed with rheumatoid arthritis and a heart murmur and was initially told to avoid vigorous activity.", 15],
      ["jiu-jitsu-despite-medical-restrictions", "A family friend introduced Oliveira to Brazilian jiu-jitsu around age 12; he became obsessed with it and continued training while still receiving medical treatment.", 15],
      ["do-bronx-neighborhood-identity", "Oliveira's 'Do Bronx' name is a reference to being from the favela or neighborhood where he grew up.", 15],
      ["community-raffle-funded-us-trip", "When Oliveira needed money for his first trip to the United States for an MMA opportunity, people in his community organized a raffle at a local market to help fund it.", 15],
      ["family-fight-week-fasting-ritual", "During fight weeks, Oliveira's parents have fasted with him in solidarity with his weight cut, while his grandmother sends a voice message that he repeatedly listens to.", 15],
    ],
  ],
  [
    "ufc:frankie-edgar",
    [
      ["union-plumber-double-life", "Edgar worked full shifts as a union plumber while already competing in the UFC, then coached wrestling before training at night.", 16],
      ["clarion-division-one-wrestler", "At Clarion University, Edgar qualified for the NCAA Division I wrestling championships in each of his four years.", 17],
      ["political-science-degree", "Edgar earned a bachelor's degree in Political Science from Clarion University.", 17],
      ["sixty-dollar-first-fight", "Edgar has recalled earning only $60 for his first MMA fight, breaking his orbital bone in the bout, with his future wife Renee in attendance.", 18],
      ["wrestling-school-and-gym-owner", "Edgar later became an entrepreneur in his hometown area, owning a wrestling school and opening a UFC GYM location.", 19],
    ],
  ],
  [
    "ufc:benson-henderson",
    [
      ["korean-mother-taekwondo-tradition", "Henderson's Korean mother insisted that he and his brother learn taekwondo when they were young as a way to connect with Korean culture and tradition.", 20],
      ["dana-college-wrestling-all-american", "Henderson fell in love with wrestling after wandering into a wrestling room and later became a two-time NAIA All-American at Dana College.", 20],
      ["criminal-justice-sociology-double-major", "Henderson double-majored in criminal justice and sociology in college.", 20],
      ["declined-police-career-for-mma", "After college, Henderson passed police testing and received job offers from departments in Omaha and Denver, but chose to pursue MMA instead.", 20],
      ["toothpick-fight-habit", "Henderson admitted that for many fights he secretly kept a toothpick in his mouth while competing and even once accidentally swallowed one.", 21],
    ],
  ],
  [
    "ufc:bj-penn",
    [
      ["baby-jay-name-origin", "Penn was born Jay Dee Penn; with his father and older brothers also sharing the Jay Dee name, the youngest became known as 'Baby Jay,' which was shortened to B.J.", 22],
      ["neighbor-tom-callos-bjj-introduction", "Penn was introduced to Brazilian jiu-jitsu as a teenager through Tom Callos, a neighbor and tenant connected to the Penn family.", 23],
      ["prodigy-rapid-black-belt-rise", "Penn earned a Brazilian jiu-jitsu black belt in less than three years and became the first American to win a black-belt world championship, helping establish 'The Prodigy' identity.", 24],
      ["penn-brothers-training-family", "B.J. and his brothers trained together for years and helped build a family-centered martial-arts culture in Hilo.", 25],
      ["father-career-supporter", "Penn's father, Jay Dee Penn Sr., was a master carpenter and businessman who strongly supported his sons' martial-arts pursuits and helped B.J. navigate his early career.", 23],
    ],
  ],
  [
    "ufc:glover-teixeira",
    [
      ["brazilian-farm-upbringing", "Teixeira grew up in the rural Brazilian town of Sobrália on a farm before emigrating to the United States as a teenager.", 26],
      ["connecticut-landscaping-job", "After moving to Connecticut around age 19, Teixeira worked in landscaping and sent money home to help his family.", 26],
      ["royce-tape-changed-boxing-plan", "Teixeira initially wanted to box, but watching a tape of Royce Gracie at UFC 1 redirected him toward mixed martial arts and jiu-jitsu.", 27],
      ["hackleman-liddell-mentorship", "John Hackleman invited Teixeira to train in California, where Chuck Liddell became an important training partner and influence on his striking and wrestling development.", 27],
      ["visa-exile-delayed-us-return", "Immigration and visa problems forced Teixeira to leave the United States for Brazil for years, delaying the American chapter of his career until the issue was resolved.", 27],
    ],
  ],
  [
    "ufc:leon-edwards",
    [
      ["kingston-to-birmingham-childhood", "Edwards was born in Kingston, Jamaica, where his family lived in a modest wooden home with a zinc roof, before moving to Birmingham, England.", 28],
      ["father-killed-in-london", "Edwards' father was shot and killed in London when Edwards was a teenager, a turning point he has openly linked to a turbulent period in his life.", 28],
      ["street-gang-path-before-mma", "As a teenager in Birmingham, Edwards became involved in street violence and gang activity before martial arts gave him a different path.", 28],
      ["mother-pushed-him-into-mma-gym", "Edwards credits his mother with pushing him into an MMA gym as a teenager after she saw a local gym opening and wanted him away from the streets.", 29],
      ["brother-fabian-pro-fighter", "Leon Edwards' younger brother Fabian also became a professional mixed martial artist, making fighting a family profession.", 29],
    ],
  ],
  [
    "ufc:fabricio-werdum",
    [
      ["girlfriends-ex-started-bjj-path", "Werdum has said a beach confrontation in which his girlfriend's ex-boyfriend, a jiu-jitsu practitioner, easily controlled him pushed him to begin Brazilian jiu-jitsu training.", 30],
      ["spain-long-term-home", "Werdum moved to Spain after establishing himself in jiu-jitsu and lived there for years, becoming fluent enough in Spanish to be closely identified with Spanish-speaking MMA audiences.", 31],
      ["ufc-spanish-analyst", "While still an active fighter, Werdum joined UFC's Spanish-language pay-per-view broadcasts as an analyst.", 32],
      ["cro-cop-croatia-japan-bridge", "Werdum went from Spain to Croatia to train Mirko Cro Cop, and that relationship helped open the door to Werdum's fighting career in Japan.", 31],
      ["vai-cavalo-nickname", "Werdum is known by the Portuguese nickname 'Vai Cavalo,' a horse-related phrase often rendered approximately as 'go horse.'", 31],
    ],
  ],
  [
    "ufc:tony-ferguson",
    [
      ["three-sport-varsity-athlete", "Ferguson lettered repeatedly in football, baseball and wrestling in high school, with organized sports becoming a major part of his Michigan upbringing.", 33],
      ["el-cucuy-nickname-meaning", "Ferguson's 'El Cucuy' nickname refers to the Spanish boogeyman.", 33],
      ["bartender-before-fighting", "Ferguson has said the longest-running job he held before fighting full time was bartending, a job he enjoyed because of the constant interaction with people.", 34],
      ["hunting-taught-patience", "Ferguson has credited lessons from hunting with his father for teaching him patience and the value of staying quiet and focused.", 35],
      ["unconventional-self-designed-training", "Ferguson became known for self-designed, unconventional training methods, including tire work and a routine he called 'Cucuy's Cold Cool Down,' which he said always had a purpose even when it looked unusual.", 36],
    ],
  ],
  [
    "ufc:frank-shamrock",
    [
      ["foster-and-group-home-childhood", "Born Frank Juarez, Shamrock left home young and spent years moving through foster homes and group homes before reaching Bob Shamrock's Boys Ranch.", 37],
      ["bob-shamrock-adoption", "Bob Shamrock took Frank in at his ranch for troubled youth and eventually adopted him; Frank took the Shamrock surname in honor of the man who became his father figure.", 38],
      ["helped-form-american-kickboxing-academy", "After leaving the Lion's Den orbit, Shamrock moved to San Jose and helped form American Kickboxing Academy.", 38],
      ["early-balanced-cross-training", "Working with Javier Mendez, Maurice Smith and Tsuyoshi Kohsaka, Shamrock deliberately diversified his striking, wrestling and submission skills and became an early model of the well-rounded modern MMA fighter.", 38],
      ["fighter-to-fight-executive-identity", "After his first retirement in 1999, Shamrock said he stopped thinking of himself only as a fighter and became a 'fight executive,' taking deliberate control of his personal brand and business value.", 38],
    ],
  ],
  [
    "ufc:deiveson-figueiredo",
    [
      ["marajo-island-farm-upbringing", "Figueiredo grew up around a small farm on Marajó Island in Pará, an upbringing closely tied to fishing, animals and rural life.", 39],
      ["marajoara-grappling-origin", "Before formal MMA success, Figueiredo practiced luta marajoara, the traditional grappling style associated with Marajó Island.", 39],
      ["security-guard-job", "Figueiredo worked as a security guard before his fighting career was financially established.", 39],
      ["sushi-chef-and-delivery-business", "Figueiredo worked as a sushi chef and later used money from his early UFC career to help start a sushi-delivery business with his brother.", 39],
      ["hair-salon-work", "Figueiredo also worked in a hair salon, learning styling and makeup work while building his fighting career.", 39],
    ],
  ],
  [
    "ufc:vitor-belfort",
    [
      ["street-sparring-tissue-mouthguards", "Belfort has recalled sparring grown men in Rio as a boy using improvised bathroom-tissue mouthguards before he had proper equipment.", 40],
      ["carlson-gracie-protege", "Belfort began boxing and Brazilian jiu-jitsu young and became a black belt under Carlson Gracie by age 18.", 41],
      ["teenage-move-to-los-angeles", "Belfort moved from Brazil to Los Angeles as a teenager to pursue his fighting development in the United States.", 42],
      ["sister-priscila-disappearance", "The 2004 disappearance of Belfort's sister Priscila became a defining family tragedy that Belfort has discussed publicly throughout his career.", 43],
      ["published-autobiography", "Outside competition, Belfort published an autobiography in 2012.", 41],
    ],
  ],
  [
    "ufc:tom-aspinall",
    [
      ["martial-arts-father-andy", "Aspinall grew up in martial arts under his father and coach Andy Aspinall, a British jiu-jitsu pioneer with experience across boxing, kickboxing, judo and wrestling.", 29],
      ["jiu-jitsu-first-background", "Despite becoming known for fast heavyweight boxing, Aspinall says his original combat base was Brazilian jiu-jitsu, and he later earned a black belt under his father.", 44],
      ["blue-collar-wigan-area-upbringing", "Aspinall describes growing up in a very blue-collar area around factory workers and plumbers near Manchester/Wigan rather than in a professional-sports environment.", 29],
      ["tyson-fury-training-influence", "Aspinall trained with heavyweight boxing champion Tyson Fury earlier in his career and has named Fury, alongside his father, as an important influence on how he approaches fighting.", 45],
      ["speed-over-heavyweight-stereotype", "Aspinall has deliberately built his identity around moving and training more like a lighter fighter instead of accepting the slow, power-only stereotype of heavyweight MMA.", 46],
    ],
  ],
  [
    "ufc:royce-gracie",
    [
      ["adult-sparring-by-fourteen", "By age 14, Gracie was already accustomed to sparring with fully grown men in the Gracie family's jiu-jitsu environment.", 47],
      ["moved-to-rorion-california-garage", "At 17, Gracie left Brazil to join his brother Rorion in Southern California, where the early American Gracie jiu-jitsu operation was run out of a small Hermosa Beach garage.", 47],
      ["chosen-as-unimposing-gracie-representative", "Royce was selected to represent the Gracie family at UFC 1 in part because his relatively ordinary, non-intimidating build would make a stronger demonstration of technique beating size.", 48],
      ["helio-never-forced-jiu-jitsu", "Gracie said his father Hélio never forced him to use jiu-jitsu competitively, instead telling his sons to learn it and choose for themselves whether to use it.", 49],
      ["ritz-crackers-ufc1-celebration", "After the first UFC tournament, Gracie's celebration was notably understated: Ritz crackers and apple juice before going to bed.", 47],
    ],
  ],
  [
    "ufc:anthony-pettis",
    [
      ["mother-started-taekwondo-at-five", "Pettis first entered martial arts at age five because his single mother, then attending college, enrolled him and his brother in a campus taekwondo class; Pettis says he initially hated it.", 50],
      ["father-killed-when-sixteen", "Pettis' father was killed in a home-invasion robbery when Pettis was 16, leading him to step away from martial arts before eventually recommitting.", 51],
      ["showtime-nickname-from-roufus", "Duke Roufus gave Pettis the 'Showtime' nickname after an amateur bout they shared on the same card, where Pettis fought through a dislocated shoulder and won with a high kick.", 52],
      ["playground-daredevil-creativity", "Pettis traces his creative fighting instinct to being the child who always tried to one-up other kids, including jumping from higher monkey bars on the playground.", 53],
      ["brother-sergio-fighter-family", "Pettis' younger brother Sergio also became a high-level professional MMA fighter, and the brothers spent years training and competing in the same sport.", 51],
    ],
  ],
  [
    "ufc:shogun-rua",
    [
      ["brother-ninja-inspired-start", "Rua began training at 16 after following his older brother Murilo 'Ninja' Rua to Chute Boxe; he has called Ninja the person who motivated him to become a fighter.", 54],
      ["worked-as-model", "Before fighting fully took over his life, Rua worked as a model in Brazil, including photo shoots and fashion shows for brands.", 54],
      ["chute-boxe-hard-sparring-culture", "Rua developed in Chute Boxe's famously aggressive gym culture, describing daily sparring with elite teammates as brutally hard and central to his development.", 55],
      ["japan-second-home", "Rua has referred to Japan as a second home because so much of his early international career, team history and fan connection were built there.", 56],
      ["curitiba-mma-upbringing", "Rua came up in Curitiba when the city was a major center of Brazilian MMA, with his brother Ninja and teammate Wanderlei Silva serving as examples he wanted to follow.", 57],
    ],
  ],
  [
    "ufc:dan-henderson",
    [
      ["father-high-school-wrestling-coach", "Henderson grew up with wrestling close to home because his father was a high-school wrestling coach.", 58],
      ["two-time-greco-roman-olympian", "Henderson represented the United States in Greco-Roman wrestling at the 1992 and 1996 Olympic Games.", 58],
      ["mma-funded-third-olympic-bid", "Henderson originally treated MMA as a way to make money while continuing to chase a third Olympic wrestling team rather than as his primary career goal.", 59],
      ["randy-couture-mma-bridge", "Longtime friend and fellow wrestler Randy Couture helped draw Henderson into early mixed martial arts competition.", 59],
      ["team-quest-founder", "Henderson became one of the foundational figures behind Team Quest, the wrestling-heavy camp that became a major part of early American MMA.", 59],
    ],
  ],
  [
    "ufc:amanda-nunes",
    [
      ["wild-child-rural-upbringing", "Nunes has described herself as an energetic, fearless child in rural Bahia, including a childhood story in which she traded for a mare and rode it despite her family's concerns.", 60],
      ["mother-put-her-in-karate", "Nunes' mother put her in karate at age seven because she had so much energy and needed a constructive outlet.", 61],
      ["sister-vanessa-bjj-bridge", "As a teenager, Nunes' older sister Vanessa helped bring her into serious jiu-jitsu training in Salvador, an important step toward her professional path.", 60],
      ["uncle-jose-alvis-fighting-influence", "Nunes has named her uncle Jose Alvis as one of her personal heroes and an early fighting influence in the family.", 61],
      ["physical-education-studies", "Nunes studied Physical Education before leaving that path to move to the United States and train full time.", 61],
    ],
  ],
  [
    "ufc:joanna-jedrzejczyk",
    [
      ["basketball-before-muay-thai", "Before becoming a combat-sports athlete, Jedrzejczyk played basketball.", 62],
      ["sisters-boyfriend-muay-thai-invitation", "Jedrzejczyk discovered Muay Thai after her twin sister's boyfriend invited her to join them for a class.", 62],
      ["self-funded-muay-thai-travel", "During her elite Muay Thai years, Jedrzejczyk often lost money competing internationally, paying travel costs herself to represent Poland at world championships.", 63],
      ["physical-education-education", "Jedrzejczyk studied Physical Education.", 64],
      ["small-business-with-mother", "Alongside fighting, Jedrzejczyk has said she had a small business with her mother.", 64],
    ],
  ],
  [
    "ufc:jessica-andrade",
    [
      ["futsal-background", "Before MMA, Andrade played competitive futsal and won trophies in the sport.", 65],
      ["school-judo-to-bjj", "Andrade practiced judo at school and was later invited to try Brazilian jiu-jitsu near the end of high school, quickly moving toward MMA.", 65],
      ["varied-working-class-jobs", "Before fighting paid the bills, Andrade worked a series of jobs that included a fish-and-pay recreation business, a pharmacy and driving a truck on a farm.", 65],
      ["bate-estaca-piledriver-nickname", "Andrade's Portuguese nickname 'Bate Estaca' refers to a pile driver or piledriving action.", 66],
      ["parents-different-reactions-to-fighting", "When Andrade began fighting, her mother was initially afraid she would be hurt while her father was enthusiastic and supportive.", 66],
    ],
  ],
  [
    "ufc:alexa-grasso",
    [
      ["grade-school-bullying-motivation", "Grasso has spoken about being bullied in grade school, including having her hair pulled and belongings taken, and later using the memory as motivation rather than retaliation.", 67],
      ["father-uncle-martial-arts-introduction", "Grasso grew up watching her uncle Francisco teach martial arts, and her father first taught her shadowboxing before she joined her uncle's class.", 68],
      ["family-gym-reception-and-cleaning", "When her family opened a gym, Grasso helped with reception and cleaning before she became one of its star fighters.", 68],
      ["national-bjj-win-with-irene-aldana", "Grasso and teammate Irene Aldana both took first place at a national jiu-jitsu tournament, an experience Grasso said made her want to keep returning to the podium.", 68],
      ["physical-culture-sports-studies", "Grasso pursued a degree in Physical Culture and Sports while building her fighting career.", 68],
    ],
  ],
  [
    "ufc:julianna-pena",
    [
      ["directionless-after-high-school", "Peña has said she felt directionless after high school until cardio kickboxing led her into MMA and gave her a clear competitive path.", 69],
      ["cleaned-gym-for-dues", "When she could not afford gym dues, Peña cleaned the gym daily in exchange for the ability to keep training.", 70],
      ["waitress-before-fighting", "Peña worked as a waitress before fighting became her career.", 71],
      ["car-crash-and-broken-arm-grit", "Early in her career, Peña fought shortly after a car accident that had broken her nose; during the bout she then broke her arm and still continued.", 71],
      ["career-threatening-knee-rebuild", "A 2014 training injury tore multiple structures in Peña's knee and required major reconstruction, forcing a long rehabilitation before she returned to competition.", 72],
    ],
  ],
  [
    "ufc:rafael-dos-anjos",
    [
      ["jeguinho-little-donkey-childhood-nickname", "As a tough, hyperactive child in Niterói, dos Anjos was nicknamed 'Jeguinho,' or 'little donkey,' and became known for accepting rough neighborhood grappling and slap-fight challenges.", 73],
      ["left-home-at-sixteen-for-training", "At 16, dos Anjos left Niterói for Belo Horizonte to live with his father and train under Aldo 'Caveirinha' Januário.", 74],
      ["jiu-jitsu-teacher-job", "Before MMA became his main profession, dos Anjos worked as a Brazilian jiu-jitsu instructor.", 75],
      ["international-training-germany-singapore", "Dos Anjos deliberately traveled outside Brazil to broaden his game, spending time training in Germany and repeatedly in Singapore to develop his striking.", 74],
      ["sold-everything-for-california-move", "Dos Anjos and his wife eventually sold their belongings and moved their family to California so he could build his career around a stronger full-time training environment.", 73],
    ],
  ],
  [
    "ufc:donald-cerrone",
    [
      ["raised-by-grandparents", "Cerrone was largely raised by his grandparents, with his grandmother Jerry becoming one of the most recognizable family figures around his fighting career.", 76],
      ["bull-riding-rodeo-background", "Before MMA, Cerrone pursued bull riding and rodeo, a background that helped make the 'Cowboy' identity more than just a nickname.", 76],
      ["extreme-adrenaline-lifestyle", "Cerrone is known for an unusually high-risk off-duty lifestyle that has included motocross, rock climbing, scuba cave diving and other adventure sports.", 77],
      ["bmf-ranch-training-compound", "Cerrone built the BMF Ranch in New Mexico into a home-and-training compound where fighters could stay, train and live together.", 77],
      ["son-middle-name-danger", "Cerrone gave his son Dacson the middle name 'Danger,' a fitting family detail for the risk-taking persona he had built.", 77],
    ],
  ],
  [
    "ufc:stephen-thompson",
    [
      ["martial-arts-family-from-age-three", "Thompson began karate around age three under his father Ray and grew up in a household where his brothers and sisters also trained.", 78],
      ["childhood-karate-rebellion", "Despite the family martial-arts culture, Thompson has said there was a period around age ten when he disliked karate before later choosing to embrace it on his own terms.", 78],
      ["wonderboy-nickname-origin", "Thompson says the 'Wonderboy' nickname crystallized after his first kickboxing bout at 15, when a commentator reacted to the teenager beating an older, accomplished opponent; a childhood 'Stevie Wonder' joke also contributed to the name.", 79],
      ["head-kids-instructor", "Alongside his own career, Thompson served as the head kids' instructor at his father's Upstate Karate gym and emphasized martial arts as character education.", 80],
      ["chris-weidman-family-connection", "Thompson and former UFC champion Chris Weidman became extended family through their siblings and have also trained together.", 81],
    ],
  ],
  [
    "ufc:derrick-lewis",
    [
      ["prison-turning-point", "Lewis served more than three years in prison after violating probation tied to an aggravated-assault case, and he has described incarceration as a major turning point in how he viewed his life.", 82],
      ["aaa-tow-truck-driver", "Before fighting paid consistently, Lewis worked as a tow-truck driver for AAA.", 83],
      ["george-foreman-boxing-mentorship", "George Foreman took an interest in Lewis as a boxer, providing opportunities and encouraging him to pursue boxing before Lewis chose MMA instead.", 83],
      ["black-beast-gym-mascot-origin", "Lewis' 'Black Beast' nickname came from his Silverback Fight Club environment, where he was jokingly treated as the gym's 'official mascot.'", 83],
      ["hurricane-harvey-rescues", "During Hurricane Harvey, Lewis used his truck to help rescue stranded people in the Houston area.", 84],
    ],
  ],
  [
    "ufc:paulo-costa",
    [
      ["homemade-cement-dumbbells", "Costa's father made homemade weights by filling tomato cans with cement, and Costa was lifting them as a child.", 85],
      ["brother-carlos-bjj-mentor", "Costa's older brother Carlos first protected him as a child and later became a major jiu-jitsu influence and member of his coaching team.", 85],
      ["fathers-death-bjj-hiatus", "When Costa's father died of throat cancer shortly after Costa turned 17, Costa stopped training Brazilian jiu-jitsu for roughly two years before returning.", 85],
      ["realtor-and-it-teacher", "Before fighting became his livelihood, Costa worked both as a real-estate agent and as an IT teacher, teaching programs such as Word, Excel and PowerPoint.", 85],
      ["borrachinha-to-eraser-nickname", "Costa's Brazilian nickname 'Borrachinha' grew out of his older brother's 'Borrachão' nickname; for English-speaking audiences his team later promoted 'The Eraser' as an alternate nickname.", 86],
    ],
  ],
  [
    "ufc:tai-tuivasa",
    [
      ["sydney-roosters-rugby-league", "Tuivasa was recruited into the Sydney Roosters rugby-league system as a teenager before MMA became his professional path.", 87],
      ["street-fighting-channeled-into-mma", "Friends who knew Tuivasa for street fighting encouraged him to bring that energy into a real MMA gym, helping turn informal fighting into a sport.", 87],
      ["indigenous-elderly-social-work", "Before his UFC rise, Tuivasa worked in social care with elderly Indigenous Australians.", 87],
      ["shoey-celebration-ritual", "Tuivasa became synonymous with the 'shoey' celebration, drinking from a shoe after fights as an extension of the party culture he shared with friends back home.", 88],
      ["fta-western-sydney-identity", "Tuivasa uses 'FTA' to mean 'From The Area,' a phrase tied to his Western Sydney roots, community pride and role-model identity.", 88],
    ],
  ],
  [
    "ufc:diego-lopes",
    [
      ["bjj-family-from-age-five", "Lopes began Brazilian jiu-jitsu around age five through his father and older brother and later helped teach at his father's academy.", 89],
      ["sao-paulo-gym-sleeping-hardship", "While trying to advance his career in São Paulo, Lopes lived through severe financial hardship that included sleeping in gyms and relying on extremely cheap subsidized meals.", 90],
      ["moved-to-mexico-to-teach-bjj", "Lopes moved from Brazil to Mexico in 2015 for a jiu-jitsu teaching opportunity and gradually built his adult life and fighting career there.", 90],
      ["alexa-grasso-coach", "Before many UFC fans knew Lopes as a fighter, he was already visible as one of Alexa Grasso's coaches and cornered her during a major stage of her UFC career.", 91],
      ["donald-cerrone-idol-and-training", "Lopes has named Donald Cerrone as a favorite fighter and later had the chance to train with him before Lopes reached the UFC.", 89],
    ],
  ],
] as const;
