// PR10 UFC person-identity research data batch 10. Canonical validation and lookup remain in ufcPersonIdentityKnowledge.ts.
export const ufcPersonIdentityResearchSources10 = [
  ["https://www.ufc.com/athlete/jessica-andrade", "UFC", "Jessica Andrade | UFC"],
  ["https://www.ufc.com/news/jessica-andrade-full-speed-ahead", "UFC", "Jessica Andrade: Full Speed Ahead"],
  ["https://www.espn.com/mma/ufc/story/_/id/27647180/mexico-strawweight-alexa-grasso-ready-live-ufc-expectations", "ESPN", "Alexa Grasso ready to live up to expectations"],
  ["https://www.ufc.com/athlete/alexa-grasso", "UFC", "Alexa Grasso | UFC"],
  ["https://www.ufc.com/news/pena-once-directionless-found-her-way-through-fighting", "UFC", "Pena, once directionless, found her way through fighting"],
  ["https://www.espn.com/blog/onenacion/post/_/id/5584/julianna-pena-mmas-venezuelan-vixen-wants-to-fight-the-good-fight", "ESPN", "Julianna Pena: MMA's Venezuelan Vixen wants to fight the good fight"],
  ["https://www.ufc.com/athlete/julianna-pena", "UFC", "Julianna Peña | UFC"],
  ["https://www.mmafighting.com/2014/1/31/5365176/michael-chiesa-on-julianna-pena-injury-situation-this-whole-thing-is", "MMA Fighting", "Michael Chiesa on Julianna Pena injury situation: 'This whole thing is pretty devastating'"],
  ["https://www.mmafighting.com/2016/7/4/12066124/from-little-donkey-to-ufc-champion-how-rafael-dos-anjos-beat-the-odds", "MMA Fighting", "From 'little donkey' to UFC champion: How Rafael dos Anjos beat the odds"],
  ["https://www.ufc.com.br/news/espantosa-evolucao-de-rafael-dos-anjos", "UFC", "A espantosa evolução de Rafael dos Anjos"],
  ["https://www.ufc.com.br/athlete/rafael-dos-anjos", "UFC", "Rafael dos Anjos | UFC"],
  ["https://www.espn.com/mma/story/_/id/28029101/what-need-know-donald-cowboy-cerrone", "ESPN", "What you need to know about Donald 'Cowboy' Cerrone"],
  ["https://www.espn.com/espn/feature/story/_/id/26642572/cowboy-cerrone-wild-ride-bmf-ranch-filled-danger-danger", "ESPN", "Cowboy's wild ride"],
  ["https://www.ufc.com/news/stephen-thompson-karates-back-20", "UFC", "Stephen Thompson - Karate's Back 2.0"],
  ["https://www.ufc.com/athlete/stephen-thompson", "UFC", "Stephen Thompson | UFC"],
  ["https://www.ufc.com/news/stephen-thompson-mma-evangelist", "UFC", "Stephen Thompson - The MMA Evangelist"],
  ["https://www.espn.com/mma/story/_/id/18015888/stephen-thompson-champion-karate-hopes-become-ufc-welterweight-champion-ufc-209", "ESPN", "Stephen Thompson: Champion in karate, hopes to become UFC welterweight champion"],
  ["https://www.ufc.com/news/derrick-lewis-reflects-his-journey-top-ufc-247-heavyweight", "UFC", "Derrick Lewis Reflects On His Journey To The Top"],
  ["https://www.mmafighting.com/2014/6/22/5829788/no-small-wonder-derrick-lewis-journey-from-sugar-land-to-the-promised", "MMA Fighting", "No small wonder: Derrick Lewis' journey from Sugar Land to the Promised Land"],
  ["https://www.ufc.com/news/derrick-lewis-goes-hands-help-houston-flood-victims", "UFC", "Derrick Lewis Goes Hands-On To Help Houston Flood Victims"],
  ["https://www.mmafighting.com/2019/8/17/20809028/troublemaker-paulo-costa-endless-quest-greatness-ufc", "MMA Fighting", "'Troublemaker': Paulo Costa's endless quest for greatness"],
  ["https://www.espn.com/mma/story/_/id/29931659/the-ufc-best-nicknames-stories-them", "ESPN", "The UFC's best nicknames and the stories behind them"],
  ["https://www.ufc.com/news/fighting-has-always-been-part-tai-tuivasa", "UFC", "Fighting has always been a part of Tai Tuivasa"],
  ["https://www.espn.com/mma/story/_/id/33202812/ufc-271-tai-tuivasa-talks-shoeys-fta-life-unlikely-role-model", "ESPN", "'From The Area': Tai Tuivasa's shoey has become more than just a celebration"],
  ["https://www.ufc.com/athlete/diego-lopes", "UFC", "Diego Lopes | UFC"],
  ["https://www.mmafighting.com/2025/4/9/24398105/8-cent-meals-bucket-shower-mexican-dream-improbable-rise-diego-lopes", "MMA Fighting", "8-cent meals, bucket shower and Mexican dream: The improbable rise of Diego Lopes"],
  ["https://www.ufc.com/news/diego-lopes-enjoys-responsibility-opening-ufc-freedom-250", "UFC", "Diego Lopes Enjoys Responsibility of Opening UFC Freedom 250"],
] as const;

export const ufcPersonIdentityResearch10 = [
  ["ufc:jessica-andrade", [
    ["futsal-background", "Before MMA, Andrade played competitive futsal and won trophies in the sport.", 0],
    ["school-judo-to-bjj", "Andrade practiced judo at school and was later invited to try Brazilian jiu-jitsu near the end of high school, quickly moving toward MMA.", 0],
    ["varied-working-class-jobs", "Before fighting paid the bills, Andrade worked a series of jobs that included a fish-and-pay recreation business, a pharmacy and driving a truck on a farm.", 0],
    ["bate-estaca-piledriver-nickname", "Andrade's Portuguese nickname 'Bate Estaca' refers to a pile driver or piledriving action.", 1],
    ["parents-different-reactions-to-fighting", "When Andrade began fighting, her mother was initially afraid she would be hurt while her father was enthusiastic and supportive.", 1],
  ]],
  ["ufc:alexa-grasso", [
    ["grade-school-bullying-motivation", "Grasso has spoken about being bullied in grade school, including having her hair pulled and belongings taken, and later using the memory as motivation rather than retaliation.", 2],
    ["father-uncle-martial-arts-introduction", "Grasso grew up watching her uncle Francisco teach martial arts, and her father first taught her shadowboxing before she joined her uncle's class.", 3],
    ["family-gym-reception-and-cleaning", "When her family opened a gym, Grasso helped with reception and cleaning before she became one of its star fighters.", 3],
    ["national-bjj-win-with-irene-aldana", "Grasso and teammate Irene Aldana both took first place at a national jiu-jitsu tournament, an experience Grasso said made her want to keep returning to the podium.", 3],
    ["physical-culture-sports-studies", "Grasso pursued a degree in Physical Culture and Sports while building her fighting career.", 3],
  ]],
  ["ufc:julianna-pena", [
    ["directionless-after-high-school", "Peña has said she felt directionless after high school until cardio kickboxing led her into MMA and gave her a clear competitive path.", 4],
    ["cleaned-gym-for-dues", "When she could not afford gym dues, Peña cleaned the gym daily in exchange for the ability to keep training.", 5],
    ["waitress-before-fighting", "Peña worked as a waitress before fighting became her career.", 6],
    ["car-crash-and-broken-arm-grit", "Early in her career, Peña fought shortly after a car accident that had broken her nose; during the bout she then broke her arm and still continued.", 6],
    ["career-threatening-knee-rebuild", "A 2014 training injury tore multiple structures in Peña's knee and required major reconstruction, forcing a long rehabilitation before she returned to competition.", 7],
  ]],
  ["ufc:rafael-dos-anjos", [
    ["jeguinho-little-donkey-childhood-nickname", "As a tough, hyperactive child in Niterói, dos Anjos was nicknamed 'Jeguinho,' or 'little donkey,' and became known for accepting rough neighborhood grappling and slap-fight challenges.", 8],
    ["left-home-at-sixteen-for-training", "At 16, dos Anjos left Niterói for Belo Horizonte to live with his father and train under Aldo 'Caveirinha' Januário.", 9],
    ["jiu-jitsu-teacher-job", "Before MMA became his main profession, dos Anjos worked as a Brazilian jiu-jitsu instructor.", 10],
    ["international-training-germany-singapore", "Dos Anjos deliberately traveled outside Brazil to broaden his game, spending time training in Germany and repeatedly in Singapore to develop his striking.", 9],
    ["sold-everything-for-california-move", "Dos Anjos and his wife eventually sold their belongings and moved their family to California so he could build his career around a stronger full-time training environment.", 8],
  ]],
  ["ufc:donald-cerrone", [
    ["raised-by-grandparents", "Cerrone was largely raised by his grandparents, with his grandmother Jerry becoming one of the most recognizable family figures around his fighting career.", 11],
    ["bull-riding-rodeo-background", "Before MMA, Cerrone pursued bull riding and rodeo, a background that helped make the 'Cowboy' identity more than just a nickname.", 11],
    ["extreme-adrenaline-lifestyle", "Cerrone is known for an unusually high-risk off-duty lifestyle that has included motocross, rock climbing, scuba cave diving and other adventure sports.", 12],
    ["bmf-ranch-training-compound", "Cerrone built the BMF Ranch in New Mexico into a home-and-training compound where fighters could stay, train and live together.", 12],
    ["son-middle-name-danger", "Cerrone gave his son Dacson the middle name 'Danger,' a fitting family detail for the risk-taking persona he had built.", 12],
  ]],
  ["ufc:stephen-thompson", [
    ["martial-arts-family-from-age-three", "Thompson began karate around age three under his father Ray and grew up in a household where his brothers and sisters also trained.", 13],
    ["childhood-karate-rebellion", "Despite the family martial-arts culture, Thompson has said there was a period around age ten when he disliked karate before later choosing to embrace it on his own terms.", 13],
    ["wonderboy-nickname-origin", "Thompson says the 'Wonderboy' nickname crystallized after his first kickboxing bout at 15, when a commentator reacted to the teenager beating an older, accomplished opponent; a childhood 'Stevie Wonder' joke also contributed to the name.", 14],
    ["head-kids-instructor", "Alongside his own career, Thompson served as the head kids' instructor at his father's Upstate Karate gym and emphasized martial arts as character education.", 15],
    ["chris-weidman-family-connection", "Thompson and former UFC champion Chris Weidman became extended family through their siblings and have also trained together.", 16],
  ]],
  ["ufc:derrick-lewis", [
    ["prison-turning-point", "Lewis served more than three years in prison after violating probation tied to an aggravated-assault case, and he has described incarceration as a major turning point in how he viewed his life.", 17],
    ["aaa-tow-truck-driver", "Before fighting paid consistently, Lewis worked as a tow-truck driver for AAA.", 18],
    ["george-foreman-boxing-mentorship", "George Foreman took an interest in Lewis as a boxer, providing opportunities and encouraging him to pursue boxing before Lewis chose MMA instead.", 18],
    ["black-beast-gym-mascot-origin", "Lewis' 'Black Beast' nickname came from his Silverback Fight Club environment, where he was jokingly treated as the gym's 'official mascot.'", 18],
    ["hurricane-harvey-rescues", "During Hurricane Harvey, Lewis used his truck to help rescue stranded people in the Houston area.", 19],
  ]],
  ["ufc:paulo-costa", [
    ["homemade-cement-dumbbells", "Costa's father made homemade weights by filling tomato cans with cement, and Costa was lifting them as a child.", 20],
    ["brother-carlos-bjj-mentor", "Costa's older brother Carlos first protected him as a child and later became a major jiu-jitsu influence and member of his coaching team.", 20],
    ["fathers-death-bjj-hiatus", "When Costa's father died of throat cancer shortly after Costa turned 17, Costa stopped training Brazilian jiu-jitsu for roughly two years before returning.", 20],
    ["realtor-and-it-teacher", "Before fighting became his livelihood, Costa worked both as a real-estate agent and as an IT teacher, teaching programs such as Word, Excel and PowerPoint.", 20],
    ["borrachinha-to-eraser-nickname", "Costa's Brazilian nickname 'Borrachinha' grew out of his older brother's 'Borrachão' nickname; for English-speaking audiences his team later promoted 'The Eraser' as an alternate nickname.", 21],
  ]],
  ["ufc:tai-tuivasa", [
    ["sydney-roosters-rugby-league", "Tuivasa was recruited into the Sydney Roosters rugby-league system as a teenager before MMA became his professional path.", 22],
    ["street-fighting-channeled-into-mma", "Friends who knew Tuivasa for street fighting encouraged him to bring that energy into a real MMA gym, helping turn informal fighting into a sport.", 22],
    ["indigenous-elderly-social-work", "Before his UFC rise, Tuivasa worked in social care with elderly Indigenous Australians.", 22],
    ["shoey-celebration-ritual", "Tuivasa became synonymous with the 'shoey' celebration, drinking from a shoe after fights as an extension of the party culture he shared with friends back home.", 23],
    ["fta-western-sydney-identity", "Tuivasa uses 'FTA' to mean 'From The Area,' a phrase tied to his Western Sydney roots, community pride and role-model identity.", 23],
  ]],
  ["ufc:diego-lopes", [
    ["bjj-family-from-age-five", "Lopes began Brazilian jiu-jitsu around age five through his father and older brother and later helped teach at his father's academy.", 24],
    ["sao-paulo-gym-sleeping-hardship", "While trying to advance his career in São Paulo, Lopes lived through severe financial hardship that included sleeping in gyms and relying on extremely cheap subsidized meals.", 25],
    ["moved-to-mexico-to-teach-bjj", "Lopes moved from Brazil to Mexico in 2015 for a jiu-jitsu teaching opportunity and gradually built his adult life and fighting career there.", 25],
    ["alexa-grasso-coach", "Before many UFC fans knew Lopes as a fighter, he was already visible as one of Alexa Grasso's coaches and cornered her during a major stage of her UFC career.", 26],
    ["donald-cerrone-idol-and-training", "Lopes has named Donald Cerrone as a favorite fighter and later had the chance to train with him before Lopes reached the UFC.", 24],
  ]],
] as const;
