// PR10 UFC person-identity research data batch 6. Canonical validation and lookup remain in ufcPersonIdentityKnowledge.ts.
export const ufcPersonIdentityResearchSources6 = [
  ["https://www.ufc.com/news/ufc-legend-rashad-evans-retires?language_content_entity=en", "UFC", "UFC Legend Rashad Evans Retires"],
  ["https://www.ufc.com/news/rashad-evans-risked-it-all-tuf", "UFC", "Rashad Evans Risked It All On TUF"],
  ["https://www.ufc.com/athlete/dominick-cruz", "UFC", "Dominick Cruz | UFC Athlete Profile"],
  ["https://www.ufc.com/news/dominick-cruz-named-ufc-hall-fame-class-2026", "UFC", "Dominick Cruz Named To UFC Hall Of Fame Class Of 2026"],
  ["https://www.ufc.com/news/dominick-cruz-comeback-begins-again", "UFC", "Dominick Cruz: The Comeback Begins Again"],
  ["https://www.ufc.com/news/few-have-done-it-better-bisping", "UFC", "Few Have Done It Better Than Bisping"],
  ["https://www.ufc.com/news/michael-bisping-giving-fans-what-they-came-see", "UFC", "Michael Bisping Giving Fans What They Came To See"],
  ["https://www.ufc.com/news/grounded-kennedy-outpoints-bisping", "UFC", "Grounded: Kennedy Outpoints Bisping"],
  ["https://www.ufc.com/news/bisping-headlines-2019-ufc-hall-fame-class", "UFC", "Bisping Headlines 2019 UFC Hall Of Fame Class"],
  ["https://jp.ufc.com/news/quintons-quotables", "UFC", "Quinton's Quotables"],
  ["https://www.ufc.com/news/rampage-jackson-theres-no-place-his-second-home", "UFC", "Rampage Jackson: There's No Place Like His Second Home"],
  ["https://www.ufc.com/news/rampage-rashad-carwin-and-more-new-ufc-mag", "UFC", "Rampage, Rashad, Carwin and More in New UFC Magazine"],
  ["https://www.ufc.com/news/brock-lesnar-be-featured-espns-e60", "UFC", "Brock Lesnar To Be Featured On ESPN's E:60"],
  ["https://kr.ufc.com/news/brock-lesnar-modern-day-gladiator", "UFC", "Brock Lesnar - Modern Day Gladiator"],
  ["https://www.ufc.com/athlete/paddy-pimblett", "UFC", "Paddy Pimblett | UFC Athlete Profile"],
  ["https://www.bbc.co.uk/sport/mixed-martial-arts/62396350", "BBC Sport", "Paddy Pimblett: UFC star's emotional mental health message after friend's death"],
  ["https://www.ufc.com/athlete/zhang-weili", "UFC", "Zhang Weili | UFC Athlete Profile"],
  ["https://www.xinhuanet.com/english/2020-03/12/c_138870504.htm", "Xinhua", "Feature: Zhang Weili fights her way to the top"],
  ["https://www.ufc.com/news/zhang-weili-found-her-voice-in-mixed-martial-arts-ufc-248", "UFC", "Zhang Weili Found Her Voice In Mixed Martial Arts"],
  ["https://www.espn.com/espnw/athletes-life/the-buzz/article/13533062/ronda-rousey-reveals-special-connection-young-fan", "ESPN", "Ronda Rousey reveals special connection to young fan"],
  ["https://www.ufc.com/news/ronda-rousey-judo-pressure-and-tate", "UFC", "Ronda Rousey: Judo, Pressure and Tate"],
  ["https://www.ufc.com/news/ronda-rousey-makes-history-first-woman-selected-induction-ufc-hall-fame", "UFC", "Ronda Rousey Makes History As First Woman Selected For Induction Into UFC Hall Of Fame"],
  ["https://www.espn.com/wwe/story/_/id/22244988/ronda-rousey-signs-wwe", "ESPN", "Ronda Rousey signs with WWE"],
  ["https://www.ufc.com/athlete/carla-esparza", "UFC", "Carla Esparza | UFC Athlete Profile"],
  ["https://www.ufc.com/news/ufc-magazine-carla-esparza-profile", "UFC", "UFC Magazine: Carla Esparza Profile"],
  ["https://www.ufc.com/athlete/mackenzie-dern", "UFC", "Mackenzie Dern | UFC Athlete Profile"],
  ["https://www.ufc.com/news/mackenzie-dern-full-circle-abu-dhabi-ufc-321", "UFC", "Mackenzie Dern | Full Circle"],
  ["https://www.ufc.com/news/mackenzie-dern-focused-motherhood-and-learning-ufc-women", "UFC", "Mackenzie Dern Focused On Motherhood And Learning"],
] as const;

export const ufcPersonIdentityResearch6 = [
  ["ufc:rashad-evans", [
    ["police-career-original-goal", "Before MMA became his profession, Evans's original career plan was to become a police officer.", 0],
    ["michigan-state-division-one-wrestler", "Evans wrestled at the NCAA Division I level for Michigan State, giving him the amateur-wrestling base that later shaped his MMA style.", 0],
    ["michigan-state-psychology-degree", "He graduated from Michigan State with a degree in psychology.", 0],
    ["mma-after-graduation-career-pivot", "Evans did not initially treat fighting as his life plan; he moved seriously toward MMA after finishing college and setting aside the law-enforcement path he had expected to follow.", 0],
    ["undersized-heavyweight-tuf2-gamble", "Although naturally closer to light heavyweight, Evans entered The Ultimate Fighter 2 as a heavyweight because it was his chance to reach the UFC, competing against substantially larger castmates.", 1],
  ]],
  ["ufc:dominick-cruz", [
    ["dominator-high-school-football-joke", "Cruz has explained that 'The Dominator' began as a tongue-in-cheek high-school football nickname while he was an undersized linebacker rather than as a self-created MMA persona.", 2],
    ["customer-service-job-before-fighting", "Before fighting became his career, Cruz worked as a customer-service representative.", 2],
    ["seventh-grade-wrestling-start", "His combat-sports foundation began with wrestling in seventh grade at Flowing Wells in Tucson.", 3],
    ["multi-surgery-injury-comeback", "Cruz's career was dramatically shaped by a long injury cycle that included two surgeries on his left ACL, a groin tear and later a torn right ACL.", 4],
    ["combat-sports-analyst-career", "Alongside and after fighting, Cruz developed a major second career as a combat-sports analyst and broadcaster, earning industry recognition for his analysis.", 3],
  ]],
  ["ufc:michael-bisping", [
    ["manual-odd-jobs-before-ufc", "Before MMA paid his bills, Bisping worked physically demanding jobs including slaughterhouse work, construction or laboring, and upholstery.", 5],
    ["count-nickname-ancestry", "His 'The Count' nickname originated as a reference to his family ancestry rather than to his fight record or a self-declared royal persona.", 6],
    ["detached-retina-two-surgeries", "A detached retina became one of the defining obstacles of Bisping's career, eventually requiring two surgeries and a long layoff while leaving lasting damage to his vision.", 7],
    ["jiujitsu-childhood-no-holds-barred", "Bisping began jiu-jitsu as a child and, as a teenager, competed in an early British 'no holds barred' event that predated his modern MMA career.", 8],
    ["analyst-commentator-acting-second-career", "He built a substantial post-fighting media career as a UFC commentator and analyst while also taking acting roles in films such as Den of Thieves and xXx: Return of Xander Cage.", 8],
  ]],
  ["ufc:quinton-jackson", [
    ["poor-memphis-upbringing", "Jackson has described growing up poor in Memphis, being picked on over his clothes, and becoming strongly motivated to create a better life for his mother and siblings.", 9],
    ["wrestling-redirected-street-path", "School wrestling became an important redirection for Jackson after a rough adolescence centered on street fighting, giving his aggression a structured competitive outlet.", 9],
    ["rv-homeless-early-pride", "Early in his professional career after moving from Memphis to California, Jackson went through a period of extreme financial instability and lived in an RV while trying to establish himself as a fighter.", 9],
    ["japan-second-home-family-ties", "His years fighting in Japan made the country a second home to him and created lasting personal and family connections beyond the bouts themselves.", 10],
    ["a-team-ba-baracus-role", "Jackson crossed into mainstream acting by playing B.A. Baracus in the 2010 film The A-Team.", 11],
  ]],
  ["ufc:brock-lesnar", [
    ["webster-dairy-farm-upbringing", "Lesnar grew up on a dairy farm outside Webster, South Dakota, a rural background that long predated his combat-sports fame.", 12],
    ["ncaa-heavyweight-wrestling-champion", "Before professional wrestling or MMA, Lesnar became an NCAA heavyweight wrestling champion after progressing through junior college and the University of Minnesota.", 12],
    ["wwe-next-big-thing-stardom", "Lesnar became a major WWE star under 'The Next Big Thing' billing before he entered elite MMA.", 12],
    ["minnesota-vikings-nfl-attempt", "At the height of his pro-wrestling fame, Lesnar left WWE to chase a childhood NFL ambition and went through Minnesota Vikings training camp despite not having played college football.", 12],
    ["diverticulitis-colon-surgery", "A severe bout of diverticulitis interrupted his MMA career and ultimately led to surgery in which a section of his colon was removed.", 13],
  ]],
  ["ufc:paddy-pimblett", [
    ["full-time-training-at-sixteen", "Pimblett began MMA training at about 15 and committed to it full time by 16, later saying he never followed a conventional job path because fighting became his occupation so young.", 14],
    ["liverpool-fc-home-away-passion", "He is a devoted Liverpool FC supporter and has described following the club home and away as his main passion outside MMA.", 14],
    ["big-nog-role-model", "Pimblett has named Antônio Rodrigo Nogueira as a favorite fighter and role model, particularly admiring Nogueira's ability to survive adversity and come back in fights.", 14],
    ["father-of-twin-daughters", "Fatherhood became a major part of Pimblett's public life after he and his wife became parents to twin daughters, Betsy and Margot.", 14],
    ["ricky-mental-health-advocacy", "After the death of his friend Ricky by suicide, Pimblett used a high-profile post-fight interview to urge men to speak openly and seek help rather than silently carry mental-health struggles.", 15],
  ]],
  ["ufc:zhang-weili", [
    ["sanda-foundation", "Zhang's martial-arts foundation included sanda before she became a professional mixed martial artist.", 16],
    ["civilian-jobs-beijing", "Before fighting could support her, Zhang worked a variety of jobs in Beijing, including supermarket cashier, kindergarten teacher and hotel desk clerk.", 17],
    ["gym-staff-free-training-equipment", "In 2010 she took a staff job at a Beijing gym in part because it gave her free access to training equipment she otherwise could not afford to use regularly.", 17],
    ["injury-hiatus-persistence", "A serious injury interrupted Zhang's early martial-arts development for years, but she eventually returned to training rather than abandoning the goal of competing.", 18],
    ["ufc157-womens-main-event-inspiration", "Watching Ronda Rousey and Liz Carmouche headline UFC 157 helped convince Zhang that women could build a future at the highest level of MMA and made the UFC feel like a realistic dream.", 16],
  ]],
  ["ufc:ronda-rousey", [
    ["childhood-speech-apraxia", "Rousey had a serious speech difficulty as a young child that was later identified as apraxia, and she spent years in speech therapy before becoming a public athlete and entertainer.", 19],
    ["competitive-swimming-with-father", "Before judo, Rousey spent part of her childhood as a competitive swimmer, a sport she shared closely with her father.", 20],
    ["mother-annmaria-judo-lineage", "She began judo under the influence of her mother, AnnMaria De Mars, who had herself become the first American to win a world judo championship.", 21],
    ["historic-2008-olympic-bronze", "Rousey won bronze in judo at the 2008 Beijing Olympics, becoming the first American woman to win an Olympic judo medal after women's judo became an official Olympic sport.", 21],
    ["pro-wrestling-fandom-wwe-crossover", "She was a longtime professional-wrestling fan before eventually joining WWE herself, turning an existing personal interest into a major second combat-entertainment career.", 22],
  ]],
  ["ufc:carla-esparza", [
    ["menlo-college-wrestling", "Esparza wrestled for four years at Menlo College and became a two-time collegiate All-American under coach and two-time Olympian Lee Allen.", 23],
    ["business-sports-management-degree", "She earned a business degree with a concentration in sports management.", 23],
    ["bjj-muay-thai-between-wrestling-seasons", "During breaks from collegiate wrestling, Esparza added Brazilian jiu-jitsu and Muay Thai, and the combination helped make MMA feel like a natural next sport.", 23],
    ["personal-training-job", "Alongside her early fight career, Esparza worked as a personal trainer.", 23],
    ["early-career-financial-sacrifice", "Her earliest professional fights were financially precarious enough that medical costs could consume most or all of a purse, and she continued living with her parents while trying to make fighting sustainable.", 24],
  ]],
  ["ufc:mackenzie-dern", [
    ["father-megaton-bjj-age-three", "Dern grew up inside Brazilian jiu-jitsu: her father is Wellington 'Megaton' Dias, and she began training in his academy at about age three.", 25],
    ["elite-bjj-championship-pedigree", "Before becoming a UFC fighter, she built one of the sport's most recognizable modern women's grappling résumés, including world-level Brazilian jiu-jitsu and ADCC titles.", 25],
    ["professional-bjj-before-mma", "Her occupation before MMA was already professional competition in Brazilian jiu-jitsu rather than a conventional civilian job.", 25],
    ["us-brazil-bilingual-identity", "Born in the United States and raised between the U.S. and Brazil, Dern grew up fluent in English and Portuguese and has described both countries as central to her identity.", 26],
    ["motherhood-jiujitsu-family-continuity", "After becoming a mother, Dern quickly folded daughter Moa into the family's jiu-jitsu culture; UFC coverage noted that Moa had her first gi while still an infant.", 27],
  ]],
] as const;
