import { barTriviaQuestion, type BarTriviaDoubleRound, type BarTriviaQuestion } from "../games/barTriviaEngine";

export const MLB_BAR_TRIVIA_PRODUCTION_CHALLENGE_KEY = "mlb-2026-play-11";
export const MLB_BAR_TRIVIA_PRODUCTION_DATE = "2026-10-21";
export const MLB_BAR_TRIVIA_DOUBLE_ROUND: BarTriviaDoubleRound = "round2";

export const MLB_BAR_TRIVIA_PRODUCTION_RUN = [
  barTriviaQuestion({
    id: "mlb-prod-r1-two-way-star",
    league: "mlb",
    round: "round1",
    category: "Modern Stars",
    prompt: "Which modern superstar is famous for starring as both a pitcher and a hitter?",
    choices: ["Aaron Judge", "Shohei Ohtani", "Mookie Betts", "Mike Trout"],
    answer: "Shohei Ohtani",
    explanation: "Shohei Ohtani became a global star by performing at an elite level as both a starting pitcher and a power hitter.",
    sourceId: "mlb-evergreen",
  }),
  barTriviaQuestion({
    id: "mlb-prod-r1-fenway",
    league: "mlb",
    round: "round1",
    category: "Ballparks",
    prompt: "Which team plays its home games at Fenway Park?",
    choices: ["Boston Red Sox", "New York Mets", "Philadelphia Phillies", "Baltimore Orioles"],
    answer: "Boston Red Sox",
    explanation: "Fenway Park has been the home of the Boston Red Sox since 1912.",
    sourceId: "mlb-evergreen",
  }),
  barTriviaQuestion({
    id: "mlb-prod-r1-judge-62",
    league: "mlb",
    round: "round1",
    category: "Home Runs",
    prompt: "Who hit 62 home runs in 2022 to set the American League single-season record?",
    choices: ["Mike Trout", "Giancarlo Stanton", "Vladimir Guerrero Jr.", "Aaron Judge"],
    answer: "Aaron Judge",
    explanation: "Aaron Judge hit 62 home runs in 2022, breaking Roger Maris' long-standing American League record.",
    sourceId: "mlb-evergreen",
  }),
  barTriviaQuestion({
    id: "mlb-prod-r2-cubs-2016",
    league: "mlb",
    round: "round2",
    category: "World Series",
    prompt: "Which team won the 2016 World Series to end a 108-year championship drought?",
    choices: ["Cleveland Guardians", "Kansas City Royals", "Chicago Cubs", "Houston Astros"],
    answer: "Chicago Cubs",
    explanation: "The Chicago Cubs won the 2016 World Series, their first championship since 1908.",
    sourceId: "mlb-evergreen",
  }),
  barTriviaQuestion({
    id: "mlb-prod-r2-big-papi",
    league: "mlb",
    round: "round2",
    category: "Nicknames",
    prompt: "Which Red Sox slugger was famously known as “Big Papi”?",
    choices: ["David Ortiz", "Manny Ramirez", "Pedro Martinez", "Nomar Garciaparra"],
    answer: "David Ortiz",
    explanation: "David Ortiz became one of Boston's most recognizable stars under the nickname “Big Papi.”",
    sourceId: "mlb-evergreen",
  }),
  barTriviaQuestion({
    id: "mlb-prod-r2-big-unit",
    league: "mlb",
    round: "round2",
    category: "Nicknames",
    prompt: "Which Hall of Fame pitcher was nicknamed “The Big Unit”?",
    choices: ["Greg Maddux", "Pedro Martinez", "Curt Schilling", "Randy Johnson"],
    answer: "Randy Johnson",
    explanation: "At 6-foot-10 with an overpowering fastball, Randy Johnson became famous as “The Big Unit.”",
    sourceId: "mlb-evergreen",
  }),
  barTriviaQuestion({
    id: "mlb-prod-r3-first-40-40",
    league: "mlb",
    round: "round3",
    category: "Milestones",
    prompt: "Who became the first MLB player to hit 40 home runs and steal 40 bases in the same season?",
    choices: ["Barry Bonds", "Jose Canseco", "Alex Rodriguez", "Alfonso Soriano"],
    answer: "Jose Canseco",
    explanation: "Jose Canseco became the first member of the 40-40 club in 1988.",
    sourceId: "mlb-evergreen",
  }),
  barTriviaQuestion({
    id: "mlb-prod-r3-giants-dynasty",
    league: "mlb",
    round: "round3",
    category: "World Series",
    prompt: "Which team won World Series titles in 2010, 2012, and 2014?",
    choices: ["Boston Red Sox", "St. Louis Cardinals", "San Francisco Giants", "New York Yankees"],
    answer: "San Francisco Giants",
    explanation: "San Francisco won three championships in five seasons: 2010, 2012, and 2014.",
    sourceId: "mlb-evergreen",
  }),
  barTriviaQuestion({
    id: "mlb-prod-r3-last-400",
    league: "mlb",
    round: "round3",
    category: "Batting Records",
    prompt: "Who remains the last MLB player to hit .400 or better in a season?",
    choices: ["Tony Gwynn", "George Brett", "Rod Carew", "Ted Williams"],
    answer: "Ted Williams",
    explanation: "Ted Williams hit .406 in 1941 and remains the last Major Leaguer to finish a season at .400 or better.",
    sourceId: "mlb-evergreen",
  }),
  barTriviaQuestion({
    id: "mlb-prod-last-cy-young",
    league: "mlb",
    round: "last-call",
    category: "Awards",
    prompt: "Which pitcher won a record seven Cy Young Awards?",
    choices: ["Randy Johnson", "Roger Clemens", "Greg Maddux", "Steve Carlton"],
    answer: "Roger Clemens",
    explanation: "Roger Clemens won seven Cy Young Awards, the most in Major League history.",
    sourceId: "mlb-evergreen",
  }),
] as const satisfies readonly BarTriviaQuestion[];
