import type { MlbPlayoffsHub } from "./mlbPlayoffsRepository";
import type { MlbChampionship } from "./mlbChampionship";
import type { MlbPlayChallengeLeaderboardEntry } from "./mlbPlayChallenge";
import { mlbTeamLogoUrl } from "./mlbTeamAssets";

export const MLB_OWNER_PREVIEW_HUB: MlbPlayoffsHub = {
  season: 2026,
  publicEnabled: false,
  fieldReady: true,
  currentRound: "wild_card",
  bracketLockAt: "2026-09-29T12:00:00-05:00",
  bracketLocked: false,
  bracketTemplate: {
    teams: [
      { id: "tb", name: "Tampa Bay Rays", abbreviation: "TB", seed: 1, league: "AL", logo_url: mlbTeamLogoUrl("TB", "Tampa Bay Rays") },
      { id: "cle", name: "Cleveland Guardians", abbreviation: "CLE", seed: 2, league: "AL", logo_url: mlbTeamLogoUrl("CLE", "Cleveland Guardians") },
      { id: "hou", name: "Houston Astros", abbreviation: "HOU", seed: 3, league: "AL", logo_url: mlbTeamLogoUrl("HOU", "Houston Astros") },
      { id: "nyy", name: "New York Yankees", abbreviation: "NYY", seed: 4, league: "AL", logo_url: mlbTeamLogoUrl("NYY", "New York Yankees") },
      { id: "bos", name: "Boston Red Sox", abbreviation: "BOS", seed: 5, league: "AL", logo_url: mlbTeamLogoUrl("BOS", "Boston Red Sox") },
      { id: "cws", name: "Chicago White Sox", abbreviation: "CWS", seed: 6, league: "AL", logo_url: mlbTeamLogoUrl("CWS", "Chicago White Sox") },
      { id: "mil", name: "Milwaukee Brewers", abbreviation: "MIL", seed: 1, league: "NL", logo_url: mlbTeamLogoUrl("MIL", "Milwaukee Brewers") },
      { id: "lad", name: "Los Angeles Dodgers", abbreviation: "LAD", seed: 2, league: "NL", logo_url: mlbTeamLogoUrl("LAD", "Los Angeles Dodgers") },
      { id: "atl", name: "Atlanta Braves", abbreviation: "ATL", seed: 3, league: "NL", logo_url: mlbTeamLogoUrl("ATL", "Atlanta Braves") },
      { id: "sd", name: "San Diego Padres", abbreviation: "SD", seed: 4, league: "NL", logo_url: mlbTeamLogoUrl("SD", "San Diego Padres") },
      { id: "chc", name: "Chicago Cubs", abbreviation: "CHC", seed: 5, league: "NL", logo_url: mlbTeamLogoUrl("CHC", "Chicago Cubs") },
      { id: "phi", name: "Philadelphia Phillies", abbreviation: "PHI", seed: 6, league: "NL", logo_url: mlbTeamLogoUrl("PHI", "Philadelphia Phillies") },
    ],
    nodes: [
      {
        id: "al-wc-1",
        round: "wild_card",
        league: "AL",
        label: "AL Wild Card · 3 vs 6",
        points: 1,
        left: { teamId: "hou", sourceNodeId: null },
        right: { teamId: "cws", sourceNodeId: null },
      },
      {
        id: "al-wc-2",
        round: "wild_card",
        league: "AL",
        label: "AL Wild Card · 4 vs 5",
        points: 1,
        left: { teamId: "nyy", sourceNodeId: null },
        right: { teamId: "bos", sourceNodeId: null },
      },
      {
        id: "nl-wc-1",
        round: "wild_card",
        league: "NL",
        label: "NL Wild Card · 3 vs 6",
        points: 1,
        left: { teamId: "atl", sourceNodeId: null },
        right: { teamId: "phi", sourceNodeId: null },
      },
      {
        id: "nl-wc-2",
        round: "wild_card",
        league: "NL",
        label: "NL Wild Card · 4 vs 5",
        points: 1,
        left: { teamId: "sd", sourceNodeId: null },
        right: { teamId: "chc", sourceNodeId: null },
      },
      {
        id: "al-ds-1",
        round: "division_series",
        league: "AL",
        label: "ALDS · No. 1 seed",
        points: 2,
        left: { teamId: "tb", sourceNodeId: null },
        right: { teamId: null, sourceNodeId: "al-wc-2" },
      },
      {
        id: "al-ds-2",
        round: "division_series",
        league: "AL",
        label: "ALDS · No. 2 seed",
        points: 2,
        left: { teamId: "cle", sourceNodeId: null },
        right: { teamId: null, sourceNodeId: "al-wc-1" },
      },
      {
        id: "nl-ds-1",
        round: "division_series",
        league: "NL",
        label: "NLDS · No. 1 seed",
        points: 2,
        left: { teamId: "mil", sourceNodeId: null },
        right: { teamId: null, sourceNodeId: "nl-wc-2" },
      },
      {
        id: "nl-ds-2",
        round: "division_series",
        league: "NL",
        label: "NLDS · No. 2 seed",
        points: 2,
        left: { teamId: "lad", sourceNodeId: null },
        right: { teamId: null, sourceNodeId: "nl-wc-1" },
      },
      {
        id: "al-cs",
        round: "championship_series",
        league: "AL",
        label: "ALCS",
        points: 5,
        left: { teamId: null, sourceNodeId: "al-ds-1" },
        right: { teamId: null, sourceNodeId: "al-ds-2" },
      },
      {
        id: "nl-cs",
        round: "championship_series",
        league: "NL",
        label: "NLCS",
        points: 5,
        left: { teamId: null, sourceNodeId: "nl-ds-1" },
        right: { teamId: null, sourceNodeId: "nl-ds-2" },
      },
      {
        id: "ws",
        round: "world_series",
        league: null,
        label: "WORLD SERIES",
        points: 10,
        left: { teamId: null, sourceNodeId: "al-cs" },
        right: { teamId: null, sourceNodeId: "nl-cs" },
      },
    ],
  },
  ownBracket: {
    "al-wc-1": "hou",
    "al-wc-2": "nyy",
    "nl-wc-1": "atl",
    "nl-wc-2": "chc",
    "al-ds-1": "tb",
    "al-ds-2": "cle",
    "nl-ds-1": "mil",
    "nl-ds-2": "lad",
    "al-cs": "tb",
    "nl-cs": "lad",
    "ws": "lad",
  },
  ownBracketScore: 14,
  brackets: [
    {
      profile_id: "preview-shane",
      display_name: "Shane",
      score: 17,
      is_current_user: false,
      picks: {
        "al-wc-1": "hou", "al-wc-2": "nyy", "nl-wc-1": "atl", "nl-wc-2": "sd",
        "al-ds-1": "tb", "al-ds-2": "cle", "nl-ds-1": "mil", "nl-ds-2": "lad",
        "al-cs": "tb", "nl-cs": "lad", "ws": "tb",
      },
    },
    {
      profile_id: "preview-you",
      display_name: "Cody",
      score: 14,
      is_current_user: true,
      picks: {
        "al-wc-1": "hou", "al-wc-2": "nyy", "nl-wc-1": "atl", "nl-wc-2": "chc",
        "al-ds-1": "tb", "al-ds-2": "cle", "nl-ds-1": "mil", "nl-ds-2": "lad",
        "al-cs": "tb", "nl-cs": "lad", "ws": "lad",
      },
    },
    {
      profile_id: "preview-tyler",
      display_name: "Tyler",
      score: 15,
      is_current_user: false,
      picks: {
        "al-wc-1": "hou", "al-wc-2": "bos", "nl-wc-1": "atl", "nl-wc-2": "chc",
        "al-ds-1": "tb", "al-ds-2": "hou", "nl-ds-1": "mil", "nl-ds-2": "lad",
        "al-cs": "tb", "nl-cs": "lad", "ws": "lad",
      },
    },
    {
      profile_id: "preview-troy",
      display_name: "Troy",
      score: 11,
      is_current_user: false,
      picks: {
        "al-wc-1": "hou", "al-wc-2": "nyy", "nl-wc-1": "phi", "nl-wc-2": "sd",
        "al-ds-1": "nyy", "al-ds-2": "cle", "nl-ds-1": "mil", "nl-ds-2": "lad",
        "al-cs": "cle", "nl-cs": "lad", "ws": "lad",
      },
    },
    {
      profile_id: "preview-lib",
      display_name: "Lib",
      score: 12,
      is_current_user: false,
      picks: {
        "al-wc-1": "cws", "al-wc-2": "bos", "nl-wc-1": "atl", "nl-wc-2": "chc",
        "al-ds-1": "tb", "al-ds-2": "cle", "nl-ds-1": "chc", "nl-ds-2": "lad",
        "al-cs": "cle", "nl-cs": "lad", "ws": "cle",
      },
    },
    {
      profile_id: "preview-chody",
      display_name: "Chody",
      score: 10,
      is_current_user: false,
      picks: {
        "al-wc-1": "cws", "al-wc-2": "nyy", "nl-wc-1": "phi", "nl-wc-2": "sd",
        "al-ds-1": "tb", "al-ds-2": "cle", "nl-ds-1": "mil", "nl-ds-2": "phi",
        "al-cs": "tb", "nl-cs": "mil", "ws": "mil",
      },
    },
  ],
  series: [
    {
      series_id: "al-wc-1",
      round: "wild_card",
      league: "AL",
      label: "AL Wild Card · 3 vs 6",
      team_a_id: "hou",
      team_a_name: "Houston Astros",
      team_b_id: "cws",
      team_b_name: "Chicago White Sox",
      starts_at: "2026-09-29T13:00:00-05:00",
      status: "scheduled",
      winner_team_id: null,
      series_score: null,
      schedule: ["G1 · Tue Sep 29", "G2 · Wed Sep 30", "G3 · Thu Oct 1 if needed"],
      team_a_moneyline: -135,
      team_b_moneyline: 115,
      odds_source: "Consensus",
      odds_updated_at: "2026-09-25T08:00:00-05:00",
    },
    {
      series_id: "al-wc-2",
      round: "wild_card",
      league: "AL",
      label: "AL Wild Card · 4 vs 5",
      team_a_id: "nyy",
      team_a_name: "New York Yankees",
      team_b_id: "bos",
      team_b_name: "Boston Red Sox",
      starts_at: "2026-09-29T15:00:00-05:00",
      status: "scheduled",
      winner_team_id: null,
      series_score: null,
      schedule: ["G1 · Tue Sep 29", "G2 · Wed Sep 30", "G3 · Thu Oct 1 if needed"],
      team_a_moneyline: -120,
      team_b_moneyline: 105,
      odds_source: "Consensus",
      odds_updated_at: "2026-09-25T08:00:00-05:00",
    },
    {
      series_id: "nl-wc-1",
      round: "wild_card",
      league: "NL",
      label: "NL Wild Card · 3 vs 6",
      team_a_id: "atl",
      team_a_name: "Atlanta Braves",
      team_b_id: "phi",
      team_b_name: "Philadelphia Phillies",
      starts_at: "2026-09-29T17:00:00-05:00",
      status: "scheduled",
      winner_team_id: null,
      series_score: null,
      schedule: ["G1 · Tue Sep 29", "G2 · Wed Sep 30", "G3 · Thu Oct 1 if needed"],
      team_a_moneyline: -110,
      team_b_moneyline: -105,
      odds_source: "Consensus",
      odds_updated_at: "2026-09-25T08:00:00-05:00",
    },
    {
      series_id: "nl-wc-2",
      round: "wild_card",
      league: "NL",
      label: "NL Wild Card · 4 vs 5",
      team_a_id: "sd",
      team_a_name: "San Diego Padres",
      team_b_id: "chc",
      team_b_name: "Chicago Cubs",
      starts_at: "2026-09-29T19:00:00-05:00",
      status: "scheduled",
      winner_team_id: null,
      series_score: null,
      schedule: ["G1 · Tue Sep 29", "G2 · Wed Sep 30", "G3 · Thu Oct 1 if needed"],
      team_a_moneyline: -125,
      team_b_moneyline: 110,
      odds_source: "Consensus",
      odds_updated_at: "2026-09-25T08:00:00-05:00",
    },
  ],
  ownRoundPicks: [
    { series_id: "al-wc-1", winner_team_id: "hou", picked_at: "2026-09-24T18:00:00-05:00" },
    { series_id: "al-wc-2", winner_team_id: "nyy", picked_at: "2026-09-24T18:00:00-05:00" },
    { series_id: "nl-wc-1", winner_team_id: "atl", picked_at: "2026-09-24T18:00:00-05:00" },
    { series_id: "nl-wc-2", winner_team_id: "chc", picked_at: "2026-09-24T18:00:00-05:00" },
  ],
  roundPickEntries: [
    {
      profile_id: "preview-you", display_name: "Cody", is_current_user: true, completed: 4, total: 4, wins: 0, losses: 0,
      picks: { "al-wc-1": "hou", "al-wc-2": "nyy", "nl-wc-1": "atl", "nl-wc-2": "chc" },
    },
    {
      profile_id: "preview-chody", display_name: "Chody", is_current_user: false, completed: 4, total: 4, wins: 0, losses: 0,
      picks: { "al-wc-1": "cws", "al-wc-2": "nyy", "nl-wc-1": "phi", "nl-wc-2": "sd" },
    },
    {
      profile_id: "preview-lib", display_name: "Lib", is_current_user: false, completed: 4, total: 4, wins: 0, losses: 0,
      picks: { "al-wc-1": "cws", "al-wc-2": "bos", "nl-wc-1": "atl", "nl-wc-2": "chc" },
    },
    {
      profile_id: "preview-shane", display_name: "Shane", is_current_user: false, completed: 4, total: 4, wins: 0, losses: 0,
      picks: { "al-wc-1": "hou", "al-wc-2": "nyy", "nl-wc-1": "atl", "nl-wc-2": "sd" },
    },
    {
      profile_id: "preview-troy", display_name: "Troy", is_current_user: false, completed: 4, total: 4, wins: 0, losses: 0,
      picks: { "al-wc-1": "hou", "al-wc-2": "nyy", "nl-wc-1": "phi", "nl-wc-2": "sd" },
    },
    {
      profile_id: "preview-tyler", display_name: "Tyler", is_current_user: false, completed: 4, total: 4, wins: 0, losses: 0,
      picks: { "al-wc-1": "hou", "al-wc-2": "bos", "nl-wc-1": "atl", "nl-wc-2": "chc" },
    },
  ],
  spotlight: {
    series_id: "al-wc-2",
    title: "Yankees vs. Red Sox",
    round: "WILD CARD",
    status: "Wild Card · best of three",
    overview: "A short-series rivalry built around power, bullpen leverage, and zero room for a slow start.",
    keys: ["Yankees power vs. Boston relief depth", "Game 1 leverage from the first inning"],
    player_to_watch: "Aaron Judge",
    player_context: "New York Yankees · middle of the order",
    stats: ["Power · on-base · short-series leverage"],
  },
  featuredChallenge: {
    id: "mlb-2026-play-04",
    title: "Who Am I",
    kicker: "WHO AM I",
    description: "Two identities. Progressive clues. One averaged final score.",
    route: "/mlb/challenge",
    date: "2026-10-06",
    game_type: "who_am_i",
    ready: true,
    is_live: true,
  },
};


export const MLB_OWNER_PREVIEW_CHAMPIONSHIP: MlbChampionship = {
  season: 2026,
  totalMax: 100,
  seriesMax: 43,
  bracketMax: 32,
  playMax: 25,
  own: {
    profile_id: "preview-you",
    display_name: "Cody",
    is_current_user: true,
    overall_rank: 2,
    total_points: 49.5,
    series_points: 23,
    series_rank: 2,
    bracket_points: 14,
    bracket_rank: 3,
    play_points: 12.5,
    play_rank: 1,
  },
  standings: [
    {
      profile_id: "preview-shane",
      display_name: "Shane",
      is_current_user: false,
      overall_rank: 1,
      total_points: 52.25,
      series_points: 24,
      series_rank: 1,
      bracket_points: 17,
      bracket_rank: 1,
      play_points: 11.25,
      play_rank: 2,
    },
    {
      profile_id: "preview-you",
      display_name: "Cody",
      is_current_user: true,
      overall_rank: 2,
      total_points: 49.5,
      series_points: 23,
      series_rank: 2,
      bracket_points: 14,
      bracket_rank: 3,
      play_points: 12.5,
      play_rank: 1,
    },
    {
      profile_id: "preview-tyler",
      display_name: "Tyler",
      is_current_user: false,
      overall_rank: 3,
      total_points: 46,
      series_points: 21,
      series_rank: 4,
      bracket_points: 15,
      bracket_rank: 2,
      play_points: 10,
      play_rank: 6,
    },
    {
      profile_id: "preview-troy",
      display_name: "Troy",
      is_current_user: false,
      overall_rank: 4,
      total_points: 43.75,
      series_points: 22,
      series_rank: 3,
      bracket_points: 11,
      bracket_rank: 5,
      play_points: 10.75,
      play_rank: 3,
    },
    {
      profile_id: "preview-lib",
      display_name: "Lib",
      is_current_user: false,
      overall_rank: 5,
      total_points: 40.5,
      series_points: 18,
      series_rank: 5,
      bracket_points: 12,
      bracket_rank: 4,
      play_points: 10.5,
      play_rank: 5,
    },
    {
      profile_id: "preview-chody",
      display_name: "Chody",
      is_current_user: false,
      overall_rank: 6,
      total_points: 37.75,
      series_points: 17,
      series_rank: 6,
      bracket_points: 10,
      bracket_rank: 6,
      play_points: 10.75,
      play_rank: 3,
    },
  ],
};


export const MLB_OWNER_PREVIEW_PLAY_LEADERBOARD: MlbPlayChallengeLeaderboardEntry[] = [
  {
    rank: 1, profileId: "preview-shane", displayName: "Shane", initials: "SH", avatarPhotoData: null,
    rawScore: 94, gameType: "millionaire",
    publicResult: { outcome: "walked-away", final_money: 500000, completed_questions: 7, lifelines_used: 1, time_remaining_ms: 17000, score: 94 },
    resultDetail: { outcome: "walked-away", final_money: 500000, completed_questions: 7, lifelines_used: 1, time_remaining_ms: 17000 },
    completedAt: "2026-10-03T12:20:00-05:00", isCurrentUser: false,
  },
  {
    rank: 2, profileId: "preview-you", displayName: "Cody", initials: "CK", avatarPhotoData: null,
    rawScore: 90, gameType: "millionaire",
    publicResult: { outcome: "walked-away", final_money: 500000, completed_questions: 7, lifelines_used: 0, time_remaining_ms: 9000, score: 90 },
    resultDetail: { outcome: "walked-away", final_money: 500000, completed_questions: 7, lifelines_used: 0, time_remaining_ms: 9000 },
    completedAt: "2026-10-03T12:22:00-05:00", isCurrentUser: true,
  },
  {
    rank: 3, profileId: "preview-troy", displayName: "Troy", initials: "TR", avatarPhotoData: null,
    rawScore: 80, gameType: "millionaire",
    publicResult: { outcome: "lost", final_money: 100000, completed_questions: 6, lifelines_used: 0, time_remaining_ms: 24000, score: 80 },
    resultDetail: { outcome: "lost", final_money: 100000, completed_questions: 6, lifelines_used: 0, time_remaining_ms: 24000 },
    completedAt: "2026-10-03T12:25:00-05:00", isCurrentUser: false,
  },
  {
    rank: 4, profileId: "preview-lib", displayName: "Lib", initials: "LB", avatarPhotoData: null,
    rawScore: 78, gameType: "millionaire",
    publicResult: { outcome: "lost", final_money: 100000, completed_questions: 6, lifelines_used: 1, time_remaining_ms: 31000, score: 78 },
    resultDetail: { outcome: "lost", final_money: 100000, completed_questions: 6, lifelines_used: 1, time_remaining_ms: 31000 },
    completedAt: "2026-10-03T12:30:00-05:00", isCurrentUser: false,
  },
  {
    rank: 5, profileId: "preview-tyler", displayName: "Tyler", initials: "TY", avatarPhotoData: null,
    rawScore: 66, gameType: "millionaire",
    publicResult: { outcome: "lost", final_money: 5000, completed_questions: 5, lifelines_used: 1, time_remaining_ms: 43000, score: 66 },
    resultDetail: { outcome: "lost", final_money: 5000, completed_questions: 5, lifelines_used: 1, time_remaining_ms: 43000 },
    completedAt: "2026-10-03T12:35:00-05:00", isCurrentUser: false,
  },
  {
    rank: 6, profileId: "preview-chody", displayName: "Chody", initials: "CH", avatarPhotoData: null,
    rawScore: 51, gameType: "millionaire",
    publicResult: { outcome: "lost", final_money: 5000, completed_questions: 4, lifelines_used: 2, time_remaining_ms: 51000, score: 51 },
    resultDetail: { outcome: "lost", final_money: 5000, completed_questions: 4, lifelines_used: 2, time_remaining_ms: 51000 },
    completedAt: "2026-10-03T12:40:00-05:00", isCurrentUser: false,
  },
];
