import type { MlbPlayoffsHub } from "./mlbPlayoffsRepository";

export const MLB_OWNER_PREVIEW_HUB: MlbPlayoffsHub = {
  season: 2026,
  publicEnabled: false,
  fieldReady: true,
  currentRound: "wild_card",
  bracketLockAt: "2026-09-29T12:00:00-05:00",
  bracketLocked: false,
  bracketTemplate: {
    teams: [
      { id: "tb", name: "Tampa Bay Rays", abbreviation: "TB", seed: 1, league: "AL", logo_url: null },
      { id: "cle", name: "Cleveland Guardians", abbreviation: "CLE", seed: 2, league: "AL", logo_url: null },
      { id: "hou", name: "Houston Astros", abbreviation: "HOU", seed: 3, league: "AL", logo_url: null },
      { id: "nyy", name: "New York Yankees", abbreviation: "NYY", seed: 4, league: "AL", logo_url: null },
      { id: "bos", name: "Boston Red Sox", abbreviation: "BOS", seed: 5, league: "AL", logo_url: null },
      { id: "cws", name: "Chicago White Sox", abbreviation: "CWS", seed: 6, league: "AL", logo_url: null },
      { id: "mil", name: "Milwaukee Brewers", abbreviation: "MIL", seed: 1, league: "NL", logo_url: null },
      { id: "lad", name: "Los Angeles Dodgers", abbreviation: "LAD", seed: 2, league: "NL", logo_url: null },
      { id: "atl", name: "Atlanta Braves", abbreviation: "ATL", seed: 3, league: "NL", logo_url: null },
      { id: "sd", name: "San Diego Padres", abbreviation: "SD", seed: 4, league: "NL", logo_url: null },
      { id: "chc", name: "Chicago Cubs", abbreviation: "CHC", seed: 5, league: "NL", logo_url: null },
      { id: "phi", name: "Philadelphia Phillies", abbreviation: "PHI", seed: 6, league: "NL", logo_url: null },
    ],
    nodes: [
      {
        id: "al-wc-1",
        round: "wild_card",
        league: "AL",
        label: "AL Wild Card · 3 vs 6",
        points: 1,
        left: { teamId: "hou", sourceNodeId: null },
        right: { teamId: "cws", sourceNodeId: null },
      },
      {
        id: "al-wc-2",
        round: "wild_card",
        league: "AL",
        label: "AL Wild Card · 4 vs 5",
        points: 1,
        left: { teamId: "nyy", sourceNodeId: null },
        right: { teamId: "bos", sourceNodeId: null },
      },
      {
        id: "nl-wc-1",
        round: "wild_card",
        league: "NL",
        label: "NL Wild Card · 3 vs 6",
        points: 1,
        left: { teamId: "atl", sourceNodeId: null },
        right: { teamId: "phi", sourceNodeId: null },
      },
      {
        id: "nl-wc-2",
        round: "wild_card",
        league: "NL",
        label: "NL Wild Card · 4 vs 5",
        points: 1,
        left: { teamId: "sd", sourceNodeId: null },
        right: { teamId: "chc", sourceNodeId: null },
      },
      {
        id: "al-ds-1",
        round: "division_series",
        league: "AL",
        label: "ALDS · No. 1 seed",
        points: 2,
        left: { teamId: "tb", sourceNodeId: null },
        right: { teamId: null, sourceNodeId: "al-wc-2" },
      },
      {
        id: "al-ds-2",
        round: "division_series",
        league: "AL",
        label: "ALDS · No. 2 seed",
        points: 2,
        left: { teamId: "cle", sourceNodeId: null },
        right: { teamId: null, sourceNodeId: "al-wc-1" },
      },
      {
        id: "nl-ds-1",
        round: "division_series",
        league: "NL",
        label: "NLDS · No. 1 seed",
        points: 2,
        left: { teamId: "mil", sourceNodeId: null },
        right: { teamId: null, sourceNodeId: "nl-wc-2" },
      },
      {
        id: "nl-ds-2",
        round: "division_series",
        league: "NL",
        label: "NLDS · No. 2 seed",
        points: 2,
        left: { teamId: "lad", sourceNodeId: null },
        right: { teamId: null, sourceNodeId: "nl-wc-1" },
      },
      {
        id: "al-cs",
        round: "championship_series",
        league: "AL",
        label: "ALCS",
        points: 4,
        left: { teamId: null, sourceNodeId: "al-ds-1" },
        right: { teamId: null, sourceNodeId: "al-ds-2" },
      },
      {
        id: "nl-cs",
        round: "championship_series",
        league: "NL",
        label: "NLCS",
        points: 4,
        left: { teamId: null, sourceNodeId: "nl-ds-1" },
        right: { teamId: null, sourceNodeId: "nl-ds-2" },
      },
      {
        id: "ws",
        round: "world_series",
        league: null,
        label: "WORLD SERIES",
        points: 8,
        left: { teamId: null, sourceNodeId: "al-cs" },
        right: { teamId: null, sourceNodeId: "nl-cs" },
      },
    ],
  },
  ownBracket: {
    "al-wc-1": "hou",
    "al-wc-2": "nyy",
    "nl-wc-1": "atl",
    "nl-wc-2": "chc",
    "al-ds-1": "tb",
    "al-ds-2": "cle",
    "nl-ds-1": "mil",
    "nl-ds-2": "lad",
    "al-cs": "tb",
    "nl-cs": "lad",
    "ws": "lad",
  },
  ownBracketScore: 12,
  brackets: [
    {
      profile_id: "preview-shane",
      display_name: "Shane",
      score: 14,
      is_current_user: false,
      picks: {
        "al-wc-1": "hou",
        "al-wc-2": "nyy",
        "nl-wc-1": "atl",
        "nl-wc-2": "sd",
        "al-ds-1": "tb",
        "al-ds-2": "cle",
        "nl-ds-1": "mil",
        "nl-ds-2": "lad",
        "al-cs": "tb",
        "nl-cs": "lad",
        "ws": "tb",
      },
    },
    {
      profile_id: "preview-you",
      display_name: "Cody",
      score: 12,
      is_current_user: true,
      picks: {
        "al-wc-1": "hou",
        "al-wc-2": "nyy",
        "nl-wc-1": "atl",
        "nl-wc-2": "chc",
        "al-ds-1": "tb",
        "al-ds-2": "cle",
        "nl-ds-1": "mil",
        "nl-ds-2": "lad",
        "al-cs": "tb",
        "nl-cs": "lad",
        "ws": "lad",
      },
    },
    {
      profile_id: "preview-alex",
      display_name: "Alex",
      score: 9,
      is_current_user: false,
      picks: {
        "al-wc-1": "cws",
        "al-wc-2": "bos",
        "nl-wc-1": "atl",
        "nl-wc-2": "chc",
        "al-ds-1": "tb",
        "al-ds-2": "cle",
        "nl-ds-1": "mil",
        "nl-ds-2": "lad",
        "al-cs": "cle",
        "nl-cs": "mil",
        "ws": "mil",
      },
    },
  ],
  series: [
    {
      series_id: "al-wc-1",
      round: "wild_card",
      league: "AL",
      label: "AL Wild Card · 3 vs 6",
      team_a_id: "hou",
      team_a_name: "Houston Astros",
      team_b_id: "cws",
      team_b_name: "Chicago White Sox",
      starts_at: "2026-09-29T13:00:00-05:00",
      status: "scheduled",
      winner_team_id: null,
      series_score: null,
      schedule: ["G1 · Tue Sep 29", "G2 · Wed Sep 30", "G3 · Thu Oct 1 if needed"],
    },
    {
      series_id: "al-wc-2",
      round: "wild_card",
      league: "AL",
      label: "AL Wild Card · 4 vs 5",
      team_a_id: "nyy",
      team_a_name: "New York Yankees",
      team_b_id: "bos",
      team_b_name: "Boston Red Sox",
      starts_at: "2026-09-29T15:00:00-05:00",
      status: "scheduled",
      winner_team_id: null,
      series_score: null,
      schedule: ["G1 · Tue Sep 29", "G2 · Wed Sep 30", "G3 · Thu Oct 1 if needed"],
    },
    {
      series_id: "nl-wc-1",
      round: "wild_card",
      league: "NL",
      label: "NL Wild Card · 3 vs 6",
      team_a_id: "atl",
      team_a_name: "Atlanta Braves",
      team_b_id: "phi",
      team_b_name: "Philadelphia Phillies",
      starts_at: "2026-09-29T17:00:00-05:00",
      status: "scheduled",
      winner_team_id: null,
      series_score: null,
      schedule: ["G1 · Tue Sep 29", "G2 · Wed Sep 30", "G3 · Thu Oct 1 if needed"],
    },
    {
      series_id: "nl-wc-2",
      round: "wild_card",
      league: "NL",
      label: "NL Wild Card · 4 vs 5",
      team_a_id: "sd",
      team_a_name: "San Diego Padres",
      team_b_id: "chc",
      team_b_name: "Chicago Cubs",
      starts_at: "2026-09-29T19:00:00-05:00",
      status: "scheduled",
      winner_team_id: null,
      series_score: null,
      schedule: ["G1 · Tue Sep 29", "G2 · Wed Sep 30", "G3 · Thu Oct 1 if needed"],
    },
  ],
  ownRoundPicks: [
    { series_id: "al-wc-1", winner_team_id: "hou", picked_at: "2026-09-24T18:00:00-05:00" },
    { series_id: "al-wc-2", winner_team_id: "nyy", picked_at: "2026-09-24T18:00:00-05:00" },
  ],
  spotlight: {
    title: "Yankees vs. Red Sox",
    round: "WILD CARD",
    status: "Preview matchup · best of three",
    overview: "A short-series rivalry built around power, bullpen leverage, and zero room for a slow start.",
    keys: ["Yankees power vs. Boston relief depth", "Game 1 leverage from the first inning"],
    player_to_watch: "Aaron Judge",
    player_context: "New York Yankees · middle of the order",
    stats: ["Power · on-base · short-series leverage"],
  },
  featuredChallenge: {
    id: "2026-october-legend-rivera",
    title: "October Legend",
    kicker: "WHO AM I",
    description: "Four clues. One postseason icon.",
    route: "/mlb/challenge",
  },
};
