-- Initial Wheel of Football current-ability grade authority.
-- The authority is intentionally private. 2025 AP/NGS honors anchor the recent
-- elite tiers; the remaining entries are HQ football calibration for current ability.

insert into private.wheel_football_grade_authority(
  name_key,display_name,position_group,hidden_grade,basis
) values
  ('drakemaye','Drake Maye','QB',98.0,'2025 AP second team / NFL NGS first-team QB'),
  ('matthewstafford','Matthew Stafford','QB',97.0,'2025 AP first-team QB'),
  ('joshallen','Josh Allen','QB',97.0,'Recent MVP/All-Pro caliber'),
  ('lamarjackson','Lamar Jackson','QB',96.0,'Recent MVP/All-Pro caliber'),
  ('patrickmahomes','Patrick Mahomes','QB',95.0,'Elite current-ability calibration'),
  ('joeburrow','Joe Burrow','QB',95.0,'Elite current-ability calibration'),
  ('justinherbert','Justin Herbert','QB',94.0,'High-end current-ability calibration'),
  ('jaydendaniels','Jayden Daniels','QB',93.0,'High-end current-ability calibration'),
  ('jalenhurts','Jalen Hurts','QB',92.0,'High-end current-ability calibration'),
  ('bakermayfield','Baker Mayfield','QB',91.0,'High-end current-ability calibration'),
  ('jaredgoff','Jared Goff','QB',91.0,'High-end current-ability calibration'),
  ('bonix','Bo Nix','QB',90.0,'High-end current-ability calibration'),
  ('dakprescott','Dak Prescott','QB',90.0,'High-end current-ability calibration'),
  ('jordanlove','Jordan Love','QB',89.0,'Current-ability calibration'),
  ('cjstroud','C.J. Stroud','QB',89.0,'Current-ability calibration'),
  ('calebwilliams','Caleb Williams','QB',88.0,'Current-ability calibration'),
  ('bijanrobinson','Bijan Robinson','RB',99.0,'2025 AP first-team RB'),
  ('christianmccaffrey','Christian McCaffrey','RB',97.0,'2025 AP first-team all-purpose'),
  ('jamescook','James Cook','RB',96.0,'2025 AP second-team RB'),
  ('jahmyrgibbs','Jahmyr Gibbs','RB',95.0,'Elite current-ability calibration'),
  ('saquonbarkley','Saquon Barkley','RB',94.0,'Elite current-ability calibration'),
  ('derrickhenry','Derrick Henry','RB',93.0,'Elite current-ability calibration'),
  ('jonathantaylor','Jonathan Taylor','RB',93.0,'Elite current-ability calibration'),
  ('devonachane','De''Von Achane','RB',92.0,'High-end current-ability calibration'),
  ('joshjacobs','Josh Jacobs','RB',90.0,'High-end current-ability calibration'),
  ('kyrenwilliams','Kyren Williams','RB',90.0,'High-end current-ability calibration'),
  ('breecehall','Breece Hall','RB',89.0,'Current-ability calibration'),
  ('pukanacua','Puka Nacua','WR',99.0,'2025 unanimous AP first-team WR'),
  ('jaxonsmithnjigba','Jaxon Smith-Njigba','WR',99.0,'2025 unanimous AP first-team WR'),
  ('jamarrchase','Ja''Marr Chase','WR',98.0,'2025 AP first-team WR'),
  ('justinjefferson','Justin Jefferson','WR',97.0,'Elite current-ability calibration'),
  ('georgepickens','George Pickens','WR',96.0,'2025 AP second-team WR'),
  ('amonrastbrown','Amon-Ra St. Brown','WR',95.0,'2025 AP second-team WR'),
  ('ceedeelamb','CeeDee Lamb','WR',95.0,'Elite current-ability calibration'),
  ('chrisolave','Chris Olave','WR',94.0,'2025 AP second-team WR'),
  ('nicocollins','Nico Collins','WR',94.0,'High-end current-ability calibration'),
  ('ajbrown','A.J. Brown','WR',94.0,'High-end current-ability calibration'),
  ('maliknabers','Malik Nabers','WR',93.0,'High-end current-ability calibration'),
  ('teehiggins','Tee Higgins','WR',92.0,'High-end current-ability calibration'),
  ('garrettwilson','Garrett Wilson','WR',92.0,'High-end current-ability calibration'),
  ('laddmcconkey','Ladd McConkey','WR',91.0,'High-end current-ability calibration'),
  ('drakelondon','Drake London','WR',91.0,'High-end current-ability calibration'),
  ('terrymclaurin','Terry McLaurin','WR',91.0,'High-end current-ability calibration'),
  ('brianthomasjr','Brian Thomas Jr.','WR',91.0,'High-end current-ability calibration'),
  ('mikeevans','Mike Evans','WR',89.0,'Current-ability calibration'),
  ('treymcbride','Trey McBride','TE',99.0,'2025 AP first-team TE'),
  ('brockbowers','Brock Bowers','TE',96.0,'Elite current-ability calibration'),
  ('kylepitts','Kyle Pitts','TE',95.0,'2025 AP second-team TE'),
  ('georgekittle','George Kittle','TE',94.0,'Elite current-ability calibration'),
  ('samlaporta','Sam LaPorta','TE',91.0,'High-end current-ability calibration'),
  ('traviskelce','Travis Kelce','TE',90.0,'High-end current-ability calibration'),
  ('markandrews','Mark Andrews','TE',89.0,'Current-ability calibration'),
  ('mylesgarrett','Myles Garrett','Front Seven',100.0,'2025 unanimous AP first-team edge'),
  ('willandersonjr','Will Anderson Jr.','Front Seven',98.0,'2025 AP first-team edge'),
  ('micahparsons','Micah Parsons','Front Seven',98.0,'2025 AP first-team edge'),
  ('jefferysimmons','Jeffery Simmons','Front Seven',97.0,'2025 AP first-team interior DL'),
  ('fredwarner','Fred Warner','Front Seven',97.0,'Elite current-ability calibration'),
  ('zachallen','Zach Allen','Front Seven',96.0,'2025 AP first-team interior DL'),
  ('tjwatt','T.J. Watt','Front Seven',96.0,'Elite current-ability calibration'),
  ('chrisjones','Chris Jones','Front Seven',96.0,'Elite current-ability calibration'),
  ('jackcampbell','Jack Campbell','Front Seven',96.0,'2025 AP first-team LB'),
  ('jordynbrooks','Jordyn Brooks','Front Seven',95.0,'2025 AP first-team LB'),
  ('maxxcrosby','Maxx Crosby','Front Seven',95.0,'Elite current-ability calibration'),
  ('dexterlawrenceii','Dexter Lawrence II','Front Seven',95.0,'Elite current-ability calibration'),
  ('brianburns','Brian Burns','Front Seven',94.0,'2025 AP second-team edge'),
  ('daniellehunter','Danielle Hunter','Front Seven',94.0,'2025 AP second-team edge'),
  ('aidanhutchinson','Aidan Hutchinson','Front Seven',94.0,'2025 AP second-team edge'),
  ('roquansmith','Roquan Smith','Front Seven',93.0,'High-end current-ability calibration'),
  ('leonardwilliams','Leonard Williams','Front Seven',93.0,'2025 AP second-team interior DL'),
  ('cameronheyward','Cameron Heyward','Front Seven',92.0,'2025 AP second-team interior DL'),
  ('devinlloyd','Devin Lloyd','Front Seven',92.0,'2025 AP second-team LB'),
  ('quinnenwilliams','Quinnen Williams','Front Seven',92.0,'High-end current-ability calibration'),
  ('ernestjonesiv','Ernest Jones IV','Front Seven',91.0,'2025 AP second-team LB'),
  ('derekstingleyjr','Derek Stingley Jr.','Secondary',99.0,'2025 AP first-team CB'),
  ('kylehamilton','Kyle Hamilton','Secondary',98.0,'2025 AP first-team safety'),
  ('patricksurtainii','Patrick Surtain II','Secondary',97.0,'2025 AP second-team CB / recent DPOY caliber'),
  ('quinyonmitchell','Quinyon Mitchell','Secondary',97.0,'2025 AP first-team CB'),
  ('cooperdejean','Cooper DeJean','Secondary',96.0,'2025 AP first-team slot CB'),
  ('kevinbyard','Kevin Byard','Secondary',95.0,'2025 AP first-team safety'),
  ('devonwitherspoon','Devon Witherspoon','Secondary',94.0,'2025 AP second-team CB'),
  ('derwinjamesjr','Derwin James Jr.','Secondary',94.0,'2025 AP second-team slot CB'),
  ('jessiebatesiii','Jessie Bates III','Secondary',94.0,'2025 AP second-team safety'),
  ('xaviermckinney','Xavier McKinney','Secondary',93.0,'2025 AP second-team safety'),
  ('brianbranch','Brian Branch','Secondary',93.0,'High-end current-ability calibration'),
  ('saucegardner','Sauce Gardner','Secondary',92.0,'High-end current-ability calibration'),
  ('talanoahufanga','Talanoa Hufanga','Secondary',91.0,'2025 AP second-team safety'),
  ('andyreid','Andy Reid','Head Coach',99.0,'HQ current coaching calibration'),
  ('seanmcvay','Sean McVay','Head Coach',98.0,'HQ current coaching calibration'),
  ('miketomlin','Mike Tomlin','Head Coach',97.0,'HQ current coaching calibration'),
  ('kyleshanahan','Kyle Shanahan','Head Coach',96.0,'HQ current coaching calibration'),
  ('seanpayton','Sean Payton','Head Coach',95.0,'HQ current coaching calibration'),
  ('dancampbell','Dan Campbell','Head Coach',95.0,'HQ current coaching calibration'),
  ('johnharbaugh','John Harbaugh','Head Coach',94.0,'HQ current coaching calibration'),
  ('mattlafleur','Matt LaFleur','Head Coach',94.0,'HQ current coaching calibration'),
  ('seanmcdermott','Sean McDermott','Head Coach',93.0,'HQ current coaching calibration'),
  ('demecoryans','DeMeco Ryans','Head Coach',93.0,'HQ current coaching calibration'),
  ('nicksirianni','Nick Sirianni','Head Coach',93.0,'HQ current coaching calibration'),
  ('kevinoconnell','Kevin O''Connell','Head Coach',92.0,'HQ current coaching calibration'),
  ('mikevrabel','Mike Vrabel','Head Coach',92.0,'HQ current coaching calibration'),
  ('jimharbaugh','Jim Harbaugh','Head Coach',92.0,'HQ current coaching calibration'),
  ('benjohnson','Ben Johnson','Head Coach',91.0,'HQ current coaching calibration'),
  ('danquinn','Dan Quinn','Head Coach',91.0,'HQ current coaching calibration'),
  ('liamcoen','Liam Coen','Head Coach',90.0,'HQ current coaching calibration'),
  ('toddbowles','Todd Bowles','Head Coach',90.0,'HQ current coaching calibration'),
  ('kellenmoore','Kellen Moore','Head Coach',89.0,'HQ current coaching calibration'),
  ('aaronglenn','Aaron Glenn','Head Coach',88.0,'HQ current coaching calibration'),
  ('brianschottenheimer','Brian Schottenheimer','Head Coach',87.0,'HQ current coaching calibration'),
  ('davecanales','Dave Canales','Head Coach',87.0,'HQ current coaching calibration')
on conflict (name_key) do update
set display_name = excluded.display_name,
    position_group = excluded.position_group,
    hidden_grade = excluded.hidden_grade,
    basis = excluded.basis,
    updated_at = now();

comment on table private.wheel_football_grade_authority is
  'Private current-ability authority for Wheel of Football. Recent AP/NGS performance anchors the elite tier; HQ calibration fills current stars and coaches.';
