import { barTriviaQuestion, type BarTriviaQuestion } from "../games/barTriviaEngine";

const HEISMAN = "https://www.heisman.com/about-the-heisman/milestones/";
const NCAA_CHAMPS = "https://www.ncaa.com/news/football/article/college-football-national-championship-history";

function q(seed: Parameters<typeof barTriviaQuestion>[0]) {
  return barTriviaQuestion({ ...seed, verifiedAt: "2026-09-28" });
}

export const BAR_TRIVIA_CFB_EVERGREEN_WAVE_3: readonly BarTriviaQuestion[] = [
  // Round 1 — campus culture and recognizable traditions
  q({ id:"cfb-r1-toomers-corner", league:"cfb", round:"round1", category:"Traditions", prompt:"Fans celebrate big wins by rolling Toomer's Corner at which school?", choices:["Auburn","Alabama","Georgia","Ole Miss"], answer:"Auburn", explanation:"Auburn fans traditionally cover the trees and area around Toomer's Corner with toilet paper after victories.", sourceId:"auburn-toomers-corner" }),
  q({ id:"cfb-r1-midnight-yell", league:"cfb", round:"round1", category:"Traditions", prompt:"Which school holds the famous 'Midnight Yell' practice before football games?", choices:["Texas A&M","Texas","Oklahoma","TCU"], answer:"Texas A&M", explanation:"Aggies gather the night before games for Midnight Yell Practice.", sourceId:"texas-am-midnight-yell" }),
  q({ id:"cfb-r1-cowbells", league:"cfb", round:"round1", category:"Fan Culture", prompt:"Cowbells are an unmistakable game-day tradition at which SEC school?", choices:["Mississippi State","Ole Miss","Arkansas","Kentucky"], answer:"Mississippi State", explanation:"Mississippi State fans are famous for ringing cowbells at football games.", sourceId:"mississippi-state-cowbells" }),
  q({ id:"cfb-r1-country-roads", league:"cfb", round:"round1", category:"Stadium Music", prompt:"Fans sing 'Take Me Home, Country Roads' after home wins at which school?", choices:["West Virginia","Virginia Tech","Tennessee","Kentucky"], answer:"West Virginia", explanation:"West Virginia fans and players sing John Denver's Country Roads after Mountaineer victories.", sourceId:"west-virginia-country-roads" }),
  q({ id:"cfb-r1-gator-chomp", league:"cfb", round:"round1", category:"Cheers", prompt:"The two-armed 'Gator Chomp' belongs to fans of which program?", choices:["Florida","Miami","Florida State","Georgia"], answer:"Florida", explanation:"Florida fans mimic an alligator's jaws with the signature Gator Chomp.", sourceId:"florida-gator-chomp" }),
  q({ id:"cfb-r1-hook-em", league:"cfb", round:"round1", category:"Cheers", prompt:"The hand sign 'Hook 'em Horns' belongs to which school?", choices:["Texas","TCU","Texas Tech","Texas A&M"], answer:"Texas", explanation:"Texas fans use the Hook 'em Horns hand sign to represent the Longhorns.", sourceId:"texas-hook-em" }),
  q({ id:"cfb-r1-war-eagle-flight", league:"cfb", round:"round1", category:"Traditions", prompt:"A live eagle circles the stadium before home games at which school?", choices:["Auburn","Boston College","Southern Miss","Air Force"], answer:"Auburn", explanation:"Auburn's pregame eagle flight is one of college football's signature traditions.", sourceId:"auburn-war-eagle" }),
  q({ id:"cfb-r1-between-hedges", league:"cfb", round:"round1", category:"Stadiums", prompt:"Playing 'Between the Hedges' means playing at which school's home stadium?", choices:["Georgia","Auburn","Clemson","South Carolina"], answer:"Georgia", explanation:"Sanford Stadium is famous for the hedges that surround the field.", sourceId:"georgia-sanford-stadium" }),
  q({ id:"cfb-r1-stanford-tree", league:"cfb", round:"round1", category:"Mascots", prompt:"Which school is famous for the unofficial mascot known simply as 'The Tree'?", choices:["Stanford","Oregon","California","Washington"], answer:"Stanford", explanation:"The Stanford Tree represents the school's marching band and is one of college sports' strangest mascot traditions.", sourceId:"stanford-tree" }),
  q({ id:"cfb-r1-purdue-drum", league:"cfb", round:"round1", category:"Traditions", prompt:"Which program is famous for bringing a giant bass drum to football games?", choices:["Purdue","Indiana","Illinois","Iowa"], answer:"Purdue", explanation:"Purdue's 'World's Largest Drum' is a long-running Boilermaker game-day symbol.", sourceId:"purdue-drum" }),
  q({ id:"cfb-r1-miami-smoke", league:"cfb", round:"round1", category:"Entrances", prompt:"Which team is famous for running onto the field through a cloud of smoke?", choices:["Miami","Florida","Florida State","Virginia Tech"], answer:"Miami", explanation:"Miami's smoke-filled entrance has been a Hurricanes tradition for decades.", sourceId:"miami-smoke" }),
  q({ id:"cfb-r1-rammer-jammer", league:"cfb", round:"round1", category:"Cheers", prompt:"The chant 'Rammer Jammer' is associated with which program?", choices:["Alabama","Auburn","Ole Miss","Arkansas"], answer:"Alabama", explanation:"Alabama fans use the Rammer Jammer cheer as one of their best-known game-day chants.", sourceId:"alabama-rammer-jammer" }),
  q({ id:"cfb-r1-paul-bunyan-axe", league:"cfb", round:"round1", category:"Rivalry Trophies", prompt:"Paul Bunyan's Axe is awarded to the winner of Wisconsin versus which rival?", choices:["Minnesota","Iowa","Michigan State","Nebraska"], answer:"Minnesota", explanation:"Wisconsin and Minnesota play for Paul Bunyan's Axe in one of the sport's oldest rivalries.", sourceId:"paul-bunyans-axe" }),
  q({ id:"cfb-r1-stanford-axe", league:"cfb", round:"round1", category:"Rivalry Trophies", prompt:"The Stanford Axe is contested in 'The Big Game' between Stanford and which school?", choices:["California","USC","UCLA","Oregon"], answer:"California", explanation:"Stanford and Cal play The Big Game for possession of the Stanford Axe.", sourceId:"stanford-axe" }),
  q({ id:"cfb-r1-territorial-cup", league:"cfb", round:"round1", category:"Rivalry Trophies", prompt:"The Territorial Cup is played between Arizona and which rival?", choices:["Arizona State","New Mexico","Utah","Colorado"], answer:"Arizona State", explanation:"Arizona and Arizona State play for the Territorial Cup.", sourceId:"territorial-cup" }),

  // Round 2 — iconic games and deeper award lore
  q({ id:"cfb-r2-choke-at-doak", league:"cfb", round:"round2", category:"Iconic Games", prompt:"The 1994 game nicknamed the 'Choke at Doak' featured Florida State's huge comeback against which rival?", choices:["Florida","Miami","Clemson","Notre Dame"], answer:"Florida", explanation:"Florida State rallied from 31–3 down in the fourth quarter to tie Florida 31–31.", sourceId:"choke-at-doak" }),
  q({ id:"cfb-r2-earthquake-game", league:"cfb", round:"round2", category:"Iconic Games", prompt:"The 1988 'Earthquake Game' at LSU came against which opponent?", choices:["Auburn","Alabama","Florida","Georgia"], answer:"Auburn", explanation:"The crowd reaction to LSU's late winning touchdown against Auburn registered on a campus seismograph.", sourceId:"lsu-earthquake-game" }),
  q({ id:"cfb-r2-punt-bama-punt", league:"cfb", round:"round2", category:"Rivalry Moments", prompt:"The famous 1972 'Punt Bama Punt' comeback belongs to which Alabama rival?", choices:["Auburn","Tennessee","LSU","Georgia"], answer:"Auburn", explanation:"Auburn blocked two Alabama punts in the fourth quarter and returned both for touchdowns.", sourceId:"punt-bama-punt" }),
  q({ id:"cfb-r2-game-century-1971", league:"cfb", round:"round2", category:"Historic Games", prompt:"The 1971 'Game of the Century' on Thanksgiving matched Nebraska against which team?", choices:["Oklahoma","Texas","Alabama","Notre Dame"], answer:"Oklahoma", explanation:"No. 1 Nebraska beat No. 2 Oklahoma 35–31 in Norman.", sourceId:"nebraska-oklahoma-1971" }),
  q({ id:"cfb-r2-wide-right-rival", league:"cfb", round:"round2", category:"Rivalry Moments", prompt:"Florida State's famous series of 'Wide Right' heartbreaks came against which rival?", choices:["Miami","Florida","Clemson","Notre Dame"], answer:"Miami", explanation:"Several Florida State-Miami classics turned on missed field goals wide right.", sourceId:"fsu-miami-wide-right" }),
  q({ id:"cfb-r2-woody-hayes-punch", league:"cfb", round:"round2", category:"Infamous Moments", prompt:"Woody Hayes' Ohio State career ended after he struck a player from which school during the 1978 Gator Bowl?", choices:["Clemson","Michigan","Alabama","Georgia"], answer:"Clemson", explanation:"Hayes punched Clemson linebacker Charlie Bauman after an interception.", sourceId:"woody-hayes-1978" }),
  q({ id:"cfb-r2-paul-hornung-losing-team", league:"cfb", round:"round2", category:"Heisman Oddities", prompt:"Which Notre Dame star remains the only Heisman winner whose team had a losing record?", choices:["Paul Hornung","Tim Brown","John Huarte","Leon Hart"], answer:"Paul Hornung", explanation:"Hornung won the 1956 Heisman even though Notre Dame finished 2–8.", sourceId:"heisman-milestones", sourceUrl:HEISMAN }),
  q({ id:"cfb-r2-ernie-davis-first", league:"cfb", round:"round2", category:"Heisman History", prompt:"Who became the first African-American player to win the Heisman Trophy?", choices:["Ernie Davis","Jim Brown","Mike Garrett","O.J. Simpson"], answer:"Ernie Davis", explanation:"Syracuse running back Ernie Davis won the Heisman in 1961.", sourceId:"heisman-milestones", sourceUrl:HEISMAN }),
  q({ id:"cfb-r2-terry-baker-final-four", league:"cfb", round:"round2", category:"Heisman Oddities", prompt:"Which Heisman winner is also the only winner to have played in an NCAA basketball Final Four?", choices:["Terry Baker","Bo Jackson","Charlie Ward","Vic Janowicz"], answer:"Terry Baker", explanation:"Oregon State quarterback Terry Baker won the 1962 Heisman and played in the 1963 Final Four.", sourceId:"heisman-milestones", sourceUrl:HEISMAN }),
  q({ id:"cfb-r2-doc-blanchard-first-junior", league:"cfb", round:"round2", category:"Heisman History", prompt:"Which Army star became the first junior to win the Heisman?", choices:["Doc Blanchard","Glenn Davis","Pete Dawkins","Felix Jones"], answer:"Doc Blanchard", explanation:"Army fullback Doc Blanchard became the first junior Heisman winner in 1945.", sourceId:"heisman-milestones", sourceUrl:HEISMAN }),
  q({ id:"cfb-r2-last-ivy-heisman", league:"cfb", round:"round2", category:"Heisman History", prompt:"Who is the most recent Ivy League player to win the Heisman Trophy?", choices:["Dick Kazmaier","Clint Frank","Larry Kelley","Ed Marinaro"], answer:"Dick Kazmaier", explanation:"Princeton's Dick Kazmaier won in 1951 and remains the most recent Ivy League Heisman winner.", sourceId:"heisman-milestones", sourceUrl:HEISMAN }),
  q({ id:"cfb-r2-first-west-coast-heisman", league:"cfb", round:"round2", category:"Heisman History", prompt:"Which Oregon State quarterback became the first West Coast Heisman winner?", choices:["Terry Baker","Gary Beban","Jim Plunkett","Marcus Allen"], answer:"Terry Baker", explanation:"Terry Baker won the 1962 Heisman for Oregon State.", sourceId:"heisman-milestones", sourceUrl:HEISMAN }),
  q({ id:"cfb-r2-flutie-breaks-rb-streak", league:"cfb", round:"round2", category:"Heisman History", prompt:"Doug Flutie's 1984 Heisman ended a streak of how many straight running back winners?", choices:["11","7","9","13"], answer:"11", explanation:"Flutie became the first quarterback since 1971 to win after 11 consecutive running back winners.", sourceId:"heisman-milestones", sourceUrl:HEISMAN }),
  q({ id:"cfb-r2-2007-lsu-two-loss", league:"cfb", round:"round2", category:"Championship Oddities", prompt:"Which team became the first two-loss champion of the BCS era?", choices:["LSU","Florida","Ohio State","USC"], answer:"LSU", explanation:"LSU lost twice in triple overtime during the 2007 regular season but still won the BCS championship.", sourceId:"ncaa-championship-history", sourceUrl:NCAA_CHAMPS }),
  q({ id:"cfb-r2-2004-auburn-left-out", league:"cfb", round:"round2", category:"BCS Controversies", prompt:"Which SEC team finished 13–0 in 2004 but was left out of the BCS title game?", choices:["Auburn","Georgia","LSU","Tennessee"], answer:"Auburn", explanation:"Undefeated Auburn finished behind USC and Oklahoma in the BCS standings.", sourceId:"2004-auburn-bcs" }),

  // Round 3 — deeper history and oddities
  q({ id:"cfb-r3-heisman-first-live-tv", league:"cfb", round:"round3", category:"Broadcast History", prompt:"Which USC star became the first Heisman winner whose announcement was broadcast live on television?", choices:["Marcus Allen","Charles White","O.J. Simpson","Mike Garrett"], answer:"Marcus Allen", explanation:"Marcus Allen's 1981 Heisman announcement was the first broadcast live on television.", sourceId:"heisman-milestones", sourceUrl:HEISMAN }),
  q({ id:"cfb-r3-first-heisman-finalists", league:"cfb", round:"round3", category:"Heisman History", prompt:"The first group of invited Heisman finalists in 1982 included Herschel Walker, Eric Dickerson and which quarterback?", choices:["John Elway","Dan Marino","Jim McMahon","Tony Eason"], answer:"John Elway", explanation:"Walker, Elway and Dickerson were the first invited finalists for the televised 1982 ceremony.", sourceId:"heisman-milestones", sourceUrl:HEISMAN }),
  q({ id:"cfb-r3-kinnick-death", league:"cfb", round:"round3", category:"Heisman History", prompt:"Which 1939 Heisman winner died in a military plane crash during World War II?", choices:["Nile Kinnick","Tom Harmon","Davey O'Brien","Bruce Smith"], answer:"Nile Kinnick", explanation:"Iowa legend Nile Kinnick died in a training accident in 1943.", sourceId:"heisman-milestones", sourceUrl:HEISMAN }),
  q({ id:"cfb-r3-heisman-trust-born", league:"cfb", round:"round3", category:"Award History", prompt:"The charitable Heisman Trophy Trust was created in which year?", choices:["2006","1996","2010","2001"], answer:"2006", explanation:"The Heisman Trust formed after the Downtown Athletic Club closed following the September 11 attacks.", sourceId:"heisman-milestones", sourceUrl:HEISMAN }),
  q({ id:"cfb-r3-heisman-online-only", league:"cfb", round:"round3", category:"Award History", prompt:"By which year were all Heisman ballots required to be submitted online?", choices:["2009","2005","2012","2015"], answer:"2009", explanation:"The award shifted increasingly online beginning in 2007, with all ballots required online by 2009.", sourceId:"heisman-milestones", sourceUrl:HEISMAN }),
  q({ id:"cfb-r3-first-three-soph-heisman", league:"cfb", round:"round3", category:"Heisman History", prompt:"Tim Tebow began a run of three straight sophomore Heisman winners. Who followed him immediately?", choices:["Sam Bradford","Mark Ingram","Johnny Manziel","Cam Newton"], answer:"Sam Bradford", explanation:"Tebow won in 2007, Oklahoma's Sam Bradford in 2008 and Alabama's Mark Ingram in 2009.", sourceId:"heisman-milestones", sourceUrl:HEISMAN }),
  q({ id:"cfb-r3-2009-fiesta-undefeated", league:"cfb", round:"round3", category:"Bowl Oddities", prompt:"The Fiesta Bowl after the 2009 season matched which two undefeated non-BCS automatic-qualifier teams?", choices:["Boise State and TCU","Utah and Boise State","TCU and Cincinnati","Boise State and Hawaii"], answer:"Boise State and TCU", explanation:"The 2010 Fiesta Bowl paired unbeaten Boise State and TCU.", sourceId:"2009-fiesta-bowl" }),
  q({ id:"cfb-r3-2008-utah-sugar", league:"cfb", round:"round3", category:"Bowl Upsets", prompt:"Which undefeated team beat Alabama in the Sugar Bowl after the 2008 season?", choices:["Utah","Boise State","TCU","Hawaii"], answer:"Utah", explanation:"Utah finished 13–0 after beating Alabama 31–17 in the Sugar Bowl.", sourceId:"2008-utah" }),
  q({ id:"cfb-r3-last-bcs-champ", league:"cfb", round:"round3", category:"Championship History", prompt:"Which program won the final BCS National Championship before the playoff era?", choices:["Florida State","Auburn","Alabama","Ohio State"], answer:"Florida State", explanation:"Florida State beat Auburn to win the 2013 season championship, the final title of the BCS era.", sourceId:"ncaa-championship-history", sourceUrl:NCAA_CHAMPS }),
  q({ id:"cfb-r3-first-bcs-loser", league:"cfb", round:"round3", category:"Championship History", prompt:"Tennessee won the first BCS title game by beating which team?", choices:["Florida State","Nebraska","Miami","Virginia Tech"], answer:"Florida State", explanation:"Tennessee defeated Florida State 23–16 in the Fiesta Bowl after the 1998 season.", sourceId:"ncaa-championship-history", sourceUrl:NCAA_CHAMPS }),
  q({ id:"cfb-r3-2021-georgia-drought", league:"cfb", round:"round3", category:"Championship History", prompt:"Georgia's 2021 national title ended a championship drought dating to which season?", choices:["1980","1976","1984","1990"], answer:"1980", explanation:"Georgia's previous consensus national championship came with the 1980 team.", sourceId:"georgia-championship-history" }),
  q({ id:"cfb-r3-2010-auburn-heisman", league:"cfb", round:"round3", category:"Championship Stars", prompt:"Which Heisman-winning quarterback led Auburn to the 2010 national championship?", choices:["Cam Newton","Nick Marshall","Jason Campbell","Pat Sullivan"], answer:"Cam Newton", explanation:"Cam Newton won the Heisman and led Auburn to a 14–0 championship season.", sourceId:"auburn-2010" }),
  q({ id:"cfb-r3-2001-miami-qb", league:"cfb", round:"round3", category:"Championship Stars", prompt:"Who quarterbacked Miami's loaded 2001 national championship team?", choices:["Ken Dorsey","Brock Berlin","Craig Erickson","Steve Walsh"], answer:"Ken Dorsey", explanation:"Ken Dorsey quarterbacked the undefeated 2001 Hurricanes.", sourceId:"miami-2001" }),
  q({ id:"cfb-r3-2000-oklahoma-coach", league:"cfb", round:"round3", category:"Coaches", prompt:"Who coached Oklahoma to the 2000 national championship?", choices:["Bob Stoops","Barry Switzer","Lincoln Riley","Gary Gibbs"], answer:"Bob Stoops", explanation:"Bob Stoops won the national title in his second season at Oklahoma.", sourceId:"oklahoma-2000" }),
  q({ id:"cfb-r3-2001-miami-coach", league:"cfb", round:"round3", category:"Coaches", prompt:"Which coach won a national championship in his first season as a college head coach with Miami in 2001?", choices:["Larry Coker","Butch Davis","Dennis Erickson","Jimmy Johnson"], answer:"Larry Coker", explanation:"Larry Coker took over Miami in 2001 and led the Hurricanes to an undefeated national title.", sourceId:"miami-2001" }),

  // Last Call
  q({ id:"cfb-final-hornung-team-record", league:"cfb", round:"last-call", category:"Heisman Oddities", prompt:"What was Notre Dame's record when Paul Hornung won the 1956 Heisman?", choices:["2–8","4–6","5–5","3–7"], answer:"2–8", explanation:"Hornung remains the only Heisman winner from a losing team; Notre Dame finished 2–8.", sourceId:"heisman-milestones", sourceUrl:HEISMAN }),
  q({ id:"cfb-final-terry-baker-sport", league:"cfb", round:"last-call", category:"Heisman Oddities", prompt:"Besides football, Terry Baker reached the NCAA Final Four in which sport?", choices:["Basketball","Baseball","Track and field","Wrestling"], answer:"Basketball", explanation:"Baker played guard on Oregon State's 1963 Final Four basketball team.", sourceId:"heisman-milestones", sourceUrl:HEISMAN }),
  q({ id:"cfb-final-first-finalists-year", league:"cfb", round:"last-call", category:"Heisman History", prompt:"In what year were Heisman finalists first invited to New York for a live televised ceremony?", choices:["1982","1977","1985","1990"], answer:"1982", explanation:"Herschel Walker, John Elway and Eric Dickerson formed the first invited finalist group.", sourceId:"heisman-milestones", sourceUrl:HEISMAN }),
  q({ id:"cfb-final-1971-game-century-score", league:"cfb", round:"last-call", category:"Historic Games", prompt:"What was the final score of Nebraska's 1971 Game of the Century win over Oklahoma?", choices:["35–31","31–28","38–35","24–21"], answer:"35–31", explanation:"No. 1 Nebraska beat No. 2 Oklahoma 35–31 on Thanksgiving Day.", sourceId:"nebraska-oklahoma-1971" }),
  q({ id:"cfb-final-choke-at-doak-score", league:"cfb", round:"last-call", category:"Iconic Games", prompt:"What was the final score of the 1994 Florida-Florida State game nicknamed the 'Choke at Doak'?", choices:["31–31","28–28","31–30 Florida State","34–31 Florida"], answer:"31–31", explanation:"Florida State erased a 31–3 fourth-quarter deficit and forced a 31–31 tie.", sourceId:"choke-at-doak" }),
];
