import { barTriviaQuestion, type BarTriviaQuestion } from "../games/barTriviaEngine";

const FIRSTS = "https://www.profootballhof.com/news/football-firsts";
const NFL100 = "https://www.nfl.com/100/greatest-moment/all-32.html";
const PFHOF = "https://www.profootballhof.com";

function q(seed: Parameters<typeof barTriviaQuestion>[0]) {
  return barTriviaQuestion({ ...seed, verifiedAt: "2026-09-28" });
}

export const BAR_TRIVIA_NFL_EVERGREEN_WAVE_4: readonly BarTriviaQuestion[] = [
  // Round 1 — fan culture and phrases
  q({ id:"nfl-r1-bills-mafia", league:"nfl", round:"round1", category:"Fan Culture", prompt:"'Bills Mafia' is the fan identity of which NFL team?", choices:["Buffalo Bills","Baltimore Ravens","Cleveland Browns","Detroit Lions"], answer:"Buffalo Bills", explanation:"Buffalo's famously passionate fan base is widely known as Bills Mafia.", sourceId:"bills-fan-culture" }),
  q({ id:"nfl-r1-who-dat", league:"nfl", round:"round1", category:"Cheers", prompt:"The chant 'Who Dat?' is most closely associated with which franchise?", choices:["New Orleans Saints","Cincinnati Bengals","Atlanta Falcons","Tampa Bay Buccaneers"], answer:"New Orleans Saints", explanation:"Saints fans have made 'Who Dat?' one of the NFL's most recognizable chants.", sourceId:"saints-who-dat" }),
  q({ id:"nfl-r1-who-dey", league:"nfl", round:"round1", category:"Cheers", prompt:"The chant 'Who Dey?' belongs to fans of which team?", choices:["Cincinnati Bengals","New Orleans Saints","Cleveland Browns","Pittsburgh Steelers"], answer:"Cincinnati Bengals", explanation:"Bengals fans use the 'Who Dey' chant on game days.", sourceId:"bengals-who-dey" }),
  q({ id:"nfl-r1-cheeseheads", league:"nfl", round:"round1", category:"Fan Culture", prompt:"Fans wearing foam cheese wedges are supporting which team?", choices:["Green Bay Packers","Minnesota Vikings","Chicago Bears","Detroit Lions"], answer:"Green Bay Packers", explanation:"Packers fans embraced the Cheesehead identity and foam cheese hats.", sourceId:"packers-cheeseheads" }),
  q({ id:"nfl-r1-skol", league:"nfl", round:"round1", category:"Cheers", prompt:"The 'Skol' chant is associated with which franchise?", choices:["Minnesota Vikings","Green Bay Packers","Seattle Seahawks","Buffalo Bills"], answer:"Minnesota Vikings", explanation:"Vikings fans use the rhythmic Skol chant and clap at home games.", sourceId:"vikings-skol" }),
  q({ id:"nfl-r1-fly-eagles-fly", league:"nfl", round:"round1", category:"Fight Songs", prompt:"'Fly, Eagles Fly' is the fight song of which team?", choices:["Philadelphia Eagles","Atlanta Falcons","Seattle Seahawks","Baltimore Ravens"], answer:"Philadelphia Eagles", explanation:"Philadelphia fans sing 'Fly, Eagles Fly' after Eagles scores and wins.", sourceId:"eagles-fight-song" }),
  q({ id:"nfl-r1-bear-down", league:"nfl", round:"round1", category:"Fight Songs", prompt:"'Bear Down, Chicago Bears' belongs to which franchise?", choices:["Chicago Bears","Cleveland Browns","Detroit Lions","Green Bay Packers"], answer:"Chicago Bears", explanation:"The Bears' fight song begins with the words 'Bear Down, Chicago Bears.'", sourceId:"bears-fight-song" }),
  q({ id:"nfl-r1-keep-pounding", league:"nfl", round:"round1", category:"Team Mottos", prompt:"'Keep Pounding' is the rallying cry of which franchise?", choices:["Carolina Panthers","Jacksonville Jaguars","Atlanta Falcons","Tennessee Titans"], answer:"Carolina Panthers", explanation:"The phrase was inspired by former Panthers player and coach Sam Mills.", sourceId:"panthers-keep-pounding" }),
  q({ id:"nfl-r1-rise-up", league:"nfl", round:"round1", category:"Team Mottos", prompt:"'Rise Up' is a long-running rallying cry for which team?", choices:["Atlanta Falcons","Arizona Cardinals","Philadelphia Eagles","Tampa Bay Buccaneers"], answer:"Atlanta Falcons", explanation:"Atlanta has used 'Rise Up' prominently in team and fan culture.", sourceId:"falcons-rise-up" }),
  q({ id:"nfl-r1-titan-up", league:"nfl", round:"round1", category:"Team Mottos", prompt:"'Titan Up' is the rallying phrase of which franchise?", choices:["Tennessee Titans","New York Giants","Los Angeles Chargers","Houston Texans"], answer:"Tennessee Titans", explanation:"Titans fans and the franchise use 'Titan Up' as a game-day rallying phrase.", sourceId:"titans-titan-up" }),
  q({ id:"nfl-r1-raider-nation", league:"nfl", round:"round1", category:"Fan Culture", prompt:"'Raider Nation' refers to the fan base of which franchise?", choices:["Raiders","Steelers","Ravens","Cowboys"], answer:"Raiders", explanation:"The Raiders' nationwide fan following is commonly called Raider Nation.", sourceId:"raiders-fan-culture" }),
  q({ id:"nfl-r1-gang-green", league:"nfl", round:"round1", category:"Team Nicknames", prompt:"Which New York team is often nicknamed 'Gang Green'?", choices:["Jets","Giants","Bills","Eagles"], answer:"Jets", explanation:"Gang Green has long been used as a nickname for the New York Jets.", sourceId:"jets-nickname" }),
  q({ id:"nfl-r1-big-blue", league:"nfl", round:"round1", category:"Team Nicknames", prompt:"Which franchise is commonly called 'Big Blue'?", choices:["New York Giants","Detroit Lions","Buffalo Bills","Indianapolis Colts"], answer:"New York Giants", explanation:"The Giants are frequently referred to as Big Blue.", sourceId:"giants-nickname" }),
  q({ id:"nfl-r1-12s-seattle", league:"nfl", round:"round1", category:"Fan Culture", prompt:"The '12s' are the famously loud fans of which team?", choices:["Seattle Seahawks","Dallas Cowboys","Kansas City Chiefs","Las Vegas Raiders"], answer:"Seattle Seahawks", explanation:"Seattle honors its fan base as the 12s, reflecting the impact of the '12th man.'", sourceId:"seahawks-12s" }),
  q({ id:"nfl-r1-duke-football", league:"nfl", round:"round1", category:"League Traditions", prompt:"The official NFL game ball is commonly nicknamed 'The Duke.'", choices:["True — after Wellington Mara","True — after Duke Ellington","False — it is called The Shield","False — it is called The Gridiron"], answer:"True — after Wellington Mara", explanation:"The NFL game ball carries 'The Duke' nickname in honor of longtime Giants owner Wellington Mara.", sourceId:"nfl-duke-football" }),

  // Round 2 — quotes, media and Super Bowl culture
  q({ id:"nfl-r2-playoffs-mora", league:"nfl", round:"round2", category:"Famous Quotes", prompt:"Which coach delivered the famous press-conference line, 'Playoffs? Don't talk about playoffs'?", choices:["Jim Mora","Dennis Green","Herm Edwards","Mike Ditka"], answer:"Jim Mora", explanation:"Colts coach Jim Mora's incredulous 'Playoffs?' response became one of the NFL's most replayed press-conference clips.", sourceId:"nfl-famous-quotes" }),
  q({ id:"nfl-r2-who-thought-they-were", league:"nfl", round:"round2", category:"Famous Quotes", prompt:"Which coach famously said, 'They are who we thought they were'?", choices:["Dennis Green","Jim Mora","Mike Singletary","Rex Ryan"], answer:"Dennis Green", explanation:"Cardinals coach Dennis Green delivered the line after a 2006 loss to Chicago.", sourceId:"nfl-famous-quotes" }),
  q({ id:"nfl-r2-play-to-win", league:"nfl", round:"round2", category:"Famous Quotes", prompt:"Which coach declared, 'You play to win the game'?", choices:["Herm Edwards","Tony Dungy","Bill Cowher","Marty Schottenheimer"], answer:"Herm Edwards", explanation:"Jets coach Herm Edwards delivered the famous line during a 2002 press conference.", sourceId:"nfl-famous-quotes" }),
  q({ id:"nfl-r2-we-want-ball", league:"nfl", round:"round2", category:"Famous Quotes", prompt:"Which quarterback said, 'We want the ball and we're gonna score' before an overtime playoff possession?", choices:["Matt Hasselbeck","Brett Favre","Donovan McNabb","Jake Delhomme"], answer:"Matt Hasselbeck", explanation:"Seattle quarterback Matt Hasselbeck said it after winning the coin toss before throwing a game-ending interception to Green Bay.", sourceId:"seahawks-packers-2003" }),
  q({ id:"nfl-r2-wont-get-fined", league:"nfl", round:"round2", category:"Famous Quotes", prompt:"Who repeatedly told reporters, 'I'm just here so I won't get fined' during Super Bowl week?", choices:["Marshawn Lynch","Richard Sherman","Terrell Owens","Chad Johnson"], answer:"Marshawn Lynch", explanation:"Marshawn Lynch turned the phrase into a Super Bowl XLIX media-week catchphrase.", sourceId:"lynch-super-bowl-media" }),
  q({ id:"nfl-r2-do-your-job", league:"nfl", round:"round2", category:"Team Mottos", prompt:"The phrase 'Do Your Job' became closely associated with which coaching dynasty?", choices:["Bill Belichick's Patriots","Andy Reid's Chiefs","Mike Tomlin's Steelers","Pete Carroll's Seahawks"], answer:"Bill Belichick's Patriots", explanation:"New England used 'Do Your Job' as a core slogan during the Belichick era.", sourceId:"patriots-do-your-job" }),
  q({ id:"nfl-r2-autumn-wind", league:"nfl", round:"round2", category:"Team Culture", prompt:"'The Autumn Wind' is an iconic spoken-word anthem associated with which franchise?", choices:["Raiders","Steelers","Packers","Cowboys"], answer:"Raiders", explanation:"NFL Films' 'The Autumn Wind' became inseparable from Raiders identity.", sourceId:"raiders-autumn-wind" }),
  q({ id:"nfl-r2-prince-halftime", league:"nfl", round:"round2", category:"Super Bowl Halftime", prompt:"Which artist famously performed 'Purple Rain' during an actual rainstorm at Super Bowl XLI?", choices:["Prince","Bruce Springsteen","U2","Stevie Wonder"], answer:"Prince", explanation:"Prince's rain-soaked Miami halftime show is widely remembered as one of the greatest Super Bowl performances.", sourceId:"super-bowl-halftime-prince" }),
  q({ id:"nfl-r2-left-shark", league:"nfl", round:"round2", category:"Super Bowl Halftime", prompt:"The viral 'Left Shark' dancer appeared during whose Super Bowl halftime show?", choices:["Katy Perry","Lady Gaga","Beyonce","Madonna"], answer:"Katy Perry", explanation:"A dancing shark character became an internet sensation during Katy Perry's Super Bowl XLIX halftime show.", sourceId:"super-bowl-left-shark" }),
  q({ id:"nfl-r2-wardrobe-malfunction", league:"nfl", round:"round2", category:"Super Bowl Halftime", prompt:"The phrase 'wardrobe malfunction' entered pop culture after a Super Bowl halftime show involving Janet Jackson and whom?", choices:["Justin Timberlake","Usher","Nelly","P. Diddy"], answer:"Justin Timberlake", explanation:"The controversial moment occurred during the Super Bowl XXXVIII halftime show.", sourceId:"super-bowl-xxxviii-halftime" }),
  q({ id:"nfl-r2-whitney-anthem", league:"nfl", round:"round2", category:"Super Bowl Music", prompt:"Whose rendition of the national anthem before Super Bowl XXV became one of the game's most famous musical moments?", choices:["Whitney Houston","Mariah Carey","Celine Dion","Aretha Franklin"], answer:"Whitney Houston", explanation:"Whitney Houston's 1991 anthem performance became an iconic Super Bowl recording.", sourceId:"super-bowl-xxv-anthem" }),
  q({ id:"nfl-r2-wide-right-norwood", league:"nfl", round:"round2", category:"Super Bowl Moments", prompt:"Which Bills kicker became linked forever to the phrase 'Wide Right' after Super Bowl XXV?", choices:["Scott Norwood","Steve Christie","Pete Gogolak","Nick Mike-Mayer"], answer:"Scott Norwood", explanation:"Norwood's potential game-winning 47-yard field goal sailed wide right against the Giants.", sourceId:"super-bowl-xxv" }),
  q({ id:"nfl-r2-sb1-two-networks", league:"nfl", round:"round2", category:"Broadcast History", prompt:"What was unusual about the television broadcast of Super Bowl I?", choices:["CBS and NBC both televised it","It aired only on tape delay","It was the first color TV broadcast","It had no commercials"], answer:"CBS and NBC both televised it", explanation:"Because CBS held NFL rights and NBC held AFL rights, both networks simulcast the first Super Bowl.", sourceId:"super-bowl-i-broadcast" }),
  q({ id:"nfl-r2-madden-turkey-leg", league:"nfl", round:"round2", category:"Broadcast Traditions", prompt:"Which broadcaster became famous for handing out turkey legs to standout players on Thanksgiving?", choices:["John Madden","Pat Summerall","Al Michaels","Frank Gifford"], answer:"John Madden", explanation:"Madden helped turn turkey legs and later the turducken into Thanksgiving football traditions.", sourceId:"madden-thanksgiving" }),
  q({ id:"nfl-r2-yellow-line", league:"nfl", round:"round2", category:"Broadcast Innovation", prompt:"The virtual yellow line on football broadcasts represents what?", choices:["The line to gain for a first down","The line of scrimmage","The edge of field-goal range","The neutral zone"], answer:"The line to gain for a first down", explanation:"The yellow first-down line became one of football television's most useful graphics.", sourceId:"broadcast-first-down-line" }),

  // Round 3 — rules and deeper Super Bowl firsts
  q({ id:"nfl-r3-two-point-added", league:"nfl", round:"round3", category:"Rules History", prompt:"The NFL added the two-point conversion in which season?", choices:["1994","1984","1990","1999"], answer:"1994", explanation:"NFL teams gained the option to attempt a two-point conversion beginning in 1994.", sourceId:"nfl-rules-history" }),
  q({ id:"nfl-r3-first-two-point", league:"nfl", round:"round3", category:"Rules History", prompt:"Who scored the first two-point conversion in NFL history after the rule was adopted in 1994?", choices:["Tom Tupa","Steve Young","Randall Cunningham","Kordell Stewart"], answer:"Tom Tupa", explanation:"Cleveland quarterback and punter Tom Tupa ran in the league's first two-point conversion.", sourceId:"nfl-two-point-history" }),
  q({ id:"nfl-r3-goalposts-moved", league:"nfl", round:"round3", category:"Rules History", prompt:"In 1974, NFL goalposts were moved from the goal line to where?", choices:["The end line","The back of the sideline","Five yards behind the end zone","The 1-yard line"], answer:"The end line", explanation:"The 1974 rules changes moved goalposts to the end line, making field goals longer and the end zone safer.", sourceId:"nfl-rules-history" }),
  q({ id:"nfl-r3-regular-season-ot", league:"nfl", round:"round3", category:"Rules History", prompt:"The NFL introduced regular-season sudden-death overtime in which decade?", choices:["1970s","1960s","1980s","1990s"], answer:"1970s", explanation:"Regular-season overtime was introduced in 1974.", sourceId:"nfl-rules-history" }),
  q({ id:"nfl-r3-replay-returned", league:"nfl", round:"round3", category:"Rules History", prompt:"After an earlier experiment ended, the modern challenge-based instant replay system returned in which year?", choices:["1999","1994","2002","1989"], answer:"1999", explanation:"The NFL reinstated instant replay in 1999 with a coach-challenge structure.", sourceId:"nfl-replay-history" }),
  q({ id:"nfl-r3-extra-point-back", league:"nfl", round:"round3", category:"Rules History", prompt:"In 2015, the NFL moved extra-point kicks back so the snap came from which yard line?", choices:["15-yard line","10-yard line","20-yard line","12-yard line"], answer:"15-yard line", explanation:"The change made the standard extra point roughly a 33-yard kick.", sourceId:"nfl-extra-point-rule" }),
  q({ id:"nfl-r3-first-1000-rusher", league:"nfl", round:"round3", category:"Football Firsts", prompt:"Who became the first NFL player to rush for 1,000 yards in a season?", choices:["Beattie Feathers","Steve Van Buren","Jim Brown","Bronko Nagurski"], answer:"Beattie Feathers", explanation:"Chicago Bears rookie Beattie Feathers rushed for 1,004 yards in 1934, becoming the NFL's first 1,000-yard rusher.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r3-first-tv-network", league:"nfl", round:"round3", category:"Broadcast History", prompt:"Which network televised the first NFL game ever shown on television?", choices:["NBC","CBS","ABC","DuMont"], answer:"NBC", explanation:"NBC televised the Eagles-Brooklyn Dodgers game from Ebbets Field on Oct. 22, 1939.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r3-first-cold-weather-outdoor-sb", league:"nfl", round:"round3", category:"Super Bowl Venues", prompt:"Super Bowl XLVIII was the first Super Bowl played outdoors in a cold-weather market. Which stadium hosted Seattle vs. Denver?", choices:["MetLife Stadium","Giants Stadium","Soldier Field","Gillette Stadium"], answer:"MetLife Stadium", explanation:"Seattle and Denver played at MetLife Stadium in New Jersey in February 2014.", sourceId:"super-bowl-xlviii" }),
  q({ id:"nfl-r3-first-all-games-televised", league:"nfl", round:"round3", category:"Broadcast History", prompt:"Which franchise became the first NFL team to televise all of its games, home and away?", choices:["Los Angeles Rams","New York Giants","Cleveland Browns","Chicago Bears"], answer:"Los Angeles Rams", explanation:"The Los Angeles Rams televised their entire home-and-away schedule during the 1950 season.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r3-sb-li-ot-scorer", league:"nfl", round:"round3", category:"Super Bowl Moments", prompt:"Who scored the walk-off touchdown that ended the first overtime Super Bowl?", choices:["James White","Tom Brady","Julian Edelman","LeGarrette Blount"], answer:"James White", explanation:"James White's rushing touchdown completed New England's comeback against Atlanta in Super Bowl LI.", sourceId:"super-bowl-li" }),
  q({ id:"nfl-r3-sb-i-attendance", league:"nfl", round:"round3", category:"Super Bowl Oddities", prompt:"Which statement about Super Bowl I is true?", choices:["It remains the only Super Bowl that did not sell out","It was played indoors","It went to overtime","It was played in Miami"], answer:"It remains the only Super Bowl that did not sell out", explanation:"The Los Angeles Coliseum had thousands of empty seats for the first AFL-NFL championship game.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r3-first-50-pass-td", league:"nfl", round:"round3", category:"Iconic Records", prompt:"Who became the first NFL quarterback to throw 50 touchdown passes in a season?", choices:["Tom Brady","Peyton Manning","Dan Marino","Drew Brees"], answer:"Tom Brady", explanation:"Brady threw 50 touchdown passes during New England's 16–0 regular season in 2007.", sourceId:"nfl-records-history" }),
  q({ id:"nfl-r3-first-defensive-mvp", league:"nfl", round:"round3", category:"NFL Awards", prompt:"Who became the first defensive player to win the AP NFL MVP award?", choices:["Alan Page","Lawrence Taylor","Ray Lewis","Mean Joe Greene"], answer:"Alan Page", explanation:"Vikings defensive tackle Alan Page won AP MVP in 1971.", sourceId:"nfl-awards-history" }),
  q({ id:"nfl-r3-first-super-bowl-two-teams-qb", league:"nfl", round:"round3", category:"Super Bowl Firsts", prompt:"Who became the first quarterback to start a Super Bowl for two different franchises?", choices:["Craig Morton","Peyton Manning","Kurt Warner","Tom Brady"], answer:"Craig Morton", explanation:"Morton started Super Bowl V for Dallas and later Super Bowl XII for Denver.", sourceId:"super-bowl-qb-history" }),

  // Last Call
  q({ id:"nfl-final-triple-crown-baugh", league:"nfl", round:"last-call", category:"NFL Oddities", prompt:"Which Hall of Famer once led the NFL in passing, punting and interceptions in the same season?", choices:["Sammy Baugh","Sid Luckman","Don Hutson","Otto Graham"], answer:"Sammy Baugh", explanation:"Sammy Baugh led the NFL in passing, punting and defensive interceptions in 1943, a unique 'Triple Crown.'", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-final-the-duke-namesake", league:"nfl", round:"last-call", category:"League Traditions", prompt:"The NFL game ball nickname 'The Duke' honors which longtime owner?", choices:["Wellington Mara","Lamar Hunt","George Halas","Art Rooney"], answer:"Wellington Mara", explanation:"Mara was nicknamed The Duke, and the league's official football carries that name.", sourceId:"nfl-duke-football" }),
  q({ id:"nfl-final-first-tv-stadium", league:"nfl", round:"last-call", category:"Broadcast History", prompt:"Which famous baseball stadium hosted the first NFL game ever televised?", choices:["Ebbets Field","Yankee Stadium","Polo Grounds","Wrigley Field"], answer:"Ebbets Field", explanation:"NBC's first NFL telecast in 1939 showed the Philadelphia Eagles playing the Brooklyn Dodgers at Ebbets Field.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-final-first-national-thanksgiving-tv", league:"nfl", round:"last-call", category:"Broadcast Traditions", prompt:"Which team won the first nationally televised NFL Thanksgiving game in 1956?", choices:["Green Bay Packers","Detroit Lions","Chicago Bears","New York Giants"], answer:"Green Bay Packers", explanation:"Green Bay beat Detroit 24–20 in the first Thanksgiving Day NFL game televised nationally.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-final-first-cold-weather-sb-venue", league:"nfl", round:"last-call", category:"Super Bowl Venues", prompt:"Which stadium hosted the first outdoor Super Bowl in a cold-weather market?", choices:["MetLife Stadium","Soldier Field","Gillette Stadium","Lincoln Financial Field"], answer:"MetLife Stadium", explanation:"MetLife Stadium hosted Super Bowl XLVIII in East Rutherford, New Jersey.", sourceId:"super-bowl-xlviii" }),
];
