import { barTriviaQuestion, type BarTriviaQuestion } from "../games/barTriviaEngine";

const HEISMAN = "https://www.heisman.com/about-the-heisman/milestones/";
const NCAA_CHAMPS = "https://www.ncaa.com/news/football/article/college-football-national-championship-history";

function q(seed: Parameters<typeof barTriviaQuestion>[0]) {
  return barTriviaQuestion({ ...seed, verifiedAt: "2026-09-28" });
}

export const BAR_TRIVIA_CFB_EVERGREEN_WAVE_2: readonly BarTriviaQuestion[] = [
  // Round 1
  q({ id:"cfb-r1-white-out", league:"cfb", round:"round1", category:"Traditions", prompt:"The famous 'White Out' atmosphere is most closely associated with which stadium?", choices:["Beaver Stadium","Ohio Stadium","Michigan Stadium","Camp Randall Stadium"], answer:"Beaver Stadium", explanation:"Penn State's White Out turns Beaver Stadium into a sea of white for a marquee home game.", sourceId:"penn-state-white-out" }),
  q({ id:"cfb-r1-vol-navy", league:"cfb", round:"round1", category:"Traditions", prompt:"The 'Vol Navy' tradition brings fans to Tennessee home games by traveling along which river?", choices:["Tennessee River","Mississippi River","Cumberland River","Ohio River"], answer:"Tennessee River", explanation:"Fans can arrive near Neyland Stadium by boat on the Tennessee River as part of the Vol Navy tradition.", sourceId:"tennessee-vol-navy" }),
  q({ id:"cfb-r1-sandstorm", league:"cfb", round:"round1", category:"Stadium Music", prompt:"Which program's home crowd is famous for bouncing to 'Sandstorm'?", choices:["South Carolina","Virginia Tech","Wisconsin","Oregon"], answer:"South Carolina", explanation:"Darude's 'Sandstorm' has become a signature game-day song at South Carolina's Williams-Brice Stadium.", sourceId:"south-carolina-sandstorm" }),
  q({ id:"cfb-r1-tunnel-walk", league:"cfb", round:"round1", category:"Entrances", prompt:"The 'Tunnel Walk' is a signature pregame entrance for which program?", choices:["Nebraska","Oklahoma","Iowa","Texas"], answer:"Nebraska", explanation:"Nebraska's team entrance through the tunnel at Memorial Stadium is known as the Tunnel Walk.", sourceId:"nebraska-tunnel-walk" }),
  q({ id:"cfb-r1-smokey", league:"cfb", round:"round1", category:"Mascots", prompt:"Smokey, a bluetick coonhound, is the live mascot of which program?", choices:["Tennessee","Kentucky","West Virginia","North Carolina"], answer:"Tennessee", explanation:"Tennessee's live mascot Smokey is a bluetick coonhound.", sourceId:"tennessee-smokey" }),
  q({ id:"cfb-r1-mike-tiger", league:"cfb", round:"round1", category:"Mascots", prompt:"Mike the Tiger is the live mascot of which SEC school?", choices:["LSU","Auburn","Missouri","Clemson"], answer:"LSU", explanation:"LSU's live Bengal tiger mascot is named Mike.", sourceId:"lsu-mike" }),
  q({ id:"cfb-r1-reveille", league:"cfb", round:"round1", category:"Mascots", prompt:"Reveille is the live mascot of which school?", choices:["Texas A&M","Texas","Baylor","SMU"], answer:"Texas A&M", explanation:"Texas A&M's highest-ranking member of the Corps of Cadets is its collie mascot, Reveille.", sourceId:"texas-am-reveille" }),
  q({ id:"cfb-r1-brutus", league:"cfb", round:"round1", category:"Mascots", prompt:"Brutus Buckeye is the mascot of which school?", choices:["Ohio State","Ohio","Cincinnati","Miami (Ohio)"], answer:"Ohio State", explanation:"Brutus Buckeye is Ohio State's costumed mascot.", sourceId:"ohio-state-brutus" }),
  q({ id:"cfb-r1-sparty", league:"cfb", round:"round1", category:"Mascots", prompt:"Sparty is the mascot of which Big Ten program?", choices:["Michigan State","Michigan","Illinois","Purdue"], answer:"Michigan State", explanation:"Michigan State's Spartan mascot is known as Sparty.", sourceId:"michigan-state-sparty" }),
  q({ id:"cfb-r1-golden-hat", league:"cfb", round:"round1", category:"Rivalry Trophies", prompt:"Texas and Oklahoma play their rivalry game for which trophy?", choices:["Golden Hat","Golden Boot","Red River Cup","Lone Star Trophy"], answer:"Golden Hat", explanation:"The Red River rivalry winner receives the Golden Hat trophy.", sourceId:"red-river-golden-hat" }),
  q({ id:"cfb-r1-jeweled-shillelagh", league:"cfb", round:"round1", category:"Rivalry Trophies", prompt:"The Jeweled Shillelagh is awarded in the rivalry between Notre Dame and which school?", choices:["USC","Michigan","Navy","Stanford"], answer:"USC", explanation:"Notre Dame and USC play for the Jeweled Shillelagh.", sourceId:"usc-notre-dame" }),
  q({ id:"cfb-r1-land-grant-trophy", league:"cfb", round:"round1", category:"Rivalry Trophies", prompt:"The Land Grant Trophy is contested by Penn State and which school?", choices:["Michigan State","Ohio State","Purdue","Rutgers"], answer:"Michigan State", explanation:"Penn State and Michigan State play for the Land Grant Trophy.", sourceId:"land-grant-trophy" }),
  q({ id:"cfb-r1-cyhawk", league:"cfb", round:"round1", category:"Rivalry Trophies", prompt:"The Cy-Hawk Trophy goes to the winner of Iowa versus which rival?", choices:["Iowa State","Nebraska","Minnesota","Wisconsin"], answer:"Iowa State", explanation:"Iowa and Iowa State play for the Cy-Hawk Trophy.", sourceId:"cy-hawk" }),
  q({ id:"cfb-r1-kick-six-player", league:"cfb", round:"round1", category:"Iconic Plays", prompt:"Who returned Alabama's missed field goal for Auburn's famous 'Kick Six' touchdown?", choices:["Chris Davis","Tre Mason","Nick Marshall","Ricardo Louis"], answer:"Chris Davis", explanation:"Chris Davis returned the missed kick for the winning touchdown on the final play of the 2013 Iron Bowl.", sourceId:"kick-six" }),

  // Round 2
  q({ id:"cfb-r2-miracle-jordan-hare", league:"cfb", round:"round2", category:"Iconic Plays", prompt:"The 2013 'Miracle at Jordan-Hare' came when Auburn completed a tipped touchdown pass against which team?", choices:["Georgia","Alabama","LSU","Texas A&M"], answer:"Georgia", explanation:"Ricardo Louis caught a deflected fourth-down pass for a late Auburn touchdown against Georgia.", sourceId:"miracle-jordan-hare" }),
  q({ id:"cfb-r2-bluegrass-miracle", league:"cfb", round:"round2", category:"Iconic Plays", prompt:"The 'Bluegrass Miracle' was a last-second LSU touchdown against which school?", choices:["Kentucky","Tennessee","Auburn","Ole Miss"], answer:"Kentucky", explanation:"LSU beat Kentucky in 2002 on a tipped Hail Mary known as the Bluegrass Miracle.", sourceId:"bluegrass-miracle" }),
  q({ id:"cfb-r2-miracle-michigan", league:"cfb", round:"round2", category:"Iconic Plays", prompt:"Kordell Stewart's 1994 Hail Mary known as the 'Miracle at Michigan' lifted which school?", choices:["Colorado","Nebraska","Penn State","Notre Dame"], answer:"Colorado", explanation:"Colorado beat Michigan on Stewart's last-second Hail Mary to Michael Westbrook.", sourceId:"miracle-at-michigan" }),
  q({ id:"cfb-r2-trouble-with-snap", league:"cfb", round:"round2", category:"Iconic Plays", prompt:"The famous 2015 'trouble with the snap' play gave which team a last-second win over Michigan?", choices:["Michigan State","Ohio State","Iowa","Penn State"], answer:"Michigan State", explanation:"Michigan State's Jalen Watts-Jackson returned a botched punt snap for a touchdown on the final play.", sourceId:"michigan-state-michigan-2015" }),
  q({ id:"cfb-r2-clowney-hit", league:"cfb", round:"round2", category:"Iconic Plays", prompt:"Jadeveon Clowney's famous bowl-game hit came against which school?", choices:["Michigan","Ohio State","Wisconsin","Nebraska"], answer:"Michigan", explanation:"Clowney's crushing hit and fumble recovery came in South Carolina's 2013 Outback Bowl win over Michigan.", sourceId:"clowney-hit" }),
  q({ id:"cfb-r2-2nd-and-26", league:"cfb", round:"round2", category:"Championship Moments", prompt:"Alabama's famous '2nd and 26' national-title touchdown in 2018 came against which team?", choices:["Georgia","Clemson","Ohio State","LSU"], answer:"Georgia", explanation:"Tua Tagovailoa hit DeVonta Smith for the overtime championship-winning touchdown against Georgia.", sourceId:"second-and-26" }),
  q({ id:"cfb-r2-statue-liberty-scorer", league:"cfb", round:"round2", category:"Bowl Moments", prompt:"Who scored Boise State's winning two-point conversion on the Statue of Liberty play in the 2007 Fiesta Bowl?", choices:["Ian Johnson","Jared Zabransky","Vinny Perretta","Jeremy Childs"], answer:"Ian Johnson", explanation:"Running back Ian Johnson took the hidden handoff and scored the winning conversion against Oklahoma.", sourceId:"boise-fiesta-bowl" }),
  q({ id:"cfb-r2-rose-bowl-2006-opponent", league:"cfb", round:"round2", category:"Championship Moments", prompt:"Texas ended USC's 34-game winning streak in the 2006 Rose Bowl to win the national title. Who scored the winning touchdown?", choices:["Vince Young","Jamaal Charles","Limas Sweed","Selvin Young"], answer:"Vince Young", explanation:"Vince Young scored on fourth down with 19 seconds left to give Texas a 41–38 victory.", sourceId:"rose-bowl-2006" }),
  q({ id:"cfb-r2-fifth-down", league:"cfb", round:"round2", category:"Controversies", prompt:"The infamous 'Fifth Down Game' in 1990 involved Colorado and which school?", choices:["Missouri","Nebraska","Oklahoma","Kansas State"], answer:"Missouri", explanation:"Colorado mistakenly received an extra down late in its 1990 win at Missouri.", sourceId:"fifth-down-game" }),
  q({ id:"cfb-r2-wide-right-school", league:"cfb", round:"round2", category:"Rivalry Moments", prompt:"The phrase 'Wide Right' became painfully associated with which program after several close losses to Florida State?", choices:["Miami","Florida","Clemson","Notre Dame"], answer:"Miami", explanation:"Miami-Florida State rivalry history includes multiple famous missed kicks labeled Wide Right.", sourceId:"miami-fsu-wide-right" }),
  q({ id:"cfb-r2-commander-chief-trophy", league:"cfb", round:"round2", category:"Rivalry Trophies", prompt:"The Commander-in-Chief's Trophy is contested among Army, Navy and which third service academy?", choices:["Air Force","Coast Guard","Merchant Marine","The Citadel"], answer:"Air Force", explanation:"Army, Navy and Air Force compete annually for the Commander-in-Chief's Trophy.", sourceId:"commander-in-chief-trophy" }),
  q({ id:"cfb-r2-bedlam", league:"cfb", round:"round2", category:"Rivalries", prompt:"The rivalry historically known as 'Bedlam' matches Oklahoma against which school?", choices:["Oklahoma State","Texas","Nebraska","Kansas State"], answer:"Oklahoma State", explanation:"Oklahoma and Oklahoma State's in-state rivalry is known as Bedlam.", sourceId:"bedlam" }),
  q({ id:"cfb-r2-palmetto-bowl", league:"cfb", round:"round2", category:"Rivalries", prompt:"The Palmetto Bowl rivalry is Clemson against which school?", choices:["South Carolina","Georgia","NC State","Florida State"], answer:"South Carolina", explanation:"Clemson and South Carolina meet in the Palmetto Bowl.", sourceId:"palmetto-bowl" }),
  q({ id:"cfb-r2-worlds-largest-outdoor", league:"cfb", round:"round2", category:"Rivalries", prompt:"The rivalry long nicknamed the 'World's Largest Outdoor Cocktail Party' is Georgia against which school?", choices:["Florida","Auburn","Tennessee","South Carolina"], answer:"Florida", explanation:"Georgia and Florida meet annually in Jacksonville in one of college football's best-known neutral-site rivalries.", sourceId:"georgia-florida" }),

  // Round 3
  q({ id:"cfb-r3-kick-six-field-goal", league:"cfb", round:"round3", category:"Iconic Plays", prompt:"The missed Alabama field-goal attempt that produced the Kick Six was officially attempted from how far?", choices:["57 yards","52 yards","60 yards","49 yards"], answer:"57 yards", explanation:"Alabama attempted a 57-yard field goal on the final play before Chris Davis returned the miss for Auburn's winning touchdown.", sourceId:"kick-six" }),
  q({ id:"cfb-r3-band-field-opponent", league:"cfb", round:"round3", category:"Iconic Plays", prompt:"On 'The Play' in 1982, California scored through the Stanford band after how many laterals?", choices:["Five","Three","Four","Six"], answer:"Five", explanation:"Cal used five laterals on the chaotic final kickoff return against Stanford.", sourceId:"cal-the-play" }),
  q({ id:"cfb-r3-hail-flutie-receiver", league:"cfb", round:"round3", category:"Iconic Plays", prompt:"Who caught Doug Flutie's famous Hail Mary against Miami in 1984?", choices:["Gerard Phelan","Troy Stradford","Scott Gieselman","Kelvin Martin"], answer:"Gerard Phelan", explanation:"Gerard Phelan caught Flutie's last-second pass in the end zone to beat Miami.", sourceId:"hail-flutie" }),
  q({ id:"cfb-r3-app-state-blocked-kick", league:"cfb", round:"round3", category:"Upsets", prompt:"Appalachian State sealed its 2007 upset of Michigan by blocking what kind of play at the end?", choices:["Field goal","Punt","Extra point","Fourth-down pass"], answer:"Field goal", explanation:"App State blocked Michigan's potential game-winning field goal as time expired.", sourceId:"app-state-michigan" }),
  q({ id:"cfb-r3-2nd26-receiver", league:"cfb", round:"round3", category:"Championship Moments", prompt:"Who caught Tua Tagovailoa's '2nd and 26' touchdown pass to win the national championship?", choices:["DeVonta Smith","Calvin Ridley","Jerry Jeudy","Henry Ruggs III"], answer:"DeVonta Smith", explanation:"Freshman DeVonta Smith caught the overtime title-winning pass against Georgia.", sourceId:"second-and-26" }),
  q({ id:"cfb-r3-first-cfp-seed", league:"cfb", round:"round3", category:"Playoff History", prompt:"Ohio State entered the first College Football Playoff as which seed before winning the title?", choices:["No. 4","No. 1","No. 2","No. 3"], answer:"No. 4", explanation:"Ohio State entered the inaugural playoff ranked fourth, then beat Alabama and Oregon.", sourceId:"first-cfp" }),
  q({ id:"cfb-r3-1984-byu-bowl", league:"cfb", round:"round3", category:"Championship History", prompt:"BYU clinched its 1984 national-title season by winning which bowl game?", choices:["Holiday Bowl","Fiesta Bowl","Cotton Bowl","Orange Bowl"], answer:"Holiday Bowl", explanation:"BYU beat Michigan in the Holiday Bowl to finish 13–0 and claim the national championship.", sourceId:"byu-1984" }),
  q({ id:"cfb-r3-1998-tennessee-qb", league:"cfb", round:"round3", category:"Championship History", prompt:"Who quarterbacked Tennessee to the first BCS national championship after the 1998 season?", choices:["Tee Martin","Peyton Manning","Casey Clausen","Erik Ainge"], answer:"Tee Martin", explanation:"Tee Martin led Tennessee's undefeated 1998 national-title team.", sourceId:"tennessee-1998" }),
  q({ id:"cfb-r3-usc-notre-dame-trophy", league:"cfb", round:"round3", category:"Rivalry Trophies", prompt:"What object is decorated with jeweled shamrocks and Trojan heads for the USC-Notre Dame rivalry?", choices:["A shillelagh","A sword","A bell","A shield"], answer:"A shillelagh", explanation:"The Jeweled Shillelagh is the trophy exchanged by Notre Dame and USC.", sourceId:"jeweled-shillelagh" }),
  q({ id:"cfb-r3-floyd-object", league:"cfb", round:"round3", category:"Rivalry Trophies", prompt:"Floyd of Rosedale, the Iowa-Minnesota rivalry trophy, is shaped like what animal?", choices:["Pig","Bull","Bear","Hawk"], answer:"Pig", explanation:"Floyd of Rosedale is a bronze pig trophy.", sourceId:"floyd-of-rosedale" }),
  q({ id:"cfb-r3-old-oaken-object", league:"cfb", round:"round3", category:"Rivalry Trophies", prompt:"The Indiana-Purdue rivalry trophy is literally what kind of object?", choices:["Bucket","Bell","Jug","Axe"], answer:"Bucket", explanation:"The Old Oaken Bucket is exactly that: an old wooden bucket mounted as a rivalry trophy.", sourceId:"old-oaken-bucket" }),
  q({ id:"cfb-r3-land-grant-schools", league:"cfb", round:"round3", category:"Rivalry Trophies", prompt:"Why is the Penn State-Michigan State trophy called the Land Grant Trophy?", choices:["Both schools are historic land-grant universities","The trophy was carved from federal land","The winner receives farmland","The game began under a federal grant"], answer:"Both schools are historic land-grant universities", explanation:"The trophy name reflects the land-grant heritage shared by Penn State and Michigan State.", sourceId:"land-grant-trophy" }),

  // Last Call
  q({ id:"cfb-final-the-play-score", league:"cfb", round:"last-call", category:"Iconic Plays", prompt:"What was the final score of the 1982 Stanford-Cal game that ended with 'The Play'?", choices:["25–20 Cal","24–21 Cal","27–24 Stanford","28–27 Cal"], answer:"25–20 Cal", explanation:"Cal's five-lateral kickoff return produced a 25–20 victory over Stanford.", sourceId:"cal-the-play" }),
  q({ id:"cfb-final-fifth-down-score", league:"cfb", round:"last-call", category:"Controversies", prompt:"Colorado's infamous Fifth Down play produced the winning score against Missouri in which season?", choices:["1990","1989","1991","1994"], answer:"1990", explanation:"The controversial Fifth Down Game occurred during Colorado's 1990 national-title season.", sourceId:"fifth-down-game" }),
  q({ id:"cfb-final-kick-six-year", league:"cfb", round:"last-call", category:"Iconic Plays", prompt:"In what year did the Kick Six end the Iron Bowl?", choices:["2013","2012","2014","2010"], answer:"2013", explanation:"Chris Davis' legendary return ended the 2013 Iron Bowl.", sourceId:"kick-six" }),
  q({ id:"cfb-final-heisman-first-soph-year", league:"cfb", round:"last-call", category:"Heisman History", prompt:"In what year did Tim Tebow become the first sophomore to win the Heisman Trophy?", choices:["2007","2006","2008","2009"], answer:"2007", explanation:"Tebow won the Heisman as a Florida sophomore in 2007.", sourceId:"heisman-milestones", sourceUrl:HEISMAN }),
];
