import { barTriviaQuestion, type BarTriviaQuestion } from "../games/barTriviaEngine";

const HEISMAN = "https://www.heisman.com/about-the-heisman/milestones/";
const ROSE = "https://rosebowlgame.com/sports/2021/9/30/history-of-the-granddaddy-of-them-all.aspx";
const ROSE_STADIUM = "https://rosebowlgame.com/sports/2021/10/4/tournament-of-roses-rose-parade";
const ARMY_NAVY = "https://www.army.mil/article-amp/289527/10_things_to_know_before_the_2025_army_vs_navy_football_game";
const ARMY_NAVY_FACTS = "https://www.army.mil/article-amp/179134/the_army_navy_game_13_historical_facts_you_probably_dont_know";
const CFP_OT = "https://collegefootballplayoff.com/sports/2022/8/19/overtime-shutouts";
const STADIUMS = "https://www.ncaa.com/news/football/article/2018-07-30/25-biggest-college-football-stadiums-country";

function q(seed: Parameters<typeof barTriviaQuestion>[0]) {
  return barTriviaQuestion({ ...seed, verifiedAt: "2026-09-28" });
}

export const BAR_TRIVIA_CFB_EVERGREEN_WAVE_2: readonly BarTriviaQuestion[] = [
  // Round 1
  q({ id:"cfb-r1-granddaddy", league:"cfb", round:"round1", category:"Bowl Traditions", prompt:"Which bowl game is famously known as 'The Granddaddy of Them All'?", choices:["Rose Bowl","Sugar Bowl","Orange Bowl","Cotton Bowl"], answer:"Rose Bowl", explanation:"The Rose Bowl Game is traditionally known as The Granddaddy of Them All.", sourceId:"rose-bowl-history", sourceUrl:ROSE }),
  q({ id:"cfb-r1-first-postseason-game", league:"cfb", round:"round1", category:"Bowl History", prompt:"Which game is recognized as the first postseason college football game?", choices:["1902 Rose Bowl","1935 Orange Bowl","1935 Sugar Bowl","1937 Cotton Bowl"], answer:"1902 Rose Bowl", explanation:"The first Tournament of Roses football game was staged on Jan. 1, 1902.", sourceId:"rose-bowl-history", sourceUrl:ROSE }),
  q({ id:"cfb-r1-army-mascot", league:"cfb", round:"round1", category:"Mascots", prompt:"What animal serves as Army's traditional live mascot?", choices:["Mule","Goat","Horse","Eagle"], answer:"Mule", explanation:"Army chose the mule as a symbol of strength and its long military tradition.", sourceId:"army-navy-facts", sourceUrl:ARMY_NAVY }),
  q({ id:"cfb-r1-navy-mascot", league:"cfb", round:"round1", category:"Mascots", prompt:"What animal is the traditional live mascot of Navy?", choices:["Goat","Mule","Ram","Bulldog"], answer:"Goat", explanation:"Navy's mascot is a goat named Bill, rooted in an old naval superstition and football story.", sourceId:"army-navy-facts", sourceUrl:ARMY_NAVY }),
  q({ id:"cfb-r1-sing-second", league:"cfb", round:"round1", category:"Rivalry Traditions", prompt:"In the Army–Navy rivalry, what does it mean to 'Sing Second'?", choices:["Win the game","Score second","Take the field second","Choose the second uniform"], answer:"Win the game", explanation:"The losing team sings its alma mater first; the winner then runs to its band and sings second.", sourceId:"army-navy-facts", sourceUrl:ARMY_NAVY }),
  q({ id:"cfb-r1-army-navy-first-year", league:"cfb", round:"round1", category:"Rivalry History", prompt:"Army and Navy first played football against each other in which century?", choices:["19th century","18th century","20th century","21st century"], answer:"19th century", explanation:"The rivalry began in 1890 at West Point.", sourceId:"army-navy-facts", sourceUrl:ARMY_NAVY_FACTS }),
  q({ id:"cfb-r1-army-navy-most-host-city", league:"cfb", round:"round1", category:"Rivalry History", prompt:"Which city has hosted the Army–Navy game more than any other?", choices:["Philadelphia","Baltimore","New York","Washington, D.C."], answer:"Philadelphia", explanation:"Philadelphia has hosted the rivalry far more often than any other city.", sourceId:"army-navy-facts", sourceUrl:ARMY_NAVY }),
  q({ id:"cfb-r1-first-black-heisman", league:"cfb", round:"round1", category:"Heisman", prompt:"Who became the first African-American player to win the Heisman Trophy?", choices:["Ernie Davis","Jim Brown","O.J. Simpson","Gale Sayers"], answer:"Ernie Davis", explanation:"Syracuse running back Ernie Davis broke the barrier in 1961.", sourceId:"heisman-milestones", sourceUrl:HEISMAN }),
  q({ id:"cfb-r1-heisman-losing-team", league:"cfb", round:"round1", category:"Heisman Oddities", prompt:"Which Notre Dame star remains the only Heisman winner from a losing team?", choices:["Paul Hornung","Tim Brown","John Huarte","Johnny Lujack"], answer:"Paul Hornung", explanation:"Paul Hornung won the 1956 Heisman even though Notre Dame finished 2–8.", sourceId:"heisman-milestones", sourceUrl:HEISMAN }),
  q({ id:"cfb-r1-first-west-coast-heisman", league:"cfb", round:"round1", category:"Heisman", prompt:"Who became the first West Coast player to win the Heisman Trophy?", choices:["Terry Baker","O.J. Simpson","Gary Beban","Jim Plunkett"], answer:"Terry Baker", explanation:"Oregon State quarterback Terry Baker became the first West Coast Heisman winner in 1962.", sourceId:"heisman-milestones", sourceUrl:HEISMAN }),
  q({ id:"cfb-r1-first-junior-heisman", league:"cfb", round:"round1", category:"Heisman", prompt:"Who became the first junior to win the Heisman Trophy?", choices:["Doc Blanchard","Glenn Davis","Doak Walker","Johnny Lujack"], answer:"Doc Blanchard", explanation:"Army fullback Felix 'Doc' Blanchard became the first junior Heisman winner in 1945.", sourceId:"heisman-milestones", sourceUrl:HEISMAN }),
  q({ id:"cfb-r1-largest-stadium-school", league:"cfb", round:"round1", category:"Stadiums", prompt:"Which school plays in the largest-capacity primary FBS stadium entering the 2026 season?", choices:["Michigan","Penn State","Ohio State","Texas A&M"], answer:"Michigan", explanation:"Michigan Stadium, the Big House, leads the NCAA's 2026 FBS capacity list.", sourceId:"ncaa-largest-stadiums", sourceUrl:STADIUMS }),
  q({ id:"cfb-r1-first-cfp-semifinal-bowl", league:"cfb", round:"round1", category:"Playoff History", prompt:"Which bowl hosted the first College Football Playoff semifinal game?", choices:["Rose Bowl","Sugar Bowl","Orange Bowl","Fiesta Bowl"], answer:"Rose Bowl", explanation:"The Rose Bowl hosted the first CFP semifinal on Jan. 1, 2015.", sourceId:"rose-bowl-history", sourceUrl:ROSE }),

  // Round 2
  q({ id:"cfb-r2-rose-football-return", league:"cfb", round:"round2", category:"Bowl History", prompt:"After the lopsided 1902 game, Rose Bowl football returned permanently in which decade?", choices:["1910s","1900s","1920s","1930s"], answer:"1910s", explanation:"Football was permanently restored to the Tournament of Roses program in 1916.", sourceId:"rose-bowl-history", sourceUrl:ROSE }),
  q({ id:"cfb-r2-rose-chariot-races", league:"cfb", round:"round2", category:"Bowl Oddities", prompt:"What replaced football at the Tournament of Roses for years after the 1902 game?", choices:["Chariot races","Baseball","Polo","Track meets"], answer:"Chariot races", explanation:"After Michigan's 49–0 win, the Tournament replaced football with Roman-style chariot races until 1916.", sourceId:"rose-bowl-history", sourceUrl:ROSE }),
  q({ id:"cfb-r2-rose-stadium-first-game", league:"cfb", round:"round2", category:"Stadium History", prompt:"The stadium now called the Rose Bowl hosted its first game in which decade?", choices:["1920s","1910s","1930s","1940s"], answer:"1920s", explanation:"The Pasadena stadium hosted its first game on New Year's Day 1923.", sourceId:"rose-bowl-stadium", sourceUrl:ROSE_STADIUM }),
  q({ id:"cfb-r2-rose-big-ten-pac-pact", league:"cfb", round:"round2", category:"Bowl Traditions", prompt:"The Rose Bowl's long-running conference agreement traditionally matched the Big Ten against which league?", choices:["Pac-12","SEC","Big 12","ACC"], answer:"Pac-12", explanation:"The Big Ten–Pacific Coast/Pac-12 agreement dates to 1946, with the first game under it in 1947.", sourceId:"rose-bowl-history", sourceUrl:ROSE }),
  q({ id:"cfb-r2-rose-first-national-tv", league:"cfb", round:"round2", category:"Broadcast", prompt:"The Rose Bowl became the first nationally televised college football game in which decade?", choices:["1950s","1940s","1960s","1970s"], answer:"1950s", explanation:"The 1952 Rose Bowl was the first national telecast of a college football game.", sourceId:"rose-bowl-history", sourceUrl:ROSE }),
  q({ id:"cfb-r2-rose-first-color-coast", league:"cfb", round:"round2", category:"Broadcast", prompt:"The Rose Bowl delivered the first coast-to-coast color telecast of a college football game in which decade?", choices:["1960s","1950s","1970s","1980s"], answer:"1960s", explanation:"The Rose Bowl reached that broadcast milestone in 1962.", sourceId:"rose-bowl-history", sourceUrl:ROSE }),
  q({ id:"cfb-r2-army-navy-first-site", league:"cfb", round:"round2", category:"Rivalry History", prompt:"Where was the first Army–Navy football game played?", choices:["West Point","Annapolis","Philadelphia","Baltimore"], answer:"West Point", explanation:"The inaugural 1890 game was played on The Plain at West Point.", sourceId:"army-navy-facts", sourceUrl:ARMY_NAVY_FACTS }),
  q({ id:"cfb-r2-army-navy-first-winner", league:"cfb", round:"round2", category:"Rivalry History", prompt:"Who won the first Army–Navy football game in 1890?", choices:["Navy","Army","It ended in a tie","The game was canceled"], answer:"Navy", explanation:"Navy, already an established football team, beat the newly formed Army team 24–0.", sourceId:"army-navy-facts", sourceUrl:ARMY_NAVY_FACTS }),
  q({ id:"cfb-r2-army-mule-origin-year", league:"cfb", round:"round2", category:"Mascot History", prompt:"Army's tradition of using mules as mascots dates back to which century?", choices:["19th century","18th century","20th century","21st century"], answer:"19th century", explanation:"The mule mascot tradition dates to 1899.", sourceId:"army-navy-facts", sourceUrl:ARMY_NAVY_FACTS }),
  q({ id:"cfb-r2-soldier-field-army-navy", league:"cfb", round:"round2", category:"Rivalry History", prompt:"The 1926 Army–Navy game helped formally dedicate which stadium?", choices:["Soldier Field","Yankee Stadium","Franklin Field","Polo Grounds"], answer:"Soldier Field", explanation:"Army and Navy played in Chicago in 1926 for the formal dedication of Soldier Field.", sourceId:"army-navy-facts", sourceUrl:ARMY_NAVY_FACTS }),
  q({ id:"cfb-r2-heisman-renamed", league:"cfb", round:"round2", category:"Heisman History", prompt:"The Downtown Athletic Club Trophy was renamed the Heisman Memorial Trophy in which year?", choices:["1936","1935","1940","1945"], answer:"1936", explanation:"The award was renamed after John W. Heisman's death in 1936.", sourceId:"heisman-milestones", sourceUrl:HEISMAN }),
  q({ id:"cfb-r2-flutie-rb-streak", league:"cfb", round:"round2", category:"Heisman History", prompt:"Doug Flutie's 1984 Heisman ended a streak of how many straight running-back winners?", choices:["11","7","9","13"], answer:"11", explanation:"Flutie became the first quarterback since 1971 to win after 11 consecutive running backs.", sourceId:"heisman-milestones", sourceUrl:HEISMAN }),
  q({ id:"cfb-r2-first-heisman-finalists", league:"cfb", round:"round2", category:"Heisman History", prompt:"Which trio became the first group of finalists invited to New York for a live Heisman ceremony?", choices:["Herschel Walker, John Elway and Eric Dickerson","Bo Jackson, Chuck Long and Robbie Bosco","Doug Flutie, Keith Byars and Bernie Kosar","Marcus Allen, Herschel Walker and Jim McMahon"], answer:"Herschel Walker, John Elway and Eric Dickerson", explanation:"Those three were named the first official ceremony finalists in 1982.", sourceId:"heisman-milestones", sourceUrl:HEISMAN }),

  // Round 3
  q({ id:"cfb-r3-terry-baker-final-four", league:"cfb", round:"round3", category:"Two-Sport History", prompt:"Which Heisman winner is also the only one to have played in an NCAA basketball Final Four?", choices:["Terry Baker","Bo Jackson","Charlie Ward","Tony Dorsett"], answer:"Terry Baker", explanation:"Oregon State's Terry Baker won the 1962 Heisman and played in the 1963 NCAA basketball Final Four.", sourceId:"heisman-milestones", sourceUrl:HEISMAN }),
  q({ id:"cfb-r3-last-ivy-heisman", league:"cfb", round:"round3", category:"Heisman History", prompt:"Who is the most recent Ivy League player to win the Heisman Trophy?", choices:["Dick Kazmaier","Clint Frank","Larry Kelley","Ed Marinaro"], answer:"Dick Kazmaier", explanation:"Princeton's Dick Kazmaier won in 1951 and remains the most recent Ivy League Heisman winner.", sourceId:"heisman-milestones", sourceUrl:HEISMAN }),
  q({ id:"cfb-r3-hornung-record", league:"cfb", round:"round3", category:"Heisman Oddities", prompt:"Notre Dame had what record when Paul Hornung won the 1956 Heisman?", choices:["2–8","5–5","4–6","6–4"], answer:"2–8", explanation:"Hornung remains the only Heisman winner from a losing team; Notre Dame went 2–8.", sourceId:"heisman-milestones", sourceUrl:HEISMAN }),
  q({ id:"cfb-r3-ernie-davis-school", league:"cfb", round:"round3", category:"Heisman History", prompt:"Ernie Davis became the first African-American Heisman winner while playing for which school?", choices:["Syracuse","Michigan State","UCLA","Grambling State"], answer:"Syracuse", explanation:"Syracuse running back Ernie Davis won the Heisman in 1961.", sourceId:"heisman-milestones", sourceUrl:HEISMAN }),
  q({ id:"cfb-r3-first-live-heisman-winner", league:"cfb", round:"round3", category:"Broadcast", prompt:"Who was the first Heisman winner to have his announcement broadcast live on television?", choices:["Marcus Allen","Herschel Walker","George Rogers","Doug Flutie"], answer:"Marcus Allen", explanation:"USC's Marcus Allen became the first live-television Heisman announcement in 1981.", sourceId:"heisman-milestones", sourceUrl:HEISMAN }),
  q({ id:"cfb-r3-cfp-title-first-ot", league:"cfb", round:"round3", category:"Playoff History", prompt:"Which team won the first College Football Playoff national championship game to reach overtime?", choices:["Alabama","Georgia","Clemson","Ohio State"], answer:"Alabama", explanation:"Alabama beat Georgia 26–23 in overtime in the January 2018 CFP title game.", sourceId:"cfp-overtime", sourceUrl:CFP_OT }),
  q({ id:"cfb-r3-cfp-semifinal-first-2ot", league:"cfb", round:"round3", category:"Playoff History", prompt:"Which team won the first CFP semifinal to go to double overtime?", choices:["Georgia","Oklahoma","Alabama","Ohio State"], answer:"Georgia", explanation:"Georgia beat Oklahoma 54–48 in double overtime at the 2018 Rose Bowl semifinal.", sourceId:"cfp-overtime", sourceUrl:CFP_OT }),
  q({ id:"cfb-r3-cfp-rose-2024-ot", league:"cfb", round:"round3", category:"Playoff History", prompt:"Michigan's overtime Rose Bowl semifinal win in January 2024 came against which team?", choices:["Alabama","Georgia","Texas","Washington"], answer:"Alabama", explanation:"Michigan beat Alabama 27–20 in overtime before winning the national title.", sourceId:"cfp-overtime", sourceUrl:CFP_OT }),
  q({ id:"cfb-r3-cfp-peach-2025-2ot", league:"cfb", round:"round3", category:"Playoff History", prompt:"Texas won a double-overtime CFP Peach Bowl thriller in January 2025 against which team?", choices:["Arizona State","Clemson","Ohio State","Notre Dame"], answer:"Arizona State", explanation:"Texas defeated Arizona State 39–31 in two overtimes.", sourceId:"cfp-overtime", sourceUrl:CFP_OT }),
  q({ id:"cfb-r3-cfp-first-semifinal-shutout", league:"cfb", round:"round3", category:"Playoff History", prompt:"Which team recorded the first shutout in a CFP semifinal?", choices:["Alabama","Clemson","Georgia","Ohio State"], answer:"Alabama", explanation:"Alabama beat Michigan State 38–0 in the Cotton Bowl semifinal on Dec. 31, 2015.", sourceId:"cfp-overtime", sourceUrl:CFP_OT }),
  q({ id:"cfb-r3-cfp-clemson-shutout", league:"cfb", round:"round3", category:"Playoff History", prompt:"Clemson's 31–0 CFP semifinal shutout in 2016 came against which program?", choices:["Ohio State","Alabama","Oklahoma","Michigan State"], answer:"Ohio State", explanation:"Clemson blanked Ohio State 31–0 in the Fiesta Bowl semifinal.", sourceId:"cfp-overtime", sourceUrl:CFP_OT }),
  q({ id:"cfb-r3-rose-first-transcontinental-radio", league:"cfb", round:"round3", category:"Broadcast History", prompt:"The Rose Bowl became the first transcontinental radio broadcast of a sporting event in what year?", choices:["1927","1919","1935","1948"], answer:"1927", explanation:"The Rose Bowl achieved the transcontinental radio milestone in 1927.", sourceId:"rose-bowl-history", sourceUrl:ROSE }),
  q({ id:"cfb-r3-army-navy-1944-ranking", league:"cfb", round:"round3", category:"Rivalry History", prompt:"Going into the 1944 and 1945 Army–Navy games, the teams held which two spots in the national rankings?", choices:["No. 1 and No. 2","No. 1 and No. 3","No. 2 and No. 4","No. 3 and No. 4"], answer:"No. 1 and No. 2", explanation:"Army and Navy entered both 1944 and 1945 ranked first and second, with Army winning each game.", sourceId:"army-navy-facts", sourceUrl:ARMY_NAVY_FACTS }),

  // Last Call
  q({ id:"cfb-final-first-heisman-original-name", league:"cfb", round:"last-call", category:"Heisman Origins", prompt:"What was the Heisman Trophy originally called when Jay Berwanger won it in 1935?", choices:["Downtown Athletic Club Trophy","National Football Trophy","Walter Camp Award","New York Athletic Trophy"], answer:"Downtown Athletic Club Trophy", explanation:"The first award was the DAC Trophy; it was renamed for John W. Heisman in 1936.", sourceId:"heisman-milestones", sourceUrl:HEISMAN }),
  q({ id:"cfb-final-army-navy-travel-cents", league:"cfb", round:"last-call", category:"Rivalry Oddities", prompt:"For the first Army–Navy game in 1890, West Point cadets helped pay Navy's travel bill by contributing how much each?", choices:["52 cents","25 cents","1 dollar","10 cents"], answer:"52 cents", explanation:"The 271 cadets each contributed 52 cents to cover half of Navy's travel costs.", sourceId:"army-navy-facts", sourceUrl:ARMY_NAVY_FACTS }),
  q({ id:"cfb-final-rose-first-local-tv-year", league:"cfb", round:"last-call", category:"Broadcast History", prompt:"The Rose Bowl became the first locally televised college football game in what year?", choices:["1948","1942","1952","1956"], answer:"1948", explanation:"The Rose Bowl's 1948 game marked the first local telecast of a college football game.", sourceId:"rose-bowl-history", sourceUrl:ROSE }),
];
