import { barTriviaQuestion, type BarTriviaQuestion } from "../games/barTriviaEngine";

const UFC30 = "https://www.ufc.com/30";
const HOF = "https://www.ufc.com/news/ufc-hall-fame-faq";
const TOP500 = "https://www.ufc.com/news/top-500-ufc-moments-list";
const LW = "https://www.ufc.com/news/ufc-lightweight-title-lineage-khabib-mcgregor-penn-poirier-oliveira";
const MW = "https://www.ufc.com/news/ufc-middleweight-title-lineage-adesanya-whittaker-GSP-bisping-silva-history";

function q(seed: Parameters<typeof barTriviaQuestion>[0]) {
  return barTriviaQuestion({ ...seed, verifiedAt: "2026-09-28" });
}

export const BAR_TRIVIA_UFC_EVERGREEN_WAVE_4: readonly BarTriviaQuestion[] = [
  // Round 1 — recognizable champions and title changes
  q({ id:"ufc-r1-oliveira-chandler", league:"ufc", round:"round1", category:"Championship Moments", prompt:"Charles Oliveira won the vacant UFC lightweight title by stopping which opponent?", choices:["Michael Chandler","Dustin Poirier","Justin Gaethje","Tony Ferguson"], answer:"Michael Chandler", explanation:"Oliveira stopped Michael Chandler at UFC 262 to become lightweight champion.", sourceId:"ufc-lightweight-lineage", sourceUrl:LW }),
  q({ id:"ufc-r1-gsp-first-title-hughes", league:"ufc", round:"round1", category:"Championship Moments", prompt:"Georges St-Pierre won his first UFC welterweight title by defeating whom?", choices:["Matt Hughes","Matt Serra","BJ Penn","Josh Koscheck"], answer:"Matt Hughes", explanation:"St-Pierre stopped Matt Hughes at UFC 65 to capture the welterweight championship.", sourceId:"ufc-gsp-history" }),
  q({ id:"ufc-r1-cejudo-dj", league:"ufc", round:"round1", category:"Title Changes", prompt:"Who ended Demetrious Johnson's historic UFC flyweight title reign?", choices:["Henry Cejudo","Joseph Benavidez","John Dodson","Brandon Moreno"], answer:"Henry Cejudo", explanation:"Henry Cejudo edged Johnson by split decision at UFC 227.", sourceId:"ufc-cejudo-johnson" }),
  q({ id:"ufc-r1-garbrandt-cruz", league:"ufc", round:"round1", category:"Title Changes", prompt:"Who took the UFC bantamweight title from Dominick Cruz at UFC 207?", choices:["Cody Garbrandt","TJ Dillashaw","Renan Barao","Marlon Moraes"], answer:"Cody Garbrandt", explanation:"Cody Garbrandt outpointed Dominick Cruz to win the bantamweight championship.", sourceId:"ufc207-history" }),
  q({ id:"ufc-r1-volkanovski-holloway", league:"ufc", round:"round1", category:"Title Changes", prompt:"Who ended Max Holloway's first UFC featherweight title reign?", choices:["Alexander Volkanovski","Jose Aldo","Dustin Poirier","Ilia Topuria"], answer:"Alexander Volkanovski", explanation:"Volkanovski defeated Holloway by decision at UFC 245.", sourceId:"ufc-featherweight-history" }),
  q({ id:"ufc-r1-edgar-penn", league:"ufc", round:"round1", category:"Title Changes", prompt:"Who took the UFC lightweight title from BJ Penn at UFC 112?", choices:["Frankie Edgar","Gray Maynard","Kenny Florian","Sean Sherk"], answer:"Frankie Edgar", explanation:"Frankie Edgar upset BJ Penn by decision at UFC 112.", sourceId:"ufc-lightweight-lineage", sourceUrl:LW }),
  q({ id:"ufc-r1-silva-franklin", league:"ufc", round:"round1", category:"Title Changes", prompt:"Anderson Silva won the UFC middleweight title by defeating whom?", choices:["Rich Franklin","Chris Leben","Nate Marquardt","Dan Henderson"], answer:"Rich Franklin", explanation:"Silva stopped Rich Franklin at UFC 64 to begin his historic championship reign.", sourceId:"ufc-middleweight-lineage", sourceUrl:MW }),
  q({ id:"ufc-r1-joanna-esparza", league:"ufc", round:"round1", category:"Title Changes", prompt:"Joanna Jedrzejczyk won the UFC strawweight title by defeating which inaugural champion?", choices:["Carla Esparza","Rose Namajunas","Claudia Gadelha","Jessica Andrade"], answer:"Carla Esparza", explanation:"Jedrzejczyk stopped Esparza at UFC 185.", sourceId:"ufc-strawweight-history" }),
  q({ id:"ufc-r1-khabib-final", league:"ufc", round:"round1", category:"Final Fights", prompt:"Who did Khabib Nurmagomedov defeat in his final professional fight?", choices:["Justin Gaethje","Dustin Poirier","Conor McGregor","Charles Oliveira"], answer:"Justin Gaethje", explanation:"Khabib submitted Justin Gaethje at UFC 254 and retired undefeated.", sourceId:"ufc254-history" }),
  q({ id:"ufc-r1-holloway-aldo", league:"ufc", round:"round1", category:"Championship Moments", prompt:"Max Holloway became undisputed featherweight champion by defeating whom?", choices:["Jose Aldo","Conor McGregor","Anthony Pettis","Frankie Edgar"], answer:"Jose Aldo", explanation:"Holloway stopped Aldo at UFC 212 to unify the featherweight title.", sourceId:"ufc-featherweight-history" }),
  q({ id:"ufc-r1-woodley-lawler", league:"ufc", round:"round1", category:"Title Changes", prompt:"Tyron Woodley won the UFC welterweight title by knocking out whom?", choices:["Robbie Lawler","Stephen Thompson","Carlos Condit","Rory MacDonald"], answer:"Robbie Lawler", explanation:"Woodley stopped Robbie Lawler in the first round at UFC 201.", sourceId:"ufc-welterweight-history" }),
  q({ id:"ufc-r1-nunes-tate", league:"ufc", round:"round1", category:"Title Changes", prompt:"Amanda Nunes won her first UFC title by defeating whom at UFC 200?", choices:["Miesha Tate","Ronda Rousey","Holly Holm","Valentina Shevchenko"], answer:"Miesha Tate", explanation:"Nunes submitted Miesha Tate to win the women's bantamweight title.", sourceId:"ufc200-history" }),
  q({ id:"ufc-r1-khabib-eagle", league:"ufc", round:"round1", category:"Nicknames", prompt:"Which undefeated UFC champion is known as 'The Eagle'?", choices:["Khabib Nurmagomedov","Islam Makhachev","Magomed Ankalaev","Khamzat Chimaev"], answer:"Khabib Nurmagomedov", explanation:"Khabib Nurmagomedov competed under the nickname 'The Eagle.'", sourceId:"ufc-athlete-khabib" }),
  q({ id:"ufc-r1-poatan", league:"ufc", round:"round1", category:"Nicknames", prompt:"Which two-division UFC champion is known as 'Poatan'?", choices:["Alex Pereira","Israel Adesanya","Jiri Prochazka","Glover Teixeira"], answer:"Alex Pereira", explanation:"Alex Pereira is known by the nickname Poatan.", sourceId:"ufc-athlete-pereira" }),
  q({ id:"ufc-r1-rocky-edwards", league:"ufc", round:"round1", category:"Nicknames", prompt:"Which former UFC welterweight champion is nicknamed 'Rocky'?", choices:["Leon Edwards","Robbie Lawler","Colby Covington","Belal Muhammad"], answer:"Leon Edwards", explanation:"Leon Edwards competes under the nickname Rocky.", sourceId:"ufc-athlete-edwards" }),

  // Round 2 — landmark cards and famous upsets
  q({ id:"ufc-r2-ufc194-two-title-changes", league:"ufc", round:"round2", category:"Milestone Events", prompt:"At UFC 194, Conor McGregor took Jose Aldo's featherweight title and which fighter took Chris Weidman's middleweight title?", choices:["Luke Rockhold","Michael Bisping","Yoel Romero","Jacare Souza"], answer:"Luke Rockhold", explanation:"Luke Rockhold stopped Chris Weidman in the co-main event of UFC 194.", sourceId:"ufc194-history" }),
  q({ id:"ufc-r2-ufc189-interim", league:"ufc", round:"round2", category:"Milestone Events", prompt:"Conor McGregor won an interim featherweight title at UFC 189 by defeating whom?", choices:["Chad Mendes","Jose Aldo","Max Holloway","Dustin Poirier"], answer:"Chad Mendes", explanation:"McGregor stopped Chad Mendes in the second round of UFC 189.", sourceId:"ufc189-history" }),
  q({ id:"ufc-r2-ufc202-main", league:"ufc", round:"round2", category:"Rivalries", prompt:"Which rematch headlined UFC 202?", choices:["Conor McGregor vs. Nate Diaz II","Jon Jones vs. Daniel Cormier II","Khabib Nurmagomedov vs. Conor McGregor","Dustin Poirier vs. Conor McGregor II"], answer:"Conor McGregor vs. Nate Diaz II", explanation:"McGregor won a majority decision over Diaz in their UFC 202 rematch.", sourceId:"ufc202-history" }),
  q({ id:"ufc-r2-ufc264-main", league:"ufc", round:"round2", category:"Rivalries", prompt:"Which trilogy fight headlined UFC 264?", choices:["Dustin Poirier vs. Conor McGregor III","Max Holloway vs. Alexander Volkanovski III","Stipe Miocic vs. Daniel Cormier III","Chuck Liddell vs. Randy Couture III"], answer:"Dustin Poirier vs. Conor McGregor III", explanation:"Poirier and McGregor met for the third time at UFC 264.", sourceId:"ufc264-history" }),
  q({ id:"ufc-r2-ufc280-lightweight", league:"ufc", round:"round2", category:"Championship Moments", prompt:"Who won the vacant lightweight title by submitting Charles Oliveira at UFC 280?", choices:["Islam Makhachev","Dustin Poirier","Justin Gaethje","Beneil Dariush"], answer:"Islam Makhachev", explanation:"Islam Makhachev submitted Oliveira to win the lightweight championship.", sourceId:"ufc280-history" }),
  q({ id:"ufc-r2-ufc284-champ-champ", league:"ufc", round:"round2", category:"Champ-vs-Champ", prompt:"Islam Makhachev defended the lightweight title at UFC 284 against which featherweight champion?", choices:["Alexander Volkanovski","Max Holloway","Ilia Topuria","Jose Aldo"], answer:"Alexander Volkanovski", explanation:"Volkanovski moved up to challenge Makhachev in Perth.", sourceId:"ufc284-history" }),
  q({ id:"ufc-r2-ufc300-bmf", league:"ufc", round:"round2", category:"Milestone Events", prompt:"Who won the BMF title with a last-second knockout of Justin Gaethje at UFC 300?", choices:["Max Holloway","Dustin Poirier","Charles Oliveira","Michael Chandler"], answer:"Max Holloway", explanation:"Holloway knocked Gaethje out at 4:59 of the fifth round.", sourceId:"ufc300-history" }),
  q({ id:"ufc-r2-ufc300-main", league:"ufc", round:"round2", category:"Milestone Events", prompt:"Which light heavyweight title fight headlined UFC 300?", choices:["Alex Pereira vs. Jamahal Hill","Alex Pereira vs. Jiri Prochazka","Jamahal Hill vs. Glover Teixeira","Jon Jones vs. Stipe Miocic"], answer:"Alex Pereira vs. Jamahal Hill", explanation:"Pereira knocked out Hill in the first round of the UFC 300 main event.", sourceId:"ufc300-history" }),
  q({ id:"ufc-r2-ufc306-sphere", league:"ufc", round:"round2", category:"Venues", prompt:"UFC 306 was staged inside which futuristic Las Vegas venue?", choices:["Sphere","Allegiant Stadium","T-Mobile Arena","MSG Sphere Theater"], answer:"Sphere", explanation:"UFC 306 became the promotion's landmark event inside Sphere in Las Vegas.", sourceId:"ufc306-history" }),
  q({ id:"ufc-r2-cormier-stipe", league:"ufc", round:"round2", category:"Champ-Champ Moments", prompt:"Daniel Cormier became a simultaneous two-division champion by knocking out which heavyweight champion?", choices:["Stipe Miocic","Fabricio Werdum","Cain Velasquez","Junior dos Santos"], answer:"Stipe Miocic", explanation:"Cormier knocked out Miocic at UFC 226 while already holding the light heavyweight title.", sourceId:"ufc226-history" }),
  q({ id:"ufc-r2-pena-nunes", league:"ufc", round:"round2", category:"Famous Upsets", prompt:"Who shocked Amanda Nunes to win the women's bantamweight title at UFC 269?", choices:["Julianna Pena","Holly Holm","Miesha Tate","Irene Aldana"], answer:"Julianna Pena", explanation:"Pena submitted Nunes in the second round.", sourceId:"ufc269-history" }),
  q({ id:"ufc-r2-strickland-adesanya", league:"ufc", round:"round2", category:"Famous Upsets", prompt:"Who upset Israel Adesanya to win the middleweight title at UFC 293?", choices:["Sean Strickland","Dricus du Plessis","Alex Pereira","Robert Whittaker"], answer:"Sean Strickland", explanation:"Strickland won a clear decision over Adesanya in Sydney.", sourceId:"ufc293-history" }),
  q({ id:"ufc-r2-edwards-usman", league:"ufc", round:"round2", category:"Iconic Finishes", prompt:"Leon Edwards won the welterweight title from Kamaru Usman with what strike?", choices:["Head kick","Flying knee","Spinning elbow","Uppercut"], answer:"Head kick", explanation:"Edwards landed a dramatic fifth-round head kick at UFC 278.", sourceId:"ufc278-history" }),
  q({ id:"ufc-r2-dillashaw-barao", league:"ufc", round:"round2", category:"Famous Upsets", prompt:"TJ Dillashaw won his first UFC title by upsetting which champion at UFC 173?", choices:["Renan Barao","Dominick Cruz","Urijah Faber","Cody Garbrandt"], answer:"Renan Barao", explanation:"Dillashaw dominated and stopped Barao in one of the era's biggest title upsets.", sourceId:"ufc173-history" }),
  q({ id:"ufc-r2-miocic-werdum", league:"ufc", round:"round2", category:"Title Changes", prompt:"Stipe Miocic won his first UFC heavyweight title by knocking out whom in Brazil?", choices:["Fabricio Werdum","Junior dos Santos","Cain Velasquez","Alistair Overeem"], answer:"Fabricio Werdum", explanation:"Miocic knocked out Werdum at UFC 198 in Curitiba.", sourceId:"ufc198-history" }),

  // Round 3 — deeper event and rivalry history
  q({ id:"ufc-r3-serra-upset-event", league:"ufc", round:"round3", category:"Famous Upsets", prompt:"Matt Serra's shocking title win over Georges St-Pierre happened at which event?", choices:["UFC 69","UFC 65","UFC 74","UFC 83"], answer:"UFC 69", explanation:"Serra stopped St-Pierre in the first round at UFC 69.", sourceId:"ufc69-history" }),
  q({ id:"ufc-r3-weidman-upset-event", league:"ufc", round:"round3", category:"Famous Upsets", prompt:"Chris Weidman ended Anderson Silva's title reign at which event?", choices:["UFC 162","UFC 168","UFC 148","UFC 159"], answer:"UFC 162", explanation:"Weidman knocked Silva out in the second round at UFC 162.", sourceId:"ufc162-history" }),
  q({ id:"ufc-r3-couture-sylvia-return", league:"ufc", round:"round3", category:"Comebacks", prompt:"Which heavyweight champion did 43-year-old Randy Couture beat after coming out of retirement at UFC 68?", choices:["Tim Sylvia","Andrei Arlovski","Frank Mir","Gabriel Gonzaga"], answer:"Tim Sylvia", explanation:"Couture returned from a year-long retirement and dominated Tim Sylvia over five rounds to regain the heavyweight title.", sourceId:"ufc-couture-sylvia-68", sourceUrl:"https://www.ufc.com/news/randy-couture-magnificent-seven" }),
  q({ id:"ufc-r3-cejudo-dj-event", league:"ufc", round:"round3", category:"Title Changes", prompt:"Henry Cejudo ended Demetrious Johnson's flyweight reign at which event?", choices:["UFC 227","UFC 218","UFC 225","UFC 232"], answer:"UFC 227", explanation:"Cejudo won a split decision at UFC 227.", sourceId:"ufc227-history" }),
  q({ id:"ufc-r3-pena-nunes-rematch", league:"ufc", round:"round3", category:"Rivalries", prompt:"Amanda Nunes regained the bantamweight title from Julianna Pena at which event?", choices:["UFC 277","UFC 269","UFC 280","UFC 275"], answer:"UFC 277", explanation:"Nunes won a dominant decision in their rematch.", sourceId:"ufc277-history" }),
  q({ id:"ufc-r3-miocic-dc-regain", league:"ufc", round:"round3", category:"Rivalries", prompt:"Stipe Miocic regained the heavyweight title from Daniel Cormier at which event?", choices:["UFC 241","UFC 226","UFC 252","UFC 220"], answer:"UFC 241", explanation:"Miocic stopped Cormier in the fourth round of their rematch.", sourceId:"ufc241-history" }),
  q({ id:"ufc-r3-miocic-dc-trilogy", league:"ufc", round:"round3", category:"Rivalries", prompt:"Which event hosted the deciding third fight between Stipe Miocic and Daniel Cormier?", choices:["UFC 252","UFC 241","UFC 226","UFC 260"], answer:"UFC 252", explanation:"Miocic won a decision at UFC 252 to take the trilogy 2–1.", sourceId:"ufc252-history" }),
  q({ id:"ufc-r3-topuria-volkanovski", league:"ufc", round:"round3", category:"Title Changes", prompt:"Ilia Topuria won the featherweight title by knocking out Alexander Volkanovski at which event?", choices:["UFC 298","UFC 300","UFC 294","UFC 290"], answer:"UFC 298", explanation:"Topuria stopped Volkanovski in the second round at UFC 298.", sourceId:"ufc298-history" }),
  q({ id:"ufc-r3-du-plessis-first-sa", league:"ufc", round:"round3", category:"Global Firsts", prompt:"Who became the first South African UFC champion?", choices:["Dricus du Plessis","Cameron Saaiman","Trevor Prangley","Ruan Potts"], answer:"Dricus du Plessis", explanation:"Du Plessis won the middleweight championship at UFC 297.", sourceId:"ufc297-history" }),
  q({ id:"ufc-r3-du-plessis-strickland", league:"ufc", round:"round3", category:"Title Changes", prompt:"Dricus du Plessis won the middleweight title from whom at UFC 297?", choices:["Sean Strickland","Israel Adesanya","Robert Whittaker","Alex Pereira"], answer:"Sean Strickland", explanation:"Du Plessis won a split decision over Strickland.", sourceId:"ufc297-history" }),
  q({ id:"ufc-r3-ufc278-round", league:"ufc", round:"round3", category:"Iconic Finishes", prompt:"Leon Edwards' title-winning head kick against Kamaru Usman came in which round?", choices:["Fifth","Fourth","Third","Second"], answer:"Fifth", explanation:"Edwards landed the knockout with less than a minute left in round five.", sourceId:"ufc278-history" }),
  q({ id:"ufc-r3-ufc300-holloway-time", league:"ufc", round:"round3", category:"Iconic Finishes", prompt:"Max Holloway knocked out Justin Gaethje with how much time left at UFC 300?", choices:["One second","Five seconds","Ten seconds","Thirty seconds"], answer:"One second", explanation:"The official stoppage came at 4:59 of round five.", sourceId:"ufc300-history" }),
  q({ id:"ufc-r3-ufc194-aldo-time", league:"ufc", round:"round3", category:"Iconic Finishes", prompt:"How quickly did Conor McGregor knock out Jose Aldo at UFC 194?", choices:["13 seconds","5 seconds","21 seconds","48 seconds"], answer:"13 seconds", explanation:"McGregor's left hand ended Aldo's long featherweight reign in 13 seconds.", sourceId:"ufc194-history" }),
  q({ id:"ufc-r3-ufc207-nunes-rousey", league:"ufc", round:"round3", category:"Iconic Finishes", prompt:"Amanda Nunes stopped Ronda Rousey in how many seconds at UFC 207?", choices:["48 seconds","13 seconds","59 seconds","1:32"], answer:"48 seconds", explanation:"Nunes overwhelmed Rousey in 48 seconds.", sourceId:"ufc207-history" }),
  q({ id:"ufc-r3-ufc200-nunes-method", league:"ufc", round:"round3", category:"Championship Moments", prompt:"How did Amanda Nunes finish Miesha Tate to win the title at UFC 200?", choices:["Rear-naked choke","Knockout","Armbar","Decision"], answer:"Rear-naked choke", explanation:"Nunes hurt Tate with strikes and then secured a rear-naked choke.", sourceId:"ufc200-history" }),
  q({ id:"ufc-r3-ufc262-oliveira-round", league:"ufc", round:"round3", category:"Championship Moments", prompt:"Charles Oliveira stopped Michael Chandler in which round to win the vacant lightweight title?", choices:["Second","First","Third","Fourth"], answer:"Second", explanation:"Oliveira rallied from a difficult first round and stopped Chandler early in round two.", sourceId:"ufc262-history" }),
  q({ id:"ufc-r3-ufc280-makhachev-method", league:"ufc", round:"round3", category:"Championship Moments", prompt:"How did Islam Makhachev finish Charles Oliveira to win the lightweight title?", choices:["Arm-triangle choke","Rear-naked choke","Head-kick knockout","Decision"], answer:"Arm-triangle choke", explanation:"Makhachev submitted Oliveira with an arm-triangle in round two.", sourceId:"ufc280-history" }),
  q({ id:"ufc-r3-ufc226-dc-round", league:"ufc", round:"round3", category:"Champ-Champ Moments", prompt:"Daniel Cormier knocked out Stipe Miocic in which round at UFC 226?", choices:["First","Second","Third","Fourth"], answer:"First", explanation:"Cormier landed a short right hand in the clinch late in round one.", sourceId:"ufc226-history" }),
  q({ id:"ufc-r3-ufc198-city", league:"ufc", round:"round3", category:"International History", prompt:"Stipe Miocic won the heavyweight title from Fabricio Werdum in which Brazilian city?", choices:["Curitiba","Rio de Janeiro","Sao Paulo","Brasilia"], answer:"Curitiba", explanation:"UFC 198 took place at Arena da Baixada in Curitiba.", sourceId:"ufc198-history" }),
  q({ id:"ufc-r3-ufc306-main", league:"ufc", round:"round3", category:"Milestone Events", prompt:"Which bantamweight title fight headlined the UFC's Sphere event, UFC 306?", choices:["Sean O'Malley vs. Merab Dvalishvili","Sean O'Malley vs. Marlon Vera","Merab Dvalishvili vs. Petr Yan","Aljamain Sterling vs. Sean O'Malley"], answer:"Sean O'Malley vs. Merab Dvalishvili", explanation:"Dvalishvili defeated O'Malley to win the bantamweight title in the Sphere main event.", sourceId:"ufc306-history" }),

  // Last Call
  q({ id:"ufc-final-ufc194-main-seconds", league:"ufc", round:"last-call", category:"Iconic Finishes", prompt:"What was the official time of Conor McGregor's title-winning knockout of Jose Aldo?", choices:["0:13","0:05","0:21","0:48"], answer:"0:13", explanation:"McGregor's 13-second knockout remains one of UFC's most famous finishes.", sourceId:"ufc194-history" }),
  q({ id:"ufc-final-ufc278-kick-round", league:"ufc", round:"last-call", category:"Iconic Finishes", prompt:"Leon Edwards' famous head-kick knockout of Kamaru Usman came in which round?", choices:["Round 5","Round 4","Round 3","Round 2"], answer:"Round 5", explanation:"Edwards captured the welterweight title late in the fifth round at UFC 278.", sourceId:"ufc278-history" }),
  q({ id:"ufc-final-ufc300-bmf-time", league:"ufc", round:"last-call", category:"Milestone Events", prompt:"At what official time did Max Holloway knock out Justin Gaethje at UFC 300?", choices:["4:59 of Round 5","4:55 of Round 5","0:13 of Round 1","2:47 of Round 3"], answer:"4:59 of Round 5", explanation:"Holloway scored the knockout with one second remaining in the fight.", sourceId:"ufc300-history" }),
  q({ id:"ufc-final-jones-hamill-dq", league:"ufc", round:"last-call", category:"Weird History", prompt:"Jon Jones' lone official UFC loss came by disqualification against which fighter?", choices:["Matt Hamill","Alexander Gustafsson","Daniel Cormier","Ovince Saint Preux"], answer:"Matt Hamill", explanation:"Jones was disqualified against Matt Hamill in 2009 after landing illegal downward elbows.", sourceId:"ufc-jones-hamill-dq", sourceUrl:"https://www.ufc.com/news/jones-dqed-against-hamill-kimbo-outpoints-alexander" }),
  q({ id:"ufc-final-ufc205-opponent", league:"ufc", round:"last-call", category:"Champ-Champ History", prompt:"Whom did Conor McGregor defeat to become the UFC's first simultaneous two-division champion?", choices:["Eddie Alvarez","Jose Aldo","Nate Diaz","Chad Mendes"], answer:"Eddie Alvarez", explanation:"McGregor stopped Alvarez at UFC 205 to hold featherweight and lightweight gold simultaneously.", sourceId:"ufc205-history" }),
];
