import { barTriviaQuestion, type BarTriviaQuestion } from "../games/barTriviaEngine";

const UFC30 = "https://www.ufc.com/30";
const FAST = "https://www.ufc.com/news/fast-facts-our-20th-anniversary";
const GLOVE = "https://www.ufc.com/authentic-fight-glove";
const TOP500 = "https://www.ufc.com/news/top-500-ufc-moments-list";
const UFC4 = "https://www.ufc.com/event/ufc-4";
const UFC5 = "https://www.ufc.com/event/ufc-5";
const UFC6 = "https://www.ufc.com/event/ufc-6";
const OLEG = "https://www.ufc.com/news/oleg-taktarovs-greatest-hits";
const UFC38 = "https://www.ufc.com/news/first-ufc-event-uk-ufc-38-brawl-hall-hughes-newton-london";

function q(seed: Parameters<typeof barTriviaQuestion>[0]) {
  return barTriviaQuestion({ ...seed, verifiedAt: "2026-09-28" });
}

export const BAR_TRIVIA_UFC_EVERGREEN_WAVE_6: readonly BarTriviaQuestion[] = [
  // Round 1 — old-school visual oddities and firsts
  q({ id:"ufc-r1-jimmerson-one-glove", league:"ufc", round:"round1", category:"Old-School UFC", prompt:"Which UFC 1 fighter famously entered the Octagon wearing one boxing glove?", choices:["Art Jimmerson","Gerard Gordeau","Ken Shamrock","Kevin Rosier"], answer:"Art Jimmerson", explanation:"Professional boxer Art Jimmerson wore one red boxing glove against Royce Gracie at UFC 1.", sourceId:"ufc-glove-history", sourceUrl:GLOVE }),
  q({ id:"ufc-r1-abbott-fingerless", league:"ufc", round:"round1", category:"Equipment History", prompt:"Who was the first UFC fighter to wear protective fingerless gloves in competition?", choices:["Tank Abbott","Royce Gracie","Ken Shamrock","Mark Coleman"], answer:"Tank Abbott", explanation:"UFC's historical timeline credits Tank Abbott with wearing protective fingerless gloves at UFC 6.", sourceId:"ufc-top500", sourceUrl:TOP500 }),
  q({ id:"ufc-r1-first-headkick-ko", league:"ufc", round:"round1", category:"UFC Firsts", prompt:"Who scored the first head-kick knockout in UFC history?", choices:["Gerard Gordeau","Vitor Belfort","Maurice Smith","Marco Ruas"], answer:"Gerard Gordeau", explanation:"Gordeau stopped sumo wrestler Teila Tuli with the first head-kick knockout at UFC 1.", sourceId:"ufc-fast-facts", sourceUrl:FAST }),
  q({ id:"ufc-r1-first-170-fight", league:"ufc", round:"round1", category:"Division Firsts", prompt:"The first UFC fight contested at 170 pounds featured Laverne Clark against whom?", choices:["Josh Stewart","Pat Miletich","Mikey Burnett","Frank Trigg"], answer:"Josh Stewart", explanation:"UFC's Fast Facts lists Laverne Clark vs. Josh Stewart at UFC 16 as the first 170-pound fight.", sourceId:"ufc-fast-facts", sourceUrl:FAST }),
  q({ id:"ufc-r1-first-155-fight", league:"ufc", round:"round1", category:"Division Firsts", prompt:"Jens Pulver fought whom in the UFC's first 155-pound bout?", choices:["Joao Roque","Caol Uno","BJ Penn","John Lewis"], answer:"Joao Roque", explanation:"Pulver vs. Joao Roque at UFC 26 is listed as UFC's first 155-pound fight.", sourceId:"ufc-fast-facts", sourceUrl:FAST }),
  q({ id:"ufc-r1-first-145-fight", league:"ufc", round:"round1", category:"Division Firsts", prompt:"The UFC's first 145-pound bout featured Pablo Garza against whom?", choices:["Fredson Paixao","Mark Hominick","Diego Nunes","Josh Grispi"], answer:"Fredson Paixao", explanation:"Their fight at The Ultimate Fighter 12 Finale was UFC's first at 145 pounds.", sourceId:"ufc-fast-facts", sourceUrl:FAST }),
  q({ id:"ufc-r1-first-135-fight", league:"ufc", round:"round1", category:"Division Firsts", prompt:"The UFC's first 135-pound bout featured Nick Pace against whom?", choices:["Will Campuzano","Demetrious Johnson","John Dodson","Urijah Faber"], answer:"Will Campuzano", explanation:"Nick Pace vs. Will Campuzano at the TUF 12 Finale was UFC's first bantamweight bout.", sourceId:"ufc-fast-facts", sourceUrl:FAST }),
  q({ id:"ufc-r1-first-125-fight", league:"ufc", round:"round1", category:"Division Firsts", prompt:"The UFC's first flyweight bout featured Demetrious Johnson against whom?", choices:["Ian McCall","Joseph Benavidez","John Dodson","Chris Cariaso"], answer:"Ian McCall", explanation:"Ian McCall vs. Demetrious Johnson at UFC on FX 2 was UFC's first 125-pound fight.", sourceId:"ufc-fast-facts", sourceUrl:FAST }),
  q({ id:"ufc-r1-first-uk", league:"ufc", round:"round1", category:"International History", prompt:"Which numbered event was UFC's first show in the United Kingdom?", choices:["UFC 38","UFC 70","UFC 75","UFC 85"], answer:"UFC 38", explanation:"UFC 38: Brawl at the Hall took place in London in 2002.", sourceId:"ufc38-history", sourceUrl:UFC38 }),
  q({ id:"ufc-r1-gonzaga-crocop", league:"ufc", round:"round1", category:"Iconic Finishes", prompt:"Who shocked Mirko Cro Cop by knocking him out with a head kick at UFC 70?", choices:["Gabriel Gonzaga","Fabricio Werdum","Frank Mir","Junior dos Santos"], answer:"Gabriel Gonzaga", explanation:"Gonzaga turned Cro Cop's signature weapon against him with a first-round head-kick knockout in Manchester.", sourceId:"ufc70-gonzaga-crocop", sourceUrl:"https://www.ufc.com/news/on-this-day-ufc-history-mirko-cro-cop-gets-cro-gabriel-gonzaga" }),
  q({ id:"ufc-r1-first-network-tv", league:"ufc", round:"round1", category:"Broadcast History", prompt:"Which two heavyweights fought in UFC's first bout broadcast live on U.S. network television?", choices:["Cain Velasquez and Junior dos Santos","Brock Lesnar and Frank Mir","Randy Couture and Chuck Liddell","Stipe Miocic and Daniel Cormier"], answer:"Cain Velasquez and Junior dos Santos", explanation:"Their 2011 heavyweight title fight launched UFC on FOX.", sourceId:"ufc-fox-history" }),
  q({ id:"ufc-r1-fox-first-winner", league:"ufc", round:"round1", category:"Broadcast History", prompt:"Who won the UFC's first fight broadcast live on FOX?", choices:["Junior dos Santos","Cain Velasquez","Benson Henderson","Clay Guida"], answer:"Junior dos Santos", explanation:"Dos Santos knocked out Cain Velasquez to win the heavyweight title.", sourceId:"ufc-fox-history" }),
  q({ id:"ufc-r1-ufc3-winner", league:"ufc", round:"round1", category:"Tournament Era", prompt:"Who won the unusual UFC 3 tournament after entering as an alternate?", choices:["Steve Jennum","Royce Gracie","Ken Shamrock","Kimo Leopoldo"], answer:"Steve Jennum", explanation:"Police officer Steve Jennum entered late and won the UFC 3 tournament after only one fight.", sourceId:"ufc3-history" }),
  q({ id:"ufc-r1-ufc4-winner", league:"ufc", round:"round1", category:"Tournament Era", prompt:"Who won the UFC 4 tournament?", choices:["Royce Gracie","Dan Severn","Ken Shamrock","Oleg Taktarov"], answer:"Royce Gracie", explanation:"Royce Gracie submitted Dan Severn in the UFC 4 final.", sourceId:"ufc4", sourceUrl:UFC4 }),
  q({ id:"ufc-r1-ufc6-winner", league:"ufc", round:"round1", category:"Tournament Era", prompt:"Who won the UFC 6 tournament?", choices:["Oleg Taktarov","Tank Abbott","Ken Shamrock","Dan Severn"], answer:"Oleg Taktarov", explanation:"Taktarov submitted Tank Abbott in the UFC 6 tournament final.", sourceId:"ufc6", sourceUrl:UFC6 }),

  // Round 2 — early tournament chaos and rule evolution
  q({ id:"ufc-r2-ufc4-final", league:"ufc", round:"round2", category:"Tournament Era", prompt:"Royce Gracie defeated whom in the UFC 4 tournament final?", choices:["Dan Severn","Ken Shamrock","Keith Hackney","Ron Van Clief"], answer:"Dan Severn", explanation:"Gracie submitted Severn after more than 15 minutes to win UFC 4.", sourceId:"ufc4", sourceUrl:UFC4 }),
  q({ id:"ufc-r2-ufc5-winner", league:"ufc", round:"round2", category:"Tournament Era", prompt:"Who won the UFC 5 tournament?", choices:["Dan Severn","Oleg Taktarov","Dave Beneteau","Ken Shamrock"], answer:"Dan Severn", explanation:"Dan Severn submitted Dave Beneteau in the UFC 5 tournament final.", sourceId:"ufc5", sourceUrl:UFC5 }),
  q({ id:"ufc-r2-ufc5-superfight", league:"ufc", round:"round2", category:"Early UFC", prompt:"The UFC 5 Superfight between Royce Gracie and Ken Shamrock ended how?", choices:["Draw","Gracie submission","Shamrock decision","Doctor stoppage"], answer:"Draw", explanation:"Gracie and Shamrock fought to a draw in the long UFC 5 Superfight.", sourceId:"ufc5", sourceUrl:UFC5 }),
  q({ id:"ufc-r2-ufc6-final", league:"ufc", round:"round2", category:"Tournament Era", prompt:"Oleg Taktarov defeated whom in the UFC 6 tournament final?", choices:["Tank Abbott","Dan Severn","Ken Shamrock","Dave Beneteau"], answer:"Tank Abbott", explanation:"Taktarov submitted Tank Abbott to win UFC 6.", sourceId:"ufc6", sourceUrl:UFC6 }),
  q({ id:"ufc-r2-ufc6-fastest-sub", league:"ufc", round:"round2", category:"Iconic Records", prompt:"Oleg Taktarov set a UFC submission record by finishing Anthony Macias in how many seconds?", choices:["9","5","13","18"], answer:"9", explanation:"Taktarov submitted Macias in nine seconds at UFC 6.", sourceId:"oleg-taktarov", sourceUrl:OLEG }),
  q({ id:"ufc-r2-gloves-mandatory", league:"ufc", round:"round2", category:"Rules History", prompt:"At which event did UFC mandate standard fight gloves?", choices:["UFC 14","UFC 9","UFC 12","UFC 18"], answer:"UFC 14", explanation:"Boxergenics gloves first appeared at UFC 9 and became mandatory at UFC 14.", sourceId:"ufc-glove-history", sourceUrl:GLOVE }),
  q({ id:"ufc-r2-gloves-first-appearance", league:"ufc", round:"round2", category:"Equipment History", prompt:"Standard MMA-style gloves first appeared in UFC competition at which event?", choices:["UFC 9","UFC 14","UFC 6","UFC 12"], answer:"UFC 9", explanation:"UFC's glove history notes Boxergenics gloves first appeared at UFC 9.", sourceId:"ufc-glove-history", sourceUrl:GLOVE }),
  q({ id:"ufc-r2-unified-rules-first", league:"ufc", round:"round2", category:"Rules History", prompt:"Which event was the first UFC show held under the Unified Rules of MMA?", choices:["UFC 28","UFC 30","UFC 21","UFC 33"], answer:"UFC 28", explanation:"UFC 28 in November 2000 is treated as the start of the modern rules era.", sourceId:"ufc30-history", sourceUrl:UFC30 }),
  q({ id:"ufc-r2-last-bare-knuckle", league:"ufc", round:"round2", category:"Old-School UFC", prompt:"Which bout is listed by UFC as its last bare-knuckle fight?", choices:["Randy Couture vs. Steven Graham","Royce Gracie vs. Dan Severn","Mark Coleman vs. Maurice Smith","Tank Abbott vs. Oleg Taktarov"], answer:"Randy Couture vs. Steven Graham", explanation:"UFC's Fast Facts lists their UFC 13 bout as the last bare-knuckle fight.", sourceId:"ufc-fast-facts", sourceUrl:FAST }),
  q({ id:"ufc-r2-last-no-weightclasses", league:"ufc", round:"round2", category:"Rules History", prompt:"What was the last UFC event held without weight classes?", choices:["Ultimate Ultimate '96","UFC 12","UFC 10","UFC 14"], answer:"Ultimate Ultimate '96", explanation:"UFC's Fast Facts identifies Ultimate Ultimate '96 as the last event without weight classes.", sourceId:"ufc-fast-facts", sourceUrl:FAST }),
  q({ id:"ufc-r2-last-one-night-tourney", league:"ufc", round:"round2", category:"Tournament Era", prompt:"Which event hosted the UFC's last one-night tournament?", choices:["UFC 23: Ultimate Japan 2","UFC 17","UFC 20","UFC 25"], answer:"UFC 23: Ultimate Japan 2", explanation:"UFC's Fast Facts lists UFC 23 as the final one-night tournament.", sourceId:"ufc-fast-facts", sourceUrl:FAST }),
  q({ id:"ufc-r2-sterling-yan-dq", league:"ufc", round:"round2", category:"Strange Rulings", prompt:"Who won the UFC bantamweight title by disqualification after Petr Yan landed an illegal knee at UFC 259?", choices:["Aljamain Sterling","Cory Sandhagen","Henry Cejudo","Marlon Moraes"], answer:"Aljamain Sterling", explanation:"Yan was disqualified for an illegal knee to the grounded Sterling, causing the bantamweight title to change hands.", sourceId:"ufc259-sterling-yan", sourceUrl:"https://www.ufc.com/news/petr-yan-a-class-of-his-own-aljamain-sterling-interim-ufc-bantamweight-champion" }),
  q({ id:"ufc-r2-ufc38-main", league:"ufc", round:"round2", category:"Milestone Events", prompt:"Which welterweight title rematch headlined UFC 38, the first UFC event in the UK?", choices:["Matt Hughes vs. Carlos Newton","Matt Hughes vs. Frank Trigg","Georges St-Pierre vs. Matt Hughes","BJ Penn vs. Matt Hughes"], answer:"Matt Hughes vs. Carlos Newton", explanation:"Hughes defended the welterweight title against Carlos Newton in London.", sourceId:"ufc38-history", sourceUrl:UFC38 }),
  q({ id:"ufc-r2-ufc-japan-city", league:"ufc", round:"round2", category:"International History", prompt:"UFC Japan: Ultimate Japan was held in which city?", choices:["Yokohama","Tokyo","Osaka","Saitama"], answer:"Yokohama", explanation:"UFC's first event in Asia was staged in Yokohama in December 1997.", sourceId:"ufc30-history", sourceUrl:UFC30 }),
  q({ id:"ufc-r2-sakuraba-ufc-tourney", league:"ufc", round:"round2", category:"Tournament Era", prompt:"Which future PRIDE legend won the UFC Japan heavyweight tournament in 1997?", choices:["Kazushi Sakuraba","Wanderlei Silva","Kazuo Misaki","Hidehiko Yoshida"], answer:"Kazushi Sakuraba", explanation:"Sakuraba won the Ultimate Japan tournament before becoming a PRIDE icon.", sourceId:"ufc-sakuraba-history" }),

  // Round 3 — deep oddities from UFC's own historical ledger
  q({ id:"ufc-r3-last-headbutt", league:"ufc", round:"round3", category:"Rules Oddities", prompt:"UFC lists which fighter as landing the last legal headbutt before the technique was banned?", choices:["Mark Coleman","Tank Abbott","Ken Shamrock","Randy Couture"], answer:"Mark Coleman", explanation:"UFC's Fast Facts cites Coleman vs. Maurice Smith at UFC 14 as the last legal headbutt.", sourceId:"ufc-fast-facts", sourceUrl:FAST }),
  q({ id:"ufc-r3-last-groin-shot", league:"ufc", round:"round3", category:"Rules Oddities", prompt:"UFC's last legal groin strike came at which event?", choices:["UFC 12","UFC 14","UFC 10","UFC 16"], answer:"UFC 12", explanation:"Fast Facts lists Kazuo Takahashi vs. Wallid Ismail at UFC 12 as the last legal groin shot.", sourceId:"ufc-fast-facts", sourceUrl:FAST }),
  q({ id:"ufc-r3-last-shoes", league:"ufc", round:"round3", category:"Equipment Oddities", prompt:"At which event did the last UFC fighter compete wearing shoes?", choices:["UFC 30","UFC 28","UFC 33","UFC 25"], answer:"UFC 30", explanation:"Mark Robinson is listed as the last fighter to wear shoes, at UFC 30.", sourceId:"ufc-fast-facts", sourceUrl:FAST }),
  q({ id:"ufc-r3-last-gi", league:"ufc", round:"round3", category:"Equipment Oddities", prompt:"At which event did the last UFC fighter compete wearing a gi?", choices:["UFC 18","UFC 14","UFC 22","UFC 30"], answer:"UFC 18", explanation:"Frank Caracci vs. Laverne Clark at UFC 18 is listed as the last UFC bout featuring a gi-clad fighter.", sourceId:"ufc-fast-facts", sourceUrl:FAST }),
  q({ id:"ufc-r3-last-down-knees", league:"ufc", round:"round3", category:"Rules Oddities", prompt:"The last legal knees to the head of a downed UFC fighter occurred at which event?", choices:["UFC 14","UFC 12","UFC 18","UFC 21"], answer:"UFC 14", explanation:"Fast Facts cites Mark Kerr vs. Moti Horenstein at UFC 14.", sourceId:"ufc-fast-facts", sourceUrl:FAST }),
  q({ id:"ufc-r3-first-wheel-kick-ko", league:"ufc", round:"round3", category:"Iconic Finishes", prompt:"Who scored the first wheel-kick knockout in UFC history?", choices:["Edson Barboza","Stephen Thompson","Vitor Belfort","Yair Rodriguez"], answer:"Edson Barboza", explanation:"Barboza knocked out Terry Etim with a spinning wheel kick at UFC 142.", sourceId:"ufc-fast-facts", sourceUrl:FAST }),
  q({ id:"ufc-r3-double-ko", league:"ufc", round:"round3", category:"Fight Oddities", prompt:"Which two fighters produced UFC's famous double-knockout/no-contest at The Ultimate Fighter 5 Finale?", choices:["Gray Maynard and Rob Emerson","Nate Diaz and Manny Gamburyan","Joe Lauzon and Cole Miller","Roger Huerta and Doug Evans"], answer:"Gray Maynard and Rob Emerson", explanation:"Both men were unable to continue after Maynard's slam sequence, producing one of UFC's strangest results.", sourceId:"ufc-fast-facts", sourceUrl:FAST }),
  q({ id:"ufc-r3-first-170-event", league:"ufc", round:"round3", category:"Division Firsts", prompt:"The first UFC fight at 170 pounds occurred at which event?", choices:["UFC 16","UFC 18","UFC 14","UFC 20"], answer:"UFC 16", explanation:"Laverne Clark vs. Josh Stewart at UFC 16 was UFC's first 170-pound bout.", sourceId:"ufc-fast-facts", sourceUrl:FAST }),
  q({ id:"ufc-r3-first-155-event", league:"ufc", round:"round3", category:"Division Firsts", prompt:"The first UFC fight at 155 pounds occurred at which event?", choices:["UFC 26","UFC 30","UFC 28","UFC 24"], answer:"UFC 26", explanation:"Jens Pulver vs. Joao Roque at UFC 26 was the first UFC 155-pound fight.", sourceId:"ufc-fast-facts", sourceUrl:FAST }),
  q({ id:"ufc-r3-first-145-event", league:"ufc", round:"round3", category:"Division Firsts", prompt:"The UFC's first 145-pound fight took place on which event?", choices:["The Ultimate Fighter 12 Finale","UFC 125","UFC 129","WEC 53"], answer:"The Ultimate Fighter 12 Finale", explanation:"Pablo Garza vs. Fredson Paixao opened UFC's featherweight era.", sourceId:"ufc-fast-facts", sourceUrl:FAST }),
  q({ id:"ufc-r3-first-135-event", league:"ufc", round:"round3", category:"Division Firsts", prompt:"The UFC's first 135-pound fight took place on which event?", choices:["The Ultimate Fighter 12 Finale","UFC 125","UFC 126","WEC 53"], answer:"The Ultimate Fighter 12 Finale", explanation:"Nick Pace vs. Will Campuzano was UFC's first bantamweight bout.", sourceId:"ufc-fast-facts", sourceUrl:FAST }),
  q({ id:"ufc-r3-first-125-event", league:"ufc", round:"round3", category:"Division Firsts", prompt:"The UFC's first 125-pound fight took place at which event?", choices:["UFC on FX 2","UFC 152","UFC on Fox 4","TUF 14 Finale"], answer:"UFC on FX 2", explanation:"Ian McCall and Demetrious Johnson met in UFC's first flyweight bout.", sourceId:"ufc-fast-facts", sourceUrl:FAST }),
  q({ id:"ufc-r3-last-no-time-limit", league:"ufc", round:"round3", category:"Rules History", prompt:"Which famous fight is listed as UFC's last bout without a time limit?", choices:["Royce Gracie vs. Dan Severn","Royce Gracie vs. Ken Shamrock II","Oleg Taktarov vs. Tank Abbott","Ken Shamrock vs. Dan Severn"], answer:"Royce Gracie vs. Dan Severn", explanation:"Their UFC 4 tournament final is listed as UFC's last fight without a time limit.", sourceId:"ufc-fast-facts", sourceUrl:FAST }),
  q({ id:"ufc-r3-gracie-severn-time", league:"ufc", round:"round3", category:"Tournament Era", prompt:"Royce Gracie's UFC 4 final submission of Dan Severn came after roughly how long?", choices:["15 minutes 49 seconds","5 minutes 32 seconds","21 minutes","9 minutes 30 seconds"], answer:"15 minutes 49 seconds", explanation:"The UFC 4 event record lists Gracie's submission at 15:49.", sourceId:"ufc4", sourceUrl:UFC4 }),
  q({ id:"ufc-r3-gracie-shamrock-36", league:"ufc", round:"round3", category:"Early UFC", prompt:"Royce Gracie and Ken Shamrock's UFC 5 Superfight lasted approximately how long?", choices:["36 minutes","25 minutes","18 minutes","45 minutes"], answer:"36 minutes", explanation:"Their marathon draw lasted more than 36 minutes including overtime.", sourceId:"ufc-top500", sourceUrl:TOP500 }),
  q({ id:"ufc-r3-oleg-macias-opponent", league:"ufc", round:"round3", category:"Iconic Records", prompt:"Oleg Taktarov's nine-second submission at UFC 6 came against whom?", choices:["Anthony Macias","Dave Beneteau","Tank Abbott","Paul Varelans"], answer:"Anthony Macias", explanation:"Taktarov submitted Anthony Macias in nine seconds.", sourceId:"oleg-taktarov", sourceUrl:OLEG }),
  q({ id:"ufc-r3-fox-finish-time", league:"ufc", round:"round3", category:"Broadcast History", prompt:"Junior dos Santos needed how long to stop Cain Velasquez in UFC's FOX debut?", choices:["64 seconds","13 seconds","2 minutes 34 seconds","48 seconds"], answer:"64 seconds", explanation:"Dos Santos knocked Velasquez out 64 seconds into the first round.", sourceId:"ufc-fox-history" }),
  q({ id:"ufc-r3-the-natural", league:"ufc", round:"round3", category:"Nicknames", prompt:"Which UFC Hall of Famer fought under the nickname \"The Natural\"?", choices:["Randy Couture","Dan Henderson","Mark Coleman","Chuck Liddell"], answer:"Randy Couture", explanation:"Randy Couture was known as \"The Natural\" across championship runs at heavyweight and light heavyweight.", sourceId:"ufc-couture-profile", sourceUrl:"https://www.ufc.com/athlete/randy-couture" }),
  q({ id:"ufc-r3-ufc-japan-year", league:"ufc", round:"round3", category:"International History", prompt:"UFC's first event in Asia took place in which year?", choices:["1997","1995","1999","2001"], answer:"1997", explanation:"UFC Japan: Ultimate Japan took place in December 1997.", sourceId:"ufc30-history", sourceUrl:UFC30 }),
  q({ id:"ufc-r3-ufc1-eight-man", league:"ufc", round:"round3", category:"Origins", prompt:"How many fighters were in the original UFC 1 tournament?", choices:["8","16","12","4"], answer:"8", explanation:"UFC 1 was an eight-man tournament in Denver.", sourceId:"ufc30-history", sourceUrl:UFC30 }),

  // Last Call
  q({ id:"ufc-final-jimmerson-glove-color", league:"ufc", round:"last-call", category:"Old-School UFC", prompt:"What color was the single boxing glove Art Jimmerson wore at UFC 1?", choices:["Red","Blue","Black","White"], answer:"Red", explanation:"UFC's official glove history describes Jimmerson's famous single glove as red.", sourceId:"ufc-glove-history", sourceUrl:GLOVE }),
  q({ id:"ufc-final-maine-iac", league:"ufc", round:"last-call", category:"Nicknames", prompt:"Which former two-time heavyweight champion was nicknamed \"The Maine-iac\"?", choices:["Tim Sylvia","Andrei Arlovski","Ricco Rodriguez","Josh Barnett"], answer:"Tim Sylvia", explanation:"The 6-foot-8 Tim Sylvia carried \"The Maine-iac\" nickname during his two UFC heavyweight title reigns.", sourceId:"ufc-sylvia-profile", sourceUrl:"https://www.ufc.com/athlete/tim-sylvia" }),
  q({ id:"ufc-final-lewis-volkov-quote", league:"ufc", round:"last-call", category:"Fight Culture", prompt:"Derrick Lewis delivered his famous \"my balls was hot\" interview after a last-second knockout of whom at UFC 229?", choices:["Alexander Volkov","Francis Ngannou","Curtis Blaydes","Travis Browne"], answer:"Alexander Volkov", explanation:"Lewis stopped Alexander Volkov with 11 seconds left, then delivered one of the UFC's most memorable post-fight interviews.", sourceId:"ufc229-lewis-volkov", sourceUrl:"https://www.ufc.com/news/top-500-ufc-moments-list" }),
  q({ id:"ufc-final-muscle-shark", league:"ufc", round:"last-call", category:"Nicknames", prompt:"Which former UFC lightweight champion was known as \"The Muscle Shark\"?", choices:["Sean Sherk","Jens Pulver","Frankie Edgar","Kenny Florian"], answer:"Sean Sherk", explanation:"Former lightweight champion Sean Sherk fought under the nickname \"The Muscle Shark.\"", sourceId:"ufc-sherk-profile", sourceUrl:"https://www.ufc.com/athlete/sean-sherk" }),
  q({ id:"ufc-final-barboza-etim", league:"ufc", round:"last-call", category:"Historic Knockouts", prompt:"Edson Barboza's first-in-UFC spinning wheel-kick knockout came against which opponent at UFC 142?", choices:["Terry Etim","Ross Pearson","Paul Felder","Anthony Njokuani"], answer:"Terry Etim", explanation:"Barboza knocked out Terry Etim with a spinning wheel kick, the first finish of its kind in UFC history.", sourceId:"ufc142-barboza-etim", sourceUrl:"https://www.ufc.com/news/edson-barbozas-ufc-career-highlights" }),
];
