import { barTriviaQuestion, type BarTriviaQuestion } from "../games/barTriviaEngine";

const UFC30 = "https://www.ufc.com/30";
const HOF = "https://www.ufc.com/news/ufc-hall-fame-faq";
const UFC193 = "https://www.ufc.com/news/ufc-193-rousey-vs-holm-final-results";
const UFC196 = "https://www.ufc.com/news/ufc-196-final-results-all-winners-and-news";
const HEAVYWEIGHT = "https://www.ufc.com/news/15-ufc-heavyweight-champions";
const CHAMPIONSHIP = "https://www.ufc.com/news/championship-matters";
const SILVA = "https://www.ufc.com/news/super-spider-anderson-silvas-defining-moments";
const TOP500 = "https://www.ufc.com/news/top-500-ufc-moments-list";

function q(seed: Parameters<typeof barTriviaQuestion>[0]) {
  return barTriviaQuestion({ ...seed, verifiedAt: "2026-09-28" });
}

export const BAR_TRIVIA_UFC_EVERGREEN_WAVE_2: readonly BarTriviaQuestion[] = [
  // Round 1
  q({ id:"ufc-r1-stylebender", league:"ufc", round:"round1", category:"Nicknames", prompt:"Which former UFC middleweight champion is known as 'The Last Stylebender'?", choices:["Israel Adesanya","Alex Pereira","Robert Whittaker","Paulo Costa"], answer:"Israel Adesanya", explanation:"Israel Adesanya has long competed under the nickname 'The Last Stylebender.'", sourceId:"ufc-athlete-adesanya" }),
  q({ id:"ufc-r1-diamond", league:"ufc", round:"round1", category:"Nicknames", prompt:"Which UFC veteran is known as 'The Diamond'?", choices:["Dustin Poirier","Justin Gaethje","Charles Oliveira","Michael Chandler"], answer:"Dustin Poirier", explanation:"Dustin Poirier's longtime nickname is 'The Diamond.'", sourceId:"ufc-athlete-poirier" }),
  q({ id:"ufc-r1-highlight", league:"ufc", round:"round1", category:"Nicknames", prompt:"Which action-heavy lightweight is known as 'The Highlight'?", choices:["Justin Gaethje","Dustin Poirier","Dan Hooker","Tony Ferguson"], answer:"Justin Gaethje", explanation:"Justin Gaethje competes under the nickname 'The Highlight.'", sourceId:"ufc-athlete-gaethje" }),
  q({ id:"ufc-r1-bullet", league:"ufc", round:"round1", category:"Nicknames", prompt:"Which former UFC flyweight champion is known as 'Bullet'?", choices:["Valentina Shevchenko","Joanna Jedrzejczyk","Rose Namajunas","Alexa Grasso"], answer:"Valentina Shevchenko", explanation:"Valentina Shevchenko's nickname is 'Bullet.'", sourceId:"ufc-athlete-shevchenko" }),
  q({ id:"ufc-r1-nigerian-nightmare", league:"ufc", round:"round1", category:"Nicknames", prompt:"Which former UFC welterweight champion is known as 'The Nigerian Nightmare'?", choices:["Kamaru Usman","Israel Adesanya","Leon Edwards","Tyron Woodley"], answer:"Kamaru Usman", explanation:"Kamaru Usman is known as 'The Nigerian Nightmare.'", sourceId:"ufc-athlete-usman" }),
  q({ id:"ufc-r1-iceman", league:"ufc", round:"round1", category:"Nicknames", prompt:"Which Hall of Fame light heavyweight is known as 'The Iceman'?", choices:["Chuck Liddell","Randy Couture","Tito Ortiz","Wanderlei Silva"], answer:"Chuck Liddell", explanation:"Chuck Liddell became one of the UFC's biggest early stars under the nickname 'The Iceman.'", sourceId:"ufc-hof-liddell", sourceUrl:HOF }),
  q({ id:"ufc-r1-natural", league:"ufc", round:"round1", category:"Nicknames", prompt:"Which UFC Hall of Famer is known as 'The Natural'?", choices:["Randy Couture","Dan Henderson","Matt Hughes","Rich Franklin"], answer:"Randy Couture", explanation:"Randy Couture's famous nickname is 'The Natural.'", sourceId:"ufc-hof-couture", sourceUrl:HOF }),
  q({ id:"ufc-r1-prodigy", league:"ufc", round:"round1", category:"Nicknames", prompt:"Which former two-division UFC champion is known as 'The Prodigy'?", choices:["BJ Penn","Georges St-Pierre","Frankie Edgar","Matt Hughes"], answer:"BJ Penn", explanation:"BJ Penn fought under the nickname 'The Prodigy.'", sourceId:"ufc-hof-penn", sourceUrl:HOF }),
  q({ id:"ufc-r1-lioness", league:"ufc", round:"round1", category:"Nicknames", prompt:"Which former two-division women's champion is known as 'The Lioness'?", choices:["Amanda Nunes","Cris Cyborg","Ronda Rousey","Holly Holm"], answer:"Amanda Nunes", explanation:"Amanda Nunes is known as 'The Lioness.'", sourceId:"ufc-athlete-nunes" }),
  q({ id:"ufc-r1-rowdy", league:"ufc", round:"round1", category:"Nicknames", prompt:"Which pioneer of UFC women's MMA fought under the nickname 'Rowdy'?", choices:["Ronda Rousey","Miesha Tate","Holly Holm","Cat Zingano"], answer:"Ronda Rousey", explanation:"Ronda Rousey used the nickname 'Rowdy,' with permission from the family of Roddy Piper.", sourceId:"ufc-hof-rousey", sourceUrl:HOF }),
  q({ id:"ufc-r1-gamebred", league:"ufc", round:"round1", category:"Nicknames", prompt:"Which fighter is known as 'Gamebred'?", choices:["Jorge Masvidal","Nate Diaz","Colby Covington","Ben Askren"], answer:"Jorge Masvidal", explanation:"Jorge Masvidal's nickname is 'Gamebred.'", sourceId:"ufc-athlete-masvidal" }),
  q({ id:"ufc-r1-wonderboy", league:"ufc", round:"round1", category:"Nicknames", prompt:"Which longtime welterweight contender is known as 'Wonderboy'?", choices:["Stephen Thompson","Carlos Condit","Donald Cerrone","Michael Page"], answer:"Stephen Thompson", explanation:"Stephen Thompson is widely known as 'Wonderboy.'", sourceId:"ufc-athlete-thompson" }),
  q({ id:"ufc-r1-holm-ronda", league:"ufc", round:"round1", category:"Famous Upsets", prompt:"Who handed Ronda Rousey her first professional loss at UFC 193?", choices:["Holly Holm","Miesha Tate","Amanda Nunes","Cat Zingano"], answer:"Holly Holm", explanation:"Holly Holm knocked out Rousey with a head kick to win the bantamweight title at UFC 193.", sourceId:"ufc-193-results", sourceUrl:UFC193 }),
  q({ id:"ufc-r1-diaz-mcgregor", league:"ufc", round:"round1", category:"Famous Upsets", prompt:"Who submitted Conor McGregor in their first meeting at UFC 196?", choices:["Nate Diaz","Dustin Poirier","Khabib Nurmagomedov","Jose Aldo"], answer:"Nate Diaz", explanation:"Nate Diaz submitted McGregor by rear-naked choke in the second round at UFC 196.", sourceId:"ufc-196-results", sourceUrl:UFC196 }),

  // Round 2
  q({ id:"ufc-r2-mcgregor-aldo-seconds", league:"ufc", round:"round2", category:"Iconic Finishes", prompt:"Conor McGregor knocked out Jose Aldo to win the featherweight title in how many seconds?", choices:["13","5","21","37"], answer:"13", explanation:"McGregor stopped Aldo in 13 seconds at UFC 194, the fastest finish in a UFC title fight at the time and still an iconic record.", sourceId:"ufc-194-aldo-mcgregor" }),
  q({ id:"ufc-r2-silva-sonnen-submission", league:"ufc", round:"round2", category:"Iconic Finishes", prompt:"Anderson Silva completed his famous comeback against Chael Sonnen at UFC 117 with which submission?", choices:["Triangle choke","Rear-naked choke","Guillotine","Armbar from mount"], answer:"Triangle choke", explanation:"Silva caught Sonnen in a fifth-round triangle choke/armbar after trailing for most of the fight.", sourceId:"ufc-silva-sonnen", sourceUrl:SILVA }),
  q({ id:"ufc-r2-silva-belfort-kick", league:"ufc", round:"round2", category:"Iconic Finishes", prompt:"Anderson Silva's famous knockout of Vitor Belfort came from what strike?", choices:["Front kick","Spinning back kick","Flying knee","Elbow"], answer:"Front kick", explanation:"Silva dropped Belfort with a front kick to the face at UFC 126.", sourceId:"ufc-silva-belfort" }),
  q({ id:"ufc-r2-first-heavyweight-champ", league:"ufc", round:"round2", category:"Championship Origins", prompt:"Who became the UFC's first heavyweight champion?", choices:["Mark Coleman","Dan Severn","Randy Couture","Maurice Smith"], answer:"Mark Coleman", explanation:"Mark Coleman defeated Dan Severn at UFC 12 in 1997 to become the inaugural UFC heavyweight champion.", sourceId:"ufc-heavyweight-champs", sourceUrl:HEAVYWEIGHT }),
  q({ id:"ufc-r2-first-heavyweight-opponent", league:"ufc", round:"round2", category:"Championship Origins", prompt:"Mark Coleman defeated whom to become the first UFC heavyweight champion?", choices:["Dan Severn","Don Frye","Maurice Smith","Tank Abbott"], answer:"Dan Severn", explanation:"Coleman submitted Severn at UFC 12 to claim the inaugural heavyweight championship.", sourceId:"ufc-heavyweight-champs", sourceUrl:HEAVYWEIGHT }),
  q({ id:"ufc-r2-first-superfight-champ", league:"ufc", round:"round2", category:"Championship Origins", prompt:"Who became the UFC's first Superfight champion, a precursor to the heavyweight title?", choices:["Ken Shamrock","Royce Gracie","Dan Severn","Oleg Taktarov"], answer:"Ken Shamrock", explanation:"After a draw with Royce Gracie at UFC 5, Shamrock beat Dan Severn at UFC 6 to claim the Superfight title.", sourceId:"ufc-championship-history", sourceUrl:CHAMPIONSHIP }),
  q({ id:"ufc-r2-ufc5-superfight-draw", league:"ufc", round:"round2", category:"Early UFC", prompt:"The first UFC Superfight title bout at UFC 5 ended in a draw between Ken Shamrock and whom?", choices:["Royce Gracie","Dan Severn","Oleg Taktarov","Kimo Leopoldo"], answer:"Royce Gracie", explanation:"Shamrock and Gracie fought to a draw in the first Superfight championship bout.", sourceId:"ufc-championship-history", sourceUrl:CHAMPIONSHIP }),
  q({ id:"ufc-r2-ufc12-weightclasses", league:"ufc", round:"round2", category:"Rules History", prompt:"Which numbered event was the first UFC card to feature weight classes?", choices:["UFC 12","UFC 10","UFC 14","UFC 20"], answer:"UFC 12", explanation:"UFC 12 introduced weight classes and crowned Mark Coleman the first heavyweight champion.", sourceId:"ufc-30", sourceUrl:UFC30 }),
  q({ id:"ufc-r2-first-chinese-champ", league:"ufc", round:"round2", category:"Global Firsts", prompt:"Who became the first Chinese fighter to win a UFC championship?", choices:["Zhang Weili","Yan Xiaonan","Song Yadong","Li Jingliang"], answer:"Zhang Weili", explanation:"Zhang Weili won the strawweight title in 2019, becoming the UFC's first champion from China.", sourceId:"ufc-zhang-history" }),
  q({ id:"ufc-r2-first-mexican-born-champ", league:"ufc", round:"round2", category:"Global Firsts", prompt:"Who became the UFC's first Mexico-born champion?", choices:["Brandon Moreno","Yair Rodriguez","Alexa Grasso","Cain Velasquez"], answer:"Brandon Moreno", explanation:"Tijuana's Brandon Moreno became the first Mexico-born UFC champion when he won the flyweight title.", sourceId:"ufc-moreno-history" }),
  q({ id:"ufc-r2-first-british-champ", league:"ufc", round:"round2", category:"Global Firsts", prompt:"Who became the first British fighter to win a UFC championship?", choices:["Michael Bisping","Leon Edwards","Dan Hardy","Darren Till"], answer:"Michael Bisping", explanation:"Michael Bisping knocked out Luke Rockhold at UFC 199 to become the first British UFC champion.", sourceId:"ufc-bisping-history" }),
  q({ id:"ufc-r2-nunes-cyborg", league:"ufc", round:"round2", category:"Champ-Champ Moments", prompt:"Amanda Nunes became a two-division champion by knocking out which featherweight great at UFC 232?", choices:["Cris Cyborg","Holly Holm","Germaine de Randamie","Megan Anderson"], answer:"Cris Cyborg", explanation:"Nunes stopped Cris Cyborg in 51 seconds to add the featherweight title to her bantamweight belt.", sourceId:"ufc-232-results" }),
  q({ id:"ufc-r2-tuf1-middleweight", league:"ufc", round:"round2", category:"The Ultimate Fighter", prompt:"Alongside Forrest Griffin, who won the other tournament final on the first season of The Ultimate Fighter?", choices:["Diego Sanchez","Josh Koscheck","Kenny Florian","Chris Leben"], answer:"Diego Sanchez", explanation:"Diego Sanchez won the middleweight bracket on The Ultimate Fighter 1.", sourceId:"tuf1-history" }),
  q({ id:"ufc-r2-ufc193-location", league:"ufc", round:"round2", category:"Venues", prompt:"Ronda Rousey lost her title to Holly Holm at UFC 193 in which city?", choices:["Melbourne","Sydney","Las Vegas","Toronto"], answer:"Melbourne", explanation:"UFC 193 was held at Etihad Stadium in Melbourne, Australia.", sourceId:"ufc-193-results", sourceUrl:UFC193 }),

  // Round 3
  q({ id:"ufc-r3-ufc1-no-judges", league:"ufc", round:"round3", category:"Old-School UFC", prompt:"Which modern feature was completely absent from UFC 1?", choices:["Judges","A referee","A cage","A tournament bracket"], answer:"Judges", explanation:"UFC 1 had no judges, along with no weight classes and no timeouts.", sourceId:"ufc-30", sourceUrl:UFC30 }),
  q({ id:"ufc-r3-ufc1-no-timeouts", league:"ufc", round:"round3", category:"Old-School UFC", prompt:"UFC 1's original tournament format did not include which stoppage structure?", choices:["Timeouts","Submissions","Knockouts","A referee"], answer:"Timeouts", explanation:"UFC's 30th-anniversary history notes that UFC 1 had no judges and no timeouts.", sourceId:"ufc-30", sourceUrl:UFC30 }),
  q({ id:"ufc-r3-ufc8-puerto-rico", league:"ufc", round:"round3", category:"International History", prompt:"Which numbered event was the UFC's first card in Puerto Rico?", choices:["UFC 8","UFC 6","UFC 10","UFC 12"], answer:"UFC 8", explanation:"UFC 8: David vs. Goliath in February 1996 was the promotion's first event in Puerto Rico.", sourceId:"ufc-30", sourceUrl:UFC30 }),
  q({ id:"ufc-r3-coleman-ufc10", league:"ufc", round:"round3", category:"Tournament Era", prompt:"Mark Coleman won his first UFC tournament at which event?", choices:["UFC 10","UFC 8","UFC 11","UFC 12"], answer:"UFC 10", explanation:"Coleman debuted by winning the UFC 10 tournament, then won UFC 11 before becoming heavyweight champion.", sourceId:"ufc-coleman-history" }),
  q({ id:"ufc-r3-coleman-ufc11", league:"ufc", round:"round3", category:"Tournament Era", prompt:"After winning UFC 10, Mark Coleman immediately won which next tournament?", choices:["UFC 11","UFC 12","UFC 9","Ultimate Japan"], answer:"UFC 11", explanation:"Coleman won consecutive UFC tournaments at UFC 10 and UFC 11.", sourceId:"ufc-coleman-history" }),
  q({ id:"ufc-r3-silva-sonnen-round", league:"ufc", round:"round3", category:"Iconic Comebacks", prompt:"Anderson Silva submitted Chael Sonnen in which round of their UFC 117 title fight?", choices:["Fifth","Fourth","Third","Second"], answer:"Fifth", explanation:"Silva rallied in the final round to catch Sonnen in a triangle choke/armbar.", sourceId:"ufc-silva-sonnen", sourceUrl:SILVA }),
  q({ id:"ufc-r3-nunes-cyborg-time", league:"ufc", round:"round3", category:"Iconic Finishes", prompt:"How long did Amanda Nunes need to knock out Cris Cyborg at UFC 232?", choices:["51 seconds","13 seconds","1:38","2:14"], answer:"51 seconds", explanation:"Nunes stopped Cyborg just 51 seconds into the first round.", sourceId:"ufc-232-results" }),
  q({ id:"ufc-r3-holm-ronda-round", league:"ufc", round:"round3", category:"Famous Upsets", prompt:"Holly Holm finished Ronda Rousey in which round at UFC 193?", choices:["Second","First","Third","Fifth"], answer:"Second", explanation:"Holm landed the decisive head kick early in the second round.", sourceId:"ufc-193-results", sourceUrl:UFC193 }),
  q({ id:"ufc-r3-diaz-mcgregor-round", league:"ufc", round:"round3", category:"Famous Upsets", prompt:"Nate Diaz submitted Conor McGregor in which round of their first fight?", choices:["Second","First","Third","Fourth"], answer:"Second", explanation:"Diaz secured the rear-naked choke at 4:12 of round two at UFC 196.", sourceId:"ufc-196-results", sourceUrl:UFC196 }),
  q({ id:"ufc-r3-griffin-bonnar-hof", league:"ufc", round:"round3", category:"Hall of Fame", prompt:"Forrest Griffin vs. Stephan Bonnar I entered the UFC Hall of Fame in which wing?", choices:["Fight Wing","Pioneer Wing","Modern Wing","Contributors Wing"], answer:"Fight Wing", explanation:"The historic TUF 1 Finale bout became the first fight inducted into the Hall of Fame Fight Wing.", sourceId:"ufc-hof", sourceUrl:HOF }),
  q({ id:"ufc-r3-lawler-macdonald-hof", league:"ufc", round:"round3", category:"Hall of Fame", prompt:"Robbie Lawler's brutal UFC 189 rematch with Rory MacDonald is honored in which Hall of Fame wing?", choices:["Fight Wing","Modern Wing","Pioneer Wing","Contributors Wing"], answer:"Fight Wing", explanation:"Lawler vs. MacDonald II is recognized as a UFC Hall of Fame Fight Wing classic.", sourceId:"ufc-hof", sourceUrl:HOF }),
  q({ id:"ufc-r3-jones-gustafsson-event", league:"ufc", round:"round3", category:"Hall of Fame", prompt:"Jon Jones and Alexander Gustafsson's Hall of Fame classic took place at which event?", choices:["UFC 165","UFC 172","UFC 182","UFC 214"], answer:"UFC 165", explanation:"Jones and Gustafsson fought their classic five-round title bout at UFC 165 in 2013.", sourceId:"ufc-hof", sourceUrl:HOF }),

  // Last Call
  q({ id:"ufc-final-first-heavyweight-event", league:"ufc", round:"last-call", category:"Championship Origins", prompt:"The UFC crowned its first heavyweight champion at which event?", choices:["UFC 12","UFC 10","UFC 14","UFC 17"], answer:"UFC 12", explanation:"Mark Coleman beat Dan Severn at UFC 12 to become the first UFC heavyweight champion.", sourceId:"ufc-heavyweight-champs", sourceUrl:HEAVYWEIGHT }),
  q({ id:"ufc-final-superfight-first-champ-event", league:"ufc", round:"last-call", category:"Early UFC", prompt:"Ken Shamrock won the UFC's first Superfight championship at which event?", choices:["UFC 6","UFC 5","UFC 7","UFC 9"], answer:"UFC 6", explanation:"After his UFC 5 draw with Royce Gracie, Shamrock submitted Dan Severn at UFC 6 for the Superfight title.", sourceId:"ufc-championship-history", sourceUrl:CHAMPIONSHIP }),
  q({ id:"ufc-final-ufc1-tournament-size", league:"ufc", round:"last-call", category:"Origins", prompt:"How many fighters were in the tournament bracket at UFC 1?", choices:["8","16","4","12"], answer:"8", explanation:"UFC 1 was built as an eight-man tournament at McNichols Sports Arena.", sourceId:"ufc-30", sourceUrl:UFC30 }),
  q({ id:"ufc-final-ufc1-no-weightclasses", league:"ufc", round:"last-call", category:"Origins", prompt:"At which event did UFC first introduce formal weight classes?", choices:["UFC 12","UFC 1","UFC 5","UFC 20"], answer:"UFC 12", explanation:"UFC 12 marked the promotion's first use of weight classes.", sourceId:"ufc-30", sourceUrl:UFC30 }),
];
