import { barTriviaQuestion, type BarTriviaQuestion } from "../games/barTriviaEngine";

const FIRSTS = "https://www.profootballhof.com/news/football-firsts";
const NICKNAMES = "https://www.profootballhof.com/news/franchise-nicknames";
const FRANCHISES = "https://www.profootballhof.com/football-history/national-footbal-league-franchise-histories";
const NFL100 = "https://www.nfl.com/news/nfl-s-100-greatest-plays-the-final-five-unveiled-0ap3000001056879";
const NFL100_PHILLY = "https://www.nfl.com/100/originals/100-greatest/detail.html?slug=plays-10";
const THANKSGIVING = "https://www.nfl.com/news/why-do-we-play-on-thanksgiving-day";
const THANKSGIVING98 = "https://www.nfl.com/news/remembering-coin-toss-randy-moss-and-wild-thanksgiving-1998";
const QB_RADIO = "https://www.profootballhof.com/news/moments-in-nfl-history-call-1-800-qb-radio";
const TEBOW = "https://www.profootballhof.com/news/tebow-moment";
const SB_MEMORIES = "https://www.nfl.com/news/plays-not-accomplishments-define-super-bowl-memories-09000d5d80e4eef9";

function q(seed: Parameters<typeof barTriviaQuestion>[0]) {
  return barTriviaQuestion({ ...seed, verifiedAt: "2026-09-28" });
}

export const BAR_TRIVIA_NFL_EVERGREEN_WAVE_2: readonly BarTriviaQuestion[] = [
  // Round 1
  q({ id:"nfl-r1-cardinals-name-origin", league:"nfl", round:"round1", category:"Team Names", prompt:"The Cardinals nickname originally came from what unusual source?", choices:["The color of used jerseys","A state bird contest","A local baseball club","A newspaper poll"], answer:"The color of used jerseys", explanation:"Owner Chris O'Brien called the team's used maroon jerseys 'cardinal red,' and the name stuck.", sourceId:"pfhof-franchise-nicknames", sourceUrl:NICKNAMES }),
  q({ id:"nfl-r1-packers-name-origin", league:"nfl", round:"round1", category:"Team Names", prompt:"The Green Bay Packers got their nickname from what kind of business?", choices:["A meat-packing company","A shipping company","A cheese company","A lumber company"], answer:"A meat-packing company", explanation:"Green Bay was sponsored first by Indian Packing Company and later Acme Packing Company.", sourceId:"pfhof-franchise-nicknames", sourceUrl:NICKNAMES }),
  q({ id:"nfl-r1-falcons-name-contest", league:"nfl", round:"round1", category:"Team Names", prompt:"The Atlanta Falcons nickname was selected after what kind of process?", choices:["A fan contest","An owner vote","A player vote","A newspaper editorial"], answer:"A fan contest", explanation:"Atlanta received more than 1,300 fan entries suggesting hundreds of possible team names.", sourceId:"pfhof-franchise-nicknames", sourceUrl:NICKNAMES }),
  q({ id:"nfl-r1-texans-final-name", league:"nfl", round:"round1", category:"Team Names", prompt:"Which nickname did Houston choose for its expansion franchise from finalists that included Apollos and Stallions?", choices:["Texans","Roughnecks","Toros","Wranglers"], answer:"Texans", explanation:"Houston unveiled the Texans name, colors and logo in September 2000.", sourceId:"pfhof-franchise-nicknames", sourceUrl:NICKNAMES }),
  q({ id:"nfl-r1-colts-name-horses", league:"nfl", round:"round1", category:"Team Names", prompt:"The Colts nickname was chosen to reflect Baltimore's history with which sport?", choices:["Horse racing","Baseball","Boxing","Rowing"], answer:"Horse racing", explanation:"A fan contest chose Colts to reflect the Baltimore area's horse-breeding and racing tradition.", sourceId:"pfhof-franchise-nicknames", sourceUrl:NICKNAMES }),
  q({ id:"nfl-r1-immaculate-reception-player", league:"nfl", round:"round1", category:"Iconic Plays", prompt:"Who made the catch on the 'Immaculate Reception'?", choices:["Franco Harris","Lynn Swann","John Stallworth","Rocky Bleier"], answer:"Franco Harris", explanation:"Franco Harris caught the deflected pass and ran for the winning touchdown against Oakland in the 1972 playoffs.", sourceId:"nfl100-greatest-plays", sourceUrl:NFL100 }),
  q({ id:"nfl-r1-the-catch-receiver", league:"nfl", round:"round1", category:"Iconic Plays", prompt:"Which 49ers receiver made the play simply known as 'The Catch'?", choices:["Dwight Clark","Jerry Rice","Freddie Solomon","John Taylor"], answer:"Dwight Clark", explanation:"Dwight Clark caught Joe Montana's late touchdown pass in the 1981 NFC Championship Game.", sourceId:"nfl100-greatest-plays", sourceUrl:NFL100 }),
  q({ id:"nfl-r1-helmet-catch-player", league:"nfl", round:"round1", category:"Super Bowl Moments", prompt:"Which Giants receiver made the famous 'Helmet Catch' in Super Bowl XLII?", choices:["David Tyree","Plaxico Burress","Amani Toomer","Steve Smith"], answer:"David Tyree", explanation:"David Tyree pinned Eli Manning's pass against his helmet during the Giants' winning drive.", sourceId:"nfl-super-bowl-memories", sourceUrl:SB_MEMORIES }),
  q({ id:"nfl-r1-one-yard-short-tackle", league:"nfl", round:"round1", category:"Super Bowl Moments", prompt:"Which Rams defender made the tackle at the 1-yard line to end Super Bowl XXXIV?", choices:["Mike Jones","London Fletcher","Aeneas Williams","Grant Wistrom"], answer:"Mike Jones", explanation:"Mike Jones tackled Tennessee's Kevin Dyson one yard short of the end zone as time expired.", sourceId:"nfl-super-bowl-memories", sourceUrl:SB_MEMORIES }),
  q({ id:"nfl-r1-philly-special-passer", league:"nfl", round:"round1", category:"Iconic Plays", prompt:"Who threw the touchdown pass to Nick Foles on the 'Philly Special'?", choices:["Trey Burton","Corey Clement","Zach Ertz","Nelson Agholor"], answer:"Trey Burton", explanation:"Corey Clement took the snap, pitched to Trey Burton, and Burton threw to Foles for the touchdown.", sourceId:"nfl100-philly-special", sourceUrl:NFL100_PHILLY }),
  q({ id:"nfl-r1-thanksgiving-lions-start", league:"nfl", round:"round1", category:"Traditions", prompt:"Which franchise began its annual Thanksgiving home-game tradition in 1934?", choices:["Detroit Lions","Dallas Cowboys","Green Bay Packers","Chicago Bears"], answer:"Detroit Lions", explanation:"Lions owner George A. Richards scheduled the 1934 Thanksgiving game against Chicago to boost attendance.", sourceId:"nfl-thanksgiving-history", sourceUrl:THANKSGIVING }),
  q({ id:"nfl-r1-thanksgiving-third-game", league:"nfl", round:"round1", category:"Traditions", prompt:"The NFL added a third Thanksgiving Day game in which decade?", choices:["2000s","1990s","1980s","2010s"], answer:"2000s", explanation:"A third Thanksgiving game was added in 2006 and can feature teams beyond Detroit and Dallas.", sourceId:"nfl-thanksgiving-history", sourceUrl:THANKSGIVING }),
  q({ id:"nfl-r1-radio-helmet-team", league:"nfl", round:"round1", category:"Football Innovation", prompt:"Which team first experimented with a coach-to-quarterback radio inside a helmet?", choices:["Cleveland Browns","Dallas Cowboys","Baltimore Colts","New York Giants"], answer:"Cleveland Browns", explanation:"Paul Brown secretly tested a radio receiver in Browns quarterback George Ratterman's helmet in 1956.", sourceId:"pfhof-qb-radio", sourceUrl:QB_RADIO }),

  // Round 2
  q({ id:"nfl-r2-first-regular-outside-us-city", league:"nfl", round:"round2", category:"International", prompt:"The NFL's first regular-season game outside the United States was played in which city?", choices:["Mexico City","London","Toronto","Tokyo"], answer:"Mexico City", explanation:"Arizona beat San Francisco at Estadio Azteca in Mexico City in 2005.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r2-first-regular-outside-na-city", league:"nfl", round:"round2", category:"International", prompt:"The first NFL regular-season game played outside North America was held in which city?", choices:["London","Berlin","Tokyo","Dublin"], answer:"London", explanation:"The Giants beat the Dolphins at Wembley Stadium in London in 2007.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r2-first-regular-outside-us-teams", league:"nfl", round:"round2", category:"International", prompt:"Which two teams played the NFL's first regular-season game outside the United States?", choices:["Cardinals and 49ers","Giants and Dolphins","Cowboys and Bears","Patriots and Buccaneers"], answer:"Cardinals and 49ers", explanation:"Arizona defeated San Francisco 31–14 in Mexico City in 2005.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r2-first-regular-outside-na-teams", league:"nfl", round:"round2", category:"International", prompt:"Which two teams played the NFL's first regular-season game outside North America?", choices:["Giants and Dolphins","Cardinals and 49ers","Chargers and Saints","Patriots and Buccaneers"], answer:"Giants and Dolphins", explanation:"New York defeated Miami 13–10 at Wembley Stadium in 2007.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r2-first-11-10-game", league:"nfl", round:"round2", category:"Score Oddities", prompt:"Which team won the first 11–10 game in NFL history?", choices:["Pittsburgh Steelers","San Diego Chargers","Baltimore Ravens","Chicago Bears"], answer:"Pittsburgh Steelers", explanation:"Pittsburgh beat San Diego 11–10 in November 2008, the first such final score in league history.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r2-manning-pro-bowl-brothers", league:"nfl", round:"round2", category:"Family Ties", prompt:"Which quarterback brothers became the first at their position voted to the same Pro Bowl?", choices:["Peyton and Eli Manning","Jim and John Harbaugh","Carson and Jordan Palmer","Matt and Tim Hasselbeck"], answer:"Peyton and Eli Manning", explanation:"Peyton and Eli Manning were both selected to the 2009 Pro Bowl after the 2008 season.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r2-first-national-radio-game", league:"nfl", round:"round2", category:"Broadcast", prompt:"Which matchup produced the first national radio broadcast of an NFL game?", choices:["Lions vs. Bears","Packers vs. Giants","Bears vs. Packers","Giants vs. Washington"], answer:"Lions vs. Bears", explanation:"Detroit-Chicago on Thanksgiving 1934 was the first national radio broadcast of an NFL game.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r2-radio-helmet-quarterback", league:"nfl", round:"round2", category:"Football Innovation", prompt:"Which Browns quarterback wore the experimental radio helmet tested by Paul Brown in the 1950s?", choices:["George Ratterman","Otto Graham","Milt Plum","Frank Ryan"], answer:"George Ratterman", explanation:"The radio receiver was placed inside George Ratterman's helmet during the Browns' early tests.", sourceId:"pfhof-qb-radio", sourceUrl:QB_RADIO }),
  q({ id:"nfl-r2-radio-helmet-standard-year", league:"nfl", round:"round2", category:"Football Innovation", prompt:"The NFL officially introduced sideline-to-quarterback radio helmets in which decade?", choices:["1990s","1980s","1970s","2000s"], answer:"1990s", explanation:"The league instituted limited coach-to-quarterback radio communication in 1994.", sourceId:"pfhof-radio-helmet", sourceUrl:"https://www.profootballhof.com/news/ratterman-s-radio-helmet" }),
  q({ id:"nfl-r2-tebow-ot-receiver", league:"nfl", round:"round2", category:"Playoff Moments", prompt:"Tim Tebow's famous walk-off overtime touchdown against Pittsburgh went to which receiver?", choices:["Demaryius Thomas","Eric Decker","Brandon Lloyd","Eddie Royal"], answer:"Demaryius Thomas", explanation:"Tebow hit Demaryius Thomas for an 80-yard touchdown 11 seconds into overtime.", sourceId:"pfhof-tebow-moment", sourceUrl:TEBOW }),
  q({ id:"nfl-r2-1998-thanksgiving-coin", league:"nfl", round:"round2", category:"Thanksgiving Oddities", prompt:"Which Steelers star was at the center of the infamous 1998 Thanksgiving overtime coin-toss controversy?", choices:["Jerome Bettis","Kordell Stewart","Hines Ward","Rod Woodson"], answer:"Jerome Bettis", explanation:"Confusion over Jerome Bettis' coin-toss call helped produce one of Thanksgiving's strangest NFL moments.", sourceId:"nfl-thanksgiving-1998", sourceUrl:THANKSGIVING98 }),
  q({ id:"nfl-r2-1998-thanksgiving-moss-opponent", league:"nfl", round:"round2", category:"Thanksgiving Moments", prompt:"Rookie Randy Moss' famous 1998 Thanksgiving breakout came against which team?", choices:["Dallas Cowboys","Detroit Lions","Green Bay Packers","Chicago Bears"], answer:"Dallas Cowboys", explanation:"Moss and Minnesota exploded against Dallas in the second Thanksgiving game of 1998.", sourceId:"nfl-thanksgiving-1998", sourceUrl:THANKSGIVING98 }),
  q({ id:"nfl-r2-washington-boston-braves", league:"nfl", round:"round2", category:"Franchise Origins", prompt:"The franchise now based in Washington entered the NFL in 1932 under which name?", choices:["Boston Braves","Boston Yanks","Washington Senators","Pottsville Maroons"], answer:"Boston Braves", explanation:"The franchise began as the Boston Braves in 1932 before later changing names and moving to Washington.", sourceId:"pfhof-franchise-history", sourceUrl:FRANCHISES }),

  // Round 3
  q({ id:"nfl-r3-cardinals-original-city", league:"nfl", round:"round3", category:"Franchise Origins", prompt:"The Cardinals franchise was a charter NFL member while based in which city?", choices:["Chicago","St. Louis","Phoenix","Cleveland"], answer:"Chicago", explanation:"The Cardinals played in Chicago before moving to St. Louis in 1960 and Arizona in 1988.", sourceId:"pfhof-franchise-nicknames", sourceUrl:NICKNAMES }),
  q({ id:"nfl-r3-cardinals-cardinal-red", league:"nfl", round:"round3", category:"Team Names", prompt:"The Cardinals nickname traces to jerseys originally purchased from which university?", choices:["University of Chicago","Northwestern","Illinois","Notre Dame"], answer:"University of Chicago", explanation:"The club bought used maroon jerseys from the University of Chicago; owner Chris O'Brien called them 'cardinal red.'", sourceId:"pfhof-franchise-nicknames", sourceUrl:NICKNAMES }),
  q({ id:"nfl-r3-texans-other-finalist", league:"nfl", round:"round3", category:"Team Names", prompt:"Which of these was one of the three finalists considered before Houston chose 'Texans'?", choices:["Apollos","Comets","Mustangs","Oilers"], answer:"Apollos", explanation:"Houston narrowed its expansion nickname list to Apollos, Stallions and Texans.", sourceId:"pfhof-franchise-nicknames", sourceUrl:NICKNAMES }),
  q({ id:"nfl-r3-first-national-radio-announcer", league:"nfl", round:"round3", category:"Broadcast", prompt:"Who called play-by-play on the first national radio broadcast of an NFL game in 1934?", choices:["Graham McNamee","Red Barber","Mel Allen","Ted Husing"], answer:"Graham McNamee", explanation:"Graham McNamee called Lions-Bears on Thanksgiving 1934 for the first national NFL radio broadcast.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r3-immaculate-opponent", league:"nfl", round:"round3", category:"Iconic Plays", prompt:"The 'Immaculate Reception' came against which opponent?", choices:["Oakland Raiders","Baltimore Colts","Miami Dolphins","Cleveland Browns"], answer:"Oakland Raiders", explanation:"Franco Harris' miracle play beat Oakland in the 1972 AFC divisional playoffs.", sourceId:"nfl100-greatest-plays", sourceUrl:NFL100 }),
  q({ id:"nfl-r3-the-catch-opponent", league:"nfl", round:"round3", category:"Iconic Plays", prompt:"Dwight Clark's 'The Catch' eliminated which team in the NFC Championship Game?", choices:["Dallas Cowboys","New York Giants","Chicago Bears","Washington"], answer:"Dallas Cowboys", explanation:"San Francisco beat Dallas 28–27 after Clark's famous touchdown catch.", sourceId:"nfl100-greatest-plays", sourceUrl:NFL100 }),
  q({ id:"nfl-r3-helmet-catch-opponent", league:"nfl", round:"round3", category:"Super Bowl Moments", prompt:"David Tyree's Helmet Catch came against which team?", choices:["New England Patriots","Baltimore Ravens","Green Bay Packers","Pittsburgh Steelers"], answer:"New England Patriots", explanation:"Tyree's catch helped the Giants upset the previously unbeaten Patriots in Super Bowl XLII.", sourceId:"nfl-super-bowl-memories", sourceUrl:SB_MEMORIES }),
  q({ id:"nfl-r3-one-yard-short-player", league:"nfl", round:"round3", category:"Super Bowl Moments", prompt:"Which Titans receiver was tackled one yard short on the final play of Super Bowl XXXIV?", choices:["Kevin Dyson","Derrick Mason","Frank Wycheck","Chris Sanders"], answer:"Kevin Dyson", explanation:"Kevin Dyson caught Steve McNair's pass before Mike Jones stopped him at the 1-yard line.", sourceId:"nfl-super-bowl-memories", sourceUrl:SB_MEMORIES }),
  q({ id:"nfl-r3-philly-special-snap", league:"nfl", round:"round3", category:"Iconic Plays", prompt:"Who took the direct snap on the 'Philly Special' before pitching it to Trey Burton?", choices:["Corey Clement","LeGarrette Blount","Jay Ajayi","Nelson Agholor"], answer:"Corey Clement", explanation:"Corey Clement took the snap and pitched to Trey Burton, who found Nick Foles in the end zone.", sourceId:"nfl100-philly-special", sourceUrl:NFL100_PHILLY }),
  q({ id:"nfl-r3-radio-helmet-coach", league:"nfl", round:"round3", category:"Football Innovation", prompt:"Which Hall of Fame coach secretly tested the NFL's early quarterback radio helmet?", choices:["Paul Brown","Vince Lombardi","Tom Landry","Sid Gillman"], answer:"Paul Brown", explanation:"Cleveland coach Paul Brown tested the radio system in George Ratterman's helmet in 1956.", sourceId:"pfhof-qb-radio", sourceUrl:QB_RADIO }),
  q({ id:"nfl-r3-thanksgiving-1934-opponent", league:"nfl", round:"round3", category:"Traditions", prompt:"Detroit launched its annual Thanksgiving tradition in 1934 against which team?", choices:["Chicago Bears","Green Bay Packers","New York Giants","Cleveland Rams"], answer:"Chicago Bears", explanation:"The Lions hosted the Bears on Thanksgiving 1934 in the game that established Detroit's annual tradition.", sourceId:"nfl-thanksgiving-history", sourceUrl:THANKSGIVING }),
  q({ id:"nfl-r3-tebow-ot-seconds", league:"nfl", round:"round3", category:"Playoff Oddities", prompt:"How long into overtime did Tim Tebow's playoff-winning touchdown against Pittsburgh occur?", choices:["11 seconds","31 seconds","51 seconds","71 seconds"], answer:"11 seconds", explanation:"Tebow connected with Demaryius Thomas for an 80-yard touchdown just 11 seconds into overtime.", sourceId:"pfhof-tebow-moment", sourceUrl:TEBOW }),
  q({ id:"nfl-r3-boston-braves-year", league:"nfl", round:"round3", category:"Franchise Origins", prompt:"The Washington franchise entered the NFL as the Boston Braves in which decade?", choices:["1930s","1920s","1940s","1950s"], answer:"1930s", explanation:"The franchise began as the Boston Braves in 1932.", sourceId:"pfhof-franchise-history", sourceUrl:FRANCHISES }),

  // Last Call
  q({ id:"nfl-final-first-radio-game-year", league:"nfl", round:"last-call", category:"Broadcast History", prompt:"The first national radio broadcast of an NFL game took place in what year?", choices:["1934","1929","1939","1946"], answer:"1934", explanation:"Detroit's Thanksgiving game against Chicago on Nov. 29, 1934 was the first national NFL radio broadcast.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-final-radio-helmet-test-year", league:"nfl", round:"last-call", category:"Football Innovation", prompt:"Paul Brown first tested a radio receiver inside George Ratterman's helmet in what year?", choices:["1956","1948","1964","1972"], answer:"1956", explanation:"The Browns experimented with the coach-to-quarterback radio helmet in 1956, decades before it became standard.", sourceId:"pfhof-qb-radio", sourceUrl:QB_RADIO }),
  q({ id:"nfl-final-cardinals-name-quote", league:"nfl", round:"last-call", category:"Team Name Oddities", prompt:"The Cardinals nickname began after owner Chris O'Brien rejected the description 'faded red' and called the jerseys what instead?", choices:["Cardinal red","Crimson red","Varsity red","Chicago red"], answer:"Cardinal red", explanation:"O'Brien insisted the used jerseys were 'cardinal red,' providing the franchise's lasting nickname.", sourceId:"pfhof-franchise-nicknames", sourceUrl:NICKNAMES }),
];
