import { barTriviaQuestion, type BarTriviaQuestion } from "../games/barTriviaEngine";

const FIRSTS = "https://www.profootballhof.com/news/football-firsts";
const DRAFT_1936 = "https://www.profootballhof.com/football-history/nfl-draft-history/1930/1936";
const SUPER_BOWL_NAME = "https://www.profootballhof.com/news/2005/01/news-spotlight-game-week-3-lamar-hunt/";
const IMMACULATE = "https://www.nfl.com/news/immaculate-reception-named-nfl-100-greatest-moment-0ap3000001100539";

function q(seed: Parameters<typeof barTriviaQuestion>[0]) {
  return barTriviaQuestion({ ...seed, verifiedAt: "2026-09-28" });
}

export const BAR_TRIVIA_NFL_EVERGREEN_WAVE_2: readonly BarTriviaQuestion[] = [
  // Round 1
  q({ id:"nfl-r1-49ers-name", league:"nfl", round:"round1", category:"Team Identity", prompt:"The San Francisco 49ers' name refers to people who flocked west during which historic event?", choices:["California Gold Rush","Oregon Trail","Transcontinental Railroad boom","Klondike Gold Rush"], answer:"California Gold Rush", explanation:"The 49ers name honors prospectors who came to California during the 1849 Gold Rush.", sourceId:"49ers-history" }),
  q({ id:"nfl-r1-browns-name", league:"nfl", round:"round1", category:"Team Identity", prompt:"The Cleveland Browns are named for which influential football figure?", choices:["Paul Brown","Jim Brown","Otto Graham","Lou Groza"], answer:"Paul Brown", explanation:"The franchise name honors founding coach Paul Brown.", sourceId:"browns-history" }),
  q({ id:"nfl-r1-jets-original-name", league:"nfl", round:"round1", category:"Franchise Origins", prompt:"Before becoming the New York Jets, the franchise was known as the...", choices:["Titans of New York","New York Americans","New York Bulldogs","Gothams"], answer:"Titans of New York", explanation:"The AFL franchise began as the Titans of New York before adopting the Jets name in 1963.", sourceId:"jets-history" }),
  q({ id:"nfl-r1-titans-oilers", league:"nfl", round:"round1", category:"Franchise Origins", prompt:"The Tennessee Titans franchise originally played under what name?", choices:["Houston Oilers","Memphis Hounds","Tennessee Oilers","Houston Texans"], answer:"Houston Oilers", explanation:"The franchise began as the Houston Oilers in the AFL before eventually becoming the Tennessee Titans.", sourceId:"titans-history" }),
  q({ id:"nfl-r1-lambeau-leap", league:"nfl", round:"round1", category:"Celebrations", prompt:"Which team is associated with the touchdown celebration known as the 'Lambeau Leap'?", choices:["Green Bay Packers","Chicago Bears","Minnesota Vikings","Detroit Lions"], answer:"Green Bay Packers", explanation:"Packers players leap into the stands at Lambeau Field after touchdowns in the celebration known as the Lambeau Leap.", sourceId:"packers-traditions" }),
  q({ id:"nfl-r1-americas-team", league:"nfl", round:"round1", category:"Nicknames", prompt:"Which NFL franchise is famously nicknamed 'America's Team'?", choices:["Dallas Cowboys","Pittsburgh Steelers","Green Bay Packers","New England Patriots"], answer:"Dallas Cowboys", explanation:"The 'America's Team' nickname became closely associated with the Cowboys in the late 1970s.", sourceId:"cowboys-history" }),
  q({ id:"nfl-r1-monsters-midway", league:"nfl", round:"round1", category:"Nicknames", prompt:"The nickname 'Monsters of the Midway' is associated with which franchise?", choices:["Chicago Bears","Detroit Lions","Cleveland Browns","New York Giants"], answer:"Chicago Bears", explanation:"The Bears have long carried the 'Monsters of the Midway' nickname.", sourceId:"bears-history" }),
  q({ id:"nfl-r1-dawg-pound", league:"nfl", round:"round1", category:"Fan Culture", prompt:"The 'Dawg Pound' is the famous fan section associated with which team?", choices:["Cleveland Browns","Buffalo Bills","Philadelphia Eagles","Baltimore Ravens"], answer:"Cleveland Browns", explanation:"Cleveland's rowdy end-zone fan section became known as the Dawg Pound.", sourceId:"browns-fan-culture" }),
  q({ id:"nfl-r1-buccaneers-pirate-ship", league:"nfl", round:"round1", category:"Stadiums", prompt:"Which NFL stadium experience is famous for a pirate ship that fires cannons after home-team scores?", choices:["Tampa Bay Buccaneers","Las Vegas Raiders","Seattle Seahawks","New Orleans Saints"], answer:"Tampa Bay Buccaneers", explanation:"Raymond James Stadium features the Buccaneers' pirate ship in its north end zone.", sourceId:"buccaneers-stadium" }),
  q({ id:"nfl-r1-super-bowl-name-origin", league:"nfl", round:"round1", category:"Super Bowl Lore", prompt:"Which team founder is credited with casually coining the name 'Super Bowl'?", choices:["Lamar Hunt","Al Davis","George Halas","Art Rooney"], answer:"Lamar Hunt", explanation:"Chiefs founder Lamar Hunt said the phrase came to him after hearing his children talk about the Wham-O Super Ball toy.", sourceId:"lamar-hunt-super-bowl", sourceUrl:SUPER_BOWL_NAME }),
  q({ id:"nfl-r1-super-bowl-toy", league:"nfl", round:"round1", category:"Super Bowl Lore", prompt:"The phrase 'Super Bowl' was partly inspired by which popular children's toy?", choices:["Super Ball","Frisbee","Hula Hoop","Slinky"], answer:"Super Ball", explanation:"Lamar Hunt connected the championship game's nickname to the Wham-O Super Ball his children played with.", sourceId:"lamar-hunt-super-bowl", sourceUrl:SUPER_BOWL_NAME }),
  q({ id:"nfl-r1-immaculate-reception", league:"nfl", round:"round1", category:"Iconic Plays", prompt:"Who made the catch on the play known as the 'Immaculate Reception'?", choices:["Franco Harris","Lynn Swann","John Fuqua","Terry Bradshaw"], answer:"Franco Harris", explanation:"Franco Harris scooped the deflected pass and ran for the winning touchdown against Oakland in the 1972 playoffs.", sourceId:"nfl-immaculate-reception", sourceUrl:IMMACULATE }),
  q({ id:"nfl-r1-helmet-catch", league:"nfl", round:"round1", category:"Super Bowl Moments", prompt:"Who made the famous 'Helmet Catch' for the Giants in Super Bowl XLII?", choices:["David Tyree","Plaxico Burress","Amani Toomer","Steve Smith"], answer:"David Tyree", explanation:"David Tyree pinned Eli Manning's pass against his helmet during the Giants' game-winning drive against New England.", sourceId:"nfl-helmet-catch" }),

  // Round 2
  q({ id:"nfl-r2-first-draft-city", league:"nfl", round:"round2", category:"Draft History", prompt:"The first NFL Draft in 1936 was held in which city?", choices:["Philadelphia","New York","Chicago","Canton"], answer:"Philadelphia", explanation:"The first NFL Draft was held at the Ritz-Carlton Hotel in Philadelphia.", sourceId:"pfhof-1936-draft", sourceUrl:DRAFT_1936 }),
  q({ id:"nfl-r2-first-draft-pick", league:"nfl", round:"round2", category:"Draft History", prompt:"Who was the first player ever selected in an NFL Draft?", choices:["Jay Berwanger","Sammy Baugh","Don Hutson","Sid Luckman"], answer:"Jay Berwanger", explanation:"The Eagles selected University of Chicago back Jay Berwanger first overall in the inaugural 1936 draft.", sourceId:"pfhof-1936-draft", sourceUrl:DRAFT_1936 }),
  q({ id:"nfl-r2-first-draft-pick-never-played", league:"nfl", round:"round2", category:"Draft Oddities", prompt:"What unusual fact is true about first-ever NFL Draft pick Jay Berwanger?", choices:["He never played an NFL game","He became a Hall of Fame quarterback","He was drafted twice in the same year","He immediately became an NFL coach"], answer:"He never played an NFL game", explanation:"Berwanger never reached a contract agreement and never played in the NFL.", sourceId:"pfhof-1936-draft", sourceUrl:DRAFT_1936 }),
  q({ id:"nfl-r2-first-draft-hotel", league:"nfl", round:"round2", category:"Draft History", prompt:"The inaugural NFL Draft took place at which Philadelphia hotel?", choices:["Ritz-Carlton","Bellevue-Stratford","Waldorf-Astoria","Warwick"], answer:"Ritz-Carlton", explanation:"NFL owners gathered at Philadelphia's Ritz-Carlton Hotel for the first draft in 1936.", sourceId:"pfhof-1936-draft", sourceUrl:DRAFT_1936 }),
  q({ id:"nfl-r2-super-bowl-iii-guarantee", league:"nfl", round:"round2", category:"Famous Quotes", prompt:"Which quarterback famously guaranteed victory before Super Bowl III?", choices:["Joe Namath","Johnny Unitas","Len Dawson","Bart Starr"], answer:"Joe Namath", explanation:"Jets quarterback Joe Namath guaranteed his team would beat the heavily favored Baltimore Colts.", sourceId:"super-bowl-iii-history" }),
  q({ id:"nfl-r2-the-catch", league:"nfl", round:"round2", category:"Iconic Plays", prompt:"Joe Montana's pass to which receiver became known simply as 'The Catch'?", choices:["Dwight Clark","Jerry Rice","Freddie Solomon","John Taylor"], answer:"Dwight Clark", explanation:"Dwight Clark caught Montana's late touchdown pass against Dallas in the 1981 NFC Championship Game.", sourceId:"49ers-the-catch" }),
  q({ id:"nfl-r2-beast-quake", league:"nfl", round:"round2", category:"Iconic Plays", prompt:"Which running back's playoff touchdown run became known as the 'Beast Quake'?", choices:["Marshawn Lynch","Shaun Alexander","Adrian Peterson","Frank Gore"], answer:"Marshawn Lynch", explanation:"Marshawn Lynch's tackle-breaking run against New Orleans in the 2010 playoffs became the Beast Quake.", sourceId:"seahawks-beast-quake" }),
  q({ id:"nfl-r2-minneapolis-miracle", league:"nfl", round:"round2", category:"Iconic Plays", prompt:"Who caught the touchdown pass on the 'Minneapolis Miracle'?", choices:["Stefon Diggs","Adam Thielen","Kyle Rudolph","Jarius Wright"], answer:"Stefon Diggs", explanation:"Stefon Diggs scored on the final play to lift Minnesota past New Orleans in the 2017 divisional round.", sourceId:"vikings-minneapolis-miracle" }),
  q({ id:"nfl-r2-miracle-meadowlands", league:"nfl", round:"round2", category:"Iconic Plays", prompt:"Who returned Joe Pisarcik's fumble for the winning touchdown in the original 'Miracle at the Meadowlands'?", choices:["Herman Edwards","Ron Jaworski","Wilbert Montgomery","Bill Bergey"], answer:"Herman Edwards", explanation:"Eagles defensive back Herman Edwards scooped the fumble and scored the stunning game-winning touchdown in 1978.", sourceId:"eagles-miracle-meadowlands" }),
  q({ id:"nfl-r2-double-doink", league:"nfl", round:"round2", category:"Playoff Moments", prompt:"Which Bears kicker's missed playoff field goal became known as the 'Double Doink'?", choices:["Cody Parkey","Robbie Gould","Eddy Pineiro","Connor Barth"], answer:"Cody Parkey", explanation:"Cody Parkey's kick hit an upright and the crossbar in Chicago's 2018 wild-card loss to Philadelphia.", sourceId:"bears-double-doink" }),
  q({ id:"nfl-r2-tuck-rule", league:"nfl", round:"round2", category:"Playoff Moments", prompt:"The famous 'Tuck Rule Game' matched New England against which team?", choices:["Oakland Raiders","Pittsburgh Steelers","New York Jets","Indianapolis Colts"], answer:"Oakland Raiders", explanation:"The Patriots beat Oakland in the snowy 2001 divisional playoff remembered for the tuck-rule replay decision.", sourceId:"patriots-tuck-rule" }),
  q({ id:"nfl-r2-river-city-relay", league:"nfl", round:"round2", category:"Odd Finishes", prompt:"Which team scored on the wild multi-lateral 'River City Relay' in 2003?", choices:["New Orleans Saints","Jacksonville Jaguars","Miami Dolphins","Carolina Panthers"], answer:"New Orleans Saints", explanation:"New Orleans used multiple laterals to score as time expired against Jacksonville, only to miss the tying extra point.", sourceId:"saints-river-city-relay" }),
  q({ id:"nfl-r2-holy-roller", league:"nfl", round:"round2", category:"Odd Finishes", prompt:"The controversial 1978 play known as the 'Holy Roller' involved which franchise?", choices:["Oakland Raiders","Dallas Cowboys","Pittsburgh Steelers","Miami Dolphins"], answer:"Oakland Raiders", explanation:"Oakland advanced a fumble into the end zone to beat San Diego, prompting an eventual rule change.", sourceId:"raiders-holy-roller" }),

  // Round 3
  q({ id:"nfl-r3-first-draft-idea", league:"nfl", round:"round3", category:"League History", prompt:"Which future NFL commissioner devised the league's original player-draft concept?", choices:["Bert Bell","Pete Rozelle","Joe Carr","Paul Tagliabue"], answer:"Bert Bell", explanation:"Eagles owner Bert Bell proposed the draft to improve competitive balance.", sourceId:"pfhof-1936-draft", sourceUrl:DRAFT_1936 }),
  q({ id:"nfl-r3-first-draft-second-pick-first-player", league:"nfl", round:"round3", category:"Draft Oddities", prompt:"Because Jay Berwanger never played, which No. 2 pick became the first drafted player to actually appear in the NFL?", choices:["Riley Smith","Bill Shakespeare","Joe Stydahar","Tuffy Leemans"], answer:"Riley Smith", explanation:"Boston selected Alabama back Riley Smith second overall in 1936, and he became the first drafted player to play in the league.", sourceId:"pfhof-first-draft", sourceUrl:DRAFT_1936 }),
  q({ id:"nfl-r3-first-draft-team-count", league:"nfl", round:"round3", category:"Draft History", prompt:"How many NFL teams participated in the inaugural 1936 draft?", choices:["9","8","10","12"], answer:"9", explanation:"Owners from the league's nine teams gathered for the first draft.", sourceId:"pfhof-first-draft", sourceUrl:DRAFT_1936 }),
  q({ id:"nfl-r3-first-draft-coverage", league:"nfl", round:"round3", category:"Media History", prompt:"Which statement was true of the first NFL Draft in 1936?", choices:["It had no radio, TV or newspaper coverage","It was broadcast nationally on radio","It was held in a theater before fans","It aired as a newsreel before movies"], answer:"It had no radio, TV or newspaper coverage", explanation:"The first draft was a quiet owners' meeting with no live media coverage.", sourceId:"pfhof-first-draft", sourceUrl:"https://www.profootballhof.com/news/first-nfl-draft-in-1936-was-all-about-sport-not-spectacle" }),
  q({ id:"nfl-r3-berwanger-rights-traded", league:"nfl", round:"round3", category:"Draft Oddities", prompt:"After drafting Jay Berwanger first overall, Philadelphia traded his rights to which team?", choices:["Chicago Bears","Green Bay Packers","New York Giants","Detroit Lions"], answer:"Chicago Bears", explanation:"The Eagles traded Berwanger's rights to George Halas' Chicago Bears, but he still never signed.", sourceId:"pfhof-1936-draft", sourceUrl:DRAFT_1936 }),
  q({ id:"nfl-r3-super-bowl-name-not-official-until", league:"nfl", round:"round3", category:"Super Bowl Lore", prompt:"The league did not officially embrace the 'Super Bowl' name until which game?", choices:["Super Bowl III","Super Bowl II","Super Bowl IV","Super Bowl V"], answer:"Super Bowl III", explanation:"Lamar Hunt recalled that the league resisted the nickname until the third AFL-NFL championship game.", sourceId:"lamar-hunt-super-bowl", sourceUrl:SUPER_BOWL_NAME }),
  q({ id:"nfl-r3-first-super-bowl-mvp", league:"nfl", round:"round3", category:"Super Bowl History", prompt:"Who was named MVP of the first two Super Bowls?", choices:["Bart Starr","Max McGee","Willie Davis","Len Dawson"], answer:"Bart Starr", explanation:"Packers quarterback Bart Starr won MVP honors in both Super Bowl I and Super Bowl II.", sourceId:"super-bowl-mvp-history" }),
  q({ id:"nfl-r3-first-black-qb-super-bowl-win", league:"nfl", round:"round3", category:"Super Bowl History", prompt:"Who became the first Black starting quarterback to win a Super Bowl?", choices:["Doug Williams","Warren Moon","Steve McNair","Russell Wilson"], answer:"Doug Williams", explanation:"Washington quarterback Doug Williams won Super Bowl XXII and was named the game's MVP.", sourceId:"super-bowl-xxii-history" }),
  q({ id:"nfl-r3-longest-nfl-game", league:"nfl", round:"round3", category:"Historic Games", prompt:"The longest game in NFL history was a 1971 playoff between Miami and which team?", choices:["Kansas City Chiefs","Oakland Raiders","Baltimore Colts","Cleveland Browns"], answer:"Kansas City Chiefs", explanation:"Miami beat Kansas City in double overtime on Christmas Day 1971 after 82 minutes and 40 seconds of play.", sourceId:"nfl-longest-game" }),
  q({ id:"nfl-r3-first-regular-season-mexico", league:"nfl", round:"round3", category:"International", prompt:"The NFL's first regular-season game outside the United States was played in 2005 in which city?", choices:["Mexico City","London","Toronto","Tokyo"], answer:"Mexico City", explanation:"Arizona and San Francisco played at Estadio Azteca in the NFL's first regular-season game outside the United States.", sourceId:"nfl-international-history" }),
  q({ id:"nfl-r3-first-london-regular-season", league:"nfl", round:"round3", category:"International", prompt:"Which two teams played in the NFL's first regular-season game in London in 2007?", choices:["Giants and Dolphins","Patriots and Buccaneers","Saints and Chargers","Cowboys and Jaguars"], answer:"Giants and Dolphins", explanation:"The New York Giants beat the Miami Dolphins at Wembley in the first regular-season NFL game in London.", sourceId:"nfl-london-history" }),
  q({ id:"nfl-r3-steagles", league:"nfl", round:"round3", category:"Wartime Football", prompt:"During World War II, which two teams temporarily merged to form the unofficially named 'Steagles'?", choices:["Steelers and Eagles","Steelers and Cardinals","Eagles and Giants","Bears and Cardinals"], answer:"Steelers and Eagles", explanation:"Player shortages led Pittsburgh and Philadelphia to combine for the 1943 season.", sourceId:"nfl-steagles-history" }),

  // Last Call
  q({ id:"nfl-final-first-draft-date", league:"nfl", round:"last-call", category:"Draft History", prompt:"On what date was the first NFL Draft held?", choices:["February 8, 1936","January 1, 1935","April 26, 1937","September 17, 1920"], answer:"February 8, 1936", explanation:"NFL owners conducted the inaugural draft at Philadelphia's Ritz-Carlton Hotel on Feb. 8, 1936.", sourceId:"pfhof-1936-draft", sourceUrl:DRAFT_1936 }),
  q({ id:"nfl-final-first-draft-bear-bryant", league:"nfl", round:"last-call", category:"Draft Oddities", prompt:"Which future legendary college coach was selected in the first NFL Draft but never played in the league?", choices:["Bear Bryant","Woody Hayes","Ara Parseghian","Bud Wilkinson"], answer:"Bear Bryant", explanation:"Paul 'Bear' Bryant was among the 1936 draft selections who never played an NFL game.", sourceId:"pfhof-first-draft", sourceUrl:"https://www.profootballhof.com/news/first-nfl-draft-in-1936-was-all-about-sport-not-spectacle" }),
  q({ id:"nfl-final-super-bowl-original-working-name", league:"nfl", round:"last-call", category:"Super Bowl Lore", prompt:"Before 'Super Bowl' caught on, what formal title was used for the first AFL-NFL championship game?", choices:["AFL-NFL World Championship Game","Pro Football World Series","National Football Championship Classic","AFL-NFL Title Bowl"], answer:"AFL-NFL World Championship Game", explanation:"The first two games were formally promoted as the AFL-NFL World Championship Game before 'Super Bowl' became official.", sourceId:"super-bowl-name-history" }),
  q({ id:"nfl-final-immaculate-opponent", league:"nfl", round:"last-call", category:"Iconic Plays", prompt:"The Immaculate Reception gave Pittsburgh a playoff win over which opponent?", choices:["Oakland Raiders","Miami Dolphins","Cleveland Browns","Baltimore Colts"], answer:"Oakland Raiders", explanation:"Franco Harris' famous touchdown defeated Oakland in the 1972 AFC divisional playoffs.", sourceId:"nfl-immaculate-reception", sourceUrl:IMMACULATE }),
];
