import { barTriviaQuestion, type BarTriviaQuestion } from "../games/barTriviaEngine";

const HEISMAN_MILESTONES = "https://www.heisman.com/about-the-heisman/milestones/";
const HEISMAN_RECORDS = "https://www.heisman.com/voting-records/";
const NCAA_CHAMPS = "https://www.ncaa.com/news/football/article/college-football-national-championship-history";
const USC_TRAVELER = "https://usctrojans.com/sports/2017/6/15/trads-usc-m-fb-mas-html.aspx";
const FSU_OSCEOLA = "https://seminoles.com/sports/2017/7/5/osceola-and-renegade";
const GT_RECK = "https://ramblinwreck.com/news/2026/09/23/reck-day-set-for-oct-10";
const OLE_MISS_GROVE = "https://olemisssports.com/sports/2018/7/20/trads-the-grove-html";
const IOWA_WAVE = "https://hawkeyesports.com/wave";
const BOISE_BLUE = "https://broncosports.com/news/2024/9/13/football-boise-state-celebrates-38th-anniversary-of-the-blue";
const EGG_BOWL = "https://olemisssports.com/news/2026/1/15/football-date-changed-for-2026-egg-bowl-presented-by-facebook";

function q(seed: Parameters<typeof barTriviaQuestion>[0]) {
  return barTriviaQuestion({ ...seed, verifiedAt: "2026-09-28" });
}

export const BAR_TRIVIA_CFB_EVERGREEN_EXPANSION: readonly BarTriviaQuestion[] = [
  // Round 1 — famous sights, traditions and major milestones
  q({ id:"cfb-r1-traveler", league:"cfb", round:"round1", category:"Mascots", prompt:"Traveler, the white horse that circles the Coliseum after USC scores, belongs to which program?", choices:["USC","Texas","Florida State","Oklahoma"], answer:"USC", explanation:"USC's Traveler appears with a Trojan rider and gallops around the Coliseum after Trojan scores.", sourceId:"usc-traveler", sourceUrl:USC_TRAVELER }),
  q({ id:"cfb-r1-osceola-renegade", league:"cfb", round:"round1", category:"Traditions", prompt:"Osceola plants a flaming spear at midfield before home games for which program?", choices:["Florida State","Miami","Florida","Virginia Tech"], answer:"Florida State", explanation:"Florida State's Osceola rides Renegade to midfield and plants a flaming spear before home games.", sourceId:"fsu-osceola-renegade", sourceUrl:FSU_OSCEOLA }),
  q({ id:"cfb-r1-ramblin-reck", league:"cfb", round:"round1", category:"Traditions", prompt:"A vintage car known as the Ramblin' Reck leads which team onto its home field?", choices:["Georgia Tech","Georgia","Purdue","Army"], answer:"Georgia Tech", explanation:"Georgia Tech's Ramblin' Reck leads the Yellow Jackets onto the field before home games.", sourceId:"gt-ramblin-reck", sourceUrl:GT_RECK }),
  q({ id:"cfb-r1-the-grove", league:"cfb", round:"round1", category:"Tailgating", prompt:"The famous tailgating area known as 'The Grove' is found on which campus?", choices:["Ole Miss","Alabama","LSU","Tennessee"], answer:"Ole Miss", explanation:"The Grove is the tree-shaded tailgating heart of Ole Miss football Saturdays.", sourceId:"ole-miss-grove", sourceUrl:OLE_MISS_GROVE }),
  q({ id:"cfb-r1-hawkeye-wave", league:"cfb", round:"round1", category:"Traditions", prompt:"At the end of the first quarter, fans at which stadium turn and wave to children watching from a nearby hospital?", choices:["Kinnick Stadium","Camp Randall Stadium","Beaver Stadium","Neyland Stadium"], answer:"Kinnick Stadium", explanation:"Iowa's Hawkeye Wave has fans and players turn toward the UI Stead Family Children's Hospital after the first quarter.", sourceId:"iowa-wave", sourceUrl:IOWA_WAVE }),
  q({ id:"cfb-r1-blue-turf", league:"cfb", round:"round1", category:"Stadiums", prompt:"Which program is famous for playing home games on an all-blue football field?", choices:["Boise State","Coastal Carolina","Eastern Washington","Memphis"], answer:"Boise State", explanation:"Boise State installed its iconic blue turf in 1986.", sourceId:"boise-blue", sourceUrl:BOISE_BLUE }),
  q({ id:"cfb-r1-first-sophomore-heisman", league:"cfb", round:"round1", category:"Heisman", prompt:"Who became the first sophomore to win the Heisman Trophy?", choices:["Tim Tebow","Lamar Jackson","Sam Bradford","Johnny Manziel"], answer:"Tim Tebow", explanation:"Florida quarterback Tim Tebow became the first sophomore Heisman winner in 2007.", sourceId:"heisman-milestones", sourceUrl:HEISMAN_MILESTONES }),
  q({ id:"cfb-r1-first-freshman-heisman", league:"cfb", round:"round1", category:"Heisman", prompt:"Who became the first freshman to win the Heisman Trophy?", choices:["Johnny Manziel","Jameis Winston","Tim Tebow","Cam Newton"], answer:"Johnny Manziel", explanation:"Texas A&M's Johnny Manziel became the first redshirt freshman to win the Heisman in 2012.", sourceId:"heisman-milestones", sourceUrl:HEISMAN_MILESTONES }),
  q({ id:"cfb-r1-first-wr-heisman", league:"cfb", round:"round1", category:"Heisman", prompt:"Who became the first wide receiver to win the Heisman Trophy?", choices:["Johnny Rodgers","Tim Brown","Desmond Howard","DeVonta Smith"], answer:"Johnny Rodgers", explanation:"Nebraska's Johnny Rodgers became the first wide receiver to win the Heisman in 1972.", sourceId:"heisman-milestones", sourceUrl:HEISMAN_MILESTONES }),
  q({ id:"cfb-r1-first-defensive-heisman", league:"cfb", round:"round1", category:"Heisman", prompt:"Which Michigan star became the first primarily defensive player to win the Heisman?", choices:["Charles Woodson","Desmond Howard","Aidan Hutchinson","Jabrill Peppers"], answer:"Charles Woodson", explanation:"Charles Woodson won the 1997 Heisman as a cornerback who also contributed on offense and returns.", sourceId:"heisman-milestones", sourceUrl:HEISMAN_MILESTONES }),
  q({ id:"cfb-r1-first-cfp-champion", league:"cfb", round:"round1", category:"National Championships", prompt:"Which school won the first College Football Playoff national championship?", choices:["Ohio State","Alabama","Oregon","Clemson"], answer:"Ohio State", explanation:"Ohio State won the 2014 season's inaugural College Football Playoff championship.", sourceId:"ncaa-championship-history", sourceUrl:NCAA_CHAMPS }),
  q({ id:"cfb-r1-egg-bowl", league:"cfb", round:"round1", category:"Rivalries", prompt:"The annual Ole Miss–Mississippi State rivalry is played for which trophy?", choices:["Golden Egg","Golden Boot","Magnolia Cup","Governor's Cup"], answer:"Golden Egg", explanation:"Ole Miss and Mississippi State contest the Battle for the Golden Egg, commonly called the Egg Bowl.", sourceId:"ole-miss-egg-bowl", sourceUrl:EGG_BOWL }),

  // Round 2 — origins behind familiar traditions
  q({ id:"cfb-r2-traveler-debut-year", league:"cfb", round:"round2", category:"Mascot History", prompt:"USC's Traveler tradition began during which decade?", choices:["1960s","1940s","1980s","2000s"], answer:"1960s", explanation:"Traveler first appeared at a USC football game in 1961.", sourceId:"usc-traveler", sourceUrl:USC_TRAVELER }),
  q({ id:"cfb-r2-traveler-debut-opponent", league:"cfb", round:"round2", category:"Mascot History", prompt:"USC's Traveler first appeared at a football game in 1961 against which opponent?", choices:["Georgia Tech","Notre Dame","UCLA","Stanford"], answer:"Georgia Tech", explanation:"Traveler debuted at USC's 1961 home opener against Georgia Tech.", sourceId:"usc-traveler", sourceUrl:USC_TRAVELER }),
  q({ id:"cfb-r2-osceola-start-year", league:"cfb", round:"round2", category:"Tradition Origins", prompt:"Florida State's Osceola and Renegade pregame tradition began in which decade?", choices:["1970s","1950s","1990s","2000s"], answer:"1970s", explanation:"The tradition began in 1978 before a Florida State home game.", sourceId:"fsu-osceola-renegade", sourceUrl:FSU_OSCEOLA }),
  q({ id:"cfb-r2-osceola-first-opponent", league:"cfb", round:"round2", category:"Tradition Origins", prompt:"Osceola and Renegade made their Florida State debut before a 1978 game against which school?", choices:["Oklahoma State","Florida","Miami","Clemson"], answer:"Oklahoma State", explanation:"The first Osceola and Renegade ride came before Florida State played Oklahoma State on Sept. 16, 1978.", sourceId:"fsu-osceola-renegade", sourceUrl:FSU_OSCEOLA }),
  q({ id:"cfb-r2-reck-car", league:"cfb", round:"round2", category:"Tradition Origins", prompt:"Georgia Tech's official Ramblin' Reck is what kind of vehicle?", choices:["1930 Ford Model A","1948 Jeep Willys","1927 Chevrolet Roadster","1955 Ford Thunderbird"], answer:"1930 Ford Model A", explanation:"The official Ramblin' Reck is a restored 1930 Ford Model A Sport Coupe.", sourceId:"gt-ramblin-reck", sourceUrl:GT_RECK }),
  q({ id:"cfb-r2-reck-football-debut", league:"cfb", round:"round2", category:"Tradition Origins", prompt:"The Ramblin' Reck first led Georgia Tech's football team onto the field in 1961 against which school?", choices:["Rice","Georgia","Auburn","Clemson"], answer:"Rice", explanation:"The official Reck made its football debut against Rice on Sept. 30, 1961.", sourceId:"gt-ramblin-reck", sourceUrl:GT_RECK }),
  q({ id:"cfb-r2-grove-size", league:"cfb", round:"round2", category:"Tailgating", prompt:"Ole Miss describes The Grove as approximately how large?", choices:["10 acres","2 acres","25 acres","50 acres"], answer:"10 acres", explanation:"The Grove is a roughly 10-acre grassy, tree-shaded area in the center of the Ole Miss campus.", sourceId:"ole-miss-grove", sourceUrl:OLE_MISS_GROVE }),
  q({ id:"cfb-r2-grove-walk-arch", league:"cfb", round:"round2", category:"Tradition Origins", prompt:"What is the name of the arch where Ole Miss players begin their walk through The Grove?", choices:["Walk of Champions","Victory Gate","Rebel Arch","Champions Portal"], answer:"Walk of Champions", explanation:"The Walk of Champions arch marks the start of Ole Miss' pregame team walk through The Grove.", sourceId:"ole-miss-grove", sourceUrl:OLE_MISS_GROVE }),
  q({ id:"cfb-r2-wave-born", league:"cfb", round:"round2", category:"Tradition Origins", prompt:"Iowa's Hawkeye Wave tradition began in which year?", choices:["2017","2007","1997","2021"], answer:"2017", explanation:"The Wave began during the 2017 season after the nearby children's hospital opened.", sourceId:"iowa-wave", sourceUrl:IOWA_WAVE }),
  q({ id:"cfb-r2-blue-installed", league:"cfb", round:"round2", category:"Stadium History", prompt:"Boise State first installed its famous blue turf in which year?", choices:["1986","1976","1996","2006"], answer:"1986", explanation:"Boise State debuted the first full blue artificial football field in 1986.", sourceId:"boise-blue", sourceUrl:BOISE_BLUE }),
  q({ id:"cfb-r2-last-service-heisman", league:"cfb", round:"round2", category:"Heisman", prompt:"Who is the most recent Service Academy player to win the Heisman Trophy?", choices:["Roger Staubach","Doc Blanchard","Glenn Davis","Pete Dawkins"], answer:"Roger Staubach", explanation:"Navy quarterback Roger Staubach won in 1963 and remains the most recent Service Academy Heisman winner.", sourceId:"heisman-milestones", sourceUrl:HEISMAN_MILESTONES }),
  q({ id:"cfb-r2-heisman-tv-debut", league:"cfb", round:"round2", category:"Broadcast", prompt:"The Heisman Trophy ceremony made its television debut in which decade?", choices:["1970s","1950s","1980s","1990s"], answer:"1970s", explanation:"The Heisman presentation made its television debut in 1977.", sourceId:"heisman-milestones", sourceUrl:HEISMAN_MILESTONES }),

  // Round 3 — championship-era oddities and deeper Heisman lore
  q({ id:"cfb-r3-spurrier-coach-heisman", league:"cfb", round:"round3", category:"Heisman History", prompt:"Which former Heisman winner became the first to coach another Heisman winner?", choices:["Steve Spurrier","Frank Broyles","Pat Sullivan","Jim Plunkett"], answer:"Steve Spurrier", explanation:"Steve Spurrier won the Heisman as a Florida player and later coached 1996 winner Danny Wuerffel.", sourceId:"heisman-milestones", sourceUrl:HEISMAN_MILESTONES }),
  q({ id:"cfb-r3-1997-split-title", league:"cfb", round:"round3", category:"National Championships", prompt:"Which two programs split major national championship recognition for the 1997 season?", choices:["Michigan and Nebraska","Florida State and Florida","Tennessee and Ohio State","Miami and Washington"], answer:"Michigan and Nebraska", explanation:"Michigan and Nebraska both received major-selector national championship recognition for 1997.", sourceId:"ncaa-championship-history", sourceUrl:NCAA_CHAMPS }),
  q({ id:"cfb-r3-1990-split-title", league:"cfb", round:"round3", category:"National Championships", prompt:"Which two programs split major national championship recognition for the 1990 season?", choices:["Colorado and Georgia Tech","Miami and Washington","Notre Dame and Colorado","Nebraska and Florida State"], answer:"Colorado and Georgia Tech", explanation:"Colorado and Georgia Tech split major-selector national championship recognition in 1990.", sourceId:"ncaa-championship-history", sourceUrl:NCAA_CHAMPS }),
  q({ id:"cfb-r3-1991-split-title", league:"cfb", round:"round3", category:"National Championships", prompt:"Which two programs split major national championship recognition for the 1991 season?", choices:["Washington and Miami","Michigan and Nebraska","Alabama and Miami","Florida State and Notre Dame"], answer:"Washington and Miami", explanation:"Washington and Miami both received major-selector national championship recognition for 1991.", sourceId:"ncaa-championship-history", sourceUrl:NCAA_CHAMPS }),
  q({ id:"cfb-r3-2003-split-title", league:"cfb", round:"round3", category:"National Championships", prompt:"Which two programs split major national championship recognition for the 2003 season?", choices:["LSU and USC","Oklahoma and LSU","USC and Oklahoma","Miami and Ohio State"], answer:"LSU and USC", explanation:"LSU won the BCS title while USC finished No. 1 in other major selections, producing a split 2003 championship.", sourceId:"ncaa-championship-history", sourceUrl:NCAA_CHAMPS }),
  q({ id:"cfb-r3-1984-champion", league:"cfb", round:"round3", category:"National Championships", prompt:"Which program finished the 1984 season as the consensus national champion?", choices:["BYU","Washington","Oklahoma","Nebraska"], answer:"BYU", explanation:"BYU is listed by the NCAA as the 1984 national champion.", sourceId:"ncaa-championship-history", sourceUrl:NCAA_CHAMPS }),
  q({ id:"cfb-r3-first-bcs-champion", league:"cfb", round:"round3", category:"National Championships", prompt:"Which program won the national championship in the first BCS season?", choices:["Tennessee","Florida State","Nebraska","Miami"], answer:"Tennessee", explanation:"Tennessee won the 1998 season national championship, the first under the BCS system.", sourceId:"ncaa-championship-history", sourceUrl:NCAA_CHAMPS }),
  q({ id:"cfb-r3-blue-first-nongreen", league:"cfb", round:"round3", category:"Stadium History", prompt:"Boise State's blue turf became the first artificial football field in the country to do what?", choices:["Use a full non-green color","Use no painted yard lines","Use orange hash marks","Use two different turf colors by half"], answer:"Use a full non-green color", explanation:"Boise State's 1986 blue surface was the first full non-green artificial football field in the country.", sourceId:"boise-blue", sourceUrl:BOISE_BLUE }),
  q({ id:"cfb-r3-blue-first-game", league:"cfb", round:"round3", category:"Stadium History", prompt:"Boise State christened its original blue turf with a 74–0 win over which opponent?", choices:["Humboldt State","Idaho","Nevada","Fresno State"], answer:"Humboldt State", explanation:"The first game on The Blue was a 74–0 Boise State win over Humboldt State in 1986.", sourceId:"boise-blue", sourceUrl:BOISE_BLUE }),
  q({ id:"cfb-r3-heisman-first-wr-school", league:"cfb", round:"round3", category:"Heisman", prompt:"The first wide receiver to win the Heisman, Johnny Rodgers, played for which school?", choices:["Nebraska","Oklahoma","Notre Dame","USC"], answer:"Nebraska", explanation:"Johnny Rodgers won Nebraska's first Heisman Trophy in 1972.", sourceId:"heisman-milestones", sourceUrl:HEISMAN_MILESTONES }),
  q({ id:"cfb-r3-heisman-first-freshman-school", league:"cfb", round:"round3", category:"Heisman", prompt:"The first freshman Heisman winner represented which school?", choices:["Texas A&M","Florida State","Florida","Auburn"], answer:"Texas A&M", explanation:"Johnny Manziel won the 2012 Heisman as a redshirt freshman at Texas A&M.", sourceId:"heisman-milestones", sourceUrl:HEISMAN_MILESTONES }),
  q({ id:"cfb-r3-heisman-first-defensive-school", league:"cfb", round:"round3", category:"Heisman", prompt:"The first primarily defensive Heisman winner represented which school?", choices:["Michigan","Ohio State","Notre Dame","USC"], answer:"Michigan", explanation:"Michigan cornerback Charles Woodson won the Heisman in 1997.", sourceId:"heisman-milestones", sourceUrl:HEISMAN_MILESTONES }),

  // Last Call
  q({ id:"cfb-final-heisman-number-99", league:"cfb", round:"last-call", category:"Heisman Oddities", prompt:"Which Heisman winner wore jersey No. 99?", choices:["Jay Berwanger","Tom Harmon","Doc Blanchard","Leon Hart"], answer:"Jay Berwanger", explanation:"The Heisman record book lists inaugural winner Jay Berwanger of Chicago as No. 99.", sourceId:"heisman-voting-records", sourceUrl:HEISMAN_RECORDS }),
  q({ id:"cfb-final-heisman-threeway-player", league:"cfb", round:"last-call", category:"Heisman History", prompt:"Which 1997 Heisman winner was celebrated as a three-way player on defense, offense and special teams?", choices:["Charles Woodson","Randy Moss","Peyton Manning","Ryan Leaf"], answer:"Charles Woodson", explanation:"Charles Woodson's defensive excellence plus offensive and return contributions helped make him the first primarily defensive Heisman winner.", sourceId:"heisman-milestones", sourceUrl:HEISMAN_MILESTONES }),
  q({ id:"cfb-final-egg-trophy-introduced", league:"cfb", round:"last-call", category:"Rivalry History", prompt:"The Golden Egg trophy for Ole Miss–Mississippi State was introduced in which decade?", choices:["1920s","1940s","1960s","1980s"], answer:"1920s", explanation:"The Golden Egg trophy was introduced in 1927.", sourceId:"ole-miss-egg-bowl", sourceUrl:EGG_BOWL }),
  q({ id:"cfb-final-reck-original-newspaper", league:"cfb", round:"last-call", category:"Tradition Origins", prompt:"The nickname that evolved into Georgia Tech's 'Ramblin' Reck' was first popularized by which campus publication?", choices:["The Technique","The Red & Black","The Chronicle","The Plainsman"], answer:"The Technique", explanation:"Georgia Tech's student newspaper, The Technique, used the Ramblin' Reck name in the 1920s.", sourceId:"gt-ramblin-reck", sourceUrl:GT_RECK }),
];
