import { barTriviaQuestion, type BarTriviaQuestion } from "../games/barTriviaEngine";

const HOF = "https://www.ufc.com/news/ufc-hall-fame-faq";
const UFC30 = "https://www.ufc.com/30";
const TUF1 = "https://www.ufc.com/news/celebrating-10-years-ultimate-fighter";

function q(seed: Parameters<typeof barTriviaQuestion>[0]) {
  return barTriviaQuestion({ ...seed, verifiedAt: "2026-09-28" });
}

export const BAR_TRIVIA_UFC_EVERGREEN_WAVE_5: readonly BarTriviaQuestion[] = [
  // Round 1 — TUF faces, personalities and recognizable UFC culture
  q({ id:"ufc-r1-bisping-tuf3", league:"ufc", round:"round1", category:"The Ultimate Fighter", prompt:"Which future UFC champion won the light heavyweight tournament on The Ultimate Fighter 3?", choices:["Michael Bisping","Rashad Evans","Forrest Griffin","Matt Serra"], answer:"Michael Bisping", explanation:"Michael Bisping won the light heavyweight bracket on TUF 3.", sourceId:"tuf3-history" }),
  q({ id:"ufc-r1-nate-diaz-tuf5", league:"ufc", round:"round1", category:"The Ultimate Fighter", prompt:"Which future fan favorite won The Ultimate Fighter 5 lightweight tournament?", choices:["Nate Diaz","Gray Maynard","Joe Lauzon","Cole Miller"], answer:"Nate Diaz", explanation:"Nate Diaz won the TUF 5 lightweight final.", sourceId:"tuf5-history" }),
  q({ id:"ufc-r1-rashad-tuf2", league:"ufc", round:"round1", category:"The Ultimate Fighter", prompt:"Which future light heavyweight champion won the heavyweight tournament on The Ultimate Fighter 2?", choices:["Rashad Evans","Keith Jardine","Matt Hamill","Joe Stevenson"], answer:"Rashad Evans", explanation:"Rashad Evans won the heavyweight bracket on TUF 2 before later becoming UFC champion.", sourceId:"tuf2-history" }),
  q({ id:"ufc-r1-serra-tuf4", league:"ufc", round:"round1", category:"The Ultimate Fighter", prompt:"Which fighter won The Ultimate Fighter 4 and then shocked Georges St-Pierre for the title?", choices:["Matt Serra","Chris Lytle","Patrick Cote","Travis Lutter"], answer:"Matt Serra", explanation:"Matt Serra won the welterweight bracket on TUF 4, earning the title shot that led to his famous upset.", sourceId:"tuf4-history" }),
  q({ id:"ufc-r1-roy-nelson-tuf10", league:"ufc", round:"round1", category:"The Ultimate Fighter", prompt:"Which heavyweight known as 'Big Country' won The Ultimate Fighter 10?", choices:["Roy Nelson","Brendan Schaub","Matt Mitrione","Kimbo Slice"], answer:"Roy Nelson", explanation:"Roy Nelson won the TUF 10 heavyweight tournament.", sourceId:"tuf10-history" }),
  q({ id:"ufc-r1-tony-tuf13", league:"ufc", round:"round1", category:"The Ultimate Fighter", prompt:"Which future interim lightweight champion won The Ultimate Fighter 13?", choices:["Tony Ferguson","Michael Johnson","Ramsey Nijem","Ryan McGillivray"], answer:"Tony Ferguson", explanation:"Tony Ferguson won the welterweight tournament on TUF 13.", sourceId:"tuf13-history" }),
  q({ id:"ufc-r1-gastelum-tuf17", league:"ufc", round:"round1", category:"The Ultimate Fighter", prompt:"Which fighter upset Uriah Hall to win The Ultimate Fighter 17?", choices:["Kelvin Gastelum","Robert Whittaker","Luke Barnatt","Josh Samman"], answer:"Kelvin Gastelum", explanation:"Kelvin Gastelum edged Uriah Hall by split decision in the TUF 17 finale.", sourceId:"tuf17-history" }),
  q({ id:"ufc-r1-pena-tuf18", league:"ufc", round:"round1", category:"The Ultimate Fighter", prompt:"Who became the first female winner of The Ultimate Fighter?", choices:["Julianna Pena","Raquel Pennington","Rose Namajunas","Jessica Rakoczy"], answer:"Julianna Pena", explanation:"Julianna Pena won the women's bantamweight tournament on TUF 18.", sourceId:"tuf18-history" }),
  q({ id:"ufc-r1-usman-tuf21", league:"ufc", round:"round1", category:"The Ultimate Fighter", prompt:"Which future welterweight champion won The Ultimate Fighter 21?", choices:["Kamaru Usman","Colby Covington","Leon Edwards","Vicente Luque"], answer:"Kamaru Usman", explanation:"Kamaru Usman won TUF 21 before eventually becoming UFC welterweight champion.", sourceId:"tuf21-history" }),
  q({ id:"ufc-r1-big-john", league:"ufc", round:"round1", category:"Officials", prompt:"Which referee became an early UFC icon under the nickname 'Big John'?", choices:["John McCarthy","Herb Dean","Mario Yamasaki","Dan Miragliotta"], answer:"John McCarthy", explanation:"John 'Big John' McCarthy refereed many of the promotion's earliest and most famous bouts.", sourceId:"ufc-officials-history" }),
  q({ id:"ufc-r1-herb-dean", league:"ufc", round:"round1", category:"Officials", prompt:"Which longtime referee has become one of the UFC's most recognizable officials?", choices:["Herb Dean","Bruce Buffer","Joe Rogan","Marc Goddard"], answer:"Herb Dean", explanation:"Herb Dean has officiated championship fights and major UFC events for decades.", sourceId:"ufc-officials-history" }),
  q({ id:"ufc-r1-voice-octagon", league:"ufc", round:"round1", category:"Broadcast Personalities", prompt:"Who is known as the 'Voice of the Octagon' and announces fighters before UFC bouts?", choices:["Bruce Buffer","Jon Anik","Joe Rogan","Mike Goldberg"], answer:"Bruce Buffer", explanation:"Bruce Buffer is UFC's longtime Octagon announcer.", sourceId:"ufc-buffer-history" }),
  q({ id:"ufc-r1-rogan-role", league:"ufc", round:"round1", category:"Broadcast Personalities", prompt:"Joe Rogan is best known in UFC broadcasts for which role?", choices:["Color commentator","Ring announcer","Play-by-play announcer only","Referee"], answer:"Color commentator", explanation:"Rogan has long served as a UFC color commentator and interviewer.", sourceId:"ufc-broadcast-history" }),
  q({ id:"ufc-r1-anik-role", league:"ufc", round:"round1", category:"Broadcast Personalities", prompt:"Jon Anik is primarily known in UFC broadcasts as a...", choices:["Play-by-play announcer","Referee","Ring announcer","Matchmaker"], answer:"Play-by-play announcer", explanation:"Jon Anik has served as UFC's lead play-by-play voice on many major cards.", sourceId:"ufc-broadcast-history" }),
  q({ id:"ufc-r1-ufc205-venue", league:"ufc", round:"round1", category:"Venues", prompt:"UFC 205 was the promotion's first event at which famous arena?", choices:["Madison Square Garden","Barclays Center","TD Garden","United Center"], answer:"Madison Square Garden", explanation:"UFC 205 marked the promotion's long-awaited debut at Madison Square Garden.", sourceId:"ufc205-history" }),

  // Round 2 — venues, international expansion and Hall of Fame fights
  q({ id:"ufc-r2-ufc129-city", league:"ufc", round:"round2", category:"International History", prompt:"UFC 129, the promotion's first stadium-scale Canadian event, took place in which city?", choices:["Toronto","Montreal","Vancouver","Calgary"], answer:"Toronto", explanation:"UFC 129 filled Rogers Centre in Toronto.", sourceId:"ufc129-history" }),
  q({ id:"ufc-r2-ufc193-city-melbourne", league:"ufc", round:"round2", category:"International History", prompt:"Which Australian city hosted UFC 193, where Holly Holm upset Ronda Rousey?", choices:["Melbourne","Sydney","Brisbane","Perth"], answer:"Melbourne", explanation:"UFC 193 took place at Etihad Stadium in Melbourne.", sourceId:"ufc193-history" }),
  q({ id:"ufc-r2-ufc243-city", league:"ufc", round:"round2", category:"International History", prompt:"UFC 243, headlined by Whittaker vs. Adesanya, was held in which city?", choices:["Melbourne","Sydney","Auckland","Perth"], answer:"Melbourne", explanation:"UFC 243 took place at Marvel Stadium in Melbourne.", sourceId:"ufc243-history" }),
  q({ id:"ufc-r2-first-canada", league:"ufc", round:"round2", category:"International History", prompt:"Which numbered event was the UFC's first card in Canada?", choices:["UFC 83","UFC 79","UFC 97","UFC 113"], answer:"UFC 83", explanation:"UFC 83 in Montreal featured Georges St-Pierre vs. Matt Serra II.", sourceId:"ufc83-history" }),
  q({ id:"ufc-r2-first-australia", league:"ufc", round:"round2", category:"International History", prompt:"Which numbered event marked UFC's first trip to Australia?", choices:["UFC 110","UFC 127","UFC 193","UFC 243"], answer:"UFC 110", explanation:"UFC 110 took place in Sydney in February 2010.", sourceId:"ufc110-history" }),
  q({ id:"ufc-r2-first-mexico", league:"ufc", round:"round2", category:"International History", prompt:"Which numbered event marked UFC's first event in Mexico?", choices:["UFC 180","UFC 188","UFC 192","UFC 197"], answer:"UFC 180", explanation:"UFC 180 took place in Mexico City in 2014.", sourceId:"ufc180-history" }),
  q({ id:"ufc-r2-first-france", league:"ufc", round:"round2", category:"International History", prompt:"UFC's first event in France was headlined by Ciryl Gane against whom?", choices:["Tai Tuivasa","Derrick Lewis","Alexander Volkov","Serghei Spivac"], answer:"Tai Tuivasa", explanation:"Gane vs. Tuivasa headlined UFC's first Paris event in 2022.", sourceId:"ufc-paris-history" }),
  q({ id:"ufc-r2-ufc83-main", league:"ufc", round:"round2", category:"Milestone Events", prompt:"Who did Georges St-Pierre defeat in the main event of UFC 83 in Montreal?", choices:["Matt Serra","Matt Hughes","BJ Penn","Josh Koscheck"], answer:"Matt Serra", explanation:"St-Pierre avenged his upset loss to Serra and unified the welterweight title.", sourceId:"ufc83-history" }),
  q({ id:"ufc-r2-lawler-macdonald-event", league:"ufc", round:"round2", category:"Hall of Fame Fights", prompt:"Robbie Lawler vs. Rory MacDonald II took place at which event?", choices:["UFC 189","UFC 181","UFC 195","UFC 201"], answer:"UFC 189", explanation:"Their brutal welterweight title fight at UFC 189 entered the Hall of Fame Fight Wing.", sourceId:"ufc-hof", sourceUrl:HOF }),
  q({ id:"ufc-r2-hughes-trigg-event", league:"ufc", round:"round2", category:"Hall of Fame Fights", prompt:"Matt Hughes vs. Frank Trigg II took place at which event?", choices:["UFC 52","UFC 50","UFC 54","UFC 60"], answer:"UFC 52", explanation:"Hughes' dramatic comeback against Trigg became a Hall of Fame Fight Wing bout.", sourceId:"ufc-hof", sourceUrl:HOF }),
  q({ id:"ufc-r2-hendo-shogun-event", league:"ufc", round:"round2", category:"Hall of Fame Fights", prompt:"Dan Henderson vs. Mauricio 'Shogun' Rua I took place at which event?", choices:["UFC 139","UFC 145","UFC 128","UFC 157"], answer:"UFC 139", explanation:"Their five-round war headlined UFC 139 and later entered the Hall of Fame.", sourceId:"ufc-hof", sourceUrl:HOF }),
  q({ id:"ufc-r2-sanchez-guida-event", league:"ufc", round:"round2", category:"Hall of Fame Fights", prompt:"Diego Sanchez vs. Clay Guida took place at the finale of which season of The Ultimate Fighter?", choices:["Season 9","Season 5","Season 7","Season 11"], answer:"Season 9", explanation:"Their 2009 classic headlined The Ultimate Fighter 9 Finale.", sourceId:"ufc-hof", sourceUrl:HOF }),
  q({ id:"ufc-r2-jones-gus-event", league:"ufc", round:"round2", category:"Hall of Fame Fights", prompt:"Jon Jones vs. Alexander Gustafsson I took place at which event?", choices:["UFC 165","UFC 172","UFC 182","UFC 214"], answer:"UFC 165", explanation:"Their 2013 light heavyweight title fight became a Hall of Fame classic.", sourceId:"ufc-hof", sourceUrl:HOF }),
  q({ id:"ufc-r2-swanson-choi-event", league:"ufc", round:"round2", category:"Hall of Fame Fights", prompt:"Cub Swanson vs. Doo Ho Choi took place at which numbered event?", choices:["UFC 206","UFC 199","UFC 214","UFC 217"], answer:"UFC 206", explanation:"Their action-packed 2016 fight became a Hall of Fame Fight Wing selection.", sourceId:"ufc-hof", sourceUrl:HOF }),
  q({ id:"ufc-r2-first-msg-year", league:"ufc", round:"round2", category:"Milestone Events", prompt:"UFC first held an event at Madison Square Garden in which year?", choices:["2016","2014","2018","2012"], answer:"2016", explanation:"UFC 205 brought the Octagon to Madison Square Garden in November 2016.", sourceId:"ufc205-history" }),

  // Round 3 — TUF history and Hall of Fame structure
  q({ id:"ufc-r3-tuf3-other-winner", league:"ufc", round:"round3", category:"The Ultimate Fighter", prompt:"Alongside Michael Bisping, who won the other tournament on The Ultimate Fighter 3?", choices:["Kendall Grove","Ed Herman","Matt Hamill","Ross Pointon"], answer:"Kendall Grove", explanation:"Kendall Grove won the middleweight tournament on TUF 3.", sourceId:"tuf3-history" }),
  q({ id:"ufc-r3-tuf4-other-winner", league:"ufc", round:"round3", category:"The Ultimate Fighter", prompt:"Alongside Matt Serra, who won the other tournament on The Ultimate Fighter 4?", choices:["Travis Lutter","Chris Lytle","Patrick Cote","Pete Sell"], answer:"Travis Lutter", explanation:"Travis Lutter won the middleweight bracket on the comeback season.", sourceId:"tuf4-history" }),
  q({ id:"ufc-r3-tuf18-male-winner", league:"ufc", round:"round3", category:"The Ultimate Fighter", prompt:"Who won the men's bantamweight tournament on The Ultimate Fighter 18?", choices:["Chris Holdsworth","TJ Dillashaw","John Dodson","Michael Chiesa"], answer:"Chris Holdsworth", explanation:"Chris Holdsworth won the men's bracket while Julianna Pena won the women's bracket.", sourceId:"tuf18-history" }),
  q({ id:"ufc-r3-tuf20-runnerup", league:"ufc", round:"round3", category:"The Ultimate Fighter", prompt:"Carla Esparza beat whom in the TUF 20 finale to become inaugural strawweight champion?", choices:["Rose Namajunas","Joanna Jedrzejczyk","Claudia Gadelha","Jessica Penne"], answer:"Rose Namajunas", explanation:"Esparza submitted Rose Namajunas in the TUF 20 Finale.", sourceId:"tuf20-history" }),
  q({ id:"ufc-r3-tuf21-format", league:"ufc", round:"round3", category:"The Ultimate Fighter", prompt:"The Ultimate Fighter 21 was built around a rivalry between American Top Team and which gym?", choices:["Blackzilians","AKA","Jackson-Wink","Team Alpha Male"], answer:"Blackzilians", explanation:"TUF 21 used a gym-versus-gym format featuring ATT and the Blackzilians.", sourceId:"tuf21-history" }),
  q({ id:"ufc-r3-hof-pioneer-cutoff", league:"ufc", round:"round3", category:"Hall of Fame", prompt:"The UFC Hall of Fame uses which event as the dividing line between its Pioneer and Modern wings?", choices:["UFC 28","UFC 1","UFC 40","UFC 50"], answer:"UFC 28", explanation:"UFC 28 on Nov. 17, 2000 marks the Hall of Fame era cutoff tied to the Unified Rules.", sourceId:"ufc-hof", sourceUrl:HOF }),
  q({ id:"ufc-r3-hof-modern-bisping", league:"ufc", round:"round3", category:"Hall of Fame", prompt:"Michael Bisping is inducted in which UFC Hall of Fame wing?", choices:["Modern Wing","Pioneer Wing","Contributors Wing","Fight Wing"], answer:"Modern Wing", explanation:"Bisping entered the Modern Wing in 2019.", sourceId:"ufc-hof-bisping" }),
  q({ id:"ufc-r3-hof-gracie-wing", league:"ufc", round:"round3", category:"Hall of Fame", prompt:"Royce Gracie belongs to which UFC Hall of Fame wing?", choices:["Pioneer Wing","Modern Wing","Contributors Wing","Fight Wing only"], answer:"Pioneer Wing", explanation:"Gracie's career belongs to the Hall of Fame's Pioneer era.", sourceId:"ufc-hof", sourceUrl:HOF }),
  q({ id:"ufc-r3-hof-mask-wing", league:"ufc", round:"round3", category:"Hall of Fame", prompt:"TapouT co-founder Charles 'Mask' Lewis is honored in which Hall of Fame wing?", choices:["Contributors Wing","Pioneer Wing","Modern Wing","Fight Wing"], answer:"Contributors Wing", explanation:"Mask Lewis is recognized for his impact outside the cage in the Contributors Wing.", sourceId:"ufc-hof", sourceUrl:HOF }),
  q({ id:"ufc-r3-hof-fight-first", league:"ufc", round:"round3", category:"Hall of Fame", prompt:"Which bout was the first fight inducted into the UFC Hall of Fame?", choices:["Forrest Griffin vs. Stephan Bonnar I","Matt Hughes vs. Frank Trigg II","Dan Henderson vs. Shogun Rua I","Robbie Lawler vs. Rory MacDonald II"], answer:"Forrest Griffin vs. Stephan Bonnar I", explanation:"The landmark TUF 1 Finale bout inaugurated the Fight Wing.", sourceId:"ufc-hof", sourceUrl:HOF }),
  q({ id:"ufc-r3-first-canada-city", league:"ufc", round:"round3", category:"International History", prompt:"The UFC's first Canadian event, UFC 83, took place in which city?", choices:["Montreal","Toronto","Vancouver","Quebec City"], answer:"Montreal", explanation:"UFC 83 was held at the Bell Centre in Montreal.", sourceId:"ufc83-history" }),
  q({ id:"ufc-r3-first-australia-city", league:"ufc", round:"round3", category:"International History", prompt:"The UFC's first Australian event took place in which city?", choices:["Sydney","Melbourne","Perth","Brisbane"], answer:"Sydney", explanation:"UFC 110 was staged in Sydney in 2010.", sourceId:"ufc110-history" }),
  q({ id:"ufc-r3-first-mexico-city", league:"ufc", round:"round3", category:"International History", prompt:"UFC's first event in Mexico was held in which city?", choices:["Mexico City","Monterrey","Guadalajara","Tijuana"], answer:"Mexico City", explanation:"UFC 180 took place in Mexico City in 2014.", sourceId:"ufc180-history" }),
  q({ id:"ufc-r3-ufc180-interim", league:"ufc", round:"round3", category:"Milestone Events", prompt:"Fabricio Werdum won an interim heavyweight title at UFC 180 by stopping whom?", choices:["Mark Hunt","Cain Velasquez","Junior dos Santos","Travis Browne"], answer:"Mark Hunt", explanation:"Werdum stopped Mark Hunt with a flying knee and follow-up strikes.", sourceId:"ufc180-history" }),
  q({ id:"ufc-r3-ufc129-main", league:"ufc", round:"round3", category:"Milestone Events", prompt:"Which welterweight title fight headlined UFC 129 in Toronto?", choices:["Georges St-Pierre vs. Jake Shields","Georges St-Pierre vs. Josh Koscheck","Matt Hughes vs. BJ Penn","Carlos Condit vs. Nick Diaz"], answer:"Georges St-Pierre vs. Jake Shields", explanation:"GSP defended his title against Jake Shields before a massive Toronto crowd.", sourceId:"ufc129-history" }),
  q({ id:"ufc-r3-ufc193-venue-name", league:"ufc", round:"round3", category:"Venues", prompt:"UFC 193 took place at a Melbourne stadium then known as what?", choices:["Etihad Stadium","Marvel Stadium","Rod Laver Arena","MCG"], answer:"Etihad Stadium", explanation:"The venue was called Etihad Stadium at the time of Rousey vs. Holm.", sourceId:"ufc193-history" }),
  q({ id:"ufc-r3-ufc243-venue-name", league:"ufc", round:"round3", category:"Venues", prompt:"UFC 243 took place at which Melbourne venue?", choices:["Marvel Stadium","Rod Laver Arena","Etihad Stadium","MCG"], answer:"Marvel Stadium", explanation:"Whittaker vs. Adesanya headlined UFC 243 at Marvel Stadium.", sourceId:"ufc243-history" }),
  q({ id:"ufc-r3-griffin-bonnar-year", league:"ufc", round:"round3", category:"The Ultimate Fighter", prompt:"Forrest Griffin vs. Stephan Bonnar I took place in which year?", choices:["2005","2003","2007","2009"], answer:"2005", explanation:"The TUF 1 Finale aired in April 2005.", sourceId:"tuf1-history", sourceUrl:TUF1 }),
  q({ id:"ufc-r3-tuf1-network", league:"ufc", round:"round3", category:"Broadcast History", prompt:"The first season of The Ultimate Fighter originally aired on which network?", choices:["Spike TV","ESPN","FX","Fox Sports 1"], answer:"Spike TV", explanation:"TUF debuted on Spike TV in 2005 and helped expand UFC's mainstream audience.", sourceId:"tuf1-history", sourceUrl:TUF1 }),
  q({ id:"ufc-r3-ufc205-state", league:"ufc", round:"round3", category:"Legalization History", prompt:"UFC 205 became possible after professional MMA was legalized in which state?", choices:["New York","New Jersey","Massachusetts","Pennsylvania"], answer:"New York", explanation:"New York legalized professional MMA in 2016, allowing UFC to debut at Madison Square Garden.", sourceId:"ufc205-history" }),

  // Last Call
  q({ id:"ufc-final-tuf1-network", league:"ufc", round:"last-call", category:"Broadcast History", prompt:"Which cable network aired the original season of The Ultimate Fighter?", choices:["Spike TV","FX","ESPN2","Versus"], answer:"Spike TV", explanation:"The show premiered on Spike TV in 2005.", sourceId:"tuf1-history", sourceUrl:TUF1 }),
  q({ id:"ufc-final-first-canada-event", league:"ufc", round:"last-call", category:"International History", prompt:"What was the UFC's first event in Canada?", choices:["UFC 83","UFC 97","UFC 113","UFC 129"], answer:"UFC 83", explanation:"UFC 83 took place in Montreal in April 2008.", sourceId:"ufc83-history" }),
  q({ id:"ufc-final-first-australia-event", league:"ufc", round:"last-call", category:"International History", prompt:"What was the UFC's first event in Australia?", choices:["UFC 110","UFC 127","UFC 193","UFC 243"], answer:"UFC 110", explanation:"UFC 110 took place in Sydney in 2010.", sourceId:"ufc110-history" }),
  q({ id:"ufc-final-hof-era-cutoff", league:"ufc", round:"last-call", category:"Hall of Fame", prompt:"Which event marks the Hall of Fame cutoff between UFC's Pioneer and Modern eras?", choices:["UFC 28","UFC 30","UFC 1","UFC 50"], answer:"UFC 28", explanation:"The Hall of Fame uses Nov. 17, 2000 — UFC 28 — as its era dividing line.", sourceId:"ufc-hof", sourceUrl:HOF }),
  q({ id:"ufc-final-first-hof-fight", league:"ufc", round:"last-call", category:"Hall of Fame", prompt:"Which bout was the first inducted into UFC's Hall of Fame Fight Wing?", choices:["Forrest Griffin vs. Stephan Bonnar I","Matt Hughes vs. Frank Trigg II","Jones vs. Gustafsson I","Lawler vs. MacDonald II"], answer:"Forrest Griffin vs. Stephan Bonnar I", explanation:"The TUF 1 Finale classic became the first Fight Wing induction.", sourceId:"ufc-hof", sourceUrl:HOF }),
];
