import { barTriviaQuestion, type BarTriviaQuestion } from "../games/barTriviaEngine";

const NCAA_CHAMPS = "https://www.ncaa.com/news/football/article/college-football-national-championship-history";
const HEISMAN = "https://www.heisman.com/about-the-heisman/milestones/";

function q(seed: Parameters<typeof barTriviaQuestion>[0]) {
  return barTriviaQuestion({ ...seed, verifiedAt: "2026-09-28" });
}

export const BAR_TRIVIA_CFB_EVERGREEN_WAVE_4: readonly BarTriviaQuestion[] = [
  // Round 1 — mascots, music and campus personality
  q({ id:"cfb-r1-script-ohio", league:"cfb", round:"round1", category:"Band Traditions", prompt:"The marching-band formation known as 'Script Ohio' belongs to which school?", choices:["Ohio State","Ohio","Michigan","Cincinnati"], answer:"Ohio State", explanation:"The Ohio State University Marching Band performs Script Ohio, capped by the famous dotting of the i.", sourceId:"ohio-state-script-ohio" }),
  q({ id:"cfb-r1-hang-on-sloopy", league:"cfb", round:"round1", category:"Stadium Music", prompt:"'Hang On Sloopy' is a game-day anthem at which school?", choices:["Ohio State","Michigan","Wisconsin","Iowa"], answer:"Ohio State", explanation:"Ohio State's band and crowd traditionally play and sing 'Hang On Sloopy.'", sourceId:"ohio-state-traditions" }),
  q({ id:"cfb-r1-rocky-top", league:"cfb", round:"round1", category:"Stadium Music", prompt:"Which program's fans sing 'Rocky Top' throughout football games?", choices:["Tennessee","Kentucky","West Virginia","Virginia Tech"], answer:"Tennessee", explanation:"The Osborne Brothers song became an unofficial anthem of Tennessee athletics.", sourceId:"tennessee-rocky-top" }),
  q({ id:"cfb-r1-boomer-sooner", league:"cfb", round:"round1", category:"Fight Songs", prompt:"'Boomer Sooner' is the fight song of which program?", choices:["Oklahoma","Oklahoma State","Nebraska","Texas"], answer:"Oklahoma", explanation:"Oklahoma's band plays 'Boomer Sooner' repeatedly on game days.", sourceId:"oklahoma-boomer-sooner" }),
  q({ id:"cfb-r1-masked-rider", league:"cfb", round:"round1", category:"Mascots", prompt:"The Masked Rider leads which team onto the field on horseback?", choices:["Texas Tech","Texas","Oklahoma State","SMU"], answer:"Texas Tech", explanation:"Texas Tech's Masked Rider is one of college football's distinctive mounted mascots.", sourceId:"texas-tech-masked-rider" }),
  q({ id:"cfb-r1-peruna", league:"cfb", round:"round1", category:"Mascots", prompt:"Peruna, a live Shetland pony, is the mascot of which school?", choices:["SMU","TCU","Baylor","Texas Tech"], answer:"SMU", explanation:"SMU's live pony mascot is named Peruna.", sourceId:"smu-peruna" }),
  q({ id:"cfb-r1-bill-goat", league:"cfb", round:"round1", category:"Mascots", prompt:"Bill the Goat is the live mascot of which service academy?", choices:["Navy","Army","Air Force","Coast Guard"], answer:"Navy", explanation:"The U.S. Naval Academy's mascot is Bill the Goat.", sourceId:"navy-bill-goat" }),
  q({ id:"cfb-r1-army-mules", league:"cfb", round:"round1", category:"Mascots", prompt:"Which service academy uses mules as its live mascots?", choices:["Army","Navy","Air Force","Coast Guard"], answer:"Army", explanation:"Army West Point's live mascot tradition features mules.", sourceId:"army-mules" }),
  q({ id:"cfb-r1-air-force-falcon", league:"cfb", round:"round1", category:"Mascots", prompt:"Which service academy's live mascot tradition features trained falcons?", choices:["Air Force","Army","Navy","Coast Guard"], answer:"Air Force", explanation:"The Air Force Academy uses live falcons as mascots.", sourceId:"air-force-falcon" }),
  q({ id:"cfb-r1-pistol-pete", league:"cfb", round:"round1", category:"Mascots", prompt:"Pistol Pete is the cowboy mascot of which Big 12 program?", choices:["Oklahoma State","Texas Tech","Kansas State","Baylor"], answer:"Oklahoma State", explanation:"Oklahoma State's mascot Pistol Pete is based on famed lawman Frank Eaton.", sourceId:"oklahoma-state-pistol-pete" }),
  q({ id:"cfb-r1-superfrog", league:"cfb", round:"round1", category:"Mascots", prompt:"SuperFrog is the mascot of which program?", choices:["TCU","Baylor","Kansas State","SMU"], answer:"TCU", explanation:"TCU's costumed mascot SuperFrog represents the Horned Frogs.", sourceId:"tcu-superfrog" }),
  q({ id:"cfb-r1-mountaineer-musket", league:"cfb", round:"round1", category:"Mascots", prompt:"Which school's Mountaineer mascot carries a traditional musket?", choices:["West Virginia","Appalachian State","Tennessee","Kentucky"], answer:"West Virginia", explanation:"West Virginia's Mountaineer mascot appears in buckskins and carries a musket.", sourceId:"west-virginia-mountaineer" }),
  q({ id:"cfb-r1-boilermaker-special", league:"cfb", round:"round1", category:"Traditions", prompt:"The Boilermaker Special, which resembles a train, belongs to which school?", choices:["Purdue","Illinois","Indiana","Iowa"], answer:"Purdue", explanation:"Purdue's official mascot vehicle is the locomotive-styled Boilermaker Special.", sourceId:"purdue-boilermaker-special" }),
  q({ id:"cfb-r1-pink-locker-room", league:"cfb", round:"round1", category:"Stadium Oddities", prompt:"Which stadium is famous for a visitors' locker room painted pink?", choices:["Kinnick Stadium","Camp Randall Stadium","Neyland Stadium","Kyle Field"], answer:"Kinnick Stadium", explanation:"Former Iowa coach Hayden Fry had the visitors' locker room at Kinnick Stadium painted pink.", sourceId:"iowa-pink-locker-room" }),
  q({ id:"cfb-r1-fifth-quarter", league:"cfb", round:"round1", category:"Band Traditions", prompt:"The postgame 'Fifth Quarter' marching-band performance is a tradition at which school?", choices:["Wisconsin","Ohio State","Michigan","Iowa"], answer:"Wisconsin", explanation:"Wisconsin's band keeps the show going after games with its Fifth Quarter performance.", sourceId:"wisconsin-fifth-quarter" }),

  // Round 2 — rivalry hardware and famous championship moments
  q({ id:"cfb-r2-old-brass-spittoon", league:"cfb", round:"round2", category:"Rivalry Trophies", prompt:"The Old Brass Spittoon is played for by Michigan State and which school?", choices:["Indiana","Purdue","Illinois","Michigan"], answer:"Indiana", explanation:"Michigan State and Indiana contest the Old Brass Spittoon.", sourceId:"old-brass-spittoon" }),
  q({ id:"cfb-r2-illibuck", league:"cfb", round:"round2", category:"Rivalry Trophies", prompt:"The Illibuck trophy belongs to the rivalry between Illinois and which school?", choices:["Ohio State","Indiana","Purdue","Northwestern"], answer:"Ohio State", explanation:"Illinois and Ohio State play for the Illibuck, a wooden turtle trophy.", sourceId:"illibuck" }),
  q({ id:"cfb-r2-commonwealth-cup", league:"cfb", round:"round2", category:"Rivalry Trophies", prompt:"The Commonwealth Cup is awarded in the rivalry between Virginia and which school?", choices:["Virginia Tech","West Virginia","North Carolina","Maryland"], answer:"Virginia Tech", explanation:"Virginia and Virginia Tech play for the Commonwealth Cup.", sourceId:"commonwealth-cup" }),
  q({ id:"cfb-r2-heartland-trophy", league:"cfb", round:"round2", category:"Rivalry Trophies", prompt:"The Heartland Trophy is contested by Iowa and which school?", choices:["Wisconsin","Minnesota","Nebraska","Illinois"], answer:"Wisconsin", explanation:"Iowa and Wisconsin play for the Heartland Trophy.", sourceId:"heartland-trophy" }),
  q({ id:"cfb-r2-golden-boot", league:"cfb", round:"round2", category:"Rivalry Trophies", prompt:"The Golden Boot trophy is awarded in the rivalry between Arkansas and which school?", choices:["LSU","Texas","Ole Miss","Missouri"], answer:"LSU", explanation:"Arkansas and LSU play for a trophy shaped like the outline of the two states.", sourceId:"arkansas-lsu-golden-boot" }),
  q({ id:"cfb-r2-magnolia-bowl", league:"cfb", round:"round2", category:"Rivalries", prompt:"The Magnolia Bowl is the rivalry between LSU and which school?", choices:["Ole Miss","Mississippi State","Alabama","Tulane"], answer:"Ole Miss", explanation:"LSU and Ole Miss meet in the rivalry known as the Magnolia Bowl.", sourceId:"magnolia-bowl" }),
  q({ id:"cfb-r2-2013-title-catch", league:"cfb", round:"round2", category:"Championship Moments", prompt:"Who caught Florida State's late game-winning touchdown in the 2013 national championship game?", choices:["Kelvin Benjamin","Rashad Greene","Nick O'Leary","Devonta Freeman"], answer:"Kelvin Benjamin", explanation:"Jameis Winston found Kelvin Benjamin for the winning touchdown against Auburn.", sourceId:"florida-state-2013" }),
  q({ id:"cfb-r2-2016-title-catch", league:"cfb", round:"round2", category:"Championship Moments", prompt:"Who caught Clemson's last-second touchdown to beat Alabama for the 2016 national title?", choices:["Hunter Renfrow","Mike Williams","Artavis Scott","Deon Cain"], answer:"Hunter Renfrow", explanation:"Deshaun Watson hit Hunter Renfrow with one second left for the championship-winning score.", sourceId:"clemson-2016" }),
  q({ id:"cfb-r2-2010-dyer-run", league:"cfb", round:"round2", category:"Championship Moments", prompt:"Which Auburn running back had the famous 'wasn't down' run late in the 2010 national championship game?", choices:["Michael Dyer","Onterio McCalebb","Cam Newton","Tre Mason"], answer:"Michael Dyer", explanation:"Dyer rolled over an Oregon defender without touching the ground and kept running to set up the winning field goal.", sourceId:"auburn-oregon-2010" }),
  q({ id:"cfb-r2-2003-fiesta-champion", league:"cfb", round:"round2", category:"Championship Games", prompt:"Which team beat Miami in double overtime to win the 2002 national championship?", choices:["Ohio State","Florida State","Oklahoma","USC"], answer:"Ohio State", explanation:"Ohio State beat Miami 31–24 in the Fiesta Bowl to finish 14–0.", sourceId:"ohio-state-2002" }),
  q({ id:"cfb-r2-1984-orange-champ", league:"cfb", round:"round2", category:"Championship Games", prompt:"Which team beat Nebraska 31–30 in the 1984 Orange Bowl to claim the 1983 national title?", choices:["Miami","Florida State","Oklahoma","Clemson"], answer:"Miami", explanation:"Miami stopped Nebraska's late two-point try to win the national championship.", sourceId:"miami-1983" }),
  q({ id:"cfb-r2-1988-nd-miami", league:"cfb", round:"round2", category:"Rivalry Classics", prompt:"Notre Dame's famous 1988 'Catholics vs. Convicts' win over Miami ended with what score?", choices:["31–30","24–21","27–24","35–34"], answer:"31–30", explanation:"Miami's late two-point conversion attempt failed, preserving Notre Dame's 31–30 win.", sourceId:"notre-dame-miami-1988" }),
  q({ id:"cfb-r2-1966-game-century", league:"cfb", round:"round2", category:"Historic Games", prompt:"Notre Dame and Michigan State played to what score in their famous 1966 'Game of the Century'?", choices:["10–10","7–7","14–14","17–17"], answer:"10–10", explanation:"The top-ranked teams played to a 10–10 tie in East Lansing.", sourceId:"notre-dame-msu-1966" }),
  q({ id:"cfb-r2-1996-florida-title", league:"cfb", round:"round2", category:"Championship Games", prompt:"Florida won its first national championship by beating which rival in the Sugar Bowl?", choices:["Florida State","Tennessee","Georgia","Alabama"], answer:"Florida State", explanation:"Florida beat Florida State 52–20 in a rematch after the 1996 regular season.", sourceId:"florida-1996" }),
  q({ id:"cfb-r2-1993-fsu-title", league:"cfb", round:"round2", category:"Championship Games", prompt:"Florida State won its first national championship by beating which team in the Orange Bowl?", choices:["Nebraska","Miami","Notre Dame","Florida"], answer:"Nebraska", explanation:"Florida State beat Nebraska 18–16 after the 1993 season.", sourceId:"florida-state-1993" }),

  // Round 3 — coaching lore and deeper historical anchors
  q({ id:"cfb-r3-head-ball-coach", league:"cfb", round:"round3", category:"Coaching Nicknames", prompt:"Which coach was famously known as 'The Head Ball Coach'?", choices:["Steve Spurrier","Lou Holtz","Bobby Bowden","Barry Switzer"], answer:"Steve Spurrier", explanation:"Steve Spurrier embraced the Head Ball Coach nickname throughout his career.", sourceId:"spurrier-history" }),
  q({ id:"cfb-r3-beamer-ball", league:"cfb", round:"round3", category:"Coaching Lore", prompt:"The phrase 'Beamer Ball' referred to the special-teams emphasis of which coach?", choices:["Frank Beamer","Bobby Bowden","Bill Snyder","Tom Osborne"], answer:"Frank Beamer", explanation:"Virginia Tech became famous for blocked kicks, returns and special-teams scores under Frank Beamer.", sourceId:"virginia-tech-beamer" }),
  q({ id:"cfb-r3-houndstooth-bryant", league:"cfb", round:"round3", category:"Coaching Style", prompt:"The houndstooth hat became an iconic look associated with which coach?", choices:["Bear Bryant","Woody Hayes","Darrell Royal","Bud Wilkinson"], answer:"Bear Bryant", explanation:"Alabama coach Bear Bryant was famously photographed in his houndstooth-patterned hat.", sourceId:"bear-bryant-history" }),
  q({ id:"cfb-r3-darrell-royal-stadium", league:"cfb", round:"round3", category:"Stadium Names", prompt:"Texas' football stadium is named in part for which legendary Longhorns coach?", choices:["Darrell Royal","Mack Brown","Dana X. Bible","Fred Akers"], answer:"Darrell Royal", explanation:"Darrell K Royal-Texas Memorial Stadium honors the longtime Texas coach.", sourceId:"texas-stadium-history" }),
  q({ id:"cfb-r3-bowden-program", league:"cfb", round:"round3", category:"Coaches", prompt:"Bobby Bowden built his national-championship legacy at which school?", choices:["Florida State","West Virginia","Clemson","Alabama"], answer:"Florida State", explanation:"Bowden turned Florida State into a national powerhouse and won titles in 1993 and 1999.", sourceId:"florida-state-bowden" }),
  q({ id:"cfb-r3-osborne-program", league:"cfb", round:"round3", category:"Coaches", prompt:"Tom Osborne won three national championships in four seasons coaching which program?", choices:["Nebraska","Oklahoma","Colorado","Kansas State"], answer:"Nebraska", explanation:"Osborne's Nebraska teams won national titles in 1994, 1995 and 1997.", sourceId:"ncaa-championship-history", sourceUrl:NCAA_CHAMPS }),
  q({ id:"cfb-r3-switzer-program", league:"cfb", round:"round3", category:"Coaches", prompt:"Barry Switzer won three national championships as head coach of which program?", choices:["Oklahoma","Nebraska","Texas","Arkansas"], answer:"Oklahoma", explanation:"Switzer's Oklahoma teams won national championships in 1974, 1975 and 1985.", sourceId:"oklahoma-switzer" }),
  q({ id:"cfb-r3-1980-georgia-bowl", league:"cfb", round:"round3", category:"Championship History", prompt:"Georgia completed its 1980 national-title season by beating which team in the Sugar Bowl?", choices:["Notre Dame","Alabama","Pittsburgh","Penn State"], answer:"Notre Dame", explanation:"Georgia beat Notre Dame 17–10 to finish 12–0.", sourceId:"georgia-1980" }),
  q({ id:"cfb-r3-1992-alabama-opponent", league:"cfb", round:"round3", category:"Championship History", prompt:"Alabama's 1992 national championship team beat which powerhouse in the Sugar Bowl?", choices:["Miami","Florida State","Notre Dame","Nebraska"], answer:"Miami", explanation:"Alabama upset unbeaten Miami 34–13 in the Sugar Bowl.", sourceId:"alabama-1992" }),
  q({ id:"cfb-r3-1988-notre-dame", league:"cfb", round:"round3", category:"Championship History", prompt:"Who coached Notre Dame to the 1988 national championship?", choices:["Lou Holtz","Dan Devine","Ara Parseghian","Bob Davie"], answer:"Lou Holtz", explanation:"Lou Holtz led Notre Dame to a 12–0 season and the 1988 national title.", sourceId:"notre-dame-1988" }),
  q({ id:"cfb-r3-1983-miami-coach", league:"cfb", round:"round3", category:"Coaches", prompt:"Which coach led Miami to its first national championship after the 1983 season?", choices:["Howard Schnellenberger","Jimmy Johnson","Dennis Erickson","Larry Coker"], answer:"Howard Schnellenberger", explanation:"Schnellenberger's Hurricanes upset Nebraska in the Orange Bowl.", sourceId:"miami-1983" }),
  q({ id:"cfb-r3-1969-texas-coach", league:"cfb", round:"round3", category:"Coaches", prompt:"Which coach led Texas to the 1969 national championship?", choices:["Darrell Royal","Mack Brown","Fred Akers","Dana X. Bible"], answer:"Darrell Royal", explanation:"Darrell Royal's Longhorns went undefeated and won the 1969 national title.", sourceId:"texas-1969" }),
  q({ id:"cfb-r3-2007-lsu-coach", league:"cfb", round:"round3", category:"Coaches", prompt:"Who coached LSU to the 2007 BCS national championship?", choices:["Les Miles","Nick Saban","Ed Orgeron","Gerry DiNardo"], answer:"Les Miles", explanation:"Les Miles' LSU team beat Ohio State for the 2007 season championship.", sourceId:"lsu-2007" }),
  q({ id:"cfb-r3-2013-fsu-qb", league:"cfb", round:"round3", category:"Championship Stars", prompt:"Which Heisman winner quarterbacked Florida State to the final BCS championship?", choices:["Jameis Winston","Chris Weinke","EJ Manuel","Christian Ponder"], answer:"Jameis Winston", explanation:"Winston won the 2013 Heisman and led Florida State past Auburn for the national title.", sourceId:"florida-state-2013" }),
  q({ id:"cfb-r3-1996-spurrier-title", league:"cfb", round:"round3", category:"Coaching History", prompt:"Steve Spurrier won Florida's first national championship by defeating which coach's team?", choices:["Bobby Bowden's Florida State","Phillip Fulmer's Tennessee","Gene Stallings' Alabama","Ray Goff's Georgia"], answer:"Bobby Bowden's Florida State", explanation:"Florida defeated Bowden's Seminoles 52–20 in the Sugar Bowl rematch.", sourceId:"florida-1996" }),

  // Last Call
  q({ id:"cfb-final-1984-orange-score", league:"cfb", round:"last-call", category:"Classic Bowls", prompt:"What was the final score when Miami upset Nebraska for the 1983 national title?", choices:["31–30","28–27","24–21","35–34"], answer:"31–30", explanation:"Nebraska's late two-point conversion failed, leaving Miami with a 31–30 Orange Bowl win.", sourceId:"miami-1983" }),
  q({ id:"cfb-final-testaverde-fiesta", league:"cfb", round:"last-call", category:"Championship Lore", prompt:"Which Heisman-winning quarterback did Penn State intercept five times in its 14–10 Fiesta Bowl title win after the 1986 season?", choices:["Vinny Testaverde","Doug Flutie","Steve Walsh","Troy Aikman"], answer:"Vinny Testaverde", explanation:"Penn State intercepted Miami's Vinny Testaverde five times, including a late goal-line pick, to win the 1987 Fiesta Bowl and the national title.", sourceId:"penn-state-1986-title", sourceUrl:"https://gopsusports.com/news/2011/06/16/nittany-lions-unbeaten-1986-national-championship-squad-to-be-honored-at-iowa-clash" }),
  q({ id:"cfb-final-2013-title-receiver", league:"cfb", round:"last-call", category:"Championship Moments", prompt:"Which receiver caught Jameis Winston's game-winning pass in the final BCS title game?", choices:["Kelvin Benjamin","Rashad Greene","Kenny Shaw","Nick O'Leary"], answer:"Kelvin Benjamin", explanation:"Benjamin's late touchdown gave Florida State the 34–31 win over Auburn.", sourceId:"florida-state-2013" }),
  q({ id:"cfb-final-heisman-1961", league:"cfb", round:"last-call", category:"Heisman History", prompt:"Who became the first African-American Heisman winner in 1961?", choices:["Ernie Davis","Jim Brown","Mike Garrett","Floyd Little"], answer:"Ernie Davis", explanation:"Syracuse star Ernie Davis broke the Heisman color barrier in 1961.", sourceId:"heisman-milestones", sourceUrl:HEISMAN }),
  q({ id:"cfb-final-first-west-coast-heisman", league:"cfb", round:"last-call", category:"Heisman History", prompt:"Which Oregon State quarterback became the first Heisman winner from the West Coast?", choices:["Terry Baker","Gary Beban","Jim Plunkett","Marcus Allen"], answer:"Terry Baker", explanation:"Baker won the 1962 Heisman and also reached the NCAA basketball Final Four.", sourceId:"heisman-milestones", sourceUrl:HEISMAN }),
];
