import { barTriviaQuestion, type BarTriviaQuestion } from "../games/barTriviaEngine";

const HOF = "https://www.ufc.com/news/ufc-hall-fame-faq";
const UFC30 = "https://www.ufc.com/30";
const TUF1 = "https://www.ufc.com/news/celebrating-10-years-ultimate-fighter";

function q(seed: Parameters<typeof barTriviaQuestion>[0]) {
  return barTriviaQuestion({ ...seed, verifiedAt: "2026-09-28" });
}

export const BAR_TRIVIA_UFC_EVERGREEN_WAVE_5: readonly BarTriviaQuestion[] = [
  // Round 1 — TUF faces, personalities and recognizable UFC culture
  q({ id:"ufc-r1-buckley-kasanganay", league:"ufc", round:"round1", category:"Iconic Finishes", prompt:"Joaquin Buckley's viral jump-spinning back-kick knockout came against which opponent?", choices:["Impa Kasanganay","Kevin Holland","Alessio Di Chirico","Abdul Razak Alhassan"], answer:"Impa Kasanganay", explanation:"Buckley turned a caught kick into a jump-spinning back kick that knocked out Impa Kasanganay on Fight Island in 2020.", sourceId:"ufc-buckley-kasanganay", sourceUrl:"https://www.ufc.com/news/ufc-fight-island-5-night-moraes-vs-sandhagen-results?language_content_entity=en" }),
  q({ id:"ufc-r1-kongo-barry-comeback", league:"ufc", round:"round1", category:"Comebacks", prompt:"Who survived being dropped twice by Pat Barry before scoring a stunning comeback knockout in 2011?", choices:["Cheick Kongo","Roy Nelson","Stefan Struve","Mirko Cro Cop"], answer:"Cheick Kongo", explanation:"Cheick Kongo was badly hurt twice, recovered, and knocked Barry out with a pair of right hands in one of the UFC's wildest comebacks.", sourceId:"ufc-kongo-barry", sourceUrl:"https://www.ufc.com/news/after-epic-comeback-kongo-looks-encore" }),
  q({ id:"ufc-r1-sexyama", league:"ufc", round:"round1", category:"Nicknames", prompt:"Which UFC fan favorite was widely dubbed \"Sexyama\"?", choices:["Yoshihiro Akiyama","Yushin Okami","Dong Hyun Kim","Takanori Gomi"], answer:"Yoshihiro Akiyama", explanation:"Yoshihiro Akiyama became a fan favorite whose \"Sexyama\" persona followed him throughout his UFC run.", sourceId:"ufc-akiyama-sexyama", sourceUrl:"https://www.ufc.com/news/yoshihiro-akiyama-winning-only-motivation" }),
  q({ id:"ufc-r1-serra-tuf4", league:"ufc", round:"round1", category:"The Ultimate Fighter", prompt:"Which fighter won The Ultimate Fighter 4 and then shocked Georges St-Pierre for the title?", choices:["Matt Serra","Chris Lytle","Patrick Cote","Travis Lutter"], answer:"Matt Serra", explanation:"Matt Serra won the welterweight bracket on TUF 4, earning the title shot that led to his famous upset.", sourceId:"tuf4-history" }),
  q({ id:"ufc-r1-roy-nelson-tuf10", league:"ufc", round:"round1", category:"The Ultimate Fighter", prompt:"Which heavyweight known as 'Big Country' won The Ultimate Fighter 10?", choices:["Roy Nelson","Brendan Schaub","Matt Mitrione","Kimbo Slice"], answer:"Roy Nelson", explanation:"Roy Nelson won the TUF 10 heavyweight tournament.", sourceId:"tuf10-history" }),
  q({ id:"ufc-r1-tony-tuf13", league:"ufc", round:"round1", category:"The Ultimate Fighter", prompt:"Which future interim lightweight champion won The Ultimate Fighter 13?", choices:["Tony Ferguson","Michael Johnson","Ramsey Nijem","Ryan McGillivray"], answer:"Tony Ferguson", explanation:"Tony Ferguson won the welterweight tournament on TUF 13.", sourceId:"tuf13-history" }),
  q({ id:"ufc-r1-gastelum-tuf17", league:"ufc", round:"round1", category:"The Ultimate Fighter", prompt:"Which fighter upset Uriah Hall to win The Ultimate Fighter 17?", choices:["Kelvin Gastelum","Robert Whittaker","Luke Barnatt","Josh Samman"], answer:"Kelvin Gastelum", explanation:"Kelvin Gastelum edged Uriah Hall by split decision in the TUF 17 finale.", sourceId:"tuf17-history" }),
  q({ id:"ufc-r1-pena-tuf18", league:"ufc", round:"round1", category:"The Ultimate Fighter", prompt:"Who became the first female winner of The Ultimate Fighter?", choices:["Julianna Pena","Raquel Pennington","Rose Namajunas","Jessica Rakoczy"], answer:"Julianna Pena", explanation:"Julianna Pena won the women's bantamweight tournament on TUF 18.", sourceId:"tuf18-history" }),
  q({ id:"ufc-r1-usman-tuf21", league:"ufc", round:"round1", category:"The Ultimate Fighter", prompt:"Which future welterweight champion won The Ultimate Fighter 21?", choices:["Kamaru Usman","Colby Covington","Leon Edwards","Vicente Luque"], answer:"Kamaru Usman", explanation:"Kamaru Usman won TUF 21 before eventually becoming UFC welterweight champion.", sourceId:"tuf21-history" }),
  q({ id:"ufc-r1-big-john", league:"ufc", round:"round1", category:"Officials", prompt:"Which referee became an early UFC icon under the nickname 'Big John'?", choices:["John McCarthy","Herb Dean","Mario Yamasaki","Dan Miragliotta"], answer:"John McCarthy", explanation:"John 'Big John' McCarthy refereed many of the promotion's earliest and most famous bouts.", sourceId:"ufc-officials-history" }),
  q({ id:"ufc-r1-herb-dean", league:"ufc", round:"round1", category:"Officials", prompt:"Which longtime referee has become one of the UFC's most recognizable officials?", choices:["Herb Dean","Bruce Buffer","Joe Rogan","Marc Goddard"], answer:"Herb Dean", explanation:"Herb Dean has officiated championship fights and major UFC events for decades.", sourceId:"ufc-officials-history" }),
  q({ id:"ufc-r1-voice-octagon", league:"ufc", round:"round1", category:"Broadcast Personalities", prompt:"Who is known as the 'Voice of the Octagon' and announces fighters before UFC bouts?", choices:["Bruce Buffer","Jon Anik","Joe Rogan","Mike Goldberg"], answer:"Bruce Buffer", explanation:"Bruce Buffer is UFC's longtime Octagon announcer.", sourceId:"ufc-buffer-history" }),
  q({ id:"ufc-r1-rogan-role", league:"ufc", round:"round1", category:"Broadcast Personalities", prompt:"Joe Rogan is best known in UFC broadcasts for which role?", choices:["Color commentator","Ring announcer","Play-by-play announcer only","Referee"], answer:"Color commentator", explanation:"Rogan has long served as a UFC color commentator and interviewer.", sourceId:"ufc-broadcast-history" }),
  q({ id:"ufc-r1-anik-role", league:"ufc", round:"round1", category:"Broadcast Personalities", prompt:"Jon Anik is primarily known in UFC broadcasts as a...", choices:["Play-by-play announcer","Referee","Ring announcer","Matchmaker"], answer:"Play-by-play announcer", explanation:"Jon Anik has served as UFC's lead play-by-play voice on many major cards.", sourceId:"ufc-broadcast-history" }),
  q({ id:"ufc-r1-ufc205-venue", league:"ufc", round:"round1", category:"Venues", prompt:"UFC 205 was the promotion's first event at which famous arena?", choices:["Madison Square Garden","Barclays Center","TD Garden","United Center"], answer:"Madison Square Garden", explanation:"UFC 205 marked the promotion's long-awaited debut at Madison Square Garden.", sourceId:"ufc205-history" }),

  // Round 2 — venues, international expansion and Hall of Fame fights
  q({ id:"ufc-r2-ufc129-city", league:"ufc", round:"round2", category:"International History", prompt:"UFC 129, the promotion's first stadium-scale Canadian event, took place in which city?", choices:["Toronto","Montreal","Vancouver","Calgary"], answer:"Toronto", explanation:"UFC 129 filled Rogers Centre in Toronto.", sourceId:"ufc129-history" }),
  q({ id:"ufc-r2-ufc193-city-melbourne", league:"ufc", round:"round2", category:"International History", prompt:"Which Australian city hosted UFC 193, where Holly Holm upset Ronda Rousey?", choices:["Melbourne","Sydney","Brisbane","Perth"], answer:"Melbourne", explanation:"UFC 193 took place at Etihad Stadium in Melbourne.", sourceId:"ufc193-history" }),
  q({ id:"ufc-r2-ufc243-city", league:"ufc", round:"round2", category:"International History", prompt:"UFC 243, headlined by Whittaker vs. Adesanya, was held in which city?", choices:["Melbourne","Sydney","Auckland","Perth"], answer:"Melbourne", explanation:"UFC 243 took place at Marvel Stadium in Melbourne.", sourceId:"ufc243-history" }),
  q({ id:"ufc-r2-california-kid", league:"ufc", round:"round2", category:"Nicknames", prompt:"Which longtime bantamweight contender is known as \"The California Kid\"?", choices:["Urijah Faber","Chad Mendes","TJ Dillashaw","Dominick Cruz"], answer:"Urijah Faber", explanation:"Urijah Faber has long fought under the nickname \"The California Kid.\"", sourceId:"ufc-faber-profile", sourceUrl:"https://www.ufc.com/athlete/urijah-faber" }),
  q({ id:"ufc-r2-russia-debut-city", league:"ufc", round:"round2", category:"Global UFC", prompt:"Which city hosted the UFC's first event in Russia in 2018?", choices:["Moscow","Saint Petersburg","Sochi","Kazan"], answer:"Moscow", explanation:"The UFC made its Russian debut in Moscow with a Fight Night card headlined by Mark Hunt and Aleksei Oleinik.", sourceId:"ufc-russia-debut", sourceUrl:"https://www.ufc.com/news/hunt-vs-oleinik-headline-ufcs-debut-event-russia" }),
  q({ id:"ufc-r2-first-mexico", league:"ufc", round:"round2", category:"International History", prompt:"Which numbered event marked UFC's first event in Mexico?", choices:["UFC 180","UFC 188","UFC 192","UFC 197"], answer:"UFC 180", explanation:"UFC 180 took place in Mexico City in 2014.", sourceId:"ufc180-history" }),
  q({ id:"ufc-r2-natural-born-killer", league:"ufc", round:"round2", category:"Nicknames", prompt:"Which former interim welterweight champion is known as \"The Natural Born Killer\"?", choices:["Carlos Condit","Nick Diaz","Johny Hendricks","Rory MacDonald"], answer:"Carlos Condit", explanation:"Carlos Condit fought under the nickname \"The Natural Born Killer\" during his UFC welterweight run.", sourceId:"ufc-condit-profile", sourceUrl:"https://www.ufc.com/athlete/carlos-condit" }),
  q({ id:"ufc-r2-ufc83-main", league:"ufc", round:"round2", category:"Milestone Events", prompt:"Who did Georges St-Pierre defeat in the main event of UFC 83 in Montreal?", choices:["Matt Serra","Matt Hughes","BJ Penn","Josh Koscheck"], answer:"Matt Serra", explanation:"St-Pierre avenged his upset loss to Serra and unified the welterweight title.", sourceId:"ufc83-history" }),
  q({ id:"ufc-r2-price-brown-hammerfists", league:"ufc", round:"round2", category:"Weird Finishes", prompt:"Niko Price scored one of the UFC's strangest knockouts by hammerfisting which opponent from the bottom position?", choices:["Randy Brown","Alan Jouban","Tim Means","James Vick"], answer:"Randy Brown", explanation:"Price trapped Randy Brown's head with his foot and knocked him out with hammerfists while fighting from his back.", sourceId:"ufc-price-brown", sourceUrl:"https://www.ufc.com/news/niko-price-hitting-another-level-ufc-240" }),
  q({ id:"ufc-r2-triple-c", league:"ufc", round:"round2", category:"Nicknames", prompt:"Which Olympic gold medalist and two-division UFC champion adopted the nickname \"Triple C\"?", choices:["Henry Cejudo","Daniel Cormier","Randy Couture","Georges St-Pierre"], answer:"Henry Cejudo", explanation:"Henry Cejudo used \"Triple C\" after adding UFC flyweight and bantamweight titles to his Olympic wrestling gold medal.", sourceId:"ufc-cejudo-profile", sourceUrl:"https://www.ufc.com/athlete/henry-cejudo?language_content_entity=en-aus&page=1" }),
  q({ id:"ufc-r2-stun-gun", league:"ufc", round:"round2", category:"Nicknames", prompt:"Which South Korean welterweight was known as \"The Stun Gun\"?", choices:["Dong Hyun Kim","Chan Sung Jung","Doo Ho Choi","Yushin Okami"], answer:"Dong Hyun Kim", explanation:"Dong Hyun Kim fought under the nickname \"The Stun Gun\" throughout his UFC career.", sourceId:"ufc-kim-profile", sourceUrl:"https://www.ufc.com/athlete/dong-hyun-kim" }),
  q({ id:"ufc-r2-sanchez-guida-event", league:"ufc", round:"round2", category:"Hall of Fame Fights", prompt:"Diego Sanchez vs. Clay Guida took place at the finale of which season of The Ultimate Fighter?", choices:["Season 9","Season 5","Season 7","Season 11"], answer:"Season 9", explanation:"Their 2009 classic headlined The Ultimate Fighter 9 Finale.", sourceId:"ufc-hof", sourceUrl:HOF }),
  q({ id:"ufc-r2-jones-gus-event", league:"ufc", round:"round2", category:"Hall of Fame Fights", prompt:"Jon Jones vs. Alexander Gustafsson I took place at which event?", choices:["UFC 165","UFC 172","UFC 182","UFC 214"], answer:"UFC 165", explanation:"Their 2013 light heavyweight title fight became a Hall of Fame classic.", sourceId:"ufc-hof", sourceUrl:HOF }),
  q({ id:"ufc-r2-mighty-mouse", league:"ufc", round:"round2", category:"Nicknames", prompt:"Which longtime flyweight champion is known as \"Mighty Mouse\"?", choices:["Demetrious Johnson","Joseph Benavidez","John Dodson","Henry Cejudo"], answer:"Demetrious Johnson", explanation:"Demetrious Johnson carried the \"Mighty Mouse\" nickname throughout his record-setting UFC flyweight title reign.", sourceId:"ufc-johnson-profile", sourceUrl:"https://www.ufc.com/athlete/temetoriasu-shiyonson" }),
  q({ id:"ufc-r2-first-msg-year", league:"ufc", round:"round2", category:"Milestone Events", prompt:"UFC first held an event at Madison Square Garden in which year?", choices:["2016","2014","2018","2012"], answer:"2016", explanation:"UFC 205 brought the Octagon to Madison Square Garden in November 2016.", sourceId:"ufc205-history" }),

  // Round 3 — TUF history and Hall of Fame structure
  q({ id:"ufc-r3-tuf3-other-winner", league:"ufc", round:"round3", category:"The Ultimate Fighter", prompt:"Alongside Michael Bisping, who won the other tournament on The Ultimate Fighter 3?", choices:["Kendall Grove","Ed Herman","Matt Hamill","Ross Pointon"], answer:"Kendall Grove", explanation:"Kendall Grove won the middleweight tournament on TUF 3.", sourceId:"tuf3-history" }),
  q({ id:"ufc-r3-tuf4-other-winner", league:"ufc", round:"round3", category:"The Ultimate Fighter", prompt:"Alongside Matt Serra, who won the other tournament on The Ultimate Fighter 4?", choices:["Travis Lutter","Chris Lytle","Patrick Cote","Pete Sell"], answer:"Travis Lutter", explanation:"Travis Lutter won the middleweight bracket on the comeback season.", sourceId:"tuf4-history" }),
  q({ id:"ufc-r3-tuf18-male-winner", league:"ufc", round:"round3", category:"The Ultimate Fighter", prompt:"Who won the men's bantamweight tournament on The Ultimate Fighter 18?", choices:["Chris Holdsworth","TJ Dillashaw","John Dodson","Michael Chiesa"], answer:"Chris Holdsworth", explanation:"Chris Holdsworth won the men's bracket while Julianna Pena won the women's bracket.", sourceId:"tuf18-history" }),
  q({ id:"ufc-r3-mir-sylvia-arm", league:"ufc", round:"round3", category:"Championship Moments", prompt:"Frank Mir won the vacant heavyweight title at UFC 48 by breaking which opponent's arm with an armbar?", choices:["Tim Sylvia","Andrei Arlovski","Randy Couture","Ricco Rodriguez"], answer:"Tim Sylvia", explanation:"Mir trapped Tim Sylvia in an armbar and referee Herb Dean stopped the fight after Sylvia's arm broke, giving Mir the heavyweight title.", sourceId:"ufc48-mir-sylvia", sourceUrl:"https://www.ufc.com/news/10-best-ufc-heavyweight-title-fights-stipe-jones-lesnar-cormier" }),
  q({ id:"ufc-r3-tuf21-format", league:"ufc", round:"round3", category:"The Ultimate Fighter", prompt:"The Ultimate Fighter 21 was built around a rivalry between American Top Team and which gym?", choices:["Blackzilians","AKA","Jackson-Wink","Team Alpha Male"], answer:"Blackzilians", explanation:"TUF 21 used a gym-versus-gym format featuring ATT and the Blackzilians.", sourceId:"tuf21-history" }),
  q({ id:"ufc-r3-silva-belfort-front-kick", league:"ufc", round:"round3", category:"Iconic Finishes", prompt:"Anderson Silva's famous front-kick knockout at UFC 126 came against whom?", choices:["Vitor Belfort","Chael Sonnen","Rich Franklin","Dan Henderson"], answer:"Vitor Belfort", explanation:"Silva dropped Vitor Belfort with a front kick to the chin and finished the fight in the first round.", sourceId:"ufc126-silva-belfort", sourceUrl:"https://www.ufc.com/news/spider-bites-back-anderson-silva-kos-belfort" }),
  q({ id:"ufc-r3-hof-modern-bisping", league:"ufc", round:"round3", category:"Hall of Fame", prompt:"Michael Bisping is inducted in which UFC Hall of Fame wing?", choices:["Modern Wing","Pioneer Wing","Contributors Wing","Fight Wing"], answer:"Modern Wing", explanation:"Bisping entered the Modern Wing in 2019.", sourceId:"ufc-hof-bisping" }),
  q({ id:"ufc-r3-hof-gracie-wing", league:"ufc", round:"round3", category:"Hall of Fame", prompt:"Royce Gracie belongs to which UFC Hall of Fame wing?", choices:["Pioneer Wing","Modern Wing","Contributors Wing","Fight Wing only"], answer:"Pioneer Wing", explanation:"Gracie's career belongs to the Hall of Fame's Pioneer era.", sourceId:"ufc-hof", sourceUrl:HOF }),
  q({ id:"ufc-r3-hof-mask-wing", league:"ufc", round:"round3", category:"Hall of Fame", prompt:"TapouT co-founder Charles 'Mask' Lewis is honored in which Hall of Fame wing?", choices:["Contributors Wing","Pioneer Wing","Modern Wing","Fight Wing"], answer:"Contributors Wing", explanation:"Mask Lewis is recognized for his impact outside the cage in the Contributors Wing.", sourceId:"ufc-hof", sourceUrl:HOF }),
  q({ id:"ufc-r3-zombie-first-twister", league:"ufc", round:"round3", category:"Signature Finishes", prompt:"Whom did Chan Sung Jung submit with the first Twister finish in UFC history?", choices:["Leonard Garcia","Dustin Poirier","Mark Hominick","Dennis Bermudez"], answer:"Leonard Garcia", explanation:"The Korean Zombie forced Leonard Garcia to tap to a Twister at 4:59 of round two in their 2011 rematch.", sourceId:"ufc-zombie-twister", sourceUrl:"https://www.ufc.com/news/2011s-unofficial-half-year-awards-submissions" }),
  q({ id:"ufc-r3-yair-zombie-elbow", league:"ufc", round:"round3", category:"Iconic Finishes", prompt:"Yair Rodriguez knocked out The Korean Zombie in the final second of their 2018 classic with what strike?", choices:["Up elbow","Flying knee","Wheel kick","Spinning backfist"], answer:"Up elbow", explanation:"Rodriguez ducked under Chan Sung Jung's rush and landed an up elbow at 4:59 of round five.", sourceId:"ufc-yair-zombie-finish", sourceUrl:"https://www.ufc.com/news/rodriguez-comes-out-top-instant-classic" }),
  q({ id:"ufc-r3-russia-debut-winner", league:"ufc", round:"round3", category:"Global UFC", prompt:"Who submitted Mark Hunt in the main event of the UFC's first event in Russia?", choices:["Aleksei Oleinik","Alexander Volkov","Alistair Overeem","Curtis Blaydes"], answer:"Aleksei Oleinik", explanation:"Oleinik submitted Hunt with a rear-naked choke in the first round of the UFC's 2018 Moscow debut.", sourceId:"ufc-russia-debut-result", sourceUrl:"https://www.ufc.com/news/oleinik-eyeing-electric-finish-home-fans" }),
  q({ id:"ufc-r3-first-mexico-city", league:"ufc", round:"round3", category:"International History", prompt:"UFC's first event in Mexico was held in which city?", choices:["Mexico City","Monterrey","Guadalajara","Tijuana"], answer:"Mexico City", explanation:"UFC 180 took place in Mexico City in 2014.", sourceId:"ufc180-history" }),
  q({ id:"ufc-r3-ufc180-interim", league:"ufc", round:"round3", category:"Milestone Events", prompt:"Fabricio Werdum won an interim heavyweight title at UFC 180 by stopping whom?", choices:["Mark Hunt","Cain Velasquez","Junior dos Santos","Travis Browne"], answer:"Mark Hunt", explanation:"Werdum stopped Mark Hunt with a flying knee and follow-up strikes.", sourceId:"ufc180-history" }),
  q({ id:"ufc-r3-ufc129-main", league:"ufc", round:"round3", category:"Milestone Events", prompt:"Which welterweight title fight headlined UFC 129 in Toronto?", choices:["Georges St-Pierre vs. Jake Shields","Georges St-Pierre vs. Josh Koscheck","Matt Hughes vs. BJ Penn","Carlos Condit vs. Nick Diaz"], answer:"Georges St-Pierre vs. Jake Shields", explanation:"GSP defended his title against Jake Shields before a massive Toronto crowd.", sourceId:"ufc129-history" }),
  q({ id:"ufc-r3-ufc193-venue-name", league:"ufc", round:"round3", category:"Venues", prompt:"UFC 193 took place at a Melbourne stadium then known as what?", choices:["Etihad Stadium","Marvel Stadium","Rod Laver Arena","MCG"], answer:"Etihad Stadium", explanation:"The venue was called Etihad Stadium at the time of Rousey vs. Holm.", sourceId:"ufc193-history" }),
  q({ id:"ufc-r3-ufc243-venue-name", league:"ufc", round:"round3", category:"Venues", prompt:"UFC 243 took place at which Melbourne venue?", choices:["Marvel Stadium","Rod Laver Arena","Etihad Stadium","MCG"], answer:"Marvel Stadium", explanation:"Whittaker vs. Adesanya headlined UFC 243 at Marvel Stadium.", sourceId:"ufc243-history" }),
  q({ id:"ufc-r3-griffin-bonnar-year", league:"ufc", round:"round3", category:"The Ultimate Fighter", prompt:"Forrest Griffin vs. Stephan Bonnar I took place in which year?", choices:["2005","2003","2007","2009"], answer:"2005", explanation:"The TUF 1 Finale aired in April 2005.", sourceId:"tuf1-history", sourceUrl:TUF1 }),
  q({ id:"ufc-r3-tuf1-network", league:"ufc", round:"round3", category:"Broadcast History", prompt:"The first season of The Ultimate Fighter originally aired on which network?", choices:["Spike TV","ESPN","FX","Fox Sports 1"], answer:"Spike TV", explanation:"TUF debuted on Spike TV in 2005 and helped expand UFC's mainstream audience.", sourceId:"tuf1-history", sourceUrl:TUF1 }),
  q({ id:"ufc-r3-ufc205-state", league:"ufc", round:"round3", category:"Legalization History", prompt:"UFC 205 became possible after professional MMA was legalized in which state?", choices:["New York","New Jersey","Massachusetts","Pennsylvania"], answer:"New York", explanation:"New York legalized professional MMA in 2016, allowing UFC to debut at Madison Square Garden.", sourceId:"ufc205-history" }),

  // Last Call
  q({ id:"ufc-final-schnell-sumudaerji", league:"ufc", round:"last-call", category:"Comebacks", prompt:"Who survived a barrage from Sumudaerji and rallied to win by triangle choke in one of 2022's wildest UFC comebacks?", choices:["Matt Schnell","Brandon Royval","Tim Elliott","Kai Kara-France"], answer:"Matt Schnell", explanation:"Schnell survived being badly hurt, stormed back, and put Sumudaerji to sleep with a second-round triangle choke.", sourceId:"ufc-schnell-sumudaerji", sourceUrl:"https://www.ufc.com/news/submissions-2022-ufc-com-awards" }),
  q({ id:"ufc-final-dean-of-mean", league:"ufc", round:"last-call", category:"Nicknames", prompt:"Which UFC light heavyweight was known as \"The Dean of Mean\"?", choices:["Keith Jardine","Thiago Silva","Brandon Vera","Houston Alexander"], answer:"Keith Jardine", explanation:"Keith Jardine carried \"The Dean of Mean\" nickname during his run against many of the UFC's top light heavyweights.", sourceId:"ufc-jardine-profile", sourceUrl:"https://www.ufc.com/athlete/keith-jardine" }),
  q({ id:"ufc-final-daley-koscheck-release", league:"ufc", round:"last-call", category:"Fight Culture", prompt:"Which UFC 113 fighter was released after throwing a punch at Josh Koscheck after the final bell?", choices:["Paul Daley","Dan Hardy","Thiago Alves","Anthony Johnson"], answer:"Paul Daley", explanation:"Daley took a swing at Koscheck after their bout ended, and UFC president Dana White announced he would be released.", sourceId:"ufc113-daley-koscheck", sourceUrl:"https://www.ufc.com/news/113-ppv-koscheck-shuts-out-daley-ufc-113-co-main-earns-title-shot" }),
  q({ id:"ufc-final-belfort-ufc12-age", league:"ufc", round:"last-call", category:"Old-School UFC", prompt:"How old was Vitor Belfort when he won the UFC 12 heavyweight tournament?", choices:["19","21","23","25"], answer:"19", explanation:"Belfort entered the Octagon at 19 and tore through two opponents to win the UFC 12 heavyweight tournament.", sourceId:"ufc12-belfort-age", sourceUrl:"https://www.ufc.com/news/vitor-belfort-named-ufc-hall-fame-class-2025" }),
  q({ id:"ufc-final-smith-sell-comeback", league:"ufc", round:"last-call", category:"Iconic Finishes", prompt:"Who scored the famous TUF 4 Finale knockout of Pete Sell after being badly hurt by a body shot?", choices:["Scott Smith","Chris Leben","Patrick Cote","Travis Lutter"], answer:"Scott Smith", explanation:"Scott Smith absorbed a brutal body shot, then caught the charging Pete Sell with the one punch he said he had left.", sourceId:"ufc-smith-sell-comeback", sourceUrl:"https://www.ufc.com/news/flashback-smith-sell-and-miracle-comeback-ufc-era" }),
];
