import { barTriviaQuestion, type BarTriviaQuestion } from "../games/barTriviaEngine";

export const BAR_TRIVIA_CURRENT_EVENT_QUESTIONS: readonly BarTriviaQuestion[] = [
  barTriviaQuestion({
    id: "nfl-current-2026-w3-bills-mistakes-win",
    league: "nfl",
    round: "round2",
    difficulty: "medium",
    category: "Current Events",
    prompt: "Which team won in Week 3 despite committing at least five turnovers and at least 10 penalties?",
    choices: ["Buffalo Bills", "Kansas City Chiefs", "Detroit Lions", "Pittsburgh Steelers"],
    answer: "Buffalo Bills",
    explanation: "Buffalo beat the Chargers 24–16 despite becoming just the 10th Bills team to commit at least five turnovers and 10 penalties in the same game.",
    contentType: "current-event",
    activeFrom: "2026-09-27T00:00:00-05:00",
    expiresAt: "2026-10-11T23:59:59-05:00",
    sourceId: "nfl-2026-week3-bills-chargers",
    sourceUrl: "https://www.nfl.com/news/how-rare-was-bills-win-over-chargers-think-replacement-players-and-a-barefoot-kicker",
    verifiedAt: "2026-09-28",
  }),
  barTriviaQuestion({
    id: "cfb-current-2026-w4-iowa-michigan-walkoff",
    league: "cfb",
    round: "round1",
    difficulty: "easy",
    category: "Current Events",
    prompt: "Which team beat Michigan 20–19 on a walk-off touchdown at the Big House for its first win there since 2010?",
    choices: ["Iowa", "Wisconsin", "Michigan State", "USC"],
    answer: "Iowa",
    explanation: "Iowa quarterback Hank Brown found Reece Vander Zee for the game-winning touchdown as time expired in Ann Arbor.",
    contentType: "current-event",
    activeFrom: "2026-09-26T00:00:00-05:00",
    expiresAt: "2026-10-10T23:59:59-05:00",
    sourceId: "ncaa-2026-week4-iowa-michigan",
    sourceUrl: "https://www.ncaa.com/live-updates/football/fbs/college-football-week-4-recaps-highlights-rankings-and-scores",
    verifiedAt: "2026-09-28",
  }),
  barTriviaQuestion({
    id: "ufc-current-2026-09-26-rosas-barcelos",
    league: "ufc",
    round: "round1",
    difficulty: "easy",
    category: "Current Events",
    prompt: "Who stopped Raoni Barcelos in the fifth round of the September 26 UFC Fight Night main event?",
    choices: ["Raul Rosas Jr.", "Montel Jackson", "Brady Hiestand", "Luis Hernandez"],
    answer: "Raul Rosas Jr.",
    explanation: "Raul Rosas Jr. earned a fifth-round stoppage over Raoni Barcelos in the September 26 main event at Meta APEX.",
    contentType: "current-event",
    activeFrom: "2026-09-26T00:00:00-05:00",
    expiresAt: "2026-10-17T23:59:59-05:00",
    sourceId: "ufc-2026-09-26-rosas-barcelos",
    sourceUrl: "https://www.ufc.com/news/ufc-fight-night-rosas-jr-vs-barcelos-results",
    verifiedAt: "2026-09-28",
  }),
];
