import { barTriviaQuestion, type BarTriviaQuestion } from "../games/barTriviaEngine";

const FIRSTS = "https://www.profootballhof.com/news/football-firsts";
const FOUNDING = "https://www.profootballhof.com/news/sept-17-1920-the-founding-of-the-nfl";
const CHIEFS = "https://www.profootballhof.com/teams/kansas-city-chiefs/team-facts";
const PATRIOTS = "https://www.profootballhof.com/teams/new-england-patriots/team-facts";
const RAMS = "https://www.profootballhof.com/teams/los-angeles-rams/team-facts";
const COWBOYS = "https://www.profootballhof.com/teams/dallas-cowboys/team-facts";
const BRONCOS = "https://www.profootballhof.com/teams/denver-broncos/team-facts";

function q(seed: Parameters<typeof barTriviaQuestion>[0]) {
  return barTriviaQuestion({ ...seed, verifiedAt: "2026-09-28" });
}

export const BAR_TRIVIA_NFL_EVERGREEN_EXPANSION: readonly BarTriviaQuestion[] = [
  // Round 1 — accessible bar-room history and identity
  q({ id:"nfl-r1-super-bowl-i-winner", league:"nfl", round:"round1", category:"Super Bowl", prompt:"Which team won the very first Super Bowl?", choices:["Green Bay Packers","Kansas City Chiefs","Dallas Cowboys","Oakland Raiders"], answer:"Green Bay Packers", explanation:"Green Bay beat Kansas City 35–10 in the first AFL-NFL World Championship Game, later known as Super Bowl I.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r1-perfect-season", league:"nfl", round:"round1", category:"Iconic Seasons", prompt:"Which franchise completed the NFL's famous perfect season in 1972?", choices:["Miami Dolphins","Pittsburgh Steelers","Dallas Cowboys","Minnesota Vikings"], answer:"Miami Dolphins", explanation:"Miami finished the 1972 season 17–0, capped by a Super Bowl VII victory.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r1-first-4000-passer", league:"nfl", round:"round1", category:"Milestones", prompt:"Who became pro football's first 4,000-yard passer?", choices:["Joe Namath","Johnny Unitas","Fran Tarkenton","Sonny Jurgensen"], answer:"Joe Namath", explanation:"Joe Namath threw for 4,007 yards for the Jets in 1967.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r1-first-2000-rusher", league:"nfl", round:"round1", category:"Milestones", prompt:"Who became the first NFL player to rush for 2,000 yards in a season?", choices:["O.J. Simpson","Jim Brown","Walter Payton","Eric Dickerson"], answer:"O.J. Simpson", explanation:"O.J. Simpson rushed for 2,003 yards for Buffalo in 1973.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r1-chiefs-dallas-texans", league:"nfl", round:"round1", category:"Franchise Origins", prompt:"Before moving to Kansas City, the Chiefs franchise played under what name?", choices:["Dallas Texans","Kansas City Blues","Houston Oilers","Dallas Rangers"], answer:"Dallas Texans", explanation:"The franchise began as the AFL's Dallas Texans before moving to Kansas City and becoming the Chiefs in 1963.", sourceId:"pfhof-chiefs-facts", sourceUrl:CHIEFS }),
  q({ id:"nfl-r1-patriots-boston", league:"nfl", round:"round1", category:"Franchise Origins", prompt:"What was the New England Patriots' original team name?", choices:["Boston Patriots","Boston Minutemen","New England Colonials","Boston Pilgrims"], answer:"Boston Patriots", explanation:"The franchise entered the AFL as the Boston Patriots and adopted the New England name in 1971.", sourceId:"pfhof-patriots-facts", sourceUrl:PATRIOTS }),
  q({ id:"nfl-r1-rams-cleveland", league:"nfl", round:"round1", category:"Franchise Origins", prompt:"The Rams franchise originally entered the NFL representing which city?", choices:["Cleveland","Los Angeles","St. Louis","Chicago"], answer:"Cleveland", explanation:"The franchise was granted in 1937 as the Cleveland Rams before later moving west.", sourceId:"pfhof-rams-facts", sourceUrl:RAMS }),
  q({ id:"nfl-r1-first-mnf-matchup", league:"nfl", round:"round1", category:"Broadcast", prompt:"The first game in ABC's Monday Night Football series featured the Browns against which team?", choices:["New York Jets","Dallas Cowboys","Pittsburgh Steelers","Miami Dolphins"], answer:"New York Jets", explanation:"Cleveland hosted the New York Jets in the first Monday Night Football telecast in 1970.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r1-first-afl-super-bowl-winner", league:"nfl", round:"round1", category:"Super Bowl", prompt:"Which AFL team became the first to win a Super Bowl?", choices:["New York Jets","Kansas City Chiefs","Oakland Raiders","Buffalo Bills"], answer:"New York Jets", explanation:"The Jets upset the Baltimore Colts in Super Bowl III to give the AFL its first win in the game.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r1-first-wild-card-super-bowl-winner", league:"nfl", round:"round1", category:"Super Bowl", prompt:"Which franchise became the first wild-card team to win the Super Bowl?", choices:["Oakland Raiders","Dallas Cowboys","Pittsburgh Steelers","Los Angeles Rams"], answer:"Oakland Raiders", explanation:"Oakland beat Philadelphia in Super Bowl XV to become the first wild-card Super Bowl champion.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r1-first-indoor-super-bowl", league:"nfl", round:"round1", category:"Super Bowl", prompt:"The first Super Bowl played indoors was held in which city?", choices:["New Orleans","Detroit","Houston","Atlanta"], answer:"New Orleans", explanation:"The first indoor Super Bowl was played in the Louisiana Superdome in New Orleans in January 1978.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r1-first-final-play-super-bowl", league:"nfl", round:"round1", category:"Super Bowl Moments", prompt:"Which team became the first to win a Super Bowl on the final play of the game?", choices:["New England Patriots","San Francisco 49ers","New York Giants","Baltimore Ravens"], answer:"New England Patriots", explanation:"Adam Vinatieri's field goal as time expired beat the Rams in Super Bowl XXXVI.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),

  // Round 2 — deeper history, rules and league evolution
  q({ id:"nfl-r2-apfa-renamed", league:"nfl", round:"round2", category:"League Origins", prompt:"The NFL operated under which name before adopting 'National Football League' in 1922?", choices:["American Professional Football Association","National Gridiron Association","American Football Union","Professional Football Conference"], answer:"American Professional Football Association", explanation:"The league was founded as the APFA in 1920 and officially took the NFL name in 1922.", sourceId:"pfhof-nfl-new-name", sourceUrl:"https://www.profootballhof.com/news/moments-in-nfl-history-new-league-new-names-new-beginnings" }),
  q({ id:"nfl-r2-first-league-president", league:"nfl", round:"round2", category:"League Origins", prompt:"Which legendary athlete served as the first president of the league that became the NFL?", choices:["Jim Thorpe","George Halas","Red Grange","Curly Lambeau"], answer:"Jim Thorpe", explanation:"Jim Thorpe was named president of the APFA when the league formed in 1920.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r2-first-nfl-champion", league:"nfl", round:"round2", category:"League Origins", prompt:"Which team was recognized as the NFL's first champion in 1920?", choices:["Akron Pros","Canton Bulldogs","Chicago Bears","Green Bay Packers"], answer:"Akron Pros", explanation:"The Akron Pros were the champions of the league's inaugural 1920 season.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r2-1958-ot-title", league:"nfl", round:"round2", category:"Historic Games", prompt:"The 1958 NFL Championship, often called 'The Greatest Game Ever Played,' ended with which team beating the Giants in overtime?", choices:["Baltimore Colts","Cleveland Browns","Detroit Lions","Chicago Bears"], answer:"Baltimore Colts", explanation:"Baltimore beat New York 23–17 in the first overtime championship game in NFL history.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r2-first-soccer-kicker", league:"nfl", round:"round2", category:"Oddities", prompt:"Who is credited as pro football's first soccer-style placekicker?", choices:["Pete Gogolak","Jan Stenerud","George Blanda","Lou Groza"], answer:"Pete Gogolak", explanation:"Pete Gogolak brought the soccer-style kicking approach to the Buffalo Bills in 1964.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r2-ref-wireless-mics", league:"nfl", round:"round2", category:"Rules & Broadcast", prompt:"In which decade did NFL referees first begin using wireless microphones?", choices:["1970s","1960s","1980s","1990s"], answer:"1970s", explanation:"The NFL first used wireless microphones for referees in 1975.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r2-thirty-second-clock", league:"nfl", round:"round2", category:"Rules", prompt:"The NFL first introduced a 30-second clock between plays in which year?", choices:["1976","1966","1986","1996"], answer:"1976", explanation:"The league introduced the 30-second clock between plays in 1976.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r2-instant-replay-regular", league:"nfl", round:"round2", category:"Rules", prompt:"The NFL first began using instant replay on a regular basis in which decade?", choices:["1980s","1970s","1990s","2000s"], answer:"1980s", explanation:"Instant replay entered regular NFL use in 1986.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r2-first-game-outside-na", league:"nfl", round:"round2", category:"International", prompt:"The first NFL game played outside North America took place in which city?", choices:["Tokyo","London","Berlin","Mexico City"], answer:"Tokyo", explanation:"The Cardinals and Chargers played a 1976 preseason game in Tokyo, the NFL's first game outside North America.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r2-first-game-europe", league:"nfl", round:"round2", category:"International", prompt:"The NFL's first game in Europe was played at which famous stadium?", choices:["Wembley Stadium","Camp Nou","Olympic Stadium Berlin","San Siro"], answer:"Wembley Stadium", explanation:"Minnesota and St. Louis played a 1983 preseason game at Wembley in London.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r2-first-wild-card-super-bowl", league:"nfl", round:"round2", category:"Playoff History", prompt:"Which team became the first wild-card team to reach a Super Bowl?", choices:["Dallas Cowboys","Oakland Raiders","Miami Dolphins","Denver Broncos"], answer:"Dallas Cowboys", explanation:"Dallas reached Super Bowl X as the first wild-card entrant to make the game.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r2-first-super-bowl-pontiac", league:"nfl", round:"round2", category:"Super Bowl Venues", prompt:"Which Super Bowl was the first played in the Detroit area, at the Pontiac Silverdome?", choices:["Super Bowl XVI","Super Bowl X","Super Bowl XX","Super Bowl XXV"], answer:"Super Bowl XVI", explanation:"San Francisco beat Cincinnati in Super Bowl XVI at the Pontiac Silverdome.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),

  // Round 3 — deep-cut firsts and oddities
  q({ id:"nfl-r3-first-paid-pro", league:"nfl", round:"round3", category:"Pro Football Origins", prompt:"Who is recognized as the first known professional football player after being paid $500 for a game in 1892?", choices:["Pudge Heffelfinger","Jim Thorpe","Red Grange","George Halas"], answer:"Pudge Heffelfinger", explanation:"William 'Pudge' Heffelfinger was paid $500 to play for the Allegheny Athletic Association in 1892.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r3-league-founded-city", league:"nfl", round:"round3", category:"League Origins", prompt:"The league that became the NFL was formally organized in 1920 in which Ohio city?", choices:["Canton","Cleveland","Akron","Dayton"], answer:"Canton", explanation:"Club representatives met in Canton, Ohio, in 1920 to organize the APFA.", sourceId:"pfhof-nfl-founding", sourceUrl:FOUNDING }),
  q({ id:"nfl-r3-dayton-triangles", league:"nfl", round:"round3", category:"League Origins", prompt:"Which team beat the Columbus Panhandles 14–0 in one of the NFL's first league games in 1920?", choices:["Dayton Triangles","Akron Pros","Canton Bulldogs","Rock Island Independents"], answer:"Dayton Triangles", explanation:"The Dayton Triangles beat Columbus 14–0 on October 3, 1920, one of the league's first games.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r3-first-two-time-champ", league:"nfl", round:"round3", category:"Early NFL", prompt:"Which early NFL franchise became the league's first two-time champion?", choices:["Canton Bulldogs","Akron Pros","Chicago Cardinals","Dayton Triangles"], answer:"Canton Bulldogs", explanation:"The Canton Bulldogs won championships in 1922 and 1923.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r3-touchdown-six-points", league:"nfl", round:"round3", category:"Rules History", prompt:"In what year did a touchdown first become worth six points in pro football?", choices:["1912","1902","1920","1933"], answer:"1912", explanation:"Touchdowns became worth six points in 1912 after previously being worth four and then five.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r3-first-night-game", league:"nfl", round:"round3", category:"Football Firsts", prompt:"The first night pro football game on a lighted field was played in which year?", choices:["1902","1912","1922","1932"], answer:"1902", explanation:"The Philadelphia Athletics played Kanaweola A.C. under lights in Elmira, New York, in 1902.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r3-first-indoor-game", league:"nfl", round:"round3", category:"Football Firsts", prompt:"The first indoor pro football game was played at which famous New York venue?", choices:["Madison Square Garden","Yankee Stadium","Polo Grounds","Ebbets Field"], answer:"Madison Square Garden", explanation:"Syracuse A.C. beat New York 5–0 at Madison Square Garden in December 1902.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r3-first-black-pro", league:"nfl", round:"round3", category:"Football History", prompt:"Which player is recognized by the Hall of Fame as an early African-American pro who signed with the Shelby Athletic Club in 1904?", choices:["Charles Follis","Fritz Pollard","Kenny Washington","Joe Lillard"], answer:"Charles Follis", explanation:"Charles Follis reportedly signed a professional contract with the Shelby Athletic Club in 1904.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r3-super-bowl-name-first-used", league:"nfl", round:"round3", category:"Super Bowl History", prompt:"At which game was the title 'Super Bowl' officially recognized for the first time?", choices:["Super Bowl III","Super Bowl I","Super Bowl V","Super Bowl VII"], answer:"Super Bowl III", explanation:"The 'Super Bowl' title was officially recognized for the first time for Jets-Colts in January 1969.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r3-only-super-bowl-not-sellout", league:"nfl", round:"round3", category:"Super Bowl Oddities", prompt:"Which Super Bowl remains the only one that did not sell out?", choices:["Super Bowl I","Super Bowl II","Super Bowl III","Super Bowl V"], answer:"Super Bowl I", explanation:"The first Super Bowl at the Los Angeles Coliseum did not sell out.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r3-president-at-game", league:"nfl", round:"round3", category:"Presidential History", prompt:"Who became the first sitting U.S. president to attend an NFL game?", choices:["Lyndon B. Johnson","Richard Nixon","John F. Kennedy","Gerald Ford"], answer:"Lyndon B. Johnson", explanation:"Lyndon Johnson attended a preseason game at D.C. Stadium in 1966.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
  q({ id:"nfl-r3-pro-bowl-honolulu", league:"nfl", round:"round3", category:"Pro Bowl", prompt:"The Pro Bowl was first played in Honolulu in which decade?", choices:["1980s","1970s","1990s","1960s"], answer:"1980s", explanation:"The NFL's all-star game was first played in Honolulu in January 1980.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),

  // Last Call — hard but answerable history
  q({ id:"nfl-final-cowboys-first-draft", league:"nfl", round:"last-call", category:"Draft History", prompt:"Which Hall of Famer was the Dallas Cowboys' first-ever draft choice?", choices:["Bob Lilly","Roger Staubach","Mel Renfro","Don Meredith"], answer:"Bob Lilly", explanation:"Dallas used its first draft choice in franchise history on TCU defensive tackle Bob Lilly in 1961.", sourceId:"pfhof-cowboys-facts", sourceUrl:COWBOYS }),
  q({ id:"nfl-final-broncos-first-afl-win", league:"nfl", round:"last-call", category:"AFL History", prompt:"Which franchise won the AFL's first regular-season game in 1960?", choices:["Denver Broncos","Boston Patriots","Dallas Texans","Houston Oilers"], answer:"Denver Broncos", explanation:"Denver beat the Boston Patriots 13–10 in the first AFL regular-season game.", sourceId:"pfhof-broncos-facts", sourceUrl:BRONCOS }),
  q({ id:"nfl-final-chiefs-first-super-bowl-win-opponent", league:"nfl", round:"last-call", category:"Super Bowl History", prompt:"Which team did Kansas City beat for the franchise's first Super Bowl victory?", choices:["Minnesota Vikings","Green Bay Packers","Oakland Raiders","Dallas Cowboys"], answer:"Minnesota Vikings", explanation:"Kansas City beat Minnesota 23–7 in Super Bowl IV for its first Super Bowl title.", sourceId:"pfhof-chiefs-facts", sourceUrl:CHIEFS }),
  q({ id:"nfl-final-first-american-bowl", league:"nfl", round:"last-call", category:"International", prompt:"Which two teams played in the first American Bowl at Wembley Stadium in 1986?", choices:["Chicago Bears and Dallas Cowboys","Miami Dolphins and New York Giants","San Francisco 49ers and Denver Broncos","Raiders and Patriots"], answer:"Chicago Bears and Dallas Cowboys", explanation:"Chicago beat Dallas 17–6 at Wembley in the first American Bowl.", sourceId:"pfhof-football-firsts", sourceUrl:FIRSTS }),
];
