import { barTriviaQuestion, type BarTriviaQuestion } from "../games/barTriviaEngine";

const UFC1 = "https://www.ufc.com/news/revisiting-ufc-1-beginning";
const HOF = "https://www.ufc.com/news/ufc-hall-fame-faq";
const HOF_2015 = "https://www.ufc.com/news/ufc-hall-fame-2015-media-faqs";
const FIGHT_ISLAND = "https://www.ufc.com/news/ufc-fight-island-where-ufc-fight-island-fight-island-schedule-and-more";
const UFC30 = "https://www.ufc.com/30";
const ESPARZA = "https://www.ufc.com/news/first-strawweight-champion-30th-anniversary-carla-esparza";
const DERANDAMIE = "https://www.ufc.com/news/de-randamie-makes-history-defeating-holm";
const UFC112 = "https://www.ufc.com/news/abu-dhabi-host-ufc-title-fights-5-years";
const RECORDS = "https://statleaders.ufc.com/fight";

function q(seed: Parameters<typeof barTriviaQuestion>[0]) {
  return barTriviaQuestion({ ...seed, verifiedAt: "2026-09-28" });
}

export const BAR_TRIVIA_UFC_EVERGREEN_EXPANSION: readonly BarTriviaQuestion[] = [
  // Round 1 — recognizable personalities, nicknames and UFC landmarks
  q({ id:"ufc-r1-notorious", league:"ufc", round:"round1", category:"Nicknames", prompt:"Which UFC star is known as 'The Notorious'?", choices:["Conor McGregor","Dustin Poirier","Michael Chandler","Nate Diaz"], answer:"Conor McGregor", explanation:"Conor McGregor has long competed under the nickname 'The Notorious.'", sourceId:"ufc-athlete-mcgregor", sourceUrl:"https://www.ufc.com/athlete/conor-mcgregor" }),
  q({ id:"ufc-r1-bones", league:"ufc", round:"round1", category:"Nicknames", prompt:"Which former light heavyweight champion is known as 'Bones'?", choices:["Jon Jones","Daniel Cormier","Rashad Evans","Jamahal Hill"], answer:"Jon Jones", explanation:"Jon Jones' longtime nickname is 'Bones.'", sourceId:"ufc-athlete-jones", sourceUrl:"https://www.ufc.com/athlete/jon-jones" }),
  q({ id:"ufc-r1-rush", league:"ufc", round:"round1", category:"Nicknames", prompt:"Which UFC legend fought under the nickname 'Rush'?", choices:["Georges St-Pierre","Matt Hughes","BJ Penn","Carlos Condit"], answer:"Georges St-Pierre", explanation:"Georges St-Pierre is listed by UFC under the nickname 'Rush.'", sourceId:"ufc-athlete-gsp", sourceUrl:"https://www.ufc.com/athlete/georges-st-pierre" }),
  q({ id:"ufc-r1-spider", league:"ufc", round:"round1", category:"Nicknames", prompt:"Which longtime middleweight champion is famously known as 'The Spider'?", choices:["Anderson Silva","Israel Adesanya","Chris Weidman","Vitor Belfort"], answer:"Anderson Silva", explanation:"Anderson Silva's famous nickname is 'The Spider.'", sourceId:"ufc-athlete-silva", sourceUrl:"https://www.ufc.com/athlete/anderson-silva" }),
  q({ id:"ufc-r1-blessed", league:"ufc", round:"round1", category:"Nicknames", prompt:"Which Hawaiian UFC star is known as 'Blessed'?", choices:["Max Holloway","BJ Penn","Dan Ige","Brad Tavares"], answer:"Max Holloway", explanation:"Max Holloway competes under the nickname 'Blessed.'", sourceId:"ufc-athlete-holloway", sourceUrl:"https://www.ufc.com/athlete/max-holloway" }),
  q({ id:"ufc-r1-el-cucuy", league:"ufc", round:"round1", category:"Nicknames", prompt:"Which former interim lightweight champion is known as 'El Cucuy'?", choices:["Tony Ferguson","Justin Gaethje","Dustin Poirier","Rafael dos Anjos"], answer:"Tony Ferguson", explanation:"Tony Ferguson's longtime nickname is 'El Cucuy.'", sourceId:"ufc-athlete-ferguson", sourceUrl:"https://www.ufc.com/athlete/tony-ferguson" }),
  q({ id:"ufc-r1-cowboy", league:"ufc", round:"round1", category:"Nicknames", prompt:"Which fan favorite is best known simply as 'Cowboy'?", choices:["Donald Cerrone","Jim Miller","Clay Guida","Matt Brown"], answer:"Donald Cerrone", explanation:"Donald Cerrone competed throughout his UFC career as 'Cowboy.'", sourceId:"ufc-athlete-cerrone", sourceUrl:"https://www.ufc.com/athlete/donald-cerrone" }),
  q({ id:"ufc-r1-thug-rose", league:"ufc", round:"round1", category:"Nicknames", prompt:"Which former UFC champion is known as 'Thug Rose'?", choices:["Rose Namajunas","Joanna Jedrzejczyk","Zhang Weili","Carla Esparza"], answer:"Rose Namajunas", explanation:"Rose Namajunas' UFC profile lists her nickname as 'Thug.'", sourceId:"ufc-athlete-namajunas", sourceUrl:"https://www.ufc.com/athlete/rose-namajunas" }),
  q({ id:"ufc-r1-fight-island-location", league:"ufc", round:"round1", category:"Venues", prompt:"UFC's famous 'Fight Island' events were staged on which island?", choices:["Yas Island","Saadiyat Island","Alcatraz Island","Sentosa Island"], answer:"Yas Island", explanation:"UFC Fight Island was staged on Yas Island in Abu Dhabi.", sourceId:"ufc-fight-island", sourceUrl:FIGHT_ISLAND }),
  q({ id:"ufc-r1-first-strawweight-champ", league:"ufc", round:"round1", category:"Championships", prompt:"Who became the UFC's first women's strawweight champion?", choices:["Carla Esparza","Rose Namajunas","Joanna Jedrzejczyk","Claudia Gadelha"], answer:"Carla Esparza", explanation:"Carla Esparza won the inaugural UFC women's strawweight title in 2014.", sourceId:"ufc-esparza-first-champ", sourceUrl:ESPARZA }),
  q({ id:"ufc-r1-first-womens-featherweight-champ", league:"ufc", round:"round1", category:"Championships", prompt:"Who became the UFC's first women's featherweight champion?", choices:["Germaine de Randamie","Holly Holm","Cris Cyborg","Amanda Nunes"], answer:"Germaine de Randamie", explanation:"Germaine de Randamie beat Holly Holm at UFC 208 to become the inaugural women's featherweight champion.", sourceId:"ufc-derandamie-first-champ", sourceUrl:DERANDAMIE }),
  q({ id:"ufc-r1-first-hof-pair", league:"ufc", round:"round1", category:"Hall of Fame", prompt:"Which two fighters were the first inductees into the UFC Hall of Fame?", choices:["Royce Gracie and Ken Shamrock","Chuck Liddell and Randy Couture","Tito Ortiz and Matt Hughes","Forrest Griffin and Stephan Bonnar"], answer:"Royce Gracie and Ken Shamrock", explanation:"Royce Gracie and Ken Shamrock became the first UFC Hall of Fame inductees in 2003.", sourceId:"ufc-hof", sourceUrl:HOF }),

  // Round 2 — event history and the stories behind familiar UFC landmarks
  q({ id:"ufc-r2-el-cucuy-meaning", league:"ufc", round:"round2", category:"Nicknames", prompt:"Tony Ferguson's nickname 'El Cucuy' roughly translates to what in English?", choices:["The Boogeyman","The Hunter","The Nightmare","The Wild One"], answer:"The Boogeyman", explanation:"UFC describes 'El Cucuy' as meaning 'The Boogeyman' in Spanish.", sourceId:"ufc-athlete-ferguson", sourceUrl:"https://www.ufc.com/athlete/tony-ferguson" }),
  q({ id:"ufc-r2-hof-first-event", league:"ufc", round:"round2", category:"Hall of Fame", prompt:"At UFC 45, which two fighters became the UFC Hall of Fame's first inductees?", choices:["Royce Gracie and Ken Shamrock","Chuck Liddell and Randy Couture","Dan Severn and Mark Coleman","Tito Ortiz and Frank Shamrock"], answer:"Royce Gracie and Ken Shamrock", explanation:"The first UFC Hall of Fame induction ceremony took place around UFC 45 in 2003.", sourceId:"ufc-45-hof", sourceUrl:"https://www.ufc.com/news/on-this-day-ufc-45-revolution" }),
  q({ id:"ufc-r2-modern-era-event", league:"ufc", round:"round2", category:"Rules History", prompt:"What major rules milestone makes UFC 28 the start of the UFC's modern era?", choices:["First event under the Unified Rules of MMA","First event with mandatory gloves","First event with weight classes","First event with five-round title fights"], answer:"First event under the Unified Rules of MMA", explanation:"UFC 28 in November 2000 was the first UFC event to use the Unified Rules of Mixed Martial Arts.", sourceId:"ufc-hof-rules-era", sourceUrl:HOF_2015 }),
  q({ id:"ufc-r2-first-outdoor-event", league:"ufc", round:"round2", category:"Venues", prompt:"What venue milestone did UFC 112 set in Abu Dhabi?", choices:["First UFC event held outdoors","First UFC event in a stadium","First UFC event on Fight Island","First UFC event in Asia"], answer:"First UFC event held outdoors", explanation:"UFC 112 in Abu Dhabi was the promotion's first event held outdoors.", sourceId:"ufc-112-outdoor", sourceUrl:UFC112 }),
  q({ id:"ufc-r2-first-fight-island-ppv", league:"ufc", round:"round2", category:"Fight Island", prompt:"UFC 251 launched the first Fight Island run on which Abu Dhabi island?", choices:["Yas Island","Saadiyat Island","Al Maryah Island","Palm Jumeirah"], answer:"Yas Island", explanation:"The first Fight Island series opened with UFC 251 on Yas Island in July 2020.", sourceId:"ufc-fight-island", sourceUrl:FIGHT_ISLAND }),
  q({ id:"ufc-r2-first-abc-main-event", league:"ufc", round:"round2", category:"Broadcast", prompt:"Which matchup headlined the first UFC main card broadcast on ABC?", choices:["Max Holloway vs. Calvin Kattar","Conor McGregor vs. Dustin Poirier","Kamaru Usman vs. Jorge Masvidal","Israel Adesanya vs. Paulo Costa"], answer:"Max Holloway vs. Calvin Kattar", explanation:"Holloway vs. Kattar in January 2021 headlined the UFC's first ABC main-card broadcast.", sourceId:"ufc-30th-anniversary", sourceUrl:UFC30 }),
  q({ id:"ufc-r2-esparza-title-opponent", league:"ufc", round:"round2", category:"Championships", prompt:"Carla Esparza defeated whom to become the UFC's first women's strawweight champion?", choices:["Rose Namajunas","Joanna Jedrzejczyk","Claudia Gadelha","Jessica Andrade"], answer:"Rose Namajunas", explanation:"Esparza submitted Rose Namajunas in the TUF 20 Finale to win the inaugural strawweight belt.", sourceId:"ufc-esparza-first-champ", sourceUrl:ESPARZA }),
  q({ id:"ufc-r2-derandamie-title-opponent", league:"ufc", round:"round2", category:"Championships", prompt:"Germaine de Randamie beat which former champion to win the inaugural UFC women's featherweight belt?", choices:["Holly Holm","Cris Cyborg","Miesha Tate","Amanda Nunes"], answer:"Holly Holm", explanation:"De Randamie defeated Holly Holm by decision in the UFC 208 main event.", sourceId:"ufc-derandamie-first-champ", sourceUrl:DERANDAMIE }),
  q({ id:"ufc-r2-ufc1-arena", league:"ufc", round:"round2", category:"Origins", prompt:"UFC 1 took place at which Denver arena?", choices:["McNichols Sports Arena","Ball Arena","Denver Coliseum","Mile High Stadium"], answer:"McNichols Sports Arena", explanation:"The inaugural UFC event was held at McNichols Sports Arena in Denver.", sourceId:"ufc1-revisited", sourceUrl:UFC1 }),
  q({ id:"ufc-r2-first-fight-wing", league:"ufc", round:"round2", category:"Hall of Fame", prompt:"Which famous bout became the first fight inducted into the UFC Hall of Fame's Fight Wing?", choices:["Forrest Griffin vs. Stephan Bonnar I","Jon Jones vs. Alexander Gustafsson I","Dan Henderson vs. Shogun Rua I","Matt Hughes vs. Frank Trigg II"], answer:"Forrest Griffin vs. Stephan Bonnar I", explanation:"Griffin-Bonnar I was inducted into the Hall of Fame Fight Wing in 2014.", sourceId:"ufc-hof", sourceUrl:HOF }),
  q({ id:"ufc-r2-hof-jones-gustafsson", league:"ufc", round:"round2", category:"Hall of Fame", prompt:"Jon Jones' classic 2013 title fight against which opponent is in the UFC Hall of Fame Fight Wing?", choices:["Alexander Gustafsson","Daniel Cormier","Lyoto Machida","Glover Teixeira"], answer:"Alexander Gustafsson", explanation:"Jones vs. Gustafsson I, from September 2013, is a UFC Hall of Fame Fight Wing bout.", sourceId:"ufc-hof", sourceUrl:HOF }),
  q({ id:"ufc-r2-hof-hendo-shogun", league:"ufc", round:"round2", category:"Hall of Fame", prompt:"Dan Henderson's legendary five-round 2011 fight against which opponent is in the UFC Hall of Fame?", choices:["Mauricio 'Shogun' Rua","Wanderlei Silva","Rich Franklin","Vitor Belfort"], answer:"Mauricio 'Shogun' Rua", explanation:"Henderson vs. Shogun Rua I was inducted into the UFC Hall of Fame Fight Wing.", sourceId:"ufc-hof", sourceUrl:HOF }),

  // Round 3 — deeper UFC history, records and Hall of Fame knowledge
  q({ id:"ufc-r3-fastest-ko", league:"ufc", round:"round3", category:"Iconic Records", prompt:"Who owns the UFC record for the fastest knockout, a five-second finish of Ben Askren?", choices:["Jorge Masvidal","Conor McGregor","Duane Ludwig","Chan Sung Jung"], answer:"Jorge Masvidal", explanation:"Jorge Masvidal knocked out Ben Askren in five seconds at UFC 239.", sourceId:"ufc-record-book", sourceUrl:RECORDS }),
  q({ id:"ufc-r3-first-ufc1-fight", league:"ufc", round:"round3", category:"Origins", prompt:"Which matchup opened the very first UFC event?", choices:["Gerard Gordeau vs. Teila Tuli","Royce Gracie vs. Ken Shamrock","Kevin Rosier vs. Zane Frazier","Jason DeLucia vs. Trent Jenkins"], answer:"Gerard Gordeau vs. Teila Tuli", explanation:"Gerard Gordeau and Teila Tuli contested the first bout at UFC 1.", sourceId:"ufc1-revisited", sourceUrl:UFC1 }),
  q({ id:"ufc-r3-ufc1-first-fight-winner", league:"ufc", round:"round3", category:"Origins", prompt:"Who won the first fight in UFC history?", choices:["Gerard Gordeau","Royce Gracie","Ken Shamrock","Kevin Rosier"], answer:"Gerard Gordeau", explanation:"Gerard Gordeau stopped Teila Tuli in the opening bout of UFC 1.", sourceId:"ufc1-revisited", sourceUrl:UFC1 }),
  q({ id:"ufc-r3-hof-hughes-trigg", league:"ufc", round:"round3", category:"Hall of Fame", prompt:"Matt Hughes' famous 2005 comeback fight in the UFC Hall of Fame came against whom?", choices:["Frank Trigg","BJ Penn","Georges St-Pierre","Carlos Newton"], answer:"Frank Trigg", explanation:"Matt Hughes vs. Frank Trigg II is part of the UFC Hall of Fame Fight Wing.", sourceId:"ufc-hof", sourceUrl:HOF }),
  q({ id:"ufc-r3-hof-sanchez-guida", league:"ufc", round:"round3", category:"Hall of Fame", prompt:"Which 2009 war featuring Diego Sanchez is in the UFC Hall of Fame Fight Wing?", choices:["Diego Sanchez vs. Clay Guida","Diego Sanchez vs. BJ Penn","Diego Sanchez vs. Nick Diaz","Diego Sanchez vs. Martin Kampmann"], answer:"Diego Sanchez vs. Clay Guida", explanation:"Sanchez vs. Clay Guida from June 2009 was inducted into the Hall of Fame Fight Wing.", sourceId:"ufc-hof", sourceUrl:HOF }),
  q({ id:"ufc-r3-hof-swanson-choi", league:"ufc", round:"round3", category:"Hall of Fame", prompt:"Cub Swanson's 2016 Fight Wing classic came against which opponent?", choices:["Doo Ho Choi","Korean Zombie","Jeremy Stephens","Charles Oliveira"], answer:"Doo Ho Choi", explanation:"Cub Swanson vs. Doo Ho Choi is a UFC Hall of Fame Fight Wing bout.", sourceId:"ufc-hof", sourceUrl:HOF }),
  q({ id:"ufc-r3-first-hof-contributor", league:"ufc", round:"round3", category:"Hall of Fame", prompt:"Which TapouT co-founder became the first person inducted into the UFC Hall of Fame Contributors Wing?", choices:["Charles 'Mask' Lewis","Dana White","Joe Silva","Art Davie"], answer:"Charles 'Mask' Lewis", explanation:"Charles 'Mask' Lewis was inducted in 2009 and is listed as the earliest Contributors Wing inductee.", sourceId:"ufc-hof", sourceUrl:HOF }),
  q({ id:"ufc-r3-fight-island-year", league:"ufc", round:"round3", category:"Fight Island", prompt:"The original UFC Fight Island series debuted in which year?", choices:["2020","2018","2019","2021"], answer:"2020", explanation:"UFC staged the first Fight Island series on Yas Island in July 2020.", sourceId:"ufc-fight-island", sourceUrl:FIGHT_ISLAND }),
  q({ id:"ufc-r3-first-abu-dhabi-event", league:"ufc", round:"round3", category:"International", prompt:"At UFC 112, which middleweight title fight headlined the UFC's first event in Abu Dhabi?", choices:["Anderson Silva vs. Demian Maia","Anderson Silva vs. Vitor Belfort","BJ Penn vs. Frankie Edgar","Georges St-Pierre vs. Dan Hardy"], answer:"Anderson Silva vs. Demian Maia", explanation:"UFC 112 in April 2010 was the promotion's first event in Abu Dhabi.", sourceId:"ufc-112-outdoor", sourceUrl:UFC112 }),
  q({ id:"ufc-r3-ufc251-headliner", league:"ufc", round:"round3", category:"Fight Island", prompt:"Who challenged Kamaru Usman in the main event of UFC 251, the first Fight Island pay-per-view?", choices:["Jorge Masvidal","Gilbert Burns","Colby Covington","Leon Edwards"], answer:"Jorge Masvidal", explanation:"UFC 251 on Fight Island was headlined by Kamaru Usman vs. Jorge Masvidal.", sourceId:"ufc-30th-anniversary", sourceUrl:UFC30 }),
  q({ id:"ufc-r3-hof-gracie-year", league:"ufc", round:"round3", category:"Hall of Fame", prompt:"Royce Gracie and Ken Shamrock became the UFC Hall of Fame's first inductees in which year?", choices:["2003","2000","2005","2008"], answer:"2003", explanation:"Gracie and Shamrock were inducted as the Hall of Fame's first members in 2003.", sourceId:"ufc-hof", sourceUrl:HOF }),
  q({ id:"ufc-r3-esparza-tuf-season", league:"ufc", round:"round3", category:"The Ultimate Fighter", prompt:"Carla Esparza won which season of The Ultimate Fighter before becoming the inaugural UFC strawweight champion?", choices:["TUF 20","TUF 18","TUF 22","TUF 16"], answer:"TUF 20", explanation:"Esparza won The Ultimate Fighter 20 and then captured the inaugural strawweight title.", sourceId:"ufc-esparza-first-champ", sourceUrl:ESPARZA }),

  // Last Call — deep history with a memorable hook
  q({ id:"ufc-final-ufc1-name-mistake", league:"ufc", round:"last-call", category:"Broadcast Oddities", prompt:"During the UFC 1 television intro, commentator Bill Wallace accidentally called the promotion the Ultimate Fighting what?", choices:["Challenge","Contest","Circuit","Cup"], answer:"Challenge", explanation:"Bill 'Superfoot' Wallace mistakenly introduced UFC 1 as the 'Ultimate Fighting Challenge.'", sourceId:"ufc1-revisited", sourceUrl:UFC1 }),
  q({ id:"ufc-final-unified-rules-date", league:"ufc", round:"last-call", category:"Rules History", prompt:"UFC 28, the promotion's first event under the Unified Rules of MMA, took place in which year?", choices:["2000","1998","2002","2004"], answer:"2000", explanation:"UFC 28 took place on Nov. 17, 2000 and is used as the Hall of Fame dividing line for the modern era.", sourceId:"ufc-hof-rules-era", sourceUrl:HOF_2015 }),
  q({ id:"ufc-final-first-outdoor-city", league:"ufc", round:"last-call", category:"Venues", prompt:"The UFC's first outdoor event was staged in which city?", choices:["Abu Dhabi","Rio de Janeiro","Las Vegas","Sydney"], answer:"Abu Dhabi", explanation:"UFC 112 was held in an open-air arena on Yas Island in Abu Dhabi in 2010.", sourceId:"ufc-112-outdoor", sourceUrl:UFC112 }),
  q({ id:"ufc-final-first-abc-year", league:"ufc", round:"last-call", category:"Broadcast", prompt:"The UFC's first main card broadcast on ABC took place in which year?", choices:["2021","2019","2020","2022"], answer:"2021", explanation:"Holloway vs. Kattar in January 2021 marked the UFC's first main-card broadcast on ABC.", sourceId:"ufc-30th-anniversary", sourceUrl:UFC30 }),
];
