import { barTriviaQuestion, type BarTriviaQuestion } from "../games/barTriviaEngine";

const NFL100 = "https://www.nfl.com/100/greatest-moment/all-32.html";
const NFL_PLAYS = "https://www.nfl.com/news/nfl-s-100-greatest-plays-the-final-five-unveiled-0ap3000001056879";
const PFHOF_NICKNAMES = "https://www.profootballhof.com/news/moments-in-nfl-history-name-game-gains-fame";
const FIRSTS = "https://www.profootballhof.com/news/football-firsts";
const LOMBARDI = "https://www.profootballhof.com/news/moments-in-nfl-history-championship-trophy-gets-new-iconic-name";

function q(seed: Parameters<typeof barTriviaQuestion>[0]) {
  return barTriviaQuestion({ ...seed, verifiedAt: "2026-09-28" });
}

export const BAR_TRIVIA_NFL_EVERGREEN_WAVE_3: readonly BarTriviaQuestion[] = [
  // Round 1 — famous nicknames, units, traditions
  q({ id:"nfl-r1-megatron", league:"nfl", round:"round1", category:"Nicknames", prompt:"Which Hall of Fame receiver is famously nicknamed 'Megatron'?", choices:["Calvin Johnson","Randy Moss","Terrell Owens","Larry Fitzgerald"], answer:"Calvin Johnson", explanation:"Calvin Johnson's size and athleticism inspired the enduring nickname Megatron.", sourceId:"pfhof-nicknames", sourceUrl:PFHOF_NICKNAMES }),
  q({ id:"nfl-r1-prime-time", league:"nfl", round:"round1", category:"Nicknames", prompt:"Which Hall of Famer is known as 'Prime Time'?", choices:["Deion Sanders","Michael Irvin","Jerry Rice","Darrell Green"], answer:"Deion Sanders", explanation:"Deion Sanders built one of football's biggest personalities around the nickname Prime Time.", sourceId:"pfhof-nicknames", sourceUrl:PFHOF_NICKNAMES }),
  q({ id:"nfl-r1-the-playmaker", league:"nfl", round:"round1", category:"Nicknames", prompt:"Which Cowboys receiver was known as 'The Playmaker'?", choices:["Michael Irvin","Dez Bryant","Drew Pearson","Bob Hayes"], answer:"Michael Irvin", explanation:"Hall of Fame receiver Michael Irvin became widely known as The Playmaker.", sourceId:"pfhof-nicknames", sourceUrl:PFHOF_NICKNAMES }),
  q({ id:"nfl-r1-mean-joe", league:"nfl", round:"round1", category:"Nicknames", prompt:"Which Steelers legend carried the nickname 'Mean Joe'?", choices:["Joe Greene","Jack Lambert","Jack Ham","Mel Blount"], answer:"Joe Greene", explanation:"Defensive tackle Joe Greene was the centerpiece of Pittsburgh's Steel Curtain and became known as Mean Joe.", sourceId:"pfhof-nicknames", sourceUrl:PFHOF_NICKNAMES }),
  q({ id:"nfl-r1-the-bus", league:"nfl", round:"round1", category:"Nicknames", prompt:"Which running back was famously nicknamed 'The Bus'?", choices:["Jerome Bettis","Earl Campbell","Christian Okoye","Mike Alstott"], answer:"Jerome Bettis", explanation:"Jerome Bettis' bruising running style made The Bus one of the NFL's most recognizable nicknames.", sourceId:"nfl-nicknames" }),
  q({ id:"nfl-r1-sweetness", league:"nfl", round:"round1", category:"Nicknames", prompt:"Which Bears icon was known as 'Sweetness'?", choices:["Walter Payton","Gale Sayers","Mike Singletary","Dick Butkus"], answer:"Walter Payton", explanation:"Walter Payton was affectionately known throughout his career as Sweetness.", sourceId:"nfl-nicknames" }),
  q({ id:"nfl-r1-the-fridge", league:"nfl", round:"round1", category:"Nicknames", prompt:"Which 1985 Bears defensive lineman became a pop-culture star as 'The Refrigerator'?", choices:["William Perry","Richard Dent","Dan Hampton","Steve McMichael"], answer:"William Perry", explanation:"William Perry's massive frame and goal-line appearances made The Refrigerator a national phenomenon.", sourceId:"bears-1985" }),
  q({ id:"nfl-r1-purple-people-eaters", league:"nfl", round:"round1", category:"Famous Units", prompt:"The 'Purple People Eaters' defensive line belonged to which franchise?", choices:["Minnesota Vikings","Baltimore Ravens","Los Angeles Rams","Denver Broncos"], answer:"Minnesota Vikings", explanation:"Minnesota's dominant defensive line of the late 1960s and 1970s became known as the Purple People Eaters.", sourceId:"vikings-history" }),
  q({ id:"nfl-r1-steel-curtain", league:"nfl", round:"round1", category:"Famous Units", prompt:"The 'Steel Curtain' defense belonged to which dynasty?", choices:["Pittsburgh Steelers","Dallas Cowboys","Miami Dolphins","Oakland Raiders"], answer:"Pittsburgh Steelers", explanation:"Pittsburgh's fearsome 1970s defense was nicknamed the Steel Curtain.", sourceId:"steelers-history" }),
  q({ id:"nfl-r1-orange-crush", league:"nfl", round:"round1", category:"Famous Units", prompt:"The 'Orange Crush' defense is most closely associated with which team?", choices:["Denver Broncos","Cleveland Browns","Cincinnati Bengals","Chicago Bears"], answer:"Denver Broncos", explanation:"Denver's dominant late-1970s defense became known as the Orange Crush.", sourceId:"broncos-history" }),
  q({ id:"nfl-r1-no-name-defense", league:"nfl", round:"round1", category:"Famous Units", prompt:"The 'No-Name Defense' helped which team complete the perfect 1972 season?", choices:["Miami Dolphins","Dallas Cowboys","Pittsburgh Steelers","Minnesota Vikings"], answer:"Miami Dolphins", explanation:"Miami's overlooked defense adopted the No-Name Defense identity during its early-1970s championship run.", sourceId:"dolphins-history" }),
  q({ id:"nfl-r1-legion-boom", league:"nfl", round:"round1", category:"Famous Units", prompt:"The 'Legion of Boom' secondary belonged to which team?", choices:["Seattle Seahawks","Baltimore Ravens","Denver Broncos","San Francisco 49ers"], answer:"Seattle Seahawks", explanation:"Seattle's championship-era secondary became famous as the Legion of Boom.", sourceId:"seahawks-history" }),
  q({ id:"nfl-r1-the-hogs", league:"nfl", round:"round1", category:"Famous Units", prompt:"The offensive line nicknamed 'The Hogs' powered which franchise in the 1980s and early 1990s?", choices:["Washington","New York Giants","Dallas Cowboys","Chicago Bears"], answer:"Washington", explanation:"Washington's powerful offensive line under Joe Gibbs became known as The Hogs.", sourceId:"washington-history" }),
  q({ id:"nfl-r1-lambeau-leap-originator", league:"nfl", round:"round1", category:"Celebrations", prompt:"Which Packers defensive back is credited with creating the Lambeau Leap?", choices:["LeRoy Butler","Charles Woodson","Al Harris","Darren Sharper"], answer:"LeRoy Butler", explanation:"LeRoy Butler jumped into the Lambeau Field stands after a 1993 touchdown, creating the celebration.", sourceId:"packers-lambeau-leap" }),
  q({ id:"nfl-r1-terrible-towel-creator", league:"nfl", round:"round1", category:"Fan Culture", prompt:"Which Pittsburgh broadcaster created the Terrible Towel?", choices:["Myron Cope","Bill Hillgrove","Jack Fleming","Bob Prince"], answer:"Myron Cope", explanation:"Myron Cope introduced the Terrible Towel in 1975 as a rallying symbol for Steelers fans.", sourceId:"steelers-terrible-towel" }),

  // Round 2 — famous oddities, broadcasts, playoff moments
  q({ id:"nfl-r2-philly-special-snap", league:"nfl", round:"round2", category:"Super Bowl Moments", prompt:"Which Eagles running back took the direct snap that started the 'Philly Special'?", choices:["Corey Clement","Jay Ajayi","LeGarrette Blount","Darren Sproles"], answer:"Corey Clement", explanation:"Corey Clement took the direct snap, pitched to Trey Burton, and Burton threw the touchdown pass to Nick Foles.", sourceId:"nfl100-philly-special", sourceUrl:NFL_PLAYS }),
  q({ id:"nfl-r2-music-city-lateral", league:"nfl", round:"round2", category:"Iconic Plays", prompt:"Who threw the lateral that sprung Kevin Dyson on the Music City Miracle?", choices:["Frank Wycheck","Steve McNair","Derrick Mason","Eddie George"], answer:"Frank Wycheck", explanation:"Tight end Frank Wycheck threw the cross-field lateral that reached Kevin Dyson on Tennessee's winning return.", sourceId:"music-city-miracle" }),
  q({ id:"nfl-r2-helmet-catch-qb", league:"nfl", round:"round2", category:"Super Bowl Moments", prompt:"Which quarterback escaped pressure and threw the pass that became David Tyree's Helmet Catch?", choices:["Eli Manning","Tom Brady","Kurt Warner","Ben Roethlisberger"], answer:"Eli Manning", explanation:"Eli Manning escaped a near sack and found David Tyree on the defining play of Super Bowl XLII.", sourceId:"helmet-catch", sourceUrl:NFL100 }),
  q({ id:"nfl-r2-heidi-game", league:"nfl", round:"round2", category:"Broadcast Oddities", prompt:"The infamous 1968 'Heidi Game' involved the Jets and which team?", choices:["Oakland Raiders","Kansas City Chiefs","Miami Dolphins","Baltimore Colts"], answer:"Oakland Raiders", explanation:"NBC cut away from Jets-Raiders for the movie Heidi before Oakland scored twice late to win.", sourceId:"heidi-game" }),
  q({ id:"nfl-r2-fog-bowl", league:"nfl", round:"round2", category:"Weather Games", prompt:"The 1988 playoff game known as the 'Fog Bowl' matched the Bears against which team?", choices:["Philadelphia Eagles","New York Giants","Washington","Minnesota Vikings"], answer:"Philadelphia Eagles", explanation:"Dense fog swallowed Soldier Field during Chicago's playoff win over Philadelphia.", sourceId:"fog-bowl" }),
  q({ id:"nfl-r2-freezer-bowl", league:"nfl", round:"round2", category:"Weather Games", prompt:"The 1981 AFC Championship known as the 'Freezer Bowl' featured Cincinnati against which team?", choices:["San Diego Chargers","Pittsburgh Steelers","Buffalo Bills","Cleveland Browns"], answer:"San Diego Chargers", explanation:"The Bengals beat the Chargers in brutal cold and wind at Riverfront Stadium.", sourceId:"freezer-bowl" }),
  q({ id:"nfl-r2-snowplow-game", league:"nfl", round:"round2", category:"Weather Games", prompt:"In the 1982 'Snowplow Game,' which team used a stadium worker to clear a spot for the winning field goal?", choices:["New England Patriots","Miami Dolphins","Buffalo Bills","New York Jets"], answer:"New England Patriots", explanation:"A snowplow cleared a patch for Patriots kicker John Smith before the only score of a 3–0 win over Miami.", sourceId:"snowplow-game" }),
  q({ id:"nfl-r2-fail-mary", league:"nfl", round:"round2", category:"Officiating Oddities", prompt:"The controversial 2012 play nicknamed the 'Fail Mary' gave Seattle a win over which team?", choices:["Green Bay Packers","San Francisco 49ers","Dallas Cowboys","New England Patriots"], answer:"Green Bay Packers", explanation:"Replacement officials awarded Seattle a last-play touchdown against Green Bay, fueling the 'Fail Mary' nickname.", sourceId:"fail-mary" }),
  q({ id:"nfl-r2-holy-roller-opponent", league:"nfl", round:"round2", category:"Odd Finishes", prompt:"Oakland's controversial 'Holy Roller' finish in 1978 came against which team?", choices:["San Diego Chargers","Denver Broncos","Kansas City Chiefs","Seattle Seahawks"], answer:"San Diego Chargers", explanation:"The Raiders' fumble-filled final play beat San Diego and helped inspire a rule change.", sourceId:"holy-roller" }),
  q({ id:"nfl-r2-river-city-relay-miss", league:"nfl", round:"round2", category:"Odd Finishes", prompt:"After the Saints scored on the River City Relay, what happened on the extra point?", choices:["It was missed","It was blocked and returned","There was a bad snap","A penalty erased it"], answer:"It was missed", explanation:"John Carney missed the extra point after the miracle touchdown, leaving New Orleans one point short.", sourceId:"river-city-relay" }),
  q({ id:"nfl-r2-double-doink-opponent", league:"nfl", round:"round2", category:"Playoff Moments", prompt:"The Bears' 'Double Doink' playoff miss came against which opponent?", choices:["Philadelphia Eagles","Green Bay Packers","Minnesota Vikings","Los Angeles Rams"], answer:"Philadelphia Eagles", explanation:"Chicago's potential winning kick hit both an upright and the crossbar in a wild-card loss to Philadelphia.", sourceId:"double-doink" }),
  q({ id:"nfl-r2-beast-quake-opponent", league:"nfl", round:"round2", category:"Playoff Moments", prompt:"Marshawn Lynch's Beast Quake run came against which team?", choices:["New Orleans Saints","San Francisco 49ers","Green Bay Packers","Carolina Panthers"], answer:"New Orleans Saints", explanation:"Lynch broke tackle after tackle against New Orleans in Seattle's 2010 wild-card upset.", sourceId:"beast-quake" }),
  q({ id:"nfl-r2-minneapolis-miracle-opponent", league:"nfl", round:"round2", category:"Playoff Moments", prompt:"The Minneapolis Miracle knocked which team out of the playoffs?", choices:["New Orleans Saints","Philadelphia Eagles","Green Bay Packers","Atlanta Falcons"], answer:"New Orleans Saints", explanation:"Stefon Diggs' last-play touchdown sent Minnesota past New Orleans in the 2017 divisional round.", sourceId:"minneapolis-miracle" }),
  q({ id:"nfl-r2-immaculate-number-one", league:"nfl", round:"round2", category:"Iconic Plays", prompt:"Which play finished No. 1 in the NFL's 100 Greatest Plays ranking?", choices:["Immaculate Reception","The Catch","Helmet Catch","Music City Miracle"], answer:"Immaculate Reception", explanation:"NFL Network ranked Franco Harris' Immaculate Reception as the greatest play in league history.", sourceId:"nfl100-plays", sourceUrl:NFL_PLAYS }),
  q({ id:"nfl-r2-the-catch-opponent", league:"nfl", round:"round2", category:"Iconic Plays", prompt:"Dwight Clark's 'The Catch' sent San Francisco to its first Super Bowl by beating which team?", choices:["Dallas Cowboys","New York Giants","Washington","Chicago Bears"], answer:"Dallas Cowboys", explanation:"The 49ers beat Dallas 28–27 in the 1981 NFC Championship after Clark's famous touchdown.", sourceId:"nfl100-the-catch", sourceUrl:NFL_PLAYS }),

  // Round 3 — deeper culture, rules and history
  q({ id:"nfl-r3-first-black-modern-hc", league:"nfl", round:"round3", category:"League History", prompt:"Who became the NFL's first Black head coach of the modern era when the Raiders promoted him in 1989?", choices:["Art Shell","Tony Dungy","Dennis Green","Ray Rhodes"], answer:"Art Shell", explanation:"The Raiders promoted Hall of Famer Art Shell in 1989, making him the first Black head coach in the NFL's modern era.", sourceId:"nfl-art-shell-history" }),
  q({ id:"nfl-r3-first-female-official", league:"nfl", round:"round3", category:"League Firsts", prompt:"Who became the NFL's first full-time female game official in 2015?", choices:["Sarah Thomas","Maia Chaka","Shannon Eastin","Robin DeLorenzo"], answer:"Sarah Thomas", explanation:"Sarah Thomas joined the NFL officiating staff in 2015 as the league's first full-time female official.", sourceId:"nfl-sarah-thomas" }),
  q({ id:"nfl-r3-first-female-super-bowl-official", league:"nfl", round:"round3", category:"Super Bowl Firsts", prompt:"Who became the first woman to officiate a Super Bowl?", choices:["Sarah Thomas","Maia Chaka","Shannon Eastin","Terri Valenti"], answer:"Sarah Thomas", explanation:"Sarah Thomas served as a down judge in Super Bowl LV.", sourceId:"nfl-sarah-thomas" }),
  q({ id:"nfl-r3-walter-payton-award", league:"nfl", round:"round3", category:"NFL Honors", prompt:"The NFL's Man of the Year Award is named for which Bears legend?", choices:["Walter Payton","Gale Sayers","Dick Butkus","George Halas"], answer:"Walter Payton", explanation:"The league renamed its Man of the Year Award for Walter Payton in 1999.", sourceId:"walter-payton-moy" }),
  q({ id:"nfl-r3-lombardi-maker", league:"nfl", round:"round3", category:"Super Bowl Lore", prompt:"Which famous jeweler manufactures the Vince Lombardi Trophy?", choices:["Tiffany & Co.","Cartier","Bulgari","Harry Winston"], answer:"Tiffany & Co.", explanation:"Tiffany & Co. has handcrafted the NFL's championship trophy for decades.", sourceId:"lombardi-trophy", sourceUrl:LOMBARDI }),
  q({ id:"nfl-r3-lombardi-renamed-year", league:"nfl", round:"round3", category:"Super Bowl Lore", prompt:"In what year did the championship trophy officially become the Vince Lombardi Trophy?", choices:["1970","1967","1972","1975"], answer:"1970", explanation:"The trophy was officially renamed for Vince Lombardi in September 1970.", sourceId:"lombardi-trophy", sourceUrl:LOMBARDI }),
  q({ id:"nfl-r3-first-mnf-announcer-cosell", league:"nfl", round:"round3", category:"Broadcast History", prompt:"Which outspoken broadcaster was part of the original Monday Night Football booth?", choices:["Howard Cosell","John Madden","Pat Summerall","Al Michaels"], answer:"Howard Cosell", explanation:"Howard Cosell was one of the defining voices of ABC's original Monday Night Football team.", sourceId:"mnf-history" }),
  q({ id:"nfl-r3-first-mnf-playbyplay", league:"nfl", round:"round3", category:"Broadcast History", prompt:"Who handled play-by-play in the original 1970 Monday Night Football booth?", choices:["Keith Jackson","Frank Gifford","Al Michaels","Curt Gowdy"], answer:"Keith Jackson", explanation:"Keith Jackson was the original play-by-play announcer alongside Howard Cosell and Don Meredith.", sourceId:"mnf-history" }),
  q({ id:"nfl-r3-nfl-films-founder", league:"nfl", round:"round3", category:"Media History", prompt:"Which filmmaker founded the company that became NFL Films?", choices:["Ed Sabol","Steve Sabol","Pete Rozelle","John Facenda"], answer:"Ed Sabol", explanation:"Ed Sabol founded Blair Motion Pictures, which evolved into NFL Films.", sourceId:"nfl-films-history" }),
  q({ id:"nfl-r3-nfl-films-voice", league:"nfl", round:"round3", category:"Media History", prompt:"Which narrator became known as 'The Voice of God' for his work with NFL Films?", choices:["John Facenda","Pat Summerall","Harry Kalas","Howard Cosell"], answer:"John Facenda", explanation:"John Facenda's dramatic narration became one of the signature sounds of NFL Films.", sourceId:"nfl-films-history" }),
  q({ id:"nfl-r3-gatorade-dump-team", league:"nfl", round:"round3", category:"Celebrations", prompt:"The tradition of dumping Gatorade on a winning coach is most closely traced to which 1980s team?", choices:["New York Giants","Chicago Bears","San Francisco 49ers","Washington"], answer:"New York Giants", explanation:"Giants players popularized the celebratory Gatorade dump on coach Bill Parcells during their 1980s run.", sourceId:"gatorade-dump-history" }),
  q({ id:"nfl-r3-dirty-bird", league:"nfl", round:"round3", category:"Celebrations", prompt:"Which Falcons running back popularized the 'Dirty Bird' touchdown dance during the 1998 season?", choices:["Jamal Anderson","Warrick Dunn","T.J. Duckett","Gerald Riggs"], answer:"Jamal Anderson", explanation:"Jamal Anderson's Dirty Bird dance became a symbol of Atlanta's 1998 Super Bowl run.", sourceId:"falcons-dirty-bird" }),
  q({ id:"nfl-r3-ickey-shuffle", league:"nfl", round:"round3", category:"Celebrations", prompt:"The 'Ickey Shuffle' touchdown dance belonged to which Bengals running back?", choices:["Ickey Woods","James Brooks","Corey Dillon","Rudi Johnson"], answer:"Ickey Woods", explanation:"Rookie Ickey Woods' end-zone dance became a defining image of Cincinnati's 1988 Super Bowl season.", sourceId:"bengals-ickey-shuffle" }),
  q({ id:"nfl-r3-black-hole", league:"nfl", round:"round3", category:"Fan Culture", prompt:"The fan section known as the 'Black Hole' is associated with which franchise?", choices:["Raiders","Ravens","Steelers","Falcons"], answer:"Raiders", explanation:"Raiders fans made the Black Hole one of the league's most recognizable end-zone sections.", sourceId:"raiders-black-hole" }),
  q({ id:"nfl-r3-first-super-bowl-home-team", league:"nfl", round:"round3", category:"Super Bowl Firsts", prompt:"Which team became the first to play a Super Bowl in its home stadium?", choices:["Tampa Bay Buccaneers","Los Angeles Rams","Miami Dolphins","New Orleans Saints"], answer:"Tampa Bay Buccaneers", explanation:"Tampa Bay played and won Super Bowl LV at Raymond James Stadium.", sourceId:"super-bowl-home-stadium" }),

  // Last Call
  q({ id:"nfl-final-immaculate-intended-target", league:"nfl", round:"last-call", category:"Iconic Plays", prompt:"Terry Bradshaw's pass on the Immaculate Reception was intended for which Steelers player?", choices:["John Fuqua","Franco Harris","Ron Shanklin","Larry Brown"], answer:"John Fuqua", explanation:"Bradshaw's fourth-down pass was directed toward John Fuqua before the collision and deflection reached Franco Harris.", sourceId:"nfl100-immaculate", sourceUrl:NFL_PLAYS }),
  q({ id:"nfl-final-first-super-bowl-td", league:"nfl", round:"last-call", category:"Super Bowl History", prompt:"Who scored the first touchdown in Super Bowl history?", choices:["Max McGee","Bart Starr","Elijah Pitts","Len Dawson"], answer:"Max McGee", explanation:"Packers receiver Max McGee caught a 37-yard touchdown pass from Bart Starr for the first Super Bowl touchdown.", sourceId:"super-bowl-i-history" }),
  q({ id:"nfl-final-first-sb-kick-return-td", league:"nfl", round:"last-call", category:"Super Bowl History", prompt:"Who recorded the first kickoff-return touchdown in Super Bowl history?", choices:["Fulton Walker","Desmond Howard","Devin Hester","Timmy Smith"], answer:"Fulton Walker", explanation:"Miami's Fulton Walker returned a kickoff for a touchdown in Super Bowl XVII.", sourceId:"super-bowl-return-history" }),
  q({ id:"nfl-final-first-home-sb-winner", league:"nfl", round:"last-call", category:"Super Bowl Firsts", prompt:"Which team became the first to win a Super Bowl in its own home stadium?", choices:["Tampa Bay Buccaneers","Los Angeles Rams","Miami Dolphins","San Francisco 49ers"], answer:"Tampa Bay Buccaneers", explanation:"Tampa Bay beat Kansas City in Super Bowl LV at Raymond James Stadium.", sourceId:"super-bowl-home-stadium" }),
  q({ id:"nfl-final-lombardi-old-name", league:"nfl", round:"last-call", category:"Super Bowl Lore", prompt:"Before it was renamed for Vince Lombardi, the Super Bowl trophy was officially called the...", choices:["World Professional Football Championship Trophy","AFL-NFL Memorial Trophy","Commissioner's Championship Trophy","Professional Football World Cup"], answer:"World Professional Football Championship Trophy", explanation:"That was the formal name used before the trophy was renamed for Lombardi in 1970.", sourceId:"lombardi-trophy", sourceUrl:LOMBARDI }),
];
