import { barTriviaQuestion, type BarTriviaQuestion } from "../games/barTriviaEngine";

export const BAR_TRIVIA_CURRENT_EVENT_QUESTIONS: readonly BarTriviaQuestion[] = [
  // Oct. 6 editorial additions
  barTriviaQuestion({
    id: "nfl-current-2026-w4-keenum-bears-eagles",
    league: "nfl",
    round: "round1",
    difficulty: "easy",
    category: "Veteran Comebacks",
    prompt: "Which 38-year-old quarterback returned for his first NFL start since 2023 and led Chicago to a 27–7 upset of Philadelphia?",
    choices: ["Case Keenum", "Joe Flacco", "Andy Dalton", "Ryan Tannehill"],
    answer: "Case Keenum",
    explanation: "Case Keenum started for injured Caleb Williams and led Chicago past Philadelphia in his first NFL start since December 2023.",
    contentType: "current-event",
    activeFrom: "2026-09-29T00:00:00-05:00",
    expiresAt: "2026-10-18T23:59:59-05:00",
    sourceId: "nfl-2026-w4-keenum-bears-eagles",
    sourceUrl: "https://www.nfl.com/news/eagles-bears-on-monday-night-football-what-we-learned-from-chicago-s-27-7-win-over-philadelphia",
    verifiedAt: "2026-10-06",
  }),
  barTriviaQuestion({
    id: "cfb-current-2026-w5-northwestern-ryan-field",
    league: "cfb",
    round: "round1",
    difficulty: "easy",
    category: "Stadium Openers",
    prompt: "Which Big Ten team opened its new $875 million Ryan Field by routing Penn State 34–13?",
    choices: ["Northwestern", "Illinois", "Wisconsin", "Minnesota"],
    answer: "Northwestern",
    explanation: "Northwestern opened the rebuilt Ryan Field with a memorable 34–13 win over Penn State.",
    contentType: "current-event",
    activeFrom: "2026-10-03T00:00:00-05:00",
    expiresAt: "2026-10-24T23:59:59-05:00",
    sourceId: "ncaa-2026-w5-northwestern-ryan-field",
    sourceUrl: "https://www.ncaa.com/live-updates/football/fbs/college-football-week-5-live-updates-schedule-scores-rankings",
    verifiedAt: "2026-10-06",
  }),
  barTriviaQuestion({
    id: "ufc-current-2026-10-03-silva-wang-title",
    league: "ufc",
    round: "round1",
    difficulty: "easy",
    category: "Title Changes",
    prompt: "Who won the vacant UFC women's flyweight title by defeating Wang Cong at UFC 332?",
    choices: ["Natalia Silva", "Alexa Grasso", "Manon Fiorot", "Erin Blanchfield"],
    answer: "Natalia Silva",
    explanation: "Natalia Silva defeated Wang Cong by unanimous decision to become the UFC women's flyweight champion.",
    contentType: "current-event",
    activeFrom: "2026-10-04T00:00:00-05:00",
    expiresAt: "2026-11-07T23:59:59-05:00",
    sourceId: "ufc-332-silva-wang-title",
    sourceUrl: "https://www.ufc.com/event/ufc-332",
    verifiedAt: "2026-10-06",
  }),

  // NFL — 10 active launch stories
  barTriviaQuestion({
    id: "nfl-current-2026-w3-bills-mistakes-win",
    league: "nfl",
    round: "round2",
    difficulty: "medium",
    category: "Wild Wins",
    prompt: "Which team pulled off a chaotic Week 3 win over the Chargers despite five turnovers and double-digit penalties?",
    choices: ["Buffalo Bills", "Kansas City Chiefs", "Detroit Lions", "Pittsburgh Steelers"],
    answer: "Buffalo Bills",
    explanation: "Buffalo beat the Chargers 24–16 despite becoming just the 10th Bills team to commit at least five turnovers and 10 penalties in the same game.",
    contentType: "current-event",
    activeFrom: "2026-09-27T00:00:00-05:00",
    expiresAt: "2026-10-11T23:59:59-05:00",
    sourceId: "nfl-2026-week3-bills-chargers",
    sourceUrl: "https://www.nfl.com/news/how-rare-was-bills-win-over-chargers-think-replacement-players-and-a-barefoot-kicker",
    verifiedAt: "2026-09-28",
  }),
  barTriviaQuestion({
    id: "nfl-current-2026-w3-commanders-end-seahawks-streak",
    league: "nfl",
    round: "round1",
    difficulty: "easy",
    category: "Streak Stoppers",
    prompt: "Which team ended Seattle's franchise-record 12-game winning streak with a 33–31 Week 3 victory?",
    choices: ["Washington Commanders", "Pittsburgh Steelers", "Detroit Lions", "San Francisco 49ers"],
    answer: "Washington Commanders",
    explanation: "Washington held off a late Seattle comeback to win 33–31 and hand the defending champions their first loss since Week 11 of 2025.",
    contentType: "current-event",
    activeFrom: "2026-09-27T00:00:00-05:00",
    expiresAt: "2026-10-11T23:59:59-05:00",
    sourceId: "seahawks-2026-week3-commanders-streak",
    sourceUrl: "https://www.seahawks.com/news/seahawks-disappointed-but-not-down-after-first-loss-in-10-months",
    verifiedAt: "2026-09-28",
  }),
  barTriviaQuestion({
    id: "nfl-current-2026-w2-highmark-opener",
    league: "nfl",
    round: "round1",
    difficulty: "easy",
    category: "Stadium Openers",
    prompt: "Which team did Buffalo beat 41–31 in the first regular-season game at the new Highmark Stadium?",
    choices: ["Detroit Lions", "Miami Dolphins", "Kansas City Chiefs", "Cincinnati Bengals"],
    answer: "Detroit Lions",
    explanation: "Josh Allen accounted for five touchdowns as Buffalo opened its new stadium with a 41–31 Thursday night win over Detroit.",
    contentType: "current-event",
    activeFrom: "2026-09-17T00:00:00-05:00",
    expiresAt: "2026-10-05T23:59:59-05:00",
    sourceId: "nfl-2026-week2-highmark-opener",
    sourceUrl: "https://www.nfl.com/news/lions-bills-on-thursday-night-football-what-we-learned-from-buffalo-s-41-31-win",
    verifiedAt: "2026-09-28",
  }),
  barTriviaQuestion({
    id: "nfl-current-2026-w2-panthers-bounceback",
    league: "nfl",
    round: "round1",
    difficulty: "easy",
    category: "Bounce-Backs",
    prompt: "Which team answered a 59-point Week 1 defensive disaster by beating Atlanta 34–3 the next week?",
    choices: ["Carolina Panthers", "Cleveland Browns", "New Orleans Saints", "New England Patriots"],
    answer: "Carolina Panthers",
    explanation: "Carolina went from allowing 59 points to Chicago in Week 1 to smothering Atlanta 34–3 in Week 2.",
    contentType: "current-event",
    activeFrom: "2026-09-20T00:00:00-05:00",
    expiresAt: "2026-10-05T23:59:59-05:00",
    sourceId: "nfl-2026-week2-panthers-falcons",
    sourceUrl: "https://www.nfl.com/news/2026-nfl-season-week-2-what-we-learned-from-sunday-s-games",
    verifiedAt: "2026-09-28",
  }),
  barTriviaQuestion({
    id: "nfl-current-2026-w2-shough-ravens",
    league: "nfl",
    round: "round2",
    difficulty: "medium",
    category: "Clutch Moments",
    prompt: "Which Saints quarterback scored the late fourth-down rushing touchdown in New Orleans' 24–17 upset of Baltimore?",
    choices: ["Tyler Shough", "Spencer Rattler", "Derek Carr", "Jake Haener"],
    answer: "Tyler Shough",
    explanation: "Tyler Shough powered across the goal line on fourth down as the Saints completed a second-half comeback against the Ravens.",
    contentType: "current-event",
    activeFrom: "2026-09-20T00:00:00-05:00",
    expiresAt: "2026-10-05T23:59:59-05:00",
    sourceId: "nfl-2026-week2-saints-ravens",
    sourceUrl: "https://www.nfl.com/news/2026-nfl-season-week-2-what-we-learned-from-sunday-s-games",
    verifiedAt: "2026-09-28",
  }),
  barTriviaQuestion({
    id: "nfl-current-2026-w2-49ers-five-drives",
    league: "nfl",
    round: "round2",
    difficulty: "medium",
    category: "Offensive Runs",
    prompt: "Which team opened its Week 2 game against Miami by scoring touchdowns on five consecutive drives?",
    choices: ["San Francisco 49ers", "Buffalo Bills", "Philadelphia Eagles", "Seattle Seahawks"],
    answer: "San Francisco 49ers",
    explanation: "San Francisco scored touchdowns on five straight possessions while building a 35–6 lead through three quarters against Miami.",
    contentType: "current-event",
    activeFrom: "2026-09-20T00:00:00-05:00",
    expiresAt: "2026-10-05T23:59:59-05:00",
    sourceId: "nfl-2026-week2-49ers-dolphins",
    sourceUrl: "https://www.nfl.com/news/2026-nfl-season-week-2-what-we-learned-from-sunday-s-games",
    verifiedAt: "2026-09-28",
  }),
  barTriviaQuestion({
    id: "nfl-current-2026-w1-bears-panthers-record",
    league: "nfl",
    round: "round1",
    difficulty: "easy",
    category: "Record Games",
    prompt: "Which Week 1 matchup became the highest-scoring season opener in NFL history with 96 combined points?",
    choices: ["Bears vs. Panthers", "Bills vs. Texans", "Lions vs. Saints", "Bengals vs. Buccaneers"],
    answer: "Bears vs. Panthers",
    explanation: "Chicago's 59–37 win over Carolina produced 96 combined points, the most ever in an NFL Week 1 game.",
    contentType: "current-event",
    activeFrom: "2026-09-13T00:00:00-05:00",
    expiresAt: "2026-10-04T23:59:59-05:00",
    sourceId: "nfl-2026-week1-bears-panthers-record",
    sourceUrl: "https://www.nfl.com/news/2026-nfl-season-week-1-what-we-learned-from-sunday-s-games",
    verifiedAt: "2026-09-28",
  }),
  barTriviaQuestion({
    id: "nfl-current-2026-w1-allen-80-rushing-td",
    league: "nfl",
    round: "round2",
    difficulty: "medium",
    category: "Milestones",
    prompt: "Which quarterback became the first in NFL history to reach 80 career rushing touchdowns?",
    choices: ["Josh Allen", "Lamar Jackson", "Jalen Hurts", "Cam Newton"],
    answer: "Josh Allen",
    explanation: "Josh Allen reached 80 career rushing touchdowns in Buffalo's Week 1 win over Houston, becoming the first quarterback to hit that mark.",
    contentType: "current-event",
    activeFrom: "2026-09-13T00:00:00-05:00",
    expiresAt: "2026-10-04T23:59:59-05:00",
    sourceId: "nfl-2026-week1-allen-80-rush-td",
    sourceUrl: "https://www.nfl.com/news/2026-nfl-season-week-1-what-we-learned-from-sunday-s-games",
    verifiedAt: "2026-09-28",
  }),
  barTriviaQuestion({
    id: "nfl-current-2026-w1-harbaugh-giants-debut",
    league: "nfl",
    round: "round2",
    difficulty: "medium",
    category: "Coaching Debuts",
    prompt: "Which longtime Ravens coach opened his Giants tenure with a 28–20 win over Dallas?",
    choices: ["John Harbaugh", "Mike Tomlin", "Sean Payton", "Ron Rivera"],
    answer: "John Harbaugh",
    explanation: "John Harbaugh's first regular-season game as Giants head coach ended with a rivalry win over the Cowboys.",
    contentType: "current-event",
    activeFrom: "2026-09-13T00:00:00-05:00",
    expiresAt: "2026-10-04T23:59:59-05:00",
    sourceId: "nfl-2026-week1-harbaugh-giants",
    sourceUrl: "https://www.nfl.com/news/2026-nfl-season-week-1-what-we-learned-from-sunday-s-games",
    verifiedAt: "2026-09-28",
  }),
  barTriviaQuestion({
    id: "nfl-current-2026-w1-obj-giants-return",
    league: "nfl",
    round: "round1",
    difficulty: "easy",
    category: "Comebacks",
    prompt: "Which star receiver played an official game for the Giants for the first time since 2018 in their Week 1 win over Dallas?",
    choices: ["Odell Beckham Jr.", "Sterling Shepard", "Golden Tate", "Kadarius Toney"],
    answer: "Odell Beckham Jr.",
    explanation: "Odell Beckham Jr. returned to the Giants in 2026 and appeared in his first official game for New York since December 2018.",
    contentType: "current-event",
    activeFrom: "2026-09-13T00:00:00-05:00",
    expiresAt: "2026-10-04T23:59:59-05:00",
    sourceId: "nfl-2026-week1-obj-giants-return",
    sourceUrl: "https://www.nfl.com/news/2026-nfl-season-week-1-what-we-learned-from-sunday-s-games",
    verifiedAt: "2026-09-28",
  }),

  // CFB — 10 active launch stories
  barTriviaQuestion({
    id: "cfb-current-2026-w4-iowa-michigan-walkoff",
    league: "cfb",
    round: "round1",
    difficulty: "easy",
    category: "Walk-Offs",
    prompt: "Which team beat Michigan 20–19 on a walk-off touchdown at the Big House for its first win there since 2010?",
    choices: ["Iowa", "Wisconsin", "Michigan State", "USC"],
    answer: "Iowa",
    explanation: "Iowa quarterback Hank Brown found Reece Vander Zee for the game-winning touchdown as time expired in Ann Arbor.",
    contentType: "current-event",
    activeFrom: "2026-09-26T00:00:00-05:00",
    expiresAt: "2026-10-17T23:59:59-05:00",
    sourceId: "ncaa-2026-week4-iowa-michigan",
    sourceUrl: "https://www.ncaa.com/live-updates/football/fbs/college-football-week-4-recaps-highlights-rankings-and-scores",
    verifiedAt: "2026-09-28",
  }),
  barTriviaQuestion({
    id: "cfb-current-2026-w4-wake-louisville-upset",
    league: "cfb",
    round: "round1",
    difficulty: "easy",
    category: "Road Upsets",
    prompt: "Which unranked ACC team knocked off No. 16 Louisville 30–27 on the road in Week 4?",
    choices: ["Wake Forest", "Virginia Tech", "NC State", "Boston College"],
    answer: "Wake Forest",
    explanation: "Wake Forest held on for a 30–27 road win when Louisville missed a late field goal.",
    contentType: "current-event",
    activeFrom: "2026-09-26T00:00:00-05:00",
    expiresAt: "2026-10-17T23:59:59-05:00",
    sourceId: "ncaa-2026-week4-wake-louisville",
    sourceUrl: "https://www.ncaa.com/live-updates/football/fbs/college-football-week-4-recaps-highlights-rankings-and-scores",
    verifiedAt: "2026-09-28",
  }),
  barTriviaQuestion({
    id: "cfb-current-2026-w4-jeremiah-smith-3000",
    league: "cfb",
    round: "round1",
    difficulty: "easy",
    category: "Milestones",
    prompt: "Which Ohio State receiver became the first Buckeye ever to reach 3,000 career receiving yards?",
    choices: ["Jeremiah Smith", "Marvin Harrison Jr.", "Jaxon Smith-Njigba", "Chris Olave"],
    answer: "Jeremiah Smith",
    explanation: "Jeremiah Smith crossed 3,000 career receiving yards during a four-touchdown performance against Illinois.",
    contentType: "current-event",
    activeFrom: "2026-09-26T00:00:00-05:00",
    expiresAt: "2026-10-17T23:59:59-05:00",
    sourceId: "ncaa-2026-week4-jeremiah-smith-3000",
    sourceUrl: "https://www.ncaa.com/live-updates/football/fbs/college-football-week-4-recaps-highlights-rankings-and-scores",
    verifiedAt: "2026-09-28",
  }),
  barTriviaQuestion({
    id: "cfb-current-2026-w4-romaine-back-to-back-picks",
    league: "cfb",
    round: "round2",
    difficulty: "medium",
    category: "Weird Moments",
    prompt: "Which Texas Tech defender returned interceptions for touchdowns on back-to-back plays against Sam Houston?",
    choices: ["Austin Romaine", "Jacob Rodriguez", "Ben Roberts", "Maurice Westmoreland"],
    answer: "Austin Romaine",
    explanation: "Austin Romaine became the first player since 2013 to record pick-sixes on consecutive plays.",
    contentType: "current-event",
    activeFrom: "2026-09-26T00:00:00-05:00",
    expiresAt: "2026-10-17T23:59:59-05:00",
    sourceId: "ncaa-2026-week4-romaine-pick-sixes",
    sourceUrl: "https://www.ncaa.com/live-updates/football/fbs/college-football-week-4-live-updates-schedule-scores-rankings",
    verifiedAt: "2026-09-28",
  }),
  barTriviaQuestion({
    id: "cfb-current-2026-w4-colin-simmons-five-sacks",
    league: "cfb",
    round: "round2",
    difficulty: "medium",
    category: "Defensive Takeovers",
    prompt: "Which Texas edge rusher tied the program's single-game record with five sacks at Tennessee?",
    choices: ["Colin Simmons", "Anthony Hill Jr.", "Trey Moore", "Ethan Burke"],
    answer: "Colin Simmons",
    explanation: "Colin Simmons recorded five sacks as Texas survived Tennessee 20–17 in Knoxville.",
    contentType: "current-event",
    activeFrom: "2026-09-26T00:00:00-05:00",
    expiresAt: "2026-10-17T23:59:59-05:00",
    sourceId: "ncaa-2026-week4-colin-simmons",
    sourceUrl: "https://www.ncaa.com/live-updates/football/fbs/college-football-week-4-recaps-highlights-rankings-and-scores",
    verifiedAt: "2026-09-28",
  }),
  barTriviaQuestion({
    id: "cfb-current-2026-w3-kentucky-texas-am",
    league: "cfb",
    round: "round1",
    difficulty: "easy",
    category: "Top-10 Upsets",
    prompt: "Which unranked team stunned No. 9 Texas A&M 31–21 at Kyle Field in Week 3?",
    choices: ["Kentucky", "Arkansas", "Mississippi State", "Auburn"],
    answer: "Kentucky",
    explanation: "Kentucky handed Texas A&M its first home loss to an unranked team since 2022.",
    contentType: "current-event",
    activeFrom: "2026-09-19T00:00:00-05:00",
    expiresAt: "2026-10-10T23:59:59-05:00",
    sourceId: "ncaa-2026-week3-kentucky-texas-am",
    sourceUrl: "https://www.ncaa.com/live-updates/football/fbs/college-football-week-3-recap-scores-highlights",
    verifiedAt: "2026-09-28",
  }),
  barTriviaQuestion({
    id: "cfb-current-2026-w3-wvu-hawkins-five-td",
    league: "cfb",
    round: "round2",
    difficulty: "medium",
    category: "Breakout Games",
    prompt: "Which West Virginia quarterback accounted for a career-high five touchdowns in the 38–27 upset of No. 25 Virginia?",
    choices: ["Michael Hawkins Jr.", "Nicco Marchiol", "Garrett Greene", "CJ Donaldson"],
    answer: "Michael Hawkins Jr.",
    explanation: "Michael Hawkins Jr. powered West Virginia's ranked upset with a career-high five total touchdowns.",
    contentType: "current-event",
    activeFrom: "2026-09-19T00:00:00-05:00",
    expiresAt: "2026-10-10T23:59:59-05:00",
    sourceId: "ncaa-2026-week3-wvu-virginia",
    sourceUrl: "https://www.ncaa.com/live-updates/football/fbs/college-football-week-3-live-updates-schedule-scores-highlights",
    verifiedAt: "2026-09-28",
  }),
  barTriviaQuestion({
    id: "cfb-current-2026-w2-oklahoma-state-oregon",
    league: "cfb",
    round: "round1",
    difficulty: "easy",
    category: "Historic Upsets",
    prompt: "Which team snapped a 12-game losing streak by stunning No. 6 Oregon 39–31?",
    choices: ["Oklahoma State", "Oregon State", "Kansas State", "Colorado"],
    answer: "Oklahoma State",
    explanation: "Oklahoma State became the first FBS team to end a double-digit losing streak by beating a top-10 opponent.",
    contentType: "current-event",
    activeFrom: "2026-09-12T00:00:00-05:00",
    expiresAt: "2026-10-03T23:59:59-05:00",
    sourceId: "ncaa-2026-week2-oklahoma-state-oregon",
    sourceUrl: "https://www.ncaa.com/news/football/article/2026-09-12/oklahoma-state-upsets-no-6-oregon-2-top-12-teams-fall-unranked-foes",
    verifiedAt: "2026-09-28",
  }),
  barTriviaQuestion({
    id: "cfb-current-2026-w2-michigan-oklahoma",
    league: "cfb",
    round: "round1",
    difficulty: "easy",
    category: "Ranked Upsets",
    prompt: "Which team knocked off No. 11 Oklahoma 17–10 in Week 2?",
    choices: ["Michigan", "Nebraska", "Wisconsin", "Iowa"],
    answer: "Michigan",
    explanation: "Michigan handed No. 11 Oklahoma a 17–10 loss in one of Week 2's two major unranked-over-ranked upsets.",
    contentType: "current-event",
    activeFrom: "2026-09-12T00:00:00-05:00",
    expiresAt: "2026-10-03T23:59:59-05:00",
    sourceId: "ncaa-2026-week2-michigan-oklahoma",
    sourceUrl: "https://www.ncaa.com/news/football/article/2026-09-12/oklahoma-state-upsets-no-6-oregon-2-top-12-teams-fall-unranked-foes",
    verifiedAt: "2026-09-28",
  }),
  barTriviaQuestion({
    id: "cfb-current-2026-w2-texas-ohio-state",
    league: "cfb",
    round: "round1",
    difficulty: "easy",
    category: "No. 1 Falls",
    prompt: "Which team beat No. 1 Ohio State 24–23 in the Week 2 showdown in Austin?",
    choices: ["Texas", "Georgia", "Notre Dame", "Alabama"],
    answer: "Texas",
    explanation: "Texas edged Ohio State 24–23, a result that propelled the Longhorns to the top of the rankings.",
    contentType: "current-event",
    activeFrom: "2026-09-12T00:00:00-05:00",
    expiresAt: "2026-10-03T23:59:59-05:00",
    sourceId: "ncaa-2026-week2-texas-ohio-state",
    sourceUrl: "https://www.ncaa.com/live-updates/football/fbs/college-football-week-2-recap-scores-highlights",
    verifiedAt: "2026-09-28",
  }),

  // UFC — 10 active launch stories
  barTriviaQuestion({
    id: "ufc-current-2026-09-26-rosas-barcelos",
    league: "ufc",
    round: "round1",
    difficulty: "easy",
    category: "Main Event Moments",
    prompt: "Whose first UFC main event ended with a fifth-round slam TKO of Raoni Barcelos?",
    choices: ["Raul Rosas Jr.", "Montel Jackson", "Brady Hiestand", "Luis Hernandez"],
    answer: "Raul Rosas Jr.",
    explanation: "Raul Rosas Jr. earned a fifth-round stoppage over Raoni Barcelos in the September 26 main event at Meta APEX.",
    contentType: "current-event",
    activeFrom: "2026-09-26T00:00:00-05:00",
    expiresAt: "2026-10-24T23:59:59-05:00",
    sourceId: "ufc-2026-09-26-rosas-barcelos",
    sourceUrl: "https://www.ufc.com/news/ufc-fight-night-rosas-jr-vs-barcelos-results",
    verifiedAt: "2026-09-28",
  }),
  barTriviaQuestion({
    id: "ufc-current-2026-09-26-akylbek-tuf-dq",
    league: "ufc",
    round: "round2",
    difficulty: "medium",
    category: "Strange Endings",
    prompt: "Which fighter became the first competitor from Kyrgyzstan to win The Ultimate Fighter after an illegal-knee disqualification?",
    choices: ["Ilimbek Akylbek", "Mahammadali Osmanli", "Rinya Nakamura", "Brady Hiestand"],
    answer: "Ilimbek Akylbek",
    explanation: "Ilimbek Akylbek won the TUF 34 bantamweight finale when Mahammadali Osmanli was disqualified for an illegal knee.",
    contentType: "current-event",
    activeFrom: "2026-09-26T00:00:00-05:00",
    expiresAt: "2026-10-24T23:59:59-05:00",
    sourceId: "ufc-2026-09-26-akylbek-osmanli",
    sourceUrl: "https://www.ufc.com/news/ufc-fight-night-rosas-jr-vs-barcelos-results",
    verifiedAt: "2026-09-28",
  }),
  barTriviaQuestion({
    id: "ufc-current-2026-09-26-tina-black-tuf",
    league: "ufc",
    round: "round1",
    difficulty: "easy",
    category: "TUF History",
    prompt: "Who became the first Brazilian woman to win The Ultimate Fighter with a second-round stoppage of Melissa Amaya?",
    choices: ["Tina Black", "Ailin Perez", "Yazmin Jauregui", "Norma Dumont"],
    answer: "Tina Black",
    explanation: "Tina Black won the TUF 34 strawweight tournament and became the first Brazilian woman to win the show.",
    contentType: "current-event",
    activeFrom: "2026-09-26T00:00:00-05:00",
    expiresAt: "2026-10-24T23:59:59-05:00",
    sourceId: "ufc-2026-09-26-tina-black",
    sourceUrl: "https://www.ufc.com/news/ufc-fight-night-rosas-jr-vs-barcelos-results",
    verifiedAt: "2026-09-28",
  }),
  barTriviaQuestion({
    id: "ufc-current-2026-09-19-joshua-van-pantoja",
    league: "ufc",
    round: "round1",
    difficulty: "easy",
    category: "Title Fights",
    prompt: "Which flyweight champion silenced doubts by beating Alexandre Pantoja in their UFC 331 rematch?",
    choices: ["Joshua Van", "Brandon Moreno", "Tatsuro Taira", "Kai Kara-France"],
    answer: "Joshua Van",
    explanation: "Joshua Van retained the flyweight title by unanimous decision over former champion Alexandre Pantoja in Los Angeles.",
    contentType: "current-event",
    activeFrom: "2026-09-19T00:00:00-05:00",
    expiresAt: "2026-10-17T23:59:59-05:00",
    sourceId: "ufc-331-van-pantoja-rematch",
    sourceUrl: "https://www.ufc.com/news/cryptocom-ufc-331-van-vs-pantoja-2-results",
    verifiedAt: "2026-09-28",
  }),
  barTriviaQuestion({
    id: "ufc-current-2026-09-19-sharaf-steveson",
    league: "ufc",
    round: "round1",
    difficulty: "easy",
    category: "Massive Upsets",
    prompt: "Who knocked out Olympic gold medalist Gable Steveson in just 12 seconds at UFC 331?",
    choices: ["Sean Sharaf", "Tai Tuivasa", "Robelis Despaigne", "Josh Hokit"],
    answer: "Sean Sharaf",
    explanation: "Sean Sharaf landed a left hook that stopped the previously unbeaten Gable Steveson in 12 seconds.",
    contentType: "current-event",
    activeFrom: "2026-09-19T00:00:00-05:00",
    expiresAt: "2026-10-17T23:59:59-05:00",
    sourceId: "ufc-331-sharaf-steveson",
    sourceUrl: "https://www.ufc.com/news/crypto-dotcom-ufc-331-coverage-performance-bonus",
    verifiedAt: "2026-09-28",
  }),
  barTriviaQuestion({
    id: "ufc-current-2026-09-19-chito-jourdain",
    league: "ufc",
    round: "round2",
    difficulty: "medium",
    category: "Comeback Wins",
    prompt: "Which former title challenger snapped a four-fight skid by stopping Charles Jourdain at UFC 331?",
    choices: ["Marlon Vera", "Cory Sandhagen", "Deiveson Figueiredo", "Dominick Cruz"],
    answer: "Marlon Vera",
    explanation: "Marlon 'Chito' Vera returned to the win column with a third-round TKO of Charles Jourdain.",
    contentType: "current-event",
    activeFrom: "2026-09-19T00:00:00-05:00",
    expiresAt: "2026-10-17T23:59:59-05:00",
    sourceId: "ufc-331-vera-jourdain",
    sourceUrl: "https://www.ufc.com/news/cryptocom-ufc-331-van-vs-pantoja-2-prelim-results",
    verifiedAt: "2026-09-28",
  }),
  barTriviaQuestion({
    id: "ufc-current-2026-09-19-pitbull-choi",
    league: "ufc",
    round: "round2",
    difficulty: "medium",
    category: "Veteran Statements",
    prompt: "Which former Bellator champion knocked out Dooho Choi on the UFC 331 main card?",
    choices: ["Patricio Pitbull", "Michael Chandler", "A.J. McKee", "Patchy Mix"],
    answer: "Patricio Pitbull",
    explanation: "Patricio Pitbull scored a first-round knockout of Dooho Choi during UFC 331 in Los Angeles.",
    contentType: "current-event",
    activeFrom: "2026-09-19T00:00:00-05:00",
    expiresAt: "2026-10-17T23:59:59-05:00",
    sourceId: "ufc-331-pitbull-choi",
    sourceUrl: "https://www.ufc.com/news/cryptocom-ufc-331-van-vs-pantoja-2-results",
    verifiedAt: "2026-09-28",
  }),
  barTriviaQuestion({
    id: "ufc-current-2026-09-19-casey-oneill-armbar",
    league: "ufc",
    round: "round2",
    difficulty: "medium",
    category: "Submission Moments",
    prompt: "Which flyweight earned a UFC 331 performance bonus by reversing trouble into a first-round armbar of Eduarda Moura?",
    choices: ["Casey O'Neill", "Erin Blanchfield", "Maycee Barber", "Tracy Cortez"],
    answer: "Casey O'Neill",
    explanation: "Casey O'Neill escaped an anaconda-choke threat, reversed position and finished Eduarda Moura with an armbar.",
    contentType: "current-event",
    activeFrom: "2026-09-19T00:00:00-05:00",
    expiresAt: "2026-10-17T23:59:59-05:00",
    sourceId: "ufc-331-casey-oneill-moura",
    sourceUrl: "https://www.ufc.com/news/crypto-dotcom-ufc-331-coverage-performance-bonus",
    verifiedAt: "2026-09-28",
  }),
  barTriviaQuestion({
    id: "ufc-current-2026-09-05-parnasse-hooker",
    league: "ufc",
    round: "round1",
    difficulty: "easy",
    category: "Debut Statements",
    prompt: "Which French star made his UFC debut by stopping Dan Hooker in the first round of the Paris main event?",
    choices: ["Salahdine Parnasse", "Benoit Saint Denis", "Fares Ziam", "Morgan Charriere"],
    answer: "Salahdine Parnasse",
    explanation: "Salahdine Parnasse announced his UFC arrival with a first-round TKO of veteran Dan Hooker in Paris.",
    contentType: "current-event",
    activeFrom: "2026-09-05T00:00:00-05:00",
    expiresAt: "2026-10-10T23:59:59-05:00",
    sourceId: "ufc-paris-2026-parnasse-hooker",
    sourceUrl: "https://www.ufc.com/news/ufc-paris-results-hooker-vs-parnasse",
    verifiedAt: "2026-09-28",
  }),
  barTriviaQuestion({
    id: "ufc-current-2026-08-29-song-umar",
    league: "ufc",
    round: "round1",
    difficulty: "easy",
    category: "Home-Country Upsets",
    prompt: "Which Chinese bantamweight knocked out Umar Nurmagomedov in the UFC Shanghai main event?",
    choices: ["Song Yadong", "Yan Xiaonan", "Kai Asakura", "Aoriqileng"],
    answer: "Song Yadong",
    explanation: "Song Yadong stopped Umar Nurmagomedov with a second-round right uppercut, handing him only the second loss of his career.",
    contentType: "current-event",
    activeFrom: "2026-08-29T00:00:00-05:00",
    expiresAt: "2026-10-03T23:59:59-05:00",
    sourceId: "ufc-shanghai-2026-song-umar",
    sourceUrl: "https://www.ufc.com/news/ufc-shanghai-results-nurmagomedov-vs-song",
    verifiedAt: "2026-09-28",
  }),
];
