import { barTriviaQuestion, type BarTriviaQuestion } from "../games/barTriviaEngine";

const UFC30 = "https://www.ufc.com/30";
const WOMEN = "https://www.ufc.com/news/women-in-the-ufc-30th-anniversary";
const HOF = "https://www.ufc.com/news/ufc-hall-fame-faq";
const FIRST_CANADA = "https://www.ufc.com/news/first-ufc-event-canada-ufc-83-serra-vs-st-pierre-2";
const FIRST_AUSTRALIA = "https://www.ufc.com/news/first-ufc-event-australia-ufc-110-nogueira-vs-velasquez";
const FIRST_UK = "https://www.ufc.com/news/first-ufc-event-uk-ufc-38-brawl-hall-hughes-newton-london";
const FIRST_BRAZIL = "https://www.ufc.com/news/first-ufc-event-brazil-ultimate-brazil-1998";
const FIRST_FRANCE = "https://www.ufc.com/news/last-time-paris-ufc-fight-night-gane-30th-anniversary";
const LANDMARKS = "https://www.ufc.com/news/countdown-ufc-200-landmark-moments";
const TUF_WINNERS = "https://www.ufc.com/news/the-winners-of-the-ultimate-fighter-diaz-ferguson-esparza-pena-usman-tuf";
const UFC_NUMBERS = "https://www.ufc.com/news/ufc-numbers-ufc-1-ufc-300-pereira-vs-hill";
const HOF_ZHANG = "https://www.ufc.com/news/ufc-248-fight-between-zhang-weili-and-joanna-jedrzejczyk-to-be-inducted-into-ufc-hall-fame";
const HOF_ADESANYA = "https://www.ufc.com/news/ufc-236-fight-between-israel-adesanya-and-kelvin-gastelum-be-inducted-ufc-hall-fame";
const HOF_LAWLER = "https://www.ufc.com/news/ufc-189-fight-between-robbie-lawler-and-rory-macdonald-be-inducted-ufc-hall-fame";
const HOF_SILVA = "https://www.ufc.com/news/ufc-117-fight-between-anderson-silva-and-chael-sonnen-be-inducted-ufc-hall-fame";
const HOF_SWANSON = "https://www.ufc.com/news/cub-swanson-vs-dooho-choi-be-inducted-2022-ufc-hall-fame";
const HOF_JONES = "https://www.ufc.com/news/jones-gustafsson-battle-inducted-into-ufc-hall-fame";
const HOF_HENDO = "https://www.ufc.com/news/hall-fame-fight-dan-henderson-vs-shogun-rua-1-ufc-read";
const HOF_HUGHES = "https://www.ufc.com/news/hall-fame-fight-matt-hughes-vs-frank-trigg-2-read";
const HOF_SANCHEZ = "https://www.ufc.com/news/sanchez-vs-guida-be-inducted-ufc-hall-fame";
const HOF_WILLIAMS = "https://www.ufc.com/news/kick-heard-round-world-picked-hall";

function q(seed: Parameters<typeof barTriviaQuestion>[0]) {
  return barTriviaQuestion({ ...seed, verifiedAt: "2026-09-28" });
}

export const BAR_TRIVIA_UFC_EVERGREEN_WAVE_3: readonly BarTriviaQuestion[] = [
  // Round 1 — recognizable milestones, TUF and global expansion
  q({ id:"ufc-r1-first-canada-event", league:"ufc", round:"round1", category:"Global UFC", prompt:"Which numbered event was the UFC's first show in Canada?", choices:["UFC 83","UFC 70","UFC 100","UFC 129"], answer:"UFC 83", explanation:"UFC 83 in Montreal was the promotion's first event in Canada.", sourceId:"ufc-first-canada", sourceUrl:FIRST_CANADA }),
  q({ id:"ufc-r1-first-canada-city", league:"ufc", round:"round1", category:"Global UFC", prompt:"Which Canadian city hosted the UFC for the first time?", choices:["Montreal","Toronto","Vancouver","Calgary"], answer:"Montreal", explanation:"The Bell Centre in Montreal hosted UFC 83, the UFC's first Canadian event.", sourceId:"ufc-first-canada", sourceUrl:FIRST_CANADA }),
  q({ id:"ufc-r1-first-australia-event", league:"ufc", round:"round1", category:"Global UFC", prompt:"Which numbered event marked the UFC's first trip to Australia?", choices:["UFC 110","UFC 127","UFC 193","UFC 234"], answer:"UFC 110", explanation:"UFC 110 in Sydney was the promotion's first event in Australia.", sourceId:"ufc-first-australia", sourceUrl:FIRST_AUSTRALIA }),
  q({ id:"ufc-r1-first-australia-city", league:"ufc", round:"round1", category:"Global UFC", prompt:"Which city hosted the UFC's first Australian event?", choices:["Sydney","Melbourne","Perth","Brisbane"], answer:"Sydney", explanation:"UFC 110 took place at Acer Arena in Sydney.", sourceId:"ufc-first-australia", sourceUrl:FIRST_AUSTRALIA }),
  q({ id:"ufc-r1-first-europe-event", league:"ufc", round:"round1", category:"Global UFC", prompt:"Which event was the UFC's first show in Europe?", choices:["UFC 38","UFC 70","UFC 75","UFC 85"], answer:"UFC 38", explanation:"UFC 38: Brawl at the Hall was the promotion's first event in Europe.", sourceId:"ufc-first-uk", sourceUrl:FIRST_UK }),
  q({ id:"ufc-r1-first-europe-venue", league:"ufc", round:"round1", category:"Venues", prompt:"The UFC's first European event was held at which famous London venue?", choices:["Royal Albert Hall","Wembley Arena","The O2","Alexandra Palace"], answer:"Royal Albert Hall", explanation:"UFC 38 took place at London's Royal Albert Hall in July 2002.", sourceId:"ufc-first-uk", sourceUrl:FIRST_UK }),
  q({ id:"ufc-r1-first-brazil-event", league:"ufc", round:"round1", category:"Global UFC", prompt:"What was the name of the UFC's first event in Brazil?", choices:["Ultimate Brazil","UFC Rio","Brazil Brawl","UFC 18"], answer:"Ultimate Brazil", explanation:"Ultimate Brazil in 1998 was the promotion's first event in South America.", sourceId:"ufc-first-brazil", sourceUrl:FIRST_BRAZIL }),
  q({ id:"ufc-r1-first-france-headliner", league:"ufc", round:"round1", category:"Global UFC", prompt:"Who headlined the UFC's first event in France?", choices:["Ciryl Gane","Manon Fiorot","Benoit Saint Denis","Nassourdine Imavov"], answer:"Ciryl Gane", explanation:"Ciryl Gane faced Tai Tuivasa in the main event of the UFC's first Paris card in 2022.", sourceId:"ufc-first-france", sourceUrl:FIRST_FRANCE }),
  q({ id:"ufc-r1-first-france-opponent", league:"ufc", round:"round1", category:"Global UFC", prompt:"Ciryl Gane faced which heavyweight in the main event of the UFC's first show in France?", choices:["Tai Tuivasa","Alexander Volkov","Derrick Lewis","Serghei Spivac"], answer:"Tai Tuivasa", explanation:"Gane stopped Tai Tuivasa in a memorable main event at the UFC's Paris debut.", sourceId:"ufc-first-france", sourceUrl:FIRST_FRANCE }),
  q({ id:"ufc-r1-tuf2-winner", league:"ufc", round:"round1", category:"The Ultimate Fighter", prompt:"Which future UFC champion won The Ultimate Fighter season 2?", choices:["Rashad Evans","Michael Bisping","Forrest Griffin","Matt Serra"], answer:"Rashad Evans", explanation:"Rashad Evans won the heavyweight tournament on TUF 2 before later becoming UFC light heavyweight champion.", sourceId:"ufc-tuf-winners", sourceUrl:TUF_WINNERS }),
  q({ id:"ufc-r1-tuf3-winner", league:"ufc", round:"round1", category:"The Ultimate Fighter", prompt:"Which future UFC champion won The Ultimate Fighter season 3?", choices:["Michael Bisping","Rashad Evans","Nate Diaz","Tony Ferguson"], answer:"Michael Bisping", explanation:"Michael Bisping won the light heavyweight tournament on TUF 3.", sourceId:"ufc-tuf-winners", sourceUrl:TUF_WINNERS }),
  q({ id:"ufc-r1-tuf5-winner", league:"ufc", round:"round1", category:"The Ultimate Fighter", prompt:"Which fan favorite won The Ultimate Fighter season 5?", choices:["Nate Diaz","Nick Diaz","Tony Ferguson","Gray Maynard"], answer:"Nate Diaz", explanation:"Nate Diaz won the lightweight tournament on TUF 5.", sourceId:"ufc-tuf-winners", sourceUrl:TUF_WINNERS }),
  q({ id:"ufc-r1-tuf18-womens-winner", league:"ufc", round:"round1", category:"Women's MMA", prompt:"Who became the first woman to win The Ultimate Fighter?", choices:["Julianna Peña","Rose Namajunas","Carla Esparza","Tecia Torres"], answer:"Julianna Peña", explanation:"Julianna Peña won the women's bantamweight tournament on TUF 18, the first season to feature women.", sourceId:"ufc-women-history", sourceUrl:WOMEN }),
  q({ id:"ufc-r1-ufc193-attendance-record", league:"ufc", round:"round1", category:"Milestone Events", prompt:"Which event set the UFC attendance record with more than 56,000 fans?", choices:["UFC 193","UFC 205","UFC 100","UFC 300"], answer:"UFC 193", explanation:"UFC 193 in Melbourne drew 56,214 fans, the largest attendance in UFC history through UFC 300.", sourceId:"ufc-by-numbers", sourceUrl:UFC_NUMBERS }),
  q({ id:"ufc-r1-ufc100-location", league:"ufc", round:"round1", category:"Milestone Events", prompt:"UFC 100 took place in which city?", choices:["Las Vegas","New York","Los Angeles","Atlantic City"], answer:"Las Vegas", explanation:"The landmark UFC 100 card took place in Las Vegas in July 2009.", sourceId:"ufc-200-landmarks", sourceUrl:LANDMARKS }),

  // Round 2 — milestones, Hall of Fame fights and promotional history
  q({ id:"ufc-r2-first-nevada-sanctioned", league:"ufc", round:"round2", category:"Rules History", prompt:"Which event was the first UFC card sanctioned by the Nevada State Athletic Commission under the Unified Rules?", choices:["UFC 33","UFC 30","UFC 28","UFC 40"], answer:"UFC 33", explanation:"UFC 33: Victory in Vegas was the first UFC event sanctioned by Nevada under the Unified Rules.", sourceId:"ufc-30-timeline", sourceUrl:UFC30 }),
  q({ id:"ufc-r2-ufc70-city", league:"ufc", round:"round2", category:"Global UFC", prompt:"UFC 70, an early major international card, was held in which English city?", choices:["Manchester","London","Birmingham","Liverpool"], answer:"Manchester", explanation:"UFC 70 took place in Manchester in April 2007.", sourceId:"ufc-30-timeline", sourceUrl:UFC30 }),
  q({ id:"ufc-r2-first-blue-chip-sponsor", league:"ufc", round:"round2", category:"Business History", prompt:"Which company became the first blue-chip sponsor to advertise inside the UFC Octagon in 2008?", choices:["Anheuser-Busch","Nike","Coca-Cola","Toyota"], answer:"Anheuser-Busch", explanation:"Anheuser-Busch became the first blue-chip sponsor to climb inside the Octagon in 2008.", sourceId:"ufc-30-timeline", sourceUrl:UFC30 }),
  q({ id:"ufc-r2-ufc100-technical-event-number", league:"ufc", round:"round2", category:"Milestone Events", prompt:"Although it was called UFC 100, it was technically what number UFC event when Fight Nights and TUF finales were counted?", choices:["133rd","100th","125th","150th"], answer:"133rd", explanation:"UFC notes that UFC 100 was technically its 133rd event when non-numbered cards were included.", sourceId:"ufc-200-landmarks", sourceUrl:LANDMARKS }),
  q({ id:"ufc-r2-ufc100-fan-expo", league:"ufc", round:"round2", category:"Milestone Events", prompt:"Which landmark card was accompanied by the UFC's first Fan Expo?", choices:["UFC 100","UFC 50","UFC 200","UFC 205"], answer:"UFC 100", explanation:"The first UFC Fan Expo was held in the lead-up to UFC 100.", sourceId:"ufc-200-landmarks", sourceUrl:LANDMARKS }),
  q({ id:"ufc-r2-ufc83-main-result", league:"ufc", round:"round2", category:"Championship Moments", prompt:"What did Georges St-Pierre accomplish in the main event of the UFC's first Canadian card?", choices:["Regained the welterweight title","Won the middleweight title","Made his UFC debut","Retired as champion"], answer:"Regained the welterweight title", explanation:"St-Pierre stopped Matt Serra at UFC 83 to regain the welterweight championship in Montreal.", sourceId:"ufc-first-canada", sourceUrl:FIRST_CANADA }),
  q({ id:"ufc-r2-ufc110-main-winner", league:"ufc", round:"round2", category:"Global UFC", prompt:"Who won the main event of the UFC's first card in Australia?", choices:["Cain Velasquez","Antonio Rodrigo Nogueira","Wanderlei Silva","Michael Bisping"], answer:"Cain Velasquez", explanation:"Cain Velasquez knocked out Antonio Rodrigo Nogueira in the first round at UFC 110.", sourceId:"ufc-first-australia", sourceUrl:FIRST_AUSTRALIA }),
  q({ id:"ufc-r2-ufc38-main-winner", league:"ufc", round:"round2", category:"Global UFC", prompt:"Who defended the welterweight title in the main event of UFC 38, the UFC's first European card?", choices:["Matt Hughes","Carlos Newton","Pat Miletich","Georges St-Pierre"], answer:"Matt Hughes", explanation:"Matt Hughes stopped Carlos Newton in the fourth round at Royal Albert Hall.", sourceId:"ufc-first-uk", sourceUrl:FIRST_UK }),
  q({ id:"ufc-r2-hof-four-wings", league:"ufc", round:"round2", category:"Hall of Fame", prompt:"How many distinct wings does the UFC Hall of Fame use?", choices:["4","3","5","6"], answer:"4", explanation:"The UFC Hall of Fame has Modern, Pioneer, Fight and Contributors wings.", sourceId:"ufc-hof-faq", sourceUrl:HOF }),
  q({ id:"ufc-r2-hof-contributors-purpose", league:"ufc", round:"round2", category:"Hall of Fame", prompt:"Which UFC Hall of Fame wing honors major contributions outside active competition?", choices:["Contributors Wing","Fight Wing","Modern Wing","Pioneer Wing"], answer:"Contributors Wing", explanation:"The Contributors Wing recognizes important non-competitive contributions to UFC.", sourceId:"ufc-hof-faq", sourceUrl:HOF }),
  q({ id:"ufc-r2-hof-fight-purpose", league:"ufc", round:"round2", category:"Hall of Fame", prompt:"Which UFC Hall of Fame wing honors historically significant individual bouts?", choices:["Fight Wing","Pioneer Wing","Modern Wing","Contributors Wing"], answer:"Fight Wing", explanation:"The Fight Wing inducts both athletes from historically significant UFC bouts.", sourceId:"ufc-hof-faq", sourceUrl:HOF }),
  q({ id:"ufc-r2-first-womens-hof-fight", league:"ufc", round:"round2", category:"Hall of Fame", prompt:"Which bout became the first women's fight selected for the UFC Hall of Fame Fight Wing?", choices:["Zhang Weili vs. Joanna Jedrzejczyk","Ronda Rousey vs. Holly Holm","Rose Namajunas vs. Joanna Jedrzejczyk","Amanda Nunes vs. Cris Cyborg"], answer:"Zhang Weili vs. Joanna Jedrzejczyk", explanation:"Their UFC 248 classic was announced for the 2026 Fight Wing, the first women's bout selected for the honor.", sourceId:"ufc-hof-zhang-joanna", sourceUrl:HOF_ZHANG }),
  q({ id:"ufc-r2-hof-2025-fight", league:"ufc", round:"round2", category:"Hall of Fame", prompt:"Which UFC 236 classic joined the Hall of Fame Fight Wing in the Class of 2025?", choices:["Israel Adesanya vs. Kelvin Gastelum","Max Holloway vs. Dustin Poirier","Jon Jones vs. Thiago Santos","Robert Whittaker vs. Yoel Romero"], answer:"Israel Adesanya vs. Kelvin Gastelum", explanation:"Adesanya-Gastelum's 2019 interim middleweight title fight was selected for the 2025 Fight Wing.", sourceId:"ufc-hof-adesanya-gastelum", sourceUrl:HOF_ADESANYA }),
  q({ id:"ufc-r2-hof-2024-fight", league:"ufc", round:"round2", category:"Hall of Fame", prompt:"Which UFC 117 comeback fight joined the Hall of Fame Fight Wing in 2024?", choices:["Anderson Silva vs. Chael Sonnen","Frankie Edgar vs. Gray Maynard","Brock Lesnar vs. Shane Carwin","Georges St-Pierre vs. Josh Koscheck"], answer:"Anderson Silva vs. Chael Sonnen", explanation:"Silva-Sonnen I was inducted into the Hall of Fame Fight Wing as part of the Class of 2024.", sourceId:"ufc-hof-silva-sonnen", sourceUrl:HOF_SILVA }),
  q({ id:"ufc-r2-hof-2023-fight", league:"ufc", round:"round2", category:"Hall of Fame", prompt:"Which bloody UFC 189 title fight entered the Hall of Fame Fight Wing in 2023?", choices:["Robbie Lawler vs. Rory MacDonald II","Conor McGregor vs. Chad Mendes","Jose Aldo vs. Chad Mendes II","Daniel Cormier vs. Alexander Gustafsson"], answer:"Robbie Lawler vs. Rory MacDonald II", explanation:"Lawler-MacDonald II was inducted into the Fight Wing in 2023.", sourceId:"ufc-hof-lawler-macdonald", sourceUrl:HOF_LAWLER }),

  // Round 3 — deeper event and Hall of Fame history
  q({ id:"ufc-r3-hof-swanson-choi-event", league:"ufc", round:"round3", category:"Hall of Fame", prompt:"Cub Swanson and Dooho Choi's Hall of Fame war took place at which event?", choices:["UFC 206","UFC 199","UFC 217","UFC 202"], answer:"UFC 206", explanation:"Swanson and Choi fought their 2016 Fight of the Year at UFC 206.", sourceId:"ufc-hof-swanson-choi", sourceUrl:HOF_SWANSON }),
  q({ id:"ufc-r3-hof-hendo-shogun-event", league:"ufc", round:"round3", category:"Hall of Fame", prompt:"Dan Henderson and Shogun Rua's first Hall of Fame battle took place at which event?", choices:["UFC 139","UFC 128","UFC 145","UFC 157"], answer:"UFC 139", explanation:"Henderson and Rua fought a five-round classic at UFC 139 in 2011.", sourceId:"ufc-hof-hendo-shogun", sourceUrl:HOF_HENDO }),
  q({ id:"ufc-r3-hof-hughes-trigg-event", league:"ufc", round:"round3", category:"Hall of Fame", prompt:"Matt Hughes and Frank Trigg's Hall of Fame rematch happened at which event?", choices:["UFC 52","UFC 50","UFC 54","UFC 60"], answer:"UFC 52", explanation:"Hughes-Trigg II took place at UFC 52 in April 2005.", sourceId:"ufc-hof-hughes-trigg", sourceUrl:HOF_HUGHES }),
  q({ id:"ufc-r3-hof-sanchez-guida-event", league:"ufc", round:"round3", category:"Hall of Fame", prompt:"Diego Sanchez and Clay Guida's Hall of Fame fight was staged at which show?", choices:["The Ultimate Fighter 9 Finale","UFC 100","UFC 107","UFC Fight Night 19"], answer:"The Ultimate Fighter 9 Finale", explanation:"Sanchez and Guida's 2009 classic headlined The Ultimate Fighter 9 Finale.", sourceId:"ufc-hof-sanchez-guida", sourceUrl:HOF_SANCHEZ }),
  q({ id:"ufc-r3-hof-williams-coleman", league:"ufc", round:"round3", category:"Hall of Fame", prompt:"Which fighter scored the upset over Mark Coleman in the 1998 bout later inducted into the UFC Hall of Fame?", choices:["Pete Williams","Maurice Smith","Randy Couture","Bas Rutten"], answer:"Pete Williams", explanation:"Pete Williams upset Mark Coleman in a 1998 fight later selected for the Hall of Fame Fight Wing.", sourceId:"ufc-hof-williams-coleman", sourceUrl:HOF_WILLIAMS }),
  q({ id:"ufc-r3-hof-jones-gus-location", league:"ufc", round:"round3", category:"Hall of Fame", prompt:"Jon Jones and Alexander Gustafsson's UFC 165 classic took place in which city?", choices:["Toronto","Las Vegas","Stockholm","New York"], answer:"Toronto", explanation:"Their five-round light heavyweight title fight took place at Air Canada Centre in Toronto.", sourceId:"ufc-hof-jones-gustafsson", sourceUrl:HOF_JONES }),
  q({ id:"ufc-r3-hof-zhang-joanna-event", league:"ufc", round:"round3", category:"Hall of Fame", prompt:"Zhang Weili and Joanna Jedrzejczyk's Hall of Fame classic took place at which event?", choices:["UFC 248","UFC 261","UFC 217","UFC 237"], answer:"UFC 248", explanation:"The celebrated strawweight title fight took place at UFC 248 in 2020.", sourceId:"ufc-hof-zhang-joanna", sourceUrl:HOF_ZHANG }),
  q({ id:"ufc-r3-hof-adesanya-gastelum-event", league:"ufc", round:"round3", category:"Hall of Fame", prompt:"Israel Adesanya and Kelvin Gastelum fought their Hall of Fame classic at which event?", choices:["UFC 236","UFC 243","UFC 234","UFC 245"], answer:"UFC 236", explanation:"Their interim middleweight title fight was the co-main event of UFC 236.", sourceId:"ufc-hof-adesanya-gastelum", sourceUrl:HOF_ADESANYA }),
  q({ id:"ufc-r3-hof-lawler-macdonald-event", league:"ufc", round:"round3", category:"Hall of Fame", prompt:"Robbie Lawler and Rory MacDonald's Hall of Fame rematch took place at which event?", choices:["UFC 189","UFC 181","UFC 194","UFC 200"], answer:"UFC 189", explanation:"Lawler stopped MacDonald in the fifth round of their UFC 189 title rematch.", sourceId:"ufc-hof-lawler-macdonald", sourceUrl:HOF_LAWLER }),
  q({ id:"ufc-r3-hof-silva-sonnen-event", league:"ufc", round:"round3", category:"Hall of Fame", prompt:"Anderson Silva's dramatic first fight with Chael Sonnen happened at which event?", choices:["UFC 117","UFC 112","UFC 126","UFC 148"], answer:"UFC 117", explanation:"Silva submitted Sonnen late in the fifth round at UFC 117.", sourceId:"ufc-hof-silva-sonnen", sourceUrl:HOF_SILVA }),
  q({ id:"ufc-r3-first-asia-event", league:"ufc", round:"round3", category:"Global UFC", prompt:"The UFC's first event in Asia was held in which country?", choices:["Japan","China","South Korea","Singapore"], answer:"Japan", explanation:"UFC Japan: Ultimate Japan in Yokohama was the promotion's first event in Asia.", sourceId:"ufc-30-timeline", sourceUrl:UFC30 }),
  q({ id:"ufc-r3-first-asia-city", league:"ufc", round:"round3", category:"Global UFC", prompt:"Which Japanese city hosted the UFC's first event in Asia?", choices:["Yokohama","Tokyo","Saitama","Osaka"], answer:"Yokohama", explanation:"UFC Japan: Ultimate Japan took place in Yokohama.", sourceId:"ufc-30-timeline", sourceUrl:UFC30 }),
  q({ id:"ufc-r3-hunt-bigfoot-draw", league:"ufc", round:"round3", category:"Classic Fights", prompt:"What decision did the judges announce after five rounds of Mark Hunt vs. Antonio \"Bigfoot\" Silva in Brisbane?", choices:["Majority draw","Split decision for Hunt","Unanimous draw","Split decision for Silva"], answer:"Majority draw", explanation:"The 2013 heavyweight classic ended with scorecards of 48–47 Hunt and 47–47 twice, producing a majority draw.", sourceId:"ufc-hunt-bigfoot-brisbane", sourceUrl:"https://www.ufc.com/news/brisbane-bonuses-and-presser-recap" }),
  q({ id:"ufc-r3-ufc193-attendance", league:"ufc", round:"round3", category:"Milestone Events", prompt:"Roughly how many fans attended UFC 193, the promotion's attendance record through UFC 300?", choices:["56,000","42,000","71,000","33,000"], answer:"56,000", explanation:"UFC records list UFC 193 attendance at 56,214.", sourceId:"ufc-by-numbers", sourceUrl:UFC_NUMBERS }),
  q({ id:"ufc-r3-hof-modern-cutoff", league:"ufc", round:"round3", category:"Hall of Fame", prompt:"Which event serves as the UFC Hall of Fame's dividing line between the Pioneer and Modern eras?", choices:["UFC 28","UFC 30","UFC 1","UFC 33"], answer:"UFC 28", explanation:"The Hall of Fame uses UFC 28 on November 17, 2000, the first event to use the Unified Rules, as its era cutoff.", sourceId:"ufc-hof-faq", sourceUrl:HOF }),

  // Last Call — deep but memorable history
  q({ id:"ufc-final-first-europe-date", league:"ufc", round:"last-call", category:"Global UFC", prompt:"In what year did the UFC stage its first event in Europe at Royal Albert Hall?", choices:["2002","1999","2005","2007"], answer:"2002", explanation:"UFC 38: Brawl at the Hall took place in London on July 13, 2002.", sourceId:"ufc-first-uk", sourceUrl:FIRST_UK }),
  q({ id:"ufc-final-first-canada-date", league:"ufc", round:"last-call", category:"Global UFC", prompt:"In what year did UFC 83 bring the Octagon to Canada for the first time?", choices:["2008","2006","2010","2011"], answer:"2008", explanation:"UFC 83 took place in Montreal on April 19, 2008.", sourceId:"ufc-first-canada", sourceUrl:FIRST_CANADA }),
  q({ id:"ufc-final-first-australia-date", league:"ufc", round:"last-call", category:"Global UFC", prompt:"In what year did UFC 110 become the promotion's first event in Australia?", choices:["2010","2008","2012","2014"], answer:"2010", explanation:"UFC 110 took place in Sydney on February 21, 2010.", sourceId:"ufc-first-australia", sourceUrl:FIRST_AUSTRALIA }),
  q({ id:"ufc-final-hof-contributor-matchmaker", league:"ufc", round:"last-call", category:"Hall of Fame", prompt:"Which longtime UFC matchmaker is a member of the Hall of Fame Contributors Wing?", choices:["Joe Silva","Bruce Buffer","Herb Dean","Mike Goldberg"], answer:"Joe Silva", explanation:"Longtime matchmaker Joe Silva was inducted into the Contributors Wing in 2017.", sourceId:"ufc-hof-faq", sourceUrl:HOF }),
  q({ id:"ufc-final-hof-contributor-cofounder", league:"ufc", round:"last-call", category:"Hall of Fame", prompt:"Which UFC co-founder was inducted into the Hall of Fame Contributors Wing in 2018?", choices:["Art Davie","Rorion Gracie","Dana White","Lorenzo Fertitta"], answer:"Art Davie", explanation:"UFC co-founder Art Davie joined the Hall of Fame Contributors Wing in 2018.", sourceId:"ufc-hof-faq", sourceUrl:HOF }),
];
