import { barTriviaQuestion, type BarTriviaQuestion } from "../games/barTriviaEngine";

const UFC30 = "https://www.ufc.com/news/ufc-turns-30-years-old";
const ZUFFA30 = "https://www.ufc.com/news/fight-flashback-first-event";
const BRAZIL_FIRST = "https://www.ufc.com/news/murilo-bustamante-brazils-first-ufc-champion-ufc-30th-anniversary";
const MEXICO_FIRST = "https://www.ufc.com/news/brandon-moreno-mexico-first-champion-ufc-30th-anniversary";
const UK_FIRST = "https://www.ufc.com/news/michael-bisping-united-kingdom-first-champion-ufc-30th-anniversary";
const CANADA_FIRST = "https://www.ufc.com/news/canada-first-champion-carlos-newton-ufc-30th-anniversary";
const AUSTRALIA_FIRST = "https://www.ufc.com/news/robert-whittaker-australia-first-champion-ufc-30th-anniversary";
const WOMEN_FIRST = "https://www.ufc.com/news/ufc-crowns-its-first-queen";
const WOMEN_HISTORY = "https://www.ufc.com/news/women-in-the-ufc-30th-anniversary";
const UFC157 = "https://www.ufc.com/news/ufc-157-main-card-results-ronda-makes-history";
const UFC205 = "https://www.ufc.com/news/ufc-205-final-results-and-news-nyc";
const UFC205_HISTORY = "https://www.ufc.com/news/first-time-madison-square-garden-nyc-ufc-30th-anniversary-mcgregor-nurmagomedov";
const SAO_PAULO = "https://www.ufc.com/news/super-sao-paulo-moments-ufc-30th-anniversary";
const TUF1 = "https://www.ufc.com/news/ufc-legends-griffin-vs-bonnar-1";

function q(seed: Parameters<typeof barTriviaQuestion>[0]) {
  return barTriviaQuestion({ ...seed, verifiedAt: "2026-09-28" });
}

export const BAR_TRIVIA_UFC_EVERGREEN_WAVE_2: readonly BarTriviaQuestion[] = [
  // Round 1
  q({ id:"ufc-r1-founders-pair", league:"ufc", round:"round1", category:"Origins", prompt:"Which pair is credited by UFC with launching the first Ultimate Fighting Championship in 1993?", choices:["Art Davie and Rorion Gracie","Dana White and Lorenzo Fertitta","Royce Gracie and Ken Shamrock","John Milius and Bruce Buffer"], answer:"Art Davie and Rorion Gracie", explanation:"Art Davie and Rorion Gracie organized the first UFC event in 1993.", sourceId:"ufc-30-history", sourceUrl:UFC30 }),
  q({ id:"ufc-r1-zuffa-first-event", league:"ufc", round:"round1", category:"Promotion History", prompt:"UFC 30 was the first UFC show under which new ownership company?", choices:["Zuffa","Endeavor","WME-IMG","Semaphore Entertainment Group"], answer:"Zuffa", explanation:"Zuffa purchased the UFC in January 2001, and UFC 30 was its first event.", sourceId:"ufc-zuffa-first-event", sourceUrl:ZUFFA30 }),
  q({ id:"ufc-r1-zuffa-first-city", league:"ufc", round:"round1", category:"Venues", prompt:"Zuffa's first UFC event took place in which city?", choices:["Atlantic City","Las Vegas","New York","Denver"], answer:"Atlantic City", explanation:"UFC 30 was held at the Trump Taj Mahal in Atlantic City, New Jersey.", sourceId:"ufc-zuffa-first-event", sourceUrl:ZUFFA30 }),
  q({ id:"ufc-r1-brazil-first-champion", league:"ufc", round:"round1", category:"International Champions", prompt:"Who became the first Brazilian fighter to win a UFC championship?", choices:["Murilo Bustamante","Anderson Silva","Vitor Belfort","Jose Aldo"], answer:"Murilo Bustamante", explanation:"Murilo Bustamante beat Dave Menne in 2002 to become Brazil's first UFC champion.", sourceId:"ufc-brazil-first-champ", sourceUrl:BRAZIL_FIRST }),
  q({ id:"ufc-r1-mexico-first-champion", league:"ufc", round:"round1", category:"International Champions", prompt:"Who became the first Mexico-born fighter to win a UFC championship?", choices:["Brandon Moreno","Yair Rodriguez","Alexa Grasso","Diego Lopes"], answer:"Brandon Moreno", explanation:"Brandon Moreno submitted Deiveson Figueiredo at UFC 263 to become Mexico's first UFC champion.", sourceId:"ufc-mexico-first-champ", sourceUrl:MEXICO_FIRST }),
  q({ id:"ufc-r1-uk-first-champion", league:"ufc", round:"round1", category:"International Champions", prompt:"Who became the first fighter from the United Kingdom to win a UFC championship?", choices:["Michael Bisping","Leon Edwards","Tom Aspinall","Dan Hardy"], answer:"Michael Bisping", explanation:"Michael Bisping knocked out Luke Rockhold at UFC 199 to become the UK's first UFC champion.", sourceId:"ufc-uk-first-champ", sourceUrl:UK_FIRST }),
  q({ id:"ufc-r1-canada-first-champion", league:"ufc", round:"round1", category:"International Champions", prompt:"Who became Canada's first UFC champion?", choices:["Carlos Newton","Georges St-Pierre","Patrick Cote","Rory MacDonald"], answer:"Carlos Newton", explanation:"Carlos Newton submitted Pat Miletich at UFC 31 to become Canada's first UFC champion.", sourceId:"ufc-canada-first-champ", sourceUrl:CANADA_FIRST }),
  q({ id:"ufc-r1-australia-first-champion", league:"ufc", round:"round1", category:"International Champions", prompt:"Who became Australia's first UFC champion?", choices:["Robert Whittaker","Alexander Volkanovski","Mark Hunt","Jack Della Maddalena"], answer:"Robert Whittaker", explanation:"Robert Whittaker became Australia's first UFC champion in 2017.", sourceId:"ufc-australia-first-champ", sourceUrl:AUSTRALIA_FIRST }),
  q({ id:"ufc-r1-prodigy", league:"ufc", round:"round1", category:"Nicknames", prompt:"Which two-division UFC champion is famously known as \"The Prodigy\"?", choices:["BJ Penn","Frankie Edgar","Matt Hughes","Jens Pulver"], answer:"BJ Penn", explanation:"BJ Penn carried \"The Prodigy\" nickname from his rapid rise in Brazilian jiu-jitsu into his UFC Hall of Fame career.", sourceId:"ufc-bj-penn-prodigy", sourceUrl:"https://www.ufc.com/news/bj-penn-joins-ufc-hall-fame-july" }),
  q({ id:"ufc-r1-women-debut-event", league:"ufc", round:"round1", category:"Women's MMA", prompt:"UFC 157's Ronda Rousey vs. Liz Carmouche main event introduced which UFC women's division?", choices:["Women's bantamweight","Women's strawweight","Women's flyweight","Women's featherweight"], answer:"Women's bantamweight", explanation:"Ronda Rousey and Liz Carmouche made UFC history in the main event of UFC 157.", sourceId:"ufc-157-history", sourceUrl:UFC157 }),
  q({ id:"ufc-r1-first-china-champion", league:"ufc", round:"round1", category:"International Champions", prompt:"Who became the UFC's first champion from China?", choices:["Zhang Weili","Yan Xiaonan","Song Yadong","Li Jingliang"], answer:"Zhang Weili", explanation:"Zhang Weili won the strawweight title in 2019 to become the UFC's first Chinese champion.", sourceId:"ufc-women-history", sourceUrl:WOMEN_HISTORY }),
  q({ id:"ufc-r1-bisping-title-opponent", league:"ufc", round:"round1", category:"Championship Moments", prompt:"Michael Bisping won the UFC middleweight title by knocking out which champion?", choices:["Luke Rockhold","Chris Weidman","Anderson Silva","Dan Henderson"], answer:"Luke Rockhold", explanation:"Bisping took the fight on short notice and knocked out Luke Rockhold at UFC 199.", sourceId:"ufc-uk-first-champ", sourceUrl:UK_FIRST }),
  q({ id:"ufc-r1-tuf-year", league:"ufc", round:"round1", category:"The Ultimate Fighter", prompt:"The first season of The Ultimate Fighter aired in which year?", choices:["2005","2003","2007","2009"], answer:"2005", explanation:"The inaugural TUF season culminated with Griffin vs. Bonnar on April 9, 2005.", sourceId:"ufc-tuf1-legacy", sourceUrl:TUF1 }),

  // Round 2
  q({ id:"ufc-r2-zuffa-purchase-year", league:"ufc", round:"round2", category:"Promotion History", prompt:"Zuffa purchased the UFC in which year?", choices:["2001","1998","2003","2005"], answer:"2001", explanation:"Frank and Lorenzo Fertitta, with Dana White, took control of the UFC through Zuffa in January 2001.", sourceId:"ufc-zuffa-first-event", sourceUrl:ZUFFA30 }),
  q({ id:"ufc-r2-zuffa-first-venue", league:"ufc", round:"round2", category:"Venues", prompt:"Which venue hosted UFC 30, the first event of the Zuffa era?", choices:["Trump Taj Mahal","MGM Grand Garden Arena","Boardwalk Hall","Madison Square Garden"], answer:"Trump Taj Mahal", explanation:"UFC 30 took place at the Trump Taj Mahal in Atlantic City.", sourceId:"ufc-zuffa-first-event", sourceUrl:ZUFFA30 }),
  q({ id:"ufc-r2-bustamante-title-opponent", league:"ufc", round:"round2", category:"Championship History", prompt:"Murilo Bustamante beat which fighter to become Brazil's first UFC champion?", choices:["Dave Menne","Matt Lindland","Tito Ortiz","Kevin Randleman"], answer:"Dave Menne", explanation:"Bustamante defeated Dave Menne in 2002 to claim the middleweight title.", sourceId:"ufc-brazil-first-champ", sourceUrl:BRAZIL_FIRST }),
  q({ id:"ufc-r2-moreno-title-opponent", league:"ufc", round:"round2", category:"Championship History", prompt:"Brandon Moreno submitted which champion to become Mexico's first UFC titleholder?", choices:["Deiveson Figueiredo","Joseph Benavidez","Alexandre Pantoja","Kai Kara-France"], answer:"Deiveson Figueiredo", explanation:"Moreno submitted Figueiredo at UFC 263 to win the flyweight title.", sourceId:"ufc-mexico-first-champ", sourceUrl:MEXICO_FIRST }),
  q({ id:"ufc-r2-newton-title-opponent", league:"ufc", round:"round2", category:"Championship History", prompt:"Carlos Newton defeated which champion to become Canada's first UFC titleholder?", choices:["Pat Miletich","Matt Hughes","Frank Trigg","Carlos Condit"], answer:"Pat Miletich", explanation:"Newton defeated Pat Miletich at UFC 31 to win the welterweight championship.", sourceId:"ufc-canada-first-champ", sourceUrl:CANADA_FIRST }),
  q({ id:"ufc-r2-whittaker-tuf-version", league:"ufc", round:"round2", category:"The Ultimate Fighter", prompt:"Robert Whittaker first reached the UFC through which version of The Ultimate Fighter?", choices:["The Smashes","Team Hughes vs. Team Serra","The Comeback","Brazil"], answer:"The Smashes", explanation:"Whittaker won the welterweight tournament on The Ultimate Fighter: The Smashes.", sourceId:"ufc-australia-first-champ", sourceUrl:AUSTRALIA_FIRST }),
  q({ id:"ufc-r2-rousey-olympic-sport", league:"ufc", round:"round2", category:"Fighter Backgrounds", prompt:"Before becoming the UFC's first female champion, Ronda Rousey won an Olympic medal in which sport?", choices:["Judo","Wrestling","Boxing","Taekwondo"], answer:"Judo", explanation:"Rousey won an Olympic bronze medal in judo at the 2008 Beijing Games.", sourceId:"ufc-first-queen", sourceUrl:WOMEN_FIRST }),
  q({ id:"ufc-r2-rousey-carmouche-city", league:"ufc", round:"round2", category:"Venues", prompt:"Ronda Rousey and Liz Carmouche made women's UFC history in which California city?", choices:["Anaheim","Los Angeles","San Diego","Sacramento"], answer:"Anaheim", explanation:"UFC 157 was held at the Honda Center in Anaheim.", sourceId:"ufc-157-history", sourceUrl:UFC157 }),
  q({ id:"ufc-r2-first-womens-flyweight-champ", league:"ufc", round:"round2", category:"Women's MMA", prompt:"Who became the UFC's first women's flyweight champion?", choices:["Nicco Montano","Valentina Shevchenko","Joanna Jedrzejczyk","Roxanne Modafferi"], answer:"Nicco Montano", explanation:"Nicco Montano defeated Roxanne Modafferi at the TUF 26 Finale to win the inaugural flyweight title.", sourceId:"ufc-women-history", sourceUrl:WOMEN_HISTORY }),
  q({ id:"ufc-r2-first-female-double-champ", league:"ufc", round:"round2", category:"Championships", prompt:"Who became the first woman to hold UFC titles in two divisions at the same time?", choices:["Amanda Nunes","Ronda Rousey","Valentina Shevchenko","Cris Cyborg"], answer:"Amanda Nunes", explanation:"Amanda Nunes became the UFC's first female simultaneous double champion.", sourceId:"ufc-women-history", sourceUrl:WOMEN_HISTORY }),
  q({ id:"ufc-r2-ufc205-three-title-fights", league:"ufc", round:"round2", category:"Milestone Events", prompt:"What made UFC 205 unique among UFC cards at the time besides being the first at Madison Square Garden?", choices:["It featured three world title fights","It had no preliminary card","Every fight was five rounds","It used a tournament format"], answer:"It featured three world title fights", explanation:"UFC 205 was the first UFC event to feature three world title fights.", sourceId:"ufc-205-history", sourceUrl:UFC205_HISTORY }),
  q({ id:"ufc-r2-ufc205-welterweight-draw", league:"ufc", round:"round2", category:"Milestone Events", prompt:"Which two fighters battled to a majority draw for the welterweight title at UFC 205?", choices:["Tyron Woodley and Stephen Thompson","Robbie Lawler and Carlos Condit","Georges St-Pierre and Johny Hendricks","Kamaru Usman and Colby Covington"], answer:"Tyron Woodley and Stephen Thompson", explanation:"Woodley retained the welterweight championship after a majority draw with Stephen 'Wonderboy' Thompson.", sourceId:"ufc-205-results", sourceUrl:UFC205 }),
  q({ id:"ufc-r2-first-brazil-event-city", league:"ufc", round:"round2", category:"International", prompt:"The UFC's first event in Brazil took place in which city?", choices:["São Paulo","Rio de Janeiro","Curitiba","Brasília"], answer:"São Paulo", explanation:"Ultimate Brazil was held in São Paulo in 1998.", sourceId:"ufc-sao-paulo-history", sourceUrl:SAO_PAULO }),

  // Round 3
  q({ id:"ufc-r3-ufc-origin-inspiration", league:"ufc", round:"round3", category:"Origins", prompt:"UFC co-founder Art Davie said which ancient combat sport helped inspire the concept for the UFC?", choices:["Pankration","Gladiatorial chariot racing","Sumo","Savate"], answer:"Pankration", explanation:"Davie cited ancient pankration, a mix of striking and grappling, as a major inspiration.", sourceId:"ufc-30-history", sourceUrl:UFC30 }),
  q({ id:"ufc-r3-first-creative-director", league:"ufc", round:"round3", category:"Origins", prompt:"Which filmmaker and writer served as the first UFC's creative director?", choices:["John Milius","Oliver Stone","John Carpenter","Walter Hill"], answer:"John Milius", explanation:"UFC's 30th-anniversary history identifies John Milius as the first event's creative director.", sourceId:"ufc-30-history", sourceUrl:UFC30 }),
  q({ id:"ufc-r3-bustamante-ufc-debut", league:"ufc", round:"round3", category:"Fighter History", prompt:"At UFC 25, Murilo Bustamante made his UFC debut by submitting which opponent?", choices:["Yoji Anjo","Ikuhisa Minowa","Matt Lindland","Dave Menne"], answer:"Yoji Anjo", explanation:"Bustamante debuted at UFC 25 and submitted Yoji Anjo.", sourceId:"ufc-brazil-first-champ", sourceUrl:BRAZIL_FIRST }),
  q({ id:"ufc-r3-bustamante-debut-opponent", league:"ufc", round:"round3", category:"Fighter History", prompt:"Brazil's first UFC champion Murilo Bustamante made his Octagon debut against whom?", choices:["Yoji Anjo","Dave Menne","Matt Lindland","Jerry Bohlander"], answer:"Yoji Anjo", explanation:"Bustamante submitted Yoji Anjo with an arm triangle at UFC 25.", sourceId:"ufc-brazil-first-champ", sourceUrl:BRAZIL_FIRST }),
  q({ id:"ufc-r3-moreno-title-event", league:"ufc", round:"round2", category:"Championship History", prompt:"At UFC 263, whom did Brandon Moreno submit to become Mexico's first UFC champion?", choices:["Deiveson Figueiredo","Kai Kara-France","Brandon Royval","Alexandre Pantoja"], answer:"Deiveson Figueiredo", explanation:"Moreno submitted Deiveson Figueiredo at UFC 263 to win the flyweight title.", sourceId:"ufc-mexico-first-champ", sourceUrl:MEXICO_FIRST }),
  q({ id:"ufc-r3-bisping-title-event", league:"ufc", round:"round2", category:"Championship History", prompt:"At UFC 199, Michael Bisping stepped in on short notice and upset which champion for the middleweight title?", choices:["Luke Rockhold","Chris Weidman","Anderson Silva","Robert Whittaker"], answer:"Luke Rockhold", explanation:"Bisping stepped in on short notice and stopped Rockhold at UFC 199.", sourceId:"ufc-uk-first-champ", sourceUrl:UK_FIRST }),
  q({ id:"ufc-r3-bisping-tuf-season", league:"ufc", round:"round3", category:"The Ultimate Fighter", prompt:"Michael Bisping first entered the UFC by winning which season of The Ultimate Fighter?", choices:["Season 3","Season 1","Season 5","Season 7"], answer:"Season 3", explanation:"Bisping won the light heavyweight tournament on the third season of TUF.", sourceId:"ufc-uk-first-champ", sourceUrl:UK_FIRST }),
  q({ id:"ufc-r3-newton-title-event", league:"ufc", round:"round3", category:"Championship History", prompt:"At UFC 31, whom did Carlos Newton defeat to become Canada's first UFC champion?", choices:["Pat Miletich","Matt Hughes","Georges St-Pierre","Frank Trigg"], answer:"Pat Miletich", explanation:"Newton defeated Pat Miletich at UFC 31.", sourceId:"ufc-canada-first-champ", sourceUrl:CANADA_FIRST }),
  q({ id:"ufc-r3-ufc205-main-finish", league:"ufc", round:"round3", category:"Milestone Events", prompt:"How did Conor McGregor defeat Eddie Alvarez in the UFC 205 main event?", choices:["Second-round TKO","First-round submission","Five-round decision","Third-round knockout"], answer:"Second-round TKO", explanation:"McGregor stopped Alvarez at 3:04 of round two to become simultaneous featherweight and lightweight champion.", sourceId:"ufc-205-results", sourceUrl:UFC205 }),
  q({ id:"ufc-r3-ufc205-womens-title", league:"ufc", round:"round3", category:"Milestone Events", prompt:"Which women's title was defended by Joanna Jedrzejczyk at UFC 205?", choices:["Strawweight","Flyweight","Bantamweight","Featherweight"], answer:"Strawweight", explanation:"Jedrzejczyk defended the strawweight championship against Karolina Kowalkiewicz at UFC 205.", sourceId:"ufc-205-results", sourceUrl:UFC205 }),
  q({ id:"ufc-r3-ultimate-brazil-title-firsts", league:"ufc", round:"round3", category:"International", prompt:"The UFC's first event in Brazil also featured the promotion's first title fights in which two divisions?", choices:["Lightweight and middleweight","Welterweight and heavyweight","Featherweight and bantamweight","Flyweight and light heavyweight"], answer:"Lightweight and middleweight", explanation:"Ultimate Brazil in 1998 featured the first UFC lightweight and middleweight championship fights.", sourceId:"ufc-sao-paulo-history", sourceUrl:SAO_PAULO }),
  q({ id:"ufc-r3-vitor-wanderlei-event", league:"ufc", round:"round3", category:"Historic Fights", prompt:"Vitor Belfort's famous quick knockout of Wanderlei Silva happened at which event?", choices:["UFC Ultimate Brazil","UFC 12","UFC 17","UFC 20"], answer:"UFC Ultimate Brazil", explanation:"Belfort stopped Wanderlei Silva at the UFC's first event in Brazil in 1998.", sourceId:"ufc-sao-paulo-history", sourceUrl:SAO_PAULO }),
  q({ id:"ufc-r3-tuf1-other-winner", league:"ufc", round:"round3", category:"The Ultimate Fighter", prompt:"Besides Forrest Griffin, which fighter won a tournament on the first season of The Ultimate Fighter?", choices:["Diego Sanchez","Kenny Florian","Josh Koscheck","Chris Leben"], answer:"Diego Sanchez", explanation:"Diego Sanchez defeated Kenny Florian to win the middleweight competition on TUF 1.", sourceId:"ufc-tuf1-sanchez", sourceUrl:"https://www.ufc.com/news/diego-sanchez-has-new-mindset-ufc-253-fight-island" }),

  // Last Call
  q({ id:"ufc-final-zuffa-purchase-date", league:"ufc", round:"last-call", category:"Promotion History", prompt:"Zuffa's purchase of the UFC was completed in which month of 2001?", choices:["January","March","July","November"], answer:"January", explanation:"Zuffa purchased the UFC on January 11, 2001.", sourceId:"ufc-zuffa-first-event", sourceUrl:ZUFFA30 }),
  q({ id:"ufc-final-first-brazil-two-titles", league:"ufc", round:"last-call", category:"International History", prompt:"At the UFC's first event in Brazil, which future Hall of Famer fought Wanderlei Silva in the card's famous sprint of a fight?", choices:["Vitor Belfort","Royce Gracie","Anderson Silva","Murilo Bustamante"], answer:"Vitor Belfort", explanation:"Vitor Belfort stopped Wanderlei Silva at Ultimate Brazil in São Paulo.", sourceId:"ufc-sao-paulo-history", sourceUrl:SAO_PAULO }),
  q({ id:"ufc-final-first-ufc-name-purpose", league:"ufc", round:"last-call", category:"Origins", prompt:"The original UFC concept was built to answer what basic question?", choices:["Which martial art was most effective in a real fight?","Which country produced the best wrestlers?","Could boxing beat kickboxing under boxing rules?","Which fighter could win five rounds fastest?"], answer:"Which martial art was most effective in a real fight?", explanation:"Davie and Rorion Gracie conceived the first UFC as a way to compare fighting styles under a single event format.", sourceId:"ufc-30-history", sourceUrl:UFC30 }),
];
