import { barTriviaQuestion, type BarTriviaQuestion } from "../games/barTriviaEngine";

function q(question: Parameters<typeof barTriviaQuestion>[0]) {
  return barTriviaQuestion(question);
}

export const BAR_TRIVIA_EASY_EXPANSION: readonly BarTriviaQuestion[] = [
  // NFL — broad, recognizable sports-bar entry questions.
  q({ id:"nfl-easy-arrowhead", league:"nfl", round:"round1", difficulty:"easy", category:"Stadiums", prompt:"Arrowhead Stadium is the home field of which NFL team?", choices:["Kansas City Chiefs","Denver Broncos","Las Vegas Raiders","Los Angeles Chargers"], answer:"Kansas City Chiefs", explanation:"Arrowhead Stadium in Kansas City has been home to the Chiefs since 1972.", sourceId:"nfl-easy-calibration" }),
  q({ id:"nfl-easy-beast-mode", league:"nfl", round:"round1", difficulty:"easy", category:"Nicknames", prompt:"Which star running back became famous under the nickname 'Beast Mode'?", choices:["Marshawn Lynch","Adrian Peterson","LeSean McCoy","Frank Gore"], answer:"Marshawn Lynch", explanation:"Marshawn Lynch became one of football's biggest personalities under the 'Beast Mode' nickname.", sourceId:"nfl-easy-calibration" }),
  q({ id:"nfl-easy-sheriff", league:"nfl", round:"round1", difficulty:"easy", category:"Nicknames", prompt:"Which Hall of Fame quarterback was widely nicknamed 'The Sheriff'?", choices:["Peyton Manning","Brett Favre","Drew Brees","John Elway"], answer:"Peyton Manning", explanation:"Peyton Manning's command at the line of scrimmage helped make 'The Sheriff' one of his best-known nicknames.", sourceId:"nfl-easy-calibration" }),
  q({ id:"nfl-easy-broadway-joe", league:"nfl", round:"round1", difficulty:"easy", category:"Nicknames", prompt:"Which Jets legend is famously known as 'Broadway Joe'?", choices:["Joe Namath","Joe Klecko","Ken O'Brien","Mark Gastineau"], answer:"Joe Namath", explanation:"Joe Namath became 'Broadway Joe' while starring for the New York Jets.", sourceId:"nfl-easy-calibration" }),
  q({ id:"nfl-easy-monsters-midway", league:"nfl", round:"round1", difficulty:"easy", category:"Team Identity", prompt:"The nickname 'Monsters of the Midway' is most closely associated with which team?", choices:["Chicago Bears","Pittsburgh Steelers","Green Bay Packers","New York Giants"], answer:"Chicago Bears", explanation:"The 'Monsters of the Midway' nickname has long been tied to the Chicago Bears.", sourceId:"nfl-easy-calibration" }),
  q({ id:"nfl-easy-mile-high", league:"nfl", round:"round1", difficulty:"easy", category:"Stadium Culture", prompt:"Playing at 'Mile High' most commonly means visiting which NFL team?", choices:["Denver Broncos","Arizona Cardinals","Seattle Seahawks","Minnesota Vikings"], answer:"Denver Broncos", explanation:"Denver's home-field identity has long been tied to the city's Mile High altitude.", sourceId:"nfl-easy-calibration" }),
  q({ id:"nfl-easy-black-hole", league:"nfl", round:"round1", difficulty:"easy", category:"Fan Culture", prompt:"The famous fan section called the 'Black Hole' is associated with which franchise?", choices:["Las Vegas Raiders","Baltimore Ravens","New Orleans Saints","Atlanta Falcons"], answer:"Las Vegas Raiders", explanation:"Raiders fans made the intimidating 'Black Hole' section famous in Oakland.", sourceId:"nfl-easy-calibration" }),
  q({ id:"nfl-easy-gronk", league:"nfl", round:"round1", difficulty:"easy", category:"Nicknames", prompt:"Which star tight end is almost universally known simply as 'Gronk'?", choices:["Rob Gronkowski","Travis Kelce","Tony Gonzalez","Jason Witten"], answer:"Rob Gronkowski", explanation:"Rob Gronkowski's shortened surname became one of the NFL's most recognizable player nicknames.", sourceId:"nfl-easy-calibration" }),
  q({ id:"nfl-easy-28-3", league:"nfl", round:"round1", difficulty:"easy", category:"Super Bowl Moments", prompt:"New England's famous 28–3 Super Bowl comeback came against which team?", choices:["Atlanta Falcons","Seattle Seahawks","Los Angeles Rams","Carolina Panthers"], answer:"Atlanta Falcons", explanation:"The Patriots rallied from 28–3 down to beat Atlanta in overtime in Super Bowl LI.", sourceId:"nfl-easy-calibration" }),
  q({ id:"nfl-easy-pirate-ship", league:"nfl", round:"round1", difficulty:"easy", category:"Stadiums", prompt:"Which NFL team's home stadium is famous for having a giant pirate ship?", choices:["Tampa Bay Buccaneers","Las Vegas Raiders","Seattle Seahawks","Jacksonville Jaguars"], answer:"Tampa Bay Buccaneers", explanation:"Raymond James Stadium features a large pirate ship tied to the Buccaneers' theme.", sourceId:"nfl-easy-calibration" }),
  q({ id:"nfl-easy-minneapolis-miracle", league:"nfl", round:"round1", difficulty:"easy", category:"Iconic Plays", prompt:"Who caught the touchdown pass on the 'Minneapolis Miracle'?", choices:["Stefon Diggs","Adam Thielen","Kyle Rudolph","Justin Jefferson"], answer:"Stefon Diggs", explanation:"Stefon Diggs scored the walk-off touchdown that became known as the Minneapolis Miracle.", sourceId:"nfl-easy-calibration" }),
  q({ id:"nfl-easy-lambeau-leap-team", league:"nfl", round:"round1", difficulty:"easy", category:"Traditions", prompt:"The 'Lambeau Leap' touchdown celebration belongs to players from which team?", choices:["Green Bay Packers","Chicago Bears","Minnesota Vikings","Detroit Lions"], answer:"Green Bay Packers", explanation:"Packers players celebrate scores by jumping into the stands at Lambeau Field.", sourceId:"nfl-easy-calibration" }),

  // CFB — iconic programs, mascots, stadiums, and chants.
  q({ id:"cfb-easy-roll-tide", league:"cfb", round:"round1", difficulty:"easy", category:"Cheers", prompt:"The phrase 'Roll Tide' is most closely associated with which college football program?", choices:["Alabama","Georgia","Auburn","LSU"], answer:"Alabama", explanation:"'Roll Tide' is one of the most recognizable cheers tied to Alabama football.", sourceId:"cfb-easy-calibration" }),
  q({ id:"cfb-easy-uga", league:"cfb", round:"round1", difficulty:"easy", category:"Mascots", prompt:"Uga, the famous live bulldog mascot, represents which school?", choices:["Georgia","Mississippi State","Fresno State","Louisiana Tech"], answer:"Georgia", explanation:"Georgia's line of live English bulldog mascots is known by the name Uga.", sourceId:"cfb-easy-calibration" }),
  q({ id:"cfb-easy-bevo", league:"cfb", round:"round1", difficulty:"easy", category:"Mascots", prompt:"Bevo, the live longhorn mascot, belongs to which school?", choices:["Texas","Texas A&M","TCU","Texas Tech"], answer:"Texas", explanation:"Bevo is the live longhorn mascot of the University of Texas.", sourceId:"cfb-easy-calibration" }),
  q({ id:"cfb-easy-brutus", league:"cfb", round:"round1", difficulty:"easy", category:"Mascots", prompt:"Brutus Buckeye is the mascot of which Big Ten program?", choices:["Ohio State","Michigan","Penn State","Wisconsin"], answer:"Ohio State", explanation:"Brutus Buckeye is the costumed mascot associated with Ohio State athletics.", sourceId:"cfb-easy-calibration" }),
  q({ id:"cfb-easy-mike-tiger", league:"cfb", round:"round1", difficulty:"easy", category:"Mascots", prompt:"Mike the Tiger is the live mascot of which SEC school?", choices:["LSU","Auburn","Missouri","Clemson"], answer:"LSU", explanation:"LSU's live tiger mascot is traditionally known as Mike the Tiger.", sourceId:"cfb-easy-calibration" }),
  q({ id:"cfb-easy-smokey", league:"cfb", round:"round1", difficulty:"easy", category:"Mascots", prompt:"Smokey, the bluetick coonhound mascot, represents which program?", choices:["Tennessee","Kentucky","West Virginia","Virginia Tech"], answer:"Tennessee", explanation:"Tennessee's live bluetick coonhound mascot is known as Smokey.", sourceId:"cfb-easy-calibration" }),
  q({ id:"cfb-easy-reveille", league:"cfb", round:"round1", difficulty:"easy", category:"Mascots", prompt:"Reveille is the famous collie mascot of which school?", choices:["Texas A&M","Texas","Baylor","SMU"], answer:"Texas A&M", explanation:"Reveille is Texas A&M's live collie mascot and one of the school's best-known traditions.", sourceId:"cfb-easy-calibration" }),
  q({ id:"cfb-easy-touchdown-jesus", league:"cfb", round:"round1", difficulty:"easy", category:"Stadium Lore", prompt:"The mural nicknamed 'Touchdown Jesus' is associated with which football program?", choices:["Notre Dame","Boston College","USC","Michigan"], answer:"Notre Dame", explanation:"The famous mural visible near Notre Dame Stadium is widely nicknamed 'Touchdown Jesus.'", sourceId:"cfb-easy-calibration" }),
  q({ id:"cfb-easy-horseshoe", league:"cfb", round:"round1", difficulty:"easy", category:"Stadiums", prompt:"Which school plays home games in a stadium commonly called 'The Horseshoe'?", choices:["Ohio State","Georgia","Oklahoma","Nebraska"], answer:"Ohio State", explanation:"Ohio Stadium's shape helped make 'The Horseshoe' one of college football's best-known stadium nicknames.", sourceId:"cfb-easy-calibration" }),
  q({ id:"cfb-easy-white-out", league:"cfb", round:"round1", difficulty:"easy", category:"Fan Culture", prompt:"The famous all-stadium 'White Out' tradition is most associated with which school?", choices:["Penn State","Iowa","Michigan","Notre Dame"], answer:"Penn State", explanation:"Penn State's White Out games at Beaver Stadium are one of college football's signature crowd traditions.", sourceId:"cfb-easy-calibration" }),
  q({ id:"cfb-easy-go-blue", league:"cfb", round:"round1", difficulty:"easy", category:"Cheers", prompt:"The cheer 'Go Blue' is most closely associated with which program?", choices:["Michigan","Boise State","Duke","Memphis"], answer:"Michigan", explanation:"'Go Blue' is one of the most familiar cheers associated with Michigan athletics.", sourceId:"cfb-easy-calibration" }),
  q({ id:"cfb-easy-we-are", league:"cfb", round:"round1", difficulty:"easy", category:"Cheers", prompt:"Fans answering 'Penn State!' to the chant 'We Are!' are supporting which program?", choices:["Penn State","Pittsburgh","Michigan State","West Virginia"], answer:"Penn State", explanation:"'We Are... Penn State!' is one of the Nittany Lions' signature crowd chants.", sourceId:"cfb-easy-calibration" }),

  // UFC — star nicknames, iconic finishes, and basic promotion identity.
  q({ id:"ufc-easy-stylebender", league:"ufc", round:"round1", difficulty:"easy", category:"Nicknames", prompt:"Which former UFC middleweight champion is known as 'The Last Stylebender'?", choices:["Israel Adesanya","Anderson Silva","Robert Whittaker","Alex Pereira"], answer:"Israel Adesanya", explanation:"Israel Adesanya has competed throughout his UFC career as 'The Last Stylebender.'", sourceId:"ufc-easy-calibration" }),
  q({ id:"ufc-easy-bullet", league:"ufc", round:"round1", difficulty:"easy", category:"Nicknames", prompt:"Which longtime UFC champion is known by the nickname 'Bullet'?", choices:["Valentina Shevchenko","Joanna Jedrzejczyk","Rose Namajunas","Alexa Grasso"], answer:"Valentina Shevchenko", explanation:"Valentina Shevchenko has long fought under the nickname 'Bullet.'", sourceId:"ufc-easy-calibration" }),
  q({ id:"ufc-easy-diamond", league:"ufc", round:"round1", difficulty:"easy", category:"Nicknames", prompt:"Which UFC lightweight star is known as 'The Diamond'?", choices:["Dustin Poirier","Justin Gaethje","Michael Chandler","Max Holloway"], answer:"Dustin Poirier", explanation:"Dustin Poirier's long-standing fight nickname is 'The Diamond.'", sourceId:"ufc-easy-calibration" }),
  q({ id:"ufc-easy-highlight", league:"ufc", round:"round1", difficulty:"easy", category:"Nicknames", prompt:"Which former UFC interim lightweight champion is known as 'The Highlight'?", choices:["Justin Gaethje","Tony Ferguson","Dustin Poirier","Eddie Alvarez"], answer:"Justin Gaethje", explanation:"Justin Gaethje is known as 'The Highlight,' a nickname that fits his action-heavy fighting style.", sourceId:"ufc-easy-calibration" }),
  q({ id:"ufc-easy-sugar", league:"ufc", round:"round1", difficulty:"easy", category:"Nicknames", prompt:"Which UFC bantamweight star is known as 'Sugar'?", choices:["Sean O'Malley","Cory Sandhagen","Petr Yan","Marlon Vera"], answer:"Sean O'Malley", explanation:"Sean O'Malley has used the nickname 'Sugar' throughout his rise in the UFC.", sourceId:"ufc-easy-calibration" }),
  q({ id:"ufc-easy-rowdy-ronda", league:"ufc", round:"round1", difficulty:"easy", category:"Nicknames", prompt:"Which former UFC champion fought under the nickname 'Rowdy'?", choices:["Ronda Rousey","Holly Holm","Miesha Tate","Amanda Nunes"], answer:"Ronda Rousey", explanation:"Ronda Rousey was famously billed as 'Rowdy' Ronda Rousey during her championship run.", sourceId:"ufc-easy-calibration" }),
  q({ id:"ufc-easy-mighty-mouse", league:"ufc", round:"round1", difficulty:"easy", category:"Nicknames", prompt:"Which former UFC flyweight champion is famously known as 'Mighty Mouse'?", choices:["Demetrious Johnson","Henry Cejudo","Brandon Moreno","Joseph Benavidez"], answer:"Demetrious Johnson", explanation:"Demetrious Johnson became one of MMA's greatest champions while fighting as 'Mighty Mouse.'", sourceId:"ufc-easy-calibration" }),
  q({ id:"ufc-easy-fastest-ko-opponent", league:"ufc", round:"round1", difficulty:"easy", category:"Iconic Finishes", prompt:"Jorge Masvidal's record-setting five-second UFC knockout came against whom?", choices:["Ben Askren","Nate Diaz","Darren Till","Donald Cerrone"], answer:"Ben Askren", explanation:"Masvidal knocked out Ben Askren with a flying knee just five seconds into their UFC 239 bout.", sourceId:"ufc-easy-calibration" }),
  q({ id:"ufc-easy-holm-rousey", league:"ufc", round:"round1", difficulty:"easy", category:"Title Upsets", prompt:"Who shocked Ronda Rousey with a head-kick knockout to win the bantamweight title?", choices:["Holly Holm","Amanda Nunes","Miesha Tate","Valentina Shevchenko"], answer:"Holly Holm", explanation:"Holly Holm stopped Ronda Rousey with a head kick at UFC 193 to win the bantamweight title.", sourceId:"ufc-easy-calibration" }),
  q({ id:"ufc-easy-khabib-mcgregor", league:"ufc", round:"round1", difficulty:"easy", category:"Mega Fights", prompt:"Who submitted Conor McGregor in the main event of UFC 229?", choices:["Khabib Nurmagomedov","Nate Diaz","Dustin Poirier","Jose Aldo"], answer:"Khabib Nurmagomedov", explanation:"Khabib Nurmagomedov submitted McGregor in the fourth round of their UFC 229 title fight.", sourceId:"ufc-easy-calibration" }),
  q({ id:"ufc-easy-leon-usman", league:"ufc", round:"round1", difficulty:"easy", category:"Iconic Finishes", prompt:"Leon Edwards won the welterweight title with a famous head-kick knockout of which champion?", choices:["Kamaru Usman","Colby Covington","Tyron Woodley","Jorge Masvidal"], answer:"Kamaru Usman", explanation:"Leon Edwards knocked out Kamaru Usman with a late head kick at UFC 278 to win the title.", sourceId:"ufc-easy-calibration" }),
  q({ id:"ufc-easy-home-base", league:"ufc", round:"round1", difficulty:"easy", category:"Promotion Identity", prompt:"Which U.S. city is most closely associated with the UFC's longtime home base?", choices:["Las Vegas","New York","Los Angeles","Miami"], answer:"Las Vegas", explanation:"The UFC has long been headquartered in Las Vegas and has staged many of its biggest events there.", sourceId:"ufc-easy-calibration" }),
];

const CURATED_EXISTING_EASY_IDS = [
  // NFL
  "nfl-r1-lombardi",
  "nfl-r1-thanksgiving",
  "nfl-r1-frozen-tundra",
  "nfl-r1-super-bowl-i-winner",
  "nfl-r1-perfect-season",
  "nfl-r1-immaculate-reception-player",
  "nfl-r1-the-catch-receiver",
  "nfl-r1-helmet-catch-player",
  "nfl-r1-megatron",
  "nfl-r1-prime-time",
  "nfl-r1-mean-joe",
  "nfl-r1-the-bus",
  "nfl-r1-sweetness",
  "nfl-r1-the-fridge",
  "nfl-r1-purple-people-eaters",
  "nfl-r1-steel-curtain",
  "nfl-r1-legion-boom",
  "nfl-r1-bills-mafia",
  "nfl-r1-who-dat",
  "nfl-r1-who-dey",
  "nfl-r1-cheeseheads",
  "nfl-r1-skol",
  "nfl-r1-fly-eagles-fly",
  "nfl-r1-bear-down",
  "nfl-r1-keep-pounding",
  "nfl-r1-rise-up",
  "nfl-r1-raider-nation",
  "nfl-r1-12s-seattle",
  "nfl-r2-terrible-towel",
  "nfl-r2-philly-special",

  // CFB
  "cfb-r1-big-house",
  "cfb-r1-12th-man",
  "cfb-r1-howards-rock",
  "cfb-r1-red-river",
  "cfb-r1-swamp",
  "cfb-r1-traveler",
  "cfb-r1-osceola-renegade",
  "cfb-r1-the-grove",
  "cfb-r1-hawkeye-wave",
  "cfb-r1-blue-turf",
  "cfb-r1-first-cfp-champion",
  "cfb-r1-granddaddy",
  "cfb-r1-toomers-corner",
  "cfb-r1-midnight-yell",
  "cfb-r1-cowbells",
  "cfb-r1-country-roads",
  "cfb-r1-gator-chomp",
  "cfb-r1-hook-em",
  "cfb-r1-war-eagle-flight",
  "cfb-r1-between-hedges",
  "cfb-r1-stanford-tree",
  "cfb-r1-miami-smoke",
  "cfb-r1-rammer-jammer",
  "cfb-r1-script-ohio",
  "cfb-r1-rocky-top",
  "cfb-r1-boomer-sooner",
  "cfb-r1-masked-rider",
  "cfb-r2-champion-sign",
  "cfb-r2-enter-sandman",
  "cfb-r2-jump-around",
  "cfb-r2-call-hogs",
  "cfb-r2-sooner-schooner",

  // UFC
  "ufc-r1-ufc1-winner",
  "ufc-r1-eight-sides",
  "ufc-r1-its-time",
  "ufc-r1-tuf1-lhw",
  "ufc-r1-notorious",
  "ufc-r1-bones",
  "ufc-r1-rush",
  "ufc-r1-spider",
  "ufc-r1-blessed",
  "ufc-r1-cowboy",
  "ufc-r1-thug-rose",
  "ufc-r1-fight-island-location",
  "ufc-r1-black-beast",
  "ufc-r1-khabib-eagle",
  "ufc-r1-poatan",
  "ufc-r1-big-john",
  "ufc-r1-herb-dean",
  "ufc-r1-voice-octagon",
  "ufc-r1-rogan-role",
  "ufc-r1-anik-role",
  "ufc-r1-ufc205-venue",
  "ufc-r1-do-bronx",
  "ufc-r1-the-reaper",
  "ufc-r1-magnum",
  "ufc-r2-double-champ",
  "ufc-r2-first-bmf",
  "ufc-r2-korean-zombie",
  "ufc-r2-first-city",
  "ufc-r2-ufc100",
] as const;

export const BAR_TRIVIA_EASY_QUESTION_IDS = new Set<string>([
  ...CURATED_EXISTING_EASY_IDS,
  ...BAR_TRIVIA_EASY_EXPANSION.map((question) => question.id),
]);
