import { barTriviaQuestion, type BarTriviaQuestion } from "../games/barTriviaEngine";

const UFC30 = "https://www.ufc.com/30";
const HOF = "https://www.ufc.com/news/ufc-hall-fame-faq";
const LW = "https://www.ufc.com/news/ufc-lightweight-title-lineage-khabib-mcgregor-penn-poirier-oliveira";
const MW = "https://www.ufc.com/news/ufc-middleweight-title-lineage-adesanya-whittaker-GSP-bisping-silva-history";
const TUF1 = "https://www.ufc.com/news/celebrating-10-years-ultimate-fighter";
const UFC217 = "https://www.ufc.com/news/ufc-217-talking-points-gsp-goat-dillashaw-namajunas-become-champs";
const BRAZIL = "https://www.ufc.com/news/first-ufc-event-brazil-ultimate-brazil-1998";
const ALDOWEC = "https://www.ufc.com/news/ufc-adds-new-weight-divisions";

function q(seed: Parameters<typeof barTriviaQuestion>[0]) {
  return barTriviaQuestion({ ...seed, verifiedAt: "2026-09-28" });
}

export const BAR_TRIVIA_UFC_EVERGREEN_WAVE_3: readonly BarTriviaQuestion[] = [
  // Round 1 — famous champions, upsets and milestone cards
  q({ id:"ufc-r1-weidman-silva", league:"ufc", round:"round1", category:"Famous Upsets", prompt:"Who handed Anderson Silva his first UFC loss and took the middleweight title?", choices:["Chris Weidman","Chael Sonnen","Vitor Belfort","Rich Franklin"], answer:"Chris Weidman", explanation:"Chris Weidman knocked out Anderson Silva at UFC 162 to end Silva's historic title reign.", sourceId:"ufc-weidman-silva" }),
  q({ id:"ufc-r1-serra-gsp", league:"ufc", round:"round1", category:"Famous Upsets", prompt:"Who shocked Georges St-Pierre to win the welterweight title at UFC 69?", choices:["Matt Serra","Matt Hughes","BJ Penn","Josh Koscheck"], answer:"Matt Serra", explanation:"Matt Serra stopped Georges St-Pierre in one of the biggest title upsets in UFC history.", sourceId:"ufc-serra-gsp" }),
  q({ id:"ufc-r1-jones-youngest", league:"ufc", round:"round1", category:"Championship Firsts", prompt:"Who became the youngest champion in UFC history?", choices:["Jon Jones","Jose Aldo","Vitor Belfort","BJ Penn"], answer:"Jon Jones", explanation:"Jon Jones won the light heavyweight title at age 23 by defeating Mauricio 'Shogun' Rua.", sourceId:"ufc-jones-youngest" }),
  q({ id:"ufc-r1-couture-two-divisions", league:"ufc", round:"round1", category:"Championship Firsts", prompt:"Who became the first fighter to win UFC championships in two different weight classes?", choices:["Randy Couture","BJ Penn","Conor McGregor","Georges St-Pierre"], answer:"Randy Couture", explanation:"Randy Couture won UFC titles at heavyweight and light heavyweight.", sourceId:"ufc-couture-history" }),
  q({ id:"ufc-r1-ufc217-three-champs", league:"ufc", round:"round1", category:"Milestone Events", prompt:"Which event featured three title fights and saw all three championships change hands?", choices:["UFC 217","UFC 205","UFC 200","UFC 232"], answer:"UFC 217", explanation:"Rose Namajunas, TJ Dillashaw and Georges St-Pierre all won titles at UFC 217.", sourceId:"ufc217", sourceUrl:UFC217 }),
  q({ id:"ufc-r1-ufc205-double-champ", league:"ufc", round:"round1", category:"Milestone Events", prompt:"Conor McGregor became the UFC's first simultaneous two-division champion by beating whom at UFC 205?", choices:["Eddie Alvarez","Jose Aldo","Nate Diaz","Khabib Nurmagomedov"], answer:"Eddie Alvarez", explanation:"McGregor stopped Eddie Alvarez to add the lightweight belt to his featherweight title.", sourceId:"ufc205-history" }),
  q({ id:"ufc-r1-nunes-first-double-woman", league:"ufc", round:"round1", category:"Championship Firsts", prompt:"Who became the first woman to hold UFC titles in two divisions at the same time?", choices:["Amanda Nunes","Valentina Shevchenko","Cris Cyborg","Ronda Rousey"], answer:"Amanda Nunes", explanation:"Amanda Nunes added the featherweight title to her bantamweight belt by knocking out Cris Cyborg.", sourceId:"ufc-nunes-double-champ" }),
  q({ id:"ufc-r1-pulver-first-lightweight", league:"ufc", round:"round1", category:"Championship Origins", prompt:"Who became the UFC's first lightweight champion?", choices:["Jens Pulver","BJ Penn","Caol Uno","Frankie Edgar"], answer:"Jens Pulver", explanation:"Jens Pulver defeated Caol Uno at UFC 30 to win the inaugural 155-pound championship.", sourceId:"ufc-lightweight-lineage", sourceUrl:LW }),
  q({ id:"ufc-r1-menne-first-middleweight", league:"ufc", round:"round1", category:"Championship Origins", prompt:"Who became the UFC's first middleweight champion?", choices:["Dave Menne","Rich Franklin","Murilo Bustamante","Anderson Silva"], answer:"Dave Menne", explanation:"Dave Menne defeated Gil Castillo at UFC 33 to win the inaugural middleweight championship.", sourceId:"ufc-middleweight-lineage", sourceUrl:MW }),
  q({ id:"ufc-r1-miletich-first-welterweight", league:"ufc", round:"round1", category:"Championship Origins", prompt:"Who won the UFC's first welterweight championship?", choices:["Pat Miletich","Matt Hughes","Carlos Newton","Frank Trigg"], answer:"Pat Miletich", explanation:"Pat Miletich beat Mikey Burnett at Ultimate Brazil in 1998 for the inaugural welterweight title.", sourceId:"ufc-first-brazil", sourceUrl:BRAZIL }),
  q({ id:"ufc-r1-cruz-first-bantamweight", league:"ufc", round:"round1", category:"Championship Origins", prompt:"Who became the UFC's inaugural bantamweight champion when the WEC merged into UFC?", choices:["Dominick Cruz","Urijah Faber","Renan Barao","Miguel Torres"], answer:"Dominick Cruz", explanation:"WEC champion Dominick Cruz was recognized as the inaugural UFC bantamweight champion.", sourceId:"ufc-new-weight-divisions", sourceUrl:ALDOWEC }),
  q({ id:"ufc-r1-aldo-first-featherweight", league:"ufc", round:"round1", category:"Championship Origins", prompt:"Who became the UFC's inaugural featherweight champion when the WEC merged into UFC?", choices:["Jose Aldo","Chad Mendes","Urijah Faber","Frankie Edgar"], answer:"Jose Aldo", explanation:"WEC featherweight champion Jose Aldo was recognized as UFC's first featherweight champion.", sourceId:"ufc-new-weight-divisions", sourceUrl:ALDOWEC }),
  q({ id:"ufc-r1-tuf1-coaches", league:"ufc", round:"round1", category:"The Ultimate Fighter", prompt:"Which two UFC legends coached the first season of The Ultimate Fighter?", choices:["Chuck Liddell and Randy Couture","Tito Ortiz and Ken Shamrock","Matt Hughes and Rich Franklin","BJ Penn and Jens Pulver"], answer:"Chuck Liddell and Randy Couture", explanation:"Chuck Liddell and Randy Couture coached opposite teams on the landmark first season in 2005.", sourceId:"tuf1-history", sourceUrl:TUF1 }),
  q({ id:"ufc-r1-tuf1-important-fight", league:"ufc", round:"round1", category:"The Ultimate Fighter", prompt:"Which fight did Dana White repeatedly call the most important in UFC history?", choices:["Forrest Griffin vs. Stephan Bonnar","Chuck Liddell vs. Tito Ortiz","Royce Gracie vs. Ken Shamrock","Anderson Silva vs. Chael Sonnen"], answer:"Forrest Griffin vs. Stephan Bonnar", explanation:"Their TUF 1 Finale war is credited with helping launch UFC into the mainstream.", sourceId:"tuf1-history", sourceUrl:TUF1 }),
  q({ id:"ufc-r1-first-brazil-card", league:"ufc", round:"round1", category:"International History", prompt:"The UFC's first event in Brazil was held in which city?", choices:["Sao Paulo","Rio de Janeiro","Brasilia","Curitiba"], answer:"Sao Paulo", explanation:"Ultimate Brazil took place in Sao Paulo in October 1998.", sourceId:"ufc-first-brazil", sourceUrl:BRAZIL }),

  // Round 2 — title lineages, landmark seasons and memorable finishes
  q({ id:"ufc-r2-pulver-opponent", league:"ufc", round:"round2", category:"Championship Origins", prompt:"Jens Pulver defeated whom to become the UFC's first lightweight champion?", choices:["Caol Uno","BJ Penn","Dennis Hallman","Matt Serra"], answer:"Caol Uno", explanation:"Pulver won a decision over Caol Uno at UFC 30.", sourceId:"ufc-lightweight-lineage", sourceUrl:LW }),
  q({ id:"ufc-r2-menne-opponent", league:"ufc", round:"round2", category:"Championship Origins", prompt:"Dave Menne defeated whom to win the UFC's first middleweight championship?", choices:["Gil Castillo","Murilo Bustamante","Rich Franklin","Carlos Newton"], answer:"Gil Castillo", explanation:"Menne defeated Gil Castillo at UFC 33 to become the inaugural middleweight champion.", sourceId:"ufc-middleweight-lineage", sourceUrl:MW }),
  q({ id:"ufc-r2-miletich-opponent", league:"ufc", round:"round2", category:"Championship Origins", prompt:"Pat Miletich defeated whom to win the UFC's first welterweight title?", choices:["Mikey Burnett","Carlos Newton","Matt Hughes","Frank Trigg"], answer:"Mikey Burnett", explanation:"Miletich won a split decision over Mikey Burnett at Ultimate Brazil.", sourceId:"ufc-first-brazil", sourceUrl:BRAZIL }),
  q({ id:"ufc-r2-ufc30-zuffa-first", league:"ufc", round:"round2", category:"Business History", prompt:"Which numbered event was the first UFC show under Zuffa ownership?", choices:["UFC 30","UFC 28","UFC 32","UFC 33"], answer:"UFC 30", explanation:"UFC 30 in Atlantic City was the first event under the new Zuffa ownership group.", sourceId:"ufc30-history", sourceUrl:UFC30 }),
  q({ id:"ufc-r2-bustamante-first-brazilian-champ", league:"ufc", round:"round2", category:"Global Firsts", prompt:"Who became the first Brazilian fighter to wear UFC championship gold?", choices:["Murilo Bustamante","Royce Gracie","Vitor Belfort","Anderson Silva"], answer:"Murilo Bustamante", explanation:"Bustamante beat Dave Menne for the middleweight title in 2002, becoming the first Brazilian UFC champion.", sourceId:"ufc-bustamante" }),
  q({ id:"ufc-r2-gsp-middleweight", league:"ufc", round:"round2", category:"Two-Division Champions", prompt:"Georges St-Pierre returned from a four-year layoff at UFC 217 to win the middleweight title from whom?", choices:["Michael Bisping","Luke Rockhold","Robert Whittaker","Chris Weidman"], answer:"Michael Bisping", explanation:"St-Pierre submitted Michael Bisping at UFC 217 to become a two-division champion.", sourceId:"ufc217", sourceUrl:UFC217 }),
  q({ id:"ufc-r2-rose-ufc217", league:"ufc", round:"round2", category:"Famous Upsets", prompt:"Rose Namajunas won her first UFC title at UFC 217 by stopping which dominant champion?", choices:["Joanna Jedrzejczyk","Carla Esparza","Jessica Andrade","Zhang Weili"], answer:"Joanna Jedrzejczyk", explanation:"Namajunas shocked Joanna Jedrzejczyk with a first-round TKO.", sourceId:"ufc217", sourceUrl:UFC217 }),
  q({ id:"ufc-r2-dillashaw-ufc217", league:"ufc", round:"round2", category:"Title Changes", prompt:"TJ Dillashaw regained the bantamweight title at UFC 217 by stopping whom?", choices:["Cody Garbrandt","Dominick Cruz","Renan Barao","John Lineker"], answer:"Cody Garbrandt", explanation:"Dillashaw stopped former teammate Cody Garbrandt in the second round.", sourceId:"ufc217", sourceUrl:UFC217 }),
  q({ id:"ufc-r2-jones-rua", league:"ufc", round:"round2", category:"Championship Moments", prompt:"Jon Jones became the UFC's youngest champion by defeating which light heavyweight champion?", choices:["Mauricio 'Shogun' Rua","Lyoto Machida","Rashad Evans","Quinton Jackson"], answer:"Mauricio 'Shogun' Rua", explanation:"Jones stopped Shogun Rua at UFC 128 to win the light heavyweight championship.", sourceId:"ufc-jones-youngest" }),
  q({ id:"ufc-r2-first-womens-flyweight", league:"ufc", round:"round2", category:"Championship Origins", prompt:"Who became the UFC's inaugural women's flyweight champion?", choices:["Nicco Montano","Valentina Shevchenko","Rose Namajunas","Joanna Jedrzejczyk"], answer:"Nicco Montano", explanation:"Nicco Montano won the inaugural women's flyweight title at The Ultimate Fighter 26 Finale.", sourceId:"ufc-womens-flyweight-history" }),
  q({ id:"ufc-r2-tuf20-purpose", league:"ufc", round:"round2", category:"The Ultimate Fighter", prompt:"What made The Ultimate Fighter 20 unique?", choices:["It crowned the inaugural women's strawweight champion","It featured only heavyweight fighters","It had no coaches","It was filmed entirely in Brazil"], answer:"It crowned the inaugural women's strawweight champion", explanation:"TUF 20's tournament determined the first UFC women's strawweight champion.", sourceId:"tuf20-history" }),
  q({ id:"ufc-r2-tuf18-first", league:"ufc", round:"round2", category:"The Ultimate Fighter", prompt:"What was a first for The Ultimate Fighter 18?", choices:["Men and women competed on the same season","It crowned a UFC champion","There were no coaches","Every fight was live"], answer:"Men and women competed on the same season", explanation:"TUF 18 featured male bantamweights and female bantamweights together.", sourceId:"tuf18-history" }),
  q({ id:"ufc-r2-tuf18-coaches", league:"ufc", round:"round2", category:"The Ultimate Fighter", prompt:"Which rivals coached The Ultimate Fighter 18?", choices:["Ronda Rousey and Miesha Tate","Joanna Jedrzejczyk and Claudia Gadelha","Conor McGregor and Urijah Faber","Tito Ortiz and Ken Shamrock"], answer:"Ronda Rousey and Miesha Tate", explanation:"Rousey and Tate coached the first TUF season featuring women.", sourceId:"tuf18-history" }),
  q({ id:"ufc-r2-ufc243-main", league:"ufc", round:"round2", category:"Milestone Events", prompt:"Which middleweight title fight headlined UFC 243 in Melbourne?", choices:["Robert Whittaker vs. Israel Adesanya","Anderson Silva vs. Israel Adesanya","Israel Adesanya vs. Yoel Romero","Robert Whittaker vs. Yoel Romero"], answer:"Robert Whittaker vs. Israel Adesanya", explanation:"Adesanya unified the middleweight title by knocking out Robert Whittaker.", sourceId:"ufc243-history" }),
  q({ id:"ufc-r2-ufc229-main", league:"ufc", round:"round2", category:"Milestone Events", prompt:"Which rivalry headlined UFC 229?", choices:["Khabib Nurmagomedov vs. Conor McGregor","Conor McGregor vs. Nate Diaz","Jon Jones vs. Daniel Cormier","Jorge Masvidal vs. Nate Diaz"], answer:"Khabib Nurmagomedov vs. Conor McGregor", explanation:"Khabib submitted McGregor in the fourth round of UFC 229.", sourceId:"ufc229-history" }),

  // Round 3 — deeper title history and landmark-event knowledge
  q({ id:"ufc-r3-ufc30-city", league:"ufc", round:"round3", category:"Milestone Events", prompt:"UFC 30, the first event under Zuffa ownership, was held in which city?", choices:["Atlantic City","Las Vegas","New York City","Denver"], answer:"Atlantic City", explanation:"UFC 30 took place in Atlantic City, New Jersey in February 2001.", sourceId:"ufc30-history", sourceUrl:LW }),
  q({ id:"ufc-r3-pulver-title-old-name", league:"ufc", round:"round3", category:"Division History", prompt:"When Jens Pulver won his 155-pound title at UFC 30, the division was initially called what?", choices:["Bantamweight","Lightweight","Junior welterweight","Super lightweight"], answer:"Bantamweight", explanation:"The 155-pound division was called bantamweight at UFC 30 before being renamed lightweight.", sourceId:"ufc-pulver-hof" }),
  q({ id:"ufc-r3-cruz-wec53", league:"ufc", round:"round3", category:"Division History", prompt:"Dominick Cruz became the inaugural UFC bantamweight champion at the final event of which promotion?", choices:["WEC","Strikeforce","PRIDE","Affliction"], answer:"WEC", explanation:"Cruz defended the WEC belt at WEC 53 and was recognized as the first UFC bantamweight champion as the promotions merged.", sourceId:"ufc-cruz-history", sourceUrl:ALDOWEC }),
  q({ id:"ufc-r3-aldo-promoted", league:"ufc", round:"round3", category:"Division History", prompt:"Jose Aldo entered UFC as champion of which promotion?", choices:["WEC","PRIDE","Strikeforce","Bellator"], answer:"WEC", explanation:"The reigning WEC featherweight champion was promoted into UFC as its inaugural 145-pound champion.", sourceId:"ufc-new-weight-divisions", sourceUrl:ALDOWEC }),
  q({ id:"ufc-r3-first-brazil-event-name", league:"ufc", round:"round3", category:"International History", prompt:"What was the name of UFC's first event in Brazil?", choices:["Ultimate Brazil","UFC Rio","Brazilian Brawl","Vale Tudo Brazil"], answer:"Ultimate Brazil", explanation:"The October 1998 Sao Paulo card was branded Ultimate Brazil.", sourceId:"ufc-first-brazil", sourceUrl:BRAZIL }),
  q({ id:"ufc-r3-belfort-wanderlei", league:"ufc", round:"round3", category:"Iconic Finishes", prompt:"At Ultimate Brazil in 1998, Vitor Belfort stopped which future PRIDE legend in 44 seconds?", choices:["Wanderlei Silva","Mauricio Rua","Antonio Rodrigo Nogueira","Ricardo Arona"], answer:"Wanderlei Silva", explanation:"Belfort blitzed Wanderlei Silva with straight punches in one of his most famous early wins.", sourceId:"ufc-first-brazil", sourceUrl:BRAZIL }),
  q({ id:"ufc-r3-gsp-ufc217-method", league:"ufc", round:"round3", category:"Title Changes", prompt:"How did Georges St-Pierre finish Michael Bisping at UFC 217?", choices:["Rear-naked choke","Unanimous decision","Head-kick knockout","Armbar"], answer:"Rear-naked choke", explanation:"St-Pierre hurt Bisping on the feet and then secured a rear-naked choke in round three.", sourceId:"ufc217", sourceUrl:UFC217 }),
  q({ id:"ufc-r3-rose-ufc217-round", league:"ufc", round:"round3", category:"Famous Upsets", prompt:"Rose Namajunas stopped Joanna Jedrzejczyk in which round at UFC 217?", choices:["First","Second","Third","Fifth"], answer:"First", explanation:"Namajunas scored a stunning first-round TKO to win the strawweight title.", sourceId:"ufc217", sourceUrl:UFC217 }),
  q({ id:"ufc-r3-tuf1-team-winner", league:"ufc", round:"round3", category:"The Ultimate Fighter", prompt:"Forrest Griffin, winner of TUF 1's light heavyweight bracket, was coached by whom?", choices:["Chuck Liddell","Randy Couture","Tito Ortiz","Ken Shamrock"], answer:"Chuck Liddell", explanation:"Griffin fought for Team Liddell on the inaugural season.", sourceId:"tuf1-history", sourceUrl:TUF1 }),
  q({ id:"ufc-r3-tuf1-other-winner", league:"ufc", round:"round3", category:"The Ultimate Fighter", prompt:"Diego Sanchez won which weight-class tournament on The Ultimate Fighter 1?", choices:["Middleweight","Welterweight","Lightweight","Light heavyweight"], answer:"Middleweight", explanation:"The first TUF season featured light heavyweight and middleweight tournaments.", sourceId:"tuf1-history", sourceUrl:TUF1 }),
  q({ id:"ufc-r3-first-welterweight-location", league:"ufc", round:"round3", category:"Championship Origins", prompt:"The first UFC welterweight championship was decided at an event in which country?", choices:["Brazil","United States","Japan","Canada"], answer:"Brazil", explanation:"Pat Miletich won the inaugural belt at Ultimate Brazil in Sao Paulo.", sourceId:"ufc-first-brazil", sourceUrl:BRAZIL }),
  q({ id:"ufc-r3-menne-next-champ", league:"ufc", round:"round3", category:"Title Lineage", prompt:"Who defeated inaugural middleweight champion Dave Menne to take the belt?", choices:["Murilo Bustamante","Rich Franklin","Evan Tanner","Anderson Silva"], answer:"Murilo Bustamante", explanation:"Murilo Bustamante stopped Menne at UFC 35.", sourceId:"ufc-middleweight-lineage", sourceUrl:MW }),
  q({ id:"ufc-r3-pulver-vacated", league:"ufc", round:"round3", category:"Title Lineage", prompt:"What happened to the UFC lightweight title after Jens Pulver left the promotion in 2002?", choices:["It was vacated","BJ Penn was automatically awarded it","The division merged with welterweight","Caol Uno was named champion"], answer:"It was vacated", explanation:"Pulver left UFC and the lightweight title became vacant.", sourceId:"ufc-lightweight-lineage", sourceUrl:LW }),
  q({ id:"ufc-r3-ufc41-draw", league:"ufc", round:"round3", category:"Title Oddities", prompt:"Which two fighters fought to a draw for the vacant lightweight title at UFC 41?", choices:["BJ Penn and Caol Uno","Matt Serra and Din Thomas","Jens Pulver and BJ Penn","Caol Uno and Matt Serra"], answer:"BJ Penn and Caol Uno", explanation:"Their five-round draw left the lightweight championship vacant.", sourceId:"ufc-lightweight-lineage", sourceUrl:LW }),
  q({ id:"ufc-r3-first-lightweight-zuffa", league:"ufc", round:"round3", category:"Milestone Events", prompt:"UFC 30 featured the inaugural lightweight title and was also the first event under which ownership group?", choices:["Zuffa","SEG","Endeavor","TKO"], answer:"Zuffa", explanation:"UFC 30 marked the beginning of the Zuffa era.", sourceId:"ufc30-history" }),
  q({ id:"ufc-r3-ufc217-location", league:"ufc", round:"round3", category:"Venues", prompt:"UFC 217's three title changes happened at which famous arena?", choices:["Madison Square Garden","MGM Grand Garden Arena","T-Mobile Arena","TD Garden"], answer:"Madison Square Garden", explanation:"The landmark 2017 event took place at Madison Square Garden in New York.", sourceId:"ufc217", sourceUrl:UFC217 }),
  q({ id:"ufc-r3-first-bantam-nonufc-event", league:"ufc", round:"round3", category:"Division Oddities", prompt:"The inaugural UFC bantamweight championship was decided during an event that was officially promoted by which organization?", choices:["WEC","UFC","Strikeforce","PRIDE"], answer:"WEC", explanation:"Cruz's WEC 53 win was simultaneously recognized as the inaugural UFC bantamweight championship because of the merger.", sourceId:"ufc-cruz-history" }),
  q({ id:"ufc-r3-bustamante-next-fight", league:"ufc", round:"round3", category:"Championship History", prompt:"Murilo Bustamante became middleweight champion by defeating which inaugural titleholder?", choices:["Dave Menne","Rich Franklin","Evan Tanner","Carlos Newton"], answer:"Dave Menne", explanation:"Bustamante stopped Dave Menne at UFC 35.", sourceId:"ufc-middleweight-lineage", sourceUrl:MW }),
  q({ id:"ufc-r3-first-womens-main-event", league:"ufc", round:"round3", category:"Women's MMA", prompt:"The first women's fight in UFC history was also the main event of which numbered card?", choices:["UFC 157","UFC 170","UFC 184","UFC 193"], answer:"UFC 157", explanation:"Ronda Rousey vs. Liz Carmouche headlined UFC 157.", sourceId:"ufc-womens-history" }),
  q({ id:"ufc-r3-nunes-ufc232-opponent", league:"ufc", round:"round3", category:"Champ-Champ Moments", prompt:"Amanda Nunes became a simultaneous two-division champion at which event?", choices:["UFC 232","UFC 200","UFC 245","UFC 239"], answer:"UFC 232", explanation:"Nunes knocked out Cris Cyborg at UFC 232 to win the featherweight title while holding the bantamweight belt.", sourceId:"ufc-nunes-double-champ" }),

  // Last Call — deep but memorable
  q({ id:"ufc-final-first-lightweight-event", league:"ufc", round:"last-call", category:"Championship Origins", prompt:"At which event was the inaugural UFC lightweight championship decided?", choices:["UFC 30","UFC 28","UFC 33","UFC 35"], answer:"UFC 30", explanation:"Jens Pulver beat Caol Uno at UFC 30 for the first 155-pound championship.", sourceId:"ufc-lightweight-lineage", sourceUrl:LW }),
  q({ id:"ufc-final-first-middleweight-event", league:"ufc", round:"last-call", category:"Championship Origins", prompt:"At which event was the inaugural UFC middleweight championship decided?", choices:["UFC 33","UFC 30","UFC 35","UFC 37"], answer:"UFC 33", explanation:"Dave Menne beat Gil Castillo at UFC 33.", sourceId:"ufc-middleweight-lineage", sourceUrl:MW }),
  q({ id:"ufc-final-first-welterweight-event", league:"ufc", round:"last-call", category:"Championship Origins", prompt:"The inaugural UFC welterweight title was decided at which 1998 event?", choices:["Ultimate Brazil","UFC 18","UFC Japan","UFC 17"], answer:"Ultimate Brazil", explanation:"Pat Miletich beat Mikey Burnett at Ultimate Brazil for the first welterweight belt.", sourceId:"ufc-first-brazil", sourceUrl:BRAZIL }),
  q({ id:"ufc-final-ufc217-title-winners", league:"ufc", round:"last-call", category:"Milestone Events", prompt:"Which trio all won UFC titles at UFC 217?", choices:["Rose Namajunas, TJ Dillashaw and Georges St-Pierre","Joanna Jedrzejczyk, Cody Garbrandt and Michael Bisping","Rose Namajunas, Cody Garbrandt and Georges St-Pierre","TJ Dillashaw, Robert Whittaker and Rose Namajunas"], answer:"Rose Namajunas, TJ Dillashaw and Georges St-Pierre", explanation:"All three challengers captured titles on the same historic card.", sourceId:"ufc217", sourceUrl:UFC217 }),
  q({ id:"ufc-final-tuf1-coach-liddell", league:"ufc", round:"last-call", category:"The Ultimate Fighter", prompt:"Which TUF 1 coach had both tournament winners come from his team?", choices:["Chuck Liddell","Randy Couture","Both coaches had one winner","Neither coach"], answer:"Chuck Liddell", explanation:"Forrest Griffin and Diego Sanchez both emerged from Team Liddell to win their brackets.", sourceId:"tuf1-history", sourceUrl:TUF1 }),
];
