import { expandSportsFeudFamilies } from "./sportsFeudAuthoredHelpers";

export const CFB_SPORTS_FEUD_FAST_3 = expandSportsFeudFamilies("cfb-fast3", [
  {
    category: "coaches",
    entityKind: "person",
    collisionGroup: "coaches",
    prompts: [
      "Name a coach who won a college football national championship from 2000 through 2024.",
      "Name a national-title-winning college football coach from the 2000 through 2024 seasons.",
      "Name a coach you remember winning a college football championship between 2000 and 2024.",
      "Name a college coach whose résumé includes a national title from 2000 through 2024.",
      "Name a championship coach from the 2000 through 2024 college football seasons.",
    ],
    answers: [
      "Nick Saban",
      "Kirby Smart",
      "Urban Meyer",
      "Dabo Swinney",
      "Pete Carroll",
      "Jim Harbaugh",
      "Mack Brown",
      "Bob Stoops",
    ],
    alsoAcceptedAnswers: ["Larry Coker", "Jim Tressel", "Les Miles", "Gene Chizik", "Jimbo Fisher", "Ed Orgeron", "Ryan Day"],
  },
  {
    category: "coaches",
    entityKind: "person",
    collisionGroup: "coaches",
    prompts: [
      "Name an offensive-minded college football coach.",
      "Name a college coach known for creative offense.",
      "Name a coach whose scheme became part of his reputation.",
      "Name a college coach you associate with explosive offense.",
      "Name a coach whose playbook changed how people talked about offense.",
    ],
    answers: [
      "Steve Spurrier",
      "Mike Leach",
      "Chip Kelly",
      "Lincoln Riley",
      "Gus Malzahn",
      "Lane Kiffin",
      "Hal Mumme",
      "Rich Rodriguez",
    ],
    alsoAcceptedAnswers: ["Josh Heupel", "Kliff Kingsbury", "Jeff Brohm", "Paul Johnson", "June Jones", "Bobby Petrino", "Kevin Sumlin"],
  },
  {
    category: "coaches",
    entityKind: "person",
    collisionGroup: "coaches",
    prompts: [
      "Name a college football coach strongly associated with defense.",
      "Name a coach whose teams were known for being hard to score on.",
      "Name a college coach with a defensive identity.",
      "Name a coach you would trust to build an elite college defense.",
      "Name a coach whose best teams were famous for physical defense.",
    ],
    answers: [
      "Nick Saban",
      "Kirby Smart",
      "Jim Tressel",
      "Mark Dantonio",
      "Pat Narduzzi",
      "Brent Venables",
      "Dave Aranda",
      "Bud Foster",
    ],
    alsoAcceptedAnswers: ["Frank Beamer", "Will Muschamp", "Dan Lanning", "Marcus Freeman", "Manny Diaz", "Charlie Strong"],
  },
  {
    category: "rivalries",
    entityKind: "other",
    collisionGroup: "rivalries",
    prompts: [
      "Name a famous college football rivalry.",
      "Name a rivalry game that can split a state or region.",
      "Name a college matchup fans circle months in advance.",
      "Name a rivalry where bragging rights last all year.",
      "Name a college football rivalry a casual fan might recognize.",
    ],
    answers: [
      "Ohio State-Michigan",
      "Alabama-Auburn",
      "Texas-Oklahoma",
      "Army-Navy",
      "USC-Notre Dame",
      "Florida-Georgia",
      "Florida State-Miami",
      "Oregon-Washington",
    ],
    alsoAcceptedAnswers: [
      "Georgia-Auburn",
      "Clemson-South Carolina",
      "Michigan-Michigan State",
      "BYU-Utah",
      "Washington-Washington State",
      "Ole Miss-Mississippi State",
      "Iowa-Iowa State",
      "Harvard-Yale",
    ],
  },
  {
    category: "venues",
    entityKind: "other",
    collisionGroup: "venues",
    prompts: [
      "Name a college football stadium known for being loud.",
      "Name a stadium where a road offense can barely hear itself.",
      "Name a college venue famous for a hostile atmosphere.",
      "Name a stadium you would expect on a loudest-in-college-football list.",
      "Name a home field where crowd noise feels like a real advantage.",
    ],
    answers: [
      { name: "Tiger Stadium", aliases: ["LSU", "LSU Tigers", "Tiger Stadium LSU"] },
      { name: "Beaver Stadium", aliases: ["Penn State", "Nittany Lions"] },
      { name: "Neyland Stadium", aliases: ["Neyland", "Tennessee", "Vols", "Volunteers"] },
      { name: "Kyle Field", aliases: ["Texas A&M", "A&M", "Aggies", "TAMU"] },
      { name: "Autzen Stadium", aliases: ["Autzen", "Oregon", "Ducks"] },
      { name: "Ohio Stadium", aliases: ["Ohio State", "OSU", "Buckeyes", "The Horseshoe", "Horseshoe"] },
      { name: "Sanford Stadium", aliases: ["Sanford", "Georgia", "UGA", "Bulldogs"] },
      { name: "Memorial Stadium Clemson", aliases: ["Clemson", "Clemson Tigers", "Death Valley Clemson"] },
    ],
    alsoAcceptedAnswers: [
      { name: "Michigan Stadium", aliases: ["Michigan", "Wolverines", "Big House", "The Big House"] },
      { name: "Jordan-Hare Stadium", aliases: ["Auburn", "Auburn Tigers", "Jordan-Hare", "Jordan Hare"] },
      { name: "Ben Hill Griffin Stadium", aliases: ["Florida", "Gators", "The Swamp"] },
      { name: "Lane Stadium", aliases: ["Virginia Tech", "VT", "Hokies"] },
      { name: "Husky Stadium", aliases: ["Washington", "UW", "Huskies"] },
      { name: "Memorial Stadium Nebraska", aliases: ["Nebraska", "Huskers", "Cornhuskers"] },
      { name: "Kinnick Stadium", aliases: ["Iowa", "Hawkeyes", "Kinnick"] },
    ],
  },
  {
    category: "bowls",
    entityKind: "other",
    collisionGroup: "bowls",
    prompts: [
      "Name a college football bowl game.",
      "Name a bowl every college football fan has heard of.",
      "Name a postseason bowl with a long football history.",
      "Name a bowl you would expect to host a major matchup.",
      "Name a bowl game that sounds like a big deal on the schedule.",
    ],
    answers: ["Rose Bowl", "Sugar Bowl", "Orange Bowl", "Cotton Bowl", "Fiesta Bowl", "Peach Bowl", "Citrus Bowl", "Gator Bowl"],
    alsoAcceptedAnswers: ["Alamo Bowl", "Holiday Bowl", "Sun Bowl", "Liberty Bowl", "Music City Bowl", "Independence Bowl"],
  },
  {
    category: "traditions",
    entityKind: "other",
    collisionGroup: "traditions",
    prompts: [
      "Name a famous college football mascot or live mascot.",
      "Name a mascot strongly tied to a college football program.",
      "Name a college mascot fans would recognize without the school name.",
      "Name a mascot that adds to the Saturday atmosphere.",
      "Name a college football mascot that feels iconic.",
    ],
    answers: ["Uga", "Bevo", "Mike the Tiger", "Traveler", "Ralphie", "Sooner Schooner", "Brutus Buckeye", "The Oregon Duck"],
    alsoAcceptedAnswers: ["Smokey", "Reveille", "Aubie", "Cocky", "Sparty", "Nittany Lion", "Big Al", "Hairy Dawg"],
  },
  {
    category: "awards",
    entityKind: "other",
    collisionGroup: "awards",
    prompts: [
      "Name a major college football individual award.",
      "Name a college football award players can win.",
      "Name an award given to a standout college football player.",
      "Name a trophy or award college football stars chase.",
      "Name a well-known individual award in college football.",
    ],
    answers: [
      { name: "Heisman Trophy", aliases: ["Heisman"] },
      { name: "Maxwell Award", aliases: ["Maxwell"] },
      { name: "Doak Walker Award", aliases: ["Doak Walker"] },
      { name: "Biletnikoff Award", aliases: ["Biletnikoff"] },
      { name: "Bednarik Award", aliases: ["Bednarik"] },
      { name: "Butkus Award", aliases: ["Butkus"] },
      { name: "Outland Trophy", aliases: ["Outland"] },
      { name: "Lou Groza Award", aliases: ["Lou Groza", "Groza"] },
    ],
    alsoAcceptedAnswers: [
      { name: "Davey O'Brien Award", aliases: ["Davey O'Brien", "O'Brien Award", "OBrien"] },
      { name: "Jim Thorpe Award", aliases: ["Jim Thorpe", "Thorpe Award", "Thorpe"] },
      { name: "Lombardi Award", aliases: ["Lombardi"] },
      { name: "Ray Guy Award", aliases: ["Ray Guy"] },
      { name: "John Mackey Award", aliases: ["John Mackey", "Mackey Award", "Mackey"] },
      { name: "Rimington Trophy", aliases: ["Rimington"] },
      { name: "Walter Camp Award", aliases: ["Walter Camp"] },
    ],
  },
  {
    category: "conferences",
    entityKind: "other",
    collisionGroup: "conferences",
    prompts: [
      "Name a major college football conference.",
      "Name a conference you hear about constantly during college football season.",
      "Name an FBS conference a casual college football fan would recognize.",
      "Name a conference that sends teams into major college football games.",
      "Name a college football conference.",
    ],
    answers: [
      { name: "SEC", aliases: ["Southeastern Conference"] },
      { name: "Big Ten", aliases: ["Big 10", "B1G"] },
      { name: "Big 12", aliases: ["Big Twelve"] },
      { name: "ACC", aliases: ["Atlantic Coast Conference"] },
      { name: "AAC", aliases: ["American Athletic Conference", "The American"] },
      { name: "Mountain West", aliases: ["MWC", "Mountain West Conference"] },
      { name: "Sun Belt", aliases: ["Sun Belt Conference"] },
      { name: "Conference USA", aliases: ["C-USA", "CUSA"] },
    ],
    alsoAcceptedAnswers: [
      { name: "MAC", aliases: ["Mid-American Conference"] },
      { name: "Pac-12", aliases: ["Pac 12", "PAC-12", "Pacific-12"] },
    ],
  },
  {
    category: "school-identity",
    entityKind: "school",
    collisionGroup: "schools",
    prompts: [
      "Name a college football school whose primary look features red.",
      "Name a major program you associate with the color red.",
      "Name a school whose football crowd can turn a stadium red.",
      "Name a college team with red as a signature football color.",
      "Name a red-wearing college football program almost everyone recognizes.",
    ],
    answers: [
      { name: "Alabama", aliases: ["Bama", "Crimson Tide"] },
      { name: "Ohio State", aliases: ["OSU", "Buckeyes", "Ohio St"] },
      { name: "Georgia", aliases: ["UGA", "Bulldogs", "Georgia Bulldogs"] },
      { name: "Oklahoma", aliases: ["OU", "Sooners"] },
      { name: "USC", aliases: ["Southern Cal", "Trojans"] },
      { name: "Nebraska", aliases: ["Huskers", "Cornhuskers"] },
      { name: "Wisconsin", aliases: ["Badgers"] },
      { name: "Arkansas", aliases: ["Razorbacks", "Hogs"] },
    ],
    alsoAcceptedAnswers: [
      { name: "Utah", aliases: ["Utes"] },
      { name: "Texas Tech", aliases: ["Red Raiders", "Tech"] },
      { name: "NC State", aliases: ["North Carolina State", "Wolfpack"] },
      { name: "Louisville", aliases: ["Cardinals"] },
      { name: "Rutgers", aliases: ["Scarlet Knights"] },
      { name: "South Carolina", aliases: ["Gamecocks"] },
      { name: "Stanford", aliases: ["Cardinal"] },
      { name: "Indiana", aliases: ["Hoosiers"] },
    ],
  },
] as const);
