import { expandSportsFeudFamilies } from "./sportsFeudAuthoredHelpers";

export const CFB_SPORTS_FEUD_FAST_4 = expandSportsFeudFamilies("cfb-fast4", [
  {
    category: "positions",
    entityKind: "other",
    collisionGroup: "positions",
    prompts: [
      {
        prompt: "Name a college football position other than quarterback.",
        answers: ["Running back","Wide receiver","Linebacker","Cornerback","Defensive end","Safety","Tight end","Offensive tackle"],
        alsoAcceptedAnswers: ["Guard","Center","Defensive tackle","Kicker","Punter","Long snapper","Fullback"],
      },
      {
        prompt: "Name a position you can play on a football field.",
        answers: ["Wide receiver","Running back","Linebacker","Cornerback","Safety","Tight end","Defensive end","Kicker"],
        alsoAcceptedAnswers: ["Offensive tackle","Guard","Center","Defensive tackle","Punter","Long snapper","Fullback"],
      },
      {
        prompt: "Name a college football position that produces stars.",
        answers: ["Wide receiver","Running back","Defensive end","Cornerback","Linebacker","Tight end","Safety","Kicker"],
        alsoAcceptedAnswers: ["Offensive tackle","Guard","Center","Defensive tackle","Punter","Long snapper","Fullback"],
      },
      {
        prompt: "Name a football position recruits specialize in.",
        answers: ["Wide receiver","Cornerback","Linebacker","Defensive end","Running back","Offensive tackle","Safety","Tight end"],
        alsoAcceptedAnswers: ["Guard","Center","Defensive tackle","Kicker","Punter","Long snapper","Fullback"],
      },
      {
        prompt: "Name a position group coaches talk about constantly.",
        answers: ["Offensive tackle","Defensive end","Linebacker","Wide receiver","Cornerback","Running back","Safety","Tight end"],
        alsoAcceptedAnswers: ["Guard","Center","Defensive tackle","Kicker","Punter","Long snapper","Fullback"],
      },
    ],
    answers: [
      { name: "Running back", aliases: ["RB"] },
      { name: "Wide receiver", aliases: ["WR"] },
      { name: "Linebacker", aliases: ["LB"] },
      { name: "Cornerback", aliases: ["CB"] },
      { name: "Defensive end", aliases: ["DE", "Edge", "EDGE"] },
      { name: "Safety", aliases: ["S"] },
      { name: "Tight end", aliases: ["TE"] },
      { name: "Offensive tackle", aliases: ["OT"] },
    ],
    alsoAcceptedAnswers: [
      { name: "Guard", aliases: ["OG"] },
      { name: "Center", aliases: ["C"] },
      { name: "Defensive tackle", aliases: ["DT"] },
      { name: "Kicker", aliases: ["K"] },
      { name: "Punter", aliases: ["P"] },
      { name: "Long snapper", aliases: ["LS"] },
      { name: "Fullback", aliases: ["FB"] },
    ],
  },
  {
    category: "game-concepts",
    entityKind: "other",
    collisionGroup: "scoring",
    prompts: [
      {
        prompt: "Name a way to score points in college football.",
        answers: ["Touchdown","Field goal","Extra point","Two-point conversion","Safety","Pick-six","Kick return touchdown","Punt return touchdown"],
        alsoAcceptedAnswers: ["Fumble return touchdown","Blocked kick return touchdown"],
      },
      {
        prompt: "Name something that can put points on the scoreboard.",
        answers: ["Touchdown","Field goal","Extra point","Two-point conversion","Safety","Pick-six","Fumble return touchdown","Kick return touchdown"],
        alsoAcceptedAnswers: ["Punt return touchdown","Blocked kick return touchdown"],
      },
      {
        prompt: "Name a scoring play you can see on a Saturday.",
        answers: ["Touchdown","Field goal","Extra point","Two-point conversion","Pick-six","Safety","Kick return touchdown","Punt return touchdown"],
        alsoAcceptedAnswers: ["Fumble return touchdown","Blocked kick return touchdown"],
      },
      {
        prompt: "Name a way an offense, defense, or special teams unit can score.",
        answers: ["Touchdown","Field goal","Extra point","Two-point conversion","Kick return touchdown","Punt return touchdown","Pick-six","Safety"],
        alsoAcceptedAnswers: ["Fumble return touchdown","Blocked kick return touchdown"],
      },
      {
        prompt: "Name something that changes the score in a football game.",
        answers: ["Touchdown","Field goal","Extra point","Two-point conversion","Safety","Pick-six","Fumble return touchdown","Kick return touchdown"],
        alsoAcceptedAnswers: ["Punt return touchdown","Blocked kick return touchdown"],
      },
    ],
    answers: [
      { name: "Touchdown", aliases: ["TD"] },
      { name: "Field goal", aliases: ["FG"] },
      { name: "Extra point", aliases: ["PAT"] },
      { name: "Two-point conversion", aliases: ["2-point conversion", "2 point conversion"] },
      "Safety",
      { name: "Pick-six", aliases: ["Interception return touchdown", "INT return TD"] },
      { name: "Kick return touchdown", aliases: ["Kick return TD", "Kickoff return touchdown", "KR TD"] },
      { name: "Punt return touchdown", aliases: ["Punt return TD", "PR TD"] },
    ],
    alsoAcceptedAnswers: [
      { name: "Fumble return touchdown", aliases: ["Fumble return TD", "Scoop and score"] },
      { name: "Blocked kick return touchdown", aliases: ["Blocked kick TD", "Block return touchdown"] },
    ],
  },
  {
    category: "game-concepts",
    entityKind: "other",
    collisionGroup: "penalties",
    prompts: [
      {
        prompt: "Name a common football penalty.",
        answers: ["Holding","False start","Pass interference","Offsides","Personal foul","Targeting","Delay of game","Illegal formation"],
        alsoAcceptedAnswers: ["Facemask","Unsportsmanlike conduct","Roughing the passer","Intentional grounding","Illegal block in the back","Ineligible receiver downfield","Illegal substitution"],
      },
      {
        prompt: "Name a flag college football fans complain about.",
        answers: ["Targeting","Pass interference","Holding","Roughing the passer","Personal foul","Offsides","Unsportsmanlike conduct","Facemask"],
        alsoAcceptedAnswers: ["False start","Delay of game","Illegal formation","Intentional grounding","Illegal block in the back","Ineligible receiver downfield","Illegal substitution"],
      },
      {
        prompt: "Name a penalty an offense can commit.",
        answers: ["Holding","False start","Delay of game","Illegal formation","Intentional grounding","Illegal block in the back","Ineligible receiver downfield","Illegal substitution"],
        alsoAcceptedAnswers: ["Personal foul","Unsportsmanlike conduct","Facemask","Pass interference"],
      },
      {
        prompt: "Name a penalty that can ruin a big play.",
        answers: ["Holding","Pass interference","Illegal block in the back","Personal foul","Targeting","Ineligible receiver downfield","Illegal formation","Facemask"],
        alsoAcceptedAnswers: ["False start","Offsides","Unsportsmanlike conduct","Roughing the passer","Intentional grounding","Delay of game","Illegal substitution"],
      },
      {
        prompt: "Name a football penalty almost every fan understands.",
        answers: ["Holding","False start","Pass interference","Offsides","Facemask","Targeting","Delay of game","Roughing the passer"],
        alsoAcceptedAnswers: ["Personal foul","Unsportsmanlike conduct","Intentional grounding","Illegal block in the back","Ineligible receiver downfield","Illegal formation","Illegal substitution"],
      },
    ],
    answers: [
      "Holding",
      "False start",
      { name: "Pass interference", aliases: ["PI"] },
      "Offsides",
      "Personal foul",
      "Targeting",
      { name: "Delay of game", aliases: ["DOG"] },
      "Illegal formation",
    ],
    alsoAcceptedAnswers: [
      "Facemask",
      "Unsportsmanlike conduct",
      "Roughing the passer",
      "Intentional grounding",
      "Illegal block in the back",
      "Ineligible receiver downfield",
      "Illegal substitution",
    ],
  },
  {
    category: "stats",
    entityKind: "other",
    collisionGroup: "stats",
    prompts: [
      {
        prompt: "Name a quarterback statistic.",
        answers: ["Passing yards","Passing touchdowns","Completion percentage","Interceptions","Pass attempts","Completions","Yards per attempt","Passer rating"],
        alsoAcceptedAnswers: ["QBR","Rushing yards","Rushing touchdowns","Sacks taken","Turnovers"],
      },
      {
        prompt: "Name a number fans use to judge a quarterback.",
        answers: ["Passing yards","Passing touchdowns","Interceptions","Completion percentage","Passer rating","QBR","Yards per attempt","Rushing yards"],
        alsoAcceptedAnswers: ["Pass attempts","Completions","Rushing touchdowns","Sacks taken","Turnovers"],
      },
      {
        prompt: "Name a quarterback stat shown in a broadcast box score.",
        answers: ["Passing yards","Passing touchdowns","Completions","Pass attempts","Interceptions","Completion percentage","Rushing yards","Rushing touchdowns"],
        alsoAcceptedAnswers: ["Yards per attempt","Passer rating","QBR","Sacks taken","Turnovers"],
      },
      {
        prompt: "Name a passing stat people compare after a game.",
        answers: ["Passing yards","Passing touchdowns","Interceptions","Completion percentage","Completions","Pass attempts","Yards per attempt","Passer rating"],
        alsoAcceptedAnswers: ["QBR","Sacks taken"],
      },
      {
        prompt: "Name a stat that can describe how a quarterback played.",
        answers: ["Passing yards","Passing touchdowns","Interceptions","Completion percentage","Passer rating","QBR","Rushing yards","Turnovers"],
        alsoAcceptedAnswers: ["Pass attempts","Completions","Yards per attempt","Rushing touchdowns","Sacks taken"],
      },
    ],
    answers: [
      { name: "Passing yards", aliases: ["Pass yards"] },
      { name: "Passing touchdowns", aliases: ["Passing TDs", "Pass TDs"] },
      { name: "Completion percentage", aliases: ["Completion pct", "Comp pct"] },
      { name: "Interceptions", aliases: ["INTs"] },
      { name: "Pass attempts", aliases: ["Attempts"] },
      { name: "Completions", aliases: ["Comps"] },
      { name: "Yards per attempt", aliases: ["YPA"] },
      { name: "Passer rating", aliases: ["Rating"] },
    ],
    alsoAcceptedAnswers: [
      { name: "QBR", aliases: ["Total QBR"] },
      { name: "Rushing yards", aliases: ["Rush yards"] },
      { name: "Rushing touchdowns", aliases: ["Rushing TDs", "Rush TDs"] },
      { name: "Sacks taken", aliases: ["Sacked"] },
      { name: "Turnovers", aliases: ["TOs"] },
    ],
  },
  {
    category: "stats",
    entityKind: "other",
    collisionGroup: "stats",
    prompts: [
      {
        prompt: "Name a defensive football statistic.",
        answers: ["Tackles","Sacks","Interceptions","Tackles for loss","Pass breakups","Forced fumbles","Fumble recoveries","Quarterback hurries"],
        alsoAcceptedAnswers: ["Quarterback hits","Defensive touchdowns","Blocked kicks","Solo tackles","Assisted tackles"],
      },
      {
        prompt: "Name a stat that can make a defender stand out.",
        answers: ["Sacks","Interceptions","Tackles for loss","Forced fumbles","Pass breakups","Tackles","Defensive touchdowns","Quarterback hurries"],
        alsoAcceptedAnswers: ["Fumble recoveries","Quarterback hits","Blocked kicks","Solo tackles","Assisted tackles"],
      },
      {
        prompt: "Name a defensive number shown in a box score.",
        answers: ["Tackles","Sacks","Interceptions","Tackles for loss","Pass breakups","Forced fumbles","Fumble recoveries","Solo tackles"],
        alsoAcceptedAnswers: ["Quarterback hurries","Quarterback hits","Defensive touchdowns","Blocked kicks","Assisted tackles"],
      },
      {
        prompt: "Name a stat scouts notice for a college defender.",
        answers: ["Tackles for loss","Sacks","Interceptions","Pass breakups","Forced fumbles","Quarterback hurries","Tackles","Quarterback hits"],
        alsoAcceptedAnswers: ["Fumble recoveries","Defensive touchdowns","Blocked kicks","Solo tackles","Assisted tackles"],
      },
      {
        prompt: "Name a defensive stat fans brag about.",
        answers: ["Sacks","Interceptions","Tackles","Tackles for loss","Forced fumbles","Defensive touchdowns","Pass breakups","Quarterback hurries"],
        alsoAcceptedAnswers: ["Fumble recoveries","Quarterback hits","Blocked kicks","Solo tackles","Assisted tackles"],
      },
    ],
    answers: [
      "Tackles",
      "Sacks",
      "Interceptions",
      { name: "Tackles for loss", aliases: ["TFL", "TFLs"] },
      { name: "Pass breakups", aliases: ["PBU", "PBUs"] },
      { name: "Forced fumbles", aliases: ["FF"] },
      { name: "Fumble recoveries", aliases: ["FR"] },
      { name: "Quarterback hurries", aliases: ["QB hurries", "Pressures"] },
    ],
    alsoAcceptedAnswers: [
      { name: "Quarterback hits", aliases: ["QB hits"] },
      { name: "Defensive touchdowns", aliases: ["Defensive TDs"] },
      { name: "Blocked kicks", aliases: ["Blocks"] },
      { name: "Solo tackles", aliases: ["Solo"] },
      { name: "Assisted tackles", aliases: ["Assists"] },
    ],
  },
  {
    category: "strategy",
    entityKind: "other",
    collisionGroup: "offense",
    prompts: [
      "Name an offensive concept you hear in college football.",
      {
        prompt: "Name a football play concept an offense might build around.",
        answers: ["RPO","Read option","Inside zone","Outside zone","Air Raid","Spread offense","Power run","Play-action"],
        alsoAcceptedAnswers: ["Screen pass","Four verticals","Mesh","Zone read","Counter","Bootleg","Jet sweep"],
      },
      {
        prompt: "Name an offensive idea commentators mention during games.",
        answers: ["RPO","Play-action","Read option","Screen pass","Air Raid","Spread offense","Four verticals","Zone read"],
        alsoAcceptedAnswers: ["Mesh","Counter","Inside zone","Outside zone","Power run","Bootleg","Jet sweep"],
      },
      {
        prompt: "Name a concept a coordinator might use to stress a defense.",
        answers: ["RPO","Play-action","Read option","Screen pass","Mesh","Four verticals","Jet sweep","Bootleg"],
        alsoAcceptedAnswers: ["Zone read","Counter","Air Raid","Spread offense","Inside zone","Outside zone","Power run"],
      },
      {
        prompt: "Name an offensive term college football fans recognize.",
        answers: ["RPO","Play-action","Read option","Screen pass","Air Raid","Spread offense","Four verticals","Zone read"],
        alsoAcceptedAnswers: ["Mesh","Counter","Inside zone","Outside zone","Power run","Bootleg","Jet sweep"],
      },
    ],
    answers: [
      { name: "RPO", aliases: ["Run-pass option", "Run pass option"] },
      { name: "Play-action", aliases: ["Play action", "PA"] },
      { name: "Read option", aliases: ["Option", "Read-option"] },
      { name: "Screen pass", aliases: ["Screen"] },
      { name: "Four verticals", aliases: ["Four verts", "4 verts", "Verts"] },
      { name: "Mesh", aliases: ["Mesh concept"] },
      { name: "Zone read", aliases: ["Zone-read"] },
      { name: "Counter", aliases: ["Counter run"] },
    ],
    alsoAcceptedAnswers: [
      { name: "Air Raid", aliases: ["Air raid offense"] },
      { name: "Spread offense", aliases: ["Spread"] },
      { name: "Inside zone", aliases: ["IZ"] },
      { name: "Outside zone", aliases: ["OZ"] },
      { name: "Power run", aliases: ["Power"] },
      { name: "Bootleg", aliases: ["Boot"] },
      { name: "Jet sweep", aliases: ["Jet"] },
    ],
  },
  {
    category: "strategy",
    entityKind: "other",
    collisionGroup: "defense",
    prompts: [
      "Name a defensive coverage, pressure, or concept.",
      {
        prompt: "Name a defensive call a college team might use.",
        answers: ["Blitz","Cover 3","Cover 2","Man coverage","Cover 1","Quarters","Zone blitz","Cover 0"],
        alsoAcceptedAnswers: ["Cover 6","Tampa 2","Prevent defense","Nickel","Dime","Spy","Press coverage"],
      },
      {
        prompt: "Name a defensive term commentators mention during games.",
        answers: ["Blitz","Man coverage","Cover 2","Cover 3","Zone blitz","Nickel","Dime","Spy"],
        alsoAcceptedAnswers: ["Cover 1","Quarters","Cover 0","Cover 6","Tampa 2","Prevent defense","Press coverage"],
      },
      {
        prompt: "Name a defensive look a quarterback has to identify before the snap.",
        answers: ["Cover 0","Cover 1","Cover 2","Cover 3","Quarters","Blitz","Man coverage","Press coverage"],
        alsoAcceptedAnswers: ["Zone blitz","Cover 6","Tampa 2","Prevent defense","Nickel","Dime","Spy"],
      },
      {
        prompt: "Name a defensive concept college football fans hear all the time.",
        answers: ["Blitz","Man coverage","Cover 2","Cover 3","Cover 1","Quarters","Zone blitz","Nickel"],
        alsoAcceptedAnswers: ["Cover 0","Cover 6","Tampa 2","Prevent defense","Dime","Spy","Press coverage"],
      },
    ],
    answers: [
      { name: "Cover 2", aliases: ["Cover two"] },
      { name: "Cover 3", aliases: ["Cover three"] },
      { name: "Blitz", aliases: ["Blitzing", "Pressure"] },
      { name: "Man coverage", aliases: ["Man", "Man-to-man", "Man to man"] },
      { name: "Cover 1", aliases: ["Cover one"] },
      { name: "Quarters", aliases: ["Cover 4", "Cover four"] },
      { name: "Zone blitz", aliases: ["Zone pressure"] },
      { name: "Cover 0", aliases: ["Cover zero"] },
    ],
    alsoAcceptedAnswers: [
      { name: "Cover 6", aliases: ["Cover six"] },
      { name: "Tampa 2", aliases: ["Tampa two"] },
      { name: "Prevent defense", aliases: ["Prevent"] },
      { name: "Nickel", aliases: ["Nickel defense"] },
      { name: "Dime", aliases: ["Dime defense"] },
      { name: "Spy", aliases: ["QB spy", "Quarterback spy"] },
      { name: "Press coverage", aliases: ["Press", "Press man"] },
    ],
  },
  {
    category: "recruiting",
    entityKind: "other",
    collisionGroup: "recruiting",
    prompts: [
      "Name a term associated with college football recruiting.",
      {
        prompt: "Name something fans hear during recruiting season.",
        answers: ["Five-star","Commitment","Signing day","Transfer portal","Official visit","Recruiting class","Decommitment","Crystal Ball"],
        alsoAcceptedAnswers: ["Early enrollee","Flip","Preferred walk-on","NIL","Early signing period","Verbal commitment"],
      },
      {
        prompt: "Name a word coaches and fans use when talking about recruits.",
        answers: ["Five-star","Commitment","Official visit","Decommitment","Flip","Crystal Ball","Recruiting class","Verbal commitment"],
        alsoAcceptedAnswers: ["Signing day","Transfer portal","Early enrollee","Preferred walk-on","NIL","Early signing period"],
      },
      {
        prompt: "Name something tied to signing a college football prospect.",
        answers: ["Signing day","Commitment","Five-star","Official visit","Recruiting class","Early signing period","Verbal commitment","Decommitment"],
        alsoAcceptedAnswers: ["Transfer portal","Early enrollee","Crystal Ball","Flip","Preferred walk-on","NIL"],
      },
      {
        prompt: "Name a recruiting term a serious college football fan knows.",
        answers: ["Five-star","Commitment","Signing day","Official visit","Crystal Ball","Flip","Decommitment","Preferred walk-on"],
        alsoAcceptedAnswers: ["Transfer portal","Recruiting class","Early enrollee","NIL","Early signing period","Verbal commitment"],
      },
    ],
    answers: [
      { name: "Five-star", aliases: ["5-star", "5 star", "Five star"] },
      { name: "Commitment", aliases: ["Commit", "Committed"] },
      { name: "Signing day", aliases: ["NSD", "National Signing Day"] },
      { name: "Transfer portal", aliases: ["Portal"] },
      { name: "Official visit", aliases: ["Visit"] },
      { name: "Recruiting class", aliases: ["Class"] },
      { name: "Decommitment", aliases: ["Decommit", "Decommitted"] },
      { name: "Early enrollee", aliases: ["Early enroll", "Early enrollment"] },
    ],
    alsoAcceptedAnswers: [
      { name: "Crystal Ball", aliases: ["Crystal ball prediction"] },
      { name: "Flip", aliases: ["Flipped commitment", "Recruiting flip"] },
      { name: "Preferred walk-on", aliases: ["PWO", "Preferred walk on"] },
      { name: "NIL", aliases: ["Name image likeness", "Name, image and likeness"] },
      { name: "Early signing period", aliases: ["ESP", "Early signing"] },
      { name: "Verbal commitment", aliases: ["Verbal", "Verbal commit"] },
    ],
  },
  {
    category: "postseason",
    entityKind: "other",
    collisionGroup: "postseason",
    prompts: [
      {
        prompt: "Name a stage or game type in the college football postseason.",
        answers: ["Bowl game","Conference championship","CFP first round","CFP quarterfinal","CFP semifinal","National championship","New Year's Six","College Football Playoff"],
        alsoAcceptedAnswers: [],
      },
      {
        prompt: "Name a round or game teams can reach after the regular season.",
        answers: ["Bowl game","Conference championship","CFP first round","CFP quarterfinal","CFP semifinal","National championship","New Year's Six","College Football Playoff"],
        alsoAcceptedAnswers: [],
      },
      {
        prompt: "Name a postseason stage in modern college football.",
        answers: ["College Football Playoff","CFP first round","CFP quarterfinal","CFP semifinal","National championship","Bowl game","Conference championship","New Year's Six"],
        alsoAcceptedAnswers: [],
      },
      {
        prompt: "Name a game type that can appear on a college football postseason path.",
        answers: ["Bowl game","Conference championship","CFP first round","CFP quarterfinal","CFP semifinal","National championship","New Year's Six","College Football Playoff"],
        alsoAcceptedAnswers: [],
      },
      {
        prompt: "Name a college football postseason round or game.",
        answers: ["Bowl game","CFP first round","CFP quarterfinal","CFP semifinal","National championship","Conference championship","New Year's Six","College Football Playoff"],
        alsoAcceptedAnswers: [],
      },
    ],
    answers: [
      { name: "Bowl game", aliases: ["Bowl"] },
      { name: "Conference championship", aliases: ["Conference title game", "Conference title"] },
      { name: "CFP first round", aliases: ["First round", "Playoff first round"] },
      { name: "CFP quarterfinal", aliases: ["Quarterfinal", "Quarterfinals"] },
      { name: "CFP semifinal", aliases: ["Semifinal", "Semifinals"] },
      { name: "National championship", aliases: ["Championship", "Title game", "National title"] },
      { name: "New Year's Six", aliases: ["NY6", "New Years Six"] },
      { name: "College Football Playoff", aliases: ["CFP", "Playoff"] },
    ],
  },
  {
    category: "fan-culture",
    entityKind: "other",
    collisionGroup: "culture",
    prompts: [
      {
        prompt: "Name something college football fans commonly do on game day.",
        answers: ["Tailgate","Cheer","Wear team colors","Sing the fight song","Watch GameDay","Trash talk","Storm the field","Cookout"],
        alsoAcceptedAnswers: ["Attend the game","Watch party","Watch with friends","Chant","Wave a flag"],
      },
      {
        prompt: "Name a common Saturday activity for college football fans.",
        answers: ["Tailgate","Watch GameDay","Attend the game","Watch party","Wear team colors","Cheer","Cookout","Watch with friends"],
        alsoAcceptedAnswers: ["Sing the fight song","Trash talk","Storm the field","Chant","Wave a flag"],
      },
      {
        prompt: "Name something fans often do around a big college football game.",
        answers: ["Tailgate","Attend the game","Wear team colors","Cheer","Trash talk","Watch party","Cookout","Chant"],
        alsoAcceptedAnswers: ["Sing the fight song","Watch GameDay","Storm the field","Watch with friends","Wave a flag"],
      },
      {
        prompt: "Name a familiar college football game-day activity.",
        answers: ["Tailgate","Cheer","Wear team colors","Attend the game","Watch GameDay","Sing the fight song","Watch party","Cookout"],
        alsoAcceptedAnswers: ["Trash talk","Storm the field","Watch with friends","Chant","Wave a flag"],
      },
      {
        prompt: "Name something fans commonly do on a college football Saturday.",
        answers: ["Tailgate","Watch GameDay","Attend the game","Cheer","Wear team colors","Watch party","Cookout","Trash talk"],
        alsoAcceptedAnswers: ["Sing the fight song","Storm the field","Watch with friends","Chant","Wave a flag"],
      },
    ],
    answers: [
      { name: "Tailgate", aliases: ["Tailgating"] },
      { name: "Cheer", aliases: ["Cheering"] },
      { name: "Wear team colors", aliases: ["Team colors", "Wear colors", "Jersey"] },
      { name: "Sing the fight song", aliases: ["Fight song", "Sing fight song"] },
      { name: "Watch GameDay", aliases: ["GameDay", "College GameDay", "Watch College GameDay"] },
      { name: "Trash talk", aliases: ["Trash talk rivals", "Talk trash"] },
      { name: "Storm the field", aliases: ["Field storm", "Rush the field"] },
      { name: "Cookout", aliases: ["Grill", "Grilling", "Barbecue", "BBQ"] },
    ],
    alsoAcceptedAnswers: ["Attend the game", "Watch party", "Watch with friends", "Chant", "Wave a flag"],
  },
] as const);
