import { expandSportsFeudFamilies } from "./sportsFeudAuthoredHelpers";

export const CFB_SPORTS_FEUD_FAST_4 = expandSportsFeudFamilies("cfb-fast4", [
  {
    category: "positions",
    collisionGroup: "positions",
    prompts: [
      "Name a college football position other than quarterback.",
      "Name a position you can play on a football field.",
      "Name a college football position that produces stars.",
      "Name a football position recruits specialize in.",
      "Name a position group coaches talk about constantly.",
    ],
    answers: ["Running back", "Wide receiver", "Linebacker", "Cornerback", "Defensive end", "Safety", "Tight end", "Offensive tackle"],
  },
  {
    category: "game-concepts",
    collisionGroup: "scoring",
    prompts: [
      "Name a way to score points in college football.",
      "Name something that can put points on the scoreboard.",
      "Name a scoring play you can see on a Saturday.",
      "Name a way an offense or special teams unit can score.",
      "Name something that changes the score in a football game.",
    ],
    answers: ["Touchdown", "Field goal", "Extra point", "Two-point conversion", "Safety", "Pick-six", "Kick return touchdown", "Punt return touchdown"],
  },
  {
    category: "game-concepts",
    collisionGroup: "penalties",
    prompts: [
      "Name a common football penalty.",
      "Name a flag college football fans complain about.",
      "Name a penalty an offense can commit.",
      "Name a penalty that can ruin a big play.",
      "Name a football penalty almost every fan understands.",
    ],
    answers: ["Holding", "False start", "Pass interference", "Offsides", "Personal foul", "Targeting", "Delay of game", "Illegal formation"],
  },
  {
    category: "stats",
    collisionGroup: "stats",
    prompts: [
      "Name a quarterback statistic.",
      "Name a number fans use to judge a quarterback.",
      "Name a quarterback stat shown in a broadcast box score.",
      "Name a passing stat people compare after a game.",
      "Name a stat that can describe how a quarterback played.",
    ],
    answers: ["Passing yards", "Passing touchdowns", "Completion percentage", "Interceptions", "Pass attempts", "Completions", "Yards per attempt", "Passer rating"],
  },
  {
    category: "stats",
    collisionGroup: "stats",
    prompts: [
      "Name a defensive football statistic.",
      "Name a stat that can make a defender stand out.",
      "Name a defensive number shown in a box score.",
      "Name a stat scouts notice for a college defender.",
      "Name a defensive stat fans brag about.",
    ],
    answers: ["Tackles", "Sacks", "Interceptions", "Tackles for loss", "Pass breakups", "Forced fumbles", "Fumble recoveries", "Quarterback hurries"],
  },
  {
    category: "strategy",
    collisionGroup: "offense",
    prompts: [
      "Name an offensive concept you hear in college football.",
      "Name a football play concept an offense might build around.",
      "Name an offensive idea commentators mention during games.",
      "Name a concept a coordinator might use to stress a defense.",
      "Name an offensive term college football fans recognize.",
    ],
    answers: [
      { name: "RPO", aliases: ["Run-pass option", "Run pass option"] },
      { name: "Play-action", aliases: ["Play action", "PA"] },
      { name: "Read option", aliases: ["Option", "Read-option"] },
      { name: "Screen pass", aliases: ["Screen"] },
      { name: "Four verticals", aliases: ["Four verts", "4 verts", "Verts"] },
      { name: "Mesh", aliases: ["Mesh concept"] },
      { name: "Zone read", aliases: ["Zone-read"] },
      { name: "Counter", aliases: ["Counter run"] },
    ],
  },
  {
    category: "strategy",
    collisionGroup: "defense",
    prompts: [
      "Name a defensive coverage, pressure, or concept.",
      "Name a defensive call a college team might use.",
      "Name a defensive term commentators mention during games.",
      "Name a defensive look a quarterback has to identify before the snap.",
      "Name a defensive concept college football fans hear all the time.",
    ],
    answers: [
      { name: "Cover 2", aliases: ["Cover two"] },
      { name: "Cover 3", aliases: ["Cover three"] },
      { name: "Blitz", aliases: ["Blitzing", "Pressure"] },
      { name: "Man coverage", aliases: ["Man", "Man-to-man", "Man to man"] },
      { name: "Cover 1", aliases: ["Cover one"] },
      { name: "Quarters", aliases: ["Cover 4", "Cover four"] },
      { name: "Zone blitz", aliases: ["Zone pressure"] },
      { name: "Cover 0", aliases: ["Cover zero"] },
    ],
  },
  {
    category: "recruiting",
    collisionGroup: "recruiting",
    prompts: [
      "Name a term associated with college football recruiting.",
      "Name something fans hear during recruiting season.",
      "Name a word coaches and fans use when talking about recruits.",
      "Name something tied to signing a college football prospect.",
      "Name a recruiting term a serious college football fan knows.",
    ],
    answers: [
      { name: "Five-star", aliases: ["5-star", "5 star", "Five star"] },
      { name: "Commitment", aliases: ["Commit", "Committed"] },
      { name: "Signing day", aliases: ["NSD", "National Signing Day"] },
      { name: "Transfer portal", aliases: ["Portal"] },
      { name: "Official visit", aliases: ["Visit"] },
      { name: "Recruiting class", aliases: ["Class"] },
      { name: "Decommitment", aliases: ["Decommit", "Decommitted"] },
      { name: "Early enrollee", aliases: ["Early enroll", "Early enrollment"] },
    ],
  },
  {
    category: "postseason",
    collisionGroup: "postseason",
    prompts: [
      "Name a stage or game type in the college football postseason.",
      "Name a round or game teams can reach after the regular season.",
      "Name a postseason stage in modern college football.",
      "Name a game type that can appear on a college football postseason path.",
      "Name a college football postseason round or game.",
    ],
    answers: [
      { name: "Bowl game", aliases: ["Bowl"] },
      { name: "Conference championship", aliases: ["Conference title game", "Conference title"] },
      { name: "CFP first round", aliases: ["First round", "Playoff first round"] },
      { name: "CFP quarterfinal", aliases: ["Quarterfinal", "Quarterfinals"] },
      { name: "CFP semifinal", aliases: ["Semifinal", "Semifinals"] },
      { name: "National championship", aliases: ["Championship", "Title game", "National title"] },
      { name: "New Year's Six", aliases: ["NY6", "New Years Six"] },
      { name: "College Football Playoff", aliases: ["CFP", "Playoff"] },
    ],
  },
  {
    category: "fan-culture",
    collisionGroup: "culture",
    prompts: [
      "Name something college football fans commonly do on game day.",
      "Name a common Saturday activity for college football fans.",
      "Name something fans often do around a big college football game.",
      "Name a familiar college football game-day activity.",
      "Name something fans commonly do on a college football Saturday.",
    ],
    answers: [
      { name: "Tailgate", aliases: ["Tailgating"] },
      { name: "Cheer", aliases: ["Cheering", "Chant"] },
      { name: "Wear team colors", aliases: ["Team colors", "Wear colors", "Jersey"] },
      { name: "Sing the fight song", aliases: ["Fight song", "Sing fight song"] },
      { name: "Watch GameDay", aliases: ["GameDay", "College GameDay", "Watch College GameDay"] },
      { name: "Trash talk", aliases: ["Trash talk rivals", "Talk trash"] },
      { name: "Storm the field", aliases: ["Field storm", "Rush the field"] },
      { name: "Cookout", aliases: ["Grill", "Grilling", "Barbecue", "BBQ"] },
    ],
  },
] as const);
