import { expandSportsFeudFamilies } from "./sportsFeudAuthoredHelpers";

export const CFB_SPORTS_FEUD_FAST_1 = expandSportsFeudFamilies("cfb-fast1", [
  {
    category: "schools",
    entityKind: "school",
    collisionGroup: "schools",
    prompts: [
      "Name an SEC school.",
      "Name a football program from the SEC.",
      "Name an SEC team you would expect to see on national TV.",
      "Name a school that feels unmistakably SEC.",
      "Name an SEC program with a huge football following.",
    ],
    answers: [
      { name: "Alabama", aliases: ["Bama", "Crimson Tide"] },
      { name: "Georgia", aliases: ["UGA", "Georgia Bulldogs"] },
      { name: "LSU", aliases: ["Louisiana State", "LSU Tigers"] },
      { name: "Texas", aliases: ["Longhorns"] },
      { name: "Oklahoma", aliases: ["OU", "Sooners"] },
      { name: "Tennessee", aliases: ["Vols", "Volunteers"] },
      { name: "Florida", aliases: ["Gators"] },
      { name: "Texas A&M", aliases: ["A&M", "Aggies", "TAMU"] },
    ],
    alsoAcceptedAnswers: [
      { name: "Auburn", aliases: ["Auburn Tigers"] },
      { name: "Arkansas", aliases: ["Razorbacks", "Hogs"] },
      { name: "Kentucky", aliases: ["Wildcats"] },
      { name: "Mississippi State", aliases: ["Miss State", "MSU"] },
      { name: "Missouri", aliases: ["Mizzou"] },
      { name: "Ole Miss", aliases: ["Mississippi", "Rebels"] },
      { name: "South Carolina", aliases: ["Gamecocks"] },
      { name: "Vanderbilt", aliases: ["Vandy", "Commodores"] },
    ],
  },
  {
    category: "schools",
    entityKind: "school",
    collisionGroup: "schools",
    prompts: [
      "Name a Big Ten school.",
      "Name a football program from the Big Ten.",
      "Name a Big Ten team with a major national brand.",
      "Name a school that fits naturally in a Big Ten football conversation.",
      "Name a Big Ten program known by almost every college football fan.",
    ],
    answers: [
      { name: "Ohio State", aliases: ["OSU", "Buckeyes", "Ohio St"] },
      { name: "Michigan", aliases: ["Wolverines"] },
      { name: "Penn State", aliases: ["PSU", "Nittany Lions"] },
      { name: "Oregon", aliases: ["Ducks"] },
      { name: "USC", aliases: ["Southern Cal", "Trojans"] },
      { name: "Wisconsin", aliases: ["Badgers"] },
      { name: "Nebraska", aliases: ["Cornhuskers", "Huskers"] },
      { name: "Iowa", aliases: ["Hawkeyes"] },
    ],
    alsoAcceptedAnswers: [
      { name: "Illinois", aliases: ["Illini", "Fighting Illini"] },
      { name: "Indiana", aliases: ["Hoosiers"] },
      { name: "Maryland", aliases: ["Terps", "Terrapins"] },
      { name: "Michigan State", aliases: ["MSU", "Spartans"] },
      { name: "Minnesota", aliases: ["Gophers", "Golden Gophers"] },
      { name: "Northwestern", aliases: ["Wildcats"] },
      { name: "Purdue", aliases: ["Boilermakers"] },
      { name: "Rutgers", aliases: ["Scarlet Knights"] },
      { name: "UCLA", aliases: ["Bruins"] },
      { name: "Washington", aliases: ["UW", "Huskies"] },
    ],
  },
  {
    category: "schools",
    entityKind: "school",
    collisionGroup: "schools",
    prompts: [
      "Name a Big 12 school.",
      "Name a football program from the Big 12.",
      "Name a Big 12 team you associate with a strong home crowd.",
      "Name a school that belongs in a Big 12 football conversation.",
      "Name a Big 12 program fans recognize quickly.",
    ],
    answers: [
      { name: "Texas Tech", aliases: ["Red Raiders", "Tech"] },
      { name: "Oklahoma State", aliases: ["OSU Cowboys", "Cowboys", "OSU", "OK State", "Oklahoma St"] },
      { name: "Kansas State", aliases: ["K-State"] },
      { name: "TCU", aliases: ["Horned Frogs"] },
      { name: "Baylor", aliases: ["Bears"] },
      { name: "West Virginia", aliases: ["WVU", "Mountaineers"] },
      { name: "Kansas", aliases: ["Jayhawks"] },
      { name: "Iowa State", aliases: ["Cyclones"] },
    ],
    alsoAcceptedAnswers: [
      "Arizona",
      { name: "Arizona State", aliases: ["ASU", "Sun Devils"] },
      "BYU",
      { name: "Cincinnati", aliases: ["Bearcats"] },
      { name: "Colorado", aliases: ["Buffs", "Buffaloes"] },
      "Houston",
      { name: "UCF", aliases: ["Knights"] },
      { name: "Utah", aliases: ["Utes"] },
    ],
  },
  {
    category: "schools",
    entityKind: "school",
    collisionGroup: "schools",
    prompts: [
      "Name an ACC school with a recognizable football brand.",
      "Name a football program from the ACC.",
      "Name an ACC team you would expect in a big college football matchup.",
      "Name a school that feels important to ACC football history.",
      "Name an ACC program a casual college football fan might know.",
    ],
    answers: [
      { name: "Clemson", aliases: ["Tigers", "Clemson Tigers"] },
      { name: "Florida State", aliases: ["FSU", "Seminoles"] },
      { name: "Miami", aliases: ["Miami Hurricanes", "The U", "Hurricanes"] },
      { name: "Virginia Tech", aliases: ["VT", "Hokies"] },
      { name: "Louisville", aliases: ["Cardinals"] },
      { name: "NC State", aliases: ["North Carolina State", "Wolfpack"] },
      { name: "North Carolina", aliases: ["UNC", "Tar Heels"] },
      { name: "Syracuse", aliases: ["Orange"] },
    ],
    alsoAcceptedAnswers: [
      { name: "Boston College", aliases: ["BC", "Eagles"] },
      { name: "Cal", aliases: ["California", "Golden Bears"] },
      { name: "Duke", aliases: ["Blue Devils"] },
      { name: "Georgia Tech", aliases: ["GT", "Yellow Jackets"] },
      { name: "Pitt", aliases: ["Pittsburgh", "Panthers"] },
      { name: "SMU", aliases: ["Mustangs"] },
      { name: "Stanford", aliases: ["Cardinal"] },
      { name: "Virginia", aliases: ["UVA", "Cavaliers", "Hoos"] },
      { name: "Wake Forest", aliases: ["Wake", "Demon Deacons"] },
    ],
  },
  {
    category: "champions",
    entityKind: "school",
    collisionGroup: "achievements",
    prompts: [
      "Name a program that won a college football national championship from 2000 through 2024.",
      "Name a national champion in college football from the 2000 through 2024 seasons.",
      "Name a school that celebrated a college football national title between 2000 and 2024.",
      "Name a program that reached the top of college football between 2000 and 2024.",
      "Name a college football champion from the 2000 through 2024 seasons.",
    ],
    answers: [
      { name: "Alabama", aliases: ["Bama", "Crimson Tide"] },
      { name: "Georgia", aliases: ["UGA", "Bulldogs", "Georgia Bulldogs"] },
      { name: "Ohio State", aliases: ["OSU", "Buckeyes", "Ohio St"] },
      { name: "LSU", aliases: ["Louisiana State", "LSU Tigers"] },
      { name: "Clemson", aliases: ["Clemson Tigers"] },
      { name: "Florida", aliases: ["Gators"] },
      { name: "USC", aliases: ["Southern Cal", "Trojans"] },
      { name: "Texas", aliases: ["Longhorns", "UT"] },
    ],
    alsoAcceptedAnswers: [
      { name: "Auburn", aliases: ["Auburn Tigers"] },
      { name: "Florida State", aliases: ["FSU", "Seminoles"] },
      { name: "Miami", aliases: ["The U", "Hurricanes", "Miami Hurricanes"] },
      { name: "Michigan", aliases: ["Wolverines"] },
      { name: "Oklahoma", aliases: ["OU", "Sooners"] },
    ],
  },
  {
    category: "players",
    entityKind: "person",
    collisionGroup: "quarterbacks",
    prompts: [
      "Name a Heisman Trophy-winning quarterback.",
      "Name a quarterback who won the Heisman.",
      "Name a Heisman quarterback from the modern era.",
      "Name a college quarterback whose season ended with the Heisman Trophy.",
      "Name a quarterback you remember holding the Heisman.",
    ],
    answers: [
      "Tim Tebow",
      "Cam Newton",
      "Joe Burrow",
      "Lamar Jackson",
      "Johnny Manziel",
      "Baker Mayfield",
      "Marcus Mariota",
      "Jameis Winston",
    ],
    alsoAcceptedAnswers: [
      "Caleb Williams",
      "Kyler Murray",
      "Sam Bradford",
      "Troy Smith",
      "Carson Palmer",
      "Matt Leinart",
      "Robert Griffin III",
      "Jayden Daniels",
    ],
  },
  {
    category: "players",
    entityKind: "person",
    collisionGroup: "running-backs",
    prompts: [
      "Name a running back who won the Heisman Trophy.",
      "Name a Heisman-winning running back.",
      "Name a college running back remembered for a Heisman season.",
      "Name a running back whose college peak earned the Heisman.",
      "Name a Heisman back fans still talk about.",
    ],
    answers: [
      "Barry Sanders",
      "Derrick Henry",
      "Reggie Bush",
      "Eddie George",
      "Ricky Williams",
      "Mark Ingram",
      "Ron Dayne",
      "Bo Jackson",
    ],
    alsoAcceptedAnswers: [
      "Herschel Walker",
      "Marcus Allen",
      "Tony Dorsett",
      "Earl Campbell",
      "Rashaan Salaam",
      "Charles White",
      "George Rogers",
      "Mike Rozier",
    ],
  },
  {
    category: "players",
    entityKind: "person",
    collisionGroup: "running-backs",
    prompts: [
      "Name a legendary college running back.",
      "Name a college back who felt impossible to tackle.",
      "Name a running back you would put in a college football highlight reel.",
      "Name a college running back whose name still gets huge respect.",
      "Name a back who belongs in an all-time college football conversation.",
    ],
    answers: [
      "Barry Sanders",
      "Bo Jackson",
      "Herschel Walker",
      "Reggie Bush",
      "Derrick Henry",
      "Ricky Williams",
      "Adrian Peterson",
      "Earl Campbell",
    ],
    alsoAcceptedAnswers: [
      "LaDainian Tomlinson",
      "Marshall Faulk",
      "Eric Dickerson",
      "Archie Griffin",
      "Tony Dorsett",
      "Marcus Allen",
      "Jonathan Taylor",
      "Saquon Barkley",
    ],
  },
  {
    category: "players",
    entityKind: "person",
    collisionGroup: "receivers",
    prompts: [
      "Name a legendary college wide receiver.",
      "Name a receiver whose college career produced unforgettable highlights.",
      "Name a college wideout who became a Saturday superstar.",
      "Name a receiver you would include in an all-time college football debate.",
      "Name a college receiver remembered for looking different from everyone else.",
    ],
    answers: [
      "Larry Fitzgerald",
      "Randy Moss",
      "Calvin Johnson",
      "DeVonta Smith",
      "Michael Crabtree",
      "Justin Blackmon",
      "Amari Cooper",
      "Marvin Harrison Jr.",
    ],
    alsoAcceptedAnswers: [
      "Jerry Rice",
      "Fred Biletnikoff",
      "Peter Warrick",
      "Keyshawn Johnson",
      "Ja'Marr Chase",
      "Julio Jones",
      "CeeDee Lamb",
      "Torry Holt",
    ],
  },
  {
    category: "players",
    entityKind: "person",
    collisionGroup: "defenders",
    prompts: [
      "Name a legendary college defensive player.",
      "Name a defender whose college tape still gets talked about.",
      "Name a college defensive star who could take over games.",
      "Name a defender who belongs in a modern college football legend conversation.",
      "Name a college defensive player you would never want to block.",
    ],
    answers: [
      "Ndamukong Suh",
      "Charles Woodson",
      "Jadeveon Clowney",
      "Manti Te'o",
      "Chase Young",
      "Will Anderson Jr.",
      "Myles Garrett",
      "Micah Parsons",
    ],
    alsoAcceptedAnswers: [
      "Derrick Thomas",
      "Ed Reed",
      "Julius Peppers",
      "Luke Kuechly",
      "Terrell Suggs",
      "Von Miller",
      "Khalil Mack",
      "Champ Bailey",
    ],
  },
] as const);
