import { expandSportsFeudFamilies } from "./sportsFeudAuthoredHelpers";

export const CFB_SPORTS_FEUD_FAST_5 = expandSportsFeudFamilies("cfb-fast5", [
  {
    category: "player-traits",
    entityKind: "person",
    collisionGroup: "clutch",
    prompts: [
      "Name a college football player you associate with clutch moments.",
      "Name a player you would trust with one final college drive.",
      "Name a college star who seemed built for the biggest moment.",
      "Name a player whose college legacy includes huge late-game plays.",
      "Name a college football legend you would want with the game on the line.",
    ],
    answers: [
      "Vince Young",
      "Tim Tebow",
      "Cam Newton",
      "Joe Burrow",
      "Deshaun Watson",
      "Baker Mayfield",
      "Johnny Manziel",
      "Reggie Bush",
    ],
    alsoAcceptedAnswers: [
      "Stetson Bennett",
      "Trevor Lawrence",
      "Jalen Hurts",
      "Tua Tagovailoa",
      "Matt Leinart",
      "Tommie Frazier",
      "Doug Flutie",
      "Caleb Williams",
    ],
  },
  {
    category: "player-traits",
    entityKind: "person",
    collisionGroup: "speed",
    prompts: [
      "Name a college football player known for elite speed.",
      "Name a college star you remember simply running away from people.",
      "Name a player whose speed jumped off the screen on Saturdays.",
      "Name a college football player defenders hated chasing.",
      "Name a player you would pick for a college football footrace.",
    ],
    answers: [
      "Reggie Bush",
      "De'Anthony Thomas",
      "Ted Ginn Jr.",
      "Jaylen Waddle",
      "Percy Harvin",
      "CJ Spiller",
      "Xavier Worthy",
      "Chris Johnson",
    ],
    alsoAcceptedAnswers: [
      "Tavon Austin",
      "Marquise Goodwin",
      "Henry Ruggs III",
      "Raheem Mostert",
      "Jacoby Ford",
      "Dri Archer",
      "Jeff Demps",
      "Tyreek Hill",
    ],
  },
  {
    category: "player-traits",
    entityKind: "person",
    collisionGroup: "power",
    prompts: [
      "Name a college running back known for power.",
      "Name a back you would least want to tackle in the fourth quarter.",
      "Name a college running back who could run through contact.",
      "Name a power back whose college highlights look painful for defenders.",
      "Name a college back you associate with downhill running.",
    ],
    answers: [
      "Derrick Henry",
      "Bo Jackson",
      "Herschel Walker",
      "Earl Campbell",
      "Ron Dayne",
      "Jonathan Taylor",
      "Nick Chubb",
      "Leonard Fournette",
    ],
    alsoAcceptedAnswers: [
      "Eddie George",
      "Adrian Peterson",
      "Marshawn Lynch",
      "Jerome Bettis",
      "Najee Harris",
      "Trent Richardson",
      "Beanie Wells",
    ],
  },
  {
    category: "quarterbacks",
    entityKind: "person",
    collisionGroup: "quarterbacks",
    prompts: [
      "Name a famous dual-threat college quarterback.",
      "Name a college quarterback who could beat you with his legs.",
      "Name a quarterback whose rushing ability changed the game plan.",
      "Name a college QB you remember as a true run-pass threat.",
      "Name a quarterback defenders had to account for as a runner.",
    ],
    answers: [
      "Cam Newton",
      "Lamar Jackson",
      "Tim Tebow",
      "Vince Young",
      "Johnny Manziel",
      "Michael Vick",
      "Pat White",
      "Denard Robinson",
    ],
    alsoAcceptedAnswers: [
      "Kyler Murray",
      "Robert Griffin III",
      "Jalen Hurts",
      "Marcus Mariota",
      "Terrelle Pryor",
      "Colin Kaepernick",
      "Antwaan Randle El",
    ],
  },
  {
    category: "quarterbacks",
    entityKind: "person",
    collisionGroup: "quarterbacks",
    prompts: [
      "Name a college quarterback known more for passing than running.",
      "Name a classic pocket-passing college quarterback.",
      "Name a quarterback whose college game was built around throwing the ball.",
      "Name a college QB you remember for command from the pocket.",
      "Name a passer whose college highlights are mostly throws, not scrambles.",
    ],
    answers: [
      "Joe Burrow",
      "Matt Leinart",
      "Sam Bradford",
      "Mac Jones",
      "Carson Palmer",
      "Andrew Luck",
      "Philip Rivers",
      "Tua Tagovailoa",
    ],
    alsoAcceptedAnswers: [
      "Peyton Manning",
      "Tom Brady",
      "Drew Brees",
      "Eli Manning",
      "Brady Quinn",
      "Kellen Moore",
      "Colt Brennan",
      "Graham Harrell",
    ],
  },
  {
    category: "defenders",
    entityKind: "person",
    collisionGroup: "pass-rushers",
    prompts: [
      "Name a college pass rusher who became a national star.",
      "Name a defender quarterbacks hated seeing off the edge.",
      "Name a college defensive end or edge player known for getting after the quarterback.",
      "Name a pass rusher whose college tape screamed first-round talent.",
      "Name a college defender you associate with sacks and pressure.",
    ],
    answers: [
      "Chase Young",
      "Myles Garrett",
      "Jadeveon Clowney",
      "Joey Bosa",
      "Nick Bosa",
      "Will Anderson Jr.",
      "Aidan Hutchinson",
      "Von Miller",
    ],
    alsoAcceptedAnswers: [
      "Khalil Mack",
      "Terrell Suggs",
      "Dwight Freeney",
      "Derrick Thomas",
      "Julius Peppers",
      "Brian Orakpo",
      "Kayvon Thibodeaux",
    ],
  },
  {
    category: "special-teams",
    entityKind: "person",
    collisionGroup: "returners",
    prompts: [
      "Name a college football player known for dangerous returns.",
      "Name a return man who made punts or kickoffs feel exciting.",
      "Name a college star you would avoid kicking to.",
      "Name a player remembered for electric special-teams returns.",
      "Name a college returner who could flip a game in seconds.",
    ],
    answers: [
      "Devin Hester",
      "Ted Ginn Jr.",
      "Reggie Bush",
      "Dante Hall",
      "Desmond Howard",
      "Christian McCaffrey",
      "De'Anthony Thomas",
      "Antonio Brown",
    ],
    alsoAcceptedAnswers: [
      "Tavon Austin",
      { name: "Rocket Ismail", aliases: ["Raghib Ismail", "Rocket"] },
      "Johnny Rodgers",
      "Javier Arenas",
      "Tyrann Mathieu",
      "Leodis McKelvin",
    ],
  },
  {
    category: "young-stars",
    entityKind: "person",
    collisionGroup: "young-stars",
    prompts: [
      "Name a college football player who became a star very early in his career.",
      "Name a player who looked ready for the spotlight almost immediately in college.",
      "Name a college star who made a huge impact as a freshman or young player.",
      "Name a player fans knew was special before he was an upperclassman.",
      "Name a college player whose breakout came almost right away.",
    ],
    answers: [
      "Adrian Peterson",
      "Trevor Lawrence",
      "Caleb Williams",
      "Sammy Watkins",
      "Marcus Lattimore",
      "Jadeveon Clowney",
      "Derek Stingley Jr.",
      "Maurice Clarett",
    ],
    alsoAcceptedAnswers: [
      "Jameis Winston",
      "Brock Bowers",
      "Johnny Manziel",
      "Saquon Barkley",
      "Todd Gurley",
      "Amari Cooper",
      "Jeremiah Smith",
    ],
  },
  {
    category: "underdogs",
    entityKind: "school",
    collisionGroup: "programs",
    prompts: [
      "Name a college football program famous for a giant-killing upset.",
      "Name a school that makes you think of a memorable underdog win.",
      "Name a program that has crashed a bigger team's party.",
      "Name a college team fans remember for an upset that shocked the country.",
      "Name an underdog program that has had a Cinderella football moment.",
    ],
    answers: [
      { name: "Boise State", aliases: ["Broncos"] },
      { name: "Appalachian State", aliases: ["App State", "Mountaineers"] },
      { name: "UCF", aliases: ["Knights"] },
      { name: "TCU", aliases: ["Horned Frogs"] },
      { name: "Utah", aliases: ["Utes"] },
      { name: "Cincinnati", aliases: ["Bearcats"] },
      { name: "Houston", aliases: ["Cougars"] },
      { name: "James Madison", aliases: ["JMU", "Dukes"] },
    ],
    alsoAcceptedAnswers: [
      { name: "Northern Illinois", aliases: ["NIU", "Huskies"] },
      { name: "Fresno State", aliases: ["Bulldogs"] },
      { name: "Marshall", aliases: ["Herd", "Thundering Herd"] },
      { name: "Louisiana-Monroe", aliases: ["ULM", "Warhawks"] },
      { name: "Troy", aliases: ["Trojans"] },
      { name: "Georgia Southern", aliases: ["Eagles"] },
      { name: "Tulane", aliases: ["Green Wave"] },
    ],
  },
  {
    category: "culture",
    entityKind: "school",
    collisionGroup: "culture",
    prompts: [
      "Name a college football program known for great uniforms.",
      "Name a school whose football look gets fans talking.",
      "Name a program with an instantly recognizable uniform identity.",
      "Name a college team whose uniform reveal can become an event.",
      "Name a program you would put in a best-uniforms conversation.",
    ],
    answers: [
      { name: "Oregon", aliases: ["Ducks"] },
      { name: "Notre Dame", aliases: ["ND", "Fighting Irish"] },
      { name: "Michigan", aliases: ["Wolverines"] },
      { name: "Penn State", aliases: ["PSU", "Nittany Lions"] },
      { name: "USC", aliases: ["Southern Cal", "Trojans"] },
      { name: "Texas", aliases: ["Longhorns"] },
      { name: "LSU", aliases: ["Louisiana State", "LSU Tigers"] },
      { name: "Miami", aliases: ["The U", "Hurricanes", "Miami Hurricanes"] },
    ],
    alsoAcceptedAnswers: [
      { name: "Ohio State", aliases: ["OSU", "Buckeyes", "Ohio St"] },
      { name: "Florida State", aliases: ["FSU", "Seminoles"] },
      { name: "Georgia", aliases: ["UGA", "Bulldogs", "Georgia Bulldogs"] },
      { name: "Tennessee", aliases: ["Vols", "Volunteers"] },
      { name: "Clemson", aliases: ["Clemson Tigers"] },
      { name: "Miami", aliases: ["The U", "Hurricanes", "Miami Hurricanes"] },
      { name: "UCLA", aliases: ["Bruins"] },
      { name: "North Carolina", aliases: ["UNC", "Tar Heels"] },
    ],
  },
] as const);
