import { expandSportsFeudFamilies } from "./sportsFeudAuthoredHelpers";

export const CFB_SPORTS_FEUD_FAST_2 = expandSportsFeudFamilies("cfb-fast2", [
  {
    category: "school-stars",
    entityKind: "person",
    collisionGroup: "quarterbacks",
    prompts: [
      "Name an Alabama quarterback from the 2000 season or later.",
      "Name a memorable Alabama quarterback from 2000 or later.",
      "Name a quarterback associated with Alabama football since 2000.",
      "Name a Crimson Tide quarterback from the 2000s or later.",
      "Name an Alabama quarterback who became a national name since 2000.",
    ],
    answers: [
      "Tua Tagovailoa",
      "Jalen Hurts",
      "Bryce Young",
      "Mac Jones",
      "AJ McCarron",
      "Greg McElroy",
      "Blake Sims",
      "Jake Coker",
    ],
    alsoAcceptedAnswers: ["Jalen Milroe", "John Parker Wilson", "Brodie Croyle"],
  },
  {
    category: "school-stars",
    entityKind: "person",
    collisionGroup: "quarterbacks",
    prompts: [
      "Name an Ohio State quarterback from the 2000 season or later.",
      "Name a memorable Ohio State quarterback from 2000 or later.",
      "Name a Buckeyes quarterback fans remember from the 2000s or later.",
      "Name a quarterback associated with Ohio State football since 2000.",
      "Name an Ohio State signal caller who became a national name since 2000.",
    ],
    answers: [
      "CJ Stroud",
      "Justin Fields",
      "Dwayne Haskins",
      "JT Barrett",
      "Braxton Miller",
      "Troy Smith",
      "Terrelle Pryor",
      "Cardale Jones",
    ],
    alsoAcceptedAnswers: ["Craig Krenzel", "Will Howard", "Kyle McCord", "Todd Boeckman"],
  },
  {
    category: "school-stars",
    entityKind: "person",
    collisionGroup: "quarterbacks",
    prompts: [
      "Name a USC quarterback from the 2000 season or later.",
      "Name a USC quarterback fans remember from 2000 or later.",
      "Name a Trojans quarterback from the 2000s or later.",
      "Name a quarterback associated with USC football since 2000.",
      "Name a USC signal caller who became a national name since 2000.",
    ],
    answers: [
      "Matt Leinart",
      "Carson Palmer",
      "Caleb Williams",
      "Sam Darnold",
      "Mark Sanchez",
      "Matt Barkley",
      "John David Booty",
      "Cody Kessler",
    ],
    alsoAcceptedAnswers: ["Kedon Slovis", "JT Daniels", "Miller Moss", "Jayden Maiava"],
  },
  {
    category: "school-stars",
    entityKind: "person",
    collisionGroup: "quarterbacks",
    prompts: [
      "Name an Oklahoma quarterback from the 2000 season or later.",
      "Name an Oklahoma quarterback from a big offensive era since 2000.",
      "Name a Sooners quarterback fans remember from the 2000s or later.",
      "Name a quarterback associated with Oklahoma football since 2000.",
      "Name an Oklahoma signal caller who became a national star since 2000.",
    ],
    answers: [
      "Baker Mayfield",
      "Kyler Murray",
      "Jalen Hurts",
      "Sam Bradford",
      "Jason White",
      "Landry Jones",
      "Spencer Rattler",
      "Dillon Gabriel",
    ],
    alsoAcceptedAnswers: ["Josh Heupel", "Caleb Williams", "Trevor Knight", "Blake Bell"],
  },
  {
    category: "school-stars",
    entityKind: "person",
    collisionGroup: "quarterbacks",
    prompts: [
      "Name a Texas quarterback from the 2000 season or later.",
      "Name a Longhorns quarterback fans remember from 2000 or later.",
      "Name a Texas quarterback from a memorable season since 2000.",
      "Name a quarterback associated with Texas football since 2000.",
      "Name a Texas signal caller who became a national name since 2000.",
    ],
    answers: [
      "Vince Young",
      "Colt McCoy",
      "Quinn Ewers",
      "Sam Ehlinger",
      "Chris Simms",
      "Major Applewhite",
      "Case McCoy",
      "Garrett Gilbert",
    ],
    alsoAcceptedAnswers: ["David Ash", "Shane Buechele", "Arch Manning"],
  },
  {
    category: "school-stars",
    entityKind: "person",
    collisionGroup: "players",
    prompts: [
      "Name an LSU player who became a major college football star since 2000.",
      "Name a player you strongly associate with LSU football since 2000.",
      "Name an LSU star from the 2000s or later.",
      "Name a Tigers player who became a national name at LSU since 2000.",
      "Name an LSU player from 2000 or later you would put on a program highlight reel.",
    ],
    answers: [
      "Joe Burrow",
      "Tyrann Mathieu",
      "Ja'Marr Chase",
      "Patrick Peterson",
      "Leonard Fournette",
      "Odell Beckham Jr.",
      "Justin Jefferson",
      "Glenn Dorsey",
    ],
    alsoAcceptedAnswers: [
      "Jayden Daniels",
      "Malik Nabers",
      "Devin White",
      "Grant Delpit",
      "Clyde Edwards-Helaire",
      "Brian Thomas Jr.",
      "Jamal Adams",
      "Jarvis Landry",
    ],
  },
  {
    category: "school-stars",
    entityKind: "person",
    collisionGroup: "players",
    prompts: [
      "Name a Michigan player who became a major college football star since 2000.",
      "Name a player you strongly associate with Michigan football since 2000.",
      "Name a Wolverines star fans remember from the 2000s or later.",
      "Name a Michigan player whose career since 2000 became part of program history.",
      "Name a Michigan player from 2000 or later you would expect on a program legends list.",
    ],
    answers: [
      "Charles Woodson",
      "Desmond Howard",
      "Tom Brady",
      "Blake Corum",
      "Aidan Hutchinson",
      "Denard Robinson",
      "Mike Hart",
      "JJ McCarthy",
    ],
    alsoAcceptedAnswers: [
      "Braylon Edwards",
      "Jabrill Peppers",
      "Jake Long",
      "Chad Henne",
      "Donovan Edwards",
      "Will Johnson",
      "Mason Graham",
      "David Ojabo",
    ],
  },
  {
    category: "school-stars",
    entityKind: "person",
    collisionGroup: "players",
    prompts: [
      "Name a Notre Dame player college football fans remember from 2000 or later.",
      "Name a player strongly associated with Notre Dame football since 2000.",
      "Name a Fighting Irish star from the 2000s or later.",
      "Name a Notre Dame player who became a national name since 2000.",
      "Name a Notre Dame player from 2000 or later you would expect in a legends conversation.",
    ],
    answers: [
      "Tim Brown",
      "Joe Montana",
      "Jerome Bettis",
      "Manti Te'o",
      "Brady Quinn",
      "Rocket Ismail",
      "Michael Mayer",
      "Jaylon Smith",
    ],
    alsoAcceptedAnswers: [
      "Golden Tate",
      "Kyle Hamilton",
      "Jeff Samardzija",
      "Michael Floyd",
      "Harrison Smith",
      "Kyren Williams",
      "Tyler Eifert",
    ],
  },
  {
    category: "school-stars",
    entityKind: "person",
    collisionGroup: "players",
    prompts: [
      "Name a Georgia player who became a major college football star since 2000.",
      "Name a player strongly associated with Georgia football since 2000.",
      "Name a Bulldogs star fans remember from the 2000s or later.",
      "Name a Georgia player from 2000 or later you would put on a program highlight reel.",
      "Name a Georgia player who helped shape the program since 2000.",
    ],
    answers: [
      "Herschel Walker",
      "Stetson Bennett",
      "Brock Bowers",
      "Nick Chubb",
      "Todd Gurley",
      "Roquan Smith",
      "Jalen Carter",
      "Matthew Stafford",
    ],
    alsoAcceptedAnswers: [
      "A.J. Green",
      "David Pollack",
      "Aaron Murray",
      "Jordan Davis",
      "Nakobe Dean",
      "George Pickens",
      "Sony Michel",
      "Knowshon Moreno",
    ],
  },
  {
    category: "school-stars",
    entityKind: "person",
    collisionGroup: "players",
    prompts: [
      "Name a Clemson player who became a major college football star since 2000.",
      "Name a player strongly associated with Clemson football since 2000.",
      "Name a Tigers star from Clemson's modern era since 2000.",
      "Name a Clemson player fans remember from a huge game since 2000.",
      "Name a Clemson player from 2000 or later you would expect in a legends conversation.",
    ],
    answers: [
      "Deshaun Watson",
      "Trevor Lawrence",
      "CJ Spiller",
      "Sammy Watkins",
      "DeAndre Hopkins",
      "Christian Wilkins",
      "Travis Etienne",
      "Isaiah Simmons",
    ],
    alsoAcceptedAnswers: ["Tajh Boyd", "Tee Higgins", "Dexter Lawrence", "Vic Beasley", "Mike Williams", "Ben Boulware", "Wayne Gallman"],
  },
] as const);
