import { expandSportsFeudFamilies } from "./sportsFeudAuthoredHelpers";

export const CFB_SPORTS_FEUD_MAIN = expandSportsFeudFamilies("cfb-main", [
  {
    category: "program-identity",
    entityKind: "school",
    collisionGroup: "programs",
    prompts: [
      "Name a college football program known for producing great running backs.",
      "Name a school you associate with elite college running backs.",
      "Name a program where great running back play feels like part of the brand.",
      "Name a college team that seems to keep finding star running backs.",
      "Name a school a top running back recruit would love to join.",
    ],
    answers: ["Alabama", "Georgia", "Ohio State", "USC", "Texas", "Oklahoma", "Wisconsin", "Penn State"],
  },
  {
    category: "program-identity",
    entityKind: "school",
    collisionGroup: "programs",
    prompts: [
      "Name a college football program famous for producing quarterbacks.",
      "Name a school you associate with big-name college quarterbacks.",
      "Name a program where quarterback play is a major part of the identity.",
      "Name a school that always seems to have a recognizable quarterback.",
      "Name a program a blue-chip quarterback recruit would notice immediately.",
    ],
    answers: ["USC", "Oklahoma", "Alabama", "Ohio State", "LSU", "Clemson", "Miami", "Michigan"],
  },
  {
    category: "program-identity",
    entityKind: "school",
    collisionGroup: "programs",
    prompts: [
      "Name a college football program you associate with elite defense.",
      "Name a school that makes you think of dominant college defenses.",
      "Name a program known for sending scary defenders to the NFL.",
      "Name a college team whose identity often starts on defense.",
      "Name a program you would hate to face with a freshman quarterback.",
    ],
    answers: ["Alabama", "Georgia", "Ohio State", "LSU", "Michigan", "Clemson", "Penn State", "Miami"],
  },
  {
    category: "style-identity",
    entityKind: "school",
    collisionGroup: "programs",
    prompts: [
      "Name a college football program you associate with explosive offense.",
      "Name a school that makes you think of points, tempo, and big plays.",
      "Name a program famous for making offense look fast.",
      "Name a college team you expect to have creative offensive wrinkles.",
      "Name a program that has helped shape modern college offense.",
    ],
    answers: ["Oregon", "Oklahoma", "USC", "Florida", "Texas Tech", "Baylor", "West Virginia", "UCF"],
  },
  {
    category: "history-legacy",
    entityKind: "school",
    collisionGroup: "programs",
    prompts: [
      "Name a college football blue blood.",
      "Name a program that belongs in almost any college football history conversation.",
      "Name a school with one of the strongest all-time football brands.",
      "Name a program whose history alone makes the logo feel important.",
      "Name a school fans would expect to see in a blue-blood debate.",
    ],
    answers: ["Alabama", "Ohio State", "Michigan", "Notre Dame", "Oklahoma", "USC", "Texas", "Nebraska"],
  },
  {
    category: "player-identity",
    entityKind: "person",
    collisionGroup: "quarterbacks",
    prompts: [
      "Name a quarterback you immediately associate with winning the Heisman Trophy.",
      "Name a Heisman-winning college quarterback almost every football fan remembers.",
      "Name a quarterback whose Heisman season became part of college football history.",
      "Name a college quarterback who felt larger than life during his Heisman run.",
      "Name a Heisman quarterback you would expect to get named quickly in a sports bar.",
    ],
    answers: ["Tim Tebow", "Cam Newton", "Joe Burrow", "Johnny Manziel", "Lamar Jackson", "Baker Mayfield", "Marcus Mariota", "Jameis Winston"],
  },
  {
    category: "player-identity",
    entityKind: "person",
    collisionGroup: "players",
    prompts: [
      "Name a player who had one of the most dominant individual college football seasons ever.",
      "Name a college player whose peak season felt almost unfair.",
      "Name a player remembered for taking over an entire college football season.",
      "Name a college star whose best year still gets brought up in all-time season debates.",
      "Name a player whose single-season college peak became legendary.",
    ],
    answers: ["Barry Sanders", "Joe Burrow", "Cam Newton", "Reggie Bush", "Derrick Henry", "Lamar Jackson", "Tim Tebow", "Vince Young"],
  },
  {
    category: "player-identity",
    entityKind: "person",
    collisionGroup: "quarterbacks",
    prompts: [
      "Name an iconic college quarterback from the 2000s or later.",
      "Name a college quarterback whose name instantly takes you back to a great season.",
      "Name a modern-era college quarterback fans still talk about constantly.",
      "Name a quarterback whose college career created unforgettable Saturdays.",
      "Name a quarterback you would put in a modern college football time capsule.",
    ],
    answers: ["Tim Tebow", "Vince Young", "Cam Newton", "Joe Burrow", "Johnny Manziel", "Lamar Jackson", "Trevor Lawrence", "Matt Leinart"],
  },
  {
    category: "coach-legacy",
    entityKind: "person",
    collisionGroup: "coaches",
    prompts: [
      "Name a college football coach strongly associated with a dynasty.",
      "Name a coach whose program dominated college football for a sustained stretch.",
      "Name a coach you think of when someone says college football dynasty.",
      "Name a college coach who built a championship machine.",
      "Name a coach whose era changed the national title picture.",
    ],
    answers: ["Nick Saban", "Bear Bryant", "Bobby Bowden", "Pete Carroll", "Urban Meyer", "Tom Osborne", "Dabo Swinney", "Bud Wilkinson"],
  },
  {
    category: "coach-identity",
    entityKind: "person",
    collisionGroup: "coaches",
    prompts: [
      "Name a college football coach known for offensive innovation.",
      "Name a coach whose offense changed how people talked about college football.",
      "Name a college coach associated with a distinctive offensive system.",
      "Name a coach who made opposing defensive coordinators lose sleep.",
      "Name an offensive-minded college coach whose scheme became part of his identity.",
    ],
    answers: ["Steve Spurrier", "Mike Leach", "Chip Kelly", "Lincoln Riley", "Hal Mumme", "Gus Malzahn", "Rich Rodriguez", "Dana Holgorsen"],
  },
  {
    category: "rivalries",
    entityKind: "other",
    collisionGroup: "rivalries",
    prompts: [
      "Name a college football rivalry almost every fan knows.",
      "Name a rivalry game that feels bigger than an ordinary Saturday.",
      "Name a college rivalry you would explain to a new fan first.",
      "Name a rivalry where the records almost stop mattering.",
      "Name a college football matchup with instant rivalry energy.",
    ],
    answers: ["Ohio State-Michigan", "Alabama-Auburn", "Texas-Oklahoma", "Army-Navy", "Florida-Georgia", "USC-Notre Dame", "Florida State-Miami", "Oregon-Washington"],
  },
  {
    category: "venues",
    entityKind: "school",
    collisionGroup: "venues",
    prompts: [
      "Name one of the toughest places to play a road game in college football.",
      "Name a college stadium where the crowd can become part of the game.",
      "Name a road environment that can rattle even a ranked team.",
      "Name a college football venue famous for being intimidating.",
      "Name a stadium you would least want to visit with a freshman quarterback.",
    ],
    answers: ["LSU", "Penn State", "Tennessee", "Texas A&M", "Ohio State", "Oregon", "Georgia", "Alabama"],
  },
  {
    category: "traditions",
    entityKind: "other",
    collisionGroup: "traditions",
    prompts: [
      "Name a college football tradition even casual fans recognize.",
      "Name a Saturday tradition that instantly tells you which school you are watching.",
      "Name a pregame or in-game college tradition with national recognition.",
      "Name a college football ritual fans would hate to lose.",
      "Name a school tradition that belongs on a college football bucket list.",
    ],
    answers: ["Ohio State dotting the i", "Clemson running down the hill", "Virginia Tech Enter Sandman", "Wisconsin Jump Around", "Texas A&M 12th Man", "Florida State spear plant", "Notre Dame Play Like a Champion Today", "Oklahoma Sooner Schooner"],
  },
  {
    category: "bowl-history",
    entityKind: "other",
    collisionGroup: "bowls",
    prompts: [
      "Name a college football bowl game almost every fan knows.",
      "Name a bowl that sounds prestigious before you even know the matchup.",
      "Name a bowl game tied to college football history.",
      "Name a postseason bowl you would expect a casual fan to recognize.",
      "Name a bowl that has hosted major national-title-level stakes.",
    ],
    answers: ["Rose Bowl", "Sugar Bowl", "Orange Bowl", "Cotton Bowl", "Fiesta Bowl", "Peach Bowl", "Citrus Bowl", "Gator Bowl"],
  },
  {
    category: "history-legacy",
    entityKind: "other",
    collisionGroup: "conferences",
    prompts: [
      "Name a conference that has played a major role in college football history.",
      "Name a conference brand college football fans instantly recognize.",
      "Name a league that has shaped the national college football conversation.",
      "Name a conference whose old standings can trigger instant nostalgia.",
      "Name a conference name that belongs in college football history.",
    ],
    answers: ["SEC", "Big Ten", "ACC", "Big 12", "Pac-12", "Southwest Conference", "Big East", "WAC"],
  },
  {
    category: "moments",
    entityKind: "other",
    collisionGroup: "moments",
    prompts: [
      "Name an iconic college football play or moment from the modern era.",
      "Name a college football moment that still gets replayed years later.",
      "Name a single play that instantly identifies a famous college football game.",
      "Name a college football ending fans remember by a nickname.",
      "Name a moment that can make a fan remember exactly where they were.",
    ],
    answers: ["Kick Six", "Boise State Statue of Liberty", "Vince Young 4th-and-5", "Prayer at Jordan-Hare", "Michigan State trouble with the snap", "Bush Push", "Bluegrass Miracle", "Appalachian State blocks Michigan field goal"],
  },
  {
    category: "achievements",
    entityKind: "other",
    collisionGroup: "achievements",
    prompts: [
      "Name something that can make a college football season legendary.",
      "Name an accomplishment that can define a college football season.",
      "Name something fans dream about before a college season starts.",
      "Name an achievement that can turn a good season into an all-time one.",
      "Name something a team can accomplish that fans will talk about for decades.",
    ],
    answers: ["National championship", "Undefeated season", "Heisman winner", "Rivalry win", "Playoff run", "Conference title", "Iconic bowl win", "Finish ranked No. 1"],
  },
  {
    category: "positions",
    entityKind: "other",
    collisionGroup: "positions",
    prompts: [
      "Name a college football position fans love to watch.",
      "Name a position that can produce the biggest Saturday stars.",
      "Name a position recruits often become household names playing.",
      "Name a football position that can take over a college game.",
      "Name a position group that can become the identity of a team.",
    ],
    answers: ["Quarterback", "Running back", "Wide receiver", "Linebacker", "Defensive end", "Cornerback", "Safety", "Tight end"],
  },
  {
    category: "traits",
    entityKind: "other",
    collisionGroup: "traits",
    prompts: [
      "Name a trait every college football coach wants in a quarterback.",
      "Name a quarterback trait that can separate a star from an average starter.",
      "Name something scouts notice quickly when evaluating a college quarterback.",
      "Name a quarterback quality that matters late in a close game.",
      "Name a trait fans brag about when they love their quarterback.",
    ],
    answers: ["Accuracy", "Arm strength", "Processing", "Mobility", "Poise", "Leadership", "Anticipation", "Toughness"],
  },
  {
    category: "culture",
    entityKind: "school",
    collisionGroup: "culture",
    prompts: [
      "Name a college football program known for an iconic uniform look.",
      "Name a school whose football uniform is recognizable immediately.",
      "Name a program with a uniform fans argue about in a good way.",
      "Name a school whose colors look unmistakably college football.",
      "Name a program you would include in a college football uniform conversation.",
    ],
    answers: ["Oregon", "Penn State", "Notre Dame", "Michigan", "Alabama", "LSU", "USC", "Texas"],
  },
] as const);
