import { expandSportsFeudFamilies } from "./sportsFeudAuthoredHelpers";

export const CFB_SPORTS_FEUD_MAIN = expandSportsFeudFamilies("cfb-main", [
  {
    category: "program-identity",
    entityKind: "school",
    collisionGroup: "programs",
    prompts: [
      "Name a college football program known for producing great running backs.",
      "Name a school you associate with elite college running backs.",
      "Name a program where great running back play feels like part of the brand.",
      "Name a college team that seems to keep finding star running backs.",
      "Name a school a top running back recruit would love to join.",
    ],
    answers: [
      { name: "Alabama", aliases: ["Bama", "Crimson Tide"] },
      { name: "Georgia", aliases: ["UGA", "Bulldogs", "Georgia Bulldogs"] },
      { name: "Ohio State", aliases: ["OSU", "Buckeyes", "Ohio St"] },
      { name: "USC", aliases: ["Southern Cal", "Trojans"] },
      { name: "Texas", aliases: ["Longhorns"] },
      { name: "Oklahoma", aliases: ["OU", "Sooners"] },
      { name: "Wisconsin", aliases: ["Badgers"] },
      { name: "Penn State", aliases: ["PSU", "Nittany Lions"] },
    ],
    alsoAcceptedAnswers: [
      { name: "Auburn", aliases: ["Auburn Tigers"] },
      { name: "LSU", aliases: ["Louisiana State", "LSU Tigers"] },
      { name: "Michigan", aliases: ["Wolverines"] },
      { name: "Nebraska", aliases: ["Huskers", "Cornhuskers"] },
      { name: "Tennessee", aliases: ["Vols", "Volunteers"] },
      { name: "Florida State", aliases: ["FSU", "Seminoles"] },
      { name: "Miami", aliases: ["The U", "Hurricanes", "Miami Hurricanes"] },
      { name: "Notre Dame", aliases: ["ND", "Fighting Irish"] },
    ],
  },
  {
    category: "program-identity",
    entityKind: "school",
    collisionGroup: "programs",
    prompts: [
      "Name a college football program famous for producing quarterbacks.",
      "Name a school you associate with big-name college quarterbacks.",
      "Name a program where quarterback play is a major part of the identity.",
      "Name a school that always seems to have a recognizable quarterback.",
      "Name a program a blue-chip quarterback recruit would notice immediately.",
    ],
    answers: [
      { name: "USC", aliases: ["Southern Cal", "Trojans"] },
      { name: "Oklahoma", aliases: ["OU", "Sooners"] },
      { name: "Alabama", aliases: ["Bama", "Crimson Tide"] },
      { name: "Ohio State", aliases: ["OSU", "Buckeyes", "Ohio St"] },
      { name: "LSU", aliases: ["Louisiana State", "LSU Tigers"] },
      { name: "Clemson", aliases: ["Clemson Tigers"] },
      { name: "Miami", aliases: ["The U", "Hurricanes", "Miami Hurricanes"] },
      { name: "Michigan", aliases: ["Wolverines"] },
    ],
    alsoAcceptedAnswers: [
      { name: "Texas", aliases: ["Longhorns", "UT"] },
      { name: "Florida State", aliases: ["FSU", "Seminoles"] },
      { name: "Florida", aliases: ["Gators"] },
      { name: "Oregon", aliases: ["Ducks"] },
      { name: "Notre Dame", aliases: ["ND", "Fighting Irish"] },
      { name: "Penn State", aliases: ["PSU", "Nittany Lions"] },
      { name: "Washington", aliases: ["UW", "Huskies"] },
      { name: "Texas Tech", aliases: ["Red Raiders", "Tech"] },
    ],
  },
  {
    category: "program-identity",
    entityKind: "school",
    collisionGroup: "programs",
    prompts: [
      "Name a college football program you associate with elite defense.",
      "Name a school that makes you think of dominant college defenses.",
      "Name a program known for sending scary defenders to the NFL.",
      "Name a college team whose identity often starts on defense.",
      "Name a program you would hate to face with a freshman quarterback.",
    ],
    answers: [
      { name: "Alabama", aliases: ["Bama", "Crimson Tide"] },
      { name: "Georgia", aliases: ["UGA", "Bulldogs", "Georgia Bulldogs"] },
      { name: "Ohio State", aliases: ["OSU", "Buckeyes", "Ohio St"] },
      { name: "LSU", aliases: ["Louisiana State", "LSU Tigers"] },
      { name: "Michigan", aliases: ["Wolverines"] },
      { name: "Clemson", aliases: ["Clemson Tigers"] },
      { name: "Penn State", aliases: ["PSU", "Nittany Lions"] },
      { name: "Miami", aliases: ["The U", "Hurricanes", "Miami Hurricanes"] },
    ],
    alsoAcceptedAnswers: [
      { name: "Iowa", aliases: ["Hawkeyes"] },
      { name: "Wisconsin", aliases: ["Badgers"] },
      { name: "Notre Dame", aliases: ["ND", "Fighting Irish"] },
      { name: "Florida State", aliases: ["FSU", "Seminoles"] },
      { name: "Auburn", aliases: ["Auburn Tigers"] },
      { name: "Virginia Tech", aliases: ["VT", "Hokies"] },
      { name: "Tennessee", aliases: ["Vols", "Volunteers", "UT"] },
      { name: "Texas A&M", aliases: ["A&M", "TAMU", "Aggies"] },
    ],
  },
  {
    category: "style-identity",
    entityKind: "school",
    collisionGroup: "programs",
    prompts: [
      "Name a college football program you associate with explosive offense.",
      "Name a school that makes you think of points, tempo, and big plays.",
      "Name a program famous for making offense look fast.",
      "Name a college team you expect to have creative offensive wrinkles.",
      "Name a program that has helped shape modern college offense.",
    ],
    answers: [
      { name: "Oregon", aliases: ["Ducks"] },
      { name: "Oklahoma", aliases: ["OU", "Sooners"] },
      { name: "USC", aliases: ["Southern Cal", "Trojans"] },
      { name: "Florida", aliases: ["Gators"] },
      { name: "Texas Tech", aliases: ["Red Raiders", "Tech"] },
      { name: "Baylor", aliases: ["Bears"] },
      { name: "West Virginia", aliases: ["WVU", "Mountaineers"] },
      { name: "UCF", aliases: ["Knights"] },
    ],
    alsoAcceptedAnswers: [
      { name: "Ohio State", aliases: ["OSU", "Buckeyes", "Ohio St"] },
      { name: "Alabama", aliases: ["Bama", "Crimson Tide"] },
      { name: "LSU", aliases: ["Louisiana State", "LSU Tigers"] },
      { name: "Clemson", aliases: ["Clemson Tigers"] },
      { name: "Tennessee", aliases: ["Vols", "Volunteers", "UT"] },
      { name: "Ole Miss", aliases: ["Mississippi", "Rebels"] },
      { name: "Washington", aliases: ["UW", "Huskies"] },
      { name: "TCU", aliases: ["Horned Frogs"] },
    ],
  },
  {
    category: "history-legacy",
    entityKind: "school",
    collisionGroup: "programs",
    prompts: [
      "Name one of the traditional eight college football blue blood programs.",
      "Name a program from college football's traditional eight blue-blood group.",
      "Name one of the traditional eight programs most often called college football blue bloods.",
      "Name a school in the traditional eight-program college football blue-blood group.",
      "Name one of college football's traditional eight blue bloods.",
    ],
    answers: [
      { name: "Alabama", aliases: ["Bama", "Crimson Tide"] },
      { name: "Ohio State", aliases: ["OSU", "Buckeyes", "Ohio St"] },
      { name: "Michigan", aliases: ["Wolverines"] },
      { name: "Notre Dame", aliases: ["ND", "Fighting Irish"] },
      { name: "Oklahoma", aliases: ["OU", "Sooners"] },
      { name: "USC", aliases: ["Southern Cal", "Trojans"] },
      { name: "Texas", aliases: ["Longhorns", "UT"] },
      { name: "Nebraska", aliases: ["Huskers", "Cornhuskers"] },
    ],
  },
  {
    category: "player-identity",
    entityKind: "person",
    collisionGroup: "quarterbacks",
    prompts: [
      "Name a quarterback you immediately associate with winning the Heisman Trophy.",
      "Name a Heisman-winning college quarterback almost every football fan remembers.",
      "Name a quarterback whose Heisman season became part of college football history.",
      "Name a college quarterback who felt larger than life during his Heisman run.",
      "Name a Heisman quarterback you would expect to get named quickly in a sports bar.",
    ],
    answers: [
      "Tim Tebow",
      "Cam Newton",
      "Joe Burrow",
      "Johnny Manziel",
      "Lamar Jackson",
      "Baker Mayfield",
      "Marcus Mariota",
      "Jameis Winston",
    ],
    alsoAcceptedAnswers: [
      "Caleb Williams",
      "Kyler Murray",
      "Sam Bradford",
      "Troy Smith",
      "Carson Palmer",
      "Matt Leinart",
      "Robert Griffin III",
      "Jayden Daniels",
    ],
  },
  {
    category: "player-identity",
    entityKind: "person",
    collisionGroup: "players",
    prompts: [
      "Name a player who had one of the most dominant individual college football seasons ever.",
      "Name a college player whose peak season felt almost unfair.",
      "Name a player remembered for taking over an entire college football season.",
      "Name a college star whose best year still gets brought up in all-time season debates.",
      "Name a player whose single-season college peak became legendary.",
    ],
    answers: [
      "Barry Sanders",
      "Joe Burrow",
      "Cam Newton",
      "Reggie Bush",
      "Derrick Henry",
      "Lamar Jackson",
      "Tim Tebow",
      "Vince Young",
    ],
    alsoAcceptedAnswers: [
      "Ndamukong Suh",
      "Charles Woodson",
      "Adrian Peterson",
      "Ricky Williams",
      "Herschel Walker",
      "Bo Jackson",
      "Marcus Mariota",
      "Caleb Williams",
    ],
  },
  {
    category: "player-identity",
    entityKind: "person",
    collisionGroup: "quarterbacks",
    prompts: [
      "Name an iconic college quarterback from the 2000s or later.",
      "Name a college quarterback whose name instantly takes you back to a great season.",
      "Name a modern-era college quarterback fans still talk about constantly.",
      "Name a quarterback whose college career created unforgettable Saturdays.",
      "Name a quarterback you would put in a modern college football time capsule.",
    ],
    answers: [
      "Tim Tebow",
      "Vince Young",
      "Cam Newton",
      "Joe Burrow",
      "Johnny Manziel",
      "Lamar Jackson",
      "Trevor Lawrence",
      "Matt Leinart",
    ],
    alsoAcceptedAnswers: [
      "Baker Mayfield",
      "Marcus Mariota",
      "Jameis Winston",
      "Kyler Murray",
      "Caleb Williams",
      "Sam Bradford",
      "Robert Griffin III",
      "Andrew Luck",
    ],
  },
  {
    category: "coach-legacy",
    entityKind: "person",
    collisionGroup: "coaches",
    prompts: [
      "Name a college football coach strongly associated with a dynasty.",
      "Name a coach whose program dominated college football for a sustained stretch.",
      "Name a coach you think of when someone says college football dynasty.",
      "Name a college coach who built a championship machine.",
      "Name a coach whose era changed the national title picture.",
    ],
    answers: [
      "Nick Saban",
      "Bear Bryant",
      "Bobby Bowden",
      "Pete Carroll",
      "Urban Meyer",
      "Tom Osborne",
      "Dabo Swinney",
      "Bud Wilkinson",
    ],
    alsoAcceptedAnswers: ["Kirby Smart", "Woody Hayes", "Knute Rockne", "John McKay", "Barry Switzer", "Jimmy Johnson"],
  },
  {
    category: "coach-identity",
    entityKind: "person",
    collisionGroup: "coaches",
    prompts: [
      "Name a college football coach known for offensive innovation.",
      "Name a coach whose offense changed how people talked about college football.",
      "Name a college coach associated with a distinctive offensive system.",
      "Name a coach who made opposing defensive coordinators lose sleep.",
      "Name an offensive-minded college coach whose scheme became part of his identity.",
    ],
    answers: [
      "Steve Spurrier",
      "Mike Leach",
      "Chip Kelly",
      "Lincoln Riley",
      "Hal Mumme",
      "Gus Malzahn",
      "Rich Rodriguez",
      "Dana Holgorsen",
    ],
    alsoAcceptedAnswers: ["Lane Kiffin", "Kliff Kingsbury", "Josh Heupel", "Jeff Brohm", "Paul Johnson", "June Jones"],
  },
  {
    category: "rivalries",
    entityKind: "other",
    collisionGroup: "rivalries",
    prompts: [
      "Name a college football rivalry almost every fan knows.",
      "Name a rivalry game that feels bigger than an ordinary Saturday.",
      "Name a college rivalry you would explain to a new fan first.",
      "Name a rivalry where the records almost stop mattering.",
      "Name a college football matchup with instant rivalry energy.",
    ],
    answers: [
      { name: "Ohio State-Michigan", aliases: ["The Game", "Michigan-Ohio State", "Ohio State vs Michigan", "Michigan vs Ohio State"] },
      { name: "Alabama-Auburn", aliases: ["Iron Bowl", "Auburn-Alabama", "Alabama vs Auburn", "Auburn vs Alabama"] },
      { name: "Texas-Oklahoma", aliases: ["Red River Rivalry", "Red River Shootout", "Oklahoma-Texas", "Texas vs Oklahoma", "Oklahoma vs Texas"] },
      { name: "Army-Navy", aliases: ["Army Navy Game", "Army vs Navy", "Navy-Army", "Navy vs Army"] },
      { name: "Florida-Georgia", aliases: ["Cocktail Party", "Georgia-Florida", "Florida vs Georgia", "Georgia vs Florida"] },
      { name: "USC-Notre Dame", aliases: ["Notre Dame-USC", "USC vs Notre Dame", "Notre Dame vs USC"] },
      { name: "Florida State-Miami", aliases: ["FSU-Miami", "Miami-Florida State", "FSU vs Miami", "Miami vs FSU"] },
      { name: "Oregon-Washington", aliases: ["Washington-Oregon", "Oregon vs Washington", "Washington vs Oregon"] },
    ],
    alsoAcceptedAnswers: [
      "Georgia-Auburn",
      "Clemson-South Carolina",
      "Michigan-Michigan State",
      "BYU-Utah",
      "Washington-Washington State",
      "Ole Miss-Mississippi State",
      "Iowa-Iowa State",
      "Harvard-Yale",
    ],
  },
  {
    category: "venues",
    entityKind: "school",
    collisionGroup: "venues",
    prompts: [
      "Name one of the toughest places to play a road game in college football.",
      "Name a college stadium where the crowd can become part of the game.",
      "Name a road environment that can rattle even a ranked team.",
      "Name a college football venue famous for being intimidating.",
      "Name a stadium you would least want to visit with a freshman quarterback.",
    ],
    answers: [
      { name: "LSU", aliases: ["Tiger Stadium", "Death Valley LSU", "Louisiana State", "LSU Tigers"] },
      { name: "Penn State", aliases: ["Beaver Stadium", "PSU", "Nittany Lions"] },
      { name: "Tennessee", aliases: ["Neyland", "Neyland Stadium", "Vols", "Volunteers", "UT"] },
      { name: "Texas A&M", aliases: ["Kyle Field", "A&M", "TAMU", "Aggies"] },
      { name: "Ohio State", aliases: ["Ohio Stadium", "The Horseshoe", "Horseshoe", "OSU", "Buckeyes", "Ohio St"] },
      { name: "Oregon", aliases: ["Autzen", "Autzen Stadium", "Ducks"] },
      { name: "Georgia", aliases: ["Sanford", "Sanford Stadium", "UGA", "Bulldogs", "Georgia Bulldogs"] },
      { name: "Alabama", aliases: ["Bryant-Denny", "Bryant Denny", "Bryant-Denny Stadium", "Bama", "Crimson Tide"] },
    ],
    alsoAcceptedAnswers: [
      { name: "Clemson", aliases: ["Death Valley Clemson", "Clemson Tigers"] },
      { name: "Michigan", aliases: ["Michigan Stadium", "Big House", "The Big House", "Wolverines"] },
      { name: "Auburn", aliases: ["Jordan-Hare", "Jordan Hare", "Jordan-Hare Stadium", "Auburn Tigers"] },
      { name: "Florida", aliases: ["The Swamp", "Ben Hill Griffin Stadium", "Gators"] },
      { name: "Virginia Tech", aliases: ["Lane Stadium", "VT", "Hokies"] },
      { name: "Washington", aliases: ["Husky Stadium", "UW", "Huskies"] },
      { name: "Iowa", aliases: ["Kinnick", "Kinnick Stadium", "Hawkeyes"] },
    ],
  },
  {
    category: "traditions",
    entityKind: "other",
    collisionGroup: "traditions",
    prompts: [
      "Name a college football tradition even casual fans recognize.",
      "Name a Saturday tradition that instantly tells you which school you are watching.",
      "Name a pregame or in-game college tradition with national recognition.",
      "Name a college football ritual fans would hate to lose.",
      "Name a school tradition that belongs on a college football bucket list.",
    ],
    answers: [
      "Ohio State dotting the i",
      "Clemson running down the hill",
      "Virginia Tech Enter Sandman",
      "Wisconsin Jump Around",
      "Texas A&M 12th Man",
      "Florida State spear plant",
      "Notre Dame Play Like a Champion Today",
      "Oklahoma Sooner Schooner",
    ],
    alsoAcceptedAnswers: [
      "Penn State White Out",
      "Iowa Wave",
      "Tennessee running through the T",
      "Michigan touching the banner",
      "Alabama Rammer Jammer",
      "Army-Navy March On",
    ],
  },
  {
    category: "bowl-history",
    entityKind: "other",
    collisionGroup: "bowls",
    prompts: [
      "Name a college football bowl game almost every fan knows.",
      "Name a bowl that sounds prestigious before you even know the matchup.",
      "Name a bowl game tied to college football history.",
      "Name a postseason bowl you would expect a casual fan to recognize.",
      "Name a bowl that has hosted major national-title-level stakes.",
    ],
    answers: ["Rose Bowl", "Sugar Bowl", "Orange Bowl", "Cotton Bowl", "Fiesta Bowl", "Peach Bowl", "Citrus Bowl", "Gator Bowl"],
    alsoAcceptedAnswers: ["Alamo Bowl", "Holiday Bowl", "Sun Bowl", "Liberty Bowl", "Music City Bowl", "Independence Bowl"],
  },
  {
    category: "history-legacy",
    entityKind: "other",
    collisionGroup: "conferences",
    prompts: [
      "Name a conference that has played a major role in college football history.",
      "Name a conference brand college football fans instantly recognize.",
      "Name a league that has shaped the national college football conversation.",
      "Name a conference whose old standings can trigger instant nostalgia.",
      "Name a conference name that belongs in college football history.",
    ],
    answers: [
      { name: "SEC", aliases: ["Southeastern Conference"] },
      { name: "Big Ten", aliases: ["Big 10", "B1G"] },
      { name: "ACC", aliases: ["Atlantic Coast Conference"] },
      { name: "Big 12", aliases: ["Big Twelve"] },
      { name: "Pac-12", aliases: ["Pacific-12"] },
      { name: "Southwest Conference", aliases: ["SWC"] },
      { name: "Big East", aliases: ["Big East Conference"] },
      { name: "WAC", aliases: ["Western Athletic Conference"] },
    ],
    alsoAcceptedAnswers: [
      { name: "Mountain West", aliases: ["MWC", "Mountain West Conference"] },
      { name: "Conference USA", aliases: ["C-USA", "CUSA"] },
      { name: "AAC", aliases: ["American Athletic Conference", "The American"] },
      { name: "MAC", aliases: ["Mid-American Conference"] },
      { name: "Ivy League", aliases: ["Ivy"] },
    ],
  },
  {
    category: "moments",
    entityKind: "other",
    collisionGroup: "moments",
    prompts: [
      "Name an iconic college football play or moment from the modern era.",
      "Name a college football moment that still gets replayed years later.",
      "Name a single play that instantly identifies a famous college football game.",
      "Name a college football ending fans remember by a nickname.",
      "Name a moment that can make a fan remember exactly where they were.",
    ],
    answers: [
      "Kick Six",
      "Boise State Statue of Liberty",
      "Vince Young 4th-and-5",
      "Prayer at Jordan-Hare",
      "Michigan State trouble with the snap",
      "Bush Push",
      "Bluegrass Miracle",
      "Appalachian State blocks Michigan field goal",
    ],
    alsoAcceptedAnswers: [
      "Tua 2nd-and-26",
      "Crabtree catch vs Texas",
      "Clowney hit",
      "Miami lateral return vs Duke",
      "Miracle on Techwood Drive",
    ],
  },
  {
    category: "achievements",
    entityKind: "other",
    collisionGroup: "achievements",
    prompts: [
      "Name something that can make a college football season legendary.",
      "Name an accomplishment that can define a college football season.",
      "Name something fans dream about before a college season starts.",
      "Name an achievement that can turn a good season into an all-time one.",
      "Name something a team can accomplish that fans will talk about for decades.",
    ],
    answers: [
      { name: "National championship", aliases: ["National title", "Natty", "Championship"] },
      { name: "Undefeated season", aliases: ["Perfect season", "Go undefeated"] },
      { name: "Heisman winner", aliases: ["Heisman Trophy winner", "Win the Heisman"] },
      { name: "Rivalry win", aliases: ["Beat rival", "Beat a rival"] },
      { name: "Playoff run", aliases: ["CFP run", "Playoff appearance"] },
      { name: "Conference title", aliases: ["Conference championship", "Win conference"] },
      { name: "Iconic bowl win", aliases: ["Bowl win", "Win a bowl"] },
      { name: "Finish ranked No. 1", aliases: ["No. 1 finish", "Finish number one", "Finish ranked number one"] },
    ],
    alsoAcceptedAnswers: [
      { name: "Beat the No. 1 team", aliases: ["Beat No. 1", "Beat number one", "Upset No. 1"] },
      { name: "Historic comeback", aliases: ["Huge comeback", "Comeback win"] },
      { name: "Record-setting season", aliases: ["Break records", "Set records", "Record breaking season"] },
      { name: "School-record win total", aliases: ["Most wins in school history", "School win record"] },
      { name: "Beat several ranked teams", aliases: ["Multiple ranked wins", "Several ranked wins"] },
    ],
  },
  {
    category: "positions",
    entityKind: "other",
    collisionGroup: "positions",
    prompts: [
      "Name a college football position fans love to watch.",
      "Name a position that can produce the biggest Saturday stars.",
      "Name a position recruits often become household names playing.",
      "Name a football position that can take over a college game.",
      "Name a position group that can become the identity of a team.",
    ],
    answers: [
      { name: "Quarterback", aliases: ["QB"] },
      { name: "Running back", aliases: ["RB"] },
      { name: "Wide receiver", aliases: ["WR"] },
      { name: "Linebacker", aliases: ["LB"] },
      { name: "Defensive end", aliases: ["DE", "Edge", "EDGE"] },
      { name: "Cornerback", aliases: ["CB"] },
      { name: "Safety", aliases: ["S"] },
      { name: "Tight end", aliases: ["TE"] },
    ],
    alsoAcceptedAnswers: [
      { name: "Offensive tackle", aliases: ["OT"] },
      { name: "Guard", aliases: ["OG"] },
      { name: "Center", aliases: ["C"] },
      { name: "Defensive tackle", aliases: ["DT"] },
      { name: "Kicker", aliases: ["K"] },
      { name: "Punter", aliases: ["P"] },
      { name: "Long snapper", aliases: ["LS"] },
    ],
  },
  {
    category: "traits",
    entityKind: "other",
    collisionGroup: "traits",
    prompts: [
      "Name a trait every college football coach wants in a quarterback.",
      "Name a quarterback trait that can separate a star from an average starter.",
      "Name something scouts notice quickly when evaluating a college quarterback.",
      "Name a quarterback quality that matters late in a close game.",
      "Name a trait fans brag about when they love their quarterback.",
    ],
    answers: ["Accuracy", "Arm strength", "Processing", "Mobility", "Poise", "Leadership", "Anticipation", "Toughness"],
    alsoAcceptedAnswers: ["Decision-making", "Pocket awareness", "Footwork", "Vision", "Ball security"],
  },
  {
    category: "culture",
    entityKind: "school",
    collisionGroup: "culture",
    prompts: [
      "Name a college football program known for an iconic uniform look.",
      "Name a school whose football uniform is recognizable immediately.",
      "Name a program with a uniform fans argue about in a good way.",
      "Name a school whose colors look unmistakably college football.",
      "Name a program you would include in a college football uniform conversation.",
    ],
    answers: [
      { name: "Oregon", aliases: ["Ducks"] },
      { name: "Penn State", aliases: ["PSU", "Nittany Lions"] },
      { name: "Notre Dame", aliases: ["ND", "Fighting Irish"] },
      { name: "Michigan", aliases: ["Wolverines"] },
      { name: "Alabama", aliases: ["Bama", "Crimson Tide"] },
      { name: "LSU", aliases: ["Louisiana State", "LSU Tigers"] },
      { name: "USC", aliases: ["Southern Cal", "Trojans"] },
      { name: "Texas", aliases: ["Longhorns"] },
    ],
    alsoAcceptedAnswers: [
      { name: "Ohio State", aliases: ["OSU", "Buckeyes", "Ohio St"] },
      { name: "Florida State", aliases: ["FSU", "Seminoles"] },
      { name: "Georgia", aliases: ["UGA", "Bulldogs", "Georgia Bulldogs"] },
      { name: "Tennessee", aliases: ["Vols", "Volunteers"] },
      { name: "Clemson", aliases: ["Clemson Tigers"] },
      { name: "Miami", aliases: ["The U", "Hurricanes", "Miami Hurricanes"] },
      { name: "UCLA", aliases: ["Bruins"] },
      { name: "North Carolina", aliases: ["UNC", "Tar Heels"] },
    ],
  },
] as const);
