import { expandSportsFeudFamilies } from "./sportsFeudAuthoredHelpers";

export const CFB_SPORTS_FEUD_FAST_2 = expandSportsFeudFamilies("cfb-fast2", [
  {
    category: "school-stars",
    entityKind: "person",
    collisionGroup: "quarterbacks",
    prompts: [
      {
        prompt: "Name a memorable Alabama quarterback from 2000 or later.",
        answers: ["Tua Tagovailoa","Jalen Hurts","Bryce Young","Mac Jones","AJ McCarron","Greg McElroy","Jalen Milroe","Blake Sims"],
        alsoAcceptedAnswers: ["Jake Coker","John Parker Wilson","Brodie Croyle"],
      },
      {
        prompt: "Name an Alabama quarterback you strongly associate with the Crimson Tide since 2000.",
        answers: ["Tua Tagovailoa","Bryce Young","Jalen Hurts","Mac Jones","AJ McCarron","Jalen Milroe","Greg McElroy","Blake Sims"],
        alsoAcceptedAnswers: ["Jake Coker","John Parker Wilson","Brodie Croyle"],
      },
      {
        prompt: "Name an Alabama quarterback who played in a major national game since 2000.",
        answers: ["Tua Tagovailoa","Jalen Hurts","Mac Jones","AJ McCarron","Greg McElroy","Bryce Young","Jake Coker","Jalen Milroe"],
        alsoAcceptedAnswers: ["Blake Sims","John Parker Wilson","Brodie Croyle"],
      },
      {
        prompt: "Name a Crimson Tide quarterback fans remember from the 2000s or later.",
        answers: ["Tua Tagovailoa","Jalen Hurts","Bryce Young","Mac Jones","AJ McCarron","Greg McElroy","Jalen Milroe","Blake Sims"],
        alsoAcceptedAnswers: ["Jake Coker","John Parker Wilson","Brodie Croyle"],
      },
      {
        prompt: "Name an Alabama quarterback who became a national name since 2000.",
        answers: ["Tua Tagovailoa","Bryce Young","Jalen Hurts","Mac Jones","AJ McCarron","Jalen Milroe","Greg McElroy","Blake Sims"],
        alsoAcceptedAnswers: ["Jake Coker","John Parker Wilson","Brodie Croyle"],
      },
    ],
    answers: [
      "Tua Tagovailoa",
      "Jalen Hurts",
      "Bryce Young",
      "Mac Jones",
      "AJ McCarron",
      "Greg McElroy",
      "Blake Sims",
      "Jake Coker",
    ],
    alsoAcceptedAnswers: ["Jalen Milroe", "John Parker Wilson", "Brodie Croyle"],
  },
  {
    category: "school-stars",
    entityKind: "person",
    collisionGroup: "quarterbacks",
    prompts: [
      {
        prompt: "Name a memorable Ohio State quarterback from 2000 or later.",
        answers: ["CJ Stroud","Justin Fields","Dwayne Haskins","JT Barrett","Braxton Miller","Troy Smith","Terrelle Pryor","Cardale Jones"],
        alsoAcceptedAnswers: ["Craig Krenzel","Will Howard","Kyle McCord","Todd Boeckman"],
      },
      {
        prompt: "Name an Ohio State quarterback you strongly associate with the Buckeyes since 2000.",
        answers: ["Justin Fields","CJ Stroud","JT Barrett","Troy Smith","Braxton Miller","Dwayne Haskins","Terrelle Pryor","Cardale Jones"],
        alsoAcceptedAnswers: ["Craig Krenzel","Will Howard","Kyle McCord","Todd Boeckman"],
      },
      {
        prompt: "Name a Buckeyes quarterback fans remember from the 2000s or later.",
        answers: ["Troy Smith","Justin Fields","CJ Stroud","JT Barrett","Braxton Miller","Dwayne Haskins","Cardale Jones","Terrelle Pryor"],
        alsoAcceptedAnswers: ["Craig Krenzel","Will Howard","Kyle McCord","Todd Boeckman"],
      },
      {
        prompt: "Name an Ohio State quarterback associated with a major postseason run since 2000.",
        answers: ["Cardale Jones","Justin Fields","CJ Stroud","Craig Krenzel","JT Barrett","Troy Smith","Will Howard","Dwayne Haskins"],
        alsoAcceptedAnswers: ["Braxton Miller","Terrelle Pryor","Kyle McCord","Todd Boeckman"],
      },
      {
        prompt: "Name an Ohio State quarterback who became a national name since 2000.",
        answers: ["CJ Stroud","Justin Fields","Troy Smith","Dwayne Haskins","Braxton Miller","JT Barrett","Terrelle Pryor","Cardale Jones"],
        alsoAcceptedAnswers: ["Craig Krenzel","Will Howard","Kyle McCord","Todd Boeckman"],
      },
    ],
    answers: [
      "CJ Stroud",
      "Justin Fields",
      "Dwayne Haskins",
      "JT Barrett",
      "Braxton Miller",
      "Troy Smith",
      "Terrelle Pryor",
      "Cardale Jones",
    ],
    alsoAcceptedAnswers: ["Craig Krenzel", "Will Howard", "Kyle McCord", "Todd Boeckman"],
  },
  {
    category: "school-stars",
    entityKind: "person",
    collisionGroup: "quarterbacks",
    prompts: [
      {
        prompt: "Name a memorable USC quarterback from 2000 or later.",
        answers: ["Matt Leinart","Carson Palmer","Caleb Williams","Sam Darnold","Mark Sanchez","Matt Barkley","John David Booty","Cody Kessler"],
        alsoAcceptedAnswers: ["Kedon Slovis","JT Daniels","Miller Moss","Jayden Maiava"],
      },
      {
        prompt: "Name a USC quarterback fans remember from 2000 or later.",
        answers: ["Matt Leinart","Carson Palmer","Caleb Williams","Sam Darnold","Mark Sanchez","Matt Barkley","Cody Kessler","John David Booty"],
        alsoAcceptedAnswers: ["Kedon Slovis","JT Daniels","Miller Moss","Jayden Maiava"],
      },
      {
        prompt: "Name a Trojans quarterback who became a major national name since 2000.",
        answers: ["Matt Leinart","Carson Palmer","Caleb Williams","Sam Darnold","Mark Sanchez","Matt Barkley","Kedon Slovis","Cody Kessler"],
        alsoAcceptedAnswers: ["John David Booty","JT Daniels","Miller Moss","Jayden Maiava"],
      },
      {
        prompt: "Name a USC quarterback associated with a big season since 2000.",
        answers: ["Matt Leinart","Carson Palmer","Caleb Williams","Sam Darnold","Mark Sanchez","Matt Barkley","John David Booty","Cody Kessler"],
        alsoAcceptedAnswers: ["Kedon Slovis","JT Daniels","Miller Moss","Jayden Maiava"],
      },
      {
        prompt: "Name a USC quarterback who became a national name since 2000.",
        answers: ["Matt Leinart","Carson Palmer","Caleb Williams","Sam Darnold","Mark Sanchez","Matt Barkley","Kedon Slovis","Cody Kessler"],
        alsoAcceptedAnswers: ["John David Booty","JT Daniels","Miller Moss","Jayden Maiava"],
      },
    ],
    answers: [
      "Matt Leinart",
      "Carson Palmer",
      "Caleb Williams",
      "Sam Darnold",
      "Mark Sanchez",
      "Matt Barkley",
      "John David Booty",
      "Cody Kessler",
    ],
    alsoAcceptedAnswers: ["Kedon Slovis", "JT Daniels", "Miller Moss", "Jayden Maiava"],
  },
  {
    category: "school-stars",
    entityKind: "person",
    collisionGroup: "quarterbacks",
    prompts: [
      {
        prompt: "Name a memorable Oklahoma quarterback from 2000 or later.",
        answers: ["Baker Mayfield","Kyler Murray","Jalen Hurts","Sam Bradford","Jason White","Landry Jones","Dillon Gabriel","Spencer Rattler"],
        alsoAcceptedAnswers: ["Josh Heupel","Caleb Williams","Trevor Knight","Blake Bell"],
      },
      {
        prompt: "Name an Oklahoma quarterback from a big offensive era since 2000.",
        answers: ["Baker Mayfield","Kyler Murray","Sam Bradford","Jalen Hurts","Landry Jones","Dillon Gabriel","Jason White","Caleb Williams"],
        alsoAcceptedAnswers: ["Spencer Rattler","Josh Heupel","Trevor Knight","Blake Bell"],
      },
      {
        prompt: "Name a Sooners quarterback fans remember from the 2000s or later.",
        answers: ["Baker Mayfield","Kyler Murray","Sam Bradford","Jalen Hurts","Jason White","Landry Jones","Dillon Gabriel","Spencer Rattler"],
        alsoAcceptedAnswers: ["Josh Heupel","Caleb Williams","Trevor Knight","Blake Bell"],
      },
      {
        prompt: "Name an Oklahoma quarterback associated with a major national season since 2000.",
        answers: ["Baker Mayfield","Kyler Murray","Sam Bradford","Jason White","Jalen Hurts","Josh Heupel","Dillon Gabriel","Landry Jones"],
        alsoAcceptedAnswers: ["Caleb Williams","Spencer Rattler","Trevor Knight","Blake Bell"],
      },
      {
        prompt: "Name an Oklahoma quarterback who became a national star since 2000.",
        answers: ["Baker Mayfield","Kyler Murray","Sam Bradford","Jalen Hurts","Jason White","Caleb Williams","Dillon Gabriel","Landry Jones"],
        alsoAcceptedAnswers: ["Spencer Rattler","Josh Heupel","Trevor Knight","Blake Bell"],
      },
    ],
    answers: [
      "Baker Mayfield",
      "Kyler Murray",
      "Jalen Hurts",
      "Sam Bradford",
      "Jason White",
      "Landry Jones",
      "Spencer Rattler",
      "Dillon Gabriel",
    ],
    alsoAcceptedAnswers: ["Josh Heupel", "Caleb Williams", "Trevor Knight", "Blake Bell"],
  },
  {
    category: "school-stars",
    entityKind: "person",
    collisionGroup: "quarterbacks",
    prompts: [
      {
        prompt: "Name a memorable Texas quarterback from 2000 or later.",
        answers: ["Vince Young","Colt McCoy","Quinn Ewers","Sam Ehlinger","Chris Simms","Major Applewhite","Garrett Gilbert","Case McCoy"],
        alsoAcceptedAnswers: ["David Ash","Shane Buechele","Arch Manning"],
      },
      {
        prompt: "Name a Longhorns quarterback fans remember from 2000 or later.",
        answers: ["Vince Young","Colt McCoy","Quinn Ewers","Sam Ehlinger","Chris Simms","Major Applewhite","Arch Manning","Shane Buechele"],
        alsoAcceptedAnswers: ["Garrett Gilbert","Case McCoy","David Ash"],
      },
      {
        prompt: "Name a Texas quarterback from a memorable season since 2000.",
        answers: ["Vince Young","Colt McCoy","Quinn Ewers","Sam Ehlinger","Chris Simms","Major Applewhite","Garrett Gilbert","David Ash"],
        alsoAcceptedAnswers: ["Case McCoy","Shane Buechele","Arch Manning"],
      },
      {
        prompt: "Name a quarterback strongly associated with Texas football since 2000.",
        answers: ["Vince Young","Colt McCoy","Sam Ehlinger","Quinn Ewers","Chris Simms","Major Applewhite","Arch Manning","Shane Buechele"],
        alsoAcceptedAnswers: ["Garrett Gilbert","Case McCoy","David Ash"],
      },
      {
        prompt: "Name a Texas signal caller who became a national name since 2000.",
        answers: ["Vince Young","Colt McCoy","Quinn Ewers","Sam Ehlinger","Chris Simms","Arch Manning","Major Applewhite","Shane Buechele"],
        alsoAcceptedAnswers: ["Garrett Gilbert","Case McCoy","David Ash"],
      },
    ],
    answers: [
      "Vince Young",
      "Colt McCoy",
      "Quinn Ewers",
      "Sam Ehlinger",
      "Chris Simms",
      "Major Applewhite",
      "Case McCoy",
      "Garrett Gilbert",
    ],
    alsoAcceptedAnswers: ["David Ash", "Shane Buechele", "Arch Manning"],
  },
  {
    category: "school-stars",
    entityKind: "person",
    collisionGroup: "players",
    prompts: [
      {
        prompt: "Name an LSU player who became a major college football star since 2000.",
        answers: ["Joe Burrow","Tyrann Mathieu","Ja'Marr Chase","Patrick Peterson","Leonard Fournette","Odell Beckham Jr.","Justin Jefferson","Glenn Dorsey"],
        alsoAcceptedAnswers: ["Jayden Daniels","Malik Nabers","Devin White","Grant Delpit","Clyde Edwards-Helaire","Brian Thomas Jr.","Jamal Adams","Jarvis Landry"],
      },
      {
        prompt: "Name a player you strongly associate with LSU football since 2000.",
        answers: ["Joe Burrow","Tyrann Mathieu","Leonard Fournette","Patrick Peterson","Ja'Marr Chase","Glenn Dorsey","Odell Beckham Jr.","Jayden Daniels"],
        alsoAcceptedAnswers: ["Justin Jefferson","Malik Nabers","Devin White","Grant Delpit","Clyde Edwards-Helaire","Brian Thomas Jr.","Jamal Adams","Jarvis Landry"],
      },
      {
        prompt: "Name an LSU star from the 2000s or later.",
        answers: ["Joe Burrow","Tyrann Mathieu","Ja'Marr Chase","Patrick Peterson","Leonard Fournette","Jayden Daniels","Odell Beckham Jr.","Glenn Dorsey"],
        alsoAcceptedAnswers: ["Justin Jefferson","Malik Nabers","Devin White","Grant Delpit","Clyde Edwards-Helaire","Brian Thomas Jr.","Jamal Adams","Jarvis Landry"],
      },
      {
        prompt: "Name a Tigers player who became a national name at LSU since 2000.",
        answers: ["Joe Burrow","Tyrann Mathieu","Ja'Marr Chase","Leonard Fournette","Patrick Peterson","Jayden Daniels","Odell Beckham Jr.","Justin Jefferson"],
        alsoAcceptedAnswers: ["Glenn Dorsey","Malik Nabers","Devin White","Grant Delpit","Clyde Edwards-Helaire","Brian Thomas Jr.","Jamal Adams","Jarvis Landry"],
      },
      {
        prompt: "Name an LSU player from 2000 or later you would put on a program highlight reel.",
        answers: ["Joe Burrow","Tyrann Mathieu","Ja'Marr Chase","Leonard Fournette","Patrick Peterson","Odell Beckham Jr.","Jayden Daniels","Justin Jefferson"],
        alsoAcceptedAnswers: ["Glenn Dorsey","Malik Nabers","Devin White","Grant Delpit","Clyde Edwards-Helaire","Brian Thomas Jr.","Jamal Adams","Jarvis Landry"],
      },
    ],
    answers: [
      "Joe Burrow",
      "Tyrann Mathieu",
      "Ja'Marr Chase",
      "Patrick Peterson",
      "Leonard Fournette",
      "Odell Beckham Jr.",
      "Justin Jefferson",
      "Glenn Dorsey",
    ],
    alsoAcceptedAnswers: [
      "Jayden Daniels",
      "Malik Nabers",
      "Devin White",
      "Grant Delpit",
      "Clyde Edwards-Helaire",
      "Brian Thomas Jr.",
      "Jamal Adams",
      "Jarvis Landry",
    ],
  },
  {
    category: "school-stars",
    entityKind: "person",
    collisionGroup: "players",
    prompts: [
      {
        prompt: "Name a Michigan player who became a major college football star from the 2000 season or later.",
        answers: ["Blake Corum","Aidan Hutchinson","Denard Robinson","Mike Hart","JJ McCarthy","Braylon Edwards","Jabrill Peppers","Jake Long"],
        alsoAcceptedAnswers: ["Chad Henne","Donovan Edwards","Will Johnson","Mason Graham","David Ojabo","Rashan Gary","Devin Bush","Jourdan Lewis","Nico Collins","Roman Wilson"],
      },
      {
        prompt: "Name a player you strongly associate with Michigan football since 2000.",
        answers: ["Blake Corum","Aidan Hutchinson","Denard Robinson","Mike Hart","JJ McCarthy","Jabrill Peppers","Braylon Edwards","Mason Graham"],
        alsoAcceptedAnswers: ["Jake Long","Chad Henne","Donovan Edwards","Will Johnson","David Ojabo","Rashan Gary","Devin Bush","Jourdan Lewis","Nico Collins","Roman Wilson"],
      },
      {
        prompt: "Name a Wolverines star fans remember from the 2000s or later.",
        answers: ["Aidan Hutchinson","Blake Corum","Denard Robinson","Mike Hart","JJ McCarthy","Braylon Edwards","Jabrill Peppers","Jake Long"],
        alsoAcceptedAnswers: ["Chad Henne","Donovan Edwards","Will Johnson","Mason Graham","David Ojabo","Rashan Gary","Devin Bush","Jourdan Lewis","Nico Collins","Roman Wilson"],
      },
      {
        prompt: "Name a Michigan player whose career since 2000 became part of program history.",
        answers: ["Blake Corum","Aidan Hutchinson","JJ McCarthy","Denard Robinson","Mike Hart","Jabrill Peppers","Braylon Edwards","Mason Graham"],
        alsoAcceptedAnswers: ["Jake Long","Chad Henne","Donovan Edwards","Will Johnson","David Ojabo","Rashan Gary","Devin Bush","Jourdan Lewis","Nico Collins","Roman Wilson"],
      },
      {
        prompt: "Name a Michigan player from 2000 or later you would expect on a program legends list.",
        answers: ["Blake Corum","Aidan Hutchinson","Denard Robinson","Mike Hart","Jabrill Peppers","JJ McCarthy","Braylon Edwards","Jake Long"],
        alsoAcceptedAnswers: ["Chad Henne","Donovan Edwards","Will Johnson","Mason Graham","David Ojabo","Rashan Gary","Devin Bush","Jourdan Lewis","Nico Collins","Roman Wilson"],
      },
    ],
    answers: ["Blake Corum","Aidan Hutchinson","Denard Robinson","Mike Hart","JJ McCarthy","Braylon Edwards","Jabrill Peppers","Jake Long"],
    alsoAcceptedAnswers: ["Chad Henne","Donovan Edwards","Will Johnson","Mason Graham","David Ojabo","Rashan Gary","Devin Bush","Jourdan Lewis","Nico Collins","Roman Wilson"],
  },
  {
    category: "school-stars",
    entityKind: "person",
    collisionGroup: "players",
    prompts: [
      {
        prompt: "Name a Notre Dame player college football fans remember from the 2000 season or later.",
        answers: ["Manti Te'o","Brady Quinn","Golden Tate","Kyle Hamilton","Michael Mayer","Jeff Samardzija","Michael Floyd","Harrison Smith"],
        alsoAcceptedAnswers: ["Kyren Williams","Tyler Eifert","Jaylon Smith","Audric Estime","Jeremiyah Love","Ian Book","Joe Alt","Quenton Nelson"],
      },
      {
        prompt: "Name a player strongly associated with Notre Dame football since 2000.",
        answers: ["Manti Te'o","Brady Quinn","Golden Tate","Jeff Samardzija","Michael Floyd","Kyle Hamilton","Michael Mayer","Harrison Smith"],
        alsoAcceptedAnswers: ["Kyren Williams","Tyler Eifert","Jaylon Smith","Audric Estime","Jeremiyah Love","Ian Book","Joe Alt","Quenton Nelson"],
      },
      {
        prompt: "Name a Fighting Irish star from the 2000s or later.",
        answers: ["Manti Te'o","Brady Quinn","Golden Tate","Kyle Hamilton","Michael Mayer","Jeff Samardzija","Michael Floyd","Harrison Smith"],
        alsoAcceptedAnswers: ["Kyren Williams","Tyler Eifert","Jaylon Smith","Audric Estime","Jeremiyah Love","Ian Book","Joe Alt","Quenton Nelson"],
      },
      {
        prompt: "Name a Notre Dame player who became a national name since 2000.",
        answers: ["Manti Te'o","Brady Quinn","Golden Tate","Kyle Hamilton","Michael Mayer","Jeff Samardzija","Michael Floyd","Jaylon Smith"],
        alsoAcceptedAnswers: ["Harrison Smith","Kyren Williams","Tyler Eifert","Audric Estime","Jeremiyah Love","Ian Book","Joe Alt","Quenton Nelson"],
      },
      {
        prompt: "Name a Notre Dame player from 2000 or later who belongs in a modern legends conversation.",
        answers: ["Manti Te'o","Brady Quinn","Golden Tate","Kyle Hamilton","Michael Mayer","Jeff Samardzija","Michael Floyd","Harrison Smith"],
        alsoAcceptedAnswers: ["Kyren Williams","Tyler Eifert","Jaylon Smith","Audric Estime","Jeremiyah Love","Ian Book","Joe Alt","Quenton Nelson"],
      },
    ],
    answers: ["Manti Te'o","Brady Quinn","Golden Tate","Kyle Hamilton","Michael Mayer","Jeff Samardzija","Michael Floyd","Harrison Smith"],
    alsoAcceptedAnswers: ["Kyren Williams","Tyler Eifert","Jaylon Smith","Audric Estime","Jeremiyah Love","Ian Book","Joe Alt","Quenton Nelson"],
  },
  {
    category: "school-stars",
    entityKind: "person",
    collisionGroup: "players",
    prompts: [
      {
        prompt: "Name a Georgia player who became a major college football star from the 2000 season or later.",
        answers: ["Stetson Bennett","Brock Bowers","Nick Chubb","Todd Gurley","Roquan Smith","Jalen Carter","Matthew Stafford","A.J. Green"],
        alsoAcceptedAnswers: ["David Pollack","Aaron Murray","Jordan Davis","Nakobe Dean","George Pickens","Sony Michel","Knowshon Moreno","Travon Walker","Malaki Starks","Ladd McConkey"],
      },
      {
        prompt: "Name a player strongly associated with Georgia football since 2000.",
        answers: ["Stetson Bennett","Brock Bowers","Nick Chubb","Todd Gurley","Roquan Smith","David Pollack","A.J. Green","Matthew Stafford"],
        alsoAcceptedAnswers: ["Jalen Carter","Aaron Murray","Jordan Davis","Nakobe Dean","George Pickens","Sony Michel","Knowshon Moreno","Travon Walker","Malaki Starks","Ladd McConkey"],
      },
      {
        prompt: "Name a Bulldogs star fans remember from the 2000s or later.",
        answers: ["Brock Bowers","Nick Chubb","Stetson Bennett","Todd Gurley","Roquan Smith","A.J. Green","Jalen Carter","Matthew Stafford"],
        alsoAcceptedAnswers: ["David Pollack","Aaron Murray","Jordan Davis","Nakobe Dean","George Pickens","Sony Michel","Knowshon Moreno","Travon Walker","Malaki Starks","Ladd McConkey"],
      },
      {
        prompt: "Name a Georgia player from 2000 or later you would put on a program highlight reel.",
        answers: ["Nick Chubb","Todd Gurley","Brock Bowers","Stetson Bennett","A.J. Green","Sony Michel","George Pickens","Matthew Stafford"],
        alsoAcceptedAnswers: ["Roquan Smith","Jalen Carter","David Pollack","Aaron Murray","Jordan Davis","Nakobe Dean","Knowshon Moreno","Travon Walker","Malaki Starks","Ladd McConkey"],
      },
      {
        prompt: "Name a Georgia player who helped shape the program since 2000.",
        answers: ["Stetson Bennett","Brock Bowers","Nick Chubb","David Pollack","Roquan Smith","Todd Gurley","Matthew Stafford","A.J. Green"],
        alsoAcceptedAnswers: ["Jalen Carter","Aaron Murray","Jordan Davis","Nakobe Dean","George Pickens","Sony Michel","Knowshon Moreno","Travon Walker","Malaki Starks","Ladd McConkey"],
      },
    ],
    answers: ["Stetson Bennett","Brock Bowers","Nick Chubb","Todd Gurley","Roquan Smith","Jalen Carter","Matthew Stafford","A.J. Green"],
    alsoAcceptedAnswers: ["David Pollack","Aaron Murray","Jordan Davis","Nakobe Dean","George Pickens","Sony Michel","Knowshon Moreno","Travon Walker","Malaki Starks","Ladd McConkey"],
  },
  {
    category: "school-stars",
    entityKind: "person",
    collisionGroup: "players",
    prompts: [
      {
        prompt: "Name a Clemson player who became a major college football star since 2000.",
        answers: ["Deshaun Watson","Trevor Lawrence","CJ Spiller","Sammy Watkins","DeAndre Hopkins","Christian Wilkins","Travis Etienne","Isaiah Simmons"],
        alsoAcceptedAnswers: ["Tajh Boyd","Tee Higgins","Dexter Lawrence","Vic Beasley","Mike Williams","Ben Boulware","Wayne Gallman"],
      },
      {
        prompt: "Name a player strongly associated with Clemson football since 2000.",
        answers: ["Deshaun Watson","Trevor Lawrence","CJ Spiller","Sammy Watkins","Travis Etienne","Christian Wilkins","Tajh Boyd","DeAndre Hopkins"],
        alsoAcceptedAnswers: ["Isaiah Simmons","Tee Higgins","Dexter Lawrence","Vic Beasley","Mike Williams","Ben Boulware","Wayne Gallman"],
      },
      {
        prompt: "Name a Tigers star from Clemson's modern era since 2000.",
        answers: ["Deshaun Watson","Trevor Lawrence","CJ Spiller","Sammy Watkins","Travis Etienne","DeAndre Hopkins","Christian Wilkins","Isaiah Simmons"],
        alsoAcceptedAnswers: ["Tajh Boyd","Tee Higgins","Dexter Lawrence","Vic Beasley","Mike Williams","Ben Boulware","Wayne Gallman"],
      },
      {
        prompt: "Name a Clemson player fans remember from a huge game since 2000.",
        answers: ["Deshaun Watson","Trevor Lawrence","Sammy Watkins","CJ Spiller","Travis Etienne","Tee Higgins","Christian Wilkins","Ben Boulware"],
        alsoAcceptedAnswers: ["DeAndre Hopkins","Isaiah Simmons","Tajh Boyd","Dexter Lawrence","Vic Beasley","Mike Williams","Wayne Gallman"],
      },
      {
        prompt: "Name a Clemson player from 2000 or later you would expect in a modern legends conversation.",
        answers: ["Deshaun Watson","Trevor Lawrence","CJ Spiller","Sammy Watkins","Travis Etienne","DeAndre Hopkins","Christian Wilkins","Isaiah Simmons"],
        alsoAcceptedAnswers: ["Tajh Boyd","Tee Higgins","Dexter Lawrence","Vic Beasley","Mike Williams","Ben Boulware","Wayne Gallman"],
      },
    ],
    answers: [
      "Deshaun Watson",
      "Trevor Lawrence",
      "CJ Spiller",
      "Sammy Watkins",
      "DeAndre Hopkins",
      "Christian Wilkins",
      "Travis Etienne",
      "Isaiah Simmons",
    ],
    alsoAcceptedAnswers: ["Tajh Boyd", "Tee Higgins", "Dexter Lawrence", "Vic Beasley", "Mike Williams", "Ben Boulware", "Wayne Gallman"],
  },
] as const);
