import type { FactCheckItem } from "../games/factCheckEngine";
import { FOOTBALL_FACT_CHECK_AUTHORITY_BANK } from "./footballFactCheckAuthorityBank";
import { FOOTBALL_FACT_CHECK_WEEKLY_BANK } from "./footballFactCheckWeeklyBank";

function fact(item: FactCheckItem): FactCheckItem {
  return item;
}

export const FOOTBALL_FACT_CHECK_HAND_AUTHORED_BANK: readonly FactCheckItem[] = [
  fact({
    id: "burrow-lsu-nine",
    sport: "football",
    league: "cfb",
    format: "true_false",
    difficulty: 1,
    prompt: "Joe Burrow wore No. 9 at LSU.",
    choices: ["TRUE", "FALSE"],
    answer: "TRUE",
    explanation: "True — Burrow wore No. 9 during both of his LSU seasons.",
    recency: "evergreen",
  }),
  fact({
    id: "dak-mississippi-state",
    sport: "football",
    league: "cfb",
    format: "true_false",
    difficulty: 1,
    prompt: "Dak Prescott played college football at Mississippi State.",
    choices: ["TRUE", "FALSE"],
    answer: "TRUE",
    explanation: "True — Prescott was Mississippi State's quarterback before Dallas drafted him.",
    recency: "evergreen",
  }),
  fact({
    id: "mahomes-texas-tech",
    sport: "football",
    league: "cfb",
    format: "true_false",
    difficulty: 1,
    prompt: "Patrick Mahomes played college football at Texas Tech.",
    choices: ["TRUE", "FALSE"],
    answer: "TRUE",
    explanation: "True — Mahomes starred at Texas Tech before becoming the No. 10 pick in 2017.",
    recency: "evergreen",
  }),
  fact({
    id: "allen-wyoming",
    sport: "football",
    league: "cfb",
    format: "either_or",
    difficulty: 1,
    prompt: "Where did Josh Allen play college football?",
    choices: ["WYOMING", "BOISE STATE"],
    answer: "WYOMING",
    explanation: "Wyoming — Allen played two full seasons for the Cowboys before entering the NFL.",
    recency: "evergreen",
  }),
  fact({
    id: "henry-heisman",
    sport: "football",
    league: "cfb",
    format: "true_false",
    difficulty: 1,
    prompt: "Derrick Henry won the Heisman Trophy at Alabama.",
    choices: ["TRUE", "FALSE"],
    answer: "TRUE",
    explanation: "True — Henry won the 2015 Heisman Trophy.",
    recency: "evergreen",
  }),
  fact({
    id: "jefferson-lsu",
    sport: "football",
    league: "cfb",
    format: "either_or",
    difficulty: 1,
    prompt: "Justin Jefferson played college football at which school?",
    choices: ["LSU", "FLORIDA STATE"],
    answer: "LSU",
    explanation: "LSU — Jefferson was part of the Tigers' 2019 national championship team.",
    recency: "evergreen",
  }),
  fact({
    id: "kelce-cincinnati",
    sport: "football",
    league: "cfb",
    format: "true_false",
    difficulty: 1,
    prompt: "Travis Kelce played college football at Cincinnati.",
    choices: ["TRUE", "FALSE"],
    answer: "TRUE",
    explanation: "True — Kelce played tight end for Cincinnati before Kansas City drafted him.",
    recency: "evergreen",
  }),
  fact({
    id: "ceedee-oklahoma",
    sport: "football",
    league: "cfb",
    format: "either_or",
    difficulty: 1,
    prompt: "CeeDee Lamb played college football at which school?",
    choices: ["OKLAHOMA", "TEXAS"],
    answer: "OKLAHOMA",
    explanation: "Oklahoma — Lamb played three seasons for the Sooners.",
    recency: "evergreen",
  }),
  fact({
    id: "saquon-penn-state",
    sport: "football",
    league: "cfb",
    format: "true_false",
    difficulty: 1,
    prompt: "Saquon Barkley played college football at Penn State.",
    choices: ["TRUE", "FALSE"],
    answer: "TRUE",
    explanation: "True — Barkley starred at Penn State before going No. 2 overall in 2018.",
    recency: "evergreen",
  }),
  fact({
    id: "hurts-finished-oklahoma",
    sport: "football",
    league: "cfb",
    format: "either_or",
    difficulty: 1,
    prompt: "Jalen Hurts finished his college career at which school?",
    choices: ["OKLAHOMA", "ALABAMA"],
    answer: "OKLAHOMA",
    explanation: "Oklahoma — Hurts transferred there for his final college season in 2019.",
    recency: "evergreen",
  }),
  fact({
    id: "brady-first-round",
    sport: "football",
    league: "nfl",
    format: "true_false",
    difficulty: 1,
    prompt: "Tom Brady was a first-round NFL Draft pick.",
    choices: ["TRUE", "FALSE"],
    answer: "FALSE",
    explanation: "False — New England selected Brady in the sixth round, 199th overall, in 2000.",
    recency: "evergreen",
  }),
  fact({
    id: "peyton-heisman",
    sport: "football",
    league: "cfb",
    format: "true_false",
    difficulty: 1,
    prompt: "Peyton Manning won the Heisman Trophy at Tennessee.",
    choices: ["TRUE", "FALSE"],
    answer: "FALSE",
    explanation: "False — Manning finished second in the 1997 Heisman voting to Charles Woodson.",
    recency: "evergreen",
  }),
  fact({
    id: "cam-heisman-school",
    sport: "football",
    league: "cfb",
    format: "either_or",
    difficulty: 1,
    prompt: "Where did Cam Newton win the Heisman Trophy?",
    choices: ["AUBURN", "FLORIDA"],
    answer: "AUBURN",
    explanation: "Auburn — Newton won the 2010 Heisman and national championship with the Tigers.",
    recency: "evergreen",
  }),
  fact({
    id: "rodgers-college",
    sport: "football",
    league: "cfb",
    format: "either_or",
    difficulty: 1,
    prompt: "Aaron Rodgers played major-college football at which school?",
    choices: ["CAL", "USC"],
    answer: "CAL",
    explanation: "Cal — Rodgers played two seasons for the Golden Bears.",
    recency: "evergreen",
  }),
  fact({
    id: "lamar-heisman-school",
    sport: "football",
    league: "cfb",
    format: "either_or",
    difficulty: 1,
    prompt: "Where did Lamar Jackson win the Heisman Trophy?",
    choices: ["LOUISVILLE", "KENTUCKY"],
    answer: "LOUISVILLE",
    explanation: "Louisville — Jackson won the 2016 Heisman Trophy.",
    recency: "evergreen",
  }),
  fact({
    id: "baker-heisman-school",
    sport: "football",
    league: "cfb",
    format: "either_or",
    difficulty: 1,
    prompt: "Where did Baker Mayfield win the Heisman Trophy?",
    choices: ["OKLAHOMA", "TEXAS TECH"],
    answer: "OKLAHOMA",
    explanation: "Oklahoma — Mayfield won the 2017 Heisman after beginning his career at Texas Tech.",
    recency: "evergreen",
  }),
  fact({
    id: "mahomes-watson-draft-order",
    sport: "football",
    league: "nfl",
    format: "before_after",
    difficulty: 2,
    prompt: "Patrick Mahomes was drafted ___ Deshaun Watson in 2017.",
    choices: ["BEFORE", "AFTER"],
    answer: "BEFORE",
    explanation: "Before — Mahomes went No. 10 overall and Watson went No. 12.",
    recency: "evergreen",
  }),
  fact({
    id: "burrow-heisman-title-order",
    sport: "football",
    league: "cfb",
    format: "before_after",
    difficulty: 2,
    prompt: "Joe Burrow won the Heisman ___ LSU won the 2019 national championship.",
    choices: ["BEFORE", "AFTER"],
    answer: "BEFORE",
    explanation: "Before — Burrow won the Heisman in December 2019 and LSU won the title in January 2020.",
    recency: "evergreen",
  }),
  fact({
    id: "saban-meyer-title-order",
    sport: "football",
    league: "cfb",
    format: "before_after",
    difficulty: 2,
    prompt: "Nick Saban won his first Alabama national title ___ Urban Meyer won his Ohio State title.",
    choices: ["BEFORE", "AFTER"],
    answer: "BEFORE",
    explanation: "Before — Alabama won the 2009 season title; Ohio State won the 2014 season title.",
    recency: "evergreen",
  }),
  fact({
    id: "lawrence-title-draft-order",
    sport: "football",
    league: "mixed",
    format: "before_after",
    difficulty: 2,
    prompt: "Trevor Lawrence won a national championship ___ he became the No. 1 NFL Draft pick.",
    choices: ["BEFORE", "AFTER"],
    answer: "BEFORE",
    explanation: "Before — Lawrence won the 2018 season title at Clemson and went No. 1 overall in 2021.",
    recency: "evergreen",
  }),
  fact({
    id: "emmitt-18k",
    sport: "football",
    league: "nfl",
    format: "over_under",
    difficulty: 2,
    prompt: "Emmitt Smith finished his NFL career with ___ 18,000 rushing yards.",
    choices: ["OVER", "UNDER"],
    answer: "OVER",
    explanation: "Over — Smith finished with 18,355 rushing yards.",
    recency: "evergreen",
  }),
  fact({
    id: "barry-15k",
    sport: "football",
    league: "nfl",
    format: "over_under",
    difficulty: 2,
    prompt: "Barry Sanders finished his NFL career with ___ 15,000 rushing yards.",
    choices: ["OVER", "UNDER"],
    answer: "OVER",
    explanation: "Over — Sanders retired with 15,269 rushing yards.",
    recency: "evergreen",
  }),
  fact({
    id: "peyton-550-td",
    sport: "football",
    league: "nfl",
    format: "over_under",
    difficulty: 2,
    prompt: "Peyton Manning threw ___ 550 regular-season touchdown passes.",
    choices: ["OVER", "UNDER"],
    answer: "UNDER",
    explanation: "Under — Manning finished with 539 regular-season touchdown passes.",
    recency: "evergreen",
  }),
  fact({
    id: "rice-200-rec-td",
    sport: "football",
    league: "nfl",
    format: "over_under",
    difficulty: 2,
    prompt: "Jerry Rice caught ___ 200 regular-season touchdown passes.",
    choices: ["OVER", "UNDER"],
    answer: "UNDER",
    explanation: "Under — Rice finished with 197 regular-season receiving touchdowns.",
    recency: "evergreen",
  }),
  fact({
    id: "moss-first-round",
    sport: "football",
    league: "nfl",
    format: "true_false",
    difficulty: 2,
    prompt: "Randy Moss was a first-round NFL Draft pick.",
    choices: ["TRUE", "FALSE"],
    answer: "TRUE",
    explanation: "True — Minnesota selected Moss 21st overall in 1998.",
    recency: "evergreen",
  }),
  fact({
    id: "donald-top-ten",
    sport: "football",
    league: "nfl",
    format: "true_false",
    difficulty: 2,
    prompt: "Aaron Donald was selected in the top 10 of the NFL Draft.",
    choices: ["TRUE", "FALSE"],
    answer: "FALSE",
    explanation: "False — the Rams selected Donald 13th overall in 2014.",
    recency: "evergreen",
  }),
  fact({
    id: "cmc-top-ten",
    sport: "football",
    league: "nfl",
    format: "true_false",
    difficulty: 2,
    prompt: "Christian McCaffrey was selected in the top 10 of the NFL Draft.",
    choices: ["TRUE", "FALSE"],
    answer: "TRUE",
    explanation: "True — Carolina selected McCaffrey eighth overall in 2017.",
    recency: "evergreen",
  }),
  fact({
    id: "peterson-top-five",
    sport: "football",
    league: "nfl",
    format: "true_false",
    difficulty: 2,
    prompt: "Adrian Peterson was selected in the top five of the NFL Draft.",
    choices: ["TRUE", "FALSE"],
    answer: "FALSE",
    explanation: "False — Minnesota selected Peterson seventh overall in 2007.",
    recency: "evergreen",
  }),
  fact({
    id: "reggie-first-overall",
    sport: "football",
    league: "nfl",
    format: "true_false",
    difficulty: 2,
    prompt: "Reggie Bush was the No. 1 overall pick in the 2006 NFL Draft.",
    choices: ["TRUE", "FALSE"],
    answer: "FALSE",
    explanation: "False — Houston took Mario Williams first; New Orleans selected Bush second.",
    recency: "evergreen",
  }),
  fact({
    id: "hurts-first-round",
    sport: "football",
    league: "nfl",
    format: "true_false",
    difficulty: 2,
    prompt: "Jalen Hurts was a first-round NFL Draft pick.",
    choices: ["TRUE", "FALSE"],
    answer: "FALSE",
    explanation: "False — Philadelphia selected Hurts in the second round, 53rd overall, in 2020.",
    recency: "evergreen",
  }),
  fact({
    id: "brees-80k",
    sport: "football",
    league: "nfl",
    format: "over_under",
    difficulty: 3,
    prompt: "Drew Brees finished his NFL career with ___ 80,000 passing yards.",
    choices: ["OVER", "UNDER"],
    answer: "OVER",
    explanation: "Over — Brees finished with 80,358 regular-season passing yards.",
    recency: "evergreen",
  }),
  fact({
    id: "tomlinson-150-rush-td",
    sport: "football",
    league: "nfl",
    format: "over_under",
    difficulty: 3,
    prompt: "LaDainian Tomlinson scored ___ 150 regular-season rushing touchdowns.",
    choices: ["OVER", "UNDER"],
    answer: "UNDER",
    explanation: "Under — Tomlinson finished with 145 rushing touchdowns.",
    recency: "evergreen",
  }),
  fact({
    id: "calvin-12k",
    sport: "football",
    league: "nfl",
    format: "over_under",
    difficulty: 3,
    prompt: "Calvin Johnson finished his NFL career with ___ 12,000 receiving yards.",
    choices: ["OVER", "UNDER"],
    answer: "UNDER",
    explanation: "Under — Johnson retired with 11,619 receiving yards.",
    recency: "evergreen",
  }),
  fact({
    id: "julio-900-catches",
    sport: "football",
    league: "nfl",
    format: "over_under",
    difficulty: 3,
    prompt: "Julio Jones finished his NFL career with ___ 900 regular-season receptions.",
    choices: ["OVER", "UNDER"],
    answer: "OVER",
    explanation: "Over — Jones finished with 914 regular-season receptions.",
    recency: "evergreen",
  }),
  fact({
    id: "gonzalez-1300-catches",
    sport: "football",
    league: "nfl",
    format: "over_under",
    difficulty: 3,
    prompt: "Tony Gonzalez finished his NFL career with ___ 1,300 receptions.",
    choices: ["OVER", "UNDER"],
    answer: "OVER",
    explanation: "Over — Gonzalez finished with 1,325 receptions.",
    recency: "evergreen",
  }),
  fact({
    id: "witten-1200-catches",
    sport: "football",
    league: "nfl",
    format: "over_under",
    difficulty: 3,
    prompt: "Jason Witten finished his NFL career with ___ 1,200 receptions.",
    choices: ["OVER", "UNDER"],
    answer: "OVER",
    explanation: "Over — Witten finished with 1,228 receptions.",
    recency: "evergreen",
  }),
  fact({
    id: "favre-500-td",
    sport: "football",
    league: "nfl",
    format: "over_under",
    difficulty: 3,
    prompt: "Brett Favre threw ___ 500 regular-season touchdown passes.",
    choices: ["OVER", "UNDER"],
    answer: "OVER",
    explanation: "Over — Favre finished with 508 regular-season touchdown passes.",
    recency: "evergreen",
  }),
  fact({
    id: "marino-400-td",
    sport: "football",
    league: "nfl",
    format: "over_under",
    difficulty: 3,
    prompt: "Dan Marino threw ___ 400 regular-season touchdown passes.",
    choices: ["OVER", "UNDER"],
    answer: "OVER",
    explanation: "Over — Marino finished with 420 regular-season touchdown passes.",
    recency: "evergreen",
  }),
  fact({
    id: "rodgers-super-bowl-mvp-order",
    sport: "football",
    league: "nfl",
    format: "either_or",
    difficulty: 3,
    prompt: "Which came first for Aaron Rodgers?",
    choices: ["SUPER BOWL WIN", "NFL MVP"],
    answer: "SUPER BOWL WIN",
    explanation: "Super Bowl win — Rodgers won Super Bowl XLV before earning his first NFL MVP for the 2011 season.",
    recency: "evergreen",
  }),
  fact({
    id: "eli-ben-draft-order",
    sport: "football",
    league: "nfl",
    format: "before_after",
    difficulty: 3,
    prompt: "Eli Manning was drafted ___ Ben Roethlisberger in 2004.",
    choices: ["BEFORE", "AFTER"],
    answer: "BEFORE",
    explanation: "Before — Manning went No. 1 overall and Roethlisberger went No. 11.",
    recency: "evergreen",
  }),
  fact({
    id: "barry-2k-four-times",
    sport: "football",
    league: "nfl",
    format: "true_false",
    difficulty: 4,
    prompt: "Barry Sanders rushed for more than 2,000 yards in four different NFL seasons.",
    choices: ["TRUE", "FALSE"],
    answer: "FALSE",
    explanation: "False — Sanders topped 2,000 once, rushing for 2,053 yards in 1997.",
    recency: "evergreen",
  }),
  fact({
    id: "lamar-playoff-second-mvp-order",
    sport: "football",
    league: "nfl",
    format: "either_or",
    difficulty: 4,
    prompt: "Which came first for Lamar Jackson?",
    choices: ["FIRST PLAYOFF WIN", "SECOND NFL MVP"],
    answer: "FIRST PLAYOFF WIN",
    explanation: "First playoff win — Baltimore beat Tennessee in January 2021; Jackson's second MVP came for the 2023 season.",
    recency: "evergreen",
  }),
  fact({
    id: "broncos-2013-600",
    sport: "football",
    league: "nfl",
    format: "over_under",
    difficulty: 4,
    prompt: "The 2013 Denver Broncos scored ___ 600 points in the regular season.",
    choices: ["OVER", "UNDER"],
    answer: "OVER",
    explanation: "Over — Denver scored 606 regular-season points in 2013.",
    recency: "evergreen",
  }),
  fact({
    id: "lsu-2019-cfp-40",
    sport: "football",
    league: "cfb",
    format: "true_false",
    difficulty: 4,
    prompt: "2019 LSU scored at least 40 points in both the CFP semifinal and national championship game.",
    choices: ["TRUE", "FALSE"],
    answer: "TRUE",
    explanation: "True — LSU scored 63 against Oklahoma and 42 against Clemson.",
    recency: "evergreen",
  }),
  fact({
    id: "packers-2011-first-playoff-loss",
    sport: "football",
    league: "nfl",
    format: "true_false",
    difficulty: 4,
    prompt: "The 15-1 Packers lost their first playoff game of the 2011 season.",
    choices: ["TRUE", "FALSE"],
    answer: "TRUE",
    explanation: "True — after a first-round bye, Green Bay lost its divisional-round opener to the Giants.",
    recency: "evergreen",
  }),
  fact({
    id: "rice-at-least-200-rec-td",
    sport: "football",
    league: "nfl",
    format: "true_false",
    difficulty: 4,
    prompt: "Jerry Rice finished with at least 200 regular-season receiving touchdowns.",
    choices: ["TRUE", "FALSE"],
    answer: "FALSE",
    explanation: "False — Rice's regular-season receiving touchdown total was 197.",
    recency: "evergreen",
  }),
];


export const FOOTBALL_FACT_CHECK_BANK: readonly FactCheckItem[] = [
  ...FOOTBALL_FACT_CHECK_HAND_AUTHORED_BANK,
  ...FOOTBALL_FACT_CHECK_AUTHORITY_BANK,
  ...FOOTBALL_FACT_CHECK_WEEKLY_BANK,
];
