import { barTriviaQuestion, type BarTriviaQuestion } from "../games/barTriviaEngine";

/**
 * Owner-only MLB Bar Trivia calibration run.
 *
 * These questions are intentionally disposable. They exist only to calibrate
 * the much easier MLB difficulty curve before the real postseason bank is authored.
 */
export const MLB_BAR_TRIVIA_MOCK_RUN = [
  barTriviaQuestion({
    id: "mlb-mock-r1-bambino",
    league: "mlb",
    round: "round1",
    category: "Nicknames",
    prompt: "Which baseball legend was famously known as “The Bambino”?",
    choices: ["Babe Ruth", "Mickey Mantle", "Joe DiMaggio", "Ted Williams"],
    answer: "Babe Ruth",
    explanation: "Babe Ruth was famously nicknamed both “The Bambino” and “The Sultan of Swat.”",
    sourceId: "mlb-mock-calibration",
  }),
  barTriviaQuestion({
    id: "mlb-mock-r1-bonds-73",
    league: "mlb",
    round: "round1",
    category: "Home Runs",
    prompt: "Who hit 73 home runs in the 2001 season?",
    choices: ["Barry Bonds", "Mark McGwire", "Sammy Sosa", "Ken Griffey Jr."],
    answer: "Barry Bonds",
    explanation: "Barry Bonds hit 73 home runs for San Francisco in 2001.",
    sourceId: "mlb-mock-calibration",
  }),
  barTriviaQuestion({
    id: "mlb-mock-r1-captain",
    league: "mlb",
    round: "round1",
    category: "Yankees",
    prompt: "Which Yankees star was widely known simply as “The Captain”?",
    choices: ["Derek Jeter", "Aaron Judge", "Alex Rodriguez", "Don Mattingly"],
    answer: "Derek Jeter",
    explanation: "Derek Jeter captained the Yankees from 2003 through his final season in 2014.",
    sourceId: "mlb-mock-calibration",
  }),
  barTriviaQuestion({
    id: "mlb-mock-r2-number-42",
    league: "mlb",
    round: "round2",
    category: "Jersey Numbers",
    prompt: "MLB retired No. 42 across every team in honor of which player?",
    choices: ["Jackie Robinson", "Hank Aaron", "Willie Mays", "Roberto Clemente"],
    answer: "Jackie Robinson",
    explanation: "Major League Baseball permanently retired Jackie Robinson’s No. 42 across all clubs.",
    sourceId: "mlb-mock-calibration",
  }),
  barTriviaQuestion({
    id: "mlb-mock-r2-iron-horse",
    league: "mlb",
    round: "round2",
    category: "Nicknames",
    prompt: "Which Yankees great was nicknamed “The Iron Horse”?",
    choices: ["Lou Gehrig", "Yogi Berra", "Mickey Mantle", "Whitey Ford"],
    answer: "Lou Gehrig",
    explanation: "Lou Gehrig earned “The Iron Horse” nickname for his durability and consecutive-games streak.",
    sourceId: "mlb-mock-calibration",
  }),
  barTriviaQuestion({
    id: "mlb-mock-r2-dimaggio-streak",
    league: "mlb",
    round: "round2",
    category: "Hitting Streaks",
    prompt: "Who recorded the famous 56-game hitting streak in 1941?",
    choices: ["Joe DiMaggio", "Ted Williams", "Stan Musial", "Ty Cobb"],
    answer: "Joe DiMaggio",
    explanation: "Joe DiMaggio hit safely in 56 consecutive games during the 1941 season.",
    sourceId: "mlb-mock-calibration",
  }),
  barTriviaQuestion({
    id: "mlb-mock-r3-hits-leader",
    league: "mlb",
    round: "round3",
    category: "Career Records",
    prompt: "Who finished his major-league career with 4,256 hits?",
    choices: ["Pete Rose", "Ty Cobb", "Hank Aaron", "Ichiro Suzuki"],
    answer: "Pete Rose",
    explanation: "Pete Rose finished his major-league career with 4,256 hits.",
    sourceId: "mlb-mock-calibration",
  }),
  barTriviaQuestion({
    id: "mlb-mock-r3-stolen-bases",
    league: "mlb",
    round: "round3",
    category: "Career Records",
    prompt: "Which player is baseball’s all-time stolen-base leader?",
    choices: ["Rickey Henderson", "Lou Brock", "Tim Raines", "Vince Coleman"],
    answer: "Rickey Henderson",
    explanation: "Rickey Henderson finished with 1,406 career stolen bases.",
    sourceId: "mlb-mock-calibration",
  }),
  barTriviaQuestion({
    id: "mlb-mock-r3-unanimous-hof",
    league: "mlb",
    round: "round3",
    category: "Hall of Fame",
    prompt: "Who became the first player elected unanimously to the Baseball Hall of Fame?",
    choices: ["Mariano Rivera", "Ken Griffey Jr.", "Derek Jeter", "Cal Ripken Jr."],
    answer: "Mariano Rivera",
    explanation: "Mariano Rivera became the first unanimous Hall of Fame selection in 2019.",
    sourceId: "mlb-mock-calibration",
  }),
  barTriviaQuestion({
    id: "mlb-mock-last-call-no-hitters",
    league: "mlb",
    round: "last-call",
    category: "Pitching Records",
    prompt: "Which pitcher threw seven career no-hitters?",
    choices: ["Nolan Ryan", "Sandy Koufax", "Randy Johnson", "Roger Clemens"],
    answer: "Nolan Ryan",
    explanation: "Nolan Ryan threw seven no-hitters, the most in major-league history.",
    sourceId: "mlb-mock-calibration",
  }),
] as const satisfies readonly BarTriviaQuestion[];
