import { expandSportsFeudFamilies } from "./sportsFeudAuthoredHelpers";

const variants = (prompts: readonly string[], rankings: readonly (readonly string[])[], accepted: readonly string[]) =>
  prompts.map((prompt, index) => ({ prompt, answers: rankings[index], alsoAcceptedAnswers: accepted }));

export const NFL_SPORTS_FEUD_FAST_5 = expandSportsFeudFamilies("nfl-fast5", [
  { category:"player-traits", entityKind:"person", collisionGroup:"clutch", prompts: variants(
    ["Name an NFL quarterback you associate with clutch moments.","Name a quarterback you would trust with one final drive.","Name an NFL QB who seemed built for the biggest moment.","Name a quarterback whose legacy includes huge late-game wins.","Name an NFL legend you would want with the game on the line."],
    [["Tom Brady","Joe Montana","Patrick Mahomes","John Elway","Peyton Manning","Aaron Rodgers","Ben Roethlisberger","Eli Manning"],["Tom Brady","Joe Montana","Patrick Mahomes","John Elway","Aaron Rodgers","Peyton Manning","Matthew Stafford","Ben Roethlisberger"],["Tom Brady","Joe Montana","Patrick Mahomes","Eli Manning","John Elway","Terry Bradshaw","Roger Staubach","Ben Roethlisberger"],["Tom Brady","Joe Montana","Patrick Mahomes","John Elway","Eli Manning","Ben Roethlisberger","Peyton Manning","Matthew Stafford"],["Tom Brady","Joe Montana","Patrick Mahomes","John Elway","Roger Staubach","Terry Bradshaw","Aaron Rodgers","Peyton Manning"]],
    ["Drew Brees","Roger Staubach","Terry Bradshaw","Troy Aikman","Brett Favre","Russell Wilson","Jim Kelly","Matthew Stafford","Eli Manning","Ben Roethlisberger"]), answers:["Tom Brady","Joe Montana","Patrick Mahomes","John Elway","Peyton Manning","Aaron Rodgers","Ben Roethlisberger","Eli Manning"] },
  { category:"player-traits", entityKind:"person", collisionGroup:"speed", prompts: variants(
    ["Name an NFL player known for elite speed.","Name a player you remember simply running away from defenders.","Name an NFL star whose speed jumped off the screen.","Name a football player defenders hated chasing in space.","Name a player you would pick for an NFL footrace."],
    [["Tyreek Hill","Deion Sanders","Chris Johnson","Randy Moss","Bo Jackson","Devin Hester","DeSean Jackson","Darrell Green"],["Tyreek Hill","Chris Johnson","Randy Moss","DeSean Jackson","Bo Jackson","Jamaal Charles","Devin Hester","Percy Harvin"],["Tyreek Hill","Deion Sanders","Randy Moss","Bo Jackson","Michael Vick","Chris Johnson","Devin Hester","DeSean Jackson"],["Tyreek Hill","Michael Vick","Chris Johnson","Devin Hester","DeSean Jackson","Jamaal Charles","Percy Harvin","Raheem Mostert"],["Tyreek Hill","Xavier Worthy","Chris Johnson","Darrell Green","Deion Sanders","Bob Hayes","DeSean Jackson","Bo Jackson"]],
    ["Bob Hayes","Darrell Green","Michael Vick","Ted Ginn Jr.","Raheem Mostert","Xavier Worthy","Jamaal Charles","Percy Harvin","Derrick Henry"]), answers:["Tyreek Hill","Deion Sanders","Chris Johnson","Randy Moss","Bo Jackson","Derrick Henry","Devin Hester","DeSean Jackson"] },
  { category:"player-traits", entityKind:"person", collisionGroup:"power", prompts: variants(
    ["Name an NFL running back known for power.","Name a back you would least want to tackle late in a game.","Name an NFL running back who could run through contact.","Name a power back whose highlights look painful for defenders.","Name an NFL back you associate with downhill running."],
    [["Derrick Henry","Marshawn Lynch","Earl Campbell","Jerome Bettis","Adrian Peterson","Jim Brown","Christian Okoye","Mike Alstott"],["Derrick Henry","Marshawn Lynch","Jerome Bettis","Earl Campbell","Nick Chubb","Adrian Peterson","Jamal Lewis","Christian Okoye"],["Derrick Henry","Earl Campbell","Marshawn Lynch","Adrian Peterson","Jim Brown","Jerome Bettis","Nick Chubb","Bo Jackson"],["Marshawn Lynch","Derrick Henry","Earl Campbell","Jerome Bettis","Mike Alstott","Christian Okoye","Bo Jackson","Jamal Lewis"],["Derrick Henry","Earl Campbell","Jerome Bettis","Christian Okoye","Eddie George","Larry Csonka","Nick Chubb","Steven Jackson"]],
    ["Jim Brown","Walter Payton","Bo Jackson","Jamal Lewis","Larry Csonka","Eddie George","Steven Jackson","Jonathan Stewart","Nick Chubb","Mike Alstott"]), answers:["Derrick Henry","Marshawn Lynch","Earl Campbell","Jerome Bettis","Adrian Peterson","Christian Okoye","Mike Alstott","Nick Chubb"] },
  { category:"quarterbacks", entityKind:"person", collisionGroup:"quarterbacks", prompts: variants(
    ["Name a famous dual-threat NFL quarterback.","Name an NFL quarterback who could beat you with his legs.","Name a quarterback whose rushing ability changed the defensive game plan.","Name an NFL QB you remember as a true run-pass threat.","Name a quarterback defenders had to account for as a runner."],
    [["Michael Vick","Lamar Jackson","Cam Newton","Steve Young","Randall Cunningham","Josh Allen","Jalen Hurts","Russell Wilson"],["Lamar Jackson","Michael Vick","Cam Newton","Josh Allen","Jalen Hurts","Justin Fields","Russell Wilson","Randall Cunningham"],["Lamar Jackson","Michael Vick","Cam Newton","Josh Allen","Randall Cunningham","Jalen Hurts","Steve Young","Kyler Murray"],["Michael Vick","Lamar Jackson","Cam Newton","Randall Cunningham","Steve Young","Russell Wilson","Josh Allen","Jalen Hurts"],["Lamar Jackson","Michael Vick","Josh Allen","Cam Newton","Jalen Hurts","Kyler Murray","Justin Fields","Randall Cunningham"]],
    ["Fran Tarkenton","Roger Staubach","Steve McNair","Kordell Stewart","Kyler Murray","Robert Griffin III","Daunte Culpepper","Justin Fields","Russell Wilson","Steve Young"]), answers:["Michael Vick","Lamar Jackson","Cam Newton","Steve Young","Randall Cunningham","Josh Allen","Jalen Hurts","Russell Wilson"] },
  { category:"quarterbacks", entityKind:"person", collisionGroup:"quarterbacks", prompts: variants(
    ["Name a classic pocket-passing NFL quarterback.","Name a quarterback whose game was built around throwing from the pocket.","Name an NFL QB remembered for command and accuracy more than rushing.","Name a passer whose highlights are mostly throws, not scrambles.","Name a quarterback you picture diagnosing a defense from the pocket."],
    [["Peyton Manning","Tom Brady","Dan Marino","Drew Brees","Joe Montana","Philip Rivers","Matt Ryan","Kurt Warner"],["Tom Brady","Peyton Manning","Dan Marino","Drew Brees","Philip Rivers","Matt Ryan","Kurt Warner","Troy Aikman"],["Peyton Manning","Tom Brady","Drew Brees","Joe Montana","Troy Aikman","Dan Marino","Kurt Warner","Matt Ryan"],["Dan Marino","Tom Brady","Peyton Manning","Drew Brees","Philip Rivers","Matt Ryan","Kurt Warner","Matthew Stafford"],["Peyton Manning","Tom Brady","Dan Marino","Drew Brees","Joe Montana","Philip Rivers","Kurt Warner","Troy Aikman"]],
    ["Troy Aikman","Eli Manning","Ben Roethlisberger","Jim Kelly","Ken Anderson","Warren Moon","Matthew Stafford","Carson Palmer","Matt Ryan","Philip Rivers","Kurt Warner"]), answers:["Peyton Manning","Tom Brady","Dan Marino","Drew Brees","Joe Montana","Philip Rivers","Matt Ryan","Kurt Warner"] },
  { category:"defenders", entityKind:"person", collisionGroup:"pass-rushers", prompts: variants(
    ["Name an NFL pass rusher who became a superstar.","Name a defender quarterbacks hated seeing off the edge.","Name an NFL player known for sacks and pressure.","Name a pass rusher whose reputation could wreck a protection plan.","Name a defender you associate with living in the backfield."],
    [["Reggie White","Bruce Smith","Lawrence Taylor","JJ Watt","Von Miller","Michael Strahan","TJ Watt","Myles Garrett"],["Lawrence Taylor","Reggie White","Von Miller","TJ Watt","Myles Garrett","Derrick Thomas","DeMarcus Ware","Jared Allen"],["Bruce Smith","Reggie White","Michael Strahan","JJ Watt","TJ Watt","Myles Garrett","Jared Allen","Kevin Greene"],["Lawrence Taylor","Reggie White","JJ Watt","Von Miller","Derrick Thomas","DeMarcus Ware","Bruce Smith","TJ Watt"],["Reggie White","Lawrence Taylor","JJ Watt","Myles Garrett","TJ Watt","Bruce Smith","Julius Peppers","Derrick Thomas"]],
    ["Kevin Greene","Jared Allen","DeMarcus Ware","Julius Peppers","Derrick Thomas","Terrell Suggs","Jack Youngblood","Mark Gastineau","Michael Strahan","Von Miller"]), answers:["Reggie White","Bruce Smith","Lawrence Taylor","JJ Watt","Von Miller","Michael Strahan","TJ Watt","Myles Garrett"] },
  { category:"defenders", entityKind:"person", collisionGroup:"corners", prompts: variants(
    ["Name an NFL cornerback known for shutting receivers down.","Name a corner quarterbacks sometimes preferred not to test.","Name an NFL cornerback famous for coverage ability.","Name a corner you would put on an elite receiver in a big game.","Name a defensive back whose reputation changed passing-game plans."],
    [["Deion Sanders","Darrelle Revis","Champ Bailey","Richard Sherman","Charles Woodson","Rod Woodson","Jalen Ramsey","Patrick Peterson"],["Darrelle Revis","Deion Sanders","Champ Bailey","Richard Sherman","Nnamdi Asomugha","Charles Woodson","Jalen Ramsey","Patrick Surtain II"],["Deion Sanders","Darrelle Revis","Champ Bailey","Richard Sherman","Charles Woodson","Rod Woodson","Patrick Peterson","Jalen Ramsey"],["Deion Sanders","Darrelle Revis","Champ Bailey","Jalen Ramsey","Charles Woodson","Richard Sherman","Patrick Surtain II","Ty Law"],["Deion Sanders","Darrelle Revis","Richard Sherman","Champ Bailey","Charles Woodson","Mel Blount","Nnamdi Asomugha","Jalen Ramsey"]],
    ["Mel Blount","Mike Haynes","Night Train Lane","Darrell Green","Aeneas Williams","Ty Law","Lester Hayes","Sauce Gardner","Patrick Surtain II","Nnamdi Asomugha","Patrick Peterson","Rod Woodson"]), answers:["Deion Sanders","Darrelle Revis","Champ Bailey","Richard Sherman","Charles Woodson","Rod Woodson","Patrick Peterson","Jalen Ramsey"] },
  { category:"young-stars", entityKind:"person", collisionGroup:"rookies", prompts: variants(
    ["Name an NFL player who made a huge impact as a rookie.","Name a player who looked ready for the league almost immediately.","Name an NFL star whose rookie season created major hype.","Name a player fans knew was special during year one.","Name an NFL player whose career started with a bang."],
    [["Randy Moss","Cam Newton","Saquon Barkley","Ezekiel Elliott","Adrian Peterson","Justin Jefferson","CJ Stroud","Micah Parsons"],["Randy Moss","CJ Stroud","Justin Jefferson","Micah Parsons","Ezekiel Elliott","Saquon Barkley","Dak Prescott","Ja'Marr Chase"],["Randy Moss","Cam Newton","Saquon Barkley","Ezekiel Elliott","CJ Stroud","Odell Beckham Jr.","Ja'Marr Chase","Robert Griffin III"],["Randy Moss","Justin Jefferson","Micah Parsons","Adrian Peterson","CJ Stroud","Ja'Marr Chase","Barry Sanders","Lawrence Taylor"],["Randy Moss","Cam Newton","Eric Dickerson","Ezekiel Elliott","Saquon Barkley","Dan Marino","Odell Beckham Jr.","Robert Griffin III"]],
    ["Lawrence Taylor","Eric Dickerson","Barry Sanders","Dan Marino","Odell Beckham Jr.","Ja'Marr Chase","Dak Prescott","Robert Griffin III","Adrian Peterson","Justin Jefferson","CJ Stroud","Micah Parsons"]), answers:["Randy Moss","Cam Newton","Saquon Barkley","Ezekiel Elliott","Adrian Peterson","Justin Jefferson","CJ Stroud","Micah Parsons"] },
  { category:"underdogs", entityKind:"team", collisionGroup:"teams", prompts: variants(
    ["Name an NFL team remembered for an underdog playoff run.","Name a franchise that has shocked a favorite in the postseason.","Name a team fans remember for a surprising January run.","Name an NFL club that has played the Cinderella role.","Name a team that showed an underdog can make serious playoff noise."],
    [["New York Giants","Pittsburgh Steelers","Green Bay Packers","Arizona Cardinals","Tennessee Titans","Jacksonville Jaguars","Cincinnati Bengals","Carolina Panthers"],["New York Giants","New England Patriots","Philadelphia Eagles","Jacksonville Jaguars","Tennessee Titans","Arizona Cardinals","Green Bay Packers","Las Vegas Raiders"],["New York Giants","Arizona Cardinals","Tennessee Titans","Jacksonville Jaguars","Cincinnati Bengals","Carolina Panthers","Green Bay Packers","Baltimore Ravens"],["New York Giants","Arizona Cardinals","Tennessee Titans","Carolina Panthers","Jacksonville Jaguars","Cincinnati Bengals","Philadelphia Eagles","Las Vegas Raiders"],["New York Giants","Pittsburgh Steelers","Green Bay Packers","Tennessee Titans","Arizona Cardinals","Jacksonville Jaguars","Cincinnati Bengals","Baltimore Ravens"]],
    ["Baltimore Ravens","Philadelphia Eagles","Las Vegas Raiders","New England Patriots","Pittsburgh Steelers","Green Bay Packers","Arizona Cardinals","Tennessee Titans","Jacksonville Jaguars","Cincinnati Bengals","Carolina Panthers"]), answers:["New York Giants","Pittsburgh Steelers","Green Bay Packers","Arizona Cardinals","Tennessee Titans","Jacksonville Jaguars","Cincinnati Bengals","Carolina Panthers"] },
  { category:"culture", entityKind:"team", collisionGroup:"culture", prompts: variants(
    ["Name an NFL team known for a classic uniform.","Name a franchise whose football look is instantly recognizable.","Name an NFL team with an iconic helmet or color scheme.","Name a team you would include in a best-uniforms conversation.","Name a franchise whose visual identity has aged well."],
    [["Green Bay Packers","Las Vegas Raiders","Pittsburgh Steelers","San Francisco 49ers","Dallas Cowboys","Chicago Bears","Miami Dolphins","Kansas City Chiefs"],["Dallas Cowboys","Green Bay Packers","Pittsburgh Steelers","Las Vegas Raiders","San Francisco 49ers","Chicago Bears","Miami Dolphins","Kansas City Chiefs"],["Pittsburgh Steelers","Dallas Cowboys","Las Vegas Raiders","Green Bay Packers","San Francisco 49ers","Miami Dolphins","Chicago Bears","Kansas City Chiefs"],["Los Angeles Chargers","Las Vegas Raiders","Miami Dolphins","San Francisco 49ers","Green Bay Packers","Pittsburgh Steelers","New Orleans Saints","Buffalo Bills"],["Green Bay Packers","Las Vegas Raiders","Pittsburgh Steelers","Chicago Bears","San Francisco 49ers","Dallas Cowboys","Indianapolis Colts","Kansas City Chiefs"]],
    ["Buffalo Bills","Indianapolis Colts","Los Angeles Chargers","Los Angeles Rams","Cleveland Browns","New York Giants","Philadelphia Eagles","New Orleans Saints","Miami Dolphins","Kansas City Chiefs","Dallas Cowboys","Chicago Bears"]), answers:["Green Bay Packers","Las Vegas Raiders","Pittsburgh Steelers","San Francisco 49ers","Dallas Cowboys","Chicago Bears","Miami Dolphins","Kansas City Chiefs"] },
] as const);
