import { expandSportsFeudFamilies } from "./sportsFeudAuthoredHelpers";

export const NFL_SPORTS_FEUD_FAST_1 = expandSportsFeudFamilies("nfl-fast1", [
  {
    category: "teams",
    collisionGroup: "teams",
    prompts: [
      "Name an NFC team.",
      "Name a franchise from the NFC.",
      "Name an NFC team with a major national fan base.",
      "Name a team you think of when someone says the NFC.",
      "Name an NFC franchise almost every football fan recognizes.",
    ],
    answers: [
      { name: "Dallas Cowboys", aliases: ["Cowboys", "Dallas"] },
      { name: "San Francisco 49ers", aliases: ["49ers", "Niners", "San Francisco"] },
      { name: "Green Bay Packers", aliases: ["Packers", "Green Bay"] },
      { name: "Philadelphia Eagles", aliases: ["Eagles", "Philadelphia"] },
      { name: "New York Giants", aliases: ["Giants", "NY Giants"] },
      { name: "Seattle Seahawks", aliases: ["Seahawks", "Seattle"] },
      { name: "Minnesota Vikings", aliases: ["Vikings", "Minnesota"] },
      { name: "Los Angeles Rams", aliases: ["Rams", "LA Rams"] },
    ],
  },
  {
    category: "teams",
    collisionGroup: "teams",
    prompts: [
      "Name an AFC team.",
      "Name a franchise from the AFC.",
      "Name an AFC team with a major national brand.",
      "Name a team you think of when someone says the AFC.",
      "Name an AFC franchise almost every football fan recognizes.",
    ],
    answers: [
      { name: "Kansas City Chiefs", aliases: ["Chiefs", "Kansas City"] },
      { name: "Pittsburgh Steelers", aliases: ["Steelers", "Pittsburgh"] },
      { name: "New England Patriots", aliases: ["Patriots", "New England"] },
      { name: "Buffalo Bills", aliases: ["Bills", "Buffalo"] },
      { name: "Baltimore Ravens", aliases: ["Ravens", "Baltimore"] },
      { name: "Denver Broncos", aliases: ["Broncos", "Denver"] },
      { name: "Las Vegas Raiders", aliases: ["Raiders", "Oakland Raiders"] },
      { name: "Miami Dolphins", aliases: ["Dolphins", "Miami"] },
    ],
  },
  {
    category: "team-identity",
    collisionGroup: "teams",
    prompts: [
      "Name an NFL team you associate with cold-weather football.",
      "Name a franchise whose home games can feel brutally cold.",
      "Name an NFL team that looks natural playing in snow.",
      "Name a team you picture in a freezing late-season game.",
      "Name a franchise whose fans know how to handle cold football weather.",
    ],
    answers: ["Green Bay Packers", "Buffalo Bills", "Chicago Bears", "Pittsburgh Steelers", "New England Patriots", "Cleveland Browns", "Minnesota Vikings", "Denver Broncos"],
  },
  {
    category: "team-identity",
    collisionGroup: "teams",
    prompts: [
      "Name an AFC franchise with a strong historical identity.",
      "Name an AFC team with decades of recognizable football history.",
      "Name a franchise that belongs in an AFC history conversation.",
      "Name an AFC team whose past includes famous players or playoff runs.",
      "Name an AFC franchise almost every generation of fans recognizes.",
    ],
    answers: ["Pittsburgh Steelers", "New England Patriots", "Kansas City Chiefs", "Las Vegas Raiders", "Denver Broncos", "Miami Dolphins", "Buffalo Bills", "Baltimore Ravens"],
  },
  {
    category: "champions",
    collisionGroup: "achievements",
    prompts: [
      "Name a franchise that has won multiple Super Bowls.",
      "Name an NFL team with more than one Super Bowl title.",
      "Name a franchise with a serious Super Bowl trophy case.",
      "Name a team whose history includes multiple Super Bowl wins.",
      "Name a franchise fans associate with repeated championship success.",
    ],
    answers: ["New England Patriots", "Pittsburgh Steelers", "San Francisco 49ers", "Dallas Cowboys", "Kansas City Chiefs", "Green Bay Packers", "New York Giants", "Denver Broncos"],
  },
  {
    category: "players",
    collisionGroup: "quarterbacks",
    prompts: [
      "Name an NFL MVP quarterback.",
      "Name a quarterback who has won league MVP.",
      "Name an MVP-winning NFL quarterback.",
      "Name a quarterback whose season ended with the NFL MVP award.",
      "Name an NFL quarterback fans remember as a league MVP.",
    ],
    answers: ["Tom Brady", "Peyton Manning", "Patrick Mahomes", "Aaron Rodgers", "Lamar Jackson", "Brett Favre", "Steve Young", "Cam Newton"],
  },
  {
    category: "players",
    collisionGroup: "running-backs",
    prompts: [
      "Name an NFL running back who rushed for 2,000 yards in a season.",
      "Name a member of the NFL's 2,000-yard rushing club.",
      "Name a running back remembered for a 2,000-yard season.",
      "Name an NFL back whose season crossed 2,000 rushing yards.",
      "Name a 2,000-yard rusher fans still talk about.",
    ],
    answers: ["Eric Dickerson", "Adrian Peterson", "Jamal Lewis", "Barry Sanders", "Terrell Davis", "Chris Johnson", "Derrick Henry", "OJ Simpson"],
  },
  {
    category: "players",
    collisionGroup: "receivers",
    prompts: [
      "Name an NFL receiver known for huge touchdown production.",
      "Name a receiver you associate with finding the end zone.",
      "Name an NFL wideout whose career includes a lot of touchdown catches.",
      "Name a receiver fans remember as a major red-zone threat.",
      "Name a wide receiver whose scoring ability became part of his reputation.",
    ],
    answers: ["Jerry Rice", "Randy Moss", "Terrell Owens", "Marvin Harrison", "Cris Carter", "Larry Fitzgerald", "Davante Adams", "Calvin Johnson"],
  },
  {
    category: "players",
    collisionGroup: "defenders",
    prompts: [
      "Name an NFL player famous for sacks.",
      "Name a pass rusher whose name belongs in a sack conversation.",
      "Name a defender quarterbacks hated seeing in the backfield.",
      "Name an NFL edge or defensive lineman known for getting to the quarterback.",
      "Name a pass rusher fans associate with dominant pressure.",
    ],
    answers: ["Bruce Smith", "Reggie White", "Michael Strahan", "JJ Watt", "Von Miller", "Aaron Donald", "Derrick Thomas", "TJ Watt"],
  },
  {
    category: "players",
    collisionGroup: "defenders",
    prompts: [
      "Name an NFL defensive back known for interceptions.",
      "Name a ball-hawking NFL defensive back.",
      "Name a DB whose reputation includes taking the ball away.",
      "Name an NFL secondary star quarterbacks had to locate before throwing.",
      "Name a defensive back remembered for making quarterbacks pay.",
    ],
    answers: ["Ed Reed", "Deion Sanders", "Rod Woodson", "Paul Krause", "Charles Woodson", "Champ Bailey", "Richard Sherman", "Ty Law"],
  },
] as const);
