import { expandSportsFeudFamilies } from "./sportsFeudAuthoredHelpers";

export const NFL_SPORTS_FEUD_MAIN = expandSportsFeudFamilies("nfl-main", [
  {
    category: "franchise-identity",
    entityKind: "team",
    collisionGroup: "franchises",
    prompts: [
      "Name an NFL franchise famous for great quarterbacks.",
      "Name a team you associate with a long line of notable quarterbacks.",
      "Name an NFL franchise where quarterback history is part of the brand.",
      "Name a team whose fans can argue about multiple great quarterbacks.",
      "Name a franchise a quarterback would love to join because of its history.",
    ],
    answers: ["Green Bay Packers", "San Francisco 49ers", "Indianapolis Colts", "Dallas Cowboys", "New England Patriots", "Pittsburgh Steelers", "Denver Broncos", "Miami Dolphins"],
    alsoAcceptedAnswers: ["New Orleans Saints", "Los Angeles Chargers", "Cincinnati Bengals", "Las Vegas Raiders", "Buffalo Bills", "Philadelphia Eagles", "Los Angeles Rams", "Minnesota Vikings"],
  },
  {
    category: "franchise-identity",
    entityKind: "team",
    collisionGroup: "franchises",
    prompts: [
      "Name an NFL franchise known for great running backs.",
      "Name a team whose history includes multiple star running backs.",
      "Name a franchise where the ground game feels like part of the identity.",
      "Name an NFL team you associate with legendary rushers.",
      "Name a franchise that belongs in a great-running-backs conversation.",
    ],
    answers: ["Dallas Cowboys", "Chicago Bears", "Pittsburgh Steelers", "Buffalo Bills", "Los Angeles Rams", "Minnesota Vikings", "Tennessee Titans", "Cleveland Browns"],
    alsoAcceptedAnswers: ["Detroit Lions", "Las Vegas Raiders", "Kansas City Chiefs", "Los Angeles Chargers", "New York Giants", "Indianapolis Colts", "San Francisco 49ers"],
  },
  {
    category: "franchise-identity",
    entityKind: "team",
    collisionGroup: "franchises",
    prompts: [
      "Name an NFL franchise you associate with elite defense.",
      "Name a team whose history makes you think defense first.",
      "Name an NFL franchise known for scary defensive units.",
      "Name a team that has built a major part of its identity on defense.",
      "Name an NFL franchise you would hate to face in a defensive slugfest.",
    ],
    answers: ["Pittsburgh Steelers", "Baltimore Ravens", "Chicago Bears", "Seattle Seahawks", "Tampa Bay Buccaneers", "New York Giants", "Denver Broncos", "San Francisco 49ers"],
    alsoAcceptedAnswers: ["Minnesota Vikings", "Dallas Cowboys", "Las Vegas Raiders", "Philadelphia Eagles", "New England Patriots", "Los Angeles Rams", "Kansas City Chiefs", "Miami Dolphins"],
  },
  {
    category: "franchise-identity",
    entityKind: "team",
    collisionGroup: "franchises",
    prompts: [
      "Name an NFL franchise known for great wide receivers.",
      "Name a team whose history includes multiple star pass catchers.",
      "Name an NFL franchise you associate with big-name receivers.",
      "Name a team that belongs in a great-receivers conversation.",
      "Name a franchise where fans can name several memorable wideouts.",
    ],
    answers: ["San Francisco 49ers", "Minnesota Vikings", "Pittsburgh Steelers", "Dallas Cowboys", "Indianapolis Colts", "Los Angeles Rams", "Las Vegas Raiders", "Miami Dolphins"],
    alsoAcceptedAnswers: ["Cincinnati Bengals", "Detroit Lions", "Arizona Cardinals", "Atlanta Falcons", "Buffalo Bills", "Philadelphia Eagles", "Green Bay Packers", "Tampa Bay Buccaneers"],
  },
  {
    category: "history-legacy",
    entityKind: "team",
    collisionGroup: "franchises",
    prompts: [
      "Name an NFL franchise with an iconic all-time brand.",
      "Name a team that belongs in almost any NFL history conversation.",
      "Name a franchise whose logo and colors feel instantly important.",
      "Name an NFL team with a huge historical footprint.",
      "Name a franchise you would include in an NFL blue-blood debate.",
    ],
    answers: ["Dallas Cowboys", "Green Bay Packers", "Pittsburgh Steelers", "San Francisco 49ers", "New England Patriots", "New York Giants", "Las Vegas Raiders", "Chicago Bears"],
    alsoAcceptedAnswers: ["Kansas City Chiefs", "Miami Dolphins", "Denver Broncos", "Philadelphia Eagles", "Buffalo Bills", "Washington Commanders", "Indianapolis Colts", "Los Angeles Rams"],
  },
  {
    category: "player-identity",
    entityKind: "person",
    collisionGroup: "quarterbacks",
    prompts: [
      "Name an all-time iconic NFL quarterback.",
      "Name a quarterback almost every NFL fan would put in a legends conversation.",
      "Name an NFL quarterback whose career defines an era.",
      "Name a quarterback you would expect on an all-time NFL highlight reel.",
      "Name a quarterback whose name alone sounds like NFL history.",
    ],
    answers: ["Tom Brady", "Joe Montana", "Peyton Manning", "Patrick Mahomes", "Aaron Rodgers", "John Elway", "Dan Marino", "Brett Favre"],
    alsoAcceptedAnswers: ["Drew Brees", "Steve Young", "Johnny Unitas", "Roger Staubach", "Kurt Warner", "Fran Tarkenton", "Troy Aikman", "Ben Roethlisberger"],
  },
  {
    category: "player-identity",
    entityKind: "person",
    collisionGroup: "running-backs",
    prompts: [
      "Name an all-time great NFL running back.",
      "Name a running back whose highlights still look special decades later.",
      "Name an NFL back you would put in a legends conversation.",
      {
        prompt: "Name a running back who became the identity of an offense.",
        answers: [
          "Barry Sanders",
          "Walter Payton",
          "Emmitt Smith",
          "Jim Brown",
          "Derrick Henry",
          "Adrian Peterson",
          "LaDainian Tomlinson",
          "Eric Dickerson",
        ],
        alsoAcceptedAnswers: [
          "Marshall Faulk",
          "Earl Campbell",
          "Marshawn Lynch",
          "Christian McCaffrey",
          "Saquon Barkley",
          "Ezekiel Elliott",
          "Priest Holmes",
          "Shaun Alexander",
          "Jamaal Charles",
          "Steven Jackson",
          "Ricky Williams",
          "Gale Sayers",
          "OJ Simpson",
          "Marcus Allen",
          "Tony Dorsett",
          "Thurman Thomas",
          "Frank Gore",
        ],
      },
      "Name a back defenders would hate to tackle all afternoon.",
    ],
    answers: ["Barry Sanders", "Walter Payton", "Emmitt Smith", "Jim Brown", "Adrian Peterson", "LaDainian Tomlinson", "Eric Dickerson", "Derrick Henry"],
    alsoAcceptedAnswers: ["Marshall Faulk", "Earl Campbell", "Gale Sayers", "OJ Simpson", "Marcus Allen", "Tony Dorsett", "Thurman Thomas", "Frank Gore"],
  },
  {
    category: "player-identity",
    entityKind: "person",
    collisionGroup: "receivers",
    prompts: [
      "Name an all-time great NFL wide receiver.",
      "Name a receiver whose career belongs in any NFL legends discussion.",
      "Name an NFL wideout whose highlights still get replayed.",
      "Name a receiver who changed how defenses had to line up.",
      "Name a wide receiver almost every football fan recognizes.",
    ],
    answers: ["Jerry Rice", "Randy Moss", "Terrell Owens", "Calvin Johnson", "Larry Fitzgerald", "Marvin Harrison", "Cris Carter", "Tyreek Hill"],
    alsoAcceptedAnswers: ["Steve Largent", "Julio Jones", "Andre Johnson", "Isaac Bruce", "Torry Holt", "Don Hutson", "Lance Alworth", "Antonio Brown"],
  },
  {
    category: "player-identity",
    entityKind: "person",
    collisionGroup: "defenders",
    prompts: [
      "Name an all-time great NFL defensive player.",
      "Name a defender whose reputation could change a game plan.",
      "Name an NFL defensive star who belongs in a legends conversation.",
      "Name a defender whose highlights make offense look miserable.",
      "Name a defensive player almost every NFL fan recognizes.",
    ],
    answers: ["Lawrence Taylor", "Reggie White", "Ray Lewis", "Deion Sanders", "Aaron Donald", "JJ Watt", "Ed Reed", "Bruce Smith"],
    alsoAcceptedAnswers: ["Ronnie Lott", "Dick Butkus", "Deacon Jones", "Joe Greene", "Junior Seau", "Mike Singletary", "Champ Bailey", "Charles Woodson"],
  },
  {
    category: "coach-legacy",
    entityKind: "person",
    collisionGroup: "coaches",
    prompts: [
      "Name an NFL coach strongly associated with a dynasty.",
      "Name a coach whose team dominated the league for a sustained stretch.",
      "Name an NFL coach you think of when someone says dynasty.",
      "Name a coach who built a championship machine.",
      "Name a coach whose era changed the NFL title picture.",
    ],
    answers: ["Bill Belichick", "Vince Lombardi", "Chuck Noll", "Bill Walsh", "Joe Gibbs", "Tom Landry", "Andy Reid", "Don Shula"],
    alsoAcceptedAnswers: ["Jimmy Johnson", "George Seifert", "Paul Brown", "George Halas", "Curly Lambeau"],
  },
  {
    category: "rivalries",
    entityKind: "other",
    collisionGroup: "rivalries",
    prompts: [
      "Name an NFL rivalry almost every football fan knows.",
      "Name a rivalry game that feels bigger than an ordinary Sunday.",
      "Name an NFL matchup where the fan bases genuinely dislike each other.",
      "Name a division rivalry you would circle before the season starts.",
      "Name an NFL rivalry that has produced memorable games for years.",
    ],
    answers: ["Packers-Bears", "Cowboys-Eagles", "Steelers-Ravens", "49ers-Cowboys", "Raiders-Chiefs", "Giants-Eagles", "Packers-Vikings", "Jets-Patriots"],
    alsoAcceptedAnswers: ["Cowboys-Commanders", "Patriots-Colts", "49ers-Seahawks", "Browns-Steelers", "Saints-Falcons", "Chiefs-Broncos", "Bears-Vikings", "Bengals-Steelers"],
  },
  {
    category: "venues",
    entityKind: "other",
    collisionGroup: "venues",
    prompts: [
      "Name one of the toughest NFL stadiums for a road team.",
      "Name an NFL stadium famous for crowd noise.",
      "Name a road environment that can make an offense miserable.",
      "Name an NFL venue where home-field advantage feels real.",
      "Name an NFL stadium widely known for a difficult road atmosphere.",
    ],
    answers: ["Arrowhead Stadium", "Lambeau Field", "Lumen Field", "Superdome", "Highmark Stadium", "Lincoln Financial Field", "Acrisure Stadium", "M&T Bank Stadium"],
    alsoAcceptedAnswers: ["U.S. Bank Stadium", "Ford Field"],
  },
  {
    category: "moments",
    entityKind: "other",
    collisionGroup: "moments",
    prompts: [
      "Name an iconic NFL playoff or Super Bowl moment.",
      "Name a single NFL play that instantly identifies a famous game.",
      "Name an NFL moment fans still replay years later.",
      "Name a postseason play that became part of football vocabulary.",
      "Name a play that can make an NFL fan remember exactly where they were.",
    ],
    answers: ["Immaculate Reception", "Helmet Catch", "Minneapolis Miracle", "Music City Miracle", "Philly Special", "Beast Quake", "Malcolm Butler goal-line interception", "Santonio Holmes toe-tap"],
    alsoAcceptedAnswers: [
      { name: "The Catch", aliases: ["Montana to Clark"] },
      "Tuck Rule",
      "Mile High Miracle",
      "Double Doink",
      "Wide Right",
      "28-3 comeback",
      "13 Seconds",
      "James Harrison 100-yard interception return",
    ],
  },
  {
    category: "history-legacy",
    entityKind: "team",
    collisionGroup: "champions",
    prompts: [
      "Name an NFL franchise you associate with Super Bowl success.",
      "Name a team with a major Super Bowl legacy.",
      "Name a franchise fans expect in a championship-history conversation.",
      "Name an NFL team whose trophy case helps define the brand.",
      "Name a franchise with memorable Super Bowl wins.",
    ],
    answers: ["New England Patriots", "Pittsburgh Steelers", "San Francisco 49ers", "Dallas Cowboys", "Kansas City Chiefs", "Green Bay Packers", "New York Giants", "Denver Broncos"],
    alsoAcceptedAnswers: ["Las Vegas Raiders", "Miami Dolphins", "Washington Commanders", "Indianapolis Colts", "Baltimore Ravens", "Tampa Bay Buccaneers", "Los Angeles Rams", "Philadelphia Eagles", "Seattle Seahawks"],
  },
  {
    category: "awards",
    entityKind: "other",
    collisionGroup: "awards",
    prompts: [
      "Name an NFL award or honor players want to win.",
      "Name an award that can define an NFL season.",
      "Name a major individual honor in pro football.",
      "Name an NFL award fans debate every year.",
      "Name an award that can become part of a player's legacy.",
    ],
    answers: ["NFL MVP", "Super Bowl MVP", "Defensive Player of the Year", "Offensive Player of the Year", "Offensive Rookie of the Year", "Defensive Rookie of the Year", "Comeback Player of the Year", "Walter Payton Man of the Year"],
    alsoAcceptedAnswers: ["First-team All-Pro", "Pro Bowl selection"],
  },
  {
    category: "achievements",
    entityKind: "other",
    collisionGroup: "achievements",
    prompts: [
      "Name an accomplishment that can make an NFL season legendary.",
      "Name something an NFL player or team can do that fans remember for decades.",
      "Name a milestone that can turn a great season into an historic one.",
      "Name an achievement that makes a football résumé jump off the page.",
      "Name something every NFL star would love attached to one season.",
    ],
    answers: ["Win the Super Bowl", "Win league MVP", "Go undefeated", "Rush for 2,000 yards", "Pass for 5,000 yards", "Record 20 sacks", "Score 20 touchdowns", "Set an NFL record"],
    alsoAcceptedAnswers: ["Win Super Bowl MVP", "Win Offensive Player of the Year", "Win Defensive Player of the Year", "Make first-team All-Pro", "Lead the NFL in a major statistic"],
  },
  {
    category: "positions",
    entityKind: "other",
    collisionGroup: "positions",
    prompts: [
      "Name an NFL position fans love to watch.",
      "Name a position that can produce the biggest Sunday stars.",
      "Name a football position casual fans recognize immediately.",
      "Name a position group that can become a team's identity.",
      "Name a position that can change a game with one play.",
    ],
    answers: ["Quarterback", "Running back", "Wide receiver", "Pass rusher", "Cornerback", "Linebacker", "Tight end", "Safety"],
    alsoAcceptedAnswers: ["Defensive tackle", "Center", "Guard", "Kicker", "Punter", "Fullback", "Long snapper", "Nose tackle"],
  },
  {
    category: "traits",
    entityKind: "other",
    collisionGroup: "traits",
    prompts: [
      "Name a trait every NFL coach wants in a quarterback.",
      "Name a quarterback trait that separates stars from average starters.",
      "Name something scouts notice immediately in an NFL quarterback.",
      "Name a quarterback quality that matters late in a close game.",
      "Name a trait fans brag about when they love their quarterback.",
    ],
    answers: ["Accuracy", "Processing", "Arm strength", "Poise", "Mobility", "Anticipation", "Leadership", "Toughness"],
    alsoAcceptedAnswers: ["Pocket presence", "Footwork", "Decision-making", "Field vision", "Mechanics", "Ball security", "Quick release", "Timing"],
  },
  {
    category: "traits",
    entityKind: "other",
    collisionGroup: "defense",
    prompts: [
      "Name a trait every great NFL defense needs.",
      "Name something that can make a defense hard to play against.",
      "Name a quality coaches want from a defensive unit.",
      "Name something fans praise when their defense is elite.",
      "Name a defensive trait that can travel in the playoffs.",
    ],
    answers: ["Pass rush", "Tackling", "Turnovers", "Coverage", "Physicality", "Communication", "Speed", "Discipline"],
    alsoAcceptedAnswers: ["Run defense", "Red-zone defense", "Depth", "Versatility", "Pursuit", "Technique", "Conditioning"],
  },
  {
    category: "culture",
    entityKind: "team",
    collisionGroup: "culture",
    prompts: [
      "Name an NFL team with an iconic uniform or logo.",
      {
        prompt: "Name an NFL franchise with a classic visual identity that has stayed recognizable for decades.",
        answers: [
          "Green Bay Packers",
          "Las Vegas Raiders",
          "Pittsburgh Steelers",
          "Dallas Cowboys",
          "San Francisco 49ers",
          "Chicago Bears",
          "Kansas City Chiefs",
          "Miami Dolphins",
        ],
        alsoAcceptedAnswers: [
          "New York Giants",
          "Indianapolis Colts",
          "Cleveland Browns",
          "New Orleans Saints",
          "Buffalo Bills",
          "Los Angeles Chargers",
          "Los Angeles Rams",
          "Philadelphia Eagles",
          "Minnesota Vikings",
          "Denver Broncos",
        ],
      },
      "Name a team whose colors and helmet feel unmistakably NFL.",
      "Name an NFL franchise you would include in a classic-uniform conversation.",
      "Name a team whose visual identity barely needs an introduction.",
    ],
    answers: ["Green Bay Packers", "Dallas Cowboys", "Las Vegas Raiders", "Pittsburgh Steelers", "San Francisco 49ers", "Kansas City Chiefs", "Chicago Bears", "Miami Dolphins"],
    alsoAcceptedAnswers: ["New York Giants", "Buffalo Bills", "Indianapolis Colts", "Los Angeles Chargers", "Los Angeles Rams", "Cleveland Browns", "Philadelphia Eagles", "New Orleans Saints"],
  },
] as const);
