import { expandSportsFeudFamilies } from "./sportsFeudAuthoredHelpers";

export const NFL_SPORTS_FEUD_FAST_4 = expandSportsFeudFamilies("nfl-fast4", [
  {
    category: "positions",
    entityKind: "other",
    collisionGroup: "positions",
    prompts: [
      "Name an NFL position other than quarterback.",
      "Name a position you can play in the NFL.",
      "Name a football position that produces stars.",
      "Name a position group coaches talk about constantly.",
      "Name a position that can change a game with one play.",
    ],
    answers: [
      { name: "Running back", aliases: ["RB"] },
      { name: "Wide receiver", aliases: ["WR"] },
      { name: "Linebacker", aliases: ["LB"] },
      { name: "Cornerback", aliases: ["CB"] },
      { name: "Defensive end", aliases: ["DE"] },
      { name: "Safety", aliases: ["S"] },
      { name: "Tight end", aliases: ["TE"] },
      { name: "Offensive tackle", aliases: ["OT"] },
    ],
    alsoAcceptedAnswers: [
      { name: "Defensive tackle", aliases: ["DT"] },
      { name: "Guard", aliases: ["G"] },
      { name: "Center", aliases: ["C"] },
      { name: "Kicker", aliases: ["K"] },
      { name: "Punter", aliases: ["P"] },
      { name: "Fullback", aliases: ["FB"] },
      { name: "Long snapper", aliases: ["LS"] },
      { name: "Nose tackle", aliases: ["NT"] },
    ],
  },
  {
    category: "game-concepts",
    entityKind: "other",
    collisionGroup: "scoring",
    prompts: [
      "Name a way to score points in an NFL game.",
      "Name something that can put points on the scoreboard.",
      "Name a scoring play you can see on a Sunday.",
      "Name a way an offense, defense, or special teams unit can score.",
      "Name something that changes the score in a football game.",
    ],
    answers: [
      { name: "Touchdown", aliases: ["TD"] },
      { name: "Field goal", aliases: ["FG"] },
      { name: "Extra point", aliases: ["PAT", "Point after", "Point after touchdown"] },
      { name: "Two-point conversion", aliases: ["Two point conversion", "2 point conversion", "2pt conversion"] },
      { name: "Safety", aliases: ["Two-point safety"] },
      { name: "Pick-six", aliases: ["Pick six", "Interception return touchdown"] },
      { name: "Kick return touchdown", aliases: ["Kick return TD", "Kickoff return touchdown"] },
      { name: "Punt return touchdown", aliases: ["Punt return TD"] },
    ],
    alsoAcceptedAnswers: [
      { name: "Fumble return touchdown", aliases: ["Fumble return TD"] },
      { name: "Blocked kick return touchdown", aliases: ["Blocked kick TD"] },
      { name: "Missed field goal return touchdown", aliases: ["Missed FG return TD"] },
      { name: "Defensive two-point return", aliases: ["Defensive 2 point return", "Defensive conversion return"] },
    ],
  },
  {
    category: "game-concepts",
    entityKind: "other",
    collisionGroup: "penalties",
    prompts: [
      "Name a common NFL penalty.",
      "Name a flag NFL fans complain about.",
      "Name a penalty you might see during an NFL game.",
      "Name a penalty that can erase a big play.",
      "Name a football penalty almost every fan understands.",
    ],
    answers: [
      "Holding",
      "False start",
      { name: "Pass interference", aliases: ["PI", "DPI", "OPI"] },
      { name: "Offsides", aliases: ["Offside"] },
      { name: "Personal foul", aliases: ["Unnecessary roughness"] },
      { name: "Roughing the passer", aliases: ["RTP"] },
      "Delay of game",
      "Illegal formation",
    ],
    alsoAcceptedAnswers: [
      "Facemask",
      "Illegal contact",
      "Intentional grounding",
      "Encroachment",
      "Neutral zone infraction",
      "Horse-collar tackle",
      "Illegal hands to the face",
      "Unsportsmanlike conduct",
      "Illegal motion",
      "Illegal shift",
      "Defensive holding",
      "Illegal block in the back",
      "Ineligible receiver downfield",
      "Illegal use of hands",
      "Taunting",
      "Tripping",
      "Clipping",
    ],
  },
  {
    category: "stats",
    entityKind: "other",
    collisionGroup: "stats",
    prompts: [
      "Name a traditional NFL passing statistic.",
      "Name a passing number fans use to judge an NFL quarterback.",
      "Name a passing stat shown in an NFL broadcast box score.",
      "Name a passing stat people compare after a game.",
      "Name a passing stat that can describe how a quarterback played.",
    ],
    answers: [
      { name: "Passing yards", aliases: ["Pass yards", "Yards"] },
      { name: "Passing touchdowns", aliases: ["Passing TDs", "Pass TDs"] },
      { name: "Completion percentage", aliases: ["Completion pct", "Comp pct"] },
      { name: "Interceptions", aliases: ["INTs", "Picks"] },
      { name: "Pass attempts", aliases: ["Attempts", "ATT"] },
      { name: "Completions", aliases: ["COMP"] },
      { name: "Yards per attempt", aliases: ["YPA"] },
      { name: "Passer rating", aliases: ["QB rating", "Rating"] },
    ],
    alsoAcceptedAnswers: ["QBR", "Longest completion", "Sacks taken", "Touchdown-to-interception ratio"],
  },
  {
    category: "stats",
    entityKind: "other",
    collisionGroup: "stats",
    prompts: [
      "Name an NFL defensive statistic.",
      "Name a stat that can make a defender stand out.",
      "Name a defensive number shown in a box score.",
      "Name a stat fans use to praise a great defender.",
      "Name a defensive stat that can earn Pro Bowl attention.",
    ],
    answers: [
      "Tackles",
      "Sacks",
      { name: "Interceptions", aliases: ["INTs", "Picks"] },
      { name: "Tackles for loss", aliases: ["TFL", "TFLs"] },
      { name: "Pass breakups", aliases: ["PBU", "PBUs", "Passes defended"] },
      { name: "Forced fumbles", aliases: ["FF"] },
      { name: "Fumble recoveries", aliases: ["FR"] },
      { name: "Quarterback hits", aliases: ["QB hits"] },
    ],
    alsoAcceptedAnswers: ["Solo tackles", "Assisted tackles", "Quarterback pressures", "Defensive touchdowns", "Interception return yards", "Sack yards"],
  },
  {
    category: "strategy",
    entityKind: "other",
    collisionGroup: "offense",
    prompts: [
      "Name an offensive concept you hear in the NFL.",
      "Name a football play concept an offense might build around.",
      "Name an offensive idea commentators mention during games.",
      "Name a concept a coordinator might use to stress a defense.",
      "Name an offensive term NFL fans recognize.",
    ],
    answers: [
      { name: "Play-action", aliases: ["Play action", "PA"] },
      { name: "RPO", aliases: ["Run-pass option", "Run pass option"] },
      { name: "Screen pass", aliases: ["Screen"] },
      { name: "Four verticals", aliases: ["Four verts", "4 verts", "Verts"] },
      { name: "Mesh", aliases: ["Mesh concept"] },
      { name: "Zone run", aliases: ["Zone", "Inside zone", "Outside zone"] },
      { name: "Counter", aliases: ["Counter run"] },
      { name: "Bootleg", aliases: ["Boot"] },
    ],
    alsoAcceptedAnswers: ["Read option", "Power run", "Draw", "Trap", "Flood", "Levels", "Sail", "Stick"],
  },
  {
    category: "strategy",
    entityKind: "other",
    collisionGroup: "defense",
    prompts: [
      "Name a defensive coverage, pressure, or concept.",
      "Name a defensive call an NFL team might use.",
      "Name a defensive term commentators mention on broadcasts.",
      "Name a defensive look a quarterback has to identify before the snap.",
      "Name a defensive concept NFL fans hear all the time.",
    ],
    answers: [
      { name: "Cover 2", aliases: ["Cover two"] },
      { name: "Cover 3", aliases: ["Cover three"] },
      { name: "Blitz", aliases: ["Blitzing", "Pressure"] },
      { name: "Man coverage", aliases: ["Man", "Man-to-man", "Man to man"] },
      { name: "Cover 1", aliases: ["Cover one"] },
      { name: "Quarters", aliases: ["Cover 4", "Cover four"] },
      { name: "Zone blitz", aliases: ["Zone pressure"] },
      { name: "Cover 0", aliases: ["Cover zero"] },
    ],
    alsoAcceptedAnswers: ["Tampa 2", "Cover 6", "Quarter-quarter-half", "QB spy", "Bracket coverage", "Prevent defense", "Nickel package", "Dime package"],
  },
  {
    category: "special-teams",
    entityKind: "other",
    collisionGroup: "special-teams",
    prompts: [
      "Name something a special teams unit does.",
      "Name a play that belongs to special teams.",
      "Name a special-teams play that can change field position or points.",
      "Name a special-teams job fans notice during a game.",
      "Name a play involving the kicking game.",
    ],
    answers: [
      { name: "Field goal", aliases: ["FG"] },
      "Punt",
      "Kickoff",
      { name: "Extra point", aliases: ["PAT", "Point after"] },
      "Punt return",
      { name: "Kick return", aliases: ["Kickoff return"] },
      "Onside kick",
      "Fake punt",
    ],
    alsoAcceptedAnswers: ["Kick coverage", "Punt coverage", "Punt block", "Field-goal block", "Long snap", "Hold for a field goal"],
  },
  {
    category: "draft",
    entityKind: "other",
    collisionGroup: "draft",
    prompts: [
      "Name a term associated with the NFL Draft.",
      "Name something fans hear constantly during draft season.",
      "Name a phrase tied to evaluating or selecting NFL prospects.",
      "Name something that can happen during the NFL Draft.",
      "Name a draft term almost every NFL fan knows.",
    ],
    answers: [
      { name: "First-round pick", aliases: ["First round", "1st round", "Round 1"] },
      { name: "Mock draft", aliases: ["Mock"] },
      { name: "Trade up", aliases: ["Move up"] },
      { name: "Trade down", aliases: ["Move down"] },
      { name: "Best player available", aliases: ["BPA", "Best available"] },
      { name: "Combine", aliases: ["NFL Combine", "Scouting Combine"] },
      { name: "Pro day", aliases: ["Pro-day"] },
      { name: "Draft steal", aliases: ["Steal"] },
    ],
    alsoAcceptedAnswers: ["On the clock", "Draft board", "Draft capital", "Compensatory pick", "Sleeper", "Reach", "War room", "Prospect"],
  },
  {
    category: "divisions",
    entityKind: "other",
    collisionGroup: "divisions",
    prompts: [
      "Name an NFL division.",
      "Name one of the league's eight divisions.",
      "Name an AFC or NFC division.",
      "Name an NFL division a team can win.",
      "Name one of the NFL's geographic divisions.",
    ],
    answers: [
      { name: "AFC East", aliases: ["AFC E"] },
      { name: "AFC North", aliases: ["AFC N"] },
      { name: "AFC South", aliases: ["AFC S"] },
      { name: "AFC West", aliases: ["AFC W"] },
      { name: "NFC East", aliases: ["NFC E"] },
      { name: "NFC North", aliases: ["NFC N"] },
      { name: "NFC South", aliases: ["NFC S"] },
      { name: "NFC West", aliases: ["NFC W"] },
    ],
  },
] as const);
