import { expandSportsFeudFamilies } from "./sportsFeudAuthoredHelpers";

export const NFL_SPORTS_FEUD_FAST_1 = expandSportsFeudFamilies("nfl-fast1", [
  {
    category: "teams",
    collisionGroup: "teams",
    prompts: [
      "Name an NFC East team.",
      "Name a team from the NFC East.",
      "Name an NFC East franchise with a huge fan base.",
      "Name a team you think of when someone says NFC East.",
      "Name an NFC East team known nationally.",
    ],
    answers: [
      { name: "Dallas Cowboys", aliases: ["Cowboys", "Dallas"] },
      { name: "Philadelphia Eagles", aliases: ["Eagles", "Philadelphia"] },
      { name: "New York Giants", aliases: ["Giants", "NY Giants"] },
      { name: "Washington Commanders", aliases: ["Commanders", "Washington"] },
      "Dallas Cowboys",
      "Philadelphia Eagles",
      "New York Giants",
      "Washington Commanders",
    ],
  },
  {
    category: "teams",
    collisionGroup: "teams",
    prompts: [
      "Name an NFC North team.",
      "Name a team from the NFC North.",
      "Name an NFC North franchise with a long football history.",
      "Name a team you think of when someone says NFC North.",
      "Name an NFC North team fans recognize quickly.",
    ],
    answers: [
      { name: "Green Bay Packers", aliases: ["Packers", "Green Bay"] },
      { name: "Chicago Bears", aliases: ["Bears", "Chicago"] },
      { name: "Detroit Lions", aliases: ["Lions", "Detroit"] },
      { name: "Minnesota Vikings", aliases: ["Vikings", "Minnesota"] },
      "Green Bay Packers",
      "Chicago Bears",
      "Detroit Lions",
      "Minnesota Vikings",
    ],
  },
  {
    category: "teams",
    collisionGroup: "teams",
    prompts: [
      "Name an AFC North team.",
      "Name a team from the AFC North.",
      "Name an AFC North franchise with a physical reputation.",
      "Name a team you think of when someone says AFC North.",
      "Name an AFC North team known for tough divisional games.",
    ],
    answers: [
      { name: "Pittsburgh Steelers", aliases: ["Steelers", "Pittsburgh"] },
      { name: "Baltimore Ravens", aliases: ["Ravens", "Baltimore"] },
      { name: "Cincinnati Bengals", aliases: ["Bengals", "Cincinnati"] },
      { name: "Cleveland Browns", aliases: ["Browns", "Cleveland"] },
      "Pittsburgh Steelers",
      "Baltimore Ravens",
      "Cincinnati Bengals",
      "Cleveland Browns",
    ],
  },
  {
    category: "teams",
    collisionGroup: "teams",
    prompts: [
      "Name an AFC West team.",
      "Name a team from the AFC West.",
      "Name an AFC West franchise with a famous rivalry.",
      "Name a team you think of when someone says AFC West.",
      "Name an AFC West team with a recognizable national brand.",
    ],
    answers: [
      { name: "Kansas City Chiefs", aliases: ["Chiefs", "Kansas City"] },
      { name: "Las Vegas Raiders", aliases: ["Raiders", "Oakland Raiders"] },
      { name: "Denver Broncos", aliases: ["Broncos", "Denver"] },
      { name: "Los Angeles Chargers", aliases: ["Chargers", "LA Chargers", "San Diego Chargers"] },
      "Kansas City Chiefs",
      "Las Vegas Raiders",
      "Denver Broncos",
      "Los Angeles Chargers",
    ],
  },
  {
    category: "champions",
    collisionGroup: "achievements",
    prompts: [
      "Name a franchise that has won multiple Super Bowls.",
      "Name an NFL team with more than one Super Bowl title.",
      "Name a franchise with a serious Super Bowl trophy case.",
      "Name a team whose history includes multiple Super Bowl wins.",
      "Name a franchise fans associate with repeated championship success.",
    ],
    answers: ["New England Patriots", "Pittsburgh Steelers", "San Francisco 49ers", "Dallas Cowboys", "Kansas City Chiefs", "Green Bay Packers", "New York Giants", "Denver Broncos"],
  },
  {
    category: "players",
    collisionGroup: "quarterbacks",
    prompts: [
      "Name an NFL MVP quarterback.",
      "Name a quarterback who has won league MVP.",
      "Name an MVP-winning NFL quarterback.",
      "Name a quarterback whose season ended with the NFL MVP award.",
      "Name an NFL quarterback fans remember as a league MVP.",
    ],
    answers: ["Tom Brady", "Peyton Manning", "Patrick Mahomes", "Aaron Rodgers", "Lamar Jackson", "Brett Favre", "Steve Young", "Cam Newton"],
  },
  {
    category: "players",
    collisionGroup: "running-backs",
    prompts: [
      "Name an NFL running back who rushed for 2,000 yards in a season.",
      "Name a member of the NFL's 2,000-yard rushing club.",
      "Name a running back remembered for a 2,000-yard season.",
      "Name an NFL back whose season crossed 2,000 rushing yards.",
      "Name a 2,000-yard rusher fans still talk about.",
    ],
    answers: ["Eric Dickerson", "Adrian Peterson", "Jamal Lewis", "Barry Sanders", "Terrell Davis", "Chris Johnson", "Derrick Henry", "OJ Simpson"],
  },
  {
    category: "players",
    collisionGroup: "receivers",
    prompts: [
      "Name an NFL receiver known for huge touchdown production.",
      "Name a receiver you associate with finding the end zone.",
      "Name an NFL wideout whose career includes a lot of touchdown catches.",
      "Name a receiver fans remember as a major red-zone threat.",
      "Name a wide receiver whose scoring ability became part of his reputation.",
    ],
    answers: ["Jerry Rice", "Randy Moss", "Terrell Owens", "Marvin Harrison", "Cris Carter", "Larry Fitzgerald", "Davante Adams", "Calvin Johnson"],
  },
  {
    category: "players",
    collisionGroup: "defenders",
    prompts: [
      "Name an NFL player famous for sacks.",
      "Name a pass rusher whose name belongs in a sack conversation.",
      "Name a defender quarterbacks hated seeing in the backfield.",
      "Name an NFL edge or defensive lineman known for getting to the quarterback.",
      "Name a pass rusher fans associate with dominant pressure.",
    ],
    answers: ["Bruce Smith", "Reggie White", "Michael Strahan", "JJ Watt", "Von Miller", "Aaron Donald", "Derrick Thomas", "TJ Watt"],
  },
  {
    category: "players",
    collisionGroup: "defenders",
    prompts: [
      "Name an NFL defensive back known for interceptions.",
      "Name a ball-hawking NFL defensive back.",
      "Name a DB whose reputation includes taking the ball away.",
      "Name an NFL secondary star quarterbacks had to locate before throwing.",
      "Name a defensive back remembered for making quarterbacks pay.",
    ],
    answers: ["Ed Reed", "Deion Sanders", "Rod Woodson", "Paul Krause", "Charles Woodson", "Champ Bailey", "Richard Sherman", "Darren Sharper"],
  },
] as const);
