import { expandSportsFeudFamilies } from "./sportsFeudAuthoredHelpers";

export const NFL_SPORTS_FEUD_FAST_2 = expandSportsFeudFamilies("nfl-fast2", [
  {
    category: "team-stars",
    entityKind: "person",
    collisionGroup: "quarterbacks",
    prompts: [
      "Name a notable quarterback who started games for the Dallas Cowboys.",
      "Name a Cowboys quarterback fans remember.",
      "Name a Dallas quarterback from a memorable era.",
      "Name a quarterback associated with Cowboys history.",
      "Name a Cowboys signal caller who became a national name.",
    ],
    answers: ["Roger Staubach", "Troy Aikman", "Tony Romo", "Dak Prescott", "Danny White", "Don Meredith", "Quincy Carter", "Vinny Testaverde"],
    alsoAcceptedAnswers: ["Craig Morton", "Steve Pelluer", "Jason Garrett", "Steve Beuerlein", "Cooper Rush"],
  },
  {
    category: "team-stars",
    entityKind: "person",
    collisionGroup: "quarterbacks",
    prompts: [
      "Name a notable quarterback who started games for the Green Bay Packers.",
      "Name a Packers quarterback fans remember.",
      "Name a Green Bay quarterback from a memorable era.",
      "Name a quarterback associated with Packers history.",
      "Name a Packers signal caller who became a national name.",
    ],
    answers: ["Bart Starr", "Brett Favre", "Aaron Rodgers", "Jordan Love", "Lynn Dickey", "Don Majkowski", "Matt Flynn", "Scott Hunter"],
    alsoAcceptedAnswers: ["Tobin Rote", "Zeke Bratkowski", "Brett Hundley", "Malik Willis", "Arnie Herber"],
  },
  {
    category: "team-stars",
    entityKind: "person",
    collisionGroup: "quarterbacks",
    prompts: [
      "Name a notable quarterback who started games for the San Francisco 49ers.",
      "Name a 49ers quarterback fans remember.",
      "Name a San Francisco quarterback from a memorable era.",
      "Name a quarterback associated with 49ers history.",
      "Name a 49ers signal caller who became a national name.",
    ],
    answers: ["Joe Montana", "Steve Young", "Brock Purdy", "Colin Kaepernick", "Jeff Garcia", "Alex Smith", "Jimmy Garoppolo", "John Brodie"],
    alsoAcceptedAnswers: ["Y.A. Tittle", "Jim Plunkett", "Elvis Grbac", "Trey Lance", "Blaine Gabbert", "Nick Mullens"],
  },
  {
    category: "team-stars",
    entityKind: "person",
    collisionGroup: "quarterbacks",
    prompts: [
      "Name a notable quarterback who started games for the Pittsburgh Steelers.",
      "Name a Steelers quarterback fans remember.",
      "Name a Pittsburgh quarterback from a memorable era.",
      "Name a quarterback associated with Steelers history.",
      "Name a Steelers signal caller who became a national name.",
    ],
    answers: ["Terry Bradshaw", "Ben Roethlisberger", "Kordell Stewart", "Neil O'Donnell", "Tommy Maddox", "Mason Rudolph", "Kenny Pickett", "Mike Tomczak"],
    alsoAcceptedAnswers: ["Bobby Layne", "Mark Malone", "Bubby Brister", "Michael Vick", "Charlie Batch", "Mitch Trubisky"],
  },
  {
    category: "team-stars",
    entityKind: "person",
    collisionGroup: "quarterbacks",
    prompts: [
      "Name a notable quarterback who started games for the New England Patriots.",
      "Name a Patriots quarterback fans remember.",
      "Name a New England quarterback from a memorable era.",
      "Name a quarterback associated with Patriots history.",
      "Name a Patriots signal caller who became a national name.",
    ],
    answers: ["Tom Brady", "Drew Bledsoe", "Mac Jones", "Jacoby Brissett", "Jimmy Garoppolo", "Matt Cassel", "Steve Grogan", "Tony Eason"],
    alsoAcceptedAnswers: ["Jim Plunkett", "Cam Newton", "Doug Flutie", "Bailey Zappe", "Drake Maye"],
  },
  {
    category: "team-stars",
    entityKind: "person",
    collisionGroup: "players",
    prompts: [
      "Name a Kansas City Chiefs player fans strongly associate with the franchise.",
      "Name a Chiefs star from a memorable era.",
      "Name a Kansas City player who became a national name.",
      "Name a player you would expect in a Chiefs legends conversation.",
      "Name a Chiefs player whose highlights define part of team history.",
    ],
    answers: ["Patrick Mahomes", "Travis Kelce", "Tony Gonzalez", "Derrick Thomas", "Jamaal Charles", "Priest Holmes", "Tyreek Hill", "Chris Jones"],
    alsoAcceptedAnswers: ["Len Dawson", "Bobby Bell", "Willie Lanier", "Eric Berry", "Dante Hall", "Neil Smith", "Willie Roaf", "Otis Taylor"],
  },
  {
    category: "team-stars",
    entityKind: "person",
    collisionGroup: "defenders",
    prompts: [
      "Name a Baltimore Ravens defensive star.",
      "Name a defender strongly associated with Ravens football.",
      "Name a Baltimore defensive player who became a national name.",
      "Name a defender you would expect in a Ravens legends conversation.",
      "Name a Ravens player whose identity fits the franchise's defensive reputation.",
    ],
    answers: ["Ray Lewis", "Ed Reed", "Terrell Suggs", "Haloti Ngata", "Peter Boulware", "Chris McAlister", "Marlon Humphrey", "Roquan Smith"],
    alsoAcceptedAnswers: ["Sam Adams", "Bart Scott", "Tony Siragusa", "Adalius Thomas", "Kyle Hamilton", "Matt Judon", "Jarret Johnson"],
  },
  {
    category: "team-stars",
    entityKind: "person",
    collisionGroup: "receivers",
    prompts: [
      "Name a famous Minnesota Vikings receiver.",
      "Name a Vikings pass catcher fans remember quickly.",
      "Name a Minnesota wide receiver who became a national name.",
      "Name a receiver you would expect in a Vikings legends conversation.",
      "Name a Vikings receiver whose highlights helped define an era.",
    ],
    answers: ["Randy Moss", "Cris Carter", "Justin Jefferson", "Adam Thielen", "Anthony Carter", "Stefon Diggs", "Jake Reed", "Sammy White"],
    alsoAcceptedAnswers: ["Ahmad Rashad", "Percy Harvin", "Sidney Rice", "Nate Burleson"],
  },
  {
    category: "team-stars",
    entityKind: "person",
    collisionGroup: "players",
    prompts: [
      "Name a famous Raiders player.",
      "Name a player strongly associated with the Raiders.",
      "Name a Raiders star whose personality fit the franchise.",
      "Name a player you would expect in a Raiders legends conversation.",
      "Name a Raiders player whose career became part of the team's mythology.",
    ],
    answers: ["Marcus Allen", "Bo Jackson", "Tim Brown", "Howie Long", "Charles Woodson", "Ken Stabler", "Gene Upshaw", "Fred Biletnikoff"],
    alsoAcceptedAnswers: ["Willie Brown", "Art Shell", "Jim Otto", "Lester Hayes", "Cliff Branch", "Dave Casper", "Ted Hendricks", "George Blanda"],
  },
  {
    category: "team-stars",
    entityKind: "person",
    collisionGroup: "defenders",
    prompts: [
      "Name a famous Chicago Bears defender.",
      "Name a defensive player strongly associated with the Bears.",
      "Name a Bears defender who became a national name.",
      "Name a player you would expect in a Bears defensive legends conversation.",
      "Name a Bears player whose career fits the franchise's defensive identity.",
    ],
    answers: ["Dick Butkus", "Mike Singletary", "Brian Urlacher", "Richard Dent", "Dan Hampton", "Lance Briggs", "Charles Tillman", "Khalil Mack"],
    alsoAcceptedAnswers: ["Doug Atkins", "Steve McMichael", "Wilber Marshall", "Gary Fencik", "Otis Wilson", "Roosevelt Colvin", "Dave Duerson"],
  },
] as const);
