import { expandSportsFeudFamilies } from "./sportsFeudAuthoredHelpers";

export const NFL_SPORTS_FEUD_FAST_3 = expandSportsFeudFamilies("nfl-fast3", [
  {
    category: "coaches",
    entityKind: "person",
    collisionGroup: "coaches",
    prompts: [
      "Name an NFL head coach who won multiple Super Bowls.",
      "Name a head coach with more than one Super Bowl win.",
      "Name a coach you remember lifting the Lombardi Trophy multiple times.",
      "Name an NFL head coach whose résumé includes multiple Super Bowl titles.",
      "Name a multiple-time Super Bowl-winning coach almost every NFL fan knows.",
    ],
    answers: ["Bill Belichick", "Andy Reid", "Bill Walsh", "Chuck Noll", "Joe Gibbs", "Tom Landry", "Don Shula", "Bill Parcells"],
    alsoAcceptedAnswers: ["George Seifert", "Tom Coughlin", "Mike Shanahan", "Jimmy Johnson", "Tom Flores"],
  },
  {
    category: "coaches",
    entityKind: "person",
    collisionGroup: "coaches",
    prompts: [
      "Name an NFL coach known for offense.",
      "Name a coach whose offensive system became part of his reputation.",
      "Name an NFL coach you associate with creative play design.",
      "Name an offensive-minded coach fans recognize quickly.",
      "Name a coach whose teams are remembered for moving the ball.",
    ],
    answers: ["Andy Reid", "Bill Walsh", "Sean McVay", "Mike Shanahan", "Kyle Shanahan", "Mike Holmgren", "Don Coryell", "Sean Payton"],
    alsoAcceptedAnswers: ["Sid Gillman", "Paul Brown", "Mike Martz", "Bruce Arians", "Jon Gruden", "Mike McDaniel", "Doug Pederson", "Kevin O'Connell"],
  },
  {
    category: "coaches",
    entityKind: "person",
    collisionGroup: "coaches",
    prompts: [
      "Name an NFL coach strongly associated with defense.",
      "Name a coach whose teams were known for being hard to score on.",
      "Name an NFL coach with a defensive identity.",
      "Name a coach you would trust to build a tough defense.",
      "Name a coach whose best teams were famous for physical defense.",
    ],
    answers: ["Bill Belichick", "Mike Tomlin", "Bill Parcells", "Tony Dungy", "Pete Carroll", "Mike Ditka", "Buddy Ryan", "Dick LeBeau"],
    alsoAcceptedAnswers: ["Bill Cowher", "Rex Ryan", "Wade Phillips", "Lovie Smith", "Dan Quinn", "George Allen", "Marty Schottenheimer"],
  },
  {
    category: "rivalries",
    entityKind: "other",
    collisionGroup: "rivalries",
    prompts: [
      "Name a famous NFL rivalry.",
      "Name a divisional matchup with real bad blood.",
      "Name an NFL game fans circle twice every season.",
      "Name a rivalry where the records do not matter much.",
      "Name an NFL rivalry a casual fan might recognize.",
    ],
    answers: ["Packers-Bears", "Cowboys-Eagles", "Steelers-Ravens", "49ers-Cowboys", "Raiders-Chiefs", "Giants-Eagles", "Packers-Vikings", "Jets-Patriots"],
    alsoAcceptedAnswers: ["Cowboys-Commanders", "Patriots-Colts", "49ers-Seahawks", "Browns-Steelers", "Saints-Falcons", "Chiefs-Broncos", "Bears-Vikings", "Bengals-Steelers"],
  },
  {
    category: "venues",
    entityKind: "other",
    collisionGroup: "venues",
    prompts: [
      "Name an NFL stadium known for being loud.",
      "Name a stadium where a road quarterback can struggle to communicate.",
      "Name an NFL venue famous for a hostile atmosphere.",
      "Name a stadium you would expect on a loudest-in-the-NFL list.",
      "Name a home field where crowd noise feels like a real advantage.",
    ],
    answers: [
      { name: "Arrowhead Stadium", aliases: ["Arrowhead", "Chiefs", "Kansas City"] },
      { name: "Lumen Field", aliases: ["Lumen", "Seahawks", "Seattle"] },
      { name: "Lambeau Field", aliases: ["Lambeau", "Packers", "Green Bay"] },
      { name: "Highmark Stadium", aliases: ["Highmark", "Bills", "Buffalo"] },
      { name: "Superdome", aliases: ["Saints", "New Orleans", "Caesars Superdome"] },
      { name: "Lincoln Financial Field", aliases: ["The Linc", "Linc", "Eagles", "Philadelphia"] },
      { name: "M&T Bank Stadium", aliases: ["M and T", "Ravens", "Baltimore"] },
      { name: "U.S. Bank Stadium", aliases: ["US Bank", "Vikings", "Minnesota"] },
    ],
    alsoAcceptedAnswers: [
      { name: "Ford Field", aliases: ["Lions", "Detroit"] },
      { name: "Empower Field at Mile High", aliases: ["Mile High", "Broncos", "Denver"] },
    ],
  },
  {
    category: "history",
    entityKind: "other",
    collisionGroup: "super-bowls",
    prompts: [
      "Name a famous Super Bowl matchup.",
      "Name a Super Bowl pairing fans still remember.",
      "Name a championship game that produced an iconic NFL moment.",
      "Name a Super Bowl you would expect in an NFL history montage.",
      "Name a Super Bowl matchup that became bigger than the final score.",
    ],
    answers: ["Giants-Patriots", "49ers-Bengals", "Cowboys-Bills", "Steelers-Cowboys", "Patriots-Seahawks", "Chiefs-49ers", "Rams-Titans", "Eagles-Patriots"],
    alsoAcceptedAnswers: ["Chiefs-Eagles", "Ravens-49ers", "Colts-Saints", "Broncos-Seahawks", "Rams-Patriots", "Bills-Giants", "Bears-Patriots", "Chiefs-Buccaneers"],
  },
  {
    category: "awards",
    entityKind: "other",
    collisionGroup: "awards",
    prompts: [
      "Name a major NFL award.",
      "Name an NFL honor players dream about winning.",
      "Name an award fans debate during the season.",
      "Name an NFL award that can boost a player's legacy.",
      "Name an individual honor announced around the end of an NFL season.",
    ],
    answers: [
      { name: "NFL MVP", aliases: ["MVP"] },
      { name: "Super Bowl MVP", aliases: ["SB MVP", "Super Bowl Most Valuable Player"] },
      { name: "Defensive Player of the Year", aliases: ["DPOY", "Defensive POY"] },
      { name: "Offensive Player of the Year", aliases: ["OPOY", "Offensive POY"] },
      { name: "Offensive Rookie of the Year", aliases: ["OROY", "Offensive ROY"] },
      { name: "Defensive Rookie of the Year", aliases: ["DROY", "Defensive ROY"] },
      { name: "Comeback Player of the Year", aliases: ["CPOY", "Comeback POY"] },
      { name: "Walter Payton Man of the Year", aliases: ["Walter Payton", "Man of the Year", "WPMOY"] },
    ],
    alsoAcceptedAnswers: [
      { name: "First-team All-Pro", aliases: ["All-Pro", "First team All Pro"] },
      { name: "Pro Bowl selection", aliases: ["Pro Bowl", "Pro Bowler"] },
      "Art Rooney Sportsmanship Award",
    ],
  },
  {
    category: "players",
    entityKind: "person",
    collisionGroup: "tight-ends",
    prompts: [
      "Name a famous NFL tight end.",
      "Name a tight end whose career belongs in a legends conversation.",
      "Name an NFL tight end who became a major receiving weapon.",
      "Name a tight end almost every football fan recognizes.",
      "Name a tight end whose highlights changed expectations for the position.",
    ],
    answers: ["Tony Gonzalez", "Rob Gronkowski", "Travis Kelce", "Antonio Gates", "Jason Witten", "Shannon Sharpe", "Kellen Winslow", "George Kittle"],
    alsoAcceptedAnswers: ["Ozzie Newsome", "Mike Ditka", "John Mackey", "Dave Casper", "Mark Andrews", "Zach Ertz", "Dallas Clark", "Vernon Davis"],
  },
  {
    category: "players",
    entityKind: "person",
    collisionGroup: "kickers",
    prompts: [
      "Name a famous NFL kicker.",
      "Name a kicker you would trust with a game-winning field goal.",
      "Name an NFL kicker fans recognize by name.",
      "Name a kicker whose career included huge pressure kicks.",
      "Name a kicker who became unusually famous for his position.",
    ],
    answers: ["Justin Tucker", "Adam Vinatieri", "Morten Andersen", "Sebastian Janikowski", "Jason Elam", "Gary Anderson", "Stephen Gostkowski", "Robbie Gould"],
    alsoAcceptedAnswers: ["Jan Stenerud", "Lou Groza", "Matt Prater", "Harrison Butker", "Nick Folk", "Matt Bryant", "John Kasay"],
  },
  {
    category: "players",
    entityKind: "person",
    collisionGroup: "returners",
    prompts: [
      "Name a famous NFL return specialist.",
      "Name a player you would hate to kick or punt to.",
      "Name an NFL player known for dangerous returns.",
      "Name a returner who could flip field position in seconds.",
      "Name a player whose special-teams highlights became part of his fame.",
    ],
    answers: ["Devin Hester", "Dante Hall", "Brian Mitchell", "Josh Cribbs", "Cordarrelle Patterson", "Deion Sanders", "Tyreek Hill", "Desmond Howard"],
    alsoAcceptedAnswers: ["Gale Sayers", "Billy Johnson", "Mel Gray", "Jacoby Jones", "Leon Washington", "Ted Ginn Jr.", "Darren Sproles"],
  },
] as const);
