import { expandSportsFeudFamilies } from "./sportsFeudAuthoredHelpers";

const variants = (prompts: readonly string[], rankings: readonly (readonly string[])[], accepted: readonly string[]) =>
  prompts.map((prompt, index) => ({ prompt, answers: rankings[index], alsoAcceptedAnswers: accepted }));

export const NFL_SPORTS_FEUD_FAST_4 = expandSportsFeudFamilies("nfl-fast4", [
  { category:"positions", entityKind:"other", collisionGroup:"positions", prompts: variants(
    ["Name an NFL position other than quarterback.","Name a position you can play in the NFL.","Name a football position that produces stars.","Name a position group coaches talk about constantly.","Name a position that can change a game with one play."],
    [["Running back","Wide receiver","Linebacker","Cornerback","Defensive end","Safety","Tight end","Offensive tackle"],["Wide receiver","Running back","Linebacker","Cornerback","Safety","Tight end","Defensive end","Kicker"],["Wide receiver","Running back","Cornerback","Linebacker","Defensive end","Tight end","Safety","Kicker"],["Offensive line","Defensive line","Wide receiver","Linebacker","Cornerback","Running back","Tight end","Safety"],["Wide receiver","Running back","Cornerback","Safety","Defensive end","Linebacker","Kicker","Tight end"]],
    ["Defensive tackle","Guard","Center","Punter","Fullback","Long snapper","Nose tackle","Offensive tackle","Offensive line","Defensive line","Kicker"]), answers:["Running back","Wide receiver","Linebacker","Cornerback","Defensive end","Safety","Tight end","Offensive tackle"] },
  { category:"game-concepts", entityKind:"other", collisionGroup:"scoring", prompts: variants(
    ["Name a way to score points in an NFL game.","Name something that can put points on the scoreboard.","Name a scoring play you can see on a Sunday.","Name a way an offense, defense, or special teams unit can score.","Name something that changes the score in a football game."],
    [["Touchdown","Field goal","Extra point","Two-point conversion","Safety","Pick-six","Kick return touchdown","Punt return touchdown"],["Touchdown","Field goal","Extra point","Two-point conversion","Safety","Pick-six","Fumble return touchdown","Kick return touchdown"],["Touchdown","Field goal","Extra point","Two-point conversion","Pick-six","Safety","Kick return touchdown","Punt return touchdown"],["Touchdown","Field goal","Pick-six","Kick return touchdown","Punt return touchdown","Fumble return touchdown","Safety","Extra point"],["Touchdown","Field goal","Extra point","Two-point conversion","Safety","Pick-six","Fumble return touchdown","Defensive two-point return"]],
    ["Fumble return touchdown","Blocked kick return touchdown","Missed field goal return touchdown","Defensive two-point return","Punt return touchdown","Kick return touchdown"]), answers:["Touchdown","Field goal","Extra point","Two-point conversion","Safety","Pick-six","Kick return touchdown","Punt return touchdown"] },
  { category:"game-concepts", entityKind:"other", collisionGroup:"penalties", prompts: variants(
    ["Name a common NFL penalty.","Name a flag NFL fans complain about.","Name a penalty you might see during an NFL game.","Name a penalty that can erase a big play.","Name a football penalty almost every fan understands."],
    [["Holding","False start","Pass interference","Offsides","Personal foul","Roughing the passer","Delay of game","Facemask"],["Pass interference","Roughing the passer","Holding","Personal foul","Taunting","Illegal contact","Offsides","False start"],["Holding","False start","Pass interference","Offsides","Delay of game","Roughing the passer","Facemask","Personal foul"],["Holding","Pass interference","Illegal block in the back","Offensive pass interference","Illegal formation","Ineligible receiver downfield","Personal foul","Illegal motion"],["Holding","False start","Pass interference","Offsides","Facemask","Roughing the passer","Delay of game","Personal foul"]],
    ["Illegal contact","Intentional grounding","Encroachment","Neutral zone infraction","Horse-collar tackle","Illegal hands to the face","Unsportsmanlike conduct","Illegal motion","Illegal shift","Defensive holding","Illegal block in the back","Ineligible receiver downfield","Illegal use of hands","Taunting","Tripping","Clipping","Illegal formation","Offensive pass interference"]), answers:["Holding","False start","Pass interference","Offsides","Personal foul","Roughing the passer","Delay of game","Illegal formation"] },
  { category:"stats", entityKind:"other", collisionGroup:"stats", prompts: variants(
    ["Name a traditional NFL passing statistic.","Name a passing number fans use to judge an NFL quarterback.","Name a passing stat shown in an NFL broadcast box score.","Name a passing stat people compare after a game.","Name a passing stat that can describe how a quarterback played."],
    [["Passing yards","Passing touchdowns","Completion percentage","Interceptions","Pass attempts","Completions","Yards per attempt","Passer rating"],["Passing yards","Passing touchdowns","Interceptions","Completion percentage","Passer rating","QBR","Yards per attempt","Touchdown-to-interception ratio"],["Passing yards","Passing touchdowns","Completions","Pass attempts","Interceptions","Completion percentage","Passer rating","Longest completion"],["Passing yards","Passing touchdowns","Interceptions","Completion percentage","Passer rating","Yards per attempt","Completions","Pass attempts"],["Passer rating","Passing yards","Passing touchdowns","Interceptions","Completion percentage","QBR","Yards per attempt","Sacks taken"]],
    ["QBR","Longest completion","Sacks taken","Touchdown-to-interception ratio","Pass attempts","Completions","Yards per attempt","Passer rating"]), answers:["Passing yards","Passing touchdowns","Completion percentage","Interceptions","Pass attempts","Completions","Yards per attempt","Passer rating"] },
  { category:"stats", entityKind:"other", collisionGroup:"stats", prompts: variants(
    ["Name an NFL defensive statistic.","Name a stat that can make a defender stand out.","Name a defensive number shown in a box score.","Name a stat fans use to praise a great defender.","Name a defensive stat that can earn Pro Bowl attention."],
    [["Tackles","Sacks","Interceptions","Tackles for loss","Pass breakups","Forced fumbles","Fumble recoveries","Quarterback hits"],["Sacks","Interceptions","Tackles","Forced fumbles","Tackles for loss","Pass breakups","Quarterback pressures","Defensive touchdowns"],["Tackles","Sacks","Interceptions","Tackles for loss","Pass breakups","Forced fumbles","Fumble recoveries","Solo tackles"],["Sacks","Interceptions","Tackles for loss","Forced fumbles","Tackles","Pass breakups","Quarterback pressures","Defensive touchdowns"],["Sacks","Interceptions","Tackles","Tackles for loss","Forced fumbles","Pass breakups","Quarterback hits","Defensive touchdowns"]],
    ["Solo tackles","Assisted tackles","Quarterback pressures","Defensive touchdowns","Interception return yards","Sack yards","Fumble recoveries","Quarterback hits"]), answers:["Tackles","Sacks","Interceptions","Tackles for loss","Pass breakups","Forced fumbles","Fumble recoveries","Quarterback hits"] },
  { category:"strategy", entityKind:"other", collisionGroup:"offense", prompts: variants(
    ["Name an offensive concept you hear in the NFL.","Name a football play concept an offense might build around.","Name an offensive idea commentators mention during games.","Name a concept a coordinator might use to stress a defense.","Name an offensive term NFL fans recognize."],
    [["Play-action","RPO","Screen pass","Four verticals","Mesh","Zone run","Counter","Bootleg"],["Zone run","Play-action","RPO","Counter","Screen pass","Power run","Mesh","Read option"],["Play-action","RPO","Screen pass","Blitz pickup","Zone run","Bootleg","Four verticals","Draw"],["RPO","Play-action","Mesh","Four verticals","Screen pass","Flood","Bootleg","Counter"],["Play-action","RPO","Screen pass","Zone run","Bootleg","Draw","Counter","Four verticals"]],
    ["Read option","Power run","Draw","Trap","Flood","Levels","Sail","Stick","Mesh","Zone run","Counter","Bootleg","Four verticals","Blitz pickup"]), answers:["Play-action","RPO","Screen pass","Four verticals","Mesh","Zone run","Counter","Bootleg"] },
  { category:"strategy", entityKind:"other", collisionGroup:"defense", prompts: variants(
    ["Name a defensive coverage, pressure, or concept.","Name a defensive call an NFL team might use.","Name a defensive term commentators mention on broadcasts.","Name a defensive look a quarterback has to identify before the snap.","Name a defensive concept NFL fans hear all the time."],
    [["Cover 2","Cover 3","Blitz","Man coverage","Cover 1","Quarters","Zone blitz","Cover 0"],["Blitz","Man coverage","Cover 3","Cover 2","Cover 1","Zone blitz","Cover 0","Quarters"],["Blitz","Man coverage","Cover 2","Cover 3","Prevent defense","Zone blitz","Nickel package","QB spy"],["Cover 2","Cover 3","Cover 1","Cover 0","Man coverage","Blitz","Quarters","Cover 6"],["Blitz","Man coverage","Cover 2","Cover 3","Zone blitz","Cover 1","Quarters","Prevent defense"]],
    ["Tampa 2","Cover 6","Quarter-quarter-half","QB spy","Bracket coverage","Prevent defense","Nickel package","Dime package","Cover 0","Quarters","Zone blitz"]), answers:["Cover 2","Cover 3","Blitz","Man coverage","Cover 1","Quarters","Zone blitz","Cover 0"] },
  { category:"special-teams", entityKind:"other", collisionGroup:"special-teams", prompts: variants(
    ["Name something a special teams unit does.","Name a play that belongs to special teams.","Name a special-teams play that can change field position or points.","Name a special-teams job fans notice during a game.","Name a play involving the kicking game."],
    [["Field goal","Punt","Kickoff","Extra point","Punt return","Kick return","Onside kick","Fake punt"],["Punt","Kickoff","Field goal","Extra point","Punt return","Kick return","Onside kick","Fake punt"],["Punt","Field goal","Kick return","Punt return","Onside kick","Punt block","Field-goal block","Fake punt"],["Kicker","Punter","Kick returner","Punt returner","Long snapper","Holder","Kick coverage","Punt coverage"],["Field goal","Kickoff","Extra point","Onside kick","Kick return","Punt","Field-goal block","Fake field goal"]],
    ["Kick coverage","Punt coverage","Punt block","Field-goal block","Long snap","Hold for a field goal","Kicker","Punter","Kick returner","Punt returner","Long snapper","Holder","Fake field goal"]), answers:["Field goal","Punt","Kickoff","Extra point","Punt return","Kick return","Onside kick","Fake punt"] },
  { category:"draft", entityKind:"other", collisionGroup:"draft", prompts: variants(
    ["Name a term associated with the NFL Draft.","Name something fans hear constantly during draft season.","Name a phrase tied to evaluating or selecting NFL prospects.","Name something that can happen during the NFL Draft.","Name a draft term almost every NFL fan knows."],
    [["First-round pick","Mock draft","Trade up","Trade down","Best player available","Combine","Pro day","Draft steal"],["Mock draft","Combine","First-round pick","Trade up","Best player available","Sleeper","Reach","Pro day"],["Best player available","Prospect","Combine","Pro day","Draft board","Sleeper","Reach","Draft grade"],["Trade up","Trade down","First-round pick","On the clock","Compensatory pick","Draft steal","Reach","Best player available"],["Mock draft","First-round pick","Trade up","Combine","Best player available","On the clock","Sleeper","Draft board"]],
    ["On the clock","Draft board","Draft capital","Compensatory pick","Sleeper","Reach","War room","Prospect","Draft grade","Pro day","Trade down","Draft steal"]), answers:["First-round pick","Mock draft","Trade up","Trade down","Best player available","Combine","Pro day","Draft steal"] },
  { category:"divisions", entityKind:"other", collisionGroup:"divisions", prompts: variants(
    ["Name an NFL division.","Name one of the league's eight divisions.","Name an AFC or NFC division.","Name an NFL division a team can win.","Name one of the NFL's geographic divisions."],
    [["AFC East","AFC North","AFC South","AFC West","NFC East","NFC North","NFC South","NFC West"],["NFC East","AFC East","NFC North","AFC North","AFC West","NFC West","NFC South","AFC South"],["AFC East","NFC East","AFC North","NFC North","AFC West","NFC West","AFC South","NFC South"],["NFC East","AFC North","AFC West","NFC North","AFC East","NFC West","NFC South","AFC South"],["AFC East","NFC East","AFC North","NFC North","AFC South","NFC South","AFC West","NFC West"]], []), answers:["AFC East","AFC North","AFC South","AFC West","NFC East","NFC North","NFC South","NFC West"] },
] as const);
