import { expandSportsFeudFamilies } from "./sportsFeudAuthoredHelpers";

export const NFL_SPORTS_FEUD_FAST_1 = expandSportsFeudFamilies("nfl-fast1", [
  {
    category: "teams",
    entityKind: "team",
    collisionGroup: "teams",
    prompts: [
      "Name an NFC team.",
      "Name a franchise from the NFC.",
      {
        prompt: "Name an NFC team with a major national fan base.",
        answers: ["Dallas Cowboys", "Green Bay Packers", "San Francisco 49ers", "Philadelphia Eagles", "Chicago Bears", "New York Giants", "Seattle Seahawks", "Minnesota Vikings"],
        alsoAcceptedAnswers: ["Washington Commanders", "Detroit Lions", "Tampa Bay Buccaneers", "Atlanta Falcons", "New Orleans Saints", "Carolina Panthers", "Arizona Cardinals", "Los Angeles Rams"],
      },
      {
        prompt: "Name a team you think of when someone says the NFC.",
        answers: ["Dallas Cowboys", "San Francisco 49ers", "Green Bay Packers", "Philadelphia Eagles", "New York Giants", "Seattle Seahawks", "Los Angeles Rams", "Chicago Bears"],
        alsoAcceptedAnswers: ["Minnesota Vikings", "Washington Commanders", "Detroit Lions", "Tampa Bay Buccaneers", "Atlanta Falcons", "New Orleans Saints", "Carolina Panthers", "Arizona Cardinals"],
      },
      {
        prompt: "Name an NFC franchise almost every football fan recognizes.",
        answers: ["Dallas Cowboys", "Green Bay Packers", "San Francisco 49ers", "Philadelphia Eagles", "New York Giants", "Chicago Bears", "Seattle Seahawks", "Los Angeles Rams"],
        alsoAcceptedAnswers: ["Minnesota Vikings", "Washington Commanders", "Detroit Lions", "Tampa Bay Buccaneers", "Atlanta Falcons", "New Orleans Saints", "Carolina Panthers", "Arizona Cardinals"],
      },
    ],
    answers: [
      { name: "Dallas Cowboys", aliases: ["Cowboys", "Dallas"] },
      { name: "San Francisco 49ers", aliases: ["49ers", "Niners", "San Francisco"] },
      { name: "Green Bay Packers", aliases: ["Packers", "Green Bay"] },
      { name: "Philadelphia Eagles", aliases: ["Eagles", "Philadelphia", "Philly"] },
      { name: "New York Giants", aliases: ["Giants", "NY Giants"] },
      { name: "Seattle Seahawks", aliases: ["Seahawks", "Seattle"] },
      { name: "Minnesota Vikings", aliases: ["Vikings", "Minnesota"] },
      { name: "Los Angeles Rams", aliases: ["Rams", "LA Rams"] },
    ],
    alsoAcceptedAnswers: [
      { name: "Washington Commanders", aliases: ["Commanders", "Washington"] },
      { name: "Chicago Bears", aliases: ["Bears", "Chicago"] },
      { name: "Detroit Lions", aliases: ["Lions", "Detroit"] },
      { name: "Tampa Bay Buccaneers", aliases: ["Buccaneers", "Bucs", "Tampa Bay", "Tampa"] },
      { name: "Atlanta Falcons", aliases: ["Falcons", "Atlanta"] },
      { name: "New Orleans Saints", aliases: ["Saints", "New Orleans"] },
      { name: "Carolina Panthers", aliases: ["Panthers", "Carolina"] },
      { name: "Arizona Cardinals", aliases: ["Cardinals", "Arizona"] },
    ],
  },
  {
    category: "teams",
    entityKind: "team",
    collisionGroup: "teams",
    prompts: [
      "Name an AFC team.",
      "Name a franchise from the AFC.",
      {
        prompt: "Name an AFC team with a major national brand.",
        answers: ["Kansas City Chiefs", "Pittsburgh Steelers", "New England Patriots", "Las Vegas Raiders", "Buffalo Bills", "Denver Broncos", "Miami Dolphins", "Baltimore Ravens"],
        alsoAcceptedAnswers: ["New York Jets", "Cincinnati Bengals", "Cleveland Browns", "Houston Texans", "Indianapolis Colts", "Jacksonville Jaguars", "Tennessee Titans", "Los Angeles Chargers"],
      },
      {
        prompt: "Name a team you think of when someone says the AFC.",
        answers: ["Kansas City Chiefs", "Pittsburgh Steelers", "New England Patriots", "Buffalo Bills", "Baltimore Ravens", "Denver Broncos", "Las Vegas Raiders", "Cincinnati Bengals"],
        alsoAcceptedAnswers: ["Miami Dolphins", "New York Jets", "Cleveland Browns", "Houston Texans", "Indianapolis Colts", "Jacksonville Jaguars", "Tennessee Titans", "Los Angeles Chargers"],
      },
      {
        prompt: "Name an AFC franchise almost every football fan recognizes.",
        answers: ["Pittsburgh Steelers", "Kansas City Chiefs", "New England Patriots", "Las Vegas Raiders", "Buffalo Bills", "Denver Broncos", "Miami Dolphins", "New York Jets"],
        alsoAcceptedAnswers: ["Baltimore Ravens", "Cincinnati Bengals", "Cleveland Browns", "Houston Texans", "Indianapolis Colts", "Jacksonville Jaguars", "Tennessee Titans", "Los Angeles Chargers"],
      },
    ],
    answers: [
      { name: "Kansas City Chiefs", aliases: ["Chiefs", "Kansas City", "KC"] },
      { name: "Pittsburgh Steelers", aliases: ["Steelers", "Pittsburgh"] },
      { name: "New England Patriots", aliases: ["Patriots", "New England"] },
      { name: "Buffalo Bills", aliases: ["Bills", "Buffalo"] },
      { name: "Baltimore Ravens", aliases: ["Ravens", "Baltimore"] },
      { name: "Denver Broncos", aliases: ["Broncos", "Denver"] },
      { name: "Las Vegas Raiders", aliases: ["Raiders", "Las Vegas", "Vegas", "Oakland Raiders"] },
      { name: "Miami Dolphins", aliases: ["Dolphins", "Miami"] },
    ],
    alsoAcceptedAnswers: [
      { name: "New York Jets", aliases: ["Jets", "NY Jets"] },
      { name: "Cincinnati Bengals", aliases: ["Bengals", "Cincinnati"] },
      { name: "Cleveland Browns", aliases: ["Browns", "Cleveland"] },
      { name: "Houston Texans", aliases: ["Texans", "Houston"] },
      { name: "Indianapolis Colts", aliases: ["Colts", "Indianapolis", "Indy"] },
      { name: "Jacksonville Jaguars", aliases: ["Jaguars", "Jags", "Jacksonville"] },
      { name: "Tennessee Titans", aliases: ["Titans", "Tennessee"] },
      { name: "Los Angeles Chargers", aliases: ["Chargers", "LA Chargers", "Bolts"] },
    ],
  },
  {
    category: "team-identity",
    entityKind: "team",
    collisionGroup: "teams",
    prompts: [
      "Name an NFL team you associate with cold-weather football.",
      {
        prompt: "Name a franchise whose outdoor home games can feel brutally cold.",
        answers: ["Green Bay Packers", "Buffalo Bills", "Chicago Bears", "Cleveland Browns", "Pittsburgh Steelers", "Denver Broncos", "New England Patriots", "Kansas City Chiefs"],
        alsoAcceptedAnswers: ["Philadelphia Eagles", "New York Giants", "New York Jets", "Cincinnati Bengals", "Baltimore Ravens"],
      },
      {
        prompt: "Name an NFL team that looks natural playing in snow.",
        answers: ["Green Bay Packers", "Buffalo Bills", "Chicago Bears", "Cleveland Browns", "Denver Broncos", "Pittsburgh Steelers", "New England Patriots", "Kansas City Chiefs"],
        alsoAcceptedAnswers: ["Philadelphia Eagles", "New York Giants", "New York Jets", "Cincinnati Bengals", "Baltimore Ravens", "Minnesota Vikings"],
      },
      {
        prompt: "Name a team you picture in a freezing late-season game.",
        answers: ["Green Bay Packers", "Buffalo Bills", "Chicago Bears", "Cleveland Browns", "Pittsburgh Steelers", "New England Patriots", "Denver Broncos", "Kansas City Chiefs"],
        alsoAcceptedAnswers: ["Philadelphia Eagles", "New York Giants", "New York Jets", "Cincinnati Bengals", "Baltimore Ravens"],
      },
      {
        prompt: "Name a franchise whose fans know how to handle cold football weather.",
        answers: ["Green Bay Packers", "Buffalo Bills", "Chicago Bears", "Cleveland Browns", "Pittsburgh Steelers", "Denver Broncos", "New England Patriots", "Kansas City Chiefs"],
        alsoAcceptedAnswers: ["Minnesota Vikings", "Philadelphia Eagles", "New York Giants", "New York Jets", "Cincinnati Bengals", "Baltimore Ravens"],
      },
    ],
    answers: ["Green Bay Packers", "Buffalo Bills", "Chicago Bears", "Pittsburgh Steelers", "New England Patriots", "Cleveland Browns", "Minnesota Vikings", "Denver Broncos"],
    alsoAcceptedAnswers: ["Kansas City Chiefs", "Philadelphia Eagles", "New York Giants", "New York Jets", "Cincinnati Bengals", "Baltimore Ravens"],
  },
  {
    category: "team-identity",
    entityKind: "team",
    collisionGroup: "teams",
    prompts: [
      "Name an AFC franchise with a strong historical identity.",
      "Name an AFC team with decades of recognizable football history.",
      "Name a franchise that belongs in an AFC history conversation.",
      "Name an AFC team whose past includes famous players or playoff runs.",
      "Name an AFC franchise almost every generation of fans recognizes.",
    ],
    answers: ["Pittsburgh Steelers", "New England Patriots", "Kansas City Chiefs", "Las Vegas Raiders", "Denver Broncos", "Miami Dolphins", "Buffalo Bills", "Baltimore Ravens"],
    alsoAcceptedAnswers: ["New York Jets", "Cincinnati Bengals", "Cleveland Browns", "Houston Texans", "Indianapolis Colts", "Jacksonville Jaguars", "Tennessee Titans", "Los Angeles Chargers"],
  },
  {
    category: "champions",
    entityKind: "team",
    collisionGroup: "achievements",
    prompts: [
      "Name a franchise that has won multiple Super Bowls.",
      "Name an NFL team with more than one Super Bowl title.",
      "Name a franchise with a serious Super Bowl trophy case.",
      "Name a team whose history includes multiple Super Bowl wins.",
      "Name a franchise fans associate with repeated championship success.",
    ],
    answers: ["New England Patriots", "Pittsburgh Steelers", "San Francisco 49ers", "Dallas Cowboys", "Kansas City Chiefs", "Green Bay Packers", "New York Giants", "Denver Broncos"],
    alsoAcceptedAnswers: ["Las Vegas Raiders", "Miami Dolphins", "Washington Commanders", "Indianapolis Colts", "Baltimore Ravens", "Tampa Bay Buccaneers", "Los Angeles Rams", "Philadelphia Eagles", "Seattle Seahawks"],
  },
  {
    category: "players",
    entityKind: "person",
    collisionGroup: "quarterbacks",
    prompts: [
      "Name an NFL MVP quarterback.",
      "Name a quarterback who has won league MVP.",
      "Name an MVP-winning NFL quarterback.",
      "Name a quarterback whose season ended with the NFL MVP award.",
      "Name an NFL quarterback fans remember as a league MVP.",
    ],
    answers: ["Tom Brady", "Peyton Manning", "Patrick Mahomes", "Aaron Rodgers", "Lamar Jackson", "Brett Favre", "Steve Young", "Cam Newton"],
    alsoAcceptedAnswers: ["Matthew Stafford", "Josh Allen", "Joe Montana", "Dan Marino", "Johnny Unitas", "Kurt Warner", "Matt Ryan", "Rich Gannon", "Joe Theismann", "Ken Anderson", "Boomer Esiason", "Brian Sipe", "Roman Gabriel", "John Brodie"],
  },
  {
    category: "players",
    entityKind: "person",
    collisionGroup: "running-backs",
    prompts: [
      "Name an NFL running back who rushed for 2,000 yards in a season.",
      "Name a member of the NFL's 2,000-yard rushing club.",
      "Name a running back remembered for a 2,000-yard season.",
      "Name an NFL back whose season crossed 2,000 rushing yards.",
      "Name a 2,000-yard rusher fans still talk about.",
    ],
    answers: ["Eric Dickerson", "Adrian Peterson", "Jamal Lewis", "Barry Sanders", "Terrell Davis", "Chris Johnson", "Derrick Henry", "OJ Simpson"],
    alsoAcceptedAnswers: ["Saquon Barkley"],
  },
  {
    category: "players",
    entityKind: "person",
    collisionGroup: "receivers",
    prompts: [
      "Name an NFL receiver known for huge touchdown production.",
      "Name a receiver you associate with finding the end zone.",
      "Name an NFL wideout whose career includes a lot of touchdown catches.",
      "Name a receiver fans remember as a major red-zone threat.",
      "Name a wide receiver whose scoring ability became part of his reputation.",
    ],
    answers: ["Jerry Rice", "Randy Moss", "Terrell Owens", "Marvin Harrison", "Cris Carter", "Larry Fitzgerald", "Davante Adams", "Calvin Johnson"],
    alsoAcceptedAnswers: ["Steve Largent", "Mike Evans", "Antonio Brown", "Julio Jones", "Isaac Bruce", "Tim Brown", "Andre Reed", "Don Hutson"],
  },
  {
    category: "players",
    entityKind: "person",
    collisionGroup: "defenders",
    prompts: [
      "Name an NFL player famous for sacks.",
      "Name a pass rusher whose name belongs in a sack conversation.",
      "Name a defender quarterbacks hated seeing in the backfield.",
      "Name an NFL edge or defensive lineman known for getting to the quarterback.",
      "Name a pass rusher fans associate with dominant pressure.",
    ],
    answers: ["Bruce Smith", "Reggie White", "Michael Strahan", "JJ Watt", "Von Miller", "Aaron Donald", "Derrick Thomas", "TJ Watt"],
    alsoAcceptedAnswers: ["Kevin Greene", "Jared Allen", "DeMarcus Ware", "Julius Peppers", "Terrell Suggs", "Chris Doleman", "John Randle", "Myles Garrett"],
  },
  {
    category: "players",
    entityKind: "person",
    collisionGroup: "defenders",
    prompts: [
      "Name an NFL defensive back known for interceptions.",
      "Name a ball-hawking NFL defensive back.",
      "Name a DB whose reputation includes taking the ball away.",
      "Name an NFL secondary star quarterbacks had to locate before throwing.",
      "Name a defensive back remembered for making quarterbacks pay.",
    ],
    answers: ["Ed Reed", "Deion Sanders", "Rod Woodson", "Paul Krause", "Charles Woodson", "Champ Bailey", "Richard Sherman", "Ty Law"],
    alsoAcceptedAnswers: ["Night Train Lane", "Ronnie Lott", "Ken Riley", "Aeneas Williams", "Ronde Barber", "Everson Walls", "Lem Barney", "Aqib Talib"],
  },
] as const);
