import type { SportsFeudAuthoredQuestion } from "./sportsFeudBankTypes";

const person = (name: string, aliases: readonly string[] = []) => ({ name, ...(aliases.length ? { aliases } : {}) });
const answer = (name: string, aliases: readonly string[] = []) => ({ name, ...(aliases.length ? { aliases } : {}) });

export const UFC_SPORTS_FEUD_SEP24_PROTOTYPE = {
  main: [
    {
      id: "ufc-sep24-main-grappling-pressure",
      category: "fighter-style",
      entityKind: "person",
      collisionGroup: "wrestling",
      prompt: "Name a UFC star you associate with relentless grappling pressure.",
      answers: [
        person("Khabib Nurmagomedov", ["Khabib"]),
        person("Islam Makhachev", ["Islam"]),
        person("Khamzat Chimaev", ["Khamzat"]),
        person("Merab Dvalishvili", ["Merab"]),
        person("Georges St-Pierre", ["GSP"]),
        person("Cain Velasquez", ["Cain"]),
        person("Kamaru Usman", ["Kamaru"]),
        person("Daniel Cormier", ["DC"]),
      ],
      alsoAcceptedAnswers: [
        person("Henry Cejudo"),
        person("Matt Hughes"),
        person("Chael Sonnen"),
        person("Randy Couture"),
        person("Colby Covington"),
        person("Frankie Edgar"),
        person("Aljamain Sterling"),
        person("Jon Fitch"),
        person("Chad Mendes"),
        person("Belal Muhammad"),
        person("Arman Tsarukyan"),
        person("Mateusz Gamrot"),
        person("Sean Brady"),
        person("Tito Ortiz"),
        person("Mark Coleman"),
      ],
    },
    {
      id: "ufc-sep24-main-womens-ufc",
      category: "fighter-legacy",
      entityKind: "person",
      collisionGroup: "women",
      prompt: "Name a fighter who helped make women's MMA a major part of the UFC.",
      answers: [
        person("Ronda Rousey", ["Ronda"]),
        person("Amanda Nunes", ["Amanda"]),
        person("Joanna Jedrzejczyk", ["Joanna"]),
        person("Valentina Shevchenko", ["Valentina"]),
        person("Miesha Tate", ["Miesha"]),
        person("Rose Namajunas", ["Rose"]),
        person("Holly Holm", ["Holly"]),
        person("Zhang Weili", ["Weili"]),
      ],
      alsoAcceptedAnswers: [
        person("Cris Cyborg", ["Cyborg"]),
        person("Cat Zingano", ["Cat"]),
        person("Liz Carmouche", ["Liz"]),
        person("Carla Esparza", ["Carla"]),
        person("Jessica Andrade"),
        person("Julianna Pena"),
        person("Alexa Grasso"),
        person("Paige VanZant"),
        person("Michelle Waterson"),
      ],
    },
  ],
  fastMoney: [
    {
      id: "ufc-sep24-fast-submission",
      category: "techniques",
      entityKind: "other",
      collisionGroup: "submissions",
      prompt: "Name a submission you might see finish a UFC fight.",
      answers: [
        answer("Rear-naked choke", ["RNC", "Rear naked choke", "Rear naked"]),
        answer("Guillotine", ["Guillotine choke"]),
        answer("Armbar", ["Arm bar"]),
        answer("Triangle choke", ["Triangle"]),
        answer("Arm-triangle choke", ["Arm triangle", "Arm-triangle"]),
        answer("Kimura", ["Kimura lock"]),
        answer("D'Arce choke", ["Darce choke", "D arce", "Darce"]),
        answer("Heel hook", ["Heelhook"]),
      ],
      alsoAcceptedAnswers: [
        answer("Anaconda choke", ["Anaconda"]),
        answer("Americana", ["Americana lock"]),
        answer("Kneebar", ["Knee bar"]),
        answer("Neck crank"),
        answer("Twister"),
        answer("Calf slicer"),
        answer("Von Flue choke", ["Von Flue"]),
        answer("Ezekiel choke", ["Ezekiel"]),
        answer("Bulldog choke", ["Bulldog"]),
        answer("Omoplata"),
        answer("Straight ankle lock", ["Ankle lock"]),
        answer("Toe hold"),
        answer("Peruvian necktie"),
      ],
    },
    {
      id: "ufc-sep24-fast-trash-talk",
      category: "personality",
      entityKind: "person",
      collisionGroup: "culture",
      prompt: "Name a UFC fighter famous for trash talk.",
      answers: [
        person("Conor McGregor", ["Conor"]),
        person("Chael Sonnen", ["Chael"]),
        person("Nate Diaz", ["Nate"]),
        person("Michael Bisping", ["Bisping"]),
        person("Colby Covington", ["Colby"]),
        person("Sean Strickland"),
        person("Jorge Masvidal", ["Jorge"]),
        person("Tito Ortiz", ["Tito"]),
      ],
      alsoAcceptedAnswers: [
        person("Kevin Holland"),
        person("Derrick Lewis"),
        person("Quinton Jackson", ["Rampage", "Rampage Jackson"]),
        person("Paddy Pimblett"),
        person("Sean O'Malley", ["O'Malley", "OMalley"]),
        person("Tony Ferguson"),
        person("Nick Diaz"),
        person("Dominick Cruz"),
        person("Israel Adesanya"),
        person("Paulo Costa"),
      ],
    },
    {
      id: "ufc-sep24-fast-weight-class",
      category: "divisions",
      entityKind: "other",
      collisionGroup: "divisions",
      prompt: "Name a UFC weight class.",
      answers: [
        answer("Lightweight", ["155", "155 pounds", "155 lb"]),
        answer("Welterweight", ["170", "170 pounds", "170 lb"]),
        answer("Middleweight", ["185", "185 pounds", "185 lb"]),
        answer("Featherweight", ["145", "145 pounds", "145 lb"]),
        answer("Bantamweight", ["135", "135 pounds", "135 lb"]),
        answer("Heavyweight", ["HW"]),
        answer("Light heavyweight", ["LHW", "205", "205 pounds", "205 lb"]),
        answer("Flyweight", ["125", "125 pounds", "125 lb"]),
      ],
      alsoAcceptedAnswers: [
        answer("Strawweight", ["115", "115 pounds", "115 lb"]),
        answer("Women's flyweight", ["Womens flyweight"]),
        answer("Women's bantamweight", ["Womens bantamweight"]),
      ],
    },
    {
      id: "ufc-sep24-fast-striking-showcase",
      category: "fighters",
      entityKind: "person",
      collisionGroup: "striking",
      prompt: "Name a UFC star you would pick for a striking showcase.",
      answers: [
        person("Anderson Silva", ["Anderson"]),
        person("Israel Adesanya", ["Israel"]),
        person("Alex Pereira", ["Pereira", "Poatan"]),
        person("Max Holloway", ["Max"]),
        person("Jose Aldo", ["Aldo"]),
        person("Conor McGregor", ["Conor"]),
        person("Stephen Thompson", ["Wonderboy"]),
        person("Joanna Jedrzejczyk", ["Joanna"]),
      ],
      alsoAcceptedAnswers: [
        person("Valentina Shevchenko"),
        person("Alexander Volkanovski", ["Volk"]),
        person("Dustin Poirier"),
        person("Justin Gaethje"),
        person("Petr Yan"),
        person("Ilia Topuria"),
        person("Leon Edwards"),
        person("Sean O'Malley", ["O'Malley", "OMalley"]),
        person("Cory Sandhagen"),
        person("Edson Barboza"),
        person("Rafael Fiziev"),
        person("Zhang Weili"),
        person("Lyoto Machida"),
        person("Mirko Cro Cop", ["Cro Cop"]),
        person("Chuck Liddell"),
        person("Robert Whittaker"),
      ],
    },
    {
      id: "ufc-sep24-fast-referee",
      category: "officials",
      entityKind: "person",
      collisionGroup: "officials",
      prompt: "Name an MMA referee you have seen inside the Octagon.",
      answers: [
        person("Herb Dean", ["Herb"]),
        person("John McCarthy", ["Big John", "Big John McCarthy"]),
        person("Marc Goddard", ["Goddard"]),
        person("Dan Miragliotta", ["Miragliotta"]),
        person("Jason Herzog", ["Herzog"]),
        person("Mario Yamasaki", ["Yamasaki"]),
        person("Keith Peterson", ["Peterson"]),
        person("Mike Beltran", ["Beltran"]),
      ],
      alsoAcceptedAnswers: [
        person("Kevin MacDonald"),
        person("Steve Mazzagatti"),
        person("Josh Rosenthal"),
        person("Yves Lavigne"),
        person("Chris Tognoni"),
        person("Mark Smith"),
        person("Kerry Hatley"),
        person("Leon Roberts"),
        person("Kim Winslow"),
        person("Steve Perceval"),
        person("Jerin Valel"),
      ],
    },
  ],
} as const satisfies {
  main: readonly SportsFeudAuthoredQuestion[];
  fastMoney: readonly SportsFeudAuthoredQuestion[];
};
