import { expandSportsFeudFamilies } from "./sportsFeudAuthoredHelpers";

export const UFC_SPORTS_FEUD_FAST_4 = expandSportsFeudFamilies("ufc-fast4", [
  {
    category: "rules",
    entityKind: "other",
    collisionGroup: "finishes",
    prompts: [
      "Name a broad way a UFC fight can end.",
      "Name a basic result type you can see on a UFC fight result.",
      "Name a common official outcome for an MMA fight.",
      "Name a broad finish or result type in the UFC.",
      "Name a simple UFC fight outcome.",
    ],
    answers: [
      { name: "Knockout", aliases: ["KO"] },
      { name: "TKO", aliases: ["Technical knockout", "Technical KO"] },
      { name: "Submission", aliases: ["Sub"] },
      { name: "Decision", aliases: ["Dec"] },
      { name: "Doctor stoppage", aliases: ["Doctor", "Medical stoppage"] },
      { name: "Disqualification", aliases: ["DQ", "Disqualified"] },
      { name: "No contest", aliases: ["NC", "No-contest"] },
      { name: "Corner stoppage", aliases: ["Corner", "Corner stop", "Corner throws in towel", "Towel"] },
    ],
    alsoAcceptedAnswers: [
      { name: "Draw", aliases: ["Split draw", "Majority draw"] },
    ],
  },
  {
    category: "techniques",
    entityKind: "other",
    collisionGroup: "submissions",
    prompts: [
      "Name a common MMA submission.",
      "Name a submission you might see finish a UFC fight.",
      "Name a grappling hold MMA fans recognize.",
      "Name a submission fighters drill constantly.",
      "Name a tap-out technique used in the UFC.",
    ],
    answers: [
      { name: "Rear-naked choke", aliases: ["RNC", "Rear naked", "Rear naked choke"] },
      { name: "Guillotine", aliases: ["Guillotine choke"] },
      { name: "Armbar", aliases: ["Arm bar"] },
      { name: "Triangle choke", aliases: ["Triangle"] },
      { name: "Kimura", aliases: ["Kimura lock"] },
      { name: "Americana", aliases: ["Americana lock"] },
      { name: "Arm-triangle choke", aliases: ["Arm triangle", "Arm-triangle"] },
      { name: "Heel hook", aliases: ["Heelhook"] },
    ],
    alsoAcceptedAnswers: ["D'Arce choke", "Anaconda choke", "Kneebar", "Neck crank", "Twister", "Calf slicer"],
  },
  {
    category: "techniques",
    entityKind: "other",
    collisionGroup: "strikes",
    prompts: [
      "Name a strike you can use in MMA.",
      "Name a striking technique you might see in the UFC.",
      "Name a legal attack fighters throw on the feet.",
      "Name a basic strike MMA athletes train.",
      "Name a strike that can hurt an opponent in the Octagon.",
    ],
    answers: ["Jab", "Cross", "Hook", "Uppercut", "Elbow", "Knee", "Body kick", "Head kick"],
    alsoAcceptedAnswers: ["Overhand", "Low kick", "Front kick", "Spinning backfist", "Hammerfist", "Spinning elbow"],
  },
  {
    category: "techniques",
    entityKind: "other",
    collisionGroup: "kicks",
    prompts: [
      "Name a type of kick used in MMA.",
      "Name a kicking technique you might see in the UFC.",
      "Name a kick fighters use to attack at range.",
      "Name a kick commentators identify during UFC fights.",
      "Name a striking weapon that comes from the legs.",
    ],
    answers: ["Low kick", "Head kick", "Body kick", "Front kick", "Side kick", "Spinning back kick", "Calf kick", "Oblique kick"],
    alsoAcceptedAnswers: ["Roundhouse kick", "Teep", "Wheel kick", "Question-mark kick", "Axe kick"],
  },
  {
    category: "grappling",
    entityKind: "other",
    collisionGroup: "grappling",
    prompts: [
      "Name a wrestling or grappling position, action, or control term used in MMA.",
      "Name a wrestling or grappling action a fighter might use after closing distance.",
      "Name a wrestling or grappling position, action, or control term commentators mention in UFC fights.",
      "Name a position, action, or control term from the wrestling or grappling side of MMA.",
      "Name a wrestling or grappling term associated with controlling an opponent.",
    ],
    answers: [
      { name: "Takedown", aliases: ["Take down"] },
      { name: "Double-leg", aliases: ["Double leg"] },
      { name: "Single-leg", aliases: ["Single leg"] },
      { name: "Clinch", aliases: ["Clinch work"] },
      { name: "Back control", aliases: ["Back", "Take the back"] },
      { name: "Mount", aliases: ["Full mount"] },
      { name: "Half guard", aliases: ["Half-guard"] },
      { name: "Ground-and-pound", aliases: ["Ground and pound", "GNP"] },
    ],
    alsoAcceptedAnswers: ["Guard", "Side control", "Sprawl", "Sweep", "Body lock", "Underhook"],
  },
  {
    category: "rules",
    entityKind: "other",
    collisionGroup: "fouls",
    prompts: [
      "Name a foul in MMA.",
      "Name something illegal inside the UFC Octagon.",
      "Name an action that can draw a warning or point deduction.",
      "Name a foul referees watch for in a UFC fight.",
      "Name an illegal technique under the unified MMA rules.",
    ],
    answers: [
      { name: "Eye poke", aliases: ["Eye poking", "Poke the eye"] },
      { name: "Groin strike", aliases: ["Low blow", "Groin shot"] },
      { name: "Fence grab", aliases: ["Grab the fence", "Cage grab"] },
      { name: "Headbutt", aliases: ["Head butt"] },
      { name: "Biting", aliases: ["Bite"] },
      { name: "Hair pulling", aliases: ["Pull hair", "Hair pull"] },
      { name: "Back-of-head strike", aliases: ["Back of head", "Hit back of head", "Rabbit punch"] },
      { name: "Knee to a grounded opponent", aliases: ["Illegal knee", "Grounded knee", "Knee grounded opponent"] },
    ],
    alsoAcceptedAnswers: [
      { name: "Grabbing shorts or gloves", aliases: ["Grab shorts", "Grab gloves", "Shorts grab", "Glove grab"] },
      { name: "Throat attack", aliases: ["Throat strike", "Strike to throat"] },
      { name: "Small-joint manipulation", aliases: ["Small joint manipulation", "Finger bending", "Toe bending"] },
      { name: "Fish-hooking", aliases: ["Fish hook", "Fish hooking"] },
      { name: "Spiking on the head or neck", aliases: ["Spiking", "Spike on head", "Spike on neck"] },
      { name: "Attacking the spine", aliases: ["Spine strike", "Strike to spine"] },
    ],
  },
  {
    category: "judging",
    entityKind: "other",
    collisionGroup: "judging",
    prompts: [
      "Name something judges or fans look at when deciding who won a round.",
      "Name a factor that can influence how an MMA round is scored.",
      "Name something that helps a fighter make a round look convincing.",
      "Name a performance area people debate on UFC scorecards.",
      "Name something that can matter when comparing two close MMA rounds.",
    ],
    answers: [
      { name: "Effective striking", aliases: ["Striking", "Significant strikes", "Strikes"] },
      { name: "Effective grappling", aliases: ["Grappling"] },
      { name: "Damage", aliases: ["Visible damage"] },
      { name: "Takedowns", aliases: ["Takedown"] },
      { name: "Submission attempts", aliases: ["Submissions", "Submission attempt", "Sub attempts"] },
      { name: "Control", aliases: ["Control time", "Octagon control"] },
      { name: "Aggression", aliases: ["Aggressive", "Effective aggression"] },
      { name: "Cage pressure", aliases: ["Pressure", "Forward pressure"] },
    ],
    alsoAcceptedAnswers: ["Knockdowns", "Positional advancement", "Near submissions", "Clean strikes", "Ground strikes"],
  },
  {
    category: "stats",
    entityKind: "other",
    collisionGroup: "stats",
    prompts: [
      "Name a UFC fight statistic.",
      "Name a number shown during or after an MMA fight.",
      "Name a stat fans use to describe what happened in a bout.",
      "Name a fight metric you might see on a UFC broadcast.",
      "Name a statistic analysts use when breaking down a UFC fight.",
    ],
    answers: ["Significant strikes", "Total strikes", "Takedowns", "Takedown accuracy", "Control time", "Knockdowns", "Submission attempts", "Head strikes"],
    alsoAcceptedAnswers: ["Body strikes", "Leg strikes", "Distance strikes", "Clinch strikes", "Ground strikes", "Striking accuracy"],
  },
  {
    category: "weight-cutting",
    entityKind: "other",
    collisionGroup: "weight-cutting",
    prompts: [
      "Name something that can happen during a difficult UFC weight cut.",
      "Name a problem a fighter can have during a hard weight cut.",
      "Name a symptom or outcome of a rough UFC weight cut.",
      "Name something a fighter might deal with while cutting a lot of weight.",
      "Name something fans worry about when a UFC weight cut goes badly.",
    ],
    answers: [
      { name: "Dehydration", aliases: ["Dehydrated"] },
      { name: "Missed weight", aliases: ["Miss weight", "Misses weight", "Overweight"] },
      { name: "Dizziness", aliases: ["Dizzy", "Lightheaded", "Lightheadedness"] },
      { name: "Cramping", aliases: ["Cramps", "Cramp"] },
      { name: "Fainting", aliases: ["Faint", "Pass out", "Passing out", "Passed out"] },
      { name: "Vomiting", aliases: ["Vomit", "Throw up", "Throwing up"] },
      { name: "Exhaustion", aliases: ["Exhausted", "Fatigue"] },
      { name: "Rehydration", aliases: ["Rehydrate", "Rehydrating"] },
    ],
    alsoAcceptedAnswers: ["Headache", "Weakness", "Nausea", "Low energy", "Poor sleep"],
  },
  {
    category: "corner",
    entityKind: "other",
    collisionGroup: "corner",
    prompts: [
      "Name something a fighter's corner does between rounds.",
      "Name a job performed by a UFC corner team.",
      "Name something coaches might do during the one-minute break.",
      "Name a responsibility of the people in a fighter's corner.",
      "Name something that can happen on the stool between rounds.",
    ],
    answers: [
      { name: "Give instructions", aliases: ["Instructions", "Coaching", "Coach"] },
      { name: "Apply ice", aliases: ["Ice", "Ice the fighter"] },
      { name: "Reduce swelling", aliases: ["Swelling", "Reduce swelling"] },
      { name: "Stop bleeding", aliases: ["Bleeding", "Cut", "Cuts", "Stop the cut"] },
      { name: "Give water", aliases: ["Water", "Hydrate", "Hydration"] },
      { name: "Control breathing", aliases: ["Breathing", "Breathe"] },
      { name: "Encourage the fighter", aliases: ["Encourage", "Motivate", "Motivation"] },
      { name: "Adjust the game plan", aliases: ["Game plan", "Gameplan", "Adjust strategy"] },
    ],
    alsoAcceptedAnswers: ["Apply petroleum jelly", "Check a cut", "Clean the fighter", "Calm the fighter down"],
  },
] as const);
