import { expandSportsFeudFamilies } from "./sportsFeudAuthoredHelpers";

export const UFC_SPORTS_FEUD_MAIN = expandSportsFeudFamilies("ufc-main", [
  {
    category: "fighter-legacy",
    entityKind: "person",
    collisionGroup: "fighters",
    prompts: [
      "Name a fighter who belongs in almost any UFC all-time-great conversation.",
      "Name a UFC fighter whose career defines an era.",
      "Name a fighter casual fans might still recognize as a UFC legend.",
      "Name a UFC champion whose legacy goes far beyond one title win.",
      "Name a fighter you would expect in a UFC Mount Rushmore debate.",
    ],
    answers: ["Jon Jones", "Georges St-Pierre", "Anderson Silva", "Demetrious Johnson", "Jose Aldo", "Khabib Nurmagomedov", "Amanda Nunes", "Conor McGregor"],
    alsoAcceptedAnswers: ["Ronda Rousey", "Stipe Miocic", "Daniel Cormier", "Randy Couture", "Matt Hughes", "Alexander Volkanovski", "Israel Adesanya"],
  },
  {
    category: "fighter-style",
    entityKind: "person",
    collisionGroup: "knockouts",
    prompts: [
      "Name a UFC fighter famous for knockout power.",
      "Name a fighter whose hands make every exchange feel dangerous.",
      "Name a UFC fighter fans associate with one-shot power.",
      "Name a fighter you would never want to stand and trade with.",
      "Name a UFC knockout artist almost every MMA fan recognizes.",
    ],
    answers: ["Francis Ngannou", "Alex Pereira", "Derrick Lewis", "Chuck Liddell", "Wanderlei Silva", "Dan Henderson", "Justin Gaethje", "Jiri Prochazka"],
    alsoAcceptedAnswers: ["Anthony Johnson", "Mark Hunt", "Mirko Cro Cop", "Quinton Jackson", "Sergei Pavlovich", "Tai Tuivasa"],
  },
  {
    category: "fighter-style",
    entityKind: "person",
    collisionGroup: "submissions",
    prompts: [
      "Name a UFC fighter famous for submissions.",
      "Name a fighter whose ground game can end a fight suddenly.",
      "Name a UFC fighter you associate with dangerous submission offense.",
      "Name a fighter you would hate to grapple with on the mat.",
      "Name a submission specialist MMA fans recognize quickly.",
    ],
    answers: ["Charles Oliveira", "Demian Maia", "Frank Mir", "BJ Penn", "Nate Diaz", "Mackenzie Dern", "Rodolfo Vieira", "Tony Ferguson"],
    alsoAcceptedAnswers: ["Khabib Nurmagomedov", "Jim Miller", "Islam Makhachev", "Brian Ortega", "Royce Gracie", "Fabricio Werdum"],
  },
  {
    category: "fighter-style",
    entityKind: "person",
    collisionGroup: "wrestling",
    prompts: [
      "Name a UFC fighter famous for wrestling.",
      "Name a fighter whose takedowns became a major part of his identity.",
      "Name a UFC star you associate with relentless grappling pressure.",
      "Name a fighter opponents dreaded having on top of them.",
      "Name a wrestler who turned elite grappling into UFC success.",
    ],
    answers: ["Khabib Nurmagomedov", "Georges St-Pierre", "Daniel Cormier", "Kamaru Usman", "Islam Makhachev", "Henry Cejudo", "Merab Dvalishvili", "Chael Sonnen"],
    alsoAcceptedAnswers: ["Matt Hughes", "Randy Couture", "Frankie Edgar", "Josh Koscheck", "Jon Fitch", "Chad Mendes"],
  },
  {
    category: "fighter-style",
    entityKind: "person",
    collisionGroup: "striking",
    prompts: [
      "Name a UFC fighter known for elite striking.",
      "Name a fighter whose stand-up skill became part of his reputation.",
      "Name a UFC star you would pick for a technical striking showcase.",
      "Name a fighter opponents had to respect at kickboxing range.",
      "Name a striker whose UFC style looked especially polished.",
    ],
    answers: ["Anderson Silva", "Israel Adesanya", "Alex Pereira", "Max Holloway", "Jose Aldo", "Conor McGregor", "Stephen Thompson", "Joanna Jedrzejczyk"],
    alsoAcceptedAnswers: ["Dustin Poirier", "Alexander Volkanovski", "Justin Gaethje", "Valentina Shevchenko", "Petr Yan", "Ilia Topuria"],
  },
  {
    category: "fighter-personality",
    entityKind: "person",
    collisionGroup: "culture",
    prompts: [
      "Name a UFC fighter famous for trash talk or personality.",
      "Name a fighter who could sell a fight before entering the cage.",
      "Name a UFC personality fans loved or hated hearing on the microphone.",
      "Name a fighter whose words became part of the promotion.",
      "Name a UFC star who knew how to create attention outside the cage.",
    ],
    answers: ["Conor McGregor", "Chael Sonnen", "Nate Diaz", "Michael Bisping", "Colby Covington", "Sean Strickland", "Kevin Holland", "Derrick Lewis"],
    alsoAcceptedAnswers: ["Jorge Masvidal", "Tito Ortiz", "Quinton Jackson", "Paddy Pimblett", "Sean O'Malley", "Tony Ferguson"],
  },
  {
    category: "fighter-legacy",
    entityKind: "person",
    collisionGroup: "champions",
    prompts: [
      "Name a UFC champion remembered for a dominant title reign.",
      "Name a fighter who made a UFC division feel like it belonged to them.",
      "Name a champion whose title run created an aura of dominance.",
      "Name a UFC fighter associated with repeated championship defenses.",
      "Name a champion who ruled a division for a meaningful stretch.",
    ],
    answers: ["Anderson Silva", "Georges St-Pierre", "Demetrious Johnson", "Jon Jones", "Jose Aldo", "Amanda Nunes", "Valentina Shevchenko", "Israel Adesanya"],
    alsoAcceptedAnswers: ["Khabib Nurmagomedov", "Alexander Volkanovski", "Kamaru Usman", "Matt Hughes", "Ronda Rousey"],
  },
  {
    category: "division-identity",
    entityKind: "person",
    collisionGroup: "lightweights",
    prompts: [
      "Name a UFC lightweight star from the modern era.",
      "Name a fighter you strongly associate with the UFC lightweight division.",
      "Name a lightweight whose UFC career produced major fights.",
      "Name a 155-pound fighter almost every MMA fan recognizes.",
      "Name a lightweight you would expect in a division history conversation.",
    ],
    answers: ["Khabib Nurmagomedov", "Charles Oliveira", "Dustin Poirier", "Justin Gaethje", "BJ Penn", "Islam Makhachev", "Tony Ferguson", "Eddie Alvarez"],
    alsoAcceptedAnswers: ["Conor McGregor", "Frankie Edgar", "Benson Henderson", "Rafael dos Anjos", "Donald Cerrone", "Nate Diaz"],
  },
  {
    category: "division-identity",
    entityKind: "person",
    collisionGroup: "welterweights",
    prompts: [
      "Name a UFC welterweight star from the modern era.",
      "Name a fighter you strongly associate with the UFC welterweight division.",
      "Name a welterweight whose UFC career produced major fights.",
      "Name a 170-pound fighter almost every MMA fan recognizes.",
      "Name a welterweight you would expect in a division history conversation.",
    ],
    answers: ["Georges St-Pierre", "Kamaru Usman", "Matt Hughes", "Robbie Lawler", "Tyron Woodley", "Leon Edwards", "Stephen Thompson", "Carlos Condit"],
    alsoAcceptedAnswers: ["Jorge Masvidal", "Nick Diaz", "Colby Covington", "Johny Hendricks", "Belal Muhammad"],
  },
  {
    category: "division-identity",
    entityKind: "person",
    collisionGroup: "heavyweights",
    prompts: [
      "Name a famous UFC heavyweight.",
      "Name a fighter you strongly associate with the UFC heavyweight division.",
      "Name a heavyweight whose UFC career produced major moments.",
      "Name a big man almost every MMA fan recognizes.",
      "Name a heavyweight you would expect in a division history conversation.",
    ],
    answers: ["Stipe Miocic", "Francis Ngannou", "Cain Velasquez", "Daniel Cormier", "Randy Couture", "Junior dos Santos", "Derrick Lewis", "Brock Lesnar"],
    alsoAcceptedAnswers: ["Fabricio Werdum", "Andrei Arlovski", "Frank Mir", "Mark Hunt", "Alistair Overeem", "Tom Aspinall", "Ciryl Gane"],
  },
  {
    category: "fighter-legacy",
    entityKind: "person",
    collisionGroup: "women",
    prompts: [
      "Name a legendary women's UFC fighter.",
      "Name a woman whose career helped shape UFC history.",
      "Name a female UFC star almost every MMA fan recognizes.",
      "Name a women's champion you would include in an all-time UFC conversation.",
      "Name a fighter who helped make women's MMA a major part of the UFC.",
    ],
    answers: ["Amanda Nunes", "Ronda Rousey", "Valentina Shevchenko", "Joanna Jedrzejczyk", "Rose Namajunas", "Cris Cyborg", "Zhang Weili", "Holly Holm"],
    alsoAcceptedAnswers: ["Miesha Tate", "Julianna Pena", "Alexa Grasso", "Jessica Andrade"],
  },
  {
    category: "gyms",
    entityKind: "other",
    collisionGroup: "gyms",
    prompts: [
      "Name a gym or team strongly associated with UFC fighters.",
      "Name a famous MMA camp that has produced UFC talent.",
      "Name a training team serious UFC fans recognize.",
      "Name a gym you would expect to hear mentioned during a UFC broadcast.",
      "Name an MMA team associated with multiple notable UFC fighters.",
    ],
    answers: ["American Top Team", "AKA", "Jackson Wink", "City Kickboxing", "Xtreme Couture", "Nova Uniao", "Team Alpha Male", "Roufusport"],
    alsoAcceptedAnswers: ["Tristar Gym", "Kings MMA", "Serra-Longo", "MMA Lab", "Kill Cliff FC"],
  },
  {
    category: "rivalries",
    entityKind: "other",
    collisionGroup: "rivalries",
    prompts: [
      "Name a famous UFC rivalry.",
      "Name a pair of fighters whose bad blood made the fight bigger.",
      "Name a UFC feud fans still remember.",
      "Name a rivalry that produced major UFC promotion and drama.",
      "Name two fighters whose rivalry became part of UFC history.",
    ],
    answers: ["McGregor-Diaz", "Jones-Cormier", "Liddell-Ortiz", "Silva-Sonnen", "McGregor-Nurmagomedov", "Hughes-St-Pierre", "Couture-Liddell", "Adesanya-Pereira"],
    alsoAcceptedAnswers: ["Ortiz-Shamrock", "McGregor-Aldo", "Nunes-Shevchenko", "Usman-Covington", "Poirier-McGregor"],
  },
  {
    category: "fights",
    entityKind: "other",
    collisionGroup: "fights",
    prompts: [
      "Name an iconic UFC fight.",
      "Name a UFC fight fans still recommend to new viewers.",
      "Name a bout that belongs in a UFC history montage.",
      "Name a fight remembered for incredible action or stakes.",
      "Name a UFC matchup people still talk about years later.",
    ],
    answers: ["Griffin-Bonnar", "Jones-Gustafsson 1", "Lawler-MacDonald 2", "Henderson-Shogun 1", "Adesanya-Gastelum", "Zhang-Jedrzejczyk 1", "McGregor-Diaz 2", "Poirier-Hooker"],
    alsoAcceptedAnswers: ["Silva-Sonnen 1", "Edgar-Maynard 2", "Hunt-Silva", "Usman-Covington 1", "Gaethje-Chandler", "Holloway-Kattar"],
  },
  {
    category: "venues",
    entityKind: "other",
    collisionGroup: "venues",
    prompts: [
      "Name a UFC arena, host city, or named event site strongly associated with major cards.",
      "Name a UFC arena, host city, or named event site where you can picture a huge card.",
      "Name an arena, host city, or named event site tied to memorable UFC nights.",
      "Name a UFC arena, host city, or named event site fans associate with big fights.",
      "Name an arena, host city, or named event site familiar to longtime UFC fans.",
    ],
    answers: ["T-Mobile Arena", "Madison Square Garden", "MGM Grand Garden Arena", "UFC APEX", "The O2", "Fight Island", "Honda Center", "Etihad Arena"],
    alsoAcceptedAnswers: ["Las Vegas", "Abu Dhabi", "London", "Anaheim"],
  },
  {
    category: "achievements",
    entityKind: "other",
    collisionGroup: "achievements",
    prompts: [
      "Name a UFC accomplishment that can define a fighter's legacy.",
      "Name something a UFC fighter would love on a career résumé.",
      "Name an achievement that can turn a great UFC career into a legendary one.",
      "Name a milestone MMA fans use in legacy debates.",
      "Name something a fighter can accomplish that fans remember for years.",
    ],
    answers: ["Win a UFC title", "Defend the title repeatedly", "Become a two-division champion", "Beat another all-time great", "Long winning streak", "Headline a huge PPV", "Record a famous knockout", "Enter the UFC Hall of Fame"],
    alsoAcceptedAnswers: ["Become pound-for-pound No. 1", "Win The Ultimate Fighter", "Set a UFC record", "Win Fight of the Night awards", "Retire as champion"],
  },
  {
    category: "divisions",
    entityKind: "other",
    collisionGroup: "divisions",
    prompts: [
      "Name a UFC weight class.",
      "Name a division on a UFC card.",
      "Name a UFC weight class fans discuss constantly.",
      "Name a division that has produced famous champions.",
      "Name a weight class a UFC fighter can compete in.",
    ],
    answers: ["Lightweight", "Welterweight", "Middleweight", "Featherweight", "Bantamweight", "Heavyweight", "Light heavyweight", "Flyweight"],
    alsoAcceptedAnswers: ["Strawweight", "Women's flyweight", "Women's bantamweight"],
  },
  {
    category: "traits",
    entityKind: "other",
    collisionGroup: "traits",
    prompts: [
      "Name a trait every elite UFC fighter needs.",
      "Name a quality that can separate a contender from the rest of the division.",
      "Name something coaches want to see in a championship-level fighter.",
      "Name a fighter trait fans notice quickly.",
      "Name a quality that matters when a UFC fight gets difficult.",
    ],
    answers: ["Cardio", "Fight IQ", "Durability", "Power", "Speed", "Wrestling defense", "Composure", "Toughness"],
    alsoAcceptedAnswers: ["Striking", "Wrestling", "Submission defense", "Adaptability", "Discipline", "Recovery"],
  },
  {
    category: "techniques",
    entityKind: "other",
    collisionGroup: "techniques",
    prompts: [
      "Name a technique you might see finish a UFC fight.",
      "Name a move that can end an MMA fight suddenly.",
      "Name a technique fighters drill because it can produce a finish.",
      "Name an MMA attack fans recognize immediately.",
      "Name a finishing technique that can change a UFC fight in seconds.",
    ],
    answers: ["Rear-naked choke", "Guillotine", "Armbar", "Head kick", "Left hook", "Ground-and-pound", "Triangle choke", "Body shot"],
    alsoAcceptedAnswers: ["Arm-triangle choke", "Kimura", "Knee", "Elbow", "Uppercut", "Heel hook"],
  },
  {
    category: "culture",
    entityKind: "person",
    collisionGroup: "culture",
    prompts: [
      "Name a UFC fighter known for a memorable walkout or entrance.",
      "Name a fighter whose walk to the cage feels like part of the show.",
      "Name a UFC star with an entrance fans look forward to.",
      "Name a fighter whose walkout helps create a big-fight atmosphere.",
      "Name a UFC fighter whose entrance has become part of the fan experience.",
    ],
    answers: ["Conor McGregor", "Israel Adesanya", "Alex Pereira", "Darren Till", "Tom Aspinall", "Paddy Pimblett", "Max Holloway", "Jiri Prochazka"],
    alsoAcceptedAnswers: ["Anderson Silva", "Ronda Rousey", "The Korean Zombie", "Tai Tuivasa", "Mike Perry", "Diego Sanchez"],
  },
] as const);
