import type {
  SportsFeudAuthoredAnswer,
  SportsFeudAuthoredQuestion,
} from "./sportsFeudBankTypes";

function answer(name: string, aliases: readonly string[] = []): SportsFeudAuthoredAnswer {
  return aliases.length ? { name, aliases } : { name };
}

export const UFC_SEP24_SPORTS_FEUD_PACK_VERSION = "ufc-sep24-prototype-v1" as const;

export const UFC_SEP24_SPORTS_FEUD_MAIN: readonly SportsFeudAuthoredQuestion[] = [
  {
    id: "ufc-sep24-main-01",
    category: "fighter-style",
    entityKind: "person",
    collisionGroup: "grappling-pressure",
    prompt: "Name a UFC star you associate with relentless grappling pressure.",
    answers: [
      answer("Khabib Nurmagomedov", ["The Eagle"]),
      answer("Islam Makhachev"),
      answer("Khamzat Chimaev", ["Borz"]),
      answer("Merab Dvalishvili", ["The Machine"]),
      answer("Georges St-Pierre", ["GSP", "Georges St Pierre"]),
      answer("Cain Velasquez"),
      answer("Kamaru Usman", ["The Nigerian Nightmare", "Nigerian Nightmare"]),
      answer("Daniel Cormier", ["DC"]),
    ],
    alsoAcceptedAnswers: [
      answer("Henry Cejudo", ["Triple C"]),
      answer("Matt Hughes"),
      answer("Chael Sonnen"),
      answer("Randy Couture"),
      answer("Colby Covington"),
      answer("Frankie Edgar"),
      answer("Aljamain Sterling", ["Aljo"]),
      answer("Jon Fitch"),
      answer("Chad Mendes"),
      answer("Belal Muhammad"),
      answer("Arman Tsarukyan"),
      answer("Mateusz Gamrot"),
      answer("Sean Brady"),
      answer("Tito Ortiz"),
      answer("Mark Coleman"),
    ],
  },
  {
    id: "ufc-sep24-main-02",
    category: "fighter-legacy",
    entityKind: "person",
    collisionGroup: "women",
    prompt: "Name a fighter who helped make women's MMA a major part of the UFC.",
    answers: [
      answer("Ronda Rousey", ["Rowdy Ronda Rousey"]),
      answer("Amanda Nunes", ["The Lioness", "Lioness"]),
      answer("Joanna Jedrzejczyk", ["Joanna Jędrzejczyk"]),
      answer("Valentina Shevchenko", ["Bullet", "The Bullet"]),
      answer("Miesha Tate", ["Cupcake"]),
      answer("Rose Namajunas", ["Thug Rose"]),
      answer("Holly Holm", ["The Preacher's Daughter"]),
      answer("Zhang Weili", ["Weili Zhang"]),
    ],
    alsoAcceptedAnswers: [
      answer("Cris Cyborg", ["Cristiane Justino", "Cyborg"]),
      answer("Cat Zingano"),
      answer("Liz Carmouche"),
      answer("Carla Esparza"),
      answer("Jessica Andrade"),
      answer("Julianna Pena", ["Julianna Peña"]),
      answer("Alexa Grasso"),
      answer("Paige VanZant", ["PVZ"]),
      answer("Michelle Waterson", ["Michelle Waterson-Gomez"]),
    ],
  },
] as const;

export const UFC_SEP24_SPORTS_FEUD_FAST: readonly SportsFeudAuthoredQuestion[] = [
  {
    id: "ufc-sep24-fast-01",
    category: "techniques",
    entityKind: "other",
    collisionGroup: "submissions",
    prompt: "Name a submission you might see finish a UFC fight.",
    answers: [
      answer("Rear-naked choke", ["RNC", "Rear naked choke", "Rear naked"]),
      answer("Guillotine", ["Guillotine choke"]),
      answer("Armbar", ["Arm bar"]),
      answer("Triangle choke", ["Triangle"]),
      answer("Arm-triangle choke", ["Arm triangle", "Arm triangle choke", "Arm-triangle"]),
      answer("Kimura", ["Kimura lock"]),
      answer("D'Arce choke", ["Darce choke", "D'Arce", "Darce", "Brabo choke"]),
      answer("Heel hook", ["Heelhook"]),
    ],
    alsoAcceptedAnswers: [
      answer("Americana", ["Americana lock", "Keylock"]),
      answer("Anaconda choke", ["Anaconda"]),
      answer("Kneebar", ["Knee bar"]),
      answer("Neck crank"),
      answer("Twister"),
      answer("Calf slicer", ["Calf slice"]),
      answer("Von Flue choke", ["Von Flue"]),
      answer("Ezekiel choke", ["Ezekiel"]),
      answer("Bulldog choke", ["Bulldog"]),
      answer("Omoplata"),
      answer("Straight ankle lock", ["Ankle lock"]),
      answer("Toe hold", ["Toehold"]),
      answer("Peruvian necktie"),
      answer("North-south choke", ["North south choke"]),
    ],
  },
  {
    id: "ufc-sep24-fast-02",
    category: "personality",
    entityKind: "person",
    collisionGroup: "trash-talk",
    prompt: "Name a UFC fighter famous for trash talk.",
    answers: [
      answer("Conor McGregor", ["The Notorious", "Notorious"]),
      answer("Chael Sonnen", ["The American Gangster"]),
      answer("Nate Diaz"),
      answer("Michael Bisping", ["The Count"]),
      answer("Colby Covington", ["Chaos"]),
      answer("Sean Strickland"),
      answer("Tito Ortiz", ["The Huntington Beach Bad Boy"]),
      answer("Jorge Masvidal", ["Gamebred"]),
    ],
    alsoAcceptedAnswers: [
      answer("Nick Diaz"),
      answer("Kevin Holland", ["Trailblazer"]),
      answer("Henry Cejudo", ["Triple C"]),
      answer("Paddy Pimblett", ["Paddy the Baddy"]),
      answer("Quinton Jackson", ["Rampage", "Rampage Jackson"]),
      answer("Josh Koscheck"),
      answer("Dominick Cruz"),
      answer("Sean O'Malley", ["Suga Sean", "Sugar Sean"]),
      answer("Derrick Lewis", ["The Black Beast", "Black Beast"]),
      answer("Tony Ferguson", ["El Cucuy"]),
    ],
  },
  {
    id: "ufc-sep24-fast-03",
    category: "divisions",
    entityKind: "other",
    collisionGroup: "divisions",
    prompt: "Name a UFC weight class.",
    answers: [
      answer("Lightweight", ["LW", "155", "155 lb", "155 lbs"]),
      answer("Welterweight", ["WW", "170", "170 lb", "170 lbs"]),
      answer("Middleweight", ["MW", "185", "185 lb", "185 lbs"]),
      answer("Heavyweight", ["HW", "265", "265 lb", "265 lbs"]),
      answer("Featherweight", ["FW", "145", "145 lb", "145 lbs"]),
      answer("Bantamweight", ["BW", "135", "135 lb", "135 lbs"]),
      answer("Light heavyweight", ["LHW", "205", "205 lb", "205 lbs", "Light-heavyweight"]),
      answer("Flyweight", ["FLW", "125", "125 lb", "125 lbs"]),
    ],
    alsoAcceptedAnswers: [
      answer("Strawweight", ["SW", "115", "115 lb", "115 lbs"]),
      answer("Women's flyweight", ["Womens flyweight", "Women's 125"]),
      answer("Women's bantamweight", ["Womens bantamweight", "Women's 135"]),
    ],
  },
  {
    id: "ufc-sep24-fast-04",
    category: "fighters",
    entityKind: "person",
    collisionGroup: "striking",
    prompt: "Name a UFC star you would pick for a striking showcase.",
    answers: [
      answer("Anderson Silva", ["The Spider", "Spider"]),
      answer("Israel Adesanya", ["Izzy", "The Last Stylebender", "Last Stylebender"]),
      answer("Alex Pereira", ["Poatan"]),
      answer("Max Holloway", ["Blessed"]),
      answer("Jose Aldo", ["José Aldo"]),
      answer("Conor McGregor", ["The Notorious", "Notorious"]),
      answer("Stephen Thompson", ["Wonderboy"]),
      answer("Joanna Jedrzejczyk", ["Joanna Jędrzejczyk"]),
    ],
    alsoAcceptedAnswers: [
      answer("Valentina Shevchenko", ["Bullet", "The Bullet"]),
      answer("Alexander Volkanovski", ["Volk"]),
      answer("Dustin Poirier", ["The Diamond", "Diamond"]),
      answer("Justin Gaethje", ["The Highlight", "Highlight"]),
      answer("Petr Yan"),
      answer("Ilia Topuria", ["El Matador"]),
      answer("Leon Edwards", ["Rocky"]),
      answer("Sean O'Malley", ["Suga Sean", "Sugar Sean"]),
      answer("Cory Sandhagen"),
      answer("Edson Barboza"),
      answer("Rafael Fiziev", ["Ataman"]),
      answer("Zhang Weili", ["Weili Zhang"]),
      answer("Lyoto Machida", ["The Dragon", "Dragon"]),
      answer("Mirko Cro Cop", ["Cro Cop", "Mirko Filipovic"]),
      answer("Chuck Liddell", ["The Iceman", "Iceman"]),
      answer("TJ Dillashaw", ["T.J. Dillashaw"]),
      answer("Dominick Cruz"),
      answer("Cody Garbrandt", ["No Love"]),
      answer("Ciryl Gane", ["Bon Gamin"]),
      answer("Robert Whittaker", ["Bobby Knuckles", "The Reaper"]),
    ],
  },
  {
    id: "ufc-sep24-fast-05",
    category: "officials",
    entityKind: "person",
    collisionGroup: "officials",
    prompt: "Name an MMA referee you have seen inside the Octagon.",
    answers: [
      answer("Herb Dean"),
      answer("John McCarthy", ["Big John", "Big John McCarthy"]),
      answer("Marc Goddard"),
      answer("Dan Miragliotta"),
      answer("Jason Herzog"),
      answer("Mario Yamasaki"),
      answer("Keith Peterson", ["No Nonsense Keith Peterson", "No Nonsense"]),
      answer("Mike Beltran"),
    ],
    alsoAcceptedAnswers: [
      answer("Kevin MacDonald"),
      answer("Steve Mazzagatti"),
      answer("Josh Rosenthal"),
      answer("Yves Lavigne"),
      answer("Chris Tognoni"),
      answer("Mark Smith"),
      answer("Kerry Hatley"),
      answer("Leon Roberts"),
      answer("Kim Winslow"),
      answer("Steve Perceval"),
      answer("Jerin Valel"),
    ],
  },
] as const;
