export const WAVELENGTH_CATALOG_VERSION = "wavelength-catalog-v1" as const;
export const WAVELENGTH_CALIBRATION_VERSION = "wavelength-calibration-v1" as const;
export const WAVELENGTH_GENERATOR_VERSION = "wavelength-generator-v2" as const;
export const WAVELENGTH_REVEAL_CONTRACT_VERSION = "wavelength-reveal-privacy-v1" as const;

export const WAVELENGTH_HISTORICAL_VERSION_IDS = [
  WAVELENGTH_CATALOG_VERSION,
  WAVELENGTH_CALIBRATION_VERSION,
  WAVELENGTH_GENERATOR_VERSION,
  WAVELENGTH_REVEAL_CONTRACT_VERSION,
] as const;

export type WavelengthCategory =
  | "FIGHTER SKILL"
  | "UFC RESUME"
  | "CHAMPIONSHIP"
  | "UFC CULTURE"
  | "EVENTS & FIGHTS"
  | "VENUE & ATMOSPHERE"
  | "PERSONALITY & PROMOTION"
  | "BROADCAST & PRESENTATION"
  | "OFFICIATING & SYSTEMS"
  | "LEGACY & HISTORY"
  | "FIGHTER TRAIT"
  | "GOAT & PRIME";

export type WavelengthCatalogStatus = "approved" | "quarantined";

export interface WavelengthCatalogItem {
  id: string;
  category: WavelengthCategory;
  text: string;
  rating: number;
  status: WavelengthCatalogStatus;
}

export interface WavelengthCategoryAnchor {
  category: WavelengthCategory;
  ratingQuestion: string;
  bottomTier: string;
  average: string;
  elite: string;
  exceptional: string;
}

export const WAVELENGTH_RATING_BANDS = [
  { label: "bottom-tier", min: 1, max: 10, meaning: "disastrous, essentially unusable, or historically damaging for the stated question" },
  { label: "poor", min: 20, max: 30, meaning: "clearly below UFC standard or actively weak, with only narrow redeeming context" },
  { label: "below average", min: 40, max: 45, meaning: "recognizable value but less than a normal solid UFC baseline" },
  { label: "average", min: 46, max: 55, meaning: "ordinary credible UFC level for the exact category question" },
  { label: "strong", min: 60, max: 74, meaning: "clearly good, memorable, or useful without being division-defining" },
  { label: "elite", min: 75, max: 89, meaning: "excellent UFC standard with durable fan or competitive credibility" },
  { label: "exceptional", min: 90, max: 100, meaning: "historically elite to nearly unimprovable for the stated question" },
] as const;

export const WAVELENGTH_CALIBRATION_RUBRIC = {
  meaning: "The 1-100 number is a calibrated UFC-context rating for the exact clue wording, not a global moral judgment or a canonical GOAT ranking input.",
  adjacentRatingRule: "Move one to three points only for a clear but modest distinction inside the same anchor band; cross a band boundary only when a neutral reviewer would describe the item with the stronger band label.",
  disagreementRule: "When two calibration passes materially disagree, rewrite the clue to narrow the question, rerate against category anchors, or quarantine it; do not average conflicting interpretations blindly.",
  quarantineRule: "Quarantine clues whose wording depends on temporary facts, non-UFC evidence presented as UFC evidence, or subjective readings that cannot be stabilized by clearer copy.",
  versioningRule: "Catalog, calibration, generator, and reveal contract versions are stable identifiers for future persistence; changing ratings or privacy semantics requires a new version rather than mutating historical official results.",
  passes: [
    "Initial pass assigned ratings against the roadmap bands and category-specific question.",
    "Independent review pass challenged outliers, ambiguous category anchors, score-band jumps, and items likely to create strong reasonable disagreement; disputed items were rewritten, rerated, or quarantined.",
  ],
} as const;

export const WAVELENGTH_CATEGORY_ANCHORS: readonly WavelengthCategoryAnchor[] = [
  { category: "FIGHTER SKILL", ratingQuestion: "How effective is this skill in UFC competition?", bottomTier: "Actively exploitable", average: "Functional UFC skill", elite: "Division-leading skill", exceptional: "All-time technical weapon" },
  { category: "UFC RESUME", ratingQuestion: "How strong is the UFC-only résumé?", bottomTier: "Failed UFC experiment", average: "Credible roster résumé", elite: "Champion or perennial elite résumé", exceptional: "All-time UFC résumé" },
  { category: "CHAMPIONSHIP", ratingQuestion: "How credible or meaningful is this UFC championship claim?", bottomTier: "No meaningful claim", average: "Some title relevance", elite: "Durable champion-level claim", exceptional: "Historic title standard" },
  { category: "UFC CULTURE", ratingQuestion: "How valuable is this to UFC fan culture?", bottomTier: "Negative or embarrassing", average: "Recognizable but mixed", elite: "Beloved or durable culture", exceptional: "Defining UFC culture" },
  { category: "EVENTS & FIGHTS", ratingQuestion: "How strong is the event or fight for the stated quality?", bottomTier: "Not worth revisiting", average: "Solid UFC viewing", elite: "Classic or major event", exceptional: "Historically essential" },
  { category: "VENUE & ATMOSPHERE", ratingQuestion: "How strong is the UFC setting or live atmosphere?", bottomTier: "Dead atmosphere", average: "Normal event feel", elite: "Major-market energy", exceptional: "Iconic atmosphere" },
  { category: "PERSONALITY & PROMOTION", ratingQuestion: "How effective is this promotional/personality trait?", bottomTier: "Actively hurts interest", average: "Some fan interest", elite: "Major draw or broadcast asset", exceptional: "Era-defining promotion" },
  { category: "BROADCAST & PRESENTATION", ratingQuestion: "How well does this improve the UFC viewing product?", bottomTier: "Distracting or poor", average: "Serviceable presentation", elite: "Premium broadcast asset", exceptional: "Signature presentation element" },
  { category: "OFFICIATING & SYSTEMS", ratingQuestion: "How trustworthy or useful is this UFC system?", bottomTier: "Fails its job", average: "Mixed but usable", elite: "Consistently strong", exceptional: "Model standard" },
  { category: "LEGACY & HISTORY", ratingQuestion: "How important is this to UFC history?", bottomTier: "Negative footnote", average: "Recognizable chapter", elite: "Major historical legacy", exceptional: "Foundational history" },
  { category: "FIGHTER TRAIT", ratingQuestion: "How strong is this fighter trait in UFC context?", bottomTier: "Severe liability", average: "Normal UFC trait", elite: "High-end weapon", exceptional: "Nearly unmatched trait" },
  { category: "GOAT & PRIME", ratingQuestion: "How strong is this UFC GOAT or prime claim?", bottomTier: "Not credible", average: "Notable but limited", elite: "Real all-time case", exceptional: "Shortlist all-time claim" },
] as const;

export const wavelengthCatalog: readonly WavelengthCatalogItem[] = [
  { id: "wl-fighter-skill-001", category: "FIGHTER SKILL", text: "CM Punk's UFC striking defense", rating: 4, status: "approved" },
  { id: "wl-fighter-skill-002", category: "FIGHTER SKILL", text: "Ben Askren's UFC striking threat", rating: 18, status: "approved" },
  { id: "wl-fighter-skill-003", category: "FIGHTER SKILL", text: "Derrick Lewis's submission game", rating: 28, status: "approved" },
  { id: "wl-fighter-skill-004", category: "FIGHTER SKILL", text: "Nate Diaz's defensive wrestling", rating: 43, status: "approved" },
  { id: "wl-fighter-skill-005", category: "FIGHTER SKILL", text: "Justin Gaethje's offensive wrestling in UFC fights", rating: 62, status: "approved" },
  { id: "wl-fighter-skill-006", category: "FIGHTER SKILL", text: "Sean O'Malley's range striking", rating: 83, status: "approved" },
  { id: "wl-fighter-skill-007", category: "FIGHTER SKILL", text: "Islam Makhachev's top control", rating: 92, status: "approved" },
  { id: "wl-fighter-skill-008", category: "FIGHTER SKILL", text: "Georges St-Pierre's jab", rating: 94, status: "approved" },
  { id: "wl-fighter-skill-009", category: "FIGHTER SKILL", text: "Demetrious Johnson's transitions", rating: 96, status: "approved" },
  { id: "wl-fighter-skill-010", category: "FIGHTER SKILL", text: "Khabib Nurmagomedov's chain wrestling", rating: 98, status: "approved" },
  { id: "wl-fighter-skill-011", category: "FIGHTER SKILL", text: "Tony Ferguson's prime scrambling", rating: 86, status: "approved" },
  { id: "wl-fighter-skill-012", category: "FIGHTER SKILL", text: "Charles Oliveira's back attacks", rating: 91, status: "approved" },
  { id: "wl-fighter-skill-013", category: "FIGHTER SKILL", text: "Anderson Silva's counterstriking prime", rating: 97, status: "approved" },
  { id: "wl-fighter-skill-014", category: "FIGHTER SKILL", text: "Valentina Shevchenko's clinch trips", rating: 88, status: "approved" },
  { id: "wl-fighter-skill-015", category: "FIGHTER SKILL", text: "Amanda Nunes's power punching", rating: 93, status: "approved" },
  { id: "wl-fighter-skill-016", category: "FIGHTER SKILL", text: "Max Holloway's volume boxing", rating: 90, status: "approved" },
  { id: "wl-fighter-skill-017", category: "FIGHTER SKILL", text: "Alexander Volkanovski's feinting", rating: 87, status: "approved" },
  { id: "wl-fighter-skill-018", category: "FIGHTER SKILL", text: "Alex Pereira's left hook", rating: 95, status: "approved" },
  { id: "wl-fighter-skill-019", category: "FIGHTER SKILL", text: "Jon Jones's oblique kicks", rating: 89, status: "approved" },
  { id: "wl-fighter-skill-020", category: "FIGHTER SKILL", text: "Robert Whittaker's blitz entries", rating: 82, status: "approved" },
  { id: "wl-fighter-skill-021", category: "FIGHTER SKILL", text: "Leon Edwards's distance management", rating: 84, status: "approved" },
  { id: "wl-fighter-skill-022", category: "FIGHTER SKILL", text: "Jose Aldo's anti-wrestling prime", rating: 96, status: "approved" },
  { id: "wl-fighter-skill-023", category: "FIGHTER SKILL", text: "Ronda Rousey's armbar threat", rating: 94, status: "approved" },
  { id: "wl-fighter-skill-024", category: "FIGHTER SKILL", text: "Mackenzie Dern's pure jiu-jitsu threat", rating: 81, status: "approved" },
  { id: "wl-fighter-skill-025", category: "FIGHTER SKILL", text: "Francis Ngannou's one-shot power", rating: 97, status: "approved" },
  { id: "wl-ufc-resume-026", category: "UFC RESUME", text: "CM Punk's UFC-only résumé", rating: 2, status: "approved" },
  { id: "wl-ufc-resume-027", category: "UFC RESUME", text: "Greg Hardy's UFC-only résumé", rating: 14, status: "approved" },
  { id: "wl-ufc-resume-028", category: "UFC RESUME", text: "Sage Northcutt's UFC-only résumé", rating: 31, status: "approved" },
  { id: "wl-ufc-resume-029", category: "UFC RESUME", text: "Paige VanZant's UFC-only résumé", rating: 35, status: "approved" },
  { id: "wl-ufc-resume-030", category: "UFC RESUME", text: "Kevin Holland's UFC-only résumé", rating: 55, status: "approved" },
  { id: "wl-ufc-resume-031", category: "UFC RESUME", text: "Michael Chandler's UFC-only résumé", rating: 60, status: "approved" },
  { id: "wl-ufc-resume-032", category: "UFC RESUME", text: "Dustin Poirier's UFC-only résumé", rating: 82, status: "approved" },
  { id: "wl-ufc-resume-033", category: "UFC RESUME", text: "Charles Oliveira's UFC-only résumé", rating: 86, status: "approved" },
  { id: "wl-ufc-resume-034", category: "UFC RESUME", text: "Kamaru Usman's UFC-only résumé", rating: 90, status: "approved" },
  { id: "wl-ufc-resume-035", category: "UFC RESUME", text: "Georges St-Pierre's UFC-only résumé", rating: 98, status: "approved" },
  { id: "wl-ufc-resume-036", category: "UFC RESUME", text: "Amanda Nunes's UFC-only résumé", rating: 97, status: "approved" },
  { id: "wl-ufc-resume-037", category: "UFC RESUME", text: "Jon Jones's UFC-only résumé", rating: 99, status: "approved" },
  { id: "wl-ufc-resume-038", category: "UFC RESUME", text: "Anderson Silva's UFC-only résumé", rating: 96, status: "approved" },
  { id: "wl-ufc-resume-039", category: "UFC RESUME", text: "Jose Aldo's UFC-only résumé", rating: 92, status: "approved" },
  { id: "wl-ufc-resume-040", category: "UFC RESUME", text: "Max Holloway's UFC-only résumé", rating: 88, status: "approved" },
  { id: "wl-ufc-resume-041", category: "UFC RESUME", text: "Conor McGregor's UFC-only résumé", rating: 84, status: "approved" },
  { id: "wl-ufc-resume-042", category: "UFC RESUME", text: "Daniel Cormier's UFC-only résumé", rating: 87, status: "approved" },
  { id: "wl-ufc-resume-043", category: "UFC RESUME", text: "Stipe Miocic's UFC-only résumé", rating: 89, status: "approved" },
  { id: "wl-ufc-resume-044", category: "UFC RESUME", text: "Demetrious Johnson's UFC-only résumé", rating: 95, status: "approved" },
  { id: "wl-ufc-resume-045", category: "UFC RESUME", text: "Khabib Nurmagomedov's UFC-only résumé", rating: 94, status: "approved" },
  { id: "wl-ufc-resume-046", category: "UFC RESUME", text: "Tony Ferguson's UFC-only résumé", rating: 75, status: "approved" },
  { id: "wl-ufc-resume-047", category: "UFC RESUME", text: "Donald Cerrone's UFC-only résumé", rating: 73, status: "approved" },
  { id: "wl-ufc-resume-048", category: "UFC RESUME", text: "Jorge Masvidal's UFC-only résumé", rating: 61, status: "approved" },
  { id: "wl-ufc-resume-049", category: "UFC RESUME", text: "Colby Covington's UFC-only résumé", rating: 64, status: "approved" },
  { id: "wl-ufc-resume-050", category: "UFC RESUME", text: "Belal Muhammad's UFC-only résumé through winning the belt", rating: 78, status: "approved" },
  { id: "wl-championship-051", category: "CHAMPIONSHIP", text: "A short-notice replacement title shot as pure merit", rating: 24, status: "approved" },
  { id: "wl-championship-052", category: "CHAMPIONSHIP", text: "A typical interim belt's historical clarity", rating: 43, status: "approved" },
  { id: "wl-championship-053", category: "CHAMPIONSHIP", text: "The BMF belt's championship meaning", rating: 47, status: "approved" },
  { id: "wl-championship-054", category: "CHAMPIONSHIP", text: "Chael Sonnen's UFC championship résumé", rating: 48, status: "approved" },
  { id: "wl-championship-055", category: "CHAMPIONSHIP", text: "Jorge Masvidal's UFC championship résumé", rating: 45, status: "approved" },
  { id: "wl-championship-056", category: "CHAMPIONSHIP", text: "Dustin Poirier's UFC championship résumé", rating: 63, status: "approved" },
  { id: "wl-championship-057", category: "CHAMPIONSHIP", text: "Colby Covington's UFC championship credibility", rating: 57, status: "approved" },
  { id: "wl-championship-058", category: "CHAMPIONSHIP", text: "Robert Whittaker's championship résumé", rating: 78, status: "approved" },
  { id: "wl-championship-059", category: "CHAMPIONSHIP", text: "Petr Yan's championship résumé", rating: 73, status: "approved" },
  { id: "wl-championship-060", category: "CHAMPIONSHIP", text: "Tyron Woodley's championship résumé", rating: 80, status: "approved" },
  { id: "wl-championship-061", category: "CHAMPIONSHIP", text: "Stipe Miocic's heavyweight championship résumé", rating: 91, status: "approved" },
  { id: "wl-championship-062", category: "CHAMPIONSHIP", text: "Amanda Nunes's two-division championship résumé", rating: 98, status: "approved" },
  { id: "wl-championship-063", category: "CHAMPIONSHIP", text: "Georges St-Pierre's championship résumé", rating: 99, status: "approved" },
  { id: "wl-championship-064", category: "CHAMPIONSHIP", text: "Jon Jones's light-heavyweight championship résumé", rating: 99, status: "approved" },
  { id: "wl-championship-065", category: "CHAMPIONSHIP", text: "Anderson Silva's middleweight title reign", rating: 98, status: "approved" },
  { id: "wl-championship-066", category: "CHAMPIONSHIP", text: "Demetrious Johnson's flyweight title reign", rating: 97, status: "approved" },
  { id: "wl-championship-067", category: "CHAMPIONSHIP", text: "Ronda Rousey's bantamweight title reign", rating: 91, status: "approved" },
  { id: "wl-championship-068", category: "CHAMPIONSHIP", text: "Jose Aldo's featherweight UFC title reign", rating: 92, status: "approved" },
  { id: "wl-championship-069", category: "CHAMPIONSHIP", text: "Khabib Nurmagomedov's lightweight title reign", rating: 88, status: "approved" },
  { id: "wl-championship-070", category: "CHAMPIONSHIP", text: "Kamaru Usman's welterweight title reign", rating: 90, status: "approved" },
  { id: "wl-championship-071", category: "CHAMPIONSHIP", text: "Israel Adesanya's middleweight title reign", rating: 86, status: "approved" },
  { id: "wl-championship-072", category: "CHAMPIONSHIP", text: "Alexander Volkanovski's featherweight title reign", rating: 91, status: "approved" },
  { id: "wl-championship-073", category: "CHAMPIONSHIP", text: "Valentina Shevchenko's flyweight title reign", rating: 93, status: "approved" },
  { id: "wl-championship-074", category: "CHAMPIONSHIP", text: "Charles Oliveira's lightweight title claim", rating: 82, status: "approved" },
  { id: "wl-championship-075", category: "CHAMPIONSHIP", text: "Alex Pereira's two-division UFC title achievement", rating: 89, status: "approved" },
  { id: "wl-ufc-culture-076", category: "UFC CULTURE", text: "UFC hot-dog-branding era aesthetics", rating: 16, status: "approved" },
  { id: "wl-ufc-culture-077", category: "UFC CULTURE", text: "The Reebok fight-kit reveal as fan excitement", rating: 22, status: "approved" },
  { id: "wl-ufc-culture-078", category: "UFC CULTURE", text: "Dana White's press-conference transparency", rating: 26, status: "approved" },
  { id: "wl-ufc-culture-079", category: "UFC CULTURE", text: "The official rankings as argument-enders", rating: 34, status: "approved" },
  { id: "wl-ufc-culture-080", category: "UFC CULTURE", text: "Generic face-off shoving as promotion", rating: 41, status: "approved" },
  { id: "wl-ufc-culture-081", category: "UFC CULTURE", text: "The BMF belt as sporting clarity", rating: 45, status: "approved" },
  { id: "wl-ufc-culture-082", category: "UFC CULTURE", text: "The BMF belt as entertainment", rating: 72, status: "approved" },
  { id: "wl-ufc-culture-083", category: "UFC CULTURE", text: "The Korean Zombie nickname", rating: 86, status: "approved" },
  { id: "wl-ufc-culture-084", category: "UFC CULTURE", text: "Bruce Buffer's catchphrase", rating: 88, status: "approved" },
  { id: "wl-ufc-culture-085", category: "UFC CULTURE", text: "Joe Rogan reaction memes as UFC culture", rating: 79, status: "approved" },
  { id: "wl-ufc-culture-086", category: "UFC CULTURE", text: "UFC Embedded as weekly habit", rating: 70, status: "approved" },
  { id: "wl-ufc-culture-087", category: "UFC CULTURE", text: "The Ultimate Fighter's modern relevance", rating: 64, status: "approved" },
  { id: "wl-ufc-culture-088", category: "UFC CULTURE", text: "International Fight Week as a fan week", rating: 76, status: "approved" },
  { id: "wl-ufc-culture-089", category: "UFC CULTURE", text: "Octagon interviews after wild finishes", rating: 82, status: "approved" },
  { id: "wl-ufc-culture-090", category: "UFC CULTURE", text: "The black-and-gold UFC 300 branding", rating: 78, status: "approved" },
  { id: "wl-ufc-culture-091", category: "UFC CULTURE", text: "Ceremonial weigh-in stare-downs", rating: 74, status: "approved" },
  { id: "wl-ufc-culture-092", category: "UFC CULTURE", text: "Walkout flags as atmosphere", rating: 69, status: "approved" },
  { id: "wl-ufc-culture-093", category: "UFC CULTURE", text: "Coach cam advice between rounds", rating: 58, status: "approved" },
  { id: "wl-ufc-culture-094", category: "UFC CULTURE", text: "Power Slap overlap with UFC credibility", rating: 18, status: "approved" },
  { id: "wl-ufc-culture-095", category: "UFC CULTURE", text: "Crypto sponsor patches as visual charm", rating: 20, status: "approved" },
  { id: "wl-ufc-culture-096", category: "UFC CULTURE", text: "A fighter missing weight by one pound as professionalism", rating: 12, status: "approved" },
  { id: "wl-ufc-culture-097", category: "UFC CULTURE", text: "Championship double-champ photos", rating: 84, status: "approved" },
  { id: "wl-ufc-culture-098", category: "UFC CULTURE", text: "Custom shorts returning for stars", rating: 71, status: "approved" },
  { id: "wl-ufc-culture-099", category: "UFC CULTURE", text: "Old-school gladiator intro nostalgia", rating: 67, status: "approved" },
  { id: "wl-ufc-culture-100", category: "UFC CULTURE", text: "The red UFC gloves reveal as product excitement", rating: 62, status: "approved" },
  { id: "wl-events-and-fights-101", category: "EVENTS & FIGHTS", text: "A forgettable Apex prelim card's rewatch value", rating: 18, status: "approved" },
  { id: "wl-events-and-fights-102", category: "EVENTS & FIGHTS", text: "A sloppy heavyweight gas-out fight's technical value", rating: 25, status: "approved" },
  { id: "wl-events-and-fights-103", category: "EVENTS & FIGHTS", text: "A typical ranked Fight Night main event", rating: 58, status: "approved" },
  { id: "wl-events-and-fights-104", category: "EVENTS & FIGHTS", text: "A strong pay-per-view co-main event", rating: 74, status: "approved" },
  { id: "wl-events-and-fights-105", category: "EVENTS & FIGHTS", text: "UFC 100's historical importance", rating: 91, status: "approved" },
  { id: "wl-events-and-fights-106", category: "EVENTS & FIGHTS", text: "UFC 205's historical importance", rating: 88, status: "approved" },
  { id: "wl-events-and-fights-107", category: "EVENTS & FIGHTS", text: "UFC 229's event atmosphere", rating: 92, status: "approved" },
  { id: "wl-events-and-fights-108", category: "EVENTS & FIGHTS", text: "UFC 300's card depth", rating: 90, status: "approved" },
  { id: "wl-events-and-fights-109", category: "EVENTS & FIGHTS", text: "McGregor vs Aldo's historical importance", rating: 96, status: "approved" },
  { id: "wl-events-and-fights-110", category: "EVENTS & FIGHTS", text: "Jones vs Gustafsson I's historical value", rating: 89, status: "approved" },
  { id: "wl-events-and-fights-111", category: "EVENTS & FIGHTS", text: "Zhang Weili vs Joanna Jędrzejczyk I's rewatchability", rating: 95, status: "approved" },
  { id: "wl-events-and-fights-112", category: "EVENTS & FIGHTS", text: "Lawler vs MacDonald II's rewatchability", rating: 96, status: "approved" },
  { id: "wl-events-and-fights-113", category: "EVENTS & FIGHTS", text: "Griffin vs Bonnar I's UFC importance", rating: 94, status: "approved" },
  { id: "wl-events-and-fights-114", category: "EVENTS & FIGHTS", text: "Holloway vs Kattar's showcase value", rating: 86, status: "approved" },
  { id: "wl-events-and-fights-115", category: "EVENTS & FIGHTS", text: "Usman vs Covington I's action quality", rating: 85, status: "approved" },
  { id: "wl-events-and-fights-116", category: "EVENTS & FIGHTS", text: "Poirier vs Gaethje I's violence-to-skill balance", rating: 87, status: "approved" },
  { id: "wl-events-and-fights-117", category: "EVENTS & FIGHTS", text: "Adesanya vs Romero's entertainment value", rating: 22, status: "approved" },
  { id: "wl-events-and-fights-118", category: "EVENTS & FIGHTS", text: "Ngannou vs Lewis's entertainment value", rating: 10, status: "approved" },
  { id: "wl-events-and-fights-119", category: "EVENTS & FIGHTS", text: "Shevchenko vs Eye's finish memorability", rating: 82, status: "approved" },
  { id: "wl-events-and-fights-120", category: "EVENTS & FIGHTS", text: "Edwards vs Usman II's comeback drama", rating: 93, status: "approved" },
  { id: "wl-events-and-fights-121", category: "EVENTS & FIGHTS", text: "Pereira vs Adesanya II's narrative payoff", rating: 90, status: "approved" },
  { id: "wl-events-and-fights-122", category: "EVENTS & FIGHTS", text: "Oliveira vs Chandler's chaos level", rating: 88, status: "approved" },
  { id: "wl-events-and-fights-123", category: "EVENTS & FIGHTS", text: "Masvidal vs Askren's finish memorability", rating: 94, status: "approved" },
  { id: "wl-events-and-fights-124", category: "EVENTS & FIGHTS", text: "Rousey vs Holm's upset shock", rating: 95, status: "approved" },
  { id: "wl-events-and-fights-125", category: "EVENTS & FIGHTS", text: "Nunes vs Cyborg's historical shock", rating: 93, status: "approved" },
  { id: "wl-venue-and-atmosphere-126", category: "VENUE & ATMOSPHERE", text: "The UFC Apex as a live crowd atmosphere", rating: 5, status: "approved" },
  { id: "wl-venue-and-atmosphere-127", category: "VENUE & ATMOSPHERE", text: "The UFC Apex as a fan travel destination", rating: 20, status: "approved" },
  { id: "wl-venue-and-atmosphere-128", category: "VENUE & ATMOSPHERE", text: "An empty-arena Apex walkout atmosphere", rating: 18, status: "approved" },
  { id: "wl-venue-and-atmosphere-129", category: "VENUE & ATMOSPHERE", text: "A small quiet Fight Night crowd", rating: 36, status: "approved" },
  { id: "wl-venue-and-atmosphere-130", category: "VENUE & ATMOSPHERE", text: "A typical Las Vegas pay-per-view crowd", rating: 68, status: "approved" },
  { id: "wl-venue-and-atmosphere-131", category: "VENUE & ATMOSPHERE", text: "Madison Square Garden as a UFC venue", rating: 86, status: "approved" },
  { id: "wl-venue-and-atmosphere-132", category: "VENUE & ATMOSPHERE", text: "A major London UFC crowd", rating: 84, status: "approved" },
  { id: "wl-venue-and-atmosphere-133", category: "VENUE & ATMOSPHERE", text: "A packed Brazil UFC crowd", rating: 88, status: "approved" },
  { id: "wl-venue-and-atmosphere-134", category: "VENUE & ATMOSPHERE", text: "A packed Mexico City UFC crowd", rating: 86, status: "approved" },
  { id: "wl-venue-and-atmosphere-135", category: "VENUE & ATMOSPHERE", text: "Abu Dhabi as a UFC location", rating: 76, status: "approved" },
  { id: "wl-venue-and-atmosphere-136", category: "VENUE & ATMOSPHERE", text: "Fight Island's visual presentation", rating: 75, status: "approved" },
  { id: "wl-venue-and-atmosphere-137", category: "VENUE & ATMOSPHERE", text: "T-Mobile Arena for a major title fight", rating: 82, status: "approved" },
  { id: "wl-venue-and-atmosphere-138", category: "VENUE & ATMOSPHERE", text: "Boston as a UFC crowd", rating: 78, status: "approved" },
  { id: "wl-venue-and-atmosphere-139", category: "VENUE & ATMOSPHERE", text: "Toronto as a UFC pay-per-view market", rating: 74, status: "approved" },
  { id: "wl-venue-and-atmosphere-140", category: "VENUE & ATMOSPHERE", text: "Australia as a UFC pay-per-view atmosphere", rating: 85, status: "approved" },
  { id: "wl-venue-and-atmosphere-141", category: "VENUE & ATMOSPHERE", text: "Paris as a newer UFC atmosphere", rating: 80, status: "approved" },
  { id: "wl-venue-and-atmosphere-142", category: "VENUE & ATMOSPHERE", text: "Apex contender-series atmosphere", rating: 28, status: "approved" },
  { id: "wl-venue-and-atmosphere-143", category: "VENUE & ATMOSPHERE", text: "Outdoor UFC event atmosphere as a concept", rating: 57, status: "approved" },
  { id: "wl-venue-and-atmosphere-144", category: "VENUE & ATMOSPHERE", text: "International Fight Week ceremonial weigh-ins", rating: 79, status: "approved" },
  { id: "wl-venue-and-atmosphere-145", category: "VENUE & ATMOSPHERE", text: "UFC 229 weigh-in atmosphere", rating: 91, status: "approved" },
  { id: "wl-venue-and-atmosphere-146", category: "VENUE & ATMOSPHERE", text: "UFC 205 MSG atmosphere", rating: 90, status: "approved" },
  { id: "wl-venue-and-atmosphere-147", category: "VENUE & ATMOSPHERE", text: "UFC 193 Melbourne scale", rating: 92, status: "approved" },
  { id: "wl-venue-and-atmosphere-148", category: "VENUE & ATMOSPHERE", text: "UFC 189 Las Vegas atmosphere", rating: 93, status: "approved" },
  { id: "wl-venue-and-atmosphere-149", category: "VENUE & ATMOSPHERE", text: "A half-empty early prelim arena", rating: 24, status: "approved" },
  { id: "wl-venue-and-atmosphere-150", category: "VENUE & ATMOSPHERE", text: "A last-minute venue change's fan experience", rating: 15, status: "approved" },
  { id: "wl-personality-and-promotion-151", category: "PERSONALITY & PROMOTION", text: "A monotone media-day answer as promotion", rating: 22, status: "approved" },
  { id: "wl-personality-and-promotion-152", category: "PERSONALITY & PROMOTION", text: "Hasbulla's UFC product relevance", rating: 25, status: "approved" },
  { id: "wl-personality-and-promotion-153", category: "PERSONALITY & PROMOTION", text: "Tito Ortiz's public speaking", rating: 29, status: "approved" },
  { id: "wl-personality-and-promotion-154", category: "PERSONALITY & PROMOTION", text: "Colby Covington's trash talk originality", rating: 46, status: "approved" },
  { id: "wl-personality-and-promotion-155", category: "PERSONALITY & PROMOTION", text: "Chael Sonnen's trash talk craft", rating: 88, status: "approved" },
  { id: "wl-personality-and-promotion-156", category: "PERSONALITY & PROMOTION", text: "Conor McGregor's promotional impact", rating: 99, status: "approved" },
  { id: "wl-personality-and-promotion-157", category: "PERSONALITY & PROMOTION", text: "Nate Diaz's authenticity", rating: 87, status: "approved" },
  { id: "wl-personality-and-promotion-158", category: "PERSONALITY & PROMOTION", text: "Sean Strickland's press-conference filter", rating: 40, status: "approved" },
  { id: "wl-personality-and-promotion-159", category: "PERSONALITY & PROMOTION", text: "Israel Adesanya's walkout creativity", rating: 83, status: "approved" },
  { id: "wl-personality-and-promotion-160", category: "PERSONALITY & PROMOTION", text: "Alex Pereira's silent-star aura", rating: 90, status: "approved" },
  { id: "wl-personality-and-promotion-161", category: "PERSONALITY & PROMOTION", text: "Paddy Pimblett's crowd connection", rating: 72, status: "approved" },
  { id: "wl-personality-and-promotion-162", category: "PERSONALITY & PROMOTION", text: "Khamzat Chimaev's menace as promotion", rating: 80, status: "approved" },
  { id: "wl-personality-and-promotion-163", category: "PERSONALITY & PROMOTION", text: "Jorge Masvidal's 2019 star surge", rating: 84, status: "approved" },
  { id: "wl-personality-and-promotion-164", category: "PERSONALITY & PROMOTION", text: "Ronda Rousey's crossover star power", rating: 95, status: "approved" },
  { id: "wl-personality-and-promotion-165", category: "PERSONALITY & PROMOTION", text: "Brock Lesnar's UFC star power", rating: 93, status: "approved" },
  { id: "wl-personality-and-promotion-166", category: "PERSONALITY & PROMOTION", text: "Jon Anik's professionalism as broadcast glue", rating: 85, status: "approved" },
  { id: "wl-personality-and-promotion-167", category: "PERSONALITY & PROMOTION", text: "Daniel Cormier's desk chemistry", rating: 78, status: "approved" },
  { id: "wl-personality-and-promotion-168", category: "PERSONALITY & PROMOTION", text: "Michael Bisping's analyst personality", rating: 76, status: "approved" },
  { id: "wl-personality-and-promotion-169", category: "PERSONALITY & PROMOTION", text: "Laura Sanko's broadcast credibility", rating: 77, status: "approved" },
  { id: "wl-personality-and-promotion-170", category: "PERSONALITY & PROMOTION", text: "Derrick Lewis's post-fight interview value", rating: 89, status: "approved" },
  { id: "wl-personality-and-promotion-171", category: "PERSONALITY & PROMOTION", text: "Paulo Costa's meme value", rating: 70, status: "approved" },
  { id: "wl-personality-and-promotion-172", category: "PERSONALITY & PROMOTION", text: "Tony Ferguson's unpredictable quote value", rating: 75, status: "approved" },
  { id: "wl-personality-and-promotion-173", category: "PERSONALITY & PROMOTION", text: "Dustin Poirier's likability", rating: 82, status: "approved" },
  { id: "wl-personality-and-promotion-174", category: "PERSONALITY & PROMOTION", text: "Max Holloway's fan connection", rating: 86, status: "approved" },
  { id: "wl-personality-and-promotion-175", category: "PERSONALITY & PROMOTION", text: "Amanda Nunes's self-promotion volume", rating: 55, status: "approved" },
  { id: "wl-broadcast-and-presentation-176", category: "BROADCAST & PRESENTATION", text: "A generic modern UFC poster", rating: 38, status: "approved" },
  { id: "wl-broadcast-and-presentation-177", category: "BROADCAST & PRESENTATION", text: "The Reebok era visual identity", rating: 33, status: "approved" },
  { id: "wl-broadcast-and-presentation-178", category: "BROADCAST & PRESENTATION", text: "Crypto-heavy canvas ads as presentation", rating: 24, status: "approved" },
  { id: "wl-broadcast-and-presentation-179", category: "BROADCAST & PRESENTATION", text: "UFC countdown shows for a weak card", rating: 45, status: "approved" },
  { id: "wl-broadcast-and-presentation-180", category: "BROADCAST & PRESENTATION", text: "UFC Embedded for a major title card", rating: 78, status: "approved" },
  { id: "wl-broadcast-and-presentation-181", category: "BROADCAST & PRESENTATION", text: "Jon Anik's play-by-play", rating: 86, status: "approved" },
  { id: "wl-broadcast-and-presentation-182", category: "BROADCAST & PRESENTATION", text: "Joe Rogan's technical commentary in his prime", rating: 82, status: "approved" },
  { id: "wl-broadcast-and-presentation-183", category: "BROADCAST & PRESENTATION", text: "Dominick Cruz's commentary accessibility", rating: 66, status: "approved" },
  { id: "wl-broadcast-and-presentation-184", category: "BROADCAST & PRESENTATION", text: "Daniel Cormier's analyst desk work", rating: 80, status: "approved" },
  { id: "wl-broadcast-and-presentation-185", category: "BROADCAST & PRESENTATION", text: "Laura Sanko's commentary upside", rating: 79, status: "approved" },
  { id: "wl-broadcast-and-presentation-186", category: "BROADCAST & PRESENTATION", text: "Megan Olivi's interviews", rating: 83, status: "approved" },
  { id: "wl-broadcast-and-presentation-187", category: "BROADCAST & PRESENTATION", text: "Bruce Buffer introductions for a title fight", rating: 92, status: "approved" },
  { id: "wl-broadcast-and-presentation-188", category: "BROADCAST & PRESENTATION", text: "The old gladiator intro's nostalgia", rating: 73, status: "approved" },
  { id: "wl-broadcast-and-presentation-189", category: "BROADCAST & PRESENTATION", text: "Modern UFC broadcast pacing", rating: 62, status: "approved" },
  { id: "wl-broadcast-and-presentation-190", category: "BROADCAST & PRESENTATION", text: "Instant replay clarity for fouls", rating: 49, status: "approved" },
  { id: "wl-broadcast-and-presentation-191", category: "BROADCAST & PRESENTATION", text: "Judges' scorecard graphics after decisions", rating: 57, status: "approved" },
  { id: "wl-broadcast-and-presentation-192", category: "BROADCAST & PRESENTATION", text: "The Tale of the Tape as useful context", rating: 68, status: "approved" },
  { id: "wl-broadcast-and-presentation-193", category: "BROADCAST & PRESENTATION", text: "Slow-motion finish replays", rating: 84, status: "approved" },
  { id: "wl-broadcast-and-presentation-194", category: "BROADCAST & PRESENTATION", text: "Octagon-side coach audio", rating: 61, status: "approved" },
  { id: "wl-broadcast-and-presentation-195", category: "BROADCAST & PRESENTATION", text: "Apex broadcast sound mix", rating: 44, status: "approved" },
  { id: "wl-broadcast-and-presentation-196", category: "BROADCAST & PRESENTATION", text: "Pay-per-view price value for a thin card", rating: 18, status: "approved" },
  { id: "wl-broadcast-and-presentation-197", category: "BROADCAST & PRESENTATION", text: "Pay-per-view price value for UFC 300", rating: 74, status: "approved" },
  { id: "wl-broadcast-and-presentation-198", category: "BROADCAST & PRESENTATION", text: "UFC Fight Pass archive value", rating: 81, status: "approved" },
  { id: "wl-broadcast-and-presentation-199", category: "BROADCAST & PRESENTATION", text: "Contender Series production polish", rating: 59, status: "approved" },
  { id: "wl-broadcast-and-presentation-200", category: "BROADCAST & PRESENTATION", text: "Road to UFC presentation", rating: 56, status: "approved" },
  { id: "wl-officiating-and-systems-201", category: "OFFICIATING & SYSTEMS", text: "Judging a close split decision as fan certainty", rating: 21, status: "approved" },
  { id: "wl-officiating-and-systems-202", category: "OFFICIATING & SYSTEMS", text: "UFC judging consistency as a whole", rating: 38, status: "approved" },
  { id: "wl-officiating-and-systems-203", category: "OFFICIATING & SYSTEMS", text: "Open scoring for UFC drama", rating: 52, status: "approved" },
  { id: "wl-officiating-and-systems-204", category: "OFFICIATING & SYSTEMS", text: "Herb Dean's overall refereeing reputation", rating: 72, status: "approved" },
  { id: "wl-officiating-and-systems-205", category: "OFFICIATING & SYSTEMS", text: "Marc Goddard's command of high-stakes fights", rating: 82, status: "approved" },
  { id: "wl-officiating-and-systems-206", category: "OFFICIATING & SYSTEMS", text: "Jason Herzog's refereeing reputation", rating: 86, status: "approved" },
  { id: "wl-officiating-and-systems-207", category: "OFFICIATING & SYSTEMS", text: "Late stoppages as fighter safety", rating: 12, status: "approved" },
  { id: "wl-officiating-and-systems-208", category: "OFFICIATING & SYSTEMS", text: "Early stoppages as fan satisfaction", rating: 28, status: "approved" },
  { id: "wl-officiating-and-systems-209", category: "OFFICIATING & SYSTEMS", text: "Instant replay implementation consistency", rating: 44, status: "approved" },
  { id: "wl-officiating-and-systems-210", category: "OFFICIATING & SYSTEMS", text: "The official rankings' usefulness", rating: 40, status: "approved" },
  { id: "wl-officiating-and-systems-211", category: "OFFICIATING & SYSTEMS", text: "Title-shot meritocracy in modern UFC", rating: 47, status: "approved" },
  { id: "wl-officiating-and-systems-212", category: "OFFICIATING & SYSTEMS", text: "Rematch frequency as sporting freshness", rating: 43, status: "approved" },
  { id: "wl-officiating-and-systems-213", category: "OFFICIATING & SYSTEMS", text: "Weight-miss penalties as deterrence", rating: 36, status: "approved" },
  { id: "wl-officiating-and-systems-214", category: "OFFICIATING & SYSTEMS", text: "Athletic commission consistency across states", rating: 39, status: "approved" },
  { id: "wl-officiating-and-systems-215", category: "OFFICIATING & SYSTEMS", text: "UFC Hall of Fame selection consistency", rating: 55, status: "approved" },
  { id: "wl-officiating-and-systems-216", category: "OFFICIATING & SYSTEMS", text: "Performance bonuses as motivation", rating: 76, status: "approved" },
  { id: "wl-officiating-and-systems-217", category: "OFFICIATING & SYSTEMS", text: "Post-fight bonus transparency", rating: 58, status: "approved" },
  { id: "wl-officiating-and-systems-218", category: "OFFICIATING & SYSTEMS", text: "Five-round non-title main events", rating: 77, status: "approved" },
  { id: "wl-officiating-and-systems-219", category: "OFFICIATING & SYSTEMS", text: "Three-round elite contender fights", rating: 54, status: "approved" },
  { id: "wl-officiating-and-systems-220", category: "OFFICIATING & SYSTEMS", text: "Interim belts during clear injuries", rating: 61, status: "approved" },
  { id: "wl-officiating-and-systems-221", category: "OFFICIATING & SYSTEMS", text: "Interim belts during short business delays", rating: 32, status: "approved" },
  { id: "wl-officiating-and-systems-222", category: "OFFICIATING & SYSTEMS", text: "Dana White contender-series contracts as opportunity", rating: 68, status: "approved" },
  { id: "wl-officiating-and-systems-223", category: "OFFICIATING & SYSTEMS", text: "Regional judging variance as trust builder", rating: 19, status: "approved" },
  { id: "wl-officiating-and-systems-224", category: "OFFICIATING & SYSTEMS", text: "Fence grabs enforcement consistency", rating: 31, status: "approved" },
  { id: "wl-officiating-and-systems-225", category: "OFFICIATING & SYSTEMS", text: "Eye-poke deterrence under current gloves", rating: 27, status: "approved" },
  { id: "wl-legacy-and-history-226", category: "LEGACY & HISTORY", text: "Greg Hardy's UFC legacy", rating: 9, status: "approved" },
  { id: "wl-legacy-and-history-227", category: "LEGACY & HISTORY", text: "Sage Northcutt's UFC legacy", rating: 34, status: "approved" },
  { id: "wl-legacy-and-history-228", category: "LEGACY & HISTORY", text: "Tito Ortiz's relevance to modern UFC fans", rating: 48, status: "approved" },
  { id: "wl-legacy-and-history-229", category: "LEGACY & HISTORY", text: "The Ultimate Fighter's importance to UFC growth", rating: 90, status: "approved" },
  { id: "wl-legacy-and-history-230", category: "LEGACY & HISTORY", text: "Forrest Griffin's UFC historical importance", rating: 82, status: "approved" },
  { id: "wl-legacy-and-history-231", category: "LEGACY & HISTORY", text: "Stephan Bonnar's UFC historical importance", rating: 78, status: "approved" },
  { id: "wl-legacy-and-history-232", category: "LEGACY & HISTORY", text: "Chuck Liddell's UFC legacy", rating: 91, status: "approved" },
  { id: "wl-legacy-and-history-233", category: "LEGACY & HISTORY", text: "Randy Couture's UFC legacy", rating: 88, status: "approved" },
  { id: "wl-legacy-and-history-234", category: "LEGACY & HISTORY", text: "BJ Penn's UFC legacy", rating: 84, status: "approved" },
  { id: "wl-legacy-and-history-235", category: "LEGACY & HISTORY", text: "Georges St-Pierre's UFC legacy", rating: 99, status: "approved" },
  { id: "wl-legacy-and-history-236", category: "LEGACY & HISTORY", text: "Anderson Silva's UFC legacy", rating: 98, status: "approved" },
  { id: "wl-legacy-and-history-237", category: "LEGACY & HISTORY", text: "Jon Jones's UFC legacy", rating: 97, status: "approved" },
  { id: "wl-legacy-and-history-238", category: "LEGACY & HISTORY", text: "Amanda Nunes's UFC legacy", rating: 96, status: "approved" },
  { id: "wl-legacy-and-history-239", category: "LEGACY & HISTORY", text: "Ronda Rousey's UFC legacy", rating: 95, status: "approved" },
  { id: "wl-legacy-and-history-240", category: "LEGACY & HISTORY", text: "Conor McGregor's UFC legacy", rating: 94, status: "approved" },
  { id: "wl-legacy-and-history-241", category: "LEGACY & HISTORY", text: "Khabib Nurmagomedov's UFC legacy", rating: 93, status: "approved" },
  { id: "wl-legacy-and-history-242", category: "LEGACY & HISTORY", text: "Jose Aldo's UFC legacy", rating: 92, status: "approved" },
  { id: "wl-legacy-and-history-243", category: "LEGACY & HISTORY", text: "Demetrious Johnson's UFC legacy", rating: 91, status: "approved" },
  { id: "wl-legacy-and-history-244", category: "LEGACY & HISTORY", text: "Daniel Cormier's UFC legacy", rating: 88, status: "approved" },
  { id: "wl-legacy-and-history-245", category: "LEGACY & HISTORY", text: "Kamaru Usman's UFC legacy", rating: 86, status: "approved" },
  { id: "wl-legacy-and-history-246", category: "LEGACY & HISTORY", text: "Israel Adesanya's UFC legacy", rating: 87, status: "approved" },
  { id: "wl-legacy-and-history-247", category: "LEGACY & HISTORY", text: "Valentina Shevchenko's UFC legacy", rating: 89, status: "approved" },
  { id: "wl-legacy-and-history-248", category: "LEGACY & HISTORY", text: "Max Holloway's UFC legacy", rating: 86, status: "approved" },
  { id: "wl-legacy-and-history-249", category: "LEGACY & HISTORY", text: "Dustin Poirier's UFC legacy", rating: 80, status: "approved" },
  { id: "wl-legacy-and-history-250", category: "LEGACY & HISTORY", text: "Donald Cerrone's UFC legacy", rating: 75, status: "approved" },
  { id: "wl-fighter-trait-251", category: "FIGHTER TRAIT", text: "An average heavyweight's five-round cardio", rating: 17, status: "approved" },
  { id: "wl-fighter-trait-252", category: "FIGHTER TRAIT", text: "Michael Chandler's ability to follow a calm game plan", rating: 35, status: "approved" },
  { id: "wl-fighter-trait-253", category: "FIGHTER TRAIT", text: "Tony Ferguson's late-career durability", rating: 24, status: "approved" },
  { id: "wl-fighter-trait-254", category: "FIGHTER TRAIT", text: "Max Holloway's chin", rating: 94, status: "approved" },
  { id: "wl-fighter-trait-255", category: "FIGHTER TRAIT", text: "Justin Gaethje's willingness to create chaos", rating: 91, status: "approved" },
  { id: "wl-fighter-trait-256", category: "FIGHTER TRAIT", text: "Dustin Poirier's mid-fight composure", rating: 84, status: "approved" },
  { id: "wl-fighter-trait-257", category: "FIGHTER TRAIT", text: "Charles Oliveira's recovery after being hurt", rating: 88, status: "approved" },
  { id: "wl-fighter-trait-258", category: "FIGHTER TRAIT", text: "Kamaru Usman's clinch strength", rating: 86, status: "approved" },
  { id: "wl-fighter-trait-259", category: "FIGHTER TRAIT", text: "Leon Edwards's patience", rating: 82, status: "approved" },
  { id: "wl-fighter-trait-260", category: "FIGHTER TRAIT", text: "Alexander Volkanovski's in-fight adjustment", rating: 90, status: "approved" },
  { id: "wl-fighter-trait-261", category: "FIGHTER TRAIT", text: "Brian Ortega's comeback danger", rating: 78, status: "approved" },
  { id: "wl-fighter-trait-262", category: "FIGHTER TRAIT", text: "Nate Diaz's pace over five rounds", rating: 81, status: "approved" },
  { id: "wl-fighter-trait-263", category: "FIGHTER TRAIT", text: "Francis Ngannou's intimidation factor", rating: 95, status: "approved" },
  { id: "wl-fighter-trait-264", category: "FIGHTER TRAIT", text: "Alex Pereira's calm under pressure", rating: 87, status: "approved" },
  { id: "wl-fighter-trait-265", category: "FIGHTER TRAIT", text: "Israel Adesanya's feint discipline", rating: 85, status: "approved" },
  { id: "wl-fighter-trait-266", category: "FIGHTER TRAIT", text: "Robert Whittaker's durability at middleweight", rating: 80, status: "approved" },
  { id: "wl-fighter-trait-267", category: "FIGHTER TRAIT", text: "Paulo Costa's contender reliability", rating: 49, status: "approved" },
  { id: "wl-fighter-trait-268", category: "FIGHTER TRAIT", text: "Kevin Holland's tactical consistency", rating: 50, status: "approved" },
  { id: "wl-fighter-trait-269", category: "FIGHTER TRAIT", text: "Belal Muhammad's pace reliability", rating: 79, status: "approved" },
  { id: "wl-fighter-trait-270", category: "FIGHTER TRAIT", text: "Merab Dvalishvili's cardio pressure", rating: 92, status: "approved" },
  { id: "wl-fighter-trait-271", category: "FIGHTER TRAIT", text: "Ilia Topuria's finishing confidence", rating: 86, status: "approved" },
  { id: "wl-fighter-trait-272", category: "FIGHTER TRAIT", text: "Tom Aspinall's heavyweight athleticism", rating: 89, status: "approved" },
  { id: "wl-fighter-trait-273", category: "FIGHTER TRAIT", text: "Derrick Lewis's comeback threat", rating: 77, status: "approved" },
  { id: "wl-fighter-trait-274", category: "FIGHTER TRAIT", text: "Sean O'Malley's composure in open space", rating: 83, status: "approved" },
  { id: "wl-fighter-trait-275", category: "FIGHTER TRAIT", text: "Aljamain Sterling's backpack control", rating: 84, status: "approved" },
  { id: "wl-goat-and-prime-276", category: "GOAT & PRIME", text: "A fringe contender's UFC GOAT case", rating: 15, status: "approved" },
  { id: "wl-goat-and-prime-277", category: "GOAT & PRIME", text: "A one-defense champion's all-time UFC GOAT case", rating: 42, status: "approved" },
  { id: "wl-goat-and-prime-278", category: "GOAT & PRIME", text: "Tony Ferguson's UFC-only GOAT case", rating: 61, status: "approved" },
  { id: "wl-goat-and-prime-279", category: "GOAT & PRIME", text: "Dustin Poirier's UFC-only GOAT case", rating: 66, status: "approved" },
  { id: "wl-goat-and-prime-280", category: "GOAT & PRIME", text: "Conor McGregor's UFC-only GOAT case", rating: 76, status: "approved" },
  { id: "wl-goat-and-prime-281", category: "GOAT & PRIME", text: "Kamaru Usman's welterweight GOAT case", rating: 88, status: "approved" },
  { id: "wl-goat-and-prime-282", category: "GOAT & PRIME", text: "Stipe Miocic's heavyweight GOAT case", rating: 92, status: "approved" },
  { id: "wl-goat-and-prime-283", category: "GOAT & PRIME", text: "Jose Aldo's featherweight GOAT case", rating: 93, status: "approved" },
  { id: "wl-goat-and-prime-284", category: "GOAT & PRIME", text: "Demetrious Johnson's flyweight GOAT case", rating: 97, status: "approved" },
  { id: "wl-goat-and-prime-285", category: "GOAT & PRIME", text: "Amanda Nunes's women's UFC GOAT case", rating: 98, status: "approved" },
  { id: "wl-goat-and-prime-286", category: "GOAT & PRIME", text: "Georges St-Pierre's UFC GOAT case", rating: 99, status: "approved" },
  { id: "wl-goat-and-prime-287", category: "GOAT & PRIME", text: "Jon Jones's UFC GOAT résumé", rating: 99, status: "approved" },
  { id: "wl-goat-and-prime-288", category: "GOAT & PRIME", text: "Anderson Silva's middleweight GOAT case", rating: 98, status: "approved" },
  { id: "wl-goat-and-prime-289", category: "GOAT & PRIME", text: "Khabib Nurmagomedov's lightweight GOAT case", rating: 94, status: "approved" },
  { id: "wl-goat-and-prime-290", category: "GOAT & PRIME", text: "Valentina Shevchenko's women's flyweight GOAT case", rating: 95, status: "approved" },
  { id: "wl-goat-and-prime-291", category: "GOAT & PRIME", text: "Alexander Volkanovski's featherweight GOAT case", rating: 91, status: "approved" },
  { id: "wl-goat-and-prime-292", category: "GOAT & PRIME", text: "Max Holloway's featherweight GOAT case", rating: 86, status: "approved" },
  { id: "wl-goat-and-prime-293", category: "GOAT & PRIME", text: "Ronda Rousey's women's bantamweight GOAT case", rating: 90, status: "approved" },
  { id: "wl-goat-and-prime-294", category: "GOAT & PRIME", text: "Khabib Nurmagomedov's prime dominance", rating: 97, status: "approved" },
  { id: "wl-goat-and-prime-295", category: "GOAT & PRIME", text: "Anderson Silva's peak aura", rating: 98, status: "approved" },
  { id: "wl-goat-and-prime-296", category: "GOAT & PRIME", text: "Georges St-Pierre's prime completeness", rating: 97, status: "approved" },
  { id: "wl-goat-and-prime-297", category: "GOAT & PRIME", text: "Jon Jones's prime adaptability", rating: 98, status: "approved" },
  { id: "wl-goat-and-prime-298", category: "GOAT & PRIME", text: "Amanda Nunes's prime finishing threat", rating: 96, status: "approved" },
  { id: "wl-goat-and-prime-299", category: "GOAT & PRIME", text: "Jose Aldo's WEC-to-UFC prime", rating: 95, status: "approved" },
  { id: "wl-goat-and-prime-300", category: "GOAT & PRIME", text: "Francis Ngannou's peak heavyweight fear factor", rating: 94, status: "approved" },
  { id: "wl-quarantine-temporary-rank", category: "OFFICIATING & SYSTEMS", text: "This week's pound-for-pound ranking accuracy", rating: 50, status: "quarantined" },
] as const;

export const approvedWavelengthCatalog = wavelengthCatalog.filter((item) => item.status === "approved");
